import { Command } from "commander";
import chalk from "chalk";
import fs from "fs-extra";
import path from "node:path";
import { configExists, readConfig } from "../utils/config.js";
import { detectProject } from "../utils/detect.js";
import { discoverLocalComponents } from "../utils/registry.js";
import { getPresetInfo } from "../utils/presets.js";
import { printIntro, symbols } from "../utils/terminal.js";

export const docsCommand = new Command("docs")
  .description("Generate local Sigil docs, llms.txt, and agent-readable project context")
  .option("-o, --out <dir>", "docs output directory", "docs")
  .option("--llms <path>", "llms.txt output path", "llms.txt")
  .option("--no-llms", "skip llms.txt generation")
  .action(async (opts) => {
    const cwd = process.cwd();
    printIntro("Sigil Docs", "Generate project docs for humans and agents");

    if (!configExists(cwd)) {
      console.log(symbols.error, "No sigil.config.ts found. Run", chalk.cyan("sigil init"), "first.");
      process.exit(1);
    }

    const config = readConfig(cwd)!;
    const detection = detectProject(cwd);
    const preset = getPresetInfo(config.preset);
    const componentsDir = path.join(cwd, config.componentsDir);
    const components = await discoverLocalComponents(componentsDir);
    const tokensPath = path.join(cwd, config.tokensPath);
    const tokenSummary = fs.existsSync(tokensPath) ? summarizeTokens(fs.readFileSync(tokensPath, "utf-8")) : [];

    const docsDir = path.join(cwd, opts.out);
    fs.ensureDirSync(docsDir);
    fs.writeFileSync(
      path.join(docsDir, "sigil-project.md"),
      renderProjectDocs({
        config,
        framework: detection.framework,
        presetDescription: preset?.description,
        presetMood: preset?.mood,
        components,
        tokenSummary,
      }),
      "utf-8",
    );

    if (opts.llms !== false) {
      fs.writeFileSync(
        path.join(cwd, opts.llms),
        renderLlmsTxt({
          config,
          framework: detection.framework,
          presetDescription: preset?.description,
          components,
          tokenSummary,
        }),
        "utf-8",
      );
      console.log(`  ${symbols.success} Wrote ${opts.llms}`);
    }

    console.log(`  ${symbols.success} Wrote ${path.relative(cwd, path.join(docsDir, "sigil-project.md"))}`);
    console.log();
    console.log(chalk.dim("  Re-run after adding components, changing presets, or editing tokens."));
  });

function summarizeTokens(content: string): string[] {
  const lines = content
    .split("\n")
    .map((line) => line.trim())
    .filter((line) => line.startsWith("--s-"))
    .slice(0, 40);

  if (lines.length > 0) return lines;

  return content
    .split("\n")
    .filter((line) => line.includes("@import"))
    .map((line) => line.trim());
}

function renderProjectDocs({
  config,
  framework,
  presetDescription,
  presetMood,
  components,
  tokenSummary,
}: {
  config: NonNullable<ReturnType<typeof readConfig>>;
  framework: string;
  presetDescription?: string;
  presetMood?: string;
  components: string[];
  tokenSummary: string[];
}): string {
  return `# Sigil Project Docs

This document was generated by \`sigil docs\`. It describes the local component library, active preset, token file, and agent workflow.

## Project

| Field | Value |
|-------|-------|
| Framework | ${framework} |
| Active preset | \`${config.preset}\`${presetDescription ? ` — ${presetDescription}` : ""} |
${presetMood ? `| Preset mood | ${presetMood} |\n` : ""}| Components directory | \`${config.componentsDir}\` |
| Tokens file | \`${config.tokensPath}\` |

## Installed Components

${components.length > 0 ? components.map((component) => `- \`${component}\``).join("\n") : "_No copied components found yet. Run `sigil add button card input`._"}

## Token Surface

${tokenSummary.length > 0 ? tokenSummary.map((line) => `- \`${line}\``).join("\n") : "_No token file found or no token variables were detected._"}

## How To Extend

- Change visual identity by editing \`${config.tokensPath}\` or running \`sigil preset <name>\`.
- Add source-owned components with \`sigil add <component>\`.
- Draft a reference-derived token direction with \`sigil inspire <url-or-file> --name <name>\`.
- Generate compatibility variables with \`sigil adapter shadcn\`, \`sigil adapter bootstrap\`, or \`sigil adapter material\`.
`;
}

function renderLlmsTxt({
  config,
  framework,
  presetDescription,
  components,
  tokenSummary,
}: {
  config: NonNullable<ReturnType<typeof readConfig>>;
  framework: string;
  presetDescription?: string;
  components: string[];
  tokenSummary: string[];
}): string {
  return `# Sigil UI Project Context

Framework: ${framework}
Active preset: ${config.preset}${presetDescription ? ` (${presetDescription})` : ""}
Components directory: ${config.componentsDir}
Tokens file: ${config.tokensPath}

## Agent rule

Edit the token file for visual changes. Do not hardcode colors, spacing, radius, shadows, fonts, or motion into components.

## Components

${components.length > 0 ? components.map((component) => `- ${component}`).join("\n") : "- none copied yet"}

## Token imports / overrides

${tokenSummary.length > 0 ? tokenSummary.map((line) => `- ${line}`).join("\n") : "- no token summary available"}

## Useful commands

- sigil add <component>
- sigil preset list
- sigil preset <name>
- sigil inspire <url-or-file> --name <name>
- sigil adapter <shadcn|bootstrap|material>
- sigil docs
- sigil doctor
`;
}
