/**
 * Legacy entry point. The structural grid implementation now lives
 * under `./sigil/` — one file per concern. This shell re-exports the
 * public surface so existing imports keep working.
 */

export {
  getSigilPatternStyles,
  IsInsidePageGridContext,
  PageGridContext,
  SigilFrame,
  SigilFullBleed,
  SigilGutter,
  SigilPage,
  SigilPageGrid,
  SIGIL_RHYTHM_STYLES,
  SigilActionRow,
  SigilGhostLink,
  SigilHero,
  SigilHeroContent,
  SigilHeroDescription,
  SigilHeroLayout,
  SigilHeroMedia,
  SigilHeroTitle,
  SigilInline,
  SigilMonoBlock,
  SigilRhythmBox,
  SigilSectionHeader,
  SigilStack,
  SigilViewCode,
  useIsInsidePageGrid,
  usePageGridConfig,
  type PageGridConfig,
  type PatternSide,
  type SigilBandStroke,
  type SigilFrameProps,
  type SigilFullBleedProps,
  type SigilGutterProps,
  type SigilPageChrome,
  type SigilPageProps,
  type SigilPageGridProps,
  type SigilPatternStyles,
  type SigilRhythmMode,
  type SigilActionRowProps,
  type SigilGhostLinkProps,
  type SigilHeroContentProps,
  type SigilHeroDescriptionProps,
  type SigilHeroLayoutProps,
  type SigilHeroMediaProps,
  type SigilHeroProps,
  type SigilHeroTitleProps,
  type SigilInlineProps,
  type SigilMonoBlockProps,
  type SigilRhythmBoxProps,
  type SigilSectionHeaderProps,
  type SigilStackProps,
  type SigilViewCodeProps,
} from "./sigil";
