import type { SigilTokens } from "./types";

/**
 * Default Sigil token values.
 * All colors are in OKLCH for perceptual uniformity and wide-gamut support.
 * Includes all optional token categories so components work without a preset.
 */
export const defaultTokens: SigilTokens = {
  colors: {
    background: {
      light: "oklch(0.99 0 0)",
      dark: "oklch(0.07 0.01 280)",
    },
    surface: {
      light: "oklch(0.97 0 0)",
      dark: "oklch(0.12 0.01 280)",
    },
    "surface-elevated": {
      light: "oklch(0.98 0 0)",
      dark: "oklch(0.15 0.01 280)",
    },

    primary: "oklch(0.65 0.15 280)",
    "primary-hover": "oklch(0.60 0.18 280)",
    "primary-muted": "oklch(0.90 0.04 280)",
    secondary: "oklch(0.70 0.12 60)",

    text: {
      light: "oklch(0.15 0 0)",
      dark: "oklch(0.93 0 0)",
    },
    "text-secondary": {
      light: "oklch(0.40 0 0)",
      dark: "oklch(0.70 0 0)",
    },
    "text-muted": {
      light: "oklch(0.55 0 0)",
      dark: "oklch(0.45 0 0)",
    },
    "text-subtle": {
      light: "oklch(0.70 0 0)",
      dark: "oklch(0.40 0 0)",
    },
    "text-disabled": {
      light: "oklch(0.80 0 0)",
      dark: "oklch(0.30 0 0)",
    },

    border: {
      light: "oklch(0.90 0 0)",
      dark: "oklch(0.25 0.01 280)",
    },
    "border-muted": {
      light: "oklch(0.94 0 0)",
      dark: "oklch(0.20 0.01 280)",
    },
    "border-strong": {
      light: "oklch(0.80 0 0)",
      dark: "oklch(0.35 0.01 280)",
    },
    "border-interactive": {
      light: "oklch(0.65 0.15 280)",
      dark: "oklch(0.65 0.15 280)",
    },

    success: "oklch(0.65 0.17 160)",
    warning: "oklch(0.75 0.15 85)",
    error: "oklch(0.60 0.20 25)",
    info: "oklch(0.60 0.15 250)",
    highlight: {
      light: "oklch(0.94 0.12 95)",
      dark: "oklch(0.30 0.08 95)",
    },
  },

  typography: {
    "font-display": '"PP Mori", system-ui, sans-serif',
    "font-body": '"PP Mori", system-ui, sans-serif',
    "font-mono": '"PP Fraktion Mono", ui-monospace, monospace',
  },

  spacing: {
    scale: [4, 8, 12, 16, 24, 32, 48, 64, 80, 96],
    unit: "px",
  },

  layout: {
    "content-max": "1200px",
    "content-max-narrow": "768px",
    "content-max-wide": "1440px",
    "page-margin": "25px",
    "page-margin-sm": "16px",
    "page-margin-lg": "50px",
    gutter: "24px",
    "gutter-sm": "16px",
    "gutter-lg": "32px",
    "grid-columns": "12",
    "grid-gap": "24px",
    "bento-gap": "16px",
    "bento-radius": "0px",
    "bento-min-height": "200px",
    "section-gap": "32px",
    "sidebar-width": "280px",
    "sidebar-collapsed": "64px",
    "footer-columns": "4",
    "stack-gap": "16px",
    "stack-gap-sm": "8px",
    "stack-gap-lg": "24px",
    "prose-max": "65ch",
  },

  sigil: {
    "grid-cell": "50px",
    "cross-arm": "10px",
    "cross-stroke": "1.5px",
    "rail-gap": "50px",
    "card-radius": "10px",
    "gutter-pattern": "grid" as const,
    "margin-pattern": "none" as const,
    "gutter-border": "1px solid",
    "margin-border": "none",
    "gutter-visible": true,
  },

  radius: {
    none: "0px",
    sm: "4px",
    md: "8px",
    lg: "12px",
    xl: "16px",
    "2xl": "24px",
    full: "9999px",
  },

  shadows: {
    sm: "0 1px 2px 0 oklch(0 0 0 / 0.05)",
    md: "0 0 0 1px oklch(0 0 0 / 0.06), 0 1px 2px -1px oklch(0 0 0 / 0.06), 0 2px 4px 0 oklch(0 0 0 / 0.04)",
    lg: "0 0 0 1px oklch(0 0 0 / 0.04), 0 2px 4px -2px oklch(0 0 0 / 0.06), 0 4px 8px -2px oklch(0 0 0 / 0.08)",
    xl: "0 0 0 1px oklch(0 0 0 / 0.03), 0 4px 6px -4px oklch(0 0 0 / 0.06), 0 10px 15px -3px oklch(0 0 0 / 0.1), 0 20px 25px -5px oklch(0 0 0 / 0.06)",
  },

  motion: {
    duration: {
      instant: "0ms",
      fast: "150ms",
      normal: "250ms",
      slow: "400ms",
      slower: "600ms",
    },
    easing: {
      default: "cubic-bezier(0.16, 1, 0.3, 1)",
      in: "cubic-bezier(0.55, 0, 1, 0.45)",
      out: "cubic-bezier(0, 0.55, 0.45, 1)",
      "in-out": "cubic-bezier(0.45, 0, 0.55, 1)",
      spring: "cubic-bezier(0.34, 1.56, 0.64, 1)",
    },
  },

  borders: {
    width: {
      none: "0px",
      thin: "1px",
      medium: "1.5px",
      thick: "2px",
    },
  },

  buttons: {
    "font-weight": "500",
    "text-transform": "none" as const,
    "letter-spacing": "0em",
    "font-family": "inherit",
    "border-width": "1px",
    "hover-effect": "darken" as const,
    "active-scale": "0.97",
    "icon-gap": "8px",
    "min-width": "0px",
  },

  cards: {
    "border-style": "solid" as const,
    "border-width": "1px",
    "hover-effect": "border" as const,
    "hover-border-color": "var(--s-border-strong)",
    padding: "24px",
    "header-padding": "24px 24px 0",
    "footer-padding": "0 24px 24px",
    "title-size": "1.125rem",
    "title-weight": "600",
    "description-size": "0.875rem",
    "background": "surface" as const,
    "shadow": "none" as const,
    "outline": true,
    "outline-on-hover-only": false,
    "gap-between": "12px",
    "aspect-ratio": "auto" as const,
    "content-padding-x": "24px",
    "content-padding-y": "16px",
  },

  headings: {
    "h1-size": "2.25rem",
    "h1-weight": "700",
    "h1-tracking": "-0.025em",
    "h1-leading": "1.2",
    "h2-size": "1.875rem",
    "h2-weight": "600",
    "h2-tracking": "-0.02em",
    "h2-leading": "1.15",
    "h3-size": "1.5rem",
    "h3-weight": "600",
    "h3-tracking": "0em",
    "h3-leading": "1.2",
    "h4-size": "1.25rem",
    "h4-weight": "600",
    "h4-tracking": "0em",
    "h4-leading": "1.3",
    "display-size": "3.75rem",
    "display-weight": "700",
    "display-tracking": "-0.03em",
    "display-leading": "1.08",
  },

  navigation: {
    "navbar-height": "50px",
    "navbar-backdrop-blur": "12px",
    "navbar-border": "1px solid",
    "navbar-bg-opacity": "0.8",
    "navbar-padding-x": "25px",
    "navbar-position": "sticky" as const,
    "navbar-logo-height": "24px",
    "navbar-logo-gap": "8px",
    "navbar-item-gap": "24px",
    "navbar-item-padding-x": "12px",
    "navbar-item-padding-y": "6px",
    "navbar-item-size": "0.875rem",
    "navbar-shadow": "none",
    "navbar-height-scrolled": "50px",
    "navbar-mobile-breakpoint": "768px",
    "nav-link-weight": "500",
    "nav-link-size": "0.875rem",
    "nav-link-hover": "color" as const,
    "breadcrumb-separator": "/",
    "pagination-radius": "0px",
    "sidebar-width": "280px",
    "sidebar-item-radius": "0px",
    "sidebar-item-padding": "8px 12px",
  },

  backgrounds: {
    pattern: "none" as const,
    "pattern-opacity": "0.05",
    "pattern-scale": "1",
    noise: false,
    "noise-opacity": "0.03",
    "gradient-angle": "135deg",
    "gradient-type": "none" as const,
    "hero-pattern": "none" as const,
    "section-divider": "none" as const,
  },

  code: {
    "font-family": "var(--s-font-mono)",
    "font-size": "0.875rem",
    "line-height": "1.7",
    bg: "var(--s-surface-sunken, var(--s-surface))",
    border: "1px solid var(--s-border)",
    "border-radius": "0px",
    padding: "16px",
    "tab-size": "2",
    "selection-bg": "var(--s-primary-muted)",
    "comment-color": "var(--s-text-muted)",
    "keyword-color": "var(--s-primary)",
    "string-color": "var(--s-success)",
    "number-color": "var(--s-warning)",
    "function-color": "var(--s-info)",
  },

  inputs: {
    height: "36px",
    "height-sm": "32px",
    "height-lg": "44px",
    "border-width": "1px",
    "focus-ring-width": "2px",
    "focus-ring-color": "var(--s-primary)",
    "focus-ring-offset": "2px",
    "placeholder-color": "var(--s-text-muted)",
    "error-border-color": "var(--s-error)",
    "label-size": "0.875rem",
    "label-weight": "500",
    "label-spacing": "8px",
    "helper-size": "0.8125rem",
  },

  cursor: {
    variant: "sigil",
    size: "28px",
    "dot-size": "4px",
    "stroke-width": "1.5px",
    "tick-size": "7px",
    gap: "3px",
    radius: "var(--s-radius-full)",
    color: "var(--s-primary)",
    "ring-color": "var(--s-primary)",
    "dot-color": "var(--s-primary)",
    glow: "0 0 18px color-mix(in oklch, var(--s-primary) 35%, transparent)",
    opacity: "0.95",
    "blend-mode": "normal",
    "z-index": "2147483647",
    "hide-native": true,
  },

  scrollbar: {
    width: "10px",
    height: "10px",
    padding: "2px",
    radius: "var(--s-radius-full)",
    track: "transparent",
    thumb: "var(--s-border)",
    "thumb-hover": "var(--s-border-strong)",
    "thumb-active": "var(--s-primary)",
    corner: "transparent",
    border: "transparent",
    "firefox-width": "thin",
    gutter: "auto",
    visibility: "auto",
  },

  alignment: {
    "rail-width": "var(--s-content-max, 1200px)",
    "rail-columns": "12",
    "rail-gutter": "24px",
    "rail-margin": "var(--s-page-margin, 24px)",
    "rail-visible": false,
    "rail-color": "var(--s-border-muted)",
    "content-align": "center" as const,
    "hero-align": "center" as const,
    "section-align": "center" as const,
    "navbar-align": "full" as const,
    "footer-align": "content" as const,
    "title-align": "left" as const,
  },

  sections: {
    "padding-y": "100px",
    "padding-y-sm": "48px",
    "padding-y-hero": "120px",
    "padding-y-lg": "120px",
    "padding-y-xl": "160px",
    "padding-x": "var(--s-page-margin, 25px)",
    "max-width": "var(--s-content-max, 1200px)",
    "gap": "24px",
    "title-align": "left" as const,
    "heading-size": "var(--s-h2-size, 1.875rem)",
    "heading-align": "left" as const,
    "heading-max-width": "32rem",
    "heading-margin-bottom": "16px",
    "description-max-width": "32rem",
    "description-gap": "12px",
    "content-gap": "24px",
    "grid-columns": "3",
    "grid-gap": "24px",
    "alternate-bg-mode": "none" as const,
    "divider-above": false,
    "divider-below": false,
    "background-alt": false,
    "indent": "0px",
  },

  dividers: {
    "style": "solid" as const,
    "width": "1px",
    "color": "var(--s-border-muted)",
    "spacing": "0px",
    "opacity": "1",
    "max-width": "100%",
    "margin-y": "0px",
    "gradient-start": "transparent",
    "gradient-end": "transparent",
    "show-cross": false,
    "show-label": false,
    "full-bleed": false,
    "ornament": "none" as const,
  },

  gridVisuals: {
    "show-lines": false,
    "line-color": "var(--s-border-muted)",
    "line-width": "1px",
    "show-dots": false,
    "dot-size": "2px",
    "cell-background": "none" as const,
    "cell-border": false,
    "cell-radius": "0px",
    "cell-padding": "0px",
    "hover-effect": "none" as const,
  },

  focus: {
    "ring-width": "2px",
    "ring-color": "var(--s-primary)",
    "ring-offset": "2px",
    "ring-shadow": "0 0 0 var(--s-focus-ring-width) color-mix(in oklch, var(--s-focus-ring-color) 35%, transparent)",
    "outline-color": "var(--s-border-interactive)",
  },

  overlays: {
    bg: "oklch(0 0 0 / 0.55)",
    blur: "2px",
    surface: "var(--s-surface)",
    border: "var(--s-border)",
    shadow: "var(--s-shadow-xl)",
    radius: "var(--s-card-radius, var(--s-radius-lg))",
    padding: "24px",
    "z-index": "50",
  },

  dataViz: {
    "series-1": "var(--s-primary)",
    "series-2": "var(--s-secondary)",
    "series-3": "var(--s-accent, var(--s-info))",
    "series-4": "var(--s-success)",
    "series-5": "var(--s-warning)",
    positive: "var(--s-success)",
    negative: "var(--s-error)",
    neutral: "var(--s-text-muted)",
    grid: "var(--s-border-muted)",
    axis: "var(--s-border-strong)",
    label: "var(--s-text-secondary)",
    "tooltip-bg": "var(--s-surface-elevated)",
    "tooltip-border": "var(--s-border)",
  },

  media: {
    radius: "var(--s-radius-md)",
    border: "1px solid var(--s-border-muted)",
    outline: "1px solid color-mix(in oklch, var(--s-text) 8%, transparent)",
    shadow: "var(--s-shadow-sm)",
    bg: "var(--s-surface-sunken, var(--s-surface))",
    "object-fit": "cover",
  },

  controls: {
    height: "36px",
    "height-sm": "32px",
    "height-lg": "44px",
    "hit-area": "40px",
    "icon-size": "16px",
    "handle-size": "20px",
    "track-height": "8px",
    "track-bg": "var(--s-surface-sunken, var(--s-surface))",
    "track-fill": "var(--s-primary)",
    "thumb-bg": "var(--s-surface-elevated)",
    "thumb-border": "var(--s-border)",
  },

  componentSurfaces: {
    bg: "var(--s-surface)",
    "bg-elevated": "var(--s-surface-elevated)",
    "bg-muted": "var(--s-surface-sunken, var(--s-surface))",
    border: "var(--s-border)",
    "border-muted": "var(--s-border-muted)",
    "border-strong": "var(--s-border-strong)",
    text: "var(--s-text)",
    "text-muted": "var(--s-text-muted)",
    contrast: "var(--s-primary-contrast, var(--s-text-inverse))",
    "hover-bg": "var(--s-surface-elevated)",
    "active-bg": "var(--s-surface-sunken, var(--s-surface))",
    "selected-bg": "color-mix(in oklch, var(--s-primary) 12%, transparent)",
  },

  hero: {
    "min-height": "auto",
    "padding-y": "100px",
    "padding-y-sm": "100px",
    "padding-x": "var(--s-page-margin, 24px)",
    "content-max": "640px",
    "content-align": "center" as const,
    "layout": "centered" as const,
    "media-position": "below" as const,
    "media-width": "50%",
    "media-radius": "var(--s-radius-lg, 12px)",
    "title-size": "clamp(2.25rem, 6vw, 4rem)",
    "title-max-width": "56rem",
    "description-size": "1.125rem",
    "description-max-width": "32rem",
    "description-gap": "24px",
    "actions-gap": "12px",
    "actions-margin-top": "32px",
    "action-padding-x": "24px",
    "action-padding-y": "12px",
    "badge-gap": "24px",
    "overlay-opacity": "0.5",
    "scroll-indicator": false,
    "gradient-overlay": "none",
  },

  cta: {
    "padding-y": "100px",
    "padding-x": "var(--s-page-margin, 24px)",
    "max-width": "var(--s-content-max, 1200px)",
    "layout": "centered" as const,
    "border": true,
    "border-radius": "var(--s-card-radius, var(--s-radius-md, 8px))",
    "bg": "var(--s-surface)",
    "title-size": "clamp(1.5rem, 4vw, 2.25rem)",
    "description-max-width": "32rem",
    "description-gap": "12px",
    "actions-gap": "12px",
    "actions-margin-top": "32px",
    "action-padding-x": "24px",
    "action-padding-y": "12px",
    "split-gap": "50px",
  },

  footer: {
    "padding-y": "50px",
    "border-top": "1px solid var(--s-border)",
    "columns": "4",
    "column-gap": "32px",
    "row-gap": "32px",
    "logo-height": "24px",
    "tagline-max-width": "20rem",
    "link-size": "0.875rem",
    "link-gap": "8px",
    "group-title-size": "0.875rem",
    "group-title-weight": "600",
    "social-icon-size": "20px",
    "social-gap": "12px",
    "bottom-bar-padding": "24px 0",
    "bottom-bar-border": "1px solid var(--s-border-muted)",
  },

  banner: {
    "height": "25px",
    "padding-y": "8px",
    "padding-x": "16px",
    "font-size": "0.875rem",
    "font-weight": "500",
    "icon-size": "16px",
    "icon-gap": "12px",
    "border-width": "1px",
    "border-position": "bottom" as const,
    "position": "top" as const,
    "dismiss-size": "16px",
    "radius": "0px",
  },

  pageRhythm: {
    "density": "normal" as const,
    "section-gap": "0px",
    "section-gap-sm": "0px",
    "section-gap-lg": "0px",
    "first-section-offset": "0px",
    "last-section-margin": "0px",
    "alternate-bg": false,
    "alternate-bg-color": "var(--s-surface)",
    "divider-between": false,
    "max-content-width": "var(--s-content-max, 1200px)",
    "vertical-rhythm-unit": "8px",
    "scroll-snap": false,
    "responsive-scale": "1",
    "responsive-breakpoint": "768px",
  },
} as const;
