import type { SigilPreset } from "@sigil-ui/tokens";

export const alloyPreset: SigilPreset = {
  name: "alloy",
  metadata: {
    description: "Mixed metals industrial. Warm metallics, exposed structure, compositional weight.",
    mood: "industrial, warm, compositional",
    tags: ["industrial", "warm", "bronze", "metallic", "structured"],
  },
  tokens: {
    colors: {
      background: { light: "oklch(0.975 0.005 70)", dark: "oklch(0.1 0.01 60)" },
      surface: { light: "oklch(0.96 0.006 70)", dark: "oklch(0.14 0.01 60)" },
      "surface-elevated": { light: "oklch(0.99 0.003 70)", dark: "oklch(0.18 0.01 60)" },
      "surface-sunken": { light: "oklch(0.94 0.008 70)", dark: "oklch(0.07 0.01 60)" },
      primary: "oklch(0.65 0.12 60)",
      "primary-hover": "oklch(0.58 0.14 60)",
      "primary-muted": "oklch(0.65 0.05 60)",
      "primary-contrast": "oklch(1 0 0)",
      secondary: "oklch(0.55 0.04 250)",
      "secondary-hover": "oklch(0.48 0.05 250)",
      "secondary-muted": "oklch(0.55 0.02 250)",
      accent: "oklch(0.72 0.1 50)",
      "accent-hover": "oklch(0.65 0.12 50)",
      "accent-muted": "oklch(0.72 0.04 50)",
      text: { light: "oklch(0.18 0.01 60)", dark: "oklch(0.9 0.008 70)" },
      "text-secondary": { light: "oklch(0.38 0.01 60)", dark: "oklch(0.72 0.008 70)" },
      "text-muted": { light: "oklch(0.52 0.008 60)", dark: "oklch(0.64 0.006 70)" },
      "text-subtle": { light: "oklch(0.64 0.006 60)", dark: "oklch(0.52 0.005 70)" },
      "text-disabled": { light: "oklch(0.74 0.004 60)", dark: "oklch(0.36 0.004 70)" },
      "text-inverse": { light: "oklch(0.94 0.006 70)", dark: "oklch(0.14 0.01 60)" },
      border: { light: "oklch(0.84 0.01 65)", dark: "oklch(0.26 0.01 60)" },
      "border-muted": { light: "oklch(0.9 0.008 65)", dark: "oklch(0.26 0.008 60)" },
      "border-strong": { light: "oklch(0.7 0.015 65)", dark: "oklch(0.38 0.012 60)" },
      "border-interactive": { light: "oklch(0.65 0.12 60)", dark: "oklch(0.65 0.12 60)" },
      success: "oklch(0.7 0.16 150)",
      "success-muted": "oklch(0.7 0.06 150)",
      warning: "oklch(0.78 0.15 70)",
      "warning-muted": "oklch(0.78 0.06 70)",
      error: "oklch(0.6 0.2 25)",
      "error-muted": "oklch(0.6 0.07 25)",
      info: "oklch(0.65 0.12 240)",
      "info-muted": "oklch(0.65 0.05 240)",
      "gradient-start": "oklch(0.65 0.12 60)",
      "gradient-end": "oklch(0.55 0.04 250)",
      glow: "oklch(0.65 0.12 60 / 0.3)",
    },
    typography: {
      "font-display": "'PP Supply Sans', system-ui, sans-serif",
      "font-body": "'PP Supply Sans', system-ui, sans-serif",
      "font-mono": "'PP Supply Mono', ui-monospace, monospace",
      "size-xs": "0.75rem",
      "size-sm": "0.875rem",
      "size-base": "1rem",
      "size-lg": "1.125rem",
      "size-xl": "1.25rem",
      "size-2xl": "1.5rem",
      "size-3xl": "1.875rem",
      "size-4xl": "2.25rem",
      "size-5xl": "3rem",
      "size-6xl": "3.75rem",
      "weight-normal": "400",
      "weight-medium": "500",
      "weight-semibold": "600",
      "weight-bold": "700",
      "weight-extrabold": "800",
      "leading-tight": "1.25",
      "leading-normal": "1.55",
      "leading-relaxed": "1.7",
      "leading-loose": "2",
      "tracking-tighter": "-0.04em",
      "tracking-tight": "-0.02em",
      "tracking-normal": "0em",
      "tracking-wide": "0.02em",
      "tracking-wider": "0.05em",
      "heading-weight": "700",
      "heading-tracking": "0.08em",
      "heading-transform": "uppercase",
      "heading-family": "'PP Supply Sans', system-ui, sans-serif",
    },
    spacing: {
      scale: [4, 8, 12, 16, 24, 32, 48, 64, 80, 96],
      unit: "px",
      "button-px": "24px",
      "button-py": "12px",
      "button-px-sm": "18px",
      "button-py-sm": "8px",
      "button-px-lg": "32px",
      "button-py-lg": "14px",
      "card-padding": "24px",
      "card-padding-sm": "20px",
      "card-padding-lg": "40px",
      "input-px": "14px",
      "input-py": "10px",
      "badge-px": "10px",
      "badge-py": "3px",
      "section-py": "88px",
      "section-py-lg": "128px",
      "navbar-height": "72px",
      "navbar-px": "32px",
      "footer-py": "60px",
      "modal-padding": "28px",
      "popover-padding": "16px",
      "tooltip-padding": "8px 14px",
      "table-cell-px": "18px",
      "table-cell-py": "14px",
    },
    layout: {
      "content-max": "1420px",
      "content-max-narrow": "800px",
      "content-max-wide": "1600px",
      "page-margin": "32px",
      "page-margin-sm": "16px",
      "page-margin-lg": "60px",
      gutter: "32px",
      "gutter-sm": "16px",
      "gutter-lg": "44px",
      "grid-columns": "12",
      "grid-gap": "28px",
      "bento-gap": "16px",
      "bento-radius": "8px",
      "bento-min-height": "220px",
      "section-gap": "40px",
      "sidebar-width": "312px",
      "sidebar-collapsed": "68px",
      "footer-columns": "4",
      "stack-gap": "16px",
      "stack-gap-sm": "8px",
      "stack-gap-lg": "28px",
      "prose-max": "68ch",
    },
    sigil: {
      "grid-cell": "56px",
      "cross-arm": "10px",
      "cross-stroke": "2px",
      "rail-gap": "32px",
      "card-radius": "8px",
      "gutter-pattern": "grid",
      "margin-pattern": "hexagon",
    },
    radius: {
      none: "0px",
      sm: "4px",
      md: "8px",
      lg: "12px",
      xl: "16px",
      "2xl": "20px",
      full: "9999px",
      button: "8px",
      card: "8px",
      input: "8px",
      badge: "9999px",
      modal: "12px",
      popover: "8px",
      tooltip: "6px",
      image: "8px",
      bento: "8px",
    },
    shadows: {
      sm: "0 1px 2px 0 rgb(0 0 0 / 0.04), 0 1px 4px 0 rgb(0 0 0 / 0.04)",
      md: "0 2px 4px -1px rgb(0 0 0 / 0.06), 0 4px 8px -1px rgb(0 0 0 / 0.08)",
      lg: "0 4px 8px -2px rgb(0 0 0 / 0.08), 0 8px 16px -4px rgb(0 0 0 / 0.1)",
      xl: "0 8px 16px -4px rgb(0 0 0 / 0.1), 0 16px 32px -8px rgb(0 0 0 / 0.12)",
      "2xl": "0 24px 48px -12px rgb(0 0 0 / 0.2)",
      glow: "0 0 24px var(--s-primary)",
      "glow-sm": "0 0 12px var(--s-primary)",
      colored: "0 4px 16px -4px var(--s-primary)",
      inner: "inset 0 2px 6px 0 rgb(0 0 0 / 0.08)",
      card: "0 2px 4px -1px rgb(0 0 0 / 0.05), 0 4px 12px -2px rgb(0 0 0 / 0.08)",
      button: "0 1px 2px 0 rgb(0 0 0 / 0.05)",
      "button-hover": "0 2px 6px -1px rgb(0 0 0 / 0.12)",
      dropdown: "0 8px 24px -4px rgb(0 0 0 / 0.12), 0 0 0 1px rgb(0 0 0 / 0.04)",
      modal: "0 20px 60px -12px rgb(0 0 0 / 0.25)",
    },
    motion: {
      duration: { instant: "0ms", fast: "150ms", normal: "280ms", slow: "450ms", slower: "650ms", slowest: "1100ms" },
      easing: {
        default: "cubic-bezier(0.25, 0.1, 0.25, 1)",
        in: "cubic-bezier(0.42, 0, 1, 1)",
        out: "cubic-bezier(0, 0, 0.58, 1)",
        "in-out": "cubic-bezier(0.42, 0, 0.58, 1)",
        spring: "cubic-bezier(0.34, 1.56, 0.64, 1)",
        bounce: "cubic-bezier(0.68, -0.55, 0.27, 1.55)",
      },
      "enter-preset": "fadeUp",
      "exit-preset": "fadeOut",
      "hover-scale": "1.015",
      "press-scale": "0.98",
      "hover-lift": "-2px",
      "stagger-interval": "60ms",
      "stagger-interval-fast": "30ms",
    },
    borders: {
      width: { none: "0px", thin: "1px", medium: "1.5px", thick: "2px" },
      style: "solid",
      "card-border": "2px solid",
      "card-border-hover": "2px solid",
      "button-border": "2px solid",
      "input-border": "2px solid",
      "divider-style": "solid",
      "divider-width": "2px",
    },
    buttons: {
      "font-weight": "500",
      "text-transform": "capitalize",
      "letter-spacing": "0.01em",
      "font-family": "'PP Supply Sans', system-ui, sans-serif",
      "border-width": "2px",
      "hover-effect": "outline",
      "active-scale": "0.97",
      "icon-gap": "10px",
      "min-width": "0px",
    },
    cards: {
      "border-style": "solid",
      "border-width": "2px",
      "hover-effect": "border",
      "hover-border-color": "var(--s-primary)",
      padding: "28px",
      "header-padding": "28px 28px 0",
      "footer-padding": "0 28px 28px",
      "title-size": "1.125rem",
      "title-weight": "700",
      "description-size": "0.875rem",
      background: "surface",
      shadow: "none",
      outline: true,
      "outline-on-hover-only": false,
      "gap-between": "16px",
      "content-padding-x": "28px",
      "content-padding-y": "20px",
    },
    headings: {
      "h1-size": "2.25rem",
      "h1-weight": "700",
      "h1-tracking": "-0.02em",
      "h1-leading": "1.2",
      "h2-size": "1.875rem",
      "h2-weight": "700",
      "h2-tracking": "-0.015em",
      "h3-size": "1.5rem",
      "h3-weight": "600",
      "h4-size": "1.25rem",
      "h4-weight": "600",
      "display-size": "3.75rem",
      "display-weight": "800",
      "display-tracking": "-0.035em",
      "display-leading": "1.1",
    },
    navigation: {
      "navbar-height": "72px",
      "navbar-backdrop-blur": "12px",
      "navbar-border": "2px solid",
      "navbar-bg-opacity": "0.92",
      "nav-link-weight": "600",
      "nav-link-size": "0.9375rem",
      "nav-link-hover": "underline",
      "breadcrumb-separator": "·",
      "pagination-radius": "8px",
      "sidebar-width": "312px",
      "sidebar-item-radius": "6px",
      "sidebar-item-padding": "10px 16px",
    },
    backgrounds: {
      pattern: "grid",
      "pattern-opacity": "0.05",
      "pattern-scale": "1",
      noise: true,
      "noise-opacity": "0.02",
      "gradient-angle": "135deg",
      "gradient-type": "none",
      "hero-pattern": "grid",
      "section-divider": "line",
    },
    code: {
      "font-family": "'PP Supply Mono', ui-monospace, monospace",
      "font-size": "0.875rem",
      "line-height": "1.7",
      bg: "var(--s-surface-sunken)",
      border: "2px solid var(--s-border)",
      "border-radius": "8px",
      padding: "18px",
      "tab-size": "2",
      "selection-bg": "var(--s-primary-muted)",
      "comment-color": "var(--s-text-muted)",
      "keyword-color": "var(--s-primary)",
      "string-color": "var(--s-success)",
      "number-color": "var(--s-accent)",
      "function-color": "var(--s-secondary)",
    },
    inputs: {
      height: "44px",
      "height-sm": "36px",
      "height-lg": "52px",
      "border-width": "2px",
      "focus-ring-width": "2px",
      "focus-ring-color": "var(--s-primary)",
      "focus-ring-offset": "2px",
      "placeholder-color": "var(--s-text-subtle)",
      "error-border-color": "var(--s-error)",
      "label-size": "0.875rem",
      "label-weight": "600",
      "label-spacing": "8px",
      "helper-size": "0.8125rem",
    },
    alignment: {
      "rail-width": "1320px",
      "rail-columns": "12",
      "rail-gutter": "28px",
      "rail-margin": "16px",
      "rail-visible": false,
      "rail-color": "var(--s-border-muted)",
      "content-align": "center",
      "hero-align": "center",
      "section-align": "center",
      "navbar-align": "full",
      "footer-align": "content",
    },
    sections: {
      "padding-y": "48px",
      "padding-y-hero": "96px",
      "padding-x": "16px",
      "max-width": "1320px",
      gap: "24px",
      "title-align": "left",
      "divider-above": false,
      "divider-below": true,
      "background-alt": false,
      indent: "0px",
    },
    dividers: {
      style: "solid",
      width: "2px",
      color: "var(--s-border)",
      spacing: "0px",
      "show-cross": false,
      "show-label": false,
      "full-bleed": false,
      ornament: "none",
    },
    gridVisuals: {
      "show-lines": true,
      "line-color": "var(--s-border-muted)",
      "line-width": "1px",
      "show-dots": false,
      "dot-size": "2px",
      "cell-background": "none",
      "cell-border": true,
      "cell-radius": "0px",
      "cell-padding": "16px",
      "hover-effect": "none",
    },
  },
};
