import type { SigilPreset } from "@sigil-ui/tokens";

export const anvilPreset: SigilPreset = {
  name: "anvil",
  metadata: {
    description: "Heavy workhorse — built to last, utilitarian brutalism",
    author: "sigil-ui",
    version: "0.1.0",
    tags: ["brutalist", "heavy", "utilitarian", "bold"],
    mood: "heavy, utilitarian, workhorse",
    inspiration: "Industrial signage, concrete architecture, factory floors",
  },
  tokens: {
    colors: {
      background: { light: "#f5f4f2", dark: "#111111" },
      surface: { light: "#eeedea", dark: "#1a1a1a" },
      "surface-elevated": { light: "#ffffff", dark: "#222222" },
      "surface-sunken": { light: "#e5e4e0", dark: "#0a0a0a" },
      text: { light: "#1e1e1e", dark: "#e0ddd8" },
      "text-secondary": { light: "#3d3d3d", dark: "#b0ada8" },
      "text-muted": { light: "#5c5c5c", dark: "#8d8b86" },
      "text-subtle": { light: "#7a7a7a", dark: "#706e6a" },
      "text-disabled": { light: "#a0a0a0", dark: "#444240" },
      "text-inverse": { light: "#f5f4f2", dark: "#1e1e1e" },
      border: { light: "#8e8b86", dark: "oklch(0.358 0.006 0)" },
      "border-muted": { light: "#bebbb6", dark: "oklch(0.298 0.006 0)" },
      "border-strong": { light: "#7a7a7a", dark: "oklch(0.438 0.006 0)" },
      "border-interactive": { light: "#1e40af", dark: "#3b82f6" },
      primary: "#325aca",
      "primary-hover": "#1e3a8a",
      "primary-muted": "#dbeafe",
      "primary-contrast": "#ffffff",
      secondary: "#57534e",
      "secondary-hover": "#44403c",
      "secondary-muted": "#d6d3d1",
      accent: "#c2410c",
      "accent-hover": "#9a3412",
      "accent-muted": "#ffedd5",
      success: "#15803d",
      "success-muted": "#dcfce7",
      warning: "#a16207",
      "warning-muted": "#fef3c7",
      error: "#be2321",
      "error-muted": "#fee2e2",
      info: "#0284c7",
      "info-muted": "#dbeafe",
      "gradient-start": "#1e40af",
      "gradient-end": "#1e3a8a",
      glow: "rgba(30, 64, 175, 0.2)",
      highlight: { light: "#c7d2fe", dark: "rgba(99, 102, 241, 0.15)" },
    },
    typography: {
      "font-display": "'ABC Monument Grotesk', system-ui, sans-serif",
      "font-body": "'PP Telegraf', system-ui, sans-serif",
      "font-mono": "'PP Supply Mono', ui-monospace, monospace",
      "size-xs": "0.8125rem",
      "size-sm": "0.875rem",
      "size-base": "1rem",
      "size-lg": "1.1875rem",
      "size-xl": "1.375rem",
      "size-2xl": "1.625rem",
      "size-3xl": "2rem",
      "size-4xl": "2.5rem",
      "size-5xl": "3.25rem",
      "size-6xl": "4rem",
      "weight-normal": "400",
      "weight-medium": "500",
      "weight-semibold": "600",
      "weight-bold": "700",
      "weight-extrabold": "800",
      "leading-tight": "1.15",
      "leading-normal": "1.45",
      "leading-relaxed": "1.6",
      "leading-loose": "1.75",
      "tracking-tighter": "-0.04em",
      "tracking-tight": "-0.02em",
      "tracking-normal": "0em",
      "tracking-wide": "0.04em",
      "tracking-wider": "0.08em",
      "heading-weight": "700",
      "heading-tracking": "0.12em",
      "heading-transform": "uppercase",
      "heading-family": "'ABC Monument Grotesk', system-ui, sans-serif",
    },
    spacing: {
      scale: [4, 8, 12, 16, 20, 24, 32, 48, 64, 80],
      unit: "px",
      "button-px": "24px",
      "button-py": "14px",
      "button-px-sm": "16px",
      "button-py-sm": "10px",
      "button-px-lg": "32px",
      "button-py-lg": "18px",
      "card-padding": "20px",
      "card-padding-sm": "14px",
      "card-padding-lg": "28px",
      "input-px": "14px",
      "input-py": "12px",
      "badge-px": "10px",
      "badge-py": "4px",
      "section-py": "72px",
      "section-py-lg": "104px",
      "navbar-height": "64px",
      "navbar-px": "24px",
      "footer-py": "48px",
      "modal-padding": "24px",
      "popover-padding": "14px",
      "tooltip-padding": "8px 12px",
      "table-cell-px": "16px",
      "table-cell-py": "12px",
    },
    layout: {
      "content-max": "1200px",
      "content-max-narrow": "720px",
      "content-max-wide": "1440px",
      "page-margin": "20px",
      "page-margin-sm": "16px",
      "page-margin-lg": "40px",
      gutter: "20px",
      "gutter-sm": "12px",
      "gutter-lg": "28px",
      "grid-columns": "12",
      "grid-gap": "20px",
      "bento-gap": "10px",
      "bento-radius": "0px",
      "bento-min-height": "220px",
      "section-gap": "56px",
      "sidebar-width": "280px",
      "sidebar-collapsed": "56px",
      "footer-columns": "4",
      "stack-gap": "16px",
      "stack-gap-sm": "8px",
      "stack-gap-lg": "24px",
      "prose-max": "70ch",
    },
    sigil: {
      "grid-cell": "52px",
      "cross-arm": "14px",
      "cross-stroke": "2.5px",
      "rail-gap": "20px",
      "card-radius": "0px",
      "gutter-pattern": "plus",
      "margin-pattern": "diamond",
      "margin-border": "2px solid var(--s-border-muted)",
    },
    radius: {
      none: "0px",
      sm: "0px",
      md: "0px",
      lg: "0px",
      xl: "0px",
      "2xl": "0px",
      full: "0px",
      button: "0px",
      card: "0px",
      input: "0px",
      badge: "0px",
      modal: "0px",
      popover: "0px",
      tooltip: "0px",
      image: "0px",
      bento: "0px",
    },
    shadows: {
      sm: "none",
      md: "none",
      lg: "none",
      xl: "none",
      "2xl": "none",
      glow: "none",
      "glow-sm": "none",
      colored: "none",
      inner: "none",
      card: "none",
      button: "none",
      "button-hover": "none",
      dropdown: "0 2px 0 0 rgba(0,0,0,0.2)",
      modal: "0 0 0 2px rgba(0,0,0,0.15)",
    },
    motion: {
      duration: {
        instant: "0ms",
        fast: "100ms",
        normal: "180ms",
        slow: "300ms",
        slower: "450ms",
        slowest: "600ms",
      },
      easing: {
        default: "cubic-bezier(0.25, 0, 0.5, 1)",
        in: "cubic-bezier(0.42, 0, 1, 1)",
        out: "cubic-bezier(0, 0, 0.58, 1)",
        "in-out": "cubic-bezier(0.42, 0, 0.58, 1)",
        spring: "cubic-bezier(0.22, 1, 0.36, 1)",
        bounce: "cubic-bezier(0.34, 1.3, 0.64, 1)",
      },
      "enter-preset": "180ms cubic-bezier(0.25, 0, 0.5, 1)",
      "exit-preset": "120ms cubic-bezier(0.42, 0, 1, 1)",
      "hover-scale": "1",
      "press-scale": "0.97",
      "hover-lift": "0px",
      "stagger-interval": "40ms",
      "stagger-interval-fast": "20ms",
    },
    borders: {
      width: { none: "0px", thin: "1px", medium: "2px", thick: "3px" },
      style: "solid",
      "card-border": "2px solid var(--s-border)",
      "card-border-hover": "2px solid var(--s-border-strong)",
      "button-border": "2px solid var(--s-border-strong)",
      "input-border": "2px solid var(--s-border)",
      "divider-style": "solid",
      "divider-width": "2px",
    },
    buttons: {
      "font-weight": "700",
      "text-transform": "uppercase",
      "letter-spacing": "0.06em",
      "font-family": "'PP Telegraf', system-ui, sans-serif",
      "border-width": "2px",
      "hover-effect": "darken",
      "active-scale": "0.97",
      "icon-gap": "10px",
      "min-width": "120px",
    },
    cards: {
      "border-style": "solid",
      "border-width": "2px",
      "hover-effect": "border",
      "hover-border-color": "var(--s-border-strong)",
      padding: "20px",
      "header-padding": "20px 20px 0",
      "footer-padding": "0 20px 20px",
      "title-size": "var(--s-size-xl)",
      "title-weight": "700",
      "description-size": "var(--s-size-base)",
      background: "surface",
      shadow: "none",
      outline: true,
      "outline-on-hover-only": false,
      "gap-between": "12px",
      "content-padding-x": "20px",
      "content-padding-y": "16px",
    },
    headings: {
      "h1-size": "3.25rem",
      "h1-weight": "800",
      "h1-tracking": "-0.03em",
      "h1-leading": "1.05",
      "h2-size": "2.5rem",
      "h2-weight": "700",
      "h2-tracking": "-0.02em",
      "h2-leading": "1.1",
      "h3-size": "1.75rem",
      "h3-weight": "700",
      "h3-tracking": "0em",
      "h3-leading": "1.15",
      "h4-size": "1.375rem",
      "h4-weight": "600",
      "h4-tracking": "0em",
      "h4-leading": "1.2",
      "display-size": "4.5rem",
      "display-weight": "800",
      "display-tracking": "-0.04em",
      "display-leading": "0.95",
    },
    navigation: {
      "navbar-height": "64px",
      "navbar-backdrop-blur": "0px",
      "navbar-border": "2px solid var(--s-border-strong)",
      "navbar-bg-opacity": "1",
      "navbar-padding-x": "20px",
      "navbar-position": "sticky",
      "navbar-logo-height": "22px",
      "navbar-logo-gap": "8px",
      "navbar-item-gap": "16px",
      "navbar-item-padding-x": "10px",
      "navbar-item-padding-y": "4px",
      "navbar-item-size": "0.8125rem",
      "navbar-shadow": "none",
      "navbar-height-scrolled": "44px",
      "navbar-mobile-breakpoint": "768px",
      "nav-link-weight": "600",
      "nav-link-size": "var(--s-size-sm)",
      "nav-link-hover": "background",
      "breadcrumb-separator": ">",
      "pagination-radius": "0px",
      "sidebar-width": "280px",
      "sidebar-item-radius": "0px",
      "sidebar-item-padding": "10px 14px",
    },
    backgrounds: {
      pattern: "grid",
      "pattern-opacity": "0.06",
      "pattern-scale": "0px",
      noise: false,
      "noise-opacity": "0",
      "gradient-angle": "180deg",
      "gradient-type": "none",
      "hero-pattern": "grid",
      "section-divider": "zigzag",
    },
    code: {
      "font-family": "'PP Supply Mono', ui-monospace, monospace",
      "font-size": "0.875rem",
      "line-height": "1.5",
      bg: "#d9d5d0",
      border: "2px solid #999590",
      "border-radius": "0px",
      padding: "20px 24px",
      "tab-size": "4",
      "selection-bg": "rgba(30, 64, 175, 0.15)",
      "comment-color": "#7a7a7a",
      "keyword-color": "#1e40af",
      "string-color": "#15803d",
      "number-color": "#b91c1c",
      "function-color": "#c2410c",
    },
    inputs: {
      height: "44px",
      "height-sm": "36px",
      "height-lg": "52px",
      "border-width": "2px",
      "focus-ring-width": "2px",
      "focus-ring-color": "var(--s-primary)",
      "focus-ring-offset": "0px",
      "placeholder-color": "var(--s-text-muted)",
      "error-border-color": "var(--s-error)",
      "label-size": "var(--s-size-sm)",
      "label-weight": "600",
      "label-spacing": "6px",
      "helper-size": "var(--s-size-xs)",
    },
    alignment: {
      "rail-width": "1280px",
      "rail-columns": "12",
      "rail-gutter": "20px",
      "rail-margin": "12px",
      "rail-visible": false,
      "rail-color": "var(--s-border-muted)",
      "content-align": "center",
      "hero-align": "center",
      "section-align": "center",
      "navbar-align": "full",
      "footer-align": "content",
    },
    sections: {
      "padding-y": "40px",
      "padding-y-hero": "80px",
      "padding-y-sm": "36px",
      "padding-x": "12px",
      "max-width": "1280px",
      gap: "20px",
      "padding-y-lg": "72px",
      "padding-y-xl": "96px",
      "title-align": "left",
      "heading-size": "clamp(1.25rem, 3vw, 2rem)",
      "heading-align": "left",
      "heading-max-width": "36rem",
      "heading-margin-bottom": "12px",
      "description-max-width": "28rem",
      "description-gap": "8px",
      "content-gap": "16px",
      "grid-columns": "3",
      "grid-gap": "16px",
      "alternate-bg": "var(--s-surface)",
      "alternate-bg-mode": "none",
      "divider-above": false,
      "divider-below": true,
      "background-alt": false,
      indent: "0px",
    },
    dividers: {
      style: "solid",
      width: "2px",
      color: "var(--s-border-muted)",
      spacing: "0px",
      opacity: "1",
      "max-width": "100%",
      "margin-y": "0px",
      thickness: "2px",
      "gradient-start": "transparent",
      "gradient-end": "transparent",
      "show-cross": false,
      "show-label": false,
      "full-bleed": true,
      ornament: "none",
    },
    gridVisuals: {
      "show-lines": true,
      "line-color": "var(--s-border-muted)",
      "line-width": "2px",
      "show-dots": false,
      "dot-size": "2px",
      "cell-background": "surface",
      "cell-border": true,
      "cell-radius": "0px",
      "cell-padding": "14px",
      "hover-effect": "none",
    },
    cursor: {
      variant: "crosshair",
      size: "24px",
      "dot-size": "4px",
      "stroke-width": "2px",
      "tick-size": "6px",
      gap: "3px",
      radius: "0px",
      color: "var(--s-text)",
      "ring-color": "var(--s-primary)",
      "dot-color": "var(--s-primary)",
      glow: "none",
      opacity: "1",
      "blend-mode": "normal",
      "z-index": "9999",
      "hide-native": false,
    },
    scrollbar: {
      width: "10px",
      height: "10px",
      padding: "2px",
      radius: "2px",
      track: "transparent",
      thumb: "var(--s-border-muted)",
      "thumb-hover": "var(--s-border)",
      "thumb-active": "var(--s-border-strong)",
      corner: "transparent",
      border: "none",
      "firefox-width": "auto",
      gutter: "stable",
      visibility: "auto",
    },
    focus: {
      "ring-width": "3px",
      "ring-color": "var(--s-primary)",
      "ring-offset": "0px",
      "ring-shadow": "0 0 0 3px var(--s-primary)",
      "outline-color": "var(--s-primary)",
    },
    overlays: {
      bg: "rgb(0 0 0 / 0.6)",
      blur: "4px",
      surface: "var(--s-surface-elevated)",
      border: "1px solid var(--s-border-muted)",
      shadow: "var(--s-shadow-xl)",
      radius: "var(--s-radius-lg)",
      padding: "20px",
      "z-index": "50",
    },
    dataViz: {
      "series-1": "var(--s-primary)",
      "series-2": "var(--s-secondary)",
      "series-3": "var(--s-accent)",
      "series-4": "var(--s-info)",
      "series-5": "var(--s-success)",
      positive: "var(--s-success)",
      negative: "var(--s-error)",
      neutral: "var(--s-text-muted)",
      grid: "var(--s-border-muted)",
      axis: "var(--s-border)",
      label: "var(--s-text-secondary)",
      "tooltip-bg": "var(--s-surface-elevated)",
      "tooltip-border": "var(--s-border-muted)",
    },
    media: {
      radius: "var(--s-radius-md)",
      border: "none",
      outline: "1px solid rgb(0 0 0 / 0.08)",
      shadow: "none",
      bg: "var(--s-surface-sunken)",
      "object-fit": "cover",
    },
    controls: {
      height: "38px",
      "height-sm": "30px",
      "height-lg": "46px",
      "hit-area": "44px",
      "icon-size": "16px",
      "handle-size": "20px",
      "track-height": "4px",
      "track-bg": "var(--s-border-muted)",
      "track-fill": "var(--s-primary)",
      "thumb-bg": "var(--s-surface-elevated)",
      "thumb-border": "2px solid var(--s-primary)",
    },
    componentSurfaces: {
      bg: "var(--s-surface)",
      "bg-elevated": "var(--s-surface-elevated)",
      "bg-muted": "var(--s-surface-sunken)",
      border: "var(--s-border)",
      "border-muted": "var(--s-border-muted)",
      "border-strong": "var(--s-border-strong)",
      text: "var(--s-text)",
      "text-muted": "var(--s-text-muted)",
      contrast: "var(--s-primary-contrast)",
      "hover-bg": "var(--s-surface-elevated)",
      "active-bg": "var(--s-surface-sunken)",
      "selected-bg": "var(--s-primary-muted)",
    },
    hero: {
      "min-height": "auto",
      "padding-y": "72px",
      "padding-y-sm": "48px",
      "padding-x": "var(--s-page-margin, 20px)",
      "content-max": "560px",
      "content-align": "left",
      layout: "split",
      "media-position": "right",
      "media-width": "45%",
      "media-radius": "var(--s-radius-sm)",
      "title-size": "clamp(1.75rem, 5vw, 3rem)",
      "title-max-width": "40rem",
      "description-size": "1rem",
      "description-max-width": "28rem",
      "description-gap": "16px",
      "actions-gap": "10px",
      "actions-margin-top": "24px",
      "action-padding-x": "20px",
      "action-padding-y": "10px",
      "badge-gap": "16px",
      "overlay-opacity": "0.6",
      "scroll-indicator": false,
      "gradient-overlay": "none",
    },
    cta: {
      "padding-y": "56px",
      "padding-x": "var(--s-page-margin, 20px)",
      "max-width": "var(--s-content-max, 1200px)",
      layout: "split",
      border: true,
      "border-radius": "var(--s-radius-sm)",
      bg: "var(--s-surface)",
      "title-size": "clamp(1.25rem, 3vw, 2rem)",
      "description-max-width": "28rem",
      "description-gap": "8px",
      "actions-gap": "10px",
      "actions-margin-top": "20px",
      "action-padding-x": "20px",
      "action-padding-y": "10px",
      "split-gap": "32px",
    },
    footer: {
      "padding-y": "36px",
      "border-top": "2px solid var(--s-border-strong)",
      columns: "4",
      "column-gap": "24px",
      "row-gap": "24px",
      "logo-height": "20px",
      "tagline-max-width": "18rem",
      "link-size": "0.8125rem",
      "link-gap": "6px",
      "group-title-size": "0.75rem",
      "group-title-weight": "700",
      "social-icon-size": "16px",
      "social-gap": "10px",
      "bottom-bar-padding": "16px 0",
      "bottom-bar-border": "2px solid var(--s-border)",
    },
    banner: {
      height: "auto",
      "padding-y": "6px",
      "padding-x": "16px",
      "font-size": "0.8125rem",
      "font-weight": "600",
      "icon-size": "14px",
      "icon-gap": "8px",
      "border-width": "2px",
      "border-position": "bottom",
      position: "top",
      "dismiss-size": "14px",
      radius: "0px",
    },
    pageRhythm: {
      density: "compact",
      "section-gap": "0px",
      "section-gap-sm": "0px",
      "section-gap-lg": "0px",
      "first-section-offset": "0px",
      "last-section-margin": "0px",
      "alternate-bg": false,
      "alternate-bg-color": "var(--s-surface)",
      "divider-between": true,
      "max-content-width": "var(--s-content-max, 1200px)",
      "vertical-rhythm-unit": "4px",
      "scroll-snap": false,
      "responsive-scale": "1",
      "responsive-breakpoint": "768px",
    },

  },
};
