import type { SigilPreset } from "@sigil-ui/tokens";

export const anvilPreset: SigilPreset = {
  name: "anvil",
  metadata: {
    description: "Heavy workhorse — built to last, utilitarian brutalism",
    author: "sigil-ui",
    version: "0.1.0",
    tags: ["brutalist", "heavy", "utilitarian", "bold"],
    mood: "heavy, utilitarian, workhorse",
    inspiration: "Industrial signage, concrete architecture, factory floors",
  },
  tokens: {
    colors: {
      background: { light: "#e5e2de", dark: "#111111" },
      surface: { light: "#d9d5d0", dark: "#1a1a1a" },
      "surface-elevated": { light: "#eeece8", dark: "#222222" },
      "surface-sunken": { light: "#ccc8c2", dark: "#0a0a0a" },
      text: { light: "#1e1e1e", dark: "#e0ddd8" },
      "text-secondary": { light: "#3d3d3d", dark: "#b0ada8" },
      "text-muted": { light: "#5c5c5c", dark: "#7a7874" },
      "text-subtle": { light: "#7a7a7a", dark: "#5c5a56" },
      "text-disabled": { light: "#a0a0a0", dark: "#444240" },
      "text-inverse": { light: "#e5e2de", dark: "#1e1e1e" },
      border: { light: "#999590", dark: "#3a3a3a" },
      "border-muted": { light: "#b5b1ac", dark: "#2a2a2a" },
      "border-strong": { light: "#5c5c5c", dark: "#555555" },
      "border-interactive": { light: "#1e40af", dark: "#3b82f6" },
      primary: "#1e40af",
      "primary-hover": "#1e3a8a",
      "primary-muted": "#dbeafe",
      "primary-contrast": "#ffffff",
      secondary: "#57534e",
      "secondary-hover": "#44403c",
      "secondary-muted": "#d6d3d1",
      accent: "#c2410c",
      "accent-hover": "#9a3412",
      "accent-muted": "#ffedd5",
      success: "#15803d",
      "success-muted": "#dcfce7",
      warning: "#a16207",
      "warning-muted": "#fef3c7",
      error: "#b91c1c",
      "error-muted": "#fee2e2",
      info: "#1e40af",
      "info-muted": "#dbeafe",
      "gradient-start": "#1e40af",
      "gradient-end": "#1e3a8a",
      glow: "rgba(30, 64, 175, 0.2)",
    },
    typography: {
      "font-display": '"Work Sans", system-ui, sans-serif',
      "font-body": '"Work Sans", system-ui, sans-serif',
      "font-mono": '"Source Code Pro", ui-monospace, monospace',
      "size-xs": "0.8125rem",
      "size-sm": "0.875rem",
      "size-base": "1rem",
      "size-lg": "1.1875rem",
      "size-xl": "1.375rem",
      "size-2xl": "1.625rem",
      "size-3xl": "2rem",
      "size-4xl": "2.5rem",
      "size-5xl": "3.25rem",
      "size-6xl": "4rem",
      "weight-normal": "400",
      "weight-medium": "500",
      "weight-semibold": "600",
      "weight-bold": "700",
      "weight-extrabold": "800",
      "leading-tight": "1.15",
      "leading-normal": "1.45",
      "leading-relaxed": "1.6",
      "leading-loose": "1.75",
      "tracking-tighter": "-0.04em",
      "tracking-tight": "-0.02em",
      "tracking-normal": "0em",
      "tracking-wide": "0.04em",
      "tracking-wider": "0.08em",
      "heading-weight": "700",
      "heading-tracking": "-0.02em",
      "heading-transform": "uppercase",
      "heading-family": '"Work Sans", system-ui, sans-serif',
    },
    spacing: {
      scale: [4, 8, 12, 16, 20, 24, 32, 48, 64, 80],
      unit: "px",
      "button-px": "24px",
      "button-py": "14px",
      "button-px-sm": "16px",
      "button-py-sm": "10px",
      "button-px-lg": "32px",
      "button-py-lg": "18px",
      "card-padding": "20px",
      "card-padding-sm": "14px",
      "card-padding-lg": "28px",
      "input-px": "14px",
      "input-py": "12px",
      "badge-px": "10px",
      "badge-py": "4px",
      "section-py": "72px",
      "section-py-lg": "112px",
      "navbar-height": "64px",
      "navbar-px": "24px",
      "footer-py": "56px",
      "modal-padding": "24px",
      "popover-padding": "14px",
      "tooltip-padding": "8px 12px",
      "table-cell-px": "16px",
      "table-cell-py": "12px",
    },
    layout: {
      "content-max": "1280px",
      "content-max-narrow": "720px",
      "content-max-wide": "1536px",
      "page-margin": "24px",
      "page-margin-sm": "16px",
      "page-margin-lg": "48px",
      gutter: "20px",
      "gutter-sm": "12px",
      "gutter-lg": "28px",
      "grid-columns": "12",
      "grid-gap": "20px",
      "bento-gap": "12px",
      "bento-radius": "0px",
      "bento-min-height": "220px",
      "section-gap": "56px",
      "sidebar-width": "280px",
      "sidebar-collapsed": "56px",
      "footer-columns": "4",
      "stack-gap": "16px",
      "stack-gap-sm": "8px",
      "stack-gap-lg": "24px",
      "prose-max": "70ch",
    },
    sigil: {
      "grid-cell": "56px",
      "cross-arm": "14px",
      "cross-stroke": "2px",
      "rail-gap": "20px",
      "card-radius": "0px",
    },
    radius: {
      none: "0px",
      sm: "0px",
      md: "0px",
      lg: "0px",
      xl: "0px",
      "2xl": "0px",
      full: "0px",
      button: "0px",
      card: "0px",
      input: "0px",
      badge: "0px",
      modal: "0px",
      popover: "0px",
      tooltip: "0px",
      image: "0px",
      bento: "0px",
    },
    shadows: {
      sm: "none",
      md: "none",
      lg: "none",
      xl: "none",
      "2xl": "none",
      glow: "none",
      "glow-sm": "none",
      colored: "none",
      inner: "none",
      card: "none",
      button: "none",
      "button-hover": "none",
      dropdown: "0 2px 0 0 rgba(0,0,0,0.2)",
      modal: "0 0 0 2px rgba(0,0,0,0.15)",
    },
    motion: {
      duration: {
        instant: "0ms",
        fast: "100ms",
        normal: "180ms",
        slow: "300ms",
        slower: "450ms",
        slowest: "600ms",
      },
      easing: {
        default: "cubic-bezier(0.25, 0, 0.5, 1)",
        in: "cubic-bezier(0.42, 0, 1, 1)",
        out: "cubic-bezier(0, 0, 0.58, 1)",
        "in-out": "cubic-bezier(0.42, 0, 0.58, 1)",
        spring: "cubic-bezier(0.22, 1, 0.36, 1)",
        bounce: "cubic-bezier(0.34, 1.3, 0.64, 1)",
      },
      "enter-preset": "180ms cubic-bezier(0.25, 0, 0.5, 1)",
      "exit-preset": "120ms cubic-bezier(0.42, 0, 1, 1)",
      "hover-scale": "1",
      "press-scale": "0.97",
      "hover-lift": "0px",
      "stagger-interval": "40ms",
      "stagger-interval-fast": "20ms",
    },
    borders: {
      width: { none: "0px", thin: "1px", medium: "2px", thick: "3px" },
      style: "solid",
      "card-border": "2px solid var(--s-border)",
      "card-border-hover": "2px solid var(--s-border-strong)",
      "button-border": "2px solid var(--s-border-strong)",
      "input-border": "2px solid var(--s-border)",
      "divider-style": "solid",
      "divider-width": "2px",
    },
    buttons: {
      "font-weight": "700",
      "text-transform": "uppercase",
      "letter-spacing": "0.06em",
      "font-family": "var(--s-font-body)",
      "border-width": "2px",
      "hover-effect": "darken",
      "active-scale": "0.97",
      "icon-gap": "10px",
      "min-width": "120px",
    },
    cards: {
      "border-style": "solid",
      "border-width": "2px",
      "hover-effect": "none",
      "hover-border-color": "var(--s-border-strong)",
      padding: "20px",
      "header-padding": "20px 20px 0",
      "footer-padding": "0 20px 20px",
      "title-size": "var(--s-size-xl)",
      "title-weight": "700",
      "description-size": "var(--s-size-base)",
      background: "surface",
      shadow: "none",
      outline: true,
      "outline-on-hover-only": false,
      "gap-between": "12px",
      "content-padding-x": "20px",
      "content-padding-y": "16px",
    },
    headings: {
      "h1-size": "3.25rem",
      "h1-weight": "800",
      "h1-tracking": "-0.03em",
      "h1-leading": "1.05",
      "h2-size": "2.5rem",
      "h2-weight": "700",
      "h2-tracking": "-0.02em",
      "h3-size": "1.75rem",
      "h3-weight": "700",
      "h4-size": "1.375rem",
      "h4-weight": "600",
      "display-size": "4.5rem",
      "display-weight": "800",
      "display-tracking": "-0.04em",
      "display-leading": "0.95",
    },
    navigation: {
      "navbar-height": "64px",
      "navbar-backdrop-blur": "0px",
      "navbar-border": "2px solid var(--s-border-strong)",
      "navbar-bg-opacity": "1",
      "nav-link-weight": "600",
      "nav-link-size": "var(--s-size-sm)",
      "nav-link-hover": "background",
      "breadcrumb-separator": ">",
      "pagination-radius": "0px",
      "sidebar-width": "280px",
      "sidebar-item-radius": "0px",
      "sidebar-item-padding": "10px 14px",
    },
    backgrounds: {
      pattern: "none",
      "pattern-opacity": "0",
      "pattern-scale": "0px",
      noise: false,
      "noise-opacity": "0",
      "gradient-angle": "180deg",
      "gradient-type": "none",
      "hero-pattern": "none",
      "section-divider": "line",
    },
    code: {
      "font-family": '"Source Code Pro", ui-monospace, monospace',
      "font-size": "0.875rem",
      "line-height": "1.5",
      bg: "#d9d5d0",
      border: "2px solid #999590",
      "border-radius": "0px",
      padding: "20px 24px",
      "tab-size": "4",
      "selection-bg": "rgba(30, 64, 175, 0.15)",
      "comment-color": "#7a7a7a",
      "keyword-color": "#1e40af",
      "string-color": "#15803d",
      "number-color": "#b91c1c",
      "function-color": "#c2410c",
    },
    inputs: {
      height: "44px",
      "height-sm": "36px",
      "height-lg": "52px",
      "border-width": "2px",
      "focus-ring-width": "2px",
      "focus-ring-color": "var(--s-primary)",
      "focus-ring-offset": "0px",
      "placeholder-color": "var(--s-text-muted)",
      "error-border-color": "var(--s-error)",
      "label-size": "var(--s-size-sm)",
      "label-weight": "600",
      "label-spacing": "6px",
      "helper-size": "var(--s-size-xs)",
    },
    alignment: {
      "rail-width": "1280px",
      "rail-columns": "12",
      "rail-gutter": "20px",
      "rail-margin": "12px",
      "rail-visible": false,
      "rail-color": "var(--s-border-muted)",
      "content-align": "center",
      "hero-align": "center",
      "section-align": "center",
      "navbar-align": "full",
      "footer-align": "content",
    },
    sections: {
      "padding-y": "40px",
      "padding-y-hero": "80px",
      "padding-x": "12px",
      "max-width": "1280px",
      gap: "20px",
      "title-align": "left",
      "divider-above": false,
      "divider-below": true,
      "background-alt": false,
      indent: "0px",
    },
    dividers: {
      style: "solid",
      width: "2px",
      color: "var(--s-border)",
      spacing: "0px",
      "show-cross": false,
      "show-label": false,
      "full-bleed": true,
      ornament: "none",
    },
    gridVisuals: {
      "show-lines": true,
      "line-color": "var(--s-border-muted)",
      "line-width": "2px",
      "show-dots": false,
      "dot-size": "2px",
      "cell-background": "surface",
      "cell-border": true,
      "cell-radius": "0px",
      "cell-padding": "14px",
      "hover-effect": "none",
    },
  },
};
