import type { SigilPreset } from "@sigil-ui/tokens";
import { completePreset } from "./_template";

export const arcPreset: SigilPreset = completePreset({
  name: "arc",
  metadata: {
    description:
      "Flowing curves. Elegant arcs, smooth gradients, generous spacing, and graceful motion.",
    mood: "flowing, curved, graceful",
    tags: ["light", "elegant", "curved", "soft", "gradients"],
  },
  tokens: {
    colors: {
      background: { light: "oklch(0.9691 0.0161 293.7557)", dark: "oklch(0.2352 0.0362 290.5754)" },
      surface: { light: "oklch(0.9433 0.0284 294.5878)", dark: "oklch(0.2684 0.0442 290.7518)" },
      "surface-elevated": { light: "oklch(1 0 0)", dark: "oklch(0.3084 0.0516 290.9689)" },
      "surface-sunken": { light: "oklch(0.9292 0.0325 293.4068)", dark: "oklch(0.2062 0.043 286.1403)" },
      primary: "oklch(0.5531 0.246 292.9129)",
      "primary-hover": "oklch(0.4907 0.2412 292.5809)",
      "primary-muted": "oklch(0.5413 0.2466 293.009 / 0.1882)",
      "primary-contrast": "oklch(1 0 0)",
      secondary: "oklch(0.6268 0.2325 303.9004)",
      "secondary-hover": "oklch(0.5575 0.2525 302.3212)",
      "secondary-muted": "oklch(0.6268 0.2325 303.9004 / 0.1882)",
      accent: "oklch(0.645 0.2154 16.4393)",
      "accent-hover": "oklch(0.5858 0.222 17.5846)",
      "accent-muted": "oklch(0.645 0.2154 16.4393 / 0.1451)",
      text: { light: "oklch(0.2245 0.0478 291.2486)", dark: "oklch(0.9433 0.0284 294.5878)" },
      "text-secondary": { light: "oklch(0.3681 0.0711 290.0994)", dark: "oklch(0.8112 0.1013 293.5712)" },
      "text-muted": { light: "oklch(0.5253 0.1008 290.9924)", dark: "oklch(0.6862 0.0747 292.4047)" },
      "text-subtle": { light: "oklch(0.6297 0.0794 293.5088)", dark: "oklch(0.6053 0.0737 299.4885)" },
      "text-disabled": { light: "oklch(0.7596 0.0631 301.8992)", dark: "oklch(0.3922 0.0694 297.7135)" },
      "text-inverse": { light: "oklch(0.9433 0.0284 294.5878)", dark: "oklch(0.2245 0.0478 291.2486)" },
      border: { light: "oklch(0.6414 0.0537 292.4592)", dark: "oklch(0.380 0.035 292)" },
      "border-muted": { light: "oklch(0.8113 0.0393 293.695)", dark: "oklch(0.320 0.025 292)" },
      "border-strong": { light: "oklch(0.6448 0.1025 293.9817)", dark: "oklch(0.480 0.045 291)" },
      "border-interactive": { light: "oklch(0.5413 0.2466 293.009)", dark: "oklch(0.5413 0.2466 293.009)" },
      success: "oklch(0.6201 0.1393 160.419)",
      "success-muted": "oklch(0.7729 0.1535 163.2231 / 0.1451)",
      warning: "oklch(0.6424 0.1344 76.9066)",
      "warning-muted": "oklch(0.8369 0.1644 84.4286 / 0.1451)",
      error: "oklch(0.6573 0.1661 22.3516)",
      "error-muted": "oklch(0.7106 0.1661 22.2162 / 0.1451)",
      info: "oklch(0.6379 0.1431 254.7237)",
      "info-muted": "oklch(0.7137 0.1434 254.624 / 0.1451)",
      "gradient-start": "oklch(0.5413 0.2466 293.009)",
      "gradient-end": "oklch(0.645 0.2154 16.4393)",
      glow: "oklch(0.5413 0.2466 293.009 / 0.251)",
      highlight: { light: "oklch(0.9433 0.0284 294.5878)", dark: "oklch(0.6056 0.2189 292.7172 / 0.15)" },
    },
    typography: {
      "font-display": "'PP Pangram Sans', system-ui, sans-serif",
      "font-body": "'PP Pangram Sans', system-ui, sans-serif",
      "font-mono": "'PP Supply Mono', ui-monospace, monospace",
      "size-xs": "0.75rem",
      "size-sm": "0.8125rem",
      "size-base": "1rem",
      "size-lg": "1.125rem",
      "size-xl": "1.25rem",
      "size-2xl": "1.5rem",
      "size-3xl": "1.875rem",
      "size-4xl": "2.25rem",
      "size-5xl": "3rem",
      "size-6xl": "3.75rem",
      "weight-normal": "400",
      "weight-medium": "500",
      "weight-semibold": "600",
      "weight-bold": "700",
      "weight-extrabold": "800",
      "leading-tight": "1.25",
      "leading-normal": "1.6",
      "leading-relaxed": "1.75",
      "leading-loose": "2",
      "tracking-tighter": "-0.03em",
      "tracking-tight": "-0.015em",
      "tracking-normal": "0em",
      "tracking-wide": "0.015em",
      "tracking-wider": "0.03em",
      "heading-weight": "500",
      "heading-tracking": "-0.01em",
      "heading-transform": "none",
      "heading-family": "'PP Pangram Sans', system-ui, sans-serif",
    },
    spacing: {
      scale: [4, 8, 16, 24, 32, 40, 56, 72, 96, 120],
      unit: "px",
      "button-px": "28px",
      "button-py": "12px",
      "button-px-sm": "18px",
      "button-py-sm": "8px",
      "button-px-lg": "36px",
      "button-py-lg": "16px",
      "card-padding": "32px",
      "card-padding-sm": "20px",
      "card-padding-lg": "44px",
      "input-px": "14px",
      "input-py": "10px",
      "badge-px": "10px",
      "badge-py": "4px",
      "section-py": "7rem",
      "section-py-lg": "10.5rem",
      "navbar-height": "56px",
      "navbar-px": "32px",
      "footer-py": "56px",
      "modal-padding": "28px",
      "popover-padding": "18px",
      "tooltip-padding": "8px 14px",
      "table-cell-px": "18px",
      "table-cell-py": "12px",
    },
    layout: {
      "content-max": "1200px",
      "content-max-narrow": "720px",
      "content-max-wide": "1440px",
      "page-margin": "32px",
      "page-margin-sm": "18px",
      "page-margin-lg": "64px",
      gutter: "0px",
      "gutter-sm": "0px",
      "gutter-lg": "0px",
      "grid-columns": "12",
      "grid-gap": "32px",
      "bento-gap": "22px",
      "bento-radius": "24px",
      "bento-min-height": "196px",
      "section-gap": "28px",
      "sidebar-width": "280px",
      "sidebar-collapsed": "60px",
      "footer-columns": "4",
      "stack-gap": "18px",
      "stack-gap-sm": "10px",
      "stack-gap-lg": "28px",
      "prose-max": "65ch",
    },
    sigil: {
      "grid-cell": "56px",
      "cross-arm": "0px",
      "cross-stroke": "0px",
      "rail-gap": "0px",
      "card-radius": "24px",
      "gutter-pattern": "none",
      "margin-pattern": "none",
      "gutter-border": "none",
      "gutter-visible": false,
      "band-height": "56px",
      "divider-thickness-sm": "calc(var(--s-grid-cell) / 2)",
      "divider-thickness-md": "var(--s-grid-cell)",
      "divider-thickness-lg": "calc(2 * var(--s-grid-cell))",
      "divider-thickness-xl": "calc(3 * var(--s-grid-cell))",
    },
    radius: {
      none: "0px",
      sm: "8px",
      md: "12px",
      lg: "20px",
      xl: "24px",
      "2xl": "28px",
      full: "9999px",
      button: "20px",
      card: "24px",
      input: "12px",
      badge: "9999px",
      modal: "24px",
      popover: "20px",
      tooltip: "12px",
      image: "20px",
      bento: "24px",
    },
    shadows: {
      sm: "0 1px 3px rgb(124 58 237 / 0.06)",
      md: "0 2px 8px rgb(124 58 237 / 0.08)",
      lg: "0 4px 16px rgb(124 58 237 / 0.1)",
      xl: "0 8px 30px rgb(124 58 237 / 0.12)",
      "2xl": "0 20px 50px rgb(124 58 237 / 0.18)",
      glow: "0 0 24px #7c3aed33",
      "glow-sm": "0 0 12px #7c3aed22",
      colored: "0 4px 18px -4px #7c3aed44",
      inner: "inset 0 2px 4px rgb(124 58 237 / 0.04)",
      card: "0 2px 12px rgb(124 58 237 / 0.06)",
      button: "none",
      "button-hover": "0 4px 12px rgb(124 58 237 / 0.15)",
      dropdown: "0 8px 24px rgb(124 58 237 / 0.12)",
      modal: "0 24px 64px rgb(124 58 237 / 0.18)",
    },
    motion: {
      duration: { instant: "0ms", fast: "200ms", normal: "350ms", slow: "500ms", slower: "700ms", slowest: "1200ms" },
      easing: {
        default: "cubic-bezier(0, 0.55, 0.45, 1)",
        in: "cubic-bezier(0.55, 0, 1, 0.45)",
        out: "cubic-bezier(0, 0.55, 0.45, 1)",
        "in-out": "cubic-bezier(0.45, 0, 0.55, 1)",
        spring: "cubic-bezier(0.34, 1.56, 0.64, 1)",
        bounce: "cubic-bezier(0.68, -0.55, 0.27, 1.55)",
      },
      "enter-preset": "fadeUp",
      "exit-preset": "fadeDown",
      "hover-scale": "1.02",
      "press-scale": "0.98",
      "hover-lift": "-4px",
      "stagger-interval": "60ms",
      "stagger-interval-fast": "30ms",
    },
    borders: {
      width: { none: "0px", thin: "1px", medium: "1.5px", thick: "2px" },
      style: "solid",
      "card-border": "0px solid",
      "card-border-hover": "0px solid",
      "button-border": "0px solid",
      "input-border": "1px solid",
      "divider-style": "solid",
      "divider-width": "1px",
    },
    buttons: {
      "font-weight": "500",
      "text-transform": "none",
      "letter-spacing": "0em",
      "font-family": "'PP Pangram Sans', system-ui, sans-serif",
      "border-width": "0px",
      "hover-effect": "fill",
      "active-scale": "0.98",
      "icon-gap": "8px",
      "min-width": "0px",
    },
    cards: {
      "border-style": "none",
      "border-width": "0px",
      "hover-effect": "glow",
      "hover-border-color": "transparent",
      padding: "28px",
      "header-padding": "28px 28px 0",
      "footer-padding": "0 28px 28px",
      "title-size": "1.125rem",
      "title-weight": "600",
      "description-size": "0.875rem",
      outline: true,
      shadow: "lg",
      background: "elevated",
    },
    headings: {
      "h1-size": "2.25rem",
      "h1-weight": "600",
      "h1-tracking": "-0.02em",
      "h1-leading": "1.2",
      "h2-size": "1.875rem",
      "h2-weight": "600",
      "h2-tracking": "-0.015em",
      "h2-leading": "1.15",
      "h3-size": "1.5rem",
      "h3-weight": "500",
      "h3-tracking": "0em",
      "h3-leading": "1.2",
      "h4-size": "1.25rem",
      "h4-weight": "500",
      "h4-tracking": "0em",
      "h4-leading": "1.3",
      "display-size": "3.75rem",
      "display-weight": "700",
      "display-tracking": "-0.03em",
      "display-leading": "1.1",
    },
    navigation: {
      "navbar-height": "56px",
      "navbar-backdrop-blur": "24px",
      "navbar-border": "none",
      "navbar-bg-opacity": "0.7",
      "navbar-padding-x": "28px",
      "navbar-position": "sticky",
      "navbar-logo-height": "24px",
      "navbar-logo-gap": "10px",
      "navbar-item-gap": "28px",
      "navbar-item-padding-x": "12px",
      "navbar-item-padding-y": "6px",
      "navbar-item-size": "0.875rem",
      "navbar-shadow": "none",
      "navbar-height-scrolled": "48px",
      "navbar-mobile-breakpoint": "768px",
      "nav-link-weight": "500",
      "nav-link-size": "0.875rem",
      "nav-link-hover": "background",
      "breadcrumb-separator": " / ",
      "pagination-radius": "20px",
      "sidebar-width": "280px",
      "sidebar-item-radius": "16px",
      "sidebar-item-padding": "10px 16px",
    },
    backgrounds: {
      pattern: "none",
      "pattern-opacity": "0",
      "pattern-scale": "1",
      noise: true,
      "noise-opacity": "0.02",
      "gradient-angle": "135deg",
      "gradient-type": "radial",
      "hero-pattern": "radial-glow",
      "section-divider": "wave",
    },
    code: {
      "font-family": "'PP Supply Mono', ui-monospace, monospace",
      "font-size": "0.8125rem",
      "line-height": "1.7",
      bg: "var(--s-surface-sunken)",
      border: "0px solid transparent",
      "border-radius": "16px",
      padding: "18px",
      "tab-size": "2",
      "selection-bg": "#7c3aed25",
      "comment-color": "var(--s-text-muted)",
      "keyword-color": "#7c3aed",
      "string-color": "#34d399",
      "number-color": "#fbbf24",
      "function-color": "#60a5fa",
    },
    inputs: {
      height: "42px",
      "height-sm": "34px",
      "height-lg": "50px",
      "border-width": "1px",
      "focus-ring-width": "2px",
      "focus-ring-color": "#7c3aed",
      "focus-ring-offset": "2px",
      "placeholder-color": "var(--s-text-subtle)",
      "error-border-color": "var(--s-error)",
      "label-size": "0.8125rem",
      "label-weight": "500",
      "label-spacing": "8px",
      "helper-size": "0.75rem",
    },
    alignment: {
      "title-align": "center",
      "rail-margin": "40px",
    },
    sections: {
      "padding-y": "7rem",
      "padding-y-hero": "10.5rem",
      "padding-y-sm": "3.5rem",
      gap: "40px",
      "padding-y-lg": "10.5rem",
      "padding-y-xl": "14rem",
      "title-align": "center",
      "heading-size": "clamp(1.5rem, 4vw, 2.25rem)",
      "heading-align": "center",
      "heading-max-width": "40rem",
      "heading-margin-bottom": "16px",
      "description-max-width": "32rem",
      "description-gap": "12px",
      "content-gap": "28px",
      "grid-columns": "3",
      "grid-gap": "28px",
      "alternate-bg": "var(--s-surface)",
      "alternate-bg-mode": "none",
      "max-width": "1080px",
    },
    dividers: {
      style: "none",
      spacing: "0px",
      opacity: "0.6",
      "max-width": "100%",
      "margin-y": "0px",
      thickness: "1px",
      "gradient-start": "transparent",
      "gradient-end": "transparent",
    },
    gridVisuals: {
      "line-color": "var(--s-border-muted)",
      "line-width": "1px",
      "show-lines": false,
      "show-dots": false,
      "cell-radius": "20px",
    },
    cursor: {
      variant: "dot",
      size: "24px",
      "dot-size": "4px",
      "stroke-width": "1.5px",
      "tick-size": "6px",
      gap: "3px",
      radius: "0px",
      color: "var(--s-text)",
      "ring-color": "var(--s-primary)",
      "dot-color": "var(--s-primary)",
      glow: "none",
      opacity: "1",
      "blend-mode": "normal",
      "z-index": "9999",
      "hide-native": false,
    },
    scrollbar: {
      width: "6px",
      height: "6px",
      padding: "2px",
      radius: "9999px",
      track: "transparent",
      thumb: "var(--s-border-muted)",
      "thumb-hover": "var(--s-border)",
      "thumb-active": "var(--s-border-strong)",
      corner: "transparent",
      border: "none",
      "firefox-width": "thin",
      gutter: "stable",
      visibility: "auto",
    },
    focus: {
      "ring-width": "2px",
      "ring-color": "var(--s-primary)",
      "ring-offset": "2px",
      "ring-shadow": "0 0 0 2px var(--s-primary)",
      "outline-color": "var(--s-primary)",
    },
    overlays: {
      bg: "rgb(0 0 0 / 0.4)",
      blur: "4px",
      surface: "var(--s-surface-elevated)",
      border: "1px solid var(--s-border-muted)",
      shadow: "var(--s-shadow-xl)",
      radius: "var(--s-radius-lg)",
      padding: "20px",
      "z-index": "50",
    },
    dataViz: {
      "series-1": "var(--s-primary)",
      "series-2": "var(--s-secondary)",
      "series-3": "var(--s-accent)",
      "series-4": "var(--s-info)",
      "series-5": "var(--s-success)",
      positive: "var(--s-success)",
      negative: "var(--s-error)",
      neutral: "var(--s-text-muted)",
      grid: "var(--s-border-muted)",
      axis: "var(--s-border)",
      label: "var(--s-text-secondary)",
      "tooltip-bg": "var(--s-surface-elevated)",
      "tooltip-border": "var(--s-border-muted)",
    },
    media: {
      radius: "var(--s-radius-md)",
      border: "none",
      outline: "1px solid rgb(0 0 0 / 0.08)",
      shadow: "none",
      bg: "var(--s-surface-sunken)",
      "object-fit": "cover",
    },
    controls: {
      height: "38px",
      "height-sm": "30px",
      "height-lg": "46px",
      "hit-area": "44px",
      "icon-size": "16px",
      "handle-size": "20px",
      "track-height": "4px",
      "track-bg": "var(--s-border-muted)",
      "track-fill": "var(--s-primary)",
      "thumb-bg": "var(--s-surface-elevated)",
      "thumb-border": "2px solid var(--s-primary)",
    },
    componentSurfaces: {
      bg: "var(--s-surface)",
      "bg-elevated": "var(--s-surface-elevated)",
      "bg-muted": "var(--s-surface-sunken)",
      border: "var(--s-border)",
      "border-muted": "var(--s-border-muted)",
      "border-strong": "var(--s-border-strong)",
      text: "var(--s-text)",
      "text-muted": "var(--s-text-muted)",
      contrast: "var(--s-primary-contrast)",
      "hover-bg": "var(--s-surface-elevated)",
      "active-bg": "var(--s-surface-sunken)",
      "selected-bg": "var(--s-primary-muted)",
    },
    hero: {
      "min-height": "auto",
      "padding-y": "112px",
      "padding-y-sm": "84px",
      "padding-x": "var(--s-page-margin, 28px)",
      "content-max": "640px",
      "content-basis": "min(42%, var(--s-hero-content-max, 640px))",
      "content-align": "center",
      layout: "centered",
      "media-position": "below",
      "media-width": "50%",
      "media-radius": "var(--s-radius-lg)",
      "split-gap": "var(--s-section-subsection-gap, var(--s-grid-cell))",
      "title-size": "clamp(2.5rem, 6vw, 4.5rem)",
      "title-max-width": "56rem",
      "description-size": "1.125rem",
      "description-max-width": "32rem",
      "description-gap": "28px",
      "actions-gap": "12px",
      "actions-margin-top": "40px",
      "action-padding-x": "28px",
      "action-padding-y": "12px",
      "badge-gap": "28px",
      "overlay-opacity": "0.3",
      "scroll-indicator": false,
      "gradient-overlay": "none",
    },
    cta: {
      "padding-y": "84px",
      "padding-x": "var(--s-page-margin, 28px)",
      "max-width": "var(--s-content-max, 1200px)",
      layout: "centered",
      border: false,
      "border-radius": "var(--s-radius-lg)",
      bg: "var(--s-surface)",
      "title-size": "clamp(1.5rem, 4vw, 2.5rem)",
      "description-max-width": "32rem",
      "description-gap": "14px",
      "actions-gap": "12px",
      "actions-margin-top": "36px",
      "action-padding-x": "28px",
      "action-padding-y": "14px",
      "split-gap": "56px",
    },
    footer: {
      "padding-y": "56px",
      "border-top": "1px solid var(--s-border-muted)",
      columns: "4",
      "column-gap": "36px",
      "row-gap": "32px",
      "logo-height": "24px",
      "tagline-max-width": "22rem",
      "link-size": "0.875rem",
      "link-gap": "10px",
      "group-title-size": "0.8125rem",
      "group-title-weight": "500",
      "social-icon-size": "18px",
      "social-gap": "14px",
      "bottom-bar-padding": "28px 0",
      "bottom-bar-border": "1px solid var(--s-border-muted)",
    },
    banner: {
      height: "auto",
      "padding-y": "10px",
      "padding-x": "20px",
      "font-size": "0.8125rem",
      "font-weight": "400",
      "icon-size": "14px",
      "icon-gap": "10px",
      "border-width": "1px",
      "border-position": "bottom",
      position: "top",
      "dismiss-size": "14px",
      radius: "0px",
    },
    pageRhythm: {
      mode: "locked",
      snap: true,
      "band-stroke": "visual",
      "hairline-width": "1px",
      "hairline-spacing": "var(--s-section-gap, 0px)",
      "hairline-style": "solid",
      density: "spacious",
      "section-gap": "0px",
      "section-gap-sm": "0px",
      "section-gap-lg": "0px",
      "first-section-offset": "0px",
      "last-section-margin": "0px",
      "alternate-bg": false,
      "alternate-bg-color": "var(--s-surface)",
      "divider-between": false,
      "max-content-width": "var(--s-content-max, 1200px)",
      "vertical-rhythm-unit": "8px",
      "scroll-snap": false,
      "responsive-scale": "0.85",
      "responsive-breakpoint": "768px",
    },

  },
});
