import type { SigilPreset } from "@sigil-ui/tokens";

export const arcPreset: SigilPreset = {
  name: "arc",
  metadata: {
    description:
      "Flowing curves. Elegant arcs, smooth gradients, generous spacing, and graceful motion.",
    mood: "flowing, curved, graceful",
    tags: ["light", "elegant", "curved", "soft", "gradients"],
  },
  tokens: {
    colors: {
      background: { light: "#f5f3ff", dark: "#1e1b2e" },
      surface: { light: "#ede9fe", dark: "#26223a" },
      "surface-elevated": { light: "#ffffff", dark: "#302b48" },
      "surface-sunken": { light: "#e8e4fc", dark: "#16142a" },
      primary: "#7f3ff1",
      "primary-hover": "#6d28d9",
      "primary-muted": "#7c3aed30",
      "primary-contrast": "#ffffff",
      secondary: "#a855f7",
      "secondary-hover": "#9333ea",
      "secondary-muted": "#a855f730",
      accent: "#f43f5e",
      "accent-hover": "#e11d48",
      "accent-muted": "#f43f5e25",
      text: { light: "#1c1730", dark: "#ede9fe" },
      "text-secondary": { light: "#3f3862", dark: "#c4b5fd" },
      "text-muted": { light: "#6b5fa0", dark: "#9b92c5" },
      "text-subtle": { light: "#8b80b5", dark: "#8878a8" },
      "text-disabled": { light: "#b8a8d3", dark: "#4a3d66" },
      "text-inverse": { light: "#ede9fe", dark: "#1c1730" },
      border: { light: "#8d87ab", dark: "#6d6396" },
      "border-muted": { light: "#ede9fe", dark: "#3d3460" },
      "border-strong": { light: "#9181c6", dark: "#6e60a6" },
      "border-interactive": { light: "#7c3aed", dark: "#7c3aed" },
      success: "#009f69",
      "success-muted": "#34d39925",
      warning: "#ba8000",
      "warning-muted": "#fbbf2425",
      error: "#e56061",
      "error-muted": "#f8717125",
      info: "#498de0",
      "info-muted": "#60a5fa25",
      "gradient-start": "#7c3aed",
      "gradient-end": "#f43f5e",
      glow: "#7c3aed40",
    },
    typography: {
      "font-display": "'PP Pangram Sans', system-ui, sans-serif",
      "font-body": "'PP Pangram Sans', system-ui, sans-serif",
      "font-mono": "'PP Supply Mono', ui-monospace, monospace",
      "size-xs": "0.75rem",
      "size-sm": "0.8125rem",
      "size-base": "1rem",
      "size-lg": "1.125rem",
      "size-xl": "1.25rem",
      "size-2xl": "1.5rem",
      "size-3xl": "1.875rem",
      "size-4xl": "2.25rem",
      "size-5xl": "3rem",
      "size-6xl": "3.75rem",
      "weight-normal": "400",
      "weight-medium": "500",
      "weight-semibold": "600",
      "weight-bold": "700",
      "weight-extrabold": "800",
      "leading-tight": "1.25",
      "leading-normal": "1.6",
      "leading-relaxed": "1.75",
      "leading-loose": "2",
      "tracking-tighter": "-0.03em",
      "tracking-tight": "-0.015em",
      "tracking-normal": "0em",
      "tracking-wide": "0.015em",
      "tracking-wider": "0.03em",
      "heading-weight": "500",
      "heading-tracking": "-0.01em",
      "heading-transform": "none",
      "heading-family": "'PP Pangram Sans', system-ui, sans-serif",
    },
    spacing: {
      scale: [4, 8, 16, 24, 32, 40, 56, 72, 96, 120],
      unit: "px",
      "button-px": "28px",
      "button-py": "12px",
      "button-px-sm": "18px",
      "button-py-sm": "8px",
      "button-px-lg": "36px",
      "button-py-lg": "16px",
      "card-padding": "32px",
      "card-padding-sm": "20px",
      "card-padding-lg": "44px",
      "input-px": "14px",
      "input-py": "10px",
      "badge-px": "10px",
      "badge-py": "4px",
      "section-py": "88px",
      "section-py-lg": "136px",
      "navbar-height": "64px",
      "navbar-px": "32px",
      "footer-py": "64px",
      "modal-padding": "28px",
      "popover-padding": "18px",
      "tooltip-padding": "8px 14px",
      "table-cell-px": "18px",
      "table-cell-py": "12px",
    },
    layout: {
      "content-max": "1200px",
      "content-max-narrow": "720px",
      "content-max-wide": "1440px",
      "page-margin": "32px",
      "page-margin-sm": "18px",
      "page-margin-lg": "64px",
      gutter: "0px",
      "gutter-sm": "0px",
      "gutter-lg": "0px",
      "grid-columns": "12",
      "grid-gap": "32px",
      "bento-gap": "22px",
      "bento-radius": "24px",
      "bento-min-height": "200px",
      "section-gap": "40px",
      "sidebar-width": "280px",
      "sidebar-collapsed": "60px",
      "footer-columns": "4",
      "stack-gap": "18px",
      "stack-gap-sm": "10px",
      "stack-gap-lg": "28px",
      "prose-max": "65ch",
    },
    sigil: {
      "grid-cell": "56px",
      "cross-arm": "0px",
      "cross-stroke": "0px",
      "rail-gap": "0px",
      "card-radius": "24px",
      "gutter-pattern": "none",
      "margin-pattern": "none",
      "gutter-border": "none",
      "gutter-visible": false,
    },
    radius: {
      none: "0px",
      sm: "8px",
      md: "12px",
      lg: "20px",
      xl: "24px",
      "2xl": "28px",
      full: "9999px",
      button: "20px",
      card: "24px",
      input: "12px",
      badge: "9999px",
      modal: "24px",
      popover: "20px",
      tooltip: "12px",
      image: "20px",
      bento: "24px",
    },
    shadows: {
      sm: "0 1px 3px rgb(124 58 237 / 0.06)",
      md: "0 2px 8px rgb(124 58 237 / 0.08)",
      lg: "0 4px 16px rgb(124 58 237 / 0.1)",
      xl: "0 8px 30px rgb(124 58 237 / 0.12)",
      "2xl": "0 20px 50px rgb(124 58 237 / 0.18)",
      glow: "0 0 24px #7c3aed33",
      "glow-sm": "0 0 12px #7c3aed22",
      colored: "0 4px 18px -4px #7c3aed44",
      inner: "inset 0 2px 4px rgb(124 58 237 / 0.04)",
      card: "0 2px 12px rgb(124 58 237 / 0.06)",
      button: "none",
      "button-hover": "0 4px 12px rgb(124 58 237 / 0.15)",
      dropdown: "0 8px 24px rgb(124 58 237 / 0.12)",
      modal: "0 24px 64px rgb(124 58 237 / 0.18)",
    },
    motion: {
      duration: { instant: "0ms", fast: "200ms", normal: "350ms", slow: "500ms", slower: "700ms", slowest: "1200ms" },
      easing: {
        default: "cubic-bezier(0, 0.55, 0.45, 1)",
        in: "cubic-bezier(0.55, 0, 1, 0.45)",
        out: "cubic-bezier(0, 0.55, 0.45, 1)",
        "in-out": "cubic-bezier(0.45, 0, 0.55, 1)",
        spring: "cubic-bezier(0.34, 1.56, 0.64, 1)",
        bounce: "cubic-bezier(0.68, -0.55, 0.27, 1.55)",
      },
      "enter-preset": "fadeUp",
      "exit-preset": "fadeDown",
      "hover-scale": "1.02",
      "press-scale": "0.98",
      "hover-lift": "-4px",
      "stagger-interval": "60ms",
      "stagger-interval-fast": "30ms",
    },
    borders: {
      width: { none: "0px", thin: "1px", medium: "1.5px", thick: "2px" },
      style: "solid",
      "card-border": "0px solid",
      "card-border-hover": "0px solid",
      "button-border": "0px solid",
      "input-border": "1px solid",
      "divider-style": "solid",
      "divider-width": "1px",
    },
    buttons: {
      "font-weight": "500",
      "text-transform": "none",
      "letter-spacing": "0em",
      "font-family": "'PP Pangram Sans', system-ui, sans-serif",
      "border-width": "0px",
      "hover-effect": "fill",
      "active-scale": "0.98",
      "icon-gap": "8px",
      "min-width": "0px",
    },
    cards: {
      "border-style": "none",
      "border-width": "0px",
      "hover-effect": "glow",
      "hover-border-color": "transparent",
      padding: "28px",
      "header-padding": "28px 28px 0",
      "footer-padding": "0 28px 28px",
      "title-size": "1.125rem",
      "title-weight": "600",
      "description-size": "0.875rem",
      outline: true,
      shadow: "lg",
      background: "elevated",
    },
    headings: {
      "h1-size": "2.25rem",
      "h1-weight": "600",
      "h1-tracking": "-0.02em",
      "h1-leading": "1.2",
      "h2-size": "1.875rem",
      "h2-weight": "600",
      "h2-tracking": "-0.015em",
      "h3-size": "1.5rem",
      "h3-weight": "500",
      "h4-size": "1.25rem",
      "h4-weight": "500",
      "display-size": "3.75rem",
      "display-weight": "700",
      "display-tracking": "-0.03em",
      "display-leading": "1.1",
    },
    navigation: {
      "navbar-height": "64px",
      "navbar-backdrop-blur": "24px",
      "navbar-border": "none",
      "navbar-bg-opacity": "0.7",
      "nav-link-weight": "500",
      "nav-link-size": "0.875rem",
      "nav-link-hover": "background",
      "breadcrumb-separator": " / ",
      "pagination-radius": "20px",
      "sidebar-width": "280px",
      "sidebar-item-radius": "16px",
      "sidebar-item-padding": "10px 16px",
    },
    backgrounds: {
      pattern: "none",
      "pattern-opacity": "0",
      "pattern-scale": "1",
      noise: true,
      "noise-opacity": "0.02",
      "gradient-angle": "135deg",
      "gradient-type": "radial",
      "hero-pattern": "radial-glow",
      "section-divider": "wave",
    },
    code: {
      "font-family": "'PP Supply Mono', ui-monospace, monospace",
      "font-size": "0.8125rem",
      "line-height": "1.7",
      bg: "var(--s-surface-sunken)",
      border: "0px solid transparent",
      "border-radius": "16px",
      padding: "18px",
      "tab-size": "2",
      "selection-bg": "#7c3aed25",
      "comment-color": "var(--s-text-muted)",
      "keyword-color": "#7c3aed",
      "string-color": "#34d399",
      "number-color": "#fbbf24",
      "function-color": "#60a5fa",
    },
    inputs: {
      height: "42px",
      "height-sm": "34px",
      "height-lg": "50px",
      "border-width": "1px",
      "focus-ring-width": "2px",
      "focus-ring-color": "#7c3aed",
      "focus-ring-offset": "2px",
      "placeholder-color": "var(--s-text-subtle)",
      "error-border-color": "var(--s-error)",
      "label-size": "0.8125rem",
      "label-weight": "500",
      "label-spacing": "8px",
      "helper-size": "0.75rem",
    },
    alignment: {
      "title-align": "center",
      "rail-margin": "40px",
    },
    sections: {
      "padding-y": "80px",
      "padding-y-hero": "160px",
      gap: "40px",
      "max-width": "1080px",
    },
    dividers: {
      style: "none",
    },
    gridVisuals: {
      "show-lines": false,
      "show-dots": false,
      "cell-radius": "20px",
    },
  },
};
