import type { SigilPreset } from "@sigil-ui/tokens";

export const auraPreset: SigilPreset = {
  name: "aura",
  metadata: {
    description: "Ethereal dark with luminous violet glow. No gutter decoration, ambient gradients.",
    mood: "ethereal, luminous, ambient",
    tags: ["edgeless", "dark", "glow", "violet", "ambient"],
  },
  tokens: {
    colors: {
      background: { light: "oklch(0.97 0.01 280)", dark: "oklch(0.08 0.02 280)" },
      surface: { light: "oklch(0.95 0.012 280)", dark: "oklch(0.12 0.025 280)" },
      "surface-elevated": { light: "oklch(1 0.005 280)", dark: "oklch(0.16 0.03 280)" },
      "surface-sunken": { light: "oklch(0.93 0.015 280)", dark: "oklch(0.05 0.015 280)" },
      primary: { light: "oklch(0.55 0.22 290)", dark: "oklch(0.70 0.20 290)" },
      "primary-hover": { light: "oklch(0.48 0.25 290)", dark: "oklch(0.76 0.18 290)" },
      "primary-muted": { light: "oklch(0.55 0.08 290)", dark: "oklch(0.70 0.06 290)" },
      "primary-contrast": { light: "oklch(1 0 0)", dark: "oklch(0.08 0.02 280)" },
      secondary: "oklch(0.60 0.15 220)",
      "secondary-hover": "oklch(0.54 0.17 220)",
      "secondary-muted": "oklch(0.60 0.05 220)",
      accent: "oklch(0.65 0.18 330)",
      "accent-hover": "oklch(0.58 0.20 330)",
      "accent-muted": "oklch(0.65 0.06 330)",
      text: { light: "oklch(0.15 0.01 280)", dark: "oklch(0.92 0.01 280)" },
      "text-secondary": { light: "oklch(0.35 0.01 280)", dark: "oklch(0.72 0.015 280)" },
      "text-muted": { light: "oklch(0.50 0.015 280)", dark: "oklch(0.55 0.02 280)" },
      "text-subtle": { light: "oklch(0.65 0.01 280)", dark: "oklch(0.40 0.02 280)" },
      "text-disabled": { light: "oklch(0.78 0.005 280)", dark: "oklch(0.28 0.01 280)" },
      "text-inverse": { light: "oklch(0.92 0.01 280)", dark: "oklch(0.15 0.01 280)" },
      border: { light: "oklch(0.85 0.015 280)", dark: "oklch(0.260 0.030 280)" },
      "border-muted": { light: "oklch(0.92 0.008 280)", dark: "oklch(0.200 0.020 280)" },
      "border-strong": { light: "oklch(0.75 0.02 280)", dark: "oklch(0.340 0.040 280)" },
      "border-interactive": { light: "oklch(0.55 0.22 290)", dark: "oklch(0.70 0.20 290)" },
      success: "oklch(0.65 0.17 160)",
      "success-muted": { light: "oklch(0.95 0.03 160)", dark: "oklch(0.14 0.04 160)" },
      warning: "oklch(0.72 0.14 85)",
      "warning-muted": { light: "oklch(0.96 0.03 85)", dark: "oklch(0.16 0.04 85)" },
      error: "oklch(0.58 0.20 25)",
      "error-muted": { light: "oklch(0.96 0.03 25)", dark: "oklch(0.16 0.04 25)" },
      info: "oklch(0.60 0.15 250)",
      "info-muted": { light: "oklch(0.96 0.02 250)", dark: "oklch(0.16 0.03 250)" },
      "gradient-start": { light: "oklch(0.55 0.22 290)", dark: "oklch(0.70 0.20 290)" },
      "gradient-end": { light: "oklch(0.60 0.15 220)", dark: "oklch(0.60 0.15 220)" },
      glow: { light: "oklch(0.55 0.22 290 / 0.2)", dark: "oklch(0.70 0.20 290 / 0.15)" },
      highlight: { light: "oklch(0.92 0.08 290)", dark: "oklch(0.28 0.06 290)" },
    },
    typography: {
      "font-display": "'General Sans', 'Satoshi', system-ui, sans-serif",
      "font-body": "'General Sans', 'Inter', system-ui, sans-serif",
      "font-mono": "'JetBrains Mono', ui-monospace, monospace",
      "size-xs": "0.75rem",
      "size-sm": "0.8125rem",
      "size-base": "0.875rem",
      "size-lg": "1rem",
      "size-xl": "1.125rem",
      "size-2xl": "1.375rem",
      "size-3xl": "1.75rem",
      "size-4xl": "2.25rem",
      "size-5xl": "3rem",
      "size-6xl": "3.75rem",
      "weight-normal": "400",
      "weight-medium": "500",
      "weight-semibold": "600",
      "weight-bold": "700",
      "weight-extrabold": "800",
      "leading-tight": "1.2",
      "leading-normal": "1.5",
      "leading-relaxed": "1.625",
      "leading-loose": "2",
      "tracking-tighter": "-0.04em",
      "tracking-tight": "-0.025em",
      "tracking-normal": "0em",
      "tracking-wide": "0.025em",
      "tracking-wider": "0.05em",
      "heading-weight": "600",
      "heading-tracking": "-0.03em",
      "heading-transform": "none",
      "heading-family": "'General Sans', 'Satoshi', system-ui, sans-serif",
    },
    spacing: {
      scale: [4, 8, 12, 16, 24, 32, 48, 64, 80, 96],
      unit: "px",
      "button-px": "20px",
      "button-py": "10px",
      "button-px-sm": "14px",
      "button-py-sm": "7px",
      "button-px-lg": "28px",
      "button-py-lg": "12px",
      "card-padding": "28px",
      "card-padding-sm": "18px",
      "card-padding-lg": "40px",
      "input-px": "14px",
      "input-py": "10px",
      "badge-px": "10px",
      "badge-py": "3px",
      "section-py": "96px",
      "section-py-lg": "128px",
      "navbar-height": "60px",
      "navbar-px": "24px",
      "footer-py": "64px",
      "modal-padding": "28px",
      "popover-padding": "16px",
      "tooltip-padding": "8px 12px",
      "table-cell-px": "16px",
      "table-cell-py": "12px",
    },
    layout: {
      "content-max": "1200px",
      "content-max-narrow": "720px",
      "content-max-wide": "1440px",
      "page-margin": "28px",
      "page-margin-sm": "16px",
      "page-margin-lg": "48px",
      gutter: "0px",
      "gutter-sm": "0px",
      "gutter-lg": "0px",
      "grid-columns": "12",
      "grid-gap": "24px",
      "bento-gap": "16px",
      "bento-radius": "12px",
      "bento-min-height": "200px",
      "section-gap": "32px",
      "sidebar-width": "260px",
      "sidebar-collapsed": "56px",
      "footer-columns": "4",
      "stack-gap": "16px",
      "stack-gap-sm": "8px",
      "stack-gap-lg": "28px",
      "prose-max": "65ch",
    },
    sigil: {
      "grid-cell": "48px",
      "cross-arm": "0px",
      "cross-stroke": "0px",
      "rail-gap": "0px",
      "card-radius": "12px",
      "gutter-pattern": "none",
      "margin-pattern": "none",
      "gutter-border": "none",
      "gutter-visible": false,
    },
    radius: {
      none: "0px",
      sm: "6px",
      md: "10px",
      lg: "14px",
      xl: "20px",
      "2xl": "28px",
      full: "9999px",
      button: "10px",
      card: "14px",
      input: "10px",
      badge: "9999px",
      modal: "20px",
      popover: "14px",
      tooltip: "8px",
      image: "12px",
      bento: "14px",
    },
    shadows: {
      sm: "0 1px 3px 0 rgb(0 0 0 / 0.06)",
      md: "0 2px 8px -1px rgb(0 0 0 / 0.08), 0 1px 3px 0 rgb(0 0 0 / 0.05)",
      lg: "0 4px 16px -3px rgb(0 0 0 / 0.12), 0 2px 4px 0 rgb(0 0 0 / 0.04)",
      xl: "0 10px 28px -6px rgb(0 0 0 / 0.16), 0 4px 8px -2px rgb(0 0 0 / 0.06)",
      "2xl": "0 20px 48px -10px rgb(0 0 0 / 0.2)",
      glow: "0 0 32px oklch(0.70 0.20 290 / 0.25)",
      "glow-sm": "0 0 16px oklch(0.70 0.20 290 / 0.15)",
      colored: "0 4px 20px -4px oklch(0.70 0.20 290 / 0.3)",
      inner: "inset 0 2px 4px 0 rgb(0 0 0 / 0.08)",
      card: "0 2px 8px -2px rgb(0 0 0 / 0.08), 0 0 0 1px rgb(255 255 255 / 0.04)",
      button: "0 1px 3px 0 rgb(0 0 0 / 0.06)",
      "button-hover": "0 2px 8px -2px rgb(0 0 0 / 0.12), 0 0 16px oklch(0.70 0.20 290 / 0.08)",
      dropdown: "0 8px 24px -4px rgb(0 0 0 / 0.15)",
      modal: "0 24px 48px -12px rgb(0 0 0 / 0.25), 0 0 32px oklch(0.70 0.20 290 / 0.06)",
    },
    motion: {
      duration: { instant: "0ms", fast: "130ms", normal: "230ms", slow: "380ms", slower: "550ms", slowest: "800ms" },
      easing: {
        default: "cubic-bezier(0.16, 1, 0.3, 1)",
        in: "cubic-bezier(0.55, 0, 1, 0.45)",
        out: "cubic-bezier(0, 0.55, 0.45, 1)",
        "in-out": "cubic-bezier(0.45, 0, 0.55, 1)",
        spring: "cubic-bezier(0.34, 1.56, 0.64, 1)",
      },
      "hover-scale": "1.02",
      "press-scale": "0.97",
      "hover-lift": "-2px",
      "stagger-interval": "50ms",
      "stagger-interval-fast": "30ms",
    },
    borders: {
      width: { none: "0px", thin: "1px", medium: "1.5px", thick: "2px" },
      style: "solid",
      "card-border": "1px solid",
      "card-border-hover": "1px solid",
      "button-border": "1px solid",
      "input-border": "1px solid",
      "divider-style": "solid",
      "divider-width": "1px",
    },
    buttons: {
      "font-weight": "500",
      "text-transform": "none",
      "letter-spacing": "0em",
      "font-family": "inherit",
      "border-width": "1px",
      "hover-effect": "glow",
      "active-scale": "0.97",
      "icon-gap": "8px",
      "min-width": "0px",
    },
    cards: {
      "border-style": "solid",
      "border-width": "1px",
      "hover-effect": "glow",
      "hover-border-color": "var(--s-primary)",
      padding: "28px",
      "header-padding": "28px 28px 0",
      "footer-padding": "0 28px 28px",
      "title-size": "1.0625rem",
      "title-weight": "600",
      "description-size": "0.875rem",
      background: "surface",
      shadow: "md",
      outline: true,
      "outline-on-hover-only": false,
      "gap-between": "16px",
      "content-padding-x": "28px",
      "content-padding-y": "20px",
    },
    headings: {
      "h1-size": "2.25rem",
      "h1-weight": "700",
      "h1-tracking": "-0.03em",
      "h1-leading": "1.12",
      "h2-size": "1.75rem",
      "h2-weight": "600",
      "h2-tracking": "-0.02em",
      "h3-size": "1.375rem",
      "h3-weight": "600",
      "h4-size": "1.125rem",
      "h4-weight": "600",
      "display-size": "3.75rem",
      "display-weight": "800",
      "display-tracking": "-0.04em",
      "display-leading": "1.06",
    },
    navigation: {
      "navbar-height": "60px",
      "navbar-backdrop-blur": "20px",
      "navbar-border": "none",
      "navbar-bg-opacity": "0.75",
      "nav-link-weight": "500",
      "nav-link-size": "0.8125rem",
      "nav-link-hover": "color",
      "breadcrumb-separator": "·",
      "pagination-radius": "10px",
      "sidebar-width": "260px",
      "sidebar-item-radius": "10px",
      "sidebar-item-padding": "10px 14px",
    },
    backgrounds: {
      pattern: "none",
      "pattern-opacity": "0",
      "pattern-scale": "1",
      noise: true,
      "noise-opacity": "0.02",
      "gradient-angle": "135deg",
      "gradient-type": "radial",
      "hero-pattern": "radial-glow",
      "section-divider": "none",
    },
    code: {
      "font-family": "'JetBrains Mono', ui-monospace, monospace",
      "font-size": "0.8125rem",
      "line-height": "1.65",
      bg: "var(--s-surface-sunken)",
      border: "1px solid var(--s-border-muted)",
      "border-radius": "10px",
      padding: "18px",
      "tab-size": "2",
      "selection-bg": "oklch(0.70 0.20 290 / 0.2)",
      "comment-color": "var(--s-text-muted)",
      "keyword-color": "oklch(0.70 0.20 290)",
      "string-color": "oklch(0.65 0.17 160)",
      "number-color": "oklch(0.72 0.14 85)",
      "function-color": "oklch(0.60 0.15 220)",
    },
    inputs: {
      height: "40px",
      "height-sm": "34px",
      "height-lg": "48px",
      "border-width": "1px",
      "focus-ring-width": "2px",
      "focus-ring-color": "var(--s-primary)",
      "focus-ring-offset": "2px",
      "placeholder-color": "var(--s-text-subtle)",
      "error-border-color": "var(--s-error)",
      "label-size": "0.8125rem",
      "label-weight": "500",
      "label-spacing": "8px",
      "helper-size": "0.75rem",
    },
    alignment: {
      "rail-width": "1200px",
      "rail-columns": "12",
      "rail-gutter": "24px",
      "rail-margin": "28px",
      "rail-visible": false,
      "rail-color": "var(--s-border-muted)",
      "content-align": "center",
      "hero-align": "center",
      "section-align": "center",
      "navbar-align": "full",
      "footer-align": "full",
    },
    sections: {
      "padding-y": "96px",
      "padding-y-hero": "128px",
      "padding-x": "28px",
      "max-width": "1200px",
      gap: "32px",
      "title-align": "center",
      "divider-above": false,
      "divider-below": false,
      "background-alt": false,
      indent: "0px",
    },
    dividers: {
      style: "none",
      width: "0px",
      color: "var(--s-border-muted)",
      spacing: "0px",
      "show-cross": false,
      "show-label": false,
      "full-bleed": false,
      ornament: "none",
    },
    gridVisuals: {
      "show-lines": false,
      "line-color": "var(--s-border-muted)",
      "line-width": "1px",
      "show-dots": false,
      "dot-size": "2px",
      "cell-background": "none",
      "cell-border": false,
      "cell-radius": "14px",
      "cell-padding": "20px",
      "hover-effect": "glow",
    },
    cursor: {
      variant: "dot",
      size: "24px",
      "dot-size": "4px",
      "stroke-width": "1.5px",
      "tick-size": "6px",
      gap: "3px",
      radius: "0px",
      color: "var(--s-text)",
      "ring-color": "var(--s-primary)",
      "dot-color": "var(--s-primary)",
      glow: "none",
      opacity: "1",
      "blend-mode": "normal",
      "z-index": "9999",
      "hide-native": false,
    },
    scrollbar: {
      width: "8px",
      height: "8px",
      padding: "2px",
      radius: "9999px",
      track: "transparent",
      thumb: "var(--s-border-muted)",
      "thumb-hover": "var(--s-border)",
      "thumb-active": "var(--s-border-strong)",
      corner: "transparent",
      border: "none",
      "firefox-width": "thin",
      gutter: "stable",
      visibility: "auto",
    },
    focus: {
      "ring-width": "2px",
      "ring-color": "var(--s-primary)",
      "ring-offset": "2px",
      "ring-shadow": "0 0 0 2px var(--s-primary)",
      "outline-color": "var(--s-primary)",
    },
    overlays: {
      bg: "rgb(0 0 0 / 0.5)",
      blur: "8px",
      surface: "var(--s-surface-elevated)",
      border: "1px solid var(--s-border-muted)",
      shadow: "var(--s-shadow-xl)",
      radius: "var(--s-radius-lg)",
      padding: "20px",
      "z-index": "50",
    },
    dataViz: {
      "series-1": "var(--s-primary)",
      "series-2": "var(--s-secondary)",
      "series-3": "var(--s-accent)",
      "series-4": "var(--s-info)",
      "series-5": "var(--s-success)",
      positive: "var(--s-success)",
      negative: "var(--s-error)",
      neutral: "var(--s-text-muted)",
      grid: "var(--s-border-muted)",
      axis: "var(--s-border)",
      label: "var(--s-text-secondary)",
      "tooltip-bg": "var(--s-surface-elevated)",
      "tooltip-border": "var(--s-border-muted)",
    },
    media: {
      radius: "var(--s-radius-md)",
      border: "none",
      outline: "1px solid rgb(0 0 0 / 0.08)",
      shadow: "none",
      bg: "var(--s-surface-sunken)",
      "object-fit": "cover",
    },
    controls: {
      height: "38px",
      "height-sm": "30px",
      "height-lg": "46px",
      "hit-area": "44px",
      "icon-size": "16px",
      "handle-size": "20px",
      "track-height": "4px",
      "track-bg": "var(--s-border-muted)",
      "track-fill": "var(--s-primary)",
      "thumb-bg": "var(--s-surface-elevated)",
      "thumb-border": "2px solid var(--s-primary)",
    },
    componentSurfaces: {
      bg: "var(--s-surface)",
      "bg-elevated": "var(--s-surface-elevated)",
      "bg-muted": "var(--s-surface-sunken)",
      border: "var(--s-border)",
      "border-muted": "var(--s-border-muted)",
      "border-strong": "var(--s-border-strong)",
      text: "var(--s-text)",
      "text-muted": "var(--s-text-muted)",
      contrast: "var(--s-primary-contrast)",
      "hover-bg": "var(--s-surface-elevated)",
      "active-bg": "var(--s-surface-sunken)",
      "selected-bg": "var(--s-primary-muted)",
    },

  },
};
