import type { SigilPreset } from "@sigil-ui/tokens";

export const axiomPreset: SigilPreset = {
  name: "axiom",
  metadata: {
    description: "Mathematical truth — clean systematic layout, proof-like structure, absolute precision.",
    mood: "mathematical, systematic, proof-like",
    tags: ["math", "systematic", "clean", "academic", "minimal"],
    author: "sigil-ui",
    version: "0.1.0",
  },
  tokens: {
    colors: {
      background: { light: "oklch(1 0 0)", dark: "oklch(0.08 0 0)" },
      surface: { light: "oklch(0.98 0 0)", dark: "oklch(0.12 0 0)" },
      "surface-elevated": { light: "oklch(1 0 0)", dark: "oklch(0.16 0 0)" },
      "surface-sunken": { light: "oklch(0.97 0.002 260)", dark: "oklch(0.06 0.002 260)" },
      primary: "oklch(0.55 0.2 260)",
      "primary-hover": "oklch(0.48 0.22 260)",
      "primary-muted": "oklch(0.9 0.04 260)",
      "primary-contrast": "oklch(1 0 0)",
      secondary: "oklch(0.45 0.06 0)",
      "secondary-hover": "oklch(0.38 0.07 0)",
      "secondary-muted": "oklch(0.8 0.02 0)",
      accent: "oklch(0.55 0.15 300)",
      "accent-hover": "oklch(0.48 0.17 300)",
      "accent-muted": "oklch(0.85 0.05 300)",
      text: { light: "oklch(0.0 0 0)", dark: "oklch(0.95 0 0)" },
      "text-secondary": { light: "oklch(0.3 0 0)", dark: "oklch(0.75 0 0)" },
      "text-muted": { light: "oklch(0.5 0 0)", dark: "oklch(0.63 0 0)" },
      "text-subtle": { light: "oklch(0.65 0 0)", dark: "oklch(0.50 0 0)" },
      "text-disabled": { light: "oklch(0.78 0 0)", dark: "oklch(0.3 0 0)" },
      "text-inverse": { light: "oklch(0.98 0 0)", dark: "oklch(0.1 0 0)" },
      border: { light: "oklch(0.66 0 0)", dark: "oklch(0.260 0.006 0)" },
      "border-muted": { light: "oklch(0.83 0.006 0)", dark: "oklch(0.200 0.006 0)" },
      "border-strong": { light: "oklch(0.50 0.005 260)", dark: "oklch(0.340 0.005 260)" },
      "border-interactive": { light: "oklch(0.55 0.2 260)", dark: "oklch(0.6 0.2 260)" },
      success: "oklch(0.64 0.17 155)",
      "success-muted": "oklch(0.65 0.05 155)",
      warning: "oklch(0.67 0.14 80)",
      "warning-muted": "oklch(0.75 0.05 80)",
      error: "oklch(0.58 0.2 25)",
      "error-muted": "oklch(0.58 0.06 25)",
      info: "oklch(0.58 0.16 235)",
      "info-muted": "oklch(0.55 0.06 260)",
      "gradient-start": "oklch(0.55 0.2 260)",
      "gradient-end": "oklch(0.55 0.15 300)",
      glow: "oklch(0.55 0.2 260 / 0.25)",
      highlight: { light: "oklch(0.92 0.08 260)", dark: "oklch(0.28 0.06 260)" },
    },
    typography: {
      "font-display": "'PP Eiko', Georgia, serif",
      "font-body": "'PP Neue Montreal', system-ui, sans-serif",
      "font-mono": "'PP Fraktion Mono', ui-monospace, monospace",
      "size-xs": "0.75rem",
      "size-sm": "0.8125rem",
      "size-base": "1rem",
      "size-lg": "1.125rem",
      "size-xl": "1.25rem",
      "size-2xl": "1.5rem",
      "size-3xl": "1.875rem",
      "size-4xl": "2.25rem",
      "size-5xl": "3rem",
      "size-6xl": "3.75rem",
      "weight-normal": "400",
      "weight-medium": "500",
      "weight-semibold": "600",
      "weight-bold": "700",
      "weight-extrabold": "800",
      "leading-tight": "1.3",
      "leading-normal": "1.618",
      "leading-relaxed": "1.75",
      "leading-loose": "2",
      "tracking-tighter": "-0.03em",
      "tracking-tight": "-0.015em",
      "tracking-normal": "0em",
      "tracking-wide": "0.01em",
      "tracking-wider": "0.025em",
      "heading-weight": "400",
      "heading-tracking": "0em",
      "heading-transform": "none",
      "heading-family": "'PP Eiko', Georgia, serif",
    },
    spacing: {
      scale: [4, 8, 12, 16, 24, 32, 48, 64, 96, 128],
      unit: "px",
      "button-px": "20px",
      "button-py": "8px",
      "button-px-sm": "14px",
      "button-py-sm": "5px",
      "button-px-lg": "28px",
      "button-py-lg": "12px",
      "card-padding": "28px",
      "card-padding-sm": "18px",
      "card-padding-lg": "40px",
      "input-px": "12px",
      "input-py": "8px",
      "badge-px": "8px",
      "badge-py": "2px",
      "section-py": "80px",
      "section-py-lg": "128px",
      "navbar-height": "56px",
      "navbar-px": "28px",
      "footer-py": "56px",
      "modal-padding": "24px",
      "popover-padding": "14px",
      "tooltip-padding": "5px 10px",
      "table-cell-px": "16px",
      "table-cell-py": "10px",
    },
    layout: {
      "content-max": "1200px",
      "content-max-narrow": "720px",
      "content-max-wide": "1440px",
      "page-margin": "36px",
      "page-margin-sm": "20px",
      "page-margin-lg": "72px",
      gutter: "0px",
      "gutter-sm": "0px",
      "gutter-lg": "0px",
      "grid-columns": "12",
      "grid-gap": "32px",
      "bento-gap": "20px",
      "bento-radius": "4px",
      "bento-min-height": "180px",
      "section-gap": "24px",
      "sidebar-width": "224px",
      "sidebar-collapsed": "52px",
      "footer-columns": "3",
      "stack-gap": "16px",
      "stack-gap-sm": "8px",
      "stack-gap-lg": "24px",
      "prose-max": "65ch",
    },
    sigil: {
      "grid-cell": "52px",
      "cross-arm": "0px",
      "cross-stroke": "0px",
      "rail-gap": "0px",
      "card-radius": "4px",
      "gutter-pattern": "none",
      "margin-pattern": "none",
      "gutter-border": "none",
      "gutter-visible": false,
    },
    radius: {
      none: "0px",
      sm: "2px",
      md: "3px",
      lg: "4px",
      xl: "6px",
      "2xl": "8px",
      full: "9999px",
      button: "3px",
      card: "4px",
      input: "3px",
      badge: "9999px",
      modal: "6px",
      popover: "4px",
      tooltip: "3px",
      image: "2px",
      bento: "4px",
    },
    shadows: {
      sm: "none",
      md: "none",
      lg: "none",
      xl: "0 4px 12px -4px rgb(0 0 0 / 0.06)",
      "2xl": "0 12px 32px -8px rgb(0 0 0 / 0.1)",
      glow: "0 0 16px var(--s-primary)",
      "glow-sm": "0 0 8px var(--s-primary)",
      colored: "0 2px 10px -3px var(--s-primary)",
      inner: "inset 0 1px 2px 0 rgb(0 0 0 / 0.04)",
      card: "none",
      button: "none",
      "button-hover": "none",
      dropdown: "0 4px 12px rgb(0 0 0 / 0.08), 0 0 0 1px rgb(0 0 0 / 0.04)",
      modal: "0 12px 40px -8px rgb(0 0 0 / 0.15)",
    },
    motion: {
      duration: { instant: "0ms", fast: "100ms", normal: "200ms", slow: "300ms", slower: "500ms", slowest: "800ms" },
      easing: {
        default: "cubic-bezier(0.25, 0.1, 0.25, 1)",
        in: "cubic-bezier(0.42, 0, 1, 1)",
        out: "cubic-bezier(0, 0, 0.58, 1)",
        "in-out": "cubic-bezier(0.42, 0, 0.58, 1)",
        spring: "cubic-bezier(0.34, 1.56, 0.64, 1)",
        bounce: "cubic-bezier(0.68, -0.55, 0.27, 1.55)",
      },
      "enter-preset": "fadeUp",
      "exit-preset": "fadeOut",
      "hover-scale": "1.0",
      "press-scale": "0.98",
      "hover-lift": "0px",
      "stagger-interval": "40ms",
      "stagger-interval-fast": "20ms",
    },
    borders: {
      width: { none: "0px", thin: "1px", medium: "1.5px", thick: "2px" },
      style: "solid",
      "card-border": "none",
      "card-border-hover": "none",
      "button-border": "1px solid",
      "input-border": "1px solid",
      "divider-style": "solid",
      "divider-width": "1px",
    },
    buttons: {
      "font-weight": "500",
      "text-transform": "none",
      "letter-spacing": "0em",
      "font-family": "'PP Neue Montreal', system-ui, sans-serif",
      "border-width": "1px",
      "hover-effect": "darken",
      "active-scale": "0.98",
      "icon-gap": "8px",
      "min-width": "0px",
    },
    cards: {
      "border-style": "none",
      "border-width": "0px",
      "hover-effect": "lift",
      "hover-border-color": "transparent",
      padding: "24px",
      "header-padding": "24px 24px 0",
      "footer-padding": "0 24px 24px",
      "title-size": "1.125rem",
      "title-weight": "600",
      "description-size": "0.875rem",
      background: "transparent",
      shadow: "none",
      outline: false,
      "outline-on-hover-only": false,
      "gap-between": "16px",
      "content-padding-x": "24px",
      "content-padding-y": "20px",
    },
    headings: {
      "h1-size": "2.25rem",
      "h1-weight": "700",
      "h1-tracking": "-0.02em",
      "h1-leading": "1.25",
      "h2-size": "1.875rem",
      "h2-weight": "700",
      "h2-tracking": "-0.015em",
      "h3-size": "1.5rem",
      "h3-weight": "600",
      "h4-size": "1.25rem",
      "h4-weight": "600",
      "display-size": "3.5rem",
      "display-weight": "700",
      "display-tracking": "-0.03em",
      "display-leading": "1.15",
    },
    navigation: {
      "navbar-height": "56px",
      "navbar-backdrop-blur": "8px",
      "navbar-border": "none",
      "navbar-bg-opacity": "0.95",
      "navbar-padding-x": "28px",
      "navbar-position": "sticky",
      "navbar-logo-height": "24px",
      "navbar-logo-gap": "10px",
      "navbar-item-gap": "28px",
      "navbar-item-padding-x": "12px",
      "navbar-item-padding-y": "6px",
      "navbar-item-size": "0.875rem",
      "navbar-shadow": "none",
      "navbar-height-scrolled": "48px",
      "navbar-mobile-breakpoint": "768px",
      "nav-link-weight": "400",
      "nav-link-size": "0.8125rem",
      "nav-link-hover": "color",
      "breadcrumb-separator": "/",
      "pagination-radius": "3px",
      "sidebar-width": "224px",
      "sidebar-item-radius": "3px",
      "sidebar-item-padding": "8px 14px",
    },
    backgrounds: {
      pattern: "none",
      "pattern-opacity": "0",
      "pattern-scale": "1",
      noise: true,
      "noise-opacity": "0.01",
      "gradient-angle": "180deg",
      "gradient-type": "radial",
      "hero-pattern": "radial-glow",
      "section-divider": "line",
    },
    code: {
      "font-family": "'PP Fraktion Mono', ui-monospace, monospace",
      "font-size": "0.8125rem",
      "line-height": "1.7",
      bg: "var(--s-surface-sunken)",
      border: "1px solid var(--s-border-muted)",
      "border-radius": "3px",
      padding: "16px",
      "tab-size": "2",
      "selection-bg": "var(--s-primary-muted)",
      "comment-color": "var(--s-text-muted)",
      "keyword-color": "var(--s-primary)",
      "string-color": "var(--s-success)",
      "number-color": "var(--s-warning)",
      "function-color": "var(--s-accent)",
    },
    inputs: {
      height: "38px",
      "height-sm": "30px",
      "height-lg": "46px",
      "border-width": "1px",
      "focus-ring-width": "2px",
      "focus-ring-color": "var(--s-primary)",
      "focus-ring-offset": "2px",
      "placeholder-color": "var(--s-text-subtle)",
      "error-border-color": "var(--s-error)",
      "label-size": "0.8125rem",
      "label-weight": "500",
      "label-spacing": "8px",
      "helper-size": "0.75rem",
    },
    alignment: {
      "title-align": "left",
    },
    sections: {
      "rail-margin": "32px",
      "padding-y": "64px",
      "padding-y-sm": "48px",
      gap: "32px",
      "padding-y-lg": "96px",
      "padding-y-xl": "144px",
      "title-align": "left",
      "heading-size": "clamp(1.5rem, 4vw, 2.25rem)",
      "heading-align": "center",
      "heading-max-width": "40rem",
      "heading-margin-bottom": "16px",
      "description-max-width": "32rem",
      "description-gap": "12px",
      "content-gap": "28px",
      "grid-columns": "3",
      "grid-gap": "28px",
      "alternate-bg": "var(--s-surface)",
      "alternate-bg-mode": "none",
      "max-width": "960px",
    },
    dividers: {
      style: "solid",
      width: "0.5px",
      spacing: "0px",
      opacity: "0.6",
      "max-width": "100%",
      "margin-y": "0px",
      thickness: "1px",
      "gradient-start": "transparent",
      "gradient-end": "transparent",
    },
    gridVisuals: {
      "line-color": "var(--s-border-muted)",
      "show-lines": true,
      "show-dots": true,
      "line-width": "0.5px",
      "rail-visible": true,
      "rail-columns": "16",
    },
    cursor: {
      variant: "dot",
      size: "24px",
      "dot-size": "4px",
      "stroke-width": "1.5px",
      "tick-size": "6px",
      gap: "3px",
      radius: "0px",
      color: "var(--s-text)",
      "ring-color": "var(--s-primary)",
      "dot-color": "var(--s-primary)",
      glow: "none",
      opacity: "1",
      "blend-mode": "normal",
      "z-index": "9999",
      "hide-native": false,
    },
    scrollbar: {
      width: "6px",
      height: "6px",
      padding: "2px",
      radius: "9999px",
      track: "transparent",
      thumb: "var(--s-border-muted)",
      "thumb-hover": "var(--s-border)",
      "thumb-active": "var(--s-border-strong)",
      corner: "transparent",
      border: "none",
      "firefox-width": "thin",
      gutter: "stable",
      visibility: "auto",
    },
    focus: {
      "ring-width": "2px",
      "ring-color": "var(--s-primary)",
      "ring-offset": "2px",
      "ring-shadow": "0 0 0 2px var(--s-primary)",
      "outline-color": "var(--s-primary)",
    },
    overlays: {
      bg: "rgb(0 0 0 / 0.4)",
      blur: "4px",
      surface: "var(--s-surface-elevated)",
      border: "1px solid var(--s-border-muted)",
      shadow: "var(--s-shadow-xl)",
      radius: "var(--s-radius-lg)",
      padding: "20px",
      "z-index": "50",
    },
    dataViz: {
      "series-1": "var(--s-primary)",
      "series-2": "var(--s-secondary)",
      "series-3": "var(--s-accent)",
      "series-4": "var(--s-info)",
      "series-5": "var(--s-success)",
      positive: "var(--s-success)",
      negative: "var(--s-error)",
      neutral: "var(--s-text-muted)",
      grid: "var(--s-border-muted)",
      axis: "var(--s-border)",
      label: "var(--s-text-secondary)",
      "tooltip-bg": "var(--s-surface-elevated)",
      "tooltip-border": "var(--s-border-muted)",
    },
    media: {
      radius: "var(--s-radius-md)",
      border: "none",
      outline: "1px solid rgb(0 0 0 / 0.08)",
      shadow: "none",
      bg: "var(--s-surface-sunken)",
      "object-fit": "cover",
    },
    controls: {
      height: "38px",
      "height-sm": "30px",
      "height-lg": "46px",
      "hit-area": "44px",
      "icon-size": "16px",
      "handle-size": "20px",
      "track-height": "4px",
      "track-bg": "var(--s-border-muted)",
      "track-fill": "var(--s-primary)",
      "thumb-bg": "var(--s-surface-elevated)",
      "thumb-border": "2px solid var(--s-primary)",
    },
    componentSurfaces: {
      bg: "var(--s-surface)",
      "bg-elevated": "var(--s-surface-elevated)",
      "bg-muted": "var(--s-surface-sunken)",
      border: "var(--s-border)",
      "border-muted": "var(--s-border-muted)",
      "border-strong": "var(--s-border-strong)",
      text: "var(--s-text)",
      "text-muted": "var(--s-text-muted)",
      contrast: "var(--s-primary-contrast)",
      "hover-bg": "var(--s-surface-elevated)",
      "active-bg": "var(--s-surface-sunken)",
      "selected-bg": "var(--s-primary-muted)",
    },
    hero: {
      "min-height": "auto",
      "padding-y": "120px",
      "padding-y-sm": "72px",
      "padding-x": "var(--s-page-margin, 28px)",
      "content-max": "640px",
      "content-align": "center",
      layout: "centered",
      "media-position": "below",
      "media-width": "50%",
      "media-radius": "var(--s-radius-lg)",
      "title-size": "clamp(2.5rem, 6vw, 4.5rem)",
      "title-max-width": "56rem",
      "description-size": "1.125rem",
      "description-max-width": "32rem",
      "description-gap": "28px",
      "actions-gap": "12px",
      "actions-margin-top": "40px",
      "action-padding-x": "28px",
      "action-padding-y": "12px",
      "badge-gap": "28px",
      "overlay-opacity": "0.3",
      "scroll-indicator": false,
      "gradient-overlay": "none",
    },
    cta: {
      "padding-y": "96px",
      "padding-x": "var(--s-page-margin, 28px)",
      "max-width": "var(--s-content-max, 1200px)",
      layout: "centered",
      border: false,
      "border-radius": "var(--s-radius-lg)",
      bg: "var(--s-surface)",
      "title-size": "clamp(1.5rem, 4vw, 2.5rem)",
      "description-max-width": "32rem",
      "description-gap": "14px",
      "actions-gap": "12px",
      "actions-margin-top": "36px",
      "action-padding-x": "28px",
      "action-padding-y": "14px",
      "split-gap": "56px",
    },
    footer: {
      "padding-y": "56px",
      "border-top": "1px solid var(--s-border-muted)",
      columns: "4",
      "column-gap": "36px",
      "row-gap": "32px",
      "logo-height": "24px",
      "tagline-max-width": "22rem",
      "link-size": "0.875rem",
      "link-gap": "10px",
      "group-title-size": "0.8125rem",
      "group-title-weight": "500",
      "social-icon-size": "18px",
      "social-gap": "14px",
      "bottom-bar-padding": "24px 0",
      "bottom-bar-border": "1px solid var(--s-border-muted)",
    },
    banner: {
      height: "auto",
      "padding-y": "10px",
      "padding-x": "20px",
      "font-size": "0.8125rem",
      "font-weight": "400",
      "icon-size": "14px",
      "icon-gap": "10px",
      "border-width": "1px",
      "border-position": "bottom",
      position: "top",
      "dismiss-size": "14px",
      radius: "0px",
    },
    pageRhythm: {
      density: "spacious",
      "section-gap": "0px",
      "section-gap-sm": "0px",
      "section-gap-lg": "0px",
      "first-section-offset": "0px",
      "last-section-margin": "0px",
      "alternate-bg": false,
      "alternate-bg-color": "var(--s-surface)",
      "divider-between": false,
      "max-content-width": "var(--s-content-max, 1200px)",
      "vertical-rhythm-unit": "8px",
      "scroll-snap": false,
      "responsive-scale": "0.85",
      "responsive-breakpoint": "768px",
    },

  },
};
