import type { SigilPreset } from "@sigil-ui/tokens";

export const basaltPreset: SigilPreset = {
  name: "basalt",
  metadata: {
    description: "Dark volcanic. Hexagonal, columnar, geological. Deep navy-black with teal-green accents.",
    mood: "volcanic, dark, columnar",
    tags: ["dark", "volcanic", "teal", "geological", "hexagonal"],
  },
  tokens: {
    colors: {
      background: { light: "oklch(0.97 0.005 210)", dark: "oklch(0.09 0.02 260)" },
      surface: { light: "oklch(0.955 0.007 210)", dark: "oklch(0.13 0.018 260)" },
      "surface-elevated": { light: "oklch(0.985 0.003 210)", dark: "oklch(0.17 0.016 260)" },
      "surface-sunken": { light: "oklch(0.935 0.008 210)", dark: "oklch(0.06 0.02 260)" },
      primary: "oklch(0.61 0.15 175)",
      "primary-hover": "oklch(0.55 0.19 175)",
      "primary-muted": "oklch(0.72 0.06 175)",
      "primary-contrast": "oklch(0.1 0.02 260)",
      secondary: "oklch(0.55 0.04 260)",
      "secondary-hover": "oklch(0.48 0.05 260)",
      "secondary-muted": "oklch(0.55 0.02 260)",
      accent: "oklch(0.78 0.12 160)",
      "accent-hover": "oklch(0.72 0.14 160)",
      "accent-muted": "oklch(0.78 0.05 160)",
      text: { light: "oklch(0.14 0.015 260)", dark: "oklch(0.92 0.006 210)" },
      "text-secondary": { light: "oklch(0.35 0.012 260)", dark: "oklch(0.74 0.006 210)" },
      "text-muted": { light: "oklch(0.5 0.008 260)", dark: "oklch(0.63 0.005 210)" },
      "text-subtle": { light: "oklch(0.62 0.006 260)", dark: "oklch(0.51 0.005 210)" },
      "text-disabled": { light: "oklch(0.73 0.004 260)", dark: "oklch(0.34 0.004 210)" },
      "text-inverse": { light: "oklch(0.92 0.006 210)", dark: "oklch(0.14 0.015 260)" },
      border: { light: "oklch(0.64 0.008 220)", dark: "oklch(0.270 0.012 260)" },
      "border-muted": { light: "oklch(0.81 0.006 220)", dark: "oklch(0.210 0.010 260)" },
      "border-strong": { light: "oklch(0.64 0.012 220)", dark: "oklch(0.350 0.015 260)" },
      "border-interactive": { light: "oklch(0.72 0.15 175)", dark: "oklch(0.72 0.15 175)" },
      success: "oklch(0.62 0.17 155)",
      "success-muted": "oklch(0.74 0.06 155)",
      warning: "oklch(0.64 0.15 80)",
      "warning-muted": "oklch(0.8 0.05 80)",
      error: "oklch(0.62 0.2 20)",
      "error-muted": "oklch(0.62 0.07 20)",
      info: "oklch(0.63 0.14 240)",
      "info-muted": "oklch(0.68 0.05 240)",
      "gradient-start": "oklch(0.72 0.15 175)",
      "gradient-end": "oklch(0.55 0.04 260)",
      glow: "oklch(0.72 0.15 175 / 0.35)",
      highlight: { light: "oklch(0.92 0.06 175)", dark: "oklch(0.28 0.05 175)" },
    },
    typography: {
      "font-display": "'PP Monument Extended', system-ui, sans-serif",
      "font-body": "'PP Neue Montreal', system-ui, sans-serif",
      "font-mono": "'PP Supply Mono', ui-monospace, monospace",
      "size-xs": "0.75rem",
      "size-sm": "0.8125rem",
      "size-base": "0.9375rem",
      "size-lg": "1.0625rem",
      "size-xl": "1.25rem",
      "size-2xl": "1.5rem",
      "size-3xl": "1.875rem",
      "size-4xl": "2.375rem",
      "size-5xl": "3.25rem",
      "size-6xl": "4rem",
      "weight-normal": "400",
      "weight-medium": "500",
      "weight-semibold": "600",
      "weight-bold": "700",
      "weight-extrabold": "800",
      "leading-tight": "1.2",
      "leading-normal": "1.5",
      "leading-relaxed": "1.625",
      "leading-loose": "1.875",
      "tracking-tighter": "-0.04em",
      "tracking-tight": "-0.02em",
      "tracking-normal": "0em",
      "tracking-wide": "0.015em",
      "tracking-wider": "0.03em",
      "heading-weight": "900",
      "heading-tracking": "0.1em",
      "heading-transform": "uppercase",
      "heading-family": "'PP Monument Extended', system-ui, sans-serif",
    },
    spacing: {
      scale: [4, 6, 10, 14, 20, 28, 40, 56, 72, 88],
      unit: "px",
      "button-px": "22px",
      "button-py": "10px",
      "button-px-sm": "14px",
      "button-py-sm": "7px",
      "button-px-lg": "30px",
      "button-py-lg": "13px",
      "card-padding": "28px",
      "card-padding-sm": "16px",
      "card-padding-lg": "32px",
      "input-px": "12px",
      "input-py": "8px",
      "badge-px": "8px",
      "badge-py": "2px",
      "section-py": "7.5rem",
      "section-py-lg": "11.25rem",
      "navbar-height": "60px",
      "navbar-px": "28px",
      "footer-py": "60px",
      "modal-padding": "24px",
      "popover-padding": "14px",
      "tooltip-padding": "6px 10px",
      "table-cell-px": "14px",
      "table-cell-py": "10px",
    },
    layout: {
      "content-max": "1200px",
      "content-max-narrow": "720px",
      "content-max-wide": "1440px",
      "page-margin": "28px",
      "page-margin-sm": "16px",
      "page-margin-lg": "56px",
      gutter: "32px",
      "gutter-sm": "14px",
      "gutter-lg": "44px",
      "grid-columns": "12",
      "grid-gap": "28px",
      "bento-gap": "18px",
      "bento-radius": "16px",
      "bento-min-height": "210px",
      "section-gap": "30px",
      "sidebar-width": "300px",
      "sidebar-collapsed": "60px",
      "footer-columns": "4",
      "stack-gap": "14px",
      "stack-gap-sm": "8px",
      "stack-gap-lg": "24px",
      "prose-max": "64ch",
    },
    sigil: {
      "grid-cell": "60px",
      "cross-arm": "14px",
      "cross-stroke": "1.5px",
      "rail-gap": "32px",
      "card-radius": "16px",
      "gutter-pattern": "crosshatch",
      "margin-pattern": "zigzag",
      "margin-border": "1px solid var(--s-border-muted)",
    },
    radius: {
      none: "0px",
      sm: "6px",
      md: "12px",
      lg: "16px",
      xl: "20px",
      "2xl": "28px",
      full: "9999px",
      button: "12px",
      card: "16px",
      input: "10px",
      badge: "9999px",
      modal: "20px",
      popover: "14px",
      tooltip: "8px",
      image: "12px",
      bento: "16px",
    },
    shadows: {
      sm: "0 1px 3px 0 rgb(0 0 0 / 0.08)",
      md: "0 2px 6px -1px rgb(0 0 0 / 0.12), 0 0 0 1px rgb(0 0 0 / 0.04)",
      lg: "0 6px 14px -2px rgb(0 0 0 / 0.14), 0 2px 4px -1px rgb(0 0 0 / 0.06)",
      xl: "0 12px 24px -4px rgb(0 0 0 / 0.16), 0 4px 8px -2px rgb(0 0 0 / 0.06)",
      "2xl": "0 28px 56px -14px rgb(0 0 0 / 0.28)",
      glow: "0 0 28px var(--s-primary)",
      "glow-sm": "0 0 14px var(--s-primary)",
      colored: "0 6px 20px -4px var(--s-primary)",
      inner: "inset 0 2px 5px 0 rgb(0 0 0 / 0.08)",
      card: "0 0 0 1px var(--s-border-muted), 0 2px 6px -1px rgb(0 0 0 / 0.06)",
      button: "none",
      "button-hover": "0 0 16px var(--s-primary)",
      dropdown: "0 8px 24px -4px rgb(0 0 0 / 0.16), 0 0 0 1px rgb(0 0 0 / 0.04)",
      modal: "0 20px 60px -16px rgb(0 0 0 / 0.3)",
    },
    motion: {
      duration: { instant: "0ms", fast: "120ms", normal: "220ms", slow: "380ms", slower: "560ms", slowest: "900ms" },
      easing: {
        default: "cubic-bezier(0.16, 1, 0.3, 1)",
        in: "cubic-bezier(0.55, 0, 1, 0.45)",
        out: "cubic-bezier(0, 0.55, 0.45, 1)",
        "in-out": "cubic-bezier(0.45, 0, 0.55, 1)",
        spring: "cubic-bezier(0.34, 1.56, 0.64, 1)",
        bounce: "cubic-bezier(0.68, -0.55, 0.27, 1.55)",
      },
      "enter-preset": "fadeUp",
      "exit-preset": "fadeDown",
      "hover-scale": "1.02",
      "press-scale": "0.97",
      "hover-lift": "-3px",
      "stagger-interval": "45ms",
      "stagger-interval-fast": "20ms",
    },
    borders: {
      width: { none: "0px", thin: "1px", medium: "1.5px", thick: "2px" },
      style: "solid",
      "card-border": "1px solid",
      "card-border-hover": "1px solid",
      "button-border": "1px solid",
      "input-border": "1px solid",
      "divider-style": "solid",
      "divider-width": "1px",
    },
    buttons: {
      "font-weight": "600",
      "text-transform": "none",
      "letter-spacing": "0em",
      "font-family": "'PP Neue Montreal', system-ui, sans-serif",
      "border-width": "1px",
      "hover-effect": "glow",
      "active-scale": "0.97",
      "icon-gap": "8px",
      "min-width": "0px",
    },
    cards: {
      "border-style": "solid",
      "border-width": "1px",
      "hover-effect": "glow",
      "hover-border-color": "var(--s-primary)",
      padding: "24px",
      "header-padding": "24px 24px 0",
      "footer-padding": "0 24px 24px",
      "title-size": "1.0625rem",
      "title-weight": "700",
      "description-size": "0.8125rem",
      background: "surface",
      shadow: "sm",
      outline: true,
      "outline-on-hover-only": false,
      "gap-between": "16px",
      "content-padding-x": "24px",
      "content-padding-y": "20px",
    },
    headings: {
      "h1-size": "2.375rem",
      "h1-weight": "800",
      "h1-tracking": "-0.03em",
      "h1-leading": "1.15",
      "h2-size": "1.875rem",
      "h2-weight": "700",
      "h2-tracking": "-0.025em",
      "h2-leading": "1.15",
      "h3-size": "1.5rem",
      "h3-weight": "600",
      "h3-tracking": "0em",
      "h3-leading": "1.2",
      "h4-size": "1.25rem",
      "h4-weight": "600",
      "h4-tracking": "0em",
      "h4-leading": "1.3",
      "display-size": "4rem",
      "display-weight": "800",
      "display-tracking": "-0.045em",
      "display-leading": "1.05",
    },
    navigation: {
      "navbar-height": "60px",
      "navbar-backdrop-blur": "20px",
      "navbar-border": "1px solid",
      "navbar-bg-opacity": "0.78",
      "navbar-padding-x": "24px",
      "navbar-position": "sticky",
      "navbar-logo-height": "24px",
      "navbar-logo-gap": "10px",
      "navbar-item-gap": "24px",
      "navbar-item-padding-x": "12px",
      "navbar-item-padding-y": "6px",
      "navbar-item-size": "0.875rem",
      "navbar-shadow": "0 1px 3px rgb(0 0 0 / 0.3)",
      "navbar-height-scrolled": "48px",
      "navbar-mobile-breakpoint": "768px",
      "nav-link-weight": "500",
      "nav-link-size": "0.875rem",
      "nav-link-hover": "background",
      "breadcrumb-separator": "›",
      "pagination-radius": "10px",
      "sidebar-width": "300px",
      "sidebar-item-radius": "12px",
      "sidebar-item-padding": "10px 16px",
    },
    backgrounds: {
      pattern: "hexagon",
      "pattern-opacity": "0.04",
      "pattern-scale": "1.2",
      noise: true,
      "noise-opacity": "0.03",
      "gradient-angle": "160deg",
      "gradient-type": "radial",
      "hero-pattern": "radial-glow",
      "section-divider": "none",
    },
    code: {
      "font-family": "'PP Supply Mono', ui-monospace, monospace",
      "font-size": "0.8125rem",
      "line-height": "1.7",
      bg: "var(--s-surface-sunken)",
      border: "1px solid var(--s-border-muted)",
      "border-radius": "12px",
      padding: "16px",
      "tab-size": "2",
      "selection-bg": "var(--s-primary-muted)",
      "comment-color": "var(--s-text-muted)",
      "keyword-color": "var(--s-primary)",
      "string-color": "var(--s-accent)",
      "number-color": "var(--s-warning)",
      "function-color": "var(--s-info)",
    },
    inputs: {
      height: "40px",
      "height-sm": "32px",
      "height-lg": "48px",
      "border-width": "1px",
      "focus-ring-width": "2px",
      "focus-ring-color": "var(--s-primary)",
      "focus-ring-offset": "2px",
      "placeholder-color": "var(--s-text-subtle)",
      "error-border-color": "var(--s-error)",
      "label-size": "0.8125rem",
      "label-weight": "600",
      "label-spacing": "6px",
      "helper-size": "0.75rem",
    },
    alignment: {
      "rail-width": "1240px",
      "rail-columns": "12",
      "rail-gutter": "24px",
      "rail-margin": "32px",
      "rail-visible": false,
      "rail-color": "var(--s-border-muted)",
      "content-align": "center",
      "hero-align": "center",
      "section-align": "center",
      "navbar-align": "full",
      "footer-align": "content",
    },
    sections: {
      "padding-y": "7.5rem",
      "padding-y-hero": "11.25rem",
      "padding-y-sm": "3.75rem",
      "padding-x": "32px",
      "max-width": "1240px",
      gap: "36px",
      "padding-y-lg": "11.25rem",
      "padding-y-xl": "15rem",
      "title-align": "left",
      "heading-size": "clamp(1.5rem, 4vw, 2.5rem)",
      "heading-align": "center",
      "heading-max-width": "40rem",
      "heading-margin-bottom": "16px",
      "description-max-width": "32rem",
      "description-gap": "14px",
      "content-gap": "24px",
      "grid-columns": "3",
      "grid-gap": "24px",
      "alternate-bg": "var(--s-surface-sunken)",
      "alternate-bg-mode": "sunken",
      "divider-above": false,
      "divider-below": true,
      "background-alt": false,
      indent: "0px",
    },
    dividers: {
      style: "solid",
      width: "1px",
      color: "var(--s-border-muted)",
      spacing: "0px",
      opacity: "0.5",
      "max-width": "100%",
      "margin-y": "0px",
      thickness: "1px",
      "gradient-start": "transparent",
      "gradient-end": "transparent",
      "show-cross": false,
      "show-label": false,
      "full-bleed": false,
      ornament: "none",
    },
    gridVisuals: {
      "show-lines": false,
      "line-color": "var(--s-border-muted)",
      "line-width": "1px",
      "show-dots": true,
      "dot-size": "3px",
      "cell-background": "surface",
      "cell-border": true,
      "cell-radius": "0px",
      "cell-padding": "16px",
      "hover-effect": "none",
    },
    cursor: {
      variant: "ring",
      size: "24px",
      "dot-size": "4px",
      "stroke-width": "1.5px",
      "tick-size": "6px",
      gap: "3px",
      radius: "0px",
      color: "var(--s-text)",
      "ring-color": "var(--s-primary)",
      "dot-color": "var(--s-primary)",
      glow: "0 0 8px var(--s-primary)",
      opacity: "1",
      "blend-mode": "normal",
      "z-index": "9999",
      "hide-native": false,
    },
    scrollbar: {
      width: "8px",
      height: "8px",
      padding: "2px",
      radius: "9999px",
      track: "transparent",
      thumb: "var(--s-border-muted)",
      "thumb-hover": "var(--s-border)",
      "thumb-active": "var(--s-border-strong)",
      corner: "transparent",
      border: "none",
      "firefox-width": "thin",
      gutter: "stable",
      visibility: "auto",
    },
    focus: {
      "ring-width": "2px",
      "ring-color": "var(--s-primary)",
      "ring-offset": "0px",
      "ring-shadow": "0 0 0 2px var(--s-primary)",
      "outline-color": "var(--s-primary)",
    },
    overlays: {
      bg: "rgb(0 0 0 / 0.7)",
      blur: "12px",
      surface: "var(--s-surface-elevated)",
      border: "1px solid var(--s-border-muted)",
      shadow: "var(--s-shadow-xl)",
      radius: "var(--s-radius-lg)",
      padding: "20px",
      "z-index": "50",
    },
    dataViz: {
      "series-1": "var(--s-primary)",
      "series-2": "var(--s-secondary)",
      "series-3": "var(--s-accent)",
      "series-4": "var(--s-info)",
      "series-5": "var(--s-success)",
      positive: "var(--s-success)",
      negative: "var(--s-error)",
      neutral: "var(--s-text-muted)",
      grid: "var(--s-border-muted)",
      axis: "var(--s-border)",
      label: "var(--s-text-secondary)",
      "tooltip-bg": "var(--s-surface-elevated)",
      "tooltip-border": "var(--s-border-muted)",
    },
    media: {
      radius: "var(--s-radius-md)",
      border: "none",
      outline: "1px solid rgb(0 0 0 / 0.08)",
      shadow: "none",
      bg: "var(--s-surface-sunken)",
      "object-fit": "cover",
    },
    controls: {
      height: "38px",
      "height-sm": "30px",
      "height-lg": "46px",
      "hit-area": "44px",
      "icon-size": "16px",
      "handle-size": "20px",
      "track-height": "4px",
      "track-bg": "var(--s-border-muted)",
      "track-fill": "var(--s-primary)",
      "thumb-bg": "var(--s-surface-elevated)",
      "thumb-border": "2px solid var(--s-primary)",
    },
    componentSurfaces: {
      bg: "var(--s-surface)",
      "bg-elevated": "var(--s-surface-elevated)",
      "bg-muted": "var(--s-surface-sunken)",
      border: "var(--s-border)",
      "border-muted": "var(--s-border-muted)",
      "border-strong": "var(--s-border-strong)",
      text: "var(--s-text)",
      "text-muted": "var(--s-text-muted)",
      contrast: "var(--s-primary-contrast)",
      "hover-bg": "var(--s-surface-elevated)",
      "active-bg": "var(--s-surface-sunken)",
      "selected-bg": "var(--s-primary-muted)",
    },
    hero: {
      "min-height": "auto",
      "padding-y": "120px",
      "padding-y-sm": "60px",
      "padding-x": "var(--s-page-margin, 24px)",
      "content-max": "640px",
      "content-align": "center",
      layout: "centered",
      "media-position": "below",
      "media-width": "50%",
      "media-radius": "var(--s-radius-lg)",
      "title-size": "clamp(2.5rem, 6vw, 4.5rem)",
      "title-max-width": "56rem",
      "description-size": "1.125rem",
      "description-max-width": "32rem",
      "description-gap": "24px",
      "actions-gap": "12px",
      "actions-margin-top": "36px",
      "action-padding-x": "24px",
      "action-padding-y": "12px",
      "badge-gap": "24px",
      "overlay-opacity": "0.7",
      "scroll-indicator": false,
      "gradient-overlay": "linear-gradient(to bottom, transparent, var(--s-background))",
    },
    cta: {
      "padding-y": "90px",
      "padding-x": "var(--s-page-margin, 24px)",
      "max-width": "var(--s-content-max, 1200px)",
      layout: "centered",
      border: false,
      "border-radius": "var(--s-radius-lg)",
      bg: "var(--s-surface-elevated)",
      "title-size": "clamp(1.5rem, 4vw, 2.5rem)",
      "description-max-width": "32rem",
      "description-gap": "14px",
      "actions-gap": "12px",
      "actions-margin-top": "36px",
      "action-padding-x": "24px",
      "action-padding-y": "12px",
      "split-gap": "60px",
    },
    footer: {
      "padding-y": "60px",
      "border-top": "1px solid var(--s-border)",
      columns: "4",
      "column-gap": "32px",
      "row-gap": "32px",
      "logo-height": "24px",
      "tagline-max-width": "20rem",
      "link-size": "0.875rem",
      "link-gap": "8px",
      "group-title-size": "0.8125rem",
      "group-title-weight": "600",
      "social-icon-size": "20px",
      "social-gap": "12px",
      "bottom-bar-padding": "30px 0",
      "bottom-bar-border": "1px solid var(--s-border-muted)",
    },
    banner: {
      height: "auto",
      "padding-y": "8px",
      "padding-x": "16px",
      "font-size": "0.875rem",
      "font-weight": "500",
      "icon-size": "16px",
      "icon-gap": "12px",
      "border-width": "1px",
      "border-position": "bottom",
      position: "top",
      "dismiss-size": "16px",
      radius: "0px",
    },
    pageRhythm: {
      density: "spacious",
      "section-gap": "0px",
      "section-gap-sm": "0px",
      "section-gap-lg": "0px",
      "first-section-offset": "0px",
      "last-section-margin": "0px",
      "alternate-bg": true,
      "alternate-bg-color": "var(--s-surface-sunken)",
      "divider-between": false,
      "max-content-width": "var(--s-content-max, 1200px)",
      "vertical-rhythm-unit": "10px",
      "scroll-snap": false,
      "responsive-scale": "0.9",
      "responsive-breakpoint": "768px",
    },

  },
};
