import type { SigilPreset } from "@sigil-ui/tokens";

export const basaltPreset: SigilPreset = {
  name: "basalt",
  metadata: {
    description: "Dark volcanic. Hexagonal, columnar, geological. Deep navy-black with teal-green accents.",
    mood: "volcanic, dark, columnar",
    tags: ["dark", "volcanic", "teal", "geological", "hexagonal"],
  },
  tokens: {
    colors: {
      background: { light: "oklch(0.97 0.005 210)", dark: "oklch(0.09 0.02 260)" },
      surface: { light: "oklch(0.955 0.007 210)", dark: "oklch(0.13 0.018 260)" },
      "surface-elevated": { light: "oklch(0.985 0.003 210)", dark: "oklch(0.17 0.016 260)" },
      "surface-sunken": { light: "oklch(0.935 0.008 210)", dark: "oklch(0.06 0.02 260)" },
      primary: "oklch(0.61 0.15 175)",
      "primary-hover": "oklch(0.66 0.17 175)",
      "primary-muted": "oklch(0.72 0.06 175)",
      "primary-contrast": "oklch(0.1 0.02 260)",
      secondary: "oklch(0.55 0.04 260)",
      "secondary-hover": "oklch(0.48 0.05 260)",
      "secondary-muted": "oklch(0.55 0.02 260)",
      accent: "oklch(0.78 0.12 160)",
      "accent-hover": "oklch(0.72 0.14 160)",
      "accent-muted": "oklch(0.78 0.05 160)",
      text: { light: "oklch(0.14 0.015 260)", dark: "oklch(0.92 0.006 210)" },
      "text-secondary": { light: "oklch(0.35 0.012 260)", dark: "oklch(0.74 0.006 210)" },
      "text-muted": { light: "oklch(0.5 0.008 260)", dark: "oklch(0.63 0.005 210)" },
      "text-subtle": { light: "oklch(0.62 0.006 260)", dark: "oklch(0.51 0.005 210)" },
      "text-disabled": { light: "oklch(0.73 0.004 260)", dark: "oklch(0.34 0.004 210)" },
      "text-inverse": { light: "oklch(0.92 0.006 210)", dark: "oklch(0.14 0.015 260)" },
      border: { light: "oklch(0.64 0.008 220)", dark: "oklch(0.48 0.012 260)" },
      "border-muted": { light: "oklch(0.92 0.006 220)", dark: "oklch(0.24 0.01 260)" },
      "border-strong": { light: "oklch(0.64 0.012 220)", dark: "oklch(0.48 0.015 260)" },
      "border-interactive": { light: "oklch(0.72 0.15 175)", dark: "oklch(0.72 0.15 175)" },
      success: "oklch(0.62 0.17 155)",
      "success-muted": "oklch(0.74 0.06 155)",
      warning: "oklch(0.64 0.15 80)",
      "warning-muted": "oklch(0.8 0.05 80)",
      error: "oklch(0.62 0.2 20)",
      "error-muted": "oklch(0.62 0.07 20)",
      info: "oklch(0.63 0.14 240)",
      "info-muted": "oklch(0.68 0.05 240)",
      "gradient-start": "oklch(0.72 0.15 175)",
      "gradient-end": "oklch(0.55 0.04 260)",
      glow: "oklch(0.72 0.15 175 / 0.35)",
    },
    typography: {
      "font-display": "'PP Monument Extended', system-ui, sans-serif",
      "font-body": "'PP Neue Montreal', system-ui, sans-serif",
      "font-mono": "'PP Supply Mono', ui-monospace, monospace",
      "size-xs": "0.75rem",
      "size-sm": "0.8125rem",
      "size-base": "0.9375rem",
      "size-lg": "1.0625rem",
      "size-xl": "1.25rem",
      "size-2xl": "1.5rem",
      "size-3xl": "1.875rem",
      "size-4xl": "2.375rem",
      "size-5xl": "3.25rem",
      "size-6xl": "4rem",
      "weight-normal": "400",
      "weight-medium": "500",
      "weight-semibold": "600",
      "weight-bold": "700",
      "weight-extrabold": "800",
      "leading-tight": "1.2",
      "leading-normal": "1.5",
      "leading-relaxed": "1.625",
      "leading-loose": "1.875",
      "tracking-tighter": "-0.04em",
      "tracking-tight": "-0.02em",
      "tracking-normal": "0em",
      "tracking-wide": "0.015em",
      "tracking-wider": "0.03em",
      "heading-weight": "900",
      "heading-tracking": "0.1em",
      "heading-transform": "uppercase",
      "heading-family": "'PP Monument Extended', system-ui, sans-serif",
    },
    spacing: {
      scale: [4, 6, 10, 14, 20, 28, 40, 56, 72, 88],
      unit: "px",
      "button-px": "22px",
      "button-py": "10px",
      "button-px-sm": "14px",
      "button-py-sm": "7px",
      "button-px-lg": "30px",
      "button-py-lg": "13px",
      "card-padding": "28px",
      "card-padding-sm": "16px",
      "card-padding-lg": "32px",
      "input-px": "12px",
      "input-py": "8px",
      "badge-px": "8px",
      "badge-py": "2px",
      "section-py": "88px",
      "section-py-lg": "128px",
      "navbar-height": "68px",
      "navbar-px": "28px",
      "footer-py": "56px",
      "modal-padding": "24px",
      "popover-padding": "14px",
      "tooltip-padding": "6px 10px",
      "table-cell-px": "14px",
      "table-cell-py": "10px",
    },
    layout: {
      "content-max": "1200px",
      "content-max-narrow": "720px",
      "content-max-wide": "1440px",
      "page-margin": "28px",
      "page-margin-sm": "16px",
      "page-margin-lg": "56px",
      gutter: "32px",
      "gutter-sm": "14px",
      "gutter-lg": "44px",
      "grid-columns": "12",
      "grid-gap": "28px",
      "bento-gap": "18px",
      "bento-radius": "16px",
      "bento-min-height": "200px",
      "section-gap": "32px",
      "sidebar-width": "300px",
      "sidebar-collapsed": "60px",
      "footer-columns": "4",
      "stack-gap": "14px",
      "stack-gap-sm": "8px",
      "stack-gap-lg": "24px",
      "prose-max": "64ch",
    },
    sigil: {
      "grid-cell": "60px",
      "cross-arm": "14px",
      "cross-stroke": "1.5px",
      "rail-gap": "32px",
      "card-radius": "16px",
      "gutter-pattern": "crosshatch",
      "margin-pattern": "zigzag",
      "margin-border": "1px solid",
    },
    radius: {
      none: "0px",
      sm: "6px",
      md: "12px",
      lg: "16px",
      xl: "20px",
      "2xl": "28px",
      full: "9999px",
      button: "12px",
      card: "16px",
      input: "10px",
      badge: "9999px",
      modal: "20px",
      popover: "14px",
      tooltip: "8px",
      image: "12px",
      bento: "16px",
    },
    shadows: {
      sm: "0 1px 3px 0 rgb(0 0 0 / 0.08)",
      md: "0 2px 6px -1px rgb(0 0 0 / 0.12), 0 0 0 1px rgb(0 0 0 / 0.04)",
      lg: "0 6px 14px -2px rgb(0 0 0 / 0.14), 0 2px 4px -1px rgb(0 0 0 / 0.06)",
      xl: "0 12px 24px -4px rgb(0 0 0 / 0.16), 0 4px 8px -2px rgb(0 0 0 / 0.06)",
      "2xl": "0 28px 56px -14px rgb(0 0 0 / 0.28)",
      glow: "0 0 28px var(--s-primary)",
      "glow-sm": "0 0 14px var(--s-primary)",
      colored: "0 6px 20px -4px var(--s-primary)",
      inner: "inset 0 2px 5px 0 rgb(0 0 0 / 0.08)",
      card: "0 0 0 1px var(--s-border-muted), 0 2px 6px -1px rgb(0 0 0 / 0.06)",
      button: "none",
      "button-hover": "0 0 16px var(--s-primary)",
      dropdown: "0 8px 24px -4px rgb(0 0 0 / 0.16), 0 0 0 1px rgb(0 0 0 / 0.04)",
      modal: "0 20px 60px -16px rgb(0 0 0 / 0.3)",
    },
    motion: {
      duration: { instant: "0ms", fast: "120ms", normal: "220ms", slow: "380ms", slower: "560ms", slowest: "900ms" },
      easing: {
        default: "cubic-bezier(0.16, 1, 0.3, 1)",
        in: "cubic-bezier(0.55, 0, 1, 0.45)",
        out: "cubic-bezier(0, 0.55, 0.45, 1)",
        "in-out": "cubic-bezier(0.45, 0, 0.55, 1)",
        spring: "cubic-bezier(0.34, 1.56, 0.64, 1)",
        bounce: "cubic-bezier(0.68, -0.55, 0.27, 1.55)",
      },
      "enter-preset": "fadeUp",
      "exit-preset": "fadeDown",
      "hover-scale": "1.02",
      "press-scale": "0.97",
      "hover-lift": "-3px",
      "stagger-interval": "45ms",
      "stagger-interval-fast": "20ms",
    },
    borders: {
      width: { none: "0px", thin: "1px", medium: "1.5px", thick: "2px" },
      style: "solid",
      "card-border": "1px solid",
      "card-border-hover": "1px solid",
      "button-border": "1px solid",
      "input-border": "1px solid",
      "divider-style": "solid",
      "divider-width": "1px",
    },
    buttons: {
      "font-weight": "600",
      "text-transform": "none",
      "letter-spacing": "0em",
      "font-family": "'PP Neue Montreal', system-ui, sans-serif",
      "border-width": "1px",
      "hover-effect": "glow",
      "active-scale": "0.97",
      "icon-gap": "8px",
      "min-width": "0px",
    },
    cards: {
      "border-style": "solid",
      "border-width": "1px",
      "hover-effect": "glow",
      "hover-border-color": "var(--s-primary)",
      padding: "24px",
      "header-padding": "24px 24px 0",
      "footer-padding": "0 24px 24px",
      "title-size": "1.0625rem",
      "title-weight": "700",
      "description-size": "0.8125rem",
      background: "surface",
      shadow: "sm",
      outline: true,
      "outline-on-hover-only": false,
      "gap-between": "16px",
      "content-padding-x": "24px",
      "content-padding-y": "20px",
    },
    headings: {
      "h1-size": "2.375rem",
      "h1-weight": "800",
      "h1-tracking": "-0.03em",
      "h1-leading": "1.15",
      "h2-size": "1.875rem",
      "h2-weight": "700",
      "h2-tracking": "-0.025em",
      "h3-size": "1.5rem",
      "h3-weight": "600",
      "h4-size": "1.25rem",
      "h4-weight": "600",
      "display-size": "4rem",
      "display-weight": "800",
      "display-tracking": "-0.045em",
      "display-leading": "1.05",
    },
    navigation: {
      "navbar-height": "68px",
      "navbar-backdrop-blur": "20px",
      "navbar-border": "1px solid",
      "navbar-bg-opacity": "0.78",
      "nav-link-weight": "500",
      "nav-link-size": "0.875rem",
      "nav-link-hover": "background",
      "breadcrumb-separator": "›",
      "pagination-radius": "10px",
      "sidebar-width": "300px",
      "sidebar-item-radius": "12px",
      "sidebar-item-padding": "10px 16px",
    },
    backgrounds: {
      pattern: "hexagon",
      "pattern-opacity": "0.04",
      "pattern-scale": "1.2",
      noise: true,
      "noise-opacity": "0.03",
      "gradient-angle": "160deg",
      "gradient-type": "radial",
      "hero-pattern": "radial-glow",
      "section-divider": "none",
    },
    code: {
      "font-family": "'PP Supply Mono', ui-monospace, monospace",
      "font-size": "0.8125rem",
      "line-height": "1.7",
      bg: "var(--s-surface-sunken)",
      border: "1px solid var(--s-border-muted)",
      "border-radius": "12px",
      padding: "16px",
      "tab-size": "2",
      "selection-bg": "var(--s-primary-muted)",
      "comment-color": "var(--s-text-muted)",
      "keyword-color": "var(--s-primary)",
      "string-color": "var(--s-accent)",
      "number-color": "var(--s-warning)",
      "function-color": "var(--s-info)",
    },
    inputs: {
      height: "40px",
      "height-sm": "32px",
      "height-lg": "48px",
      "border-width": "1px",
      "focus-ring-width": "2px",
      "focus-ring-color": "var(--s-primary)",
      "focus-ring-offset": "2px",
      "placeholder-color": "var(--s-text-subtle)",
      "error-border-color": "var(--s-error)",
      "label-size": "0.8125rem",
      "label-weight": "600",
      "label-spacing": "6px",
      "helper-size": "0.75rem",
    },
    alignment: {
      "rail-width": "1240px",
      "rail-columns": "12",
      "rail-gutter": "24px",
      "rail-margin": "32px",
      "rail-visible": false,
      "rail-color": "var(--s-border-muted)",
      "content-align": "center",
      "hero-align": "center",
      "section-align": "center",
      "navbar-align": "full",
      "footer-align": "content",
    },
    sections: {
      "padding-y": "72px",
      "padding-y-hero": "140px",
      "padding-x": "32px",
      "max-width": "1240px",
      gap: "36px",
      "title-align": "left",
      "divider-above": false,
      "divider-below": true,
      "background-alt": false,
      indent: "0px",
    },
    dividers: {
      style: "solid",
      width: "1px",
      color: "var(--s-border)",
      spacing: "0px",
      "show-cross": false,
      "show-label": false,
      "full-bleed": false,
      ornament: "none",
    },
    gridVisuals: {
      "show-lines": false,
      "line-color": "var(--s-border-muted)",
      "line-width": "1px",
      "show-dots": true,
      "dot-size": "3px",
      "cell-background": "surface",
      "cell-border": true,
      "cell-radius": "0px",
      "cell-padding": "16px",
      "hover-effect": "none",
    },
  },
};
