import type { SigilPreset } from "@sigil-ui/tokens";

export const brassPreset: SigilPreset = {
  name: "brass",
  metadata: {
    description: "Vintage warmth — art deco elegance, warm metallics, paper-like ivory.",
    mood: "vintage, warm, art-deco",
    tags: ["vintage", "warm", "art-deco", "elegant", "serif"],
    author: "sigil-ui",
    version: "0.1.0",
  },
  tokens: {
    colors: {
      background: { light: "oklch(0.99 0.01 90)", dark: "oklch(0.1 0.02 60)" },
      surface: { light: "oklch(0.97 0.012 85)", dark: "oklch(0.14 0.018 60)" },
      "surface-elevated": { light: "oklch(0.99 0.008 95)", dark: "oklch(0.18 0.016 60)" },
      "surface-sunken": { light: "oklch(0.95 0.015 80)", dark: "oklch(0.08 0.02 60)" },
      primary: "oklch(0.58 0.14 75)",
      "primary-hover": "oklch(0.52 0.16 75)",
      "primary-muted": "oklch(0.85 0.05 75)",
      "primary-contrast": "oklch(0 0 0)",
      secondary: "oklch(0.4 0.06 50)",
      "secondary-hover": "oklch(0.35 0.07 50)",
      "secondary-muted": "oklch(0.75 0.03 50)",
      accent: "oklch(0.62 0.1 45)",
      "accent-hover": "oklch(0.56 0.12 45)",
      "accent-muted": "oklch(0.85 0.04 45)",
      text: { light: "oklch(0.2 0.03 50)", dark: "oklch(0.92 0.01 80)" },
      "text-secondary": { light: "oklch(0.38 0.02 50)", dark: "oklch(0.76 0.01 80)" },
      "text-muted": { light: "oklch(0.52 0.015 50)", dark: "oklch(0.64 0.008 80)" },
      "text-subtle": { light: "oklch(0.65 0.01 50)", dark: "oklch(0.52 0.006 80)" },
      "text-disabled": { light: "oklch(0.75 0.008 50)", dark: "oklch(0.35 0.005 80)" },
      "text-inverse": { light: "oklch(0.96 0.008 85)", dark: "oklch(0.14 0.02 55)" },
      border: { light: "oklch(0.65 0.015 75)", dark: "oklch(0.280 0.015 60)" },
      "border-muted": { light: "oklch(0.82 0.010 75)", dark: "oklch(0.220 0.012 60)" },
      "border-strong": { light: "oklch(0.65 0.02 75)", dark: "oklch(0.360 0.018 60)" },
      "border-interactive": { light: "oklch(0.58 0.14 75)", dark: "oklch(0.62 0.14 75)" },
      success: "oklch(0.63 0.16 155)",
      "success-muted": "oklch(0.65 0.05 155)",
      warning: "oklch(0.66 0.14 80)",
      "warning-muted": "oklch(0.75 0.05 80)",
      error: "oklch(0.58 0.18 25)",
      "error-muted": "oklch(0.58 0.06 25)",
      info: "oklch(0.62 0.13 240)",
      "info-muted": "oklch(0.62 0.05 240)",
      "gradient-start": "oklch(0.58 0.14 75)",
      "gradient-end": "oklch(0.62 0.1 45)",
      glow: "oklch(0.58 0.14 75 / 0.3)",
      highlight: { light: "oklch(0.93 0.06 75)", dark: "oklch(0.28 0.05 75)" },
    },
    typography: {
      "font-display": "'PP Woodland', Georgia, serif",
      "font-body": "'PP Woodland', Georgia, serif",
      "font-mono": "'PP Supply Mono', ui-monospace, monospace",
      "size-xs": "0.75rem",
      "size-sm": "0.8125rem",
      "size-base": "1rem",
      "size-lg": "1.125rem",
      "size-xl": "1.25rem",
      "size-2xl": "1.5rem",
      "size-3xl": "1.875rem",
      "size-4xl": "2.25rem",
      "size-5xl": "3rem",
      "size-6xl": "3.75rem",
      "weight-normal": "400",
      "weight-medium": "500",
      "weight-semibold": "600",
      "weight-bold": "700",
      "weight-extrabold": "800",
      "leading-tight": "1.3",
      "leading-normal": "1.65",
      "leading-relaxed": "1.8",
      "leading-loose": "2.1",
      "tracking-tighter": "-0.03em",
      "tracking-tight": "-0.015em",
      "tracking-normal": "0em",
      "tracking-wide": "0.015em",
      "tracking-wider": "0.03em",
      "heading-weight": "700",
      "heading-tracking": "0.01em",
      "heading-transform": "none",
      "heading-family": "'PP Woodland', Georgia, serif",
    },
    spacing: {
      scale: [4, 8, 16, 24, 32, 48, 64, 80, 104, 128],
      unit: "px",
      "button-px": "24px",
      "button-py": "10px",
      "button-px-sm": "16px",
      "button-py-sm": "7px",
      "button-px-lg": "32px",
      "button-py-lg": "14px",
      "card-padding": "28px",
      "card-padding-sm": "20px",
      "card-padding-lg": "40px",
      "input-px": "12px",
      "input-py": "8px",
      "badge-px": "8px",
      "badge-py": "3px",
      "section-py": "84px",
      "section-py-lg": "112px",
      "navbar-height": "56px",
      "navbar-px": "32px",
      "footer-py": "56px",
      "modal-padding": "28px",
      "popover-padding": "16px",
      "tooltip-padding": "6px 12px",
      "table-cell-px": "16px",
      "table-cell-py": "12px",
    },
    layout: {
      "content-max": "1200px",
      "content-max-narrow": "720px",
      "content-max-wide": "1440px",
      "page-margin": "32px",
      "page-margin-sm": "16px",
      "page-margin-lg": "56px",
      gutter: "32px",
      "gutter-sm": "16px",
      "gutter-lg": "44px",
      "grid-columns": "12",
      "grid-gap": "28px",
      "bento-gap": "18px",
      "bento-radius": "10px",
      "bento-min-height": "196px",
      "section-gap": "28px",
      "sidebar-width": "272px",
      "sidebar-collapsed": "56px",
      "footer-columns": "4",
      "stack-gap": "16px",
      "stack-gap-sm": "8px",
      "stack-gap-lg": "24px",
      "prose-max": "60ch",
    },
    sigil: {
      "grid-cell": "56px",
      "cross-arm": "12px",
      "cross-stroke": "1.5px",
      "rail-gap": "28px",
      "card-radius": "10px",
      "gutter-pattern": "zigzag",
      "margin-pattern": "horizontal",
      "margin-border": "1px solid var(--s-border-muted)",
    },
    radius: {
      none: "0px",
      sm: "4px",
      md: "8px",
      lg: "10px",
      xl: "12px",
      "2xl": "16px",
      full: "9999px",
      button: "8px",
      card: "10px",
      input: "8px",
      badge: "9999px",
      modal: "12px",
      popover: "10px",
      tooltip: "6px",
      image: "8px",
      bento: "10px",
    },
    shadows: {
      sm: "0 1px 2px 0 rgb(80 50 10 / 0.05)",
      md: "0 2px 4px -1px rgb(80 50 10 / 0.07), 0 1px 2px rgb(80 50 10 / 0.04)",
      lg: "0 4px 10px -2px rgb(80 50 10 / 0.09), 0 2px 4px -2px rgb(80 50 10 / 0.05)",
      xl: "0 10px 20px -4px rgb(80 50 10 / 0.1), 0 4px 8px -4px rgb(80 50 10 / 0.05)",
      "2xl": "0 24px 48px -12px rgb(80 50 10 / 0.18)",
      glow: "0 0 20px var(--s-primary)",
      "glow-sm": "0 0 10px var(--s-primary)",
      colored: "0 4px 14px -3px var(--s-primary)",
      inner: "inset 0 2px 4px 0 rgb(80 50 10 / 0.06)",
      card: "none",
      button: "none",
      "button-hover": "none",
      dropdown: "0 4px 12px rgb(80 50 10 / 0.1), 0 0 0 1px rgb(80 50 10 / 0.04)",
      modal: "0 16px 48px -8px rgb(80 50 10 / 0.18)",
    },
    motion: {
      duration: { instant: "0ms", fast: "160ms", normal: "280ms", slow: "450ms", slower: "650ms", slowest: "1100ms" },
      easing: {
        default: "cubic-bezier(0.25, 0.46, 0.45, 0.94)",
        in: "cubic-bezier(0.55, 0, 1, 0.45)",
        out: "cubic-bezier(0, 0.55, 0.45, 1)",
        "in-out": "cubic-bezier(0.45, 0, 0.55, 1)",
        spring: "cubic-bezier(0.34, 1.56, 0.64, 1)",
        bounce: "cubic-bezier(0.68, -0.55, 0.27, 1.55)",
      },
      "enter-preset": "fadeUp",
      "exit-preset": "fadeOut",
      "hover-scale": "1.0",
      "press-scale": "0.98",
      "hover-lift": "0px",
      "stagger-interval": "60ms",
      "stagger-interval-fast": "30ms",
    },
    borders: {
      width: { none: "0px", thin: "1px", medium: "1.5px", thick: "2px" },
      style: "solid",
      "card-border": "1px solid",
      "card-border-hover": "1px solid",
      "button-border": "1px solid",
      "input-border": "1px solid",
      "divider-style": "solid",
      "divider-width": "1px",
    },
    buttons: {
      "font-weight": "500",
      "text-transform": "capitalize",
      "letter-spacing": "0.01em",
      "font-family": "'PP Woodland', Georgia, serif",
      "border-width": "1px",
      "hover-effect": "darken",
      "active-scale": "0.98",
      "icon-gap": "8px",
      "min-width": "0px",
    },
    cards: {
      "border-style": "solid",
      "border-width": "1px",
      "hover-effect": "border",
      "hover-border-color": "var(--s-border)",
      padding: "28px",
      "header-padding": "28px 28px 0",
      "footer-padding": "0 28px 28px",
      "title-size": "1.125rem",
      "title-weight": "600",
      "description-size": "0.875rem",
      background: "surface",
      shadow: "none",
      outline: true,
      "outline-on-hover-only": false,
      "gap-between": "20px",
      "content-padding-x": "28px",
      "content-padding-y": "24px",
    },
    headings: {
      "h1-size": "2.5rem",
      "h1-weight": "700",
      "h1-tracking": "-0.025em",
      "h1-leading": "1.2",
      "h2-size": "1.875rem",
      "h2-weight": "700",
      "h2-tracking": "-0.02em",
      "h2-leading": "1.15",
      "h3-size": "1.5rem",
      "h3-weight": "600",
      "h3-tracking": "0em",
      "h3-leading": "1.2",
      "h4-size": "1.25rem",
      "h4-weight": "600",
      "h4-tracking": "0em",
      "h4-leading": "1.3",
      "display-size": "4rem",
      "display-weight": "700",
      "display-tracking": "-0.035em",
      "display-leading": "1.1",
    },
    navigation: {
      "navbar-height": "56px",
      "navbar-backdrop-blur": "10px",
      "navbar-border": "1px solid",
      "navbar-bg-opacity": "0.9",
      "navbar-padding-x": "20px",
      "navbar-position": "sticky",
      "navbar-logo-height": "22px",
      "navbar-logo-gap": "8px",
      "navbar-item-gap": "16px",
      "navbar-item-padding-x": "10px",
      "navbar-item-padding-y": "4px",
      "navbar-item-size": "0.8125rem",
      "navbar-shadow": "none",
      "navbar-height-scrolled": "44px",
      "navbar-mobile-breakpoint": "768px",
      "nav-link-weight": "500",
      "nav-link-size": "0.875rem",
      "nav-link-hover": "underline",
      "breadcrumb-separator": "·",
      "pagination-radius": "8px",
      "sidebar-width": "272px",
      "sidebar-item-radius": "8px",
      "sidebar-item-padding": "10px 14px",
    },
    backgrounds: {
      pattern: "none",
      "pattern-opacity": "0",
      "pattern-scale": "1",
      noise: true,
      "noise-opacity": "0.03",
      "gradient-angle": "180deg",
      "gradient-type": "linear",
      "hero-pattern": "noise",
      "section-divider": "line",
    },
    code: {
      "font-family": "'PP Supply Mono', ui-monospace, monospace",
      "font-size": "0.8125rem",
      "line-height": "1.7",
      bg: "var(--s-surface-sunken)",
      border: "1px solid var(--s-border)",
      "border-radius": "8px",
      padding: "16px",
      "tab-size": "2",
      "selection-bg": "var(--s-primary-muted)",
      "comment-color": "var(--s-text-muted)",
      "keyword-color": "var(--s-primary)",
      "string-color": "var(--s-success)",
      "number-color": "var(--s-warning)",
      "function-color": "var(--s-accent)",
    },
    inputs: {
      height: "40px",
      "height-sm": "32px",
      "height-lg": "48px",
      "border-width": "1px",
      "focus-ring-width": "2px",
      "focus-ring-color": "var(--s-primary)",
      "focus-ring-offset": "2px",
      "placeholder-color": "var(--s-text-subtle)",
      "error-border-color": "var(--s-error)",
      "label-size": "0.8125rem",
      "label-weight": "500",
      "label-spacing": "6px",
      "helper-size": "0.75rem",
    },
    alignment: {
      "title-align": "center",
    },
    sections: {
      "rail-margin": "56px",
      "padding-y": "84px",
      "padding-y-hero": "140px",
      "padding-y-sm": "36px",
      gap: "40px",
      "padding-y-lg": "72px",
      "padding-y-xl": "96px",
      "max-width": "860px",
      indent: "32px",
      "heading-size": "clamp(1.25rem, 3vw, 2rem)",
      "heading-align": "left",
      "heading-max-width": "36rem",
      "heading-margin-bottom": "12px",
      "description-max-width": "28rem",
      "description-gap": "8px",
      "content-gap": "16px",
      "grid-columns": "3",
      "grid-gap": "16px",
      "alternate-bg": "var(--s-surface)",
      "alternate-bg-mode": "none",
    },
    dividers: {
      style: "dashed",
      width: "1px",
      opacity: "1",
      "max-width": "100%",
      "margin-y": "0px",
      thickness: "2px",
      "gradient-start": "transparent",
      "gradient-end": "transparent",
      ornament: "diamond",
    },
    gridVisuals: {
      "line-color": "var(--s-border-muted)",
      "line-width": "1px",
      "show-lines": false,
    },
    cursor: {
      variant: "crosshair",
      size: "24px",
      "dot-size": "4px",
      "stroke-width": "2px",
      "tick-size": "6px",
      gap: "3px",
      radius: "0px",
      color: "var(--s-text)",
      "ring-color": "var(--s-primary)",
      "dot-color": "var(--s-primary)",
      glow: "none",
      opacity: "1",
      "blend-mode": "normal",
      "z-index": "9999",
      "hide-native": false,
    },
    scrollbar: {
      width: "10px",
      height: "10px",
      padding: "2px",
      radius: "2px",
      track: "transparent",
      thumb: "var(--s-border-muted)",
      "thumb-hover": "var(--s-border)",
      "thumb-active": "var(--s-border-strong)",
      corner: "transparent",
      border: "none",
      "firefox-width": "auto",
      gutter: "stable",
      visibility: "auto",
    },
    focus: {
      "ring-width": "3px",
      "ring-color": "var(--s-primary)",
      "ring-offset": "0px",
      "ring-shadow": "0 0 0 3px var(--s-primary)",
      "outline-color": "var(--s-primary)",
    },
    overlays: {
      bg: "rgb(0 0 0 / 0.6)",
      blur: "4px",
      surface: "var(--s-surface-elevated)",
      border: "1px solid var(--s-border-muted)",
      shadow: "var(--s-shadow-xl)",
      radius: "var(--s-radius-lg)",
      padding: "20px",
      "z-index": "50",
    },
    dataViz: {
      "series-1": "var(--s-primary)",
      "series-2": "var(--s-secondary)",
      "series-3": "var(--s-accent)",
      "series-4": "var(--s-info)",
      "series-5": "var(--s-success)",
      positive: "var(--s-success)",
      negative: "var(--s-error)",
      neutral: "var(--s-text-muted)",
      grid: "var(--s-border-muted)",
      axis: "var(--s-border)",
      label: "var(--s-text-secondary)",
      "tooltip-bg": "var(--s-surface-elevated)",
      "tooltip-border": "var(--s-border-muted)",
    },
    media: {
      radius: "var(--s-radius-md)",
      border: "none",
      outline: "1px solid rgb(0 0 0 / 0.08)",
      shadow: "none",
      bg: "var(--s-surface-sunken)",
      "object-fit": "cover",
    },
    controls: {
      height: "38px",
      "height-sm": "30px",
      "height-lg": "46px",
      "hit-area": "44px",
      "icon-size": "16px",
      "handle-size": "20px",
      "track-height": "4px",
      "track-bg": "var(--s-border-muted)",
      "track-fill": "var(--s-primary)",
      "thumb-bg": "var(--s-surface-elevated)",
      "thumb-border": "2px solid var(--s-primary)",
    },
    componentSurfaces: {
      bg: "var(--s-surface)",
      "bg-elevated": "var(--s-surface-elevated)",
      "bg-muted": "var(--s-surface-sunken)",
      border: "var(--s-border)",
      "border-muted": "var(--s-border-muted)",
      "border-strong": "var(--s-border-strong)",
      text: "var(--s-text)",
      "text-muted": "var(--s-text-muted)",
      contrast: "var(--s-primary-contrast)",
      "hover-bg": "var(--s-surface-elevated)",
      "active-bg": "var(--s-surface-sunken)",
      "selected-bg": "var(--s-primary-muted)",
    },
    hero: {
      "min-height": "auto",
      "padding-y": "84px",
      "padding-y-sm": "56px",
      "padding-x": "var(--s-page-margin, 20px)",
      "content-max": "560px",
      "content-align": "left",
      layout: "split",
      "media-position": "right",
      "media-width": "45%",
      "media-radius": "var(--s-radius-sm)",
      "title-size": "clamp(1.75rem, 5vw, 3rem)",
      "title-max-width": "40rem",
      "description-size": "1rem",
      "description-max-width": "28rem",
      "description-gap": "16px",
      "actions-gap": "10px",
      "actions-margin-top": "24px",
      "action-padding-x": "20px",
      "action-padding-y": "10px",
      "badge-gap": "16px",
      "overlay-opacity": "0.6",
      "scroll-indicator": false,
      "gradient-overlay": "none",
    },
    cta: {
      "padding-y": "56px",
      "padding-x": "var(--s-page-margin, 20px)",
      "max-width": "var(--s-content-max, 1200px)",
      layout: "split",
      border: true,
      "border-radius": "var(--s-radius-sm)",
      bg: "var(--s-surface)",
      "title-size": "clamp(1.25rem, 3vw, 2rem)",
      "description-max-width": "28rem",
      "description-gap": "8px",
      "actions-gap": "10px",
      "actions-margin-top": "20px",
      "action-padding-x": "20px",
      "action-padding-y": "10px",
      "split-gap": "28px",
    },
    footer: {
      "padding-y": "28px",
      "border-top": "2px solid var(--s-border-strong)",
      columns: "4",
      "column-gap": "24px",
      "row-gap": "24px",
      "logo-height": "20px",
      "tagline-max-width": "18rem",
      "link-size": "0.8125rem",
      "link-gap": "6px",
      "group-title-size": "0.75rem",
      "group-title-weight": "700",
      "social-icon-size": "16px",
      "social-gap": "10px",
      "bottom-bar-padding": "28px 0",
      "bottom-bar-border": "2px solid var(--s-border)",
    },
    banner: {
      height: "auto",
      "padding-y": "6px",
      "padding-x": "16px",
      "font-size": "0.8125rem",
      "font-weight": "600",
      "icon-size": "14px",
      "icon-gap": "8px",
      "border-width": "2px",
      "border-position": "bottom",
      position: "top",
      "dismiss-size": "14px",
      radius: "0px",
    },
    pageRhythm: {
      density: "compact",
      "section-gap": "0px",
      "section-gap-sm": "0px",
      "section-gap-lg": "0px",
      "first-section-offset": "0px",
      "last-section-margin": "0px",
      "alternate-bg": false,
      "alternate-bg-color": "var(--s-surface)",
      "divider-between": true,
      "max-content-width": "var(--s-content-max, 1200px)",
      "vertical-rhythm-unit": "4px",
      "scroll-snap": false,
      "responsive-scale": "1",
      "responsive-breakpoint": "768px",
    },

  },
};
