import type { SigilPreset } from "@sigil-ui/tokens";

export const brassPreset: SigilPreset = {
  name: "brass",
  metadata: {
    description: "Vintage warmth — art deco elegance, warm metallics, paper-like ivory.",
    mood: "vintage, warm, art-deco",
    tags: ["vintage", "warm", "art-deco", "elegant", "serif"],
    author: "sigil-ui",
    version: "0.1.0",
  },
  tokens: {
    colors: {
      background: { light: "oklch(0.99 0.01 90)", dark: "oklch(0.1 0.02 60)" },
      surface: { light: "oklch(0.97 0.012 85)", dark: "oklch(0.14 0.018 60)" },
      "surface-elevated": { light: "oklch(0.99 0.008 95)", dark: "oklch(0.18 0.016 60)" },
      "surface-sunken": { light: "oklch(0.95 0.015 80)", dark: "oklch(0.08 0.02 60)" },
      primary: "oklch(0.58 0.14 75)",
      "primary-hover": "oklch(0.52 0.16 75)",
      "primary-muted": "oklch(0.85 0.05 75)",
      "primary-contrast": "oklch(0.99 0.005 90)",
      secondary: "oklch(0.4 0.06 50)",
      "secondary-hover": "oklch(0.35 0.07 50)",
      "secondary-muted": "oklch(0.75 0.03 50)",
      accent: "oklch(0.62 0.1 45)",
      "accent-hover": "oklch(0.56 0.12 45)",
      "accent-muted": "oklch(0.85 0.04 45)",
      text: { light: "oklch(0.2 0.03 50)", dark: "oklch(0.92 0.01 80)" },
      "text-secondary": { light: "oklch(0.38 0.02 50)", dark: "oklch(0.76 0.01 80)" },
      "text-muted": { light: "oklch(0.52 0.015 50)", dark: "oklch(0.64 0.008 80)" },
      "text-subtle": { light: "oklch(0.65 0.01 50)", dark: "oklch(0.52 0.006 80)" },
      "text-disabled": { light: "oklch(0.75 0.008 50)", dark: "oklch(0.35 0.005 80)" },
      "text-inverse": { light: "oklch(0.96 0.008 85)", dark: "oklch(0.14 0.02 55)" },
      border: { light: "oklch(0.87 0.015 75)", dark: "oklch(0.25 0.015 60)" },
      "border-muted": { light: "oklch(0.91 0.01 75)", dark: "oklch(0.26 0.012 60)" },
      "border-strong": { light: "oklch(0.76 0.02 75)", dark: "oklch(0.35 0.018 60)" },
      "border-interactive": { light: "oklch(0.58 0.14 75)", dark: "oklch(0.62 0.14 75)" },
      success: "oklch(0.65 0.16 155)",
      "success-muted": "oklch(0.65 0.05 155)",
      warning: "oklch(0.75 0.14 80)",
      "warning-muted": "oklch(0.75 0.05 80)",
      error: "oklch(0.58 0.18 25)",
      "error-muted": "oklch(0.58 0.06 25)",
      info: "oklch(0.62 0.13 240)",
      "info-muted": "oklch(0.62 0.05 240)",
      "gradient-start": "oklch(0.58 0.14 75)",
      "gradient-end": "oklch(0.62 0.1 45)",
      glow: "oklch(0.58 0.14 75 / 0.3)",
    },
    typography: {
      "font-display": "'PP Woodland', Georgia, serif",
      "font-body": "'PP Woodland', Georgia, serif",
      "font-mono": "'PP Supply Mono', ui-monospace, monospace",
      "size-xs": "0.75rem",
      "size-sm": "0.8125rem",
      "size-base": "1rem",
      "size-lg": "1.125rem",
      "size-xl": "1.25rem",
      "size-2xl": "1.5rem",
      "size-3xl": "1.875rem",
      "size-4xl": "2.25rem",
      "size-5xl": "3rem",
      "size-6xl": "3.75rem",
      "weight-normal": "400",
      "weight-medium": "500",
      "weight-semibold": "600",
      "weight-bold": "700",
      "weight-extrabold": "800",
      "leading-tight": "1.3",
      "leading-normal": "1.65",
      "leading-relaxed": "1.8",
      "leading-loose": "2.1",
      "tracking-tighter": "-0.03em",
      "tracking-tight": "-0.015em",
      "tracking-normal": "0em",
      "tracking-wide": "0.015em",
      "tracking-wider": "0.03em",
      "heading-weight": "700",
      "heading-tracking": "0.01em",
      "heading-transform": "none",
      "heading-family": "'PP Woodland', Georgia, serif",
    },
    spacing: {
      scale: [4, 8, 16, 24, 32, 48, 64, 80, 104, 128],
      unit: "px",
      "button-px": "24px",
      "button-py": "10px",
      "button-px-sm": "16px",
      "button-py-sm": "7px",
      "button-px-lg": "32px",
      "button-py-lg": "14px",
      "card-padding": "28px",
      "card-padding-sm": "20px",
      "card-padding-lg": "40px",
      "input-px": "12px",
      "input-py": "8px",
      "badge-px": "8px",
      "badge-py": "3px",
      "section-py": "84px",
      "section-py-lg": "124px",
      "navbar-height": "68px",
      "navbar-px": "32px",
      "footer-py": "64px",
      "modal-padding": "28px",
      "popover-padding": "16px",
      "tooltip-padding": "6px 12px",
      "table-cell-px": "16px",
      "table-cell-py": "12px",
    },
    layout: {
      "content-max": "1140px",
      "content-max-narrow": "680px",
      "content-max-wide": "1360px",
      "page-margin": "32px",
      "page-margin-sm": "16px",
      "page-margin-lg": "56px",
      gutter: "32px",
      "gutter-sm": "16px",
      "gutter-lg": "44px",
      "grid-columns": "12",
      "grid-gap": "28px",
      "bento-gap": "18px",
      "bento-radius": "10px",
      "bento-min-height": "200px",
      "section-gap": "36px",
      "sidebar-width": "272px",
      "sidebar-collapsed": "56px",
      "footer-columns": "4",
      "stack-gap": "16px",
      "stack-gap-sm": "8px",
      "stack-gap-lg": "24px",
      "prose-max": "60ch",
    },
    sigil: {
      "grid-cell": "56px",
      "cross-arm": "12px",
      "cross-stroke": "1.5px",
      "rail-gap": "28px",
      "card-radius": "10px",
      "gutter-pattern": "zigzag",
      "margin-pattern": "horizontal",
    },
    radius: {
      none: "0px",
      sm: "4px",
      md: "8px",
      lg: "10px",
      xl: "12px",
      "2xl": "16px",
      full: "9999px",
      button: "8px",
      card: "10px",
      input: "8px",
      badge: "9999px",
      modal: "12px",
      popover: "10px",
      tooltip: "6px",
      image: "8px",
      bento: "10px",
    },
    shadows: {
      sm: "0 1px 2px 0 rgb(80 50 10 / 0.05)",
      md: "0 2px 4px -1px rgb(80 50 10 / 0.07), 0 1px 2px rgb(80 50 10 / 0.04)",
      lg: "0 4px 10px -2px rgb(80 50 10 / 0.09), 0 2px 4px -2px rgb(80 50 10 / 0.05)",
      xl: "0 10px 20px -4px rgb(80 50 10 / 0.1), 0 4px 8px -4px rgb(80 50 10 / 0.05)",
      "2xl": "0 24px 48px -12px rgb(80 50 10 / 0.18)",
      glow: "0 0 20px var(--s-primary)",
      "glow-sm": "0 0 10px var(--s-primary)",
      colored: "0 4px 14px -3px var(--s-primary)",
      inner: "inset 0 2px 4px 0 rgb(80 50 10 / 0.06)",
      card: "none",
      button: "none",
      "button-hover": "none",
      dropdown: "0 4px 12px rgb(80 50 10 / 0.1), 0 0 0 1px rgb(80 50 10 / 0.04)",
      modal: "0 16px 48px -8px rgb(80 50 10 / 0.18)",
    },
    motion: {
      duration: { instant: "0ms", fast: "160ms", normal: "280ms", slow: "450ms", slower: "650ms", slowest: "1100ms" },
      easing: {
        default: "cubic-bezier(0.25, 0.46, 0.45, 0.94)",
        in: "cubic-bezier(0.55, 0, 1, 0.45)",
        out: "cubic-bezier(0, 0.55, 0.45, 1)",
        "in-out": "cubic-bezier(0.45, 0, 0.55, 1)",
        spring: "cubic-bezier(0.34, 1.56, 0.64, 1)",
        bounce: "cubic-bezier(0.68, -0.55, 0.27, 1.55)",
      },
      "enter-preset": "fadeUp",
      "exit-preset": "fadeOut",
      "hover-scale": "1.0",
      "press-scale": "0.98",
      "hover-lift": "0px",
      "stagger-interval": "60ms",
      "stagger-interval-fast": "30ms",
    },
    borders: {
      width: { none: "0px", thin: "1px", medium: "1.5px", thick: "2px" },
      style: "solid",
      "card-border": "1px solid",
      "card-border-hover": "1px solid",
      "button-border": "1px solid",
      "input-border": "1px solid",
      "divider-style": "solid",
      "divider-width": "1px",
    },
    buttons: {
      "font-weight": "500",
      "text-transform": "capitalize",
      "letter-spacing": "0.01em",
      "font-family": "'PP Woodland', Georgia, serif",
      "border-width": "1px",
      "hover-effect": "darken",
      "active-scale": "0.98",
      "icon-gap": "8px",
      "min-width": "0px",
    },
    cards: {
      "border-style": "solid",
      "border-width": "1px",
      "hover-effect": "border",
      "hover-border-color": "var(--s-border)",
      padding: "28px",
      "header-padding": "28px 28px 0",
      "footer-padding": "0 28px 28px",
      "title-size": "1.125rem",
      "title-weight": "600",
      "description-size": "0.875rem",
      background: "surface",
      shadow: "none",
      outline: true,
      "outline-on-hover-only": false,
      "gap-between": "20px",
      "content-padding-x": "28px",
      "content-padding-y": "24px",
    },
    headings: {
      "h1-size": "2.5rem",
      "h1-weight": "700",
      "h1-tracking": "-0.025em",
      "h1-leading": "1.2",
      "h2-size": "1.875rem",
      "h2-weight": "700",
      "h2-tracking": "-0.02em",
      "h3-size": "1.5rem",
      "h3-weight": "600",
      "h4-size": "1.25rem",
      "h4-weight": "600",
      "display-size": "4rem",
      "display-weight": "700",
      "display-tracking": "-0.035em",
      "display-leading": "1.1",
    },
    navigation: {
      "navbar-height": "68px",
      "navbar-backdrop-blur": "10px",
      "navbar-border": "1px solid",
      "navbar-bg-opacity": "0.9",
      "nav-link-weight": "500",
      "nav-link-size": "0.875rem",
      "nav-link-hover": "underline",
      "breadcrumb-separator": "·",
      "pagination-radius": "8px",
      "sidebar-width": "272px",
      "sidebar-item-radius": "8px",
      "sidebar-item-padding": "10px 14px",
    },
    backgrounds: {
      pattern: "none",
      "pattern-opacity": "0",
      "pattern-scale": "1",
      noise: true,
      "noise-opacity": "0.03",
      "gradient-angle": "180deg",
      "gradient-type": "linear",
      "hero-pattern": "noise",
      "section-divider": "line",
    },
    code: {
      "font-family": "'PP Supply Mono', ui-monospace, monospace",
      "font-size": "0.8125rem",
      "line-height": "1.7",
      bg: "var(--s-surface-sunken)",
      border: "1px solid var(--s-border)",
      "border-radius": "8px",
      padding: "16px",
      "tab-size": "2",
      "selection-bg": "var(--s-primary-muted)",
      "comment-color": "var(--s-text-muted)",
      "keyword-color": "var(--s-primary)",
      "string-color": "var(--s-success)",
      "number-color": "var(--s-warning)",
      "function-color": "var(--s-accent)",
    },
    inputs: {
      height: "40px",
      "height-sm": "32px",
      "height-lg": "48px",
      "border-width": "1px",
      "focus-ring-width": "2px",
      "focus-ring-color": "var(--s-primary)",
      "focus-ring-offset": "2px",
      "placeholder-color": "var(--s-text-subtle)",
      "error-border-color": "var(--s-error)",
      "label-size": "0.8125rem",
      "label-weight": "500",
      "label-spacing": "6px",
      "helper-size": "0.75rem",
    },
    alignment: {
      "title-align": "center",
    },
    sections: {
      "rail-margin": "56px",
      "padding-y": "80px",
      "padding-y-hero": "140px",
      gap: "40px",
      "max-width": "860px",
      indent: "32px",
    },
    dividers: {
      style: "dashed",
      width: "1px",
      ornament: "diamond",
    },
    gridVisuals: {
      "show-lines": false,
    },
  },
};
