import type { SigilPreset } from "@sigil-ui/tokens";

export const cobaltPreset: SigilPreset = {
  name: "cobalt",
  metadata: {
    description: "Blue metallic — chemical precision, deep blue spectrum",
    author: "sigil-ui",
    version: "0.1.0",
    tags: ["dark", "blue", "metallic", "chemical", "precision"],
    mood: "metallic, chemical, deep-blue",
    inspiration: "Cobalt compounds, scientific instruments, deep ocean",
  },
  tokens: {
    colors: {
      background: { light: "#f0f4ff", dark: "#020617" },
      surface: { light: "#e8eeff", dark: "#0c1425" },
      "surface-elevated": { light: "#f8f9ff", dark: "#131b30" },
      "surface-sunken": { light: "#dce4f5", dark: "#010410" },
      text: { light: "#0f172a", dark: "#e2e8f0" },
      "text-secondary": { light: "#334155", dark: "#94a3b8" },
      "text-muted": { light: "#607087", dark: "#8b9ab8" },
      "text-subtle": { light: "#7e8ca1", dark: "#6b7a96" },
      "text-disabled": { light: "#cbd5e1", dark: "#1e293b" },
      "text-inverse": { light: "#f0f4ff", dark: "#0f172a" },
      border: { light: "#8089b2", dark: "oklch(0.309 0.035 258)" },
      "border-muted": { light: "#b5bddc", dark: "oklch(0.249 0.025 260)" },
      "border-strong": { light: "#7781ec", dark: "oklch(0.389 0.039 257)" },
      "border-interactive": { light: "#2563eb", dark: "#3b82f6" },
      primary: "#2563eb",
      "primary-hover": "#1d4ed8",
      "primary-muted": "#dbeafe",
      "primary-contrast": "#ffffff",
      secondary: "#475569",
      "secondary-hover": "#334155",
      "secondary-muted": "#e2e8f0",
      accent: "#06b6d4",
      "accent-hover": "#0891b2",
      "accent-muted": "#cffafe",
      success: "#059669",
      "success-muted": "#d1fae5",
      warning: "#d37200",
      "warning-muted": "#fef3c7",
      error: "#dc2626",
      "error-muted": "#fee2e2",
      info: "#0284c7",
      "info-muted": "#e0f2fe",
      "gradient-start": "#2563eb",
      "gradient-end": "#06b6d4",
      glow: "rgba(37, 99, 235, 0.3)",
      highlight: { light: "#dbeafe", dark: "rgba(59, 130, 246, 0.15)" },
    },
    typography: {
      "font-display": "'PP Telegraf', system-ui, sans-serif",
      "font-body": "'PP Telegraf', system-ui, sans-serif",
      "font-mono": "'PP Fraktion Mono', ui-monospace, monospace",
      "size-xs": "0.75rem",
      "size-sm": "0.8125rem",
      "size-base": "0.9375rem",
      "size-lg": "1.0625rem",
      "size-xl": "1.25rem",
      "size-2xl": "1.5rem",
      "size-3xl": "1.875rem",
      "size-4xl": "2.25rem",
      "size-5xl": "3rem",
      "size-6xl": "3.75rem",
      "weight-normal": "400",
      "weight-medium": "500",
      "weight-semibold": "600",
      "weight-bold": "700",
      "weight-extrabold": "800",
      "leading-tight": "1.2",
      "leading-normal": "1.5",
      "leading-relaxed": "1.65",
      "leading-loose": "1.8",
      "tracking-tighter": "-0.03em",
      "tracking-tight": "-0.015em",
      "tracking-normal": "0em",
      "tracking-wide": "0.025em",
      "tracking-wider": "0.05em",
      "heading-weight": "700",
      "heading-tracking": "-0.02em",
      "heading-transform": "none",
      "heading-family": "'PP Telegraf', system-ui, sans-serif",
    },
    spacing: {
      scale: [4, 8, 12, 16, 24, 32, 48, 64, 80, 96],
      unit: "px",
      "button-px": "20px",
      "button-py": "10px",
      "button-px-sm": "14px",
      "button-py-sm": "7px",
      "button-px-lg": "28px",
      "button-py-lg": "14px",
      "card-padding": "28px",
      "card-padding-sm": "18px",
      "card-padding-lg": "40px",
      "input-px": "14px",
      "input-py": "10px",
      "badge-px": "10px",
      "badge-py": "3px",
      "section-py": "7rem",
      "section-py-lg": "10.5rem",
      "navbar-height": "56px",
      "navbar-px": "32px",
      "footer-py": "56px",
      "modal-padding": "24px",
      "popover-padding": "14px",
      "tooltip-padding": "6px 10px",
      "table-cell-px": "14px",
      "table-cell-py": "10px",
    },
    layout: {
      "content-max": "1200px",
      "content-max-narrow": "720px",
      "content-max-wide": "1440px",
      "page-margin": "32px",
      "page-margin-sm": "16px",
      "page-margin-lg": "56px",
      gutter: "32px",
      "gutter-sm": "16px",
      "gutter-lg": "44px",
      "grid-columns": "12",
      "grid-gap": "28px",
      "bento-gap": "20px",
      "bento-radius": "12px",
      "bento-min-height": "196px",
      "section-gap": "56px",
      "sidebar-width": "288px",
      "sidebar-collapsed": "56px",
      "footer-columns": "4",
      "stack-gap": "16px",
      "stack-gap-sm": "8px",
      "stack-gap-lg": "24px",
      "prose-max": "65ch",
    },
    sigil: {
      "grid-cell": "56px",
      "cross-arm": "12px",
      "cross-stroke": "1.5px",
      "rail-gap": "32px",
      "card-radius": "10px",
      "gutter-pattern": "triangle",
      "margin-pattern": "diagonal",
      "margin-border": "1px solid var(--s-border-muted)",
      "band-height": "56px",
      "divider-thickness-sm": "29px",
      "divider-thickness-md": "57px",
      "divider-thickness-lg": "113px",
      "divider-thickness-xl": "169px",
    },
    radius: {
      none: "0px",
      sm: "4px",
      md: "8px",
      lg: "10px",
      xl: "12px",
      "2xl": "16px",
      full: "9999px",
      button: "8px",
      card: "10px",
      input: "8px",
      badge: "6px",
      modal: "12px",
      popover: "10px",
      tooltip: "6px",
      image: "8px",
      bento: "12px",
    },
    shadows: {
      sm: "0 1px 2px rgba(2, 6, 23, 0.08)",
      md: "0 2px 4px rgba(2, 6, 23, 0.1)",
      lg: "0 4px 8px rgba(2, 6, 23, 0.12)",
      xl: "0 8px 16px rgba(2, 6, 23, 0.14)",
      "2xl": "0 16px 32px rgba(2, 6, 23, 0.18)",
      glow: "0 0 24px rgba(37, 99, 235, 0.25)",
      "glow-sm": "0 0 12px rgba(37, 99, 235, 0.15)",
      colored: "0 4px 16px rgba(37, 99, 235, 0.2)",
      inner: "inset 0 1px 3px rgba(2, 6, 23, 0.1)",
      card: "0 1px 3px rgba(2, 6, 23, 0.06), 0 0 0 1px rgba(37, 99, 235, 0.04)",
      button: "0 1px 2px rgba(2, 6, 23, 0.1)",
      "button-hover": "0 0 16px rgba(37, 99, 235, 0.2)",
      dropdown: "0 4px 16px rgba(2, 6, 23, 0.15)",
      modal: "0 16px 48px rgba(2, 6, 23, 0.25)",
    },
    motion: {
      duration: {
        instant: "0ms",
        fast: "120ms",
        normal: "220ms",
        slow: "350ms",
        slower: "500ms",
        slowest: "700ms",
      },
      easing: {
        default: "cubic-bezier(0.16, 1, 0.3, 1)",
        in: "cubic-bezier(0.55, 0, 1, 0.45)",
        out: "cubic-bezier(0, 0.55, 0.45, 1)",
        "in-out": "cubic-bezier(0.45, 0, 0.55, 1)",
        spring: "cubic-bezier(0.34, 1.56, 0.64, 1)",
        bounce: "cubic-bezier(0.34, 1.4, 0.64, 1)",
      },
      "enter-preset": "220ms cubic-bezier(0.16, 1, 0.3, 1)",
      "exit-preset": "160ms cubic-bezier(0.55, 0, 1, 0.45)",
      "hover-scale": "1.01",
      "press-scale": "0.97",
      "hover-lift": "-2px",
      "stagger-interval": "50ms",
      "stagger-interval-fast": "25ms",
    },
    borders: {
      width: { none: "0px", thin: "1px", medium: "1.5px", thick: "2px" },
      style: "solid",
      "card-border": "1px solid rgba(37, 99, 235, 0.1)",
      "card-border-hover": "1px solid rgba(37, 99, 235, 0.25)",
      "button-border": "1px solid rgba(37, 99, 235, 0.15)",
      "input-border": "1px solid var(--s-border)",
      "divider-style": "solid",
      "divider-width": "1px",
    },
    buttons: {
      "font-weight": "600",
      "text-transform": "none",
      "letter-spacing": "0em",
      "font-family": "'PP Telegraf', system-ui, sans-serif",
      "border-width": "1px",
      "hover-effect": "glow",
      "active-scale": "0.97",
      "icon-gap": "8px",
      "min-width": "0px",
    },
    cards: {
      "border-style": "solid",
      "border-width": "1px",
      "hover-effect": "glow",
      "hover-border-color": "rgba(37, 99, 235, 0.3)",
      padding: "24px",
      "header-padding": "24px 24px 0",
      "footer-padding": "0 24px 24px",
      "title-size": "var(--s-size-lg)",
      "title-weight": "600",
      "description-size": "var(--s-size-sm)",
      background: "surface",
      shadow: "sm",
      outline: true,
      "outline-on-hover-only": false,
      "gap-between": "16px",
      "content-padding-x": "24px",
      "content-padding-y": "20px",
    },
    headings: {
      "h1-size": "3rem",
      "h1-weight": "700",
      "h1-tracking": "-0.03em",
      "h1-leading": "1.1",
      "h2-size": "2.25rem",
      "h2-weight": "700",
      "h2-tracking": "-0.02em",
      "h2-leading": "1.1",
      "h3-size": "1.5rem",
      "h3-weight": "600",
      "h3-tracking": "0em",
      "h3-leading": "1.15",
      "h4-size": "1.1875rem",
      "h4-weight": "600",
      "h4-tracking": "0em",
      "h4-leading": "1.2",
      "display-size": "3.75rem",
      "display-weight": "800",
      "display-tracking": "-0.04em",
      "display-leading": "1.05",
    },
    navigation: {
      "navbar-height": "56px",
      "navbar-backdrop-blur": "20px",
      "navbar-border": "1px solid rgba(37, 99, 235, 0.08)",
      "navbar-bg-opacity": "0.75",
      "navbar-padding-x": "20px",
      "navbar-position": "sticky",
      "navbar-logo-height": "22px",
      "navbar-logo-gap": "8px",
      "navbar-item-gap": "20px",
      "navbar-item-padding-x": "10px",
      "navbar-item-padding-y": "4px",
      "navbar-item-size": "0.8125rem",
      "navbar-shadow": "none",
      "navbar-height-scrolled": "44px",
      "navbar-mobile-breakpoint": "768px",
      "nav-link-weight": "500",
      "nav-link-size": "var(--s-size-sm)",
      "nav-link-hover": "background",
      "breadcrumb-separator": "/",
      "pagination-radius": "8px",
      "sidebar-width": "288px",
      "sidebar-item-radius": "10px",
      "sidebar-item-padding": "10px 16px",
    },
    backgrounds: {
      pattern: "grid",
      "pattern-opacity": "0.04",
      "pattern-scale": "48px",
      noise: true,
      "noise-opacity": "0.02",
      "gradient-angle": "135deg",
      "gradient-type": "linear",
      "hero-pattern": "gradient",
      "section-divider": "line",
    },
    code: {
      "font-family": "'PP Fraktion Mono', ui-monospace, monospace",
      "font-size": "0.8125rem",
      "line-height": "1.6",
      bg: "#0c1425",
      border: "1px solid rgba(37, 99, 235, 0.12)",
      "border-radius": "8px",
      padding: "20px 24px",
      "tab-size": "2",
      "selection-bg": "rgba(37, 99, 235, 0.2)",
      "comment-color": "#475569",
      "keyword-color": "#3b82f6",
      "string-color": "#06b6d4",
      "number-color": "#f59e0b",
      "function-color": "#818cf8",
    },
    inputs: {
      height: "40px",
      "height-sm": "32px",
      "height-lg": "48px",
      "border-width": "1px",
      "focus-ring-width": "2px",
      "focus-ring-color": "var(--s-primary)",
      "focus-ring-offset": "1px",
      "placeholder-color": "var(--s-text-muted)",
      "error-border-color": "var(--s-error)",
      "label-size": "var(--s-size-sm)",
      "label-weight": "500",
      "label-spacing": "6px",
      "helper-size": "var(--s-size-xs)",
    },
    alignment: {
      "title-align": "left",
    },
    sections: {
      "rail-margin": "24px",
      "padding-y": "7rem",
      "padding-y-sm": "3.5rem",
      gap: "28px",
      "padding-y-lg": "10.5rem",
      "padding-y-xl": "14rem",
      "title-align": "left",
      "heading-size": "clamp(1.5rem, 4vw, 2rem)",
      "heading-align": "left",
      "heading-max-width": "36rem",
      "heading-margin-bottom": "12px",
      "description-max-width": "28rem",
      "description-gap": "10px",
      "content-gap": "20px",
      "grid-columns": "3",
      "grid-gap": "20px",
      "alternate-bg": "var(--s-surface)",
      "alternate-bg-mode": "none",
    },
    dividers: {
      style: "solid",
      width: "1px",
      opacity: "1",
      "max-width": "100%",
      "margin-y": "0px",
      thickness: "1px",
      "gradient-start": "transparent",
      "gradient-end": "transparent",
    },
    gridVisuals: {
      "line-color": "var(--s-border-muted)",
      "line-width": "1px",
      "show-dots": true,
      "dot-size": "2px",
      "cell-background": "surface",
    },
    cursor: {
      variant: "sigil",
      size: "24px",
      "dot-size": "4px",
      "stroke-width": "1.5px",
      "tick-size": "6px",
      gap: "3px",
      radius: "0px",
      color: "var(--s-text)",
      "ring-color": "var(--s-primary)",
      "dot-color": "var(--s-primary)",
      glow: "none",
      opacity: "1",
      "blend-mode": "normal",
      "z-index": "9999",
      "hide-native": false,
    },
    scrollbar: {
      width: "6px",
      height: "6px",
      padding: "2px",
      radius: "9999px",
      track: "transparent",
      thumb: "var(--s-border-muted)",
      "thumb-hover": "var(--s-border)",
      "thumb-active": "var(--s-border-strong)",
      corner: "transparent",
      border: "none",
      "firefox-width": "thin",
      gutter: "stable",
      visibility: "auto",
    },
    focus: {
      "ring-width": "2px",
      "ring-color": "var(--s-primary)",
      "ring-offset": "2px",
      "ring-shadow": "0 0 0 2px var(--s-primary)",
      "outline-color": "var(--s-primary)",
    },
    overlays: {
      bg: "rgb(0 0 0 / 0.5)",
      blur: "8px",
      surface: "var(--s-surface-elevated)",
      border: "1px solid var(--s-border-muted)",
      shadow: "var(--s-shadow-xl)",
      radius: "var(--s-radius-lg)",
      padding: "20px",
      "z-index": "50",
    },
    dataViz: {
      "series-1": "var(--s-primary)",
      "series-2": "var(--s-secondary)",
      "series-3": "var(--s-accent)",
      "series-4": "var(--s-info)",
      "series-5": "var(--s-success)",
      positive: "var(--s-success)",
      negative: "var(--s-error)",
      neutral: "var(--s-text-muted)",
      grid: "var(--s-border-muted)",
      axis: "var(--s-border)",
      label: "var(--s-text-secondary)",
      "tooltip-bg": "var(--s-surface-elevated)",
      "tooltip-border": "var(--s-border-muted)",
    },
    media: {
      radius: "var(--s-radius-md)",
      border: "none",
      outline: "1px solid rgb(0 0 0 / 0.08)",
      shadow: "none",
      bg: "var(--s-surface-sunken)",
      "object-fit": "cover",
    },
    controls: {
      height: "38px",
      "height-sm": "30px",
      "height-lg": "46px",
      "hit-area": "44px",
      "icon-size": "16px",
      "handle-size": "20px",
      "track-height": "4px",
      "track-bg": "var(--s-border-muted)",
      "track-fill": "var(--s-primary)",
      "thumb-bg": "var(--s-surface-elevated)",
      "thumb-border": "2px solid var(--s-primary)",
    },
    componentSurfaces: {
      bg: "var(--s-surface)",
      "bg-elevated": "var(--s-surface-elevated)",
      "bg-muted": "var(--s-surface-sunken)",
      border: "var(--s-border)",
      "border-muted": "var(--s-border-muted)",
      "border-strong": "var(--s-border-strong)",
      text: "var(--s-text)",
      "text-muted": "var(--s-text-muted)",
      contrast: "var(--s-primary-contrast)",
      "hover-bg": "var(--s-surface-elevated)",
      "active-bg": "var(--s-surface-sunken)",
      "selected-bg": "var(--s-primary-muted)",
    },
    hero: {
      "min-height": "auto",
      "padding-y": "84px",
      "padding-y-sm": "56px",
      "padding-x": "var(--s-page-margin, 20px)",
      "content-max": "600px",
      "content-align": "center",
      layout: "centered",
      "media-position": "below",
      "media-width": "50%",
      "media-radius": "var(--s-radius-md)",
      "title-size": "clamp(2rem, 5vw, 3.5rem)",
      "title-max-width": "48rem",
      "description-size": "1rem",
      "description-max-width": "28rem",
      "description-gap": "20px",
      "actions-gap": "10px",
      "actions-margin-top": "24px",
      "action-padding-x": "20px",
      "action-padding-y": "10px",
      "badge-gap": "20px",
      "overlay-opacity": "0.5",
      "scroll-indicator": false,
      "gradient-overlay": "none",
    },
    cta: {
      "padding-y": "56px",
      "padding-x": "var(--s-page-margin, 20px)",
      "max-width": "var(--s-content-max, 1200px)",
      layout: "centered",
      border: true,
      "border-radius": "var(--s-card-radius, 0px)",
      bg: "var(--s-surface)",
      "title-size": "clamp(1.25rem, 3vw, 2rem)",
      "description-max-width": "28rem",
      "description-gap": "10px",
      "actions-gap": "10px",
      "actions-margin-top": "24px",
      "action-padding-x": "20px",
      "action-padding-y": "10px",
      "split-gap": "28px",
    },
    footer: {
      "padding-y": "28px",
      "border-top": "1px solid var(--s-border)",
      columns: "4",
      "column-gap": "24px",
      "row-gap": "24px",
      "logo-height": "20px",
      "tagline-max-width": "18rem",
      "link-size": "0.8125rem",
      "link-gap": "6px",
      "group-title-size": "0.8125rem",
      "group-title-weight": "600",
      "social-icon-size": "18px",
      "social-gap": "10px",
      "bottom-bar-padding": "28px 0",
      "bottom-bar-border": "1px solid var(--s-border-muted)",
    },
    banner: {
      height: "auto",
      "padding-y": "6px",
      "padding-x": "16px",
      "font-size": "0.8125rem",
      "font-weight": "500",
      "icon-size": "14px",
      "icon-gap": "10px",
      "border-width": "1px",
      "border-position": "bottom",
      position: "top",
      "dismiss-size": "14px",
      radius: "0px",
    },
    pageRhythm: {
      density: "compact",
      "section-gap": "0px",
      "section-gap-sm": "0px",
      "section-gap-lg": "0px",
      "first-section-offset": "0px",
      "last-section-margin": "0px",
      "alternate-bg": false,
      "alternate-bg-color": "var(--s-surface)",
      "divider-between": true,
      "max-content-width": "var(--s-content-max, 1200px)",
      "vertical-rhythm-unit": "8px",
      "scroll-snap": false,
      "responsive-scale": "1",
      "responsive-breakpoint": "768px",
    },

  },
};
