import type { SigilPreset } from "@sigil-ui/tokens";

export const cruxPreset: SigilPreset = {
  name: "crux",
  metadata: {
    description: "Decisive minimal. Maximum whitespace. The essential kernel, nothing more.",
    mood: "minimal, decisive, essential",
    tags: ["minimal", "monochrome", "sharp", "editorial", "decisive"],
  },
  tokens: {
    colors: {
      background: { light: "oklch(1 0 0)", dark: "oklch(0.07 0 0)" },
      surface: { light: "oklch(0.98 0 0)", dark: "oklch(0.11 0 0)" },
      "surface-elevated": { light: "oklch(1 0 0)", dark: "oklch(0.15 0 0)" },
      "surface-sunken": { light: "oklch(0.96 0 0)", dark: "oklch(0.05 0 0)" },
      primary: "oklch(0.53 0.22 27)",
      "primary-hover": "oklch(0.46 0.24 27)",
      "primary-muted": "oklch(0.53 0.08 27)",
      "primary-contrast": "oklch(1 0 0)",
      secondary: "oklch(0.25 0 0)",
      "secondary-hover": "oklch(0.15 0 0)",
      "secondary-muted": "oklch(0.7 0 0)",
      accent: "oklch(0.53 0.22 27)",
      "accent-hover": "oklch(0.46 0.24 27)",
      "accent-muted": "oklch(0.53 0.08 27)",
      text: { light: "oklch(0.05 0 0)", dark: "oklch(0.96 0 0)" },
      "text-secondary": { light: "oklch(0.3 0 0)", dark: "oklch(0.75 0 0)" },
      "text-muted": { light: "oklch(0.5 0 0)", dark: "oklch(0.55 0 0)" },
      "text-subtle": { light: "oklch(0.65 0 0)", dark: "oklch(0.4 0 0)" },
      "text-disabled": { light: "oklch(0.78 0 0)", dark: "oklch(0.3 0 0)" },
      "text-inverse": { light: "oklch(0.96 0 0)", dark: "oklch(0.05 0 0)" },
      border: { light: "oklch(0.9 0 0)", dark: "oklch(0.2 0 0)" },
      "border-muted": { light: "oklch(0.94 0 0)", dark: "oklch(0.16 0 0)" },
      "border-strong": { light: "oklch(0.75 0 0)", dark: "oklch(0.35 0 0)" },
      "border-interactive": { light: "oklch(0.05 0 0)", dark: "oklch(0.96 0 0)" },
      success: "oklch(0.7 0.18 150)",
      "success-muted": "oklch(0.7 0.06 150)",
      warning: "oklch(0.78 0.14 75)",
      "warning-muted": "oklch(0.78 0.05 75)",
      error: "oklch(0.53 0.22 27)",
      "error-muted": "oklch(0.53 0.07 27)",
      info: "oklch(0.65 0.14 245)",
      "info-muted": "oklch(0.65 0.05 245)",
      "gradient-start": "oklch(0.05 0 0)",
      "gradient-end": "oklch(0.25 0 0)",
      glow: "oklch(0.53 0.22 27 / 0.3)",
    },
    typography: {
      "font-display": "'Inter', system-ui, sans-serif",
      "font-body": "'Inter', system-ui, sans-serif",
      "font-mono": "'Fira Code', ui-monospace, monospace",
      "size-xs": "0.6875rem",
      "size-sm": "0.8125rem",
      "size-base": "0.9375rem",
      "size-lg": "1rem",
      "size-xl": "1.125rem",
      "size-2xl": "1.3125rem",
      "size-3xl": "1.5625rem",
      "size-4xl": "1.875rem",
      "size-5xl": "2.375rem",
      "size-6xl": "3rem",
      "weight-normal": "400",
      "weight-medium": "500",
      "weight-semibold": "600",
      "weight-bold": "700",
      "weight-extrabold": "800",
      "leading-tight": "1.2",
      "leading-normal": "1.5",
      "leading-relaxed": "1.65",
      "leading-loose": "2",
      "tracking-tighter": "-0.05em",
      "tracking-tight": "-0.025em",
      "tracking-normal": "0em",
      "tracking-wide": "0.025em",
      "tracking-wider": "0.06em",
      "heading-weight": "700",
      "heading-tracking": "-0.03em",
      "heading-transform": "uppercase",
      "heading-family": "'Inter', system-ui, sans-serif",
    },
    spacing: {
      scale: [4, 8, 12, 16, 24, 32, 48, 64, 96, 128],
      unit: "px",
      "button-px": "24px",
      "button-py": "12px",
      "button-px-sm": "16px",
      "button-py-sm": "8px",
      "button-px-lg": "36px",
      "button-py-lg": "16px",
      "card-padding": "32px",
      "card-padding-sm": "24px",
      "card-padding-lg": "48px",
      "input-px": "12px",
      "input-py": "10px",
      "badge-px": "10px",
      "badge-py": "2px",
      "section-py": "96px",
      "section-py-lg": "128px",
      "navbar-height": "64px",
      "navbar-px": "32px",
      "footer-py": "64px",
      "modal-padding": "32px",
      "popover-padding": "16px",
      "tooltip-padding": "8px 12px",
      "table-cell-px": "16px",
      "table-cell-py": "12px",
    },
    layout: {
      "content-max": "1080px",
      "content-max-narrow": "640px",
      "content-max-wide": "1440px",
      "page-margin": "32px",
      "page-margin-sm": "16px",
      "page-margin-lg": "64px",
      gutter: "32px",
      "gutter-sm": "16px",
      "gutter-lg": "48px",
      "grid-columns": "12",
      "grid-gap": "32px",
      "bento-gap": "16px",
      "bento-radius": "0px",
      "bento-min-height": "240px",
      "section-gap": "48px",
      "sidebar-width": "240px",
      "sidebar-collapsed": "56px",
      "footer-columns": "3",
      "stack-gap": "16px",
      "stack-gap-sm": "8px",
      "stack-gap-lg": "32px",
      "prose-max": "58ch",
    },
    sigil: {
      "grid-cell": "64px",
      "cross-arm": "0px",
      "cross-stroke": "0px",
      "rail-gap": "32px",
      "card-radius": "0px",
    },
    radius: {
      none: "0px",
      sm: "0px",
      md: "0px",
      lg: "0px",
      xl: "0px",
      "2xl": "0px",
      full: "9999px",
      button: "0px",
      card: "0px",
      input: "0px",
      badge: "9999px",
      modal: "0px",
      popover: "0px",
      tooltip: "0px",
      image: "0px",
      bento: "0px",
    },
    shadows: {
      sm: "0 1px 3px 0 rgb(0 0 0 / 0.08)",
      md: "0 2px 8px -1px rgb(0 0 0 / 0.12)",
      lg: "0 6px 16px -2px rgb(0 0 0 / 0.14)",
      xl: "0 12px 28px -4px rgb(0 0 0 / 0.16)",
      "2xl": "0 24px 48px -8px rgb(0 0 0 / 0.2)",
      glow: "none",
      "glow-sm": "none",
      colored: "none",
      inner: "inset 0 1px 3px 0 rgb(0 0 0 / 0.06)",
      card: "0 2px 8px -1px rgb(0 0 0 / 0.1)",
      button: "none",
      "button-hover": "0 2px 8px -2px rgb(0 0 0 / 0.15)",
      dropdown: "0 6px 20px -2px rgb(0 0 0 / 0.15)",
      modal: "0 24px 64px -12px rgb(0 0 0 / 0.25)",
    },
    motion: {
      duration: { instant: "0ms", fast: "100ms", normal: "200ms", slow: "350ms", slower: "500ms", slowest: "800ms" },
      easing: {
        default: "cubic-bezier(0.16, 1, 0.3, 1)",
        in: "cubic-bezier(0.55, 0, 1, 0.45)",
        out: "cubic-bezier(0, 0.55, 0.45, 1)",
        "in-out": "cubic-bezier(0.45, 0, 0.55, 1)",
        spring: "cubic-bezier(0.22, 1, 0.36, 1)",
        bounce: "cubic-bezier(0.68, -0.55, 0.27, 1.55)",
      },
      "enter-preset": "fadeIn",
      "exit-preset": "fadeOut",
      "hover-scale": "1.0",
      "press-scale": "0.98",
      "hover-lift": "-4px",
      "stagger-interval": "60ms",
      "stagger-interval-fast": "30ms",
    },
    borders: {
      width: { none: "0px", thin: "1px", medium: "1.5px", thick: "2px" },
      style: "solid",
      "card-border": "0px solid",
      "card-border-hover": "0px solid",
      "button-border": "0px solid",
      "input-border": "1px solid",
      "divider-style": "solid",
      "divider-width": "1px",
    },
    buttons: {
      "font-weight": "700",
      "text-transform": "uppercase",
      "letter-spacing": "0.06em",
      "font-family": "inherit",
      "border-width": "0px",
      "hover-effect": "fill",
      "active-scale": "0.98",
      "icon-gap": "8px",
      "min-width": "0px",
    },
    cards: {
      "border-style": "none",
      "border-width": "0px",
      "hover-effect": "lift",
      "hover-border-color": "transparent",
      padding: "32px",
      "header-padding": "32px 32px 0",
      "footer-padding": "0 32px 32px",
      "title-size": "1rem",
      "title-weight": "700",
      "description-size": "0.8125rem",
      background: "transparent",
      shadow: "md",
      outline: false,
      "outline-on-hover-only": false,
      "gap-between": "24px",
      "content-padding-x": "32px",
      "content-padding-y": "24px",
    },
    headings: {
      "h1-size": "1.875rem",
      "h1-weight": "700",
      "h1-tracking": "-0.03em",
      "h1-leading": "1.15",
      "h2-size": "1.5625rem",
      "h2-weight": "700",
      "h2-tracking": "-0.025em",
      "h3-size": "1.3125rem",
      "h3-weight": "600",
      "h4-size": "1.125rem",
      "h4-weight": "600",
      "display-size": "3rem",
      "display-weight": "800",
      "display-tracking": "-0.045em",
      "display-leading": "1.05",
    },
    navigation: {
      "navbar-height": "64px",
      "navbar-backdrop-blur": "0px",
      "navbar-border": "1px solid",
      "navbar-bg-opacity": "1",
      "nav-link-weight": "500",
      "nav-link-size": "0.8125rem",
      "nav-link-hover": "none",
      "breadcrumb-separator": "→",
      "pagination-radius": "0px",
      "sidebar-width": "240px",
      "sidebar-item-radius": "0px",
      "sidebar-item-padding": "8px 12px",
    },
    backgrounds: {
      pattern: "none",
      "pattern-opacity": "0",
      "pattern-scale": "1",
      noise: false,
      "noise-opacity": "0",
      "gradient-angle": "180deg",
      "gradient-type": "none",
      "hero-pattern": "none",
      "section-divider": "line",
    },
    code: {
      "font-family": "'Fira Code', ui-monospace, monospace",
      "font-size": "0.8125rem",
      "line-height": "1.7",
      bg: "var(--s-surface-sunken)",
      border: "none",
      "border-radius": "0px",
      padding: "20px",
      "tab-size": "2",
      "selection-bg": "var(--s-primary-muted)",
      "comment-color": "var(--s-text-muted)",
      "keyword-color": "var(--s-text)",
      "string-color": "var(--s-primary)",
      "number-color": "var(--s-text-secondary)",
      "function-color": "var(--s-text)",
    },
    inputs: {
      height: "44px",
      "height-sm": "36px",
      "height-lg": "52px",
      "border-width": "1px",
      "focus-ring-width": "2px",
      "focus-ring-color": "var(--s-text)",
      "focus-ring-offset": "0px",
      "placeholder-color": "var(--s-text-subtle)",
      "error-border-color": "var(--s-error)",
      "label-size": "0.6875rem",
      "label-weight": "700",
      "label-spacing": "8px",
      "helper-size": "0.75rem",
    },
    alignment: {
      "rail-width": "960px",
      "rail-columns": "12",
      "rail-gutter": "32px",
      "rail-margin": "48px",
      "rail-visible": false,
      "rail-color": "var(--s-border-muted)",
      "content-align": "center",
      "hero-align": "center",
      "section-align": "center",
      "navbar-align": "full",
      "footer-align": "content",
    },
    sections: {
      "padding-y": "96px",
      "padding-y-hero": "160px",
      "padding-x": "48px",
      "max-width": "960px",
      gap: "48px",
      "title-align": "center",
      "divider-above": false,
      "divider-below": false,
      "background-alt": false,
      indent: "0px",
    },
    dividers: {
      style: "none",
      width: "0px",
      color: "var(--s-border)",
      spacing: "0px",
      "show-cross": false,
      "show-label": false,
      "full-bleed": false,
      ornament: "none",
    },
    gridVisuals: {
      "show-lines": false,
      "line-color": "var(--s-border-muted)",
      "line-width": "1px",
      "show-dots": false,
      "dot-size": "2px",
      "cell-background": "none",
      "cell-border": false,
      "cell-radius": "0px",
      "cell-padding": "24px",
      "hover-effect": "lift",
    },
  },
};
