import type { SigilPreset } from "@sigil-ui/tokens";

export const defaultPreset: SigilPreset = {
  name: "default",
  metadata: {
    description:
      "Pure black and white. No accent color, no distraction. The blank canvas preset.",
    mood: "neutral, clean, monochrome",
    tags: ["default", "neutral", "monochrome", "black", "white"],
  },
  tokens: {
    colors: {
      background: { light: "#ffffff", dark: "#0a0a0f" },
      surface: { light: "#f8f8fa", dark: "#141419" },
      "surface-elevated": { light: "#ffffff", dark: "#1a1a22" },
      "surface-sunken": { light: "#f0f0f4", dark: "#06060a" },
      primary: { light: "#18181b", dark: "#e4e4e7" },
      "primary-hover": { light: "#27272a", dark: "#d4d4d8" },
      "primary-muted": { light: "rgba(24, 24, 27, 0.1)", dark: "rgba(228, 228, 231, 0.1)" },
      "primary-contrast": { light: "#ffffff", dark: "#0a0a0f" },
      secondary: "#52525b",
      "secondary-hover": "#3f3f46",
      "secondary-muted": "rgba(82, 82, 91, 0.1)",
      accent: "#18181b",
      "accent-hover": "#27272a",
      "accent-muted": "rgba(24, 24, 27, 0.1)",
      text: { light: "#0a0a0f", dark: "#fafafa" },
      "text-secondary": { light: "#4a4a55", dark: "#a0a0aa" },
      "text-muted": { light: "#6a6a78", dark: "#8888a0" },
      "text-subtle": { light: "#8a8a95", dark: "#646470" },
      "text-disabled": { light: "#c8c8d0", dark: "#3a3a44" },
      "text-inverse": { light: "#fafafa", dark: "#0a0a0f" },
      border: { light: "#8a8a98", dark: "rgba(255, 255, 255, 0.12)" },
      "border-muted": { light: "#d0d0d8", dark: "rgba(255, 255, 255, 0.06)" },
      "border-strong": { light: "#808090", dark: "rgba(255, 255, 255, 0.2)" },
      "border-interactive": { light: "#18181b", dark: "#e4e4e7" },
      success: "#059669",
      "success-muted": "#ecfdf5",
      warning: "#d97706",
      "warning-muted": "#fffbeb",
      error: "#dc2626",
      "error-muted": "#fef2f2",
      info: "#2563eb",
      "info-muted": "#eff6ff",
      "gradient-start": "#18181b",
      "gradient-end": "#52525b",
      glow: "rgba(24, 24, 27, 0.2)",
    },
    typography: {
      "font-display": "'ABC Monument Grotesk', 'PP Neue Montreal', system-ui, sans-serif",
      "font-body": "'ABC Monument Grotesk', 'PP Neue Montreal', system-ui, sans-serif",
      "font-mono": "'PP Fraktion Mono', 'JetBrains Mono', ui-monospace, monospace",
      "size-xs": "0.75rem",
      "size-sm": "0.8125rem",
      "size-base": "0.9375rem",
      "size-lg": "1.0625rem",
      "size-xl": "1.1875rem",
      "size-2xl": "1.4375rem",
      "size-3xl": "1.75rem",
      "size-4xl": "2.125rem",
      "size-5xl": "2.75rem",
      "size-6xl": "3.5rem",
      "weight-normal": "400",
      "weight-medium": "500",
      "weight-semibold": "600",
      "weight-bold": "700",
      "weight-extrabold": "800",
      "leading-tight": "1.25",
      "leading-normal": "1.5",
      "leading-relaxed": "1.625",
      "leading-loose": "2",
      "tracking-tighter": "-0.04em",
      "tracking-tight": "-0.02em",
      "tracking-normal": "0em",
      "tracking-wide": "0.02em",
      "tracking-wider": "0.04em",
      "heading-weight": "700",
      "heading-tracking": "-0.025em",
      "heading-transform": "none",
      "heading-family": "'ABC Monument Grotesk', 'PP Neue Montreal', system-ui, sans-serif",
    },
    spacing: {
      scale: [4, 8, 12, 16, 20, 24, 32, 48, 64, 80],
      unit: "px",
      "button-px": "20px",
      "button-py": "10px",
      "button-px-sm": "14px",
      "button-py-sm": "6px",
      "button-px-lg": "28px",
      "button-py-lg": "12px",
      "card-padding": "20px",
      "card-padding-sm": "14px",
      "card-padding-lg": "28px",
      "input-px": "10px",
      "input-py": "7px",
      "badge-px": "7px",
      "badge-py": "2px",
      "section-py": "64px",
      "section-py-lg": "96px",
      "navbar-height": "56px",
      "navbar-px": "20px",
      "footer-py": "48px",
      "modal-padding": "24px",
      "popover-padding": "12px",
      "tooltip-padding": "4px 8px",
      "table-cell-px": "12px",
      "table-cell-py": "8px",
    },
    layout: {
      "content-max": "1200px",
      "content-max-narrow": "680px",
      "content-max-wide": "1400px",
      "page-margin": "20px",
      "page-margin-sm": "12px",
      "page-margin-lg": "40px",
      gutter: "20px",
      "gutter-sm": "12px",
      "gutter-lg": "32px",
      "grid-columns": "12",
      "grid-gap": "20px",
      "bento-gap": "14px",
      "bento-radius": "0px",
      "bento-min-height": "180px",
      "section-gap": "24px",
      "sidebar-width": "260px",
      "sidebar-collapsed": "48px",
      "footer-columns": "4",
      "stack-gap": "12px",
      "stack-gap-sm": "6px",
      "stack-gap-lg": "20px",
      "prose-max": "60ch",
    },
    sigil: {
      "grid-cell": "48px",
      "cross-arm": "10px",
      "cross-stroke": "1.5px",
      "rail-gap": "24px",
      "card-radius": "0px",
      "gutter-pattern": "grid",
      "margin-pattern": "dots",
    },
    radius: {
      none: "0px",
      sm: "0px",
      md: "2px",
      lg: "2px",
      xl: "16px",
      "2xl": "24px",
      full: "9999px",
      button: "0px",
      card: "0px",
      input: "0px",
      badge: "9999px",
      modal: "2px",
      popover: "2px",
      tooltip: "2px",
      image: "0px",
      bento: "0px",
    },
    shadows: {
      sm: "0 1px 2px 0 rgb(0 0 0 / 0.05)",
      md: "0 0 0 1px rgb(0 0 0 / 0.06), 0 1px 2px -1px rgb(0 0 0 / 0.06), 0 2px 4px 0 rgb(0 0 0 / 0.04)",
      lg: "0 0 0 1px rgb(0 0 0 / 0.04), 0 2px 4px -2px rgb(0 0 0 / 0.06), 0 4px 8px -2px rgb(0 0 0 / 0.08)",
      xl: "0 0 0 1px rgb(0 0 0 / 0.03), 0 4px 6px -4px rgb(0 0 0 / 0.06), 0 10px 15px -3px rgb(0 0 0 / 0.1), 0 20px 25px -5px rgb(0 0 0 / 0.06)",
      glow: "0 0 20px var(--s-primary)",
      "glow-sm": "0 0 10px var(--s-primary)",
      colored: "0 4px 14px -3px var(--s-primary)",
      inner: "inset 0 2px 4px 0 rgb(0 0 0 / 0.06)",
      card: "0 0 0 1px var(--s-border)",
      button: "none",
      "button-hover": "0 1px 3px rgb(0 0 0 / 0.12)",
      dropdown: "0 4px 12px rgb(0 0 0 / 0.12), 0 0 0 1px rgb(0 0 0 / 0.04)",
      modal: "0 16px 48px -8px rgb(0 0 0 / 0.2)",
    },
    motion: {
      duration: { instant: "0ms", fast: "150ms", normal: "250ms", slow: "400ms", slower: "600ms" },
      easing: {
        default: "cubic-bezier(0.16, 1, 0.3, 1)",
        in: "cubic-bezier(0.55, 0, 1, 0.45)",
        out: "cubic-bezier(0, 0.55, 0.45, 1)",
        "in-out": "cubic-bezier(0.45, 0, 0.55, 1)",
        spring: "cubic-bezier(0.34, 1.56, 0.64, 1)",
      },
      "hover-scale": "1.02",
      "press-scale": "0.97",
      "hover-lift": "-2px",
      "stagger-interval": "50ms",
      "stagger-interval-fast": "25ms",
    },
    borders: {
      width: { none: "0px", thin: "1px", medium: "1.5px", thick: "2px" },
      style: "solid",
      "card-border": "1px solid",
      "card-border-hover": "1px solid",
      "button-border": "1px solid",
      "input-border": "1px solid",
      "divider-style": "solid",
      "divider-width": "1px",
    },
    buttons: {
      "font-weight": "600",
      "text-transform": "none",
      "letter-spacing": "0em",
      "font-family": "'ABC Monument Grotesk', 'PP Neue Montreal', system-ui, sans-serif",
      "border-width": "1px",
      "hover-effect": "darken",
      "active-scale": "0.97",
      "icon-gap": "8px",
      "min-width": "0px",
    },
    cards: {
      "border-style": "solid",
      "border-width": "1px",
      "hover-effect": "lift",
      "hover-border-color": "var(--s-border-strong)",
      padding: "20px",
      "header-padding": "20px 20px 0",
      "footer-padding": "0 20px 20px",
      "title-size": "1rem",
      "title-weight": "600",
      "description-size": "0.8125rem",
      outline: true,
      shadow: "none",
    },
    headings: {
      "h1-size": "2.75rem",
      "h1-weight": "700",
      "h1-tracking": "-0.025em",
      "h1-leading": "1.1",
      "h2-size": "2rem",
      "h2-weight": "700",
      "h2-tracking": "-0.02em",
      "h3-size": "1.5rem",
      "h3-weight": "600",
      "h4-size": "1.125rem",
      "h4-weight": "600",
      "display-size": "3.5rem",
      "display-weight": "800",
      "display-tracking": "-0.03em",
      "display-leading": "1.05",
    },
    navigation: {
      "navbar-height": "56px",
      "navbar-backdrop-blur": "12px",
      "navbar-border": "1px solid",
      "navbar-bg-opacity": "0.85",
      "nav-link-weight": "500",
      "nav-link-size": "0.8125rem",
      "nav-link-hover": "color",
      "breadcrumb-separator": " / ",
      "pagination-radius": "0px",
      "sidebar-width": "260px",
      "sidebar-item-radius": "2px",
      "sidebar-item-padding": "7px 10px",
    },
    backgrounds: {
      pattern: "grid",
      "pattern-opacity": "0.03",
      "pattern-scale": "1",
      noise: true,
      "noise-opacity": "0.02",
      "gradient-angle": "0deg",
      "gradient-type": "none",
      "hero-pattern": "grid",
      "section-divider": "line",
    },
    code: {
      "font-family": "'PP Fraktion Mono', 'JetBrains Mono', ui-monospace, monospace",
      "font-size": "0.8125rem",
      "line-height": "1.6",
      bg: "var(--s-surface-sunken)",
      border: "1px solid var(--s-border)",
      "border-radius": "2px",
      padding: "16px",
      "tab-size": "2",
      "selection-bg": "rgba(24, 24, 27, 0.15)",
      "comment-color": "var(--s-text-muted)",
      "keyword-color": "#18181b",
      "string-color": "#10b981",
      "number-color": "#f59e0b",
      "function-color": "#3b82f6",
    },
    inputs: {
      height: "40px",
      "height-sm": "32px",
      "height-lg": "48px",
      "border-width": "1px",
      "focus-ring-width": "2px",
      "focus-ring-color": "#18181b",
      "focus-ring-offset": "2px",
      "placeholder-color": "var(--s-text-muted)",
      "error-border-color": "#dc2626",
      "label-size": "0.8125rem",
      "label-weight": "500",
      "label-spacing": "6px",
      "helper-size": "0.75rem",
    },
  },
};
