import type { SigilPreset } from "@sigil-ui/tokens";

export const defaultPreset: SigilPreset = {
  name: "default",
  metadata: {
    description:
      "A polished neutral zinc theme. Modern radii, balanced contrast, ready for production.",
    mood: "clean, modern, professional",
    tags: ["default", "neutral", "zinc", "modern"],
  },
  tokens: {
    colors: {
      background: { light: "#ffffff", dark: "#09090b" },
      surface: { light: "#f4f4f5", dark: "#18181b" },
      "surface-elevated": { light: "#ffffff", dark: "#27272a" },
      "surface-sunken": { light: "#f4f4f5", dark: "#09090b" },
      primary: "#18181b",
      "primary-hover": "#27272a",
      "primary-muted": "rgba(24, 24, 27, 0.08)",
      "primary-contrast": "#ffffff",
      secondary: "#f4f4f5",
      "secondary-hover": "#e4e4e7",
      "secondary-muted": "rgba(244, 244, 245, 0.6)",
      accent: "#f4f4f5",
      "accent-hover": "#e4e4e7",
      "accent-muted": "rgba(244, 244, 245, 0.6)",
      text: { light: "#09090b", dark: "#fafafa" },
      "text-secondary": { light: "#3f3f46", dark: "#a1a1aa" },
      "text-muted": { light: "#71717a", dark: "#a1a1aa" },
      "text-subtle": { light: "#a1a1aa", dark: "#71717a" },
      "text-disabled": { light: "#d4d4d8", dark: "#3f3f46" },
      "text-inverse": { light: "#fafafa", dark: "#09090b" },
      border: { light: "#e4e4e7", dark: "#27272a" },
      "border-muted": { light: "#f4f4f5", dark: "#18181b" },
      "border-strong": { light: "#d4d4d8", dark: "#3f3f46" },
      "border-interactive": { light: "#18181b", dark: "#fafafa" },
      success: "#22c55e",
      "success-muted": "#f0fdf4",
      warning: "#eab308",
      "warning-muted": "#fefce8",
      error: "#ef4444",
      "error-muted": "#fef2f2",
      info: "#3b82f6",
      "info-muted": "#eff6ff",
      "gradient-start": "#18181b",
      "gradient-end": "#71717a",
      glow: "rgba(24, 24, 27, 0.15)",
    },
    typography: {
      "font-display": "'PP Mori', system-ui, sans-serif",
      "font-body": "'PP Mori', system-ui, sans-serif",
      "font-mono": "'PP Fraktion Mono', ui-monospace, monospace",
      "size-xs": "0.75rem",
      "size-sm": "0.875rem",
      "size-base": "0.875rem",
      "size-lg": "1rem",
      "size-xl": "1.125rem",
      "size-2xl": "1.5rem",
      "size-3xl": "1.875rem",
      "size-4xl": "2.25rem",
      "size-5xl": "3rem",
      "size-6xl": "3.75rem",
      "weight-normal": "400",
      "weight-medium": "500",
      "weight-semibold": "600",
      "weight-bold": "700",
      "weight-extrabold": "800",
      "leading-tight": "1.25",
      "leading-normal": "1.5",
      "leading-relaxed": "1.625",
      "leading-loose": "2",
      "tracking-tighter": "-0.04em",
      "tracking-tight": "-0.025em",
      "tracking-normal": "0em",
      "tracking-wide": "0.025em",
      "tracking-wider": "0.05em",
      "heading-weight": "600",
      "heading-tracking": "-0.025em",
      "heading-transform": "none",
      "heading-family": "'PP Mori', system-ui, sans-serif",
    },
    spacing: {
      scale: [4, 8, 12, 16, 20, 24, 32, 48, 64, 80],
      unit: "px",
      "button-px": "16px",
      "button-py": "8px",
      "button-px-sm": "12px",
      "button-py-sm": "6px",
      "button-px-lg": "24px",
      "button-py-lg": "10px",
      "card-padding": "24px",
      "card-padding-sm": "16px",
      "card-padding-lg": "32px",
      "input-px": "12px",
      "input-py": "8px",
      "badge-px": "10px",
      "badge-py": "2px",
      "section-py": "64px",
      "section-py-lg": "96px",
      "navbar-height": "56px",
      "navbar-px": "20px",
      "footer-py": "48px",
      "modal-padding": "24px",
      "popover-padding": "16px",
      "tooltip-padding": "6px 12px",
      "table-cell-px": "16px",
      "table-cell-py": "12px",
    },
    layout: {
      "content-max": "1200px",
      "content-max-narrow": "680px",
      "content-max-wide": "1400px",
      "page-margin": "24px",
      "page-margin-sm": "16px",
      "page-margin-lg": "40px",
      gutter: "24px",
      "gutter-sm": "16px",
      "gutter-lg": "32px",
      "grid-columns": "12",
      "grid-gap": "24px",
      "bento-gap": "16px",
      "bento-radius": "0px",
      "bento-min-height": "180px",
      "section-gap": "24px",
      "sidebar-width": "256px",
      "sidebar-collapsed": "48px",
      "footer-columns": "4",
      "stack-gap": "16px",
      "stack-gap-sm": "8px",
      "stack-gap-lg": "24px",
      "prose-max": "65ch",
    },
    sigil: {
      "grid-cell": "16px",
      "cross-arm": "10px",
      "cross-stroke": "1.5px",
      "rail-gap": "48px",
      "card-radius": "0px",
      "gutter-pattern": "grid",
      "margin-pattern": "horizontal",
    },
    radius: {
      none: "0px",
      sm: "0px",
      md: "0px",
      lg: "0px",
      xl: "0px",
      "2xl": "0px",
      full: "0px",
      button: "0px",
      card: "0px",
      input: "0px",
      badge: "0px",
      modal: "0px",
      popover: "0px",
      tooltip: "0px",
      image: "0px",
      bento: "0px",
    },
    shadows: {
      sm: "0 1px 2px 0 rgb(0 0 0 / 0.05)",
      md: "0 1px 3px 0 rgb(0 0 0 / 0.1), 0 1px 2px -1px rgb(0 0 0 / 0.1)",
      lg: "0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)",
      xl: "0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)",
      glow: "0 0 20px var(--s-primary)",
      "glow-sm": "0 0 10px var(--s-primary)",
      colored: "0 4px 14px -3px var(--s-primary)",
      inner: "inset 0 2px 4px 0 rgb(0 0 0 / 0.06)",
      card: "0 1px 3px 0 rgb(0 0 0 / 0.06), 0 1px 2px -1px rgb(0 0 0 / 0.06)",
      button: "0 1px 2px 0 rgb(0 0 0 / 0.05)",
      "button-hover": "0 1px 3px 0 rgb(0 0 0 / 0.1), 0 1px 2px -1px rgb(0 0 0 / 0.1)",
      dropdown: "0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)",
      modal: "0 20px 25px -5px rgb(0 0 0 / 0.1), 0 8px 10px -6px rgb(0 0 0 / 0.1)",
    },
    motion: {
      duration: { instant: "0ms", fast: "150ms", normal: "200ms", slow: "300ms", slower: "500ms" },
      easing: {
        default: "cubic-bezier(0.16, 1, 0.3, 1)",
        in: "cubic-bezier(0.55, 0, 1, 0.45)",
        out: "cubic-bezier(0, 0.55, 0.45, 1)",
        "in-out": "cubic-bezier(0.45, 0, 0.55, 1)",
        spring: "cubic-bezier(0.34, 1.56, 0.64, 1)",
      },
      "hover-scale": "1.02",
      "press-scale": "0.98",
      "hover-lift": "-1px",
      "stagger-interval": "50ms",
      "stagger-interval-fast": "30ms",
    },
    borders: {
      width: { none: "0px", thin: "1px", medium: "1.5px", thick: "2px" },
      style: "solid",
      "card-border": "1px solid",
      "card-border-hover": "1px solid",
      "button-border": "1px solid",
      "input-border": "1px solid",
      "divider-style": "solid",
      "divider-width": "1px",
    },
    buttons: {
      "font-weight": "500",
      "text-transform": "none",
      "letter-spacing": "0em",
      "font-family": "inherit",
      "border-width": "1px",
      "hover-effect": "darken",
      "active-scale": "0.98",
      "icon-gap": "8px",
      "min-width": "0px",
    },
    cards: {
      "border-style": "solid",
      "border-width": "1px",
      "hover-effect": "lift",
      "hover-border-color": "var(--s-border-strong)",
      padding: "24px",
      "header-padding": "24px 24px 0",
      "footer-padding": "0 24px 24px",
      "title-size": "1rem",
      "title-weight": "600",
      "description-size": "0.875rem",
      outline: true,
      shadow: "sm",
    },
    headings: {
      "h1-size": "2.25rem",
      "h1-weight": "700",
      "h1-tracking": "-0.025em",
      "h1-leading": "1.1",
      "h2-size": "1.875rem",
      "h2-weight": "600",
      "h2-tracking": "-0.02em",
      "h3-size": "1.5rem",
      "h3-weight": "600",
      "h4-size": "1.25rem",
      "h4-weight": "600",
      "display-size": "3.75rem",
      "display-weight": "800",
      "display-tracking": "-0.03em",
      "display-leading": "1.05",
    },
    navigation: {
      "navbar-height": "56px",
      "navbar-backdrop-blur": "12px",
      "navbar-border": "1px solid",
      "navbar-bg-opacity": "0.8",
      "nav-link-weight": "500",
      "nav-link-size": "0.875rem",
      "nav-link-hover": "color",
      "breadcrumb-separator": " / ",
      "pagination-radius": "0px",
      "sidebar-width": "256px",
      "sidebar-item-radius": "0px",
      "sidebar-item-padding": "8px 12px",
    },
    backgrounds: {
      pattern: "none",
      "pattern-opacity": "0.03",
      "pattern-scale": "1",
      noise: false,
      "noise-opacity": "0.02",
      "gradient-angle": "0deg",
      "gradient-type": "none",
      "hero-pattern": "none",
      "section-divider": "line",
    },
    code: {
      "font-family": "'PP Fraktion Mono', ui-monospace, monospace",
      "font-size": "0.8125rem",
      "line-height": "1.6",
      bg: "var(--s-surface)",
      border: "1px solid var(--s-border)",
      "border-radius": "0px",
      padding: "16px",
      "tab-size": "2",
      "selection-bg": "rgba(59, 130, 246, 0.2)",
      "comment-color": "var(--s-text-muted)",
      "keyword-color": "#a855f7",
      "string-color": "#22c55e",
      "number-color": "#eab308",
      "function-color": "#3b82f6",
    },
    inputs: {
      height: "36px",
      "height-sm": "32px",
      "height-lg": "44px",
      "border-width": "1px",
      "focus-ring-width": "2px",
      "focus-ring-color": "var(--s-primary)",
      "focus-ring-offset": "1px",
      "placeholder-color": "var(--s-text-muted)",
      "error-border-color": "var(--s-error)",
      "label-size": "0.875rem",
      "label-weight": "500",
      "label-spacing": "6px",
      "helper-size": "0.75rem",
    },
  },
};
