import type { SigilPreset } from "@sigil-ui/tokens";

/**
 * Default preset — the authoritative neutral zinc theme.
 *
 * Design intent: sharp (0px radius), structural, engineering-precision feel.
 * Uses { light, dark } for primary/contrast colors because zinc neutrals
 * must flip between near-black and near-white across modes. Other presets
 * use single OKLCH values with moderate lightness that work in both modes.
 *
 * global.css must mirror these values so there's no flash on initial load.
 */
export const defaultPreset: SigilPreset = {
  name: "default",
  metadata: {
    description:
      "A polished neutral zinc theme. Sharp radii, balanced contrast, ready for production.",
    mood: "clean, modern, professional",
    tags: ["default", "neutral", "zinc", "modern"],
  },
  tokens: {
    colors: {
      background: { light: "#ffffff", dark: "#0a0a0f" },
      surface: { light: "#f8f8fa", dark: "#141419" },
      "surface-elevated": { light: "#ffffff", dark: "#1a1a22" },
      "surface-sunken": { light: "#f0f0f4", dark: "#06060a" },

      primary: { light: "#18181b", dark: "#e4e4e7" },
      "primary-hover": { light: "#27272a", dark: "#d4d4d8" },
      "primary-muted": { light: "rgba(24, 24, 27, 0.1)", dark: "rgba(228, 228, 231, 0.1)" },
      "primary-contrast": { light: "#ffffff", dark: "#0a0a0f" },

      secondary: { light: "#f4f4f5", dark: "#27272a" },
      "secondary-hover": { light: "#e4e4e7", dark: "#3f3f46" },
      "secondary-muted": { light: "rgba(244, 244, 245, 0.6)", dark: "rgba(39, 39, 42, 0.6)" },

      accent: { light: "#f4f4f5", dark: "#27272a" },
      "accent-hover": { light: "#e4e4e7", dark: "#3f3f46" },
      "accent-muted": { light: "rgba(244, 244, 245, 0.6)", dark: "rgba(39, 39, 42, 0.6)" },

      text: { light: "#0a0a0f", dark: "#fafafa" },
      "text-secondary": { light: "#4a4a55", dark: "#a0a0aa" },
      "text-muted": { light: "#8a8a95", dark: "#8888a0" },
      "text-subtle": { light: "#a8a8b3", dark: "#646470" },
      "text-disabled": { light: "#c8c8d0", dark: "#3a3a44" },
      "text-inverse": { light: "#fafafa", dark: "#0a0a0f" },

      border: { light: "#8a8a98", dark: "#2c2c3c" },
      "border-muted": { light: "#d0d0d8", dark: "#1f1f2d" },
      "border-strong": { light: "#808090", dark: "#3c3c50" },
      "border-interactive": { light: "#18181b", dark: "#e4e4e7" },

      success: "#059669",
      "success-muted": { light: "#ecfdf5", dark: "#052e16" },
      warning: "#d97706",
      "warning-muted": { light: "#fffbeb", dark: "#451a03" },
      error: "#dc2626",
      "error-muted": { light: "#fef2f2", dark: "#450a0a" },
      info: "#2563eb",
      "info-muted": { light: "#eff6ff", dark: "#172554" },

      "gradient-start": "#18181b",
      "gradient-end": "#71717a",
      glow: "rgba(24, 24, 27, 0.15)",
      highlight: { light: "#fef9c3", dark: "rgba(250, 204, 21, 0.15)" },
    },
    typography: {
      "font-display": '"PP Mori", system-ui, sans-serif',
      "font-body": '"PP Telegraf", "PP Mori", system-ui, sans-serif',
      "font-mono": '"PP Fraktion Mono", "JetBrains Mono", ui-monospace, monospace',
      "size-xs": "0.75rem",
      "size-sm": "0.875rem",
      "size-base": "0.875rem",
      "size-lg": "1rem",
      "size-xl": "1.125rem",
      "size-2xl": "1.5rem",
      "size-3xl": "1.875rem",
      "size-4xl": "2.25rem",
      "size-5xl": "3rem",
      "size-6xl": "3.75rem",
      "weight-normal": "400",
      "weight-medium": "500",
      "weight-semibold": "600",
      "weight-bold": "700",
      "weight-extrabold": "800",
      "leading-tight": "1.25",
      "leading-normal": "1.5",
      "leading-relaxed": "1.625",
      "leading-loose": "2",
      "tracking-tighter": "-0.04em",
      "tracking-tight": "-0.025em",
      "tracking-normal": "0em",
      "tracking-wide": "0.025em",
      "tracking-wider": "0.05em",
      "heading-weight": "600",
      "heading-tracking": "-0.025em",
      "heading-transform": "none",
      "heading-family": '"PP Mori", system-ui, sans-serif',
    },
    spacing: {
      scale: [4, 8, 12, 16, 20, 24, 32, 48, 64, 80],
      unit: "px",
      "button-px": "16px",
      "button-py": "8px",
      "button-px-sm": "12px",
      "button-py-sm": "6px",
      "button-px-lg": "24px",
      "button-py-lg": "10px",
      "card-padding": "24px",
      "card-padding-sm": "16px",
      "card-padding-lg": "32px",
      "input-px": "12px",
      "input-py": "8px",
      "badge-px": "10px",
      "badge-py": "2px",
      "section-py": "64px",
      "section-py-lg": "96px",
      "navbar-height": "56px",
      "navbar-px": "20px",
      "footer-py": "48px",
      "modal-padding": "24px",
      "popover-padding": "16px",
      "tooltip-padding": "6px 12px",
      "table-cell-px": "16px",
      "table-cell-py": "12px",
    },
    layout: {
      "content-max": "1200px",
      "content-max-narrow": "680px",
      "content-max-wide": "1400px",
      "page-margin": "24px",
      "page-margin-sm": "16px",
      "page-margin-lg": "40px",
      gutter: "24px",
      "gutter-sm": "16px",
      "gutter-lg": "32px",
      "grid-columns": "12",
      "grid-gap": "24px",
      "bento-gap": "16px",
      "bento-radius": "0px",
      "bento-min-height": "180px",
      "section-gap": "24px",
      "sidebar-width": "256px",
      "sidebar-collapsed": "48px",
      "footer-columns": "4",
      "stack-gap": "16px",
      "stack-gap-sm": "8px",
      "stack-gap-lg": "24px",
      "prose-max": "65ch",
    },
    sigil: {
      "grid-cell": "48px",
      "cross-arm": "10px",
      "cross-stroke": "1.5px",
      "rail-gap": "24px",
      "card-radius": "0px",
      "gutter-pattern": "horizontal-thin",
      "margin-pattern": "horizontal",
    },
    radius: {
      none: "0px",
      sm: "0px",
      md: "0px",
      lg: "0px",
      xl: "0px",
      "2xl": "0px",
      full: "0px",
      button: "0px",
      card: "0px",
      input: "0px",
      badge: "0px",
      modal: "0px",
      popover: "0px",
      tooltip: "0px",
      image: "0px",
      bento: "0px",
    },
    shadows: {
      sm: "0 1px 2px 0 rgb(0 0 0 / 0.05)",
      md: "0 1px 3px 0 rgb(0 0 0 / 0.1), 0 1px 2px -1px rgb(0 0 0 / 0.1)",
      lg: "0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)",
      xl: "0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)",
      glow: "0 0 20px var(--s-primary)",
      "glow-sm": "0 0 10px var(--s-primary)",
      colored: "0 4px 14px -3px var(--s-primary)",
      inner: "inset 0 2px 4px 0 rgb(0 0 0 / 0.06)",
      card: "0 1px 3px 0 rgb(0 0 0 / 0.06), 0 1px 2px -1px rgb(0 0 0 / 0.06)",
      button: "0 1px 2px 0 rgb(0 0 0 / 0.05)",
      "button-hover": "0 1px 3px 0 rgb(0 0 0 / 0.1), 0 1px 2px -1px rgb(0 0 0 / 0.1)",
      dropdown: "0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)",
      modal: "0 20px 25px -5px rgb(0 0 0 / 0.1), 0 8px 10px -6px rgb(0 0 0 / 0.1)",
    },
    motion: {
      duration: { instant: "0ms", fast: "150ms", normal: "200ms", slow: "300ms", slower: "500ms" },
      easing: {
        default: "cubic-bezier(0.16, 1, 0.3, 1)",
        in: "cubic-bezier(0.55, 0, 1, 0.45)",
        out: "cubic-bezier(0, 0.55, 0.45, 1)",
        "in-out": "cubic-bezier(0.45, 0, 0.55, 1)",
        spring: "cubic-bezier(0.34, 1.56, 0.64, 1)",
      },
      "hover-scale": "1.02",
      "press-scale": "0.98",
      "hover-lift": "-1px",
      "stagger-interval": "50ms",
      "stagger-interval-fast": "30ms",
    },
    borders: {
      width: { none: "0px", thin: "1px", medium: "1.5px", thick: "2px" },
      style: "solid",
      "card-border": "1px solid",
      "card-border-hover": "1px solid",
      "button-border": "1px solid",
      "input-border": "1px solid",
      "divider-style": "solid",
      "divider-width": "1px",
    },
    buttons: {
      "font-weight": "500",
      "text-transform": "none",
      "letter-spacing": "0em",
      "font-family": "inherit",
      "border-width": "1px",
      "hover-effect": "darken",
      "active-scale": "0.98",
      "icon-gap": "8px",
      "min-width": "0px",
    },
    cards: {
      "border-style": "solid",
      "border-width": "1px",
      "hover-effect": "lift",
      "hover-border-color": "var(--s-border-strong)",
      padding: "24px",
      "header-padding": "24px 24px 0",
      "footer-padding": "0 24px 24px",
      "title-size": "1rem",
      "title-weight": "600",
      "description-size": "0.875rem",
      outline: true,
      shadow: "sm",
    },
    headings: {
      "h1-size": "2.25rem",
      "h1-weight": "700",
      "h1-tracking": "-0.025em",
      "h1-leading": "1.1",
      "h2-size": "1.875rem",
      "h2-weight": "600",
      "h2-tracking": "-0.02em",
      "h3-size": "1.5rem",
      "h3-weight": "600",
      "h4-size": "1.25rem",
      "h4-weight": "600",
      "display-size": "3.75rem",
      "display-weight": "800",
      "display-tracking": "-0.03em",
      "display-leading": "1.05",
    },
    navigation: {
      "navbar-height": "56px",
      "navbar-backdrop-blur": "12px",
      "navbar-border": "1px solid",
      "navbar-bg-opacity": "0.8",
      "nav-link-weight": "500",
      "nav-link-size": "0.875rem",
      "nav-link-hover": "color",
      "breadcrumb-separator": " / ",
      "pagination-radius": "0px",
      "sidebar-width": "256px",
      "sidebar-item-radius": "0px",
      "sidebar-item-padding": "8px 12px",
    },
    backgrounds: {
      pattern: "none",
      "pattern-opacity": "0.03",
      "pattern-scale": "1",
      noise: false,
      "noise-opacity": "0.02",
      "gradient-angle": "0deg",
      "gradient-type": "none",
      "hero-pattern": "none",
      "section-divider": "line",
    },
    code: {
      "font-family": '"PP Fraktion Mono", "JetBrains Mono", ui-monospace, monospace',
      "font-size": "0.8125rem",
      "line-height": "1.6",
      bg: "var(--s-surface)",
      border: "1px solid var(--s-border)",
      "border-radius": "0px",
      padding: "16px",
      "tab-size": "2",
      "selection-bg": "rgba(59, 130, 246, 0.2)",
      "comment-color": "var(--s-text-muted)",
      "keyword-color": "#a855f7",
      "string-color": "#22c55e",
      "number-color": "#eab308",
      "function-color": "#3b82f6",
    },
    inputs: {
      height: "36px",
      "height-sm": "32px",
      "height-lg": "44px",
      "border-width": "1px",
      "focus-ring-width": "2px",
      "focus-ring-color": "var(--s-primary)",
      "focus-ring-offset": "1px",
      "placeholder-color": "var(--s-text-muted)",
      "error-border-color": "var(--s-error)",
      "label-size": "0.875rem",
      "label-weight": "500",
      "label-spacing": "6px",
      "helper-size": "0.75rem",
    },
    alignment: {
      "rail-width": "1200px",
      "rail-columns": "12",
      "rail-gutter": "20px",
      "rail-margin": "24px",
      "rail-visible": false,
      "rail-color": "var(--s-border-muted)",
      "content-align": "center",
      "hero-align": "center",
      "section-align": "center",
      "navbar-align": "full",
      "footer-align": "content",
      "title-align": "left",
    },
    sections: {
      "padding-y": "64px",
      "padding-y-hero": "96px",
      "padding-x": "24px",
      "max-width": "1200px",
      gap: "24px",
      "title-align": "left",
      "divider-above": false,
      "divider-below": true,
      "background-alt": false,
      indent: "0px",
    },
    dividers: {
      style: "solid",
      width: "1px",
      color: "var(--s-border-muted)",
      spacing: "0px",
      "show-cross": false,
      "show-label": false,
      "full-bleed": false,
      ornament: "none",
    },
    gridVisuals: {
      "show-lines": false,
      "line-color": "var(--s-border-muted)",
      "line-width": "1px",
      "show-dots": false,
      "dot-size": "2px",
      "cell-background": "none",
      "cell-border": false,
      "cell-radius": "0px",
      "cell-padding": "16px",
      "hover-effect": "lift",
    },
    cursor: {
      variant: "sigil",
      size: "24px",
      "dot-size": "4px",
      "stroke-width": "1.5px",
      "tick-size": "6px",
      gap: "3px",
      radius: "0px",
      color: "var(--s-text)",
      "ring-color": "var(--s-primary)",
      "dot-color": "var(--s-primary)",
      glow: "none",
      opacity: "1",
      "blend-mode": "normal",
      "z-index": "9999",
      "hide-native": false,
    },
    scrollbar: {
      width: "8px",
      height: "8px",
      padding: "2px",
      radius: "9999px",
      track: "transparent",
      thumb: "var(--s-border-muted)",
      "thumb-hover": "var(--s-border)",
      "thumb-active": "var(--s-border-strong)",
      corner: "transparent",
      border: "none",
      "firefox-width": "thin",
      gutter: "stable",
      visibility: "auto",
    },
    focus: {
      "ring-width": "2px",
      "ring-color": "var(--s-primary)",
      "ring-offset": "2px",
      "ring-shadow": "0 0 0 2px var(--s-primary)",
      "outline-color": "var(--s-primary)",
    },
    overlays: {
      bg: "rgb(0 0 0 / 0.5)",
      blur: "8px",
      surface: "var(--s-surface-elevated)",
      border: "1px solid var(--s-border-muted)",
      shadow: "var(--s-shadow-xl)",
      radius: "var(--s-radius-lg)",
      padding: "20px",
      "z-index": "50",
    },
    dataViz: {
      "series-1": "var(--s-primary)",
      "series-2": "var(--s-secondary)",
      "series-3": "var(--s-accent)",
      "series-4": "var(--s-info)",
      "series-5": "var(--s-success)",
      positive: "var(--s-success)",
      negative: "var(--s-error)",
      neutral: "var(--s-text-muted)",
      grid: "var(--s-border-muted)",
      axis: "var(--s-border)",
      label: "var(--s-text-secondary)",
      "tooltip-bg": "var(--s-surface-elevated)",
      "tooltip-border": "var(--s-border-muted)",
    },
    media: {
      radius: "var(--s-radius-md)",
      border: "none",
      outline: "1px solid rgb(0 0 0 / 0.08)",
      shadow: "none",
      bg: "var(--s-surface-sunken)",
      "object-fit": "cover",
    },
    controls: {
      height: "38px",
      "height-sm": "30px",
      "height-lg": "46px",
      "hit-area": "44px",
      "icon-size": "16px",
      "handle-size": "20px",
      "track-height": "4px",
      "track-bg": "var(--s-border-muted)",
      "track-fill": "var(--s-primary)",
      "thumb-bg": "var(--s-surface-elevated)",
      "thumb-border": "2px solid var(--s-primary)",
    },
    componentSurfaces: {
      bg: "var(--s-surface)",
      "bg-elevated": "var(--s-surface-elevated)",
      "bg-muted": "var(--s-surface-sunken)",
      border: "var(--s-border)",
      "border-muted": "var(--s-border-muted)",
      "border-strong": "var(--s-border-strong)",
      text: "var(--s-text)",
      "text-muted": "var(--s-text-muted)",
      contrast: "var(--s-primary-contrast)",
      "hover-bg": "var(--s-surface-elevated)",
      "active-bg": "var(--s-surface-sunken)",
      "selected-bg": "var(--s-primary-muted)",
    },

  },
};
