import type { SigilPreset } from "@sigil-ui/tokens";

export const dsgnPreset: SigilPreset = {
  name: "dsgn",
  metadata: {
    description:
      "Meta-design. Self-referential wireframe aesthetic with grid visibility, annotation blue, and technical precision.",
    mood: "meta-design, wireframe, technical",
    tags: ["light", "wireframe", "technical", "grid", "annotations"],
  },
  tokens: {
    colors: {
      background: { light: "#ffffff", dark: "#111111" },
      surface: { light: "#f8f8f8", dark: "#1a1a1a" },
      "surface-elevated": { light: "#ffffff", dark: "#222222" },
      "surface-sunken": { light: "#f0f0f0", dark: "#0a0a0a" },
      primary: "#2563eb",
      "primary-hover": "#1d4ed8",
      "primary-muted": "#2563eb25",
      "primary-contrast": "#ffffff",
      secondary: "#6b7280",
      "secondary-hover": "#4b5563",
      "secondary-muted": "#6b728020",
      accent: "#ef4444",
      "accent-hover": "#dc2626",
      "accent-muted": "#ef444420",
      text: { light: "#000000", dark: "#e5e5e5" },
      "text-secondary": { light: "#333333", dark: "#b0b0b0" },
      "text-muted": { light: "#666666", dark: "#808080" },
      "text-subtle": { light: "#999999", dark: "#606060" },
      "text-disabled": { light: "#cccccc", dark: "#404040" },
      "text-inverse": { light: "#ffffff", dark: "#000000" },
      border: { light: "#d1d5db", dark: "#333333" },
      "border-muted": { light: "#e5e7eb", dark: "#262626" },
      "border-strong": { light: "#9ca3af", dark: "#525252" },
      "border-interactive": { light: "#2563eb", dark: "#2563eb" },
      success: "#22c55e",
      "success-muted": "#22c55e20",
      warning: "#eab308",
      "warning-muted": "#eab30820",
      error: "#ef4444",
      "error-muted": "#ef444420",
      info: "#2563eb",
      "info-muted": "#2563eb20",
      "gradient-start": "#2563eb",
      "gradient-end": "#6b7280",
      glow: "#2563eb30",
    },
    typography: {
      "font-display": "'Azeret Mono', ui-monospace, monospace",
      "font-body": "'Inter', system-ui, sans-serif",
      "font-mono": "'Azeret Mono', ui-monospace, monospace",
      "size-xs": "0.6875rem",
      "size-sm": "0.75rem",
      "size-base": "0.8125rem",
      "size-lg": "0.875rem",
      "size-xl": "1rem",
      "size-2xl": "1.25rem",
      "size-3xl": "1.5rem",
      "size-4xl": "1.75rem",
      "size-5xl": "2.25rem",
      "size-6xl": "3rem",
      "weight-normal": "400",
      "weight-medium": "500",
      "weight-semibold": "600",
      "weight-bold": "700",
      "weight-extrabold": "800",
      "leading-tight": "1.3",
      "leading-normal": "1.5",
      "leading-relaxed": "1.625",
      "leading-loose": "1.85",
      "tracking-tighter": "-0.02em",
      "tracking-tight": "-0.01em",
      "tracking-normal": "0em",
      "tracking-wide": "0.04em",
      "tracking-wider": "0.08em",
      "heading-weight": "500",
      "heading-tracking": "0.04em",
      "heading-transform": "uppercase",
      "heading-family": "'Azeret Mono', ui-monospace, monospace",
    },
    spacing: {
      scale: [2, 4, 8, 12, 16, 20, 24, 32, 48, 64],
      unit: "px",
      "button-px": "16px",
      "button-py": "8px",
      "button-px-sm": "10px",
      "button-py-sm": "4px",
      "button-px-lg": "24px",
      "button-py-lg": "10px",
      "card-padding": "16px",
      "card-padding-sm": "12px",
      "card-padding-lg": "24px",
      "input-px": "8px",
      "input-py": "6px",
      "badge-px": "6px",
      "badge-py": "2px",
      "section-py": "48px",
      "section-py-lg": "72px",
      "navbar-height": "48px",
      "navbar-px": "16px",
      "footer-py": "32px",
      "modal-padding": "20px",
      "popover-padding": "12px",
      "tooltip-padding": "4px 8px",
      "table-cell-px": "12px",
      "table-cell-py": "8px",
    },
    layout: {
      "content-max": "1140px",
      "content-max-narrow": "680px",
      "content-max-wide": "1400px",
      "page-margin": "20px",
      "page-margin-sm": "12px",
      "page-margin-lg": "40px",
      gutter: "16px",
      "gutter-sm": "8px",
      "gutter-lg": "24px",
      "grid-columns": "12",
      "grid-gap": "16px",
      "bento-gap": "12px",
      "bento-radius": "4px",
      "bento-min-height": "160px",
      "section-gap": "24px",
      "sidebar-width": "240px",
      "sidebar-collapsed": "48px",
      "footer-columns": "4",
      "stack-gap": "12px",
      "stack-gap-sm": "6px",
      "stack-gap-lg": "20px",
      "prose-max": "60ch",
    },
    sigil: {
      "grid-cell": "40px",
      "cross-arm": "8px",
      "cross-stroke": "1px",
      "rail-gap": "20px",
      "card-radius": "4px",
    },
    radius: {
      none: "0px",
      sm: "2px",
      md: "4px",
      lg: "4px",
      xl: "6px",
      "2xl": "8px",
      full: "9999px",
      button: "4px",
      card: "4px",
      input: "4px",
      badge: "2px",
      modal: "6px",
      popover: "4px",
      tooltip: "2px",
      image: "4px",
      bento: "4px",
    },
    shadows: {
      sm: "0 1px 2px rgb(0 0 0 / 0.04)",
      md: "0 1px 3px rgb(0 0 0 / 0.06)",
      lg: "0 2px 6px rgb(0 0 0 / 0.08)",
      xl: "0 4px 12px rgb(0 0 0 / 0.1)",
      "2xl": "0 8px 24px rgb(0 0 0 / 0.12)",
      glow: "0 0 12px #2563eb22",
      "glow-sm": "0 0 6px #2563eb15",
      colored: "0 2px 8px #2563eb20",
      inner: "inset 0 1px 2px rgb(0 0 0 / 0.04)",
      card: "none",
      button: "none",
      "button-hover": "none",
      dropdown: "0 2px 8px rgb(0 0 0 / 0.1)",
      modal: "0 8px 32px rgb(0 0 0 / 0.15)",
    },
    motion: {
      duration: { instant: "0ms", fast: "100ms", normal: "200ms", slow: "300ms", slower: "500ms", slowest: "800ms" },
      easing: {
        default: "cubic-bezier(0.16, 1, 0.3, 1)",
        in: "cubic-bezier(0.55, 0, 1, 0.45)",
        out: "cubic-bezier(0, 0.55, 0.45, 1)",
        "in-out": "cubic-bezier(0.45, 0, 0.55, 1)",
        spring: "cubic-bezier(0.22, 1, 0.36, 1)",
        bounce: "cubic-bezier(0.68, -0.55, 0.27, 1.55)",
      },
      "enter-preset": "fadeIn",
      "exit-preset": "fadeOut",
      "hover-scale": "1",
      "press-scale": "0.98",
      "hover-lift": "0px",
      "stagger-interval": "40ms",
      "stagger-interval-fast": "20ms",
    },
    borders: {
      width: { none: "0px", thin: "1px", medium: "1.5px", thick: "2px" },
      style: "solid",
      "card-border": "1px dashed",
      "card-border-hover": "1px dashed",
      "button-border": "1px solid",
      "input-border": "1px solid",
      "divider-style": "dashed",
      "divider-width": "1px",
    },
    buttons: {
      "font-weight": "500",
      "text-transform": "uppercase",
      "letter-spacing": "0.04em",
      "font-family": "'Azeret Mono', ui-monospace, monospace",
      "border-width": "1px",
      "hover-effect": "outline",
      "active-scale": "0.98",
      "icon-gap": "6px",
      "min-width": "0px",
    },
    cards: {
      "border-style": "dashed",
      "border-width": "1px",
      "hover-effect": "none",
      "hover-border-color": "var(--s-border-strong)",
      padding: "16px",
      "header-padding": "16px 16px 0",
      "footer-padding": "0 16px 16px",
      "title-size": "0.875rem",
      "title-weight": "500",
      "description-size": "0.75rem",
      outline: true,
      shadow: "none",
    },
    headings: {
      "h1-size": "1.75rem",
      "h1-weight": "500",
      "h1-tracking": "0.04em",
      "h1-leading": "1.3",
      "h2-size": "1.5rem",
      "h2-weight": "500",
      "h2-tracking": "0.03em",
      "h3-size": "1.25rem",
      "h3-weight": "500",
      "h4-size": "1rem",
      "h4-weight": "500",
      "display-size": "3rem",
      "display-weight": "700",
      "display-tracking": "0.06em",
      "display-leading": "1.1",
    },
    navigation: {
      "navbar-height": "48px",
      "navbar-backdrop-blur": "0px",
      "navbar-border": "1px dashed",
      "navbar-bg-opacity": "0.95",
      "nav-link-weight": "500",
      "nav-link-size": "0.75rem",
      "nav-link-hover": "underline",
      "breadcrumb-separator": " → ",
      "pagination-radius": "4px",
      "sidebar-width": "240px",
      "sidebar-item-radius": "4px",
      "sidebar-item-padding": "6px 10px",
    },
    backgrounds: {
      pattern: "grid",
      "pattern-opacity": "0.08",
      "pattern-scale": "1",
      noise: false,
      "noise-opacity": "0",
      "gradient-angle": "0deg",
      "gradient-type": "none",
      "hero-pattern": "grid",
      "section-divider": "line",
    },
    code: {
      "font-family": "'Azeret Mono', ui-monospace, monospace",
      "font-size": "0.75rem",
      "line-height": "1.6",
      bg: "var(--s-surface-sunken)",
      border: "1px dashed var(--s-border)",
      "border-radius": "4px",
      padding: "12px",
      "tab-size": "2",
      "selection-bg": "#2563eb20",
      "comment-color": "var(--s-text-muted)",
      "keyword-color": "#2563eb",
      "string-color": "#22c55e",
      "number-color": "#eab308",
      "function-color": "#ef4444",
    },
    inputs: {
      height: "36px",
      "height-sm": "28px",
      "height-lg": "44px",
      "border-width": "1px",
      "focus-ring-width": "2px",
      "focus-ring-color": "#2563eb",
      "focus-ring-offset": "1px",
      "placeholder-color": "var(--s-text-subtle)",
      "error-border-color": "#ef4444",
      "label-size": "0.6875rem",
      "label-weight": "500",
      "label-spacing": "4px",
      "helper-size": "0.6875rem",
    },
    alignment: {
      "title-align": "left",
      "rail-margin": "24px",
    },
    sections: {
      "padding-y": "56px",
      gap: "24px",
    },
    dividers: {
      style: "dashed",
      ornament: "cross",
    },
    gridVisuals: {
      "show-lines": true,
      "show-dots": true,
      "line-width": "1px",
      "rail-visible": true,
      "rail-columns": "12",
    },
  },
};
