import type { SigilPreset } from "@sigil-ui/tokens";

export const dsgnPreset: SigilPreset = {
  name: "dsgn",
  metadata: {
    description:
      "Meta-design. Self-referential wireframe aesthetic with grid visibility, annotation blue, and technical precision.",
    mood: "meta-design, wireframe, technical",
    tags: ["light", "wireframe", "technical", "grid", "annotations"],
  },
  tokens: {
    colors: {
      background: { light: "#ffffff", dark: "#111111" },
      surface: { light: "#f8f8f8", dark: "#1a1a1a" },
      "surface-elevated": { light: "#ffffff", dark: "#222222" },
      "surface-sunken": { light: "#f0f0f0", dark: "#0a0a0a" },
      primary: "#2563eb",
      "primary-hover": "#1d4ed8",
      "primary-muted": "#2563eb25",
      "primary-contrast": "#ffffff",
      secondary: "#6b7280",
      "secondary-hover": "#4b5563",
      "secondary-muted": "#6b728020",
      accent: "#ef4444",
      "accent-hover": "#dc2626",
      "accent-muted": "#ef444420",
      text: { light: "#000000", dark: "#e5e5e5" },
      "text-secondary": { light: "#333333", dark: "#b0b0b0" },
      "text-muted": { light: "#666666", dark: "#909090" },
      "text-subtle": { light: "#929292", dark: "#707070" },
      "text-disabled": { light: "#cccccc", dark: "#404040" },
      "text-inverse": { light: "#ffffff", dark: "#000000" },
      border: { light: "#8f9398", dark: "oklch(0.358 0.006 0)" },
      "border-muted": { light: "#bec1c6", dark: "oklch(0.298 0.006 0)" },
      "border-strong": { light: "#6b7280", dark: "oklch(0.438 0.006 0)" },
      "border-interactive": { light: "#2563eb", dark: "#2563eb" },
      success: "#00a943",
      "success-muted": "#22c55e20",
      warning: "#be8900",
      "warning-muted": "#eab30820",
      error: "#dc2626",
      "error-muted": "#dc262620",
      info: "#0284c7",
      "info-muted": "#0284c720",
      "gradient-start": "#2563eb",
      "gradient-end": "#6b7280",
      glow: "#2563eb30",
      highlight: { light: "#dbeafe", dark: "rgba(59, 130, 246, 0.15)" },
    },
    typography: {
      "font-display": "'PP Casa', system-ui, sans-serif",
      "font-body": "'PP Neue Montreal', system-ui, sans-serif",
      "font-mono": "'PP Fraktion Mono', ui-monospace, monospace",
      "size-xs": "0.6875rem",
      "size-sm": "0.75rem",
      "size-base": "0.8125rem",
      "size-lg": "0.875rem",
      "size-xl": "1rem",
      "size-2xl": "1.25rem",
      "size-3xl": "1.5rem",
      "size-4xl": "1.75rem",
      "size-5xl": "2.25rem",
      "size-6xl": "3rem",
      "weight-normal": "400",
      "weight-medium": "500",
      "weight-semibold": "600",
      "weight-bold": "700",
      "weight-extrabold": "800",
      "leading-tight": "1.3",
      "leading-normal": "1.5",
      "leading-relaxed": "1.625",
      "leading-loose": "1.85",
      "tracking-tighter": "-0.02em",
      "tracking-tight": "-0.01em",
      "tracking-normal": "0em",
      "tracking-wide": "0.04em",
      "tracking-wider": "0.08em",
      "heading-weight": "400",
      "heading-tracking": "-0.01em",
      "heading-transform": "none",
      "heading-family": "'PP Casa', system-ui, sans-serif",
    },
    spacing: {
      scale: [2, 4, 8, 12, 16, 20, 24, 32, 48, 64],
      unit: "px",
      "button-px": "16px",
      "button-py": "8px",
      "button-px-sm": "10px",
      "button-py-sm": "4px",
      "button-px-lg": "24px",
      "button-py-lg": "10px",
      "card-padding": "14px",
      "card-padding-sm": "10px",
      "card-padding-lg": "20px",
      "input-px": "8px",
      "input-py": "6px",
      "badge-px": "6px",
      "badge-py": "2px",
      "section-py": "48px",
      "section-py-lg": "64px",
      "navbar-height": "48px",
      "navbar-px": "14px",
      "footer-py": "32px",
      "modal-padding": "20px",
      "popover-padding": "12px",
      "tooltip-padding": "4px 8px",
      "table-cell-px": "12px",
      "table-cell-py": "8px",
    },
    layout: {
      "content-max": "1200px",
      "content-max-narrow": "720px",
      "content-max-wide": "1440px",
      "page-margin": "16px",
      "page-margin-sm": "12px",
      "page-margin-lg": "32px",
      gutter: "12px",
      "gutter-sm": "6px",
      "gutter-lg": "20px",
      "grid-columns": "12",
      "grid-gap": "12px",
      "bento-gap": "8px",
      "bento-radius": "4px",
      "bento-min-height": "160px",
      "section-gap": "32px",
      "sidebar-width": "220px",
      "sidebar-collapsed": "48px",
      "footer-columns": "4",
      "stack-gap": "12px",
      "stack-gap-sm": "6px",
      "stack-gap-lg": "20px",
      "prose-max": "60ch",
    },
    sigil: {
      "grid-cell": "32px",
      "cross-arm": "6px",
      "cross-stroke": "1px",
      "rail-gap": "16px",
      "card-radius": "4px",
      "gutter-pattern": "plus",
      "margin-pattern": "horizontal",
    },
    radius: {
      none: "0px",
      sm: "2px",
      md: "4px",
      lg: "4px",
      xl: "6px",
      "2xl": "8px",
      full: "9999px",
      button: "4px",
      card: "4px",
      input: "4px",
      badge: "2px",
      modal: "6px",
      popover: "4px",
      tooltip: "2px",
      image: "4px",
      bento: "4px",
    },
    shadows: {
      sm: "0 1px 2px rgb(0 0 0 / 0.04)",
      md: "0 1px 3px rgb(0 0 0 / 0.06)",
      lg: "0 2px 6px rgb(0 0 0 / 0.08)",
      xl: "0 4px 12px rgb(0 0 0 / 0.1)",
      "2xl": "0 8px 24px rgb(0 0 0 / 0.12)",
      glow: "0 0 12px #2563eb22",
      "glow-sm": "0 0 6px #2563eb15",
      colored: "0 2px 8px #2563eb20",
      inner: "inset 0 1px 2px rgb(0 0 0 / 0.04)",
      card: "none",
      button: "none",
      "button-hover": "none",
      dropdown: "0 2px 8px rgb(0 0 0 / 0.1)",
      modal: "0 8px 32px rgb(0 0 0 / 0.15)",
    },
    motion: {
      duration: { instant: "0ms", fast: "100ms", normal: "200ms", slow: "300ms", slower: "500ms", slowest: "800ms" },
      easing: {
        default: "cubic-bezier(0.16, 1, 0.3, 1)",
        in: "cubic-bezier(0.55, 0, 1, 0.45)",
        out: "cubic-bezier(0, 0.55, 0.45, 1)",
        "in-out": "cubic-bezier(0.45, 0, 0.55, 1)",
        spring: "cubic-bezier(0.22, 1, 0.36, 1)",
        bounce: "cubic-bezier(0.68, -0.55, 0.27, 1.55)",
      },
      "enter-preset": "fadeIn",
      "exit-preset": "fadeOut",
      "hover-scale": "1",
      "press-scale": "0.98",
      "hover-lift": "0px",
      "stagger-interval": "40ms",
      "stagger-interval-fast": "20ms",
    },
    borders: {
      width: { none: "0px", thin: "1px", medium: "1.5px", thick: "2px" },
      style: "dashed",
      "card-border": "1px dashed",
      "card-border-hover": "1px dashed",
      "button-border": "1px solid",
      "input-border": "1px solid",
      "divider-style": "dashed",
      "divider-width": "1px",
    },
    buttons: {
      "font-weight": "500",
      "text-transform": "uppercase",
      "letter-spacing": "0.04em",
      "font-family": "'PP Neue Montreal', system-ui, sans-serif",
      "border-width": "1px",
      "hover-effect": "outline",
      "active-scale": "0.98",
      "icon-gap": "6px",
      "min-width": "0px",
    },
    cards: {
      "border-style": "dashed",
      "border-width": "1px",
      "hover-effect": "lift",
      "hover-border-color": "var(--s-border-strong)",
      padding: "16px",
      "header-padding": "16px 16px 0",
      "footer-padding": "0 16px 16px",
      "title-size": "0.875rem",
      "title-weight": "500",
      "description-size": "0.75rem",
      outline: true,
      shadow: "none",
    },
    headings: {
      "h1-size": "1.75rem",
      "h1-weight": "500",
      "h1-tracking": "0.04em",
      "h1-leading": "1.3",
      "h2-size": "1.5rem",
      "h2-weight": "500",
      "h2-tracking": "0.03em",
      "h2-leading": "1.15",
      "h3-size": "1.25rem",
      "h3-weight": "500",
      "h3-tracking": "0.02em",
      "h3-leading": "1.2",
      "h4-size": "1rem",
      "h4-weight": "500",
      "h4-tracking": "0.01em",
      "h4-leading": "1.3",
      "display-size": "3rem",
      "display-weight": "700",
      "display-tracking": "0.06em",
      "display-leading": "1.1",
    },
    navigation: {
      "navbar-height": "48px",
      "navbar-backdrop-blur": "0px",
      "navbar-border": "1px dashed",
      "navbar-bg-opacity": "1",
      "navbar-padding-x": "24px",
      "navbar-position": "sticky",
      "navbar-logo-height": "26px",
      "navbar-logo-gap": "10px",
      "navbar-item-gap": "24px",
      "navbar-item-padding-x": "14px",
      "navbar-item-padding-y": "6px",
      "navbar-item-size": "0.875rem",
      "navbar-shadow": "none",
      "navbar-height-scrolled": "48px",
      "navbar-mobile-breakpoint": "768px",
      "nav-link-weight": "500",
      "nav-link-size": "0.6875rem",
      "nav-link-hover": "underline",
      "breadcrumb-separator": " → ",
      "pagination-radius": "4px",
      "sidebar-width": "220px",
      "sidebar-item-radius": "3px",
      "sidebar-item-padding": "5px 8px",
    },
    backgrounds: {
      pattern: "dots",
      "pattern-opacity": "0.04",
      "pattern-scale": "1",
      noise: true,
      "noise-opacity": "0.015",
      "gradient-angle": "0deg",
      "gradient-type": "none",
      "hero-pattern": "noise",
      "section-divider": "line",
    },
    code: {
      "font-family": "'PP Fraktion Mono', ui-monospace, monospace",
      "font-size": "0.75rem",
      "line-height": "1.6",
      bg: "var(--s-surface-sunken)",
      border: "1px dashed var(--s-border)",
      "border-radius": "4px",
      padding: "12px",
      "tab-size": "2",
      "selection-bg": "#2563eb20",
      "comment-color": "var(--s-text-muted)",
      "keyword-color": "#2563eb",
      "string-color": "#22c55e",
      "number-color": "#eab308",
      "function-color": "#ef4444",
    },
    inputs: {
      height: "36px",
      "height-sm": "28px",
      "height-lg": "44px",
      "border-width": "1px",
      "focus-ring-width": "2px",
      "focus-ring-color": "#2563eb",
      "focus-ring-offset": "1px",
      "placeholder-color": "var(--s-text-subtle)",
      "error-border-color": "#ef4444",
      "label-size": "0.6875rem",
      "label-weight": "500",
      "label-spacing": "4px",
      "helper-size": "0.6875rem",
    },
    alignment: {
      "title-align": "left",
      "rail-margin": "24px",
    },
    sections: {
      "padding-y": "64px",
      "padding-y-hero": "96px",
      "padding-y-sm": "48px",
      gap: "24px",
      "padding-y-lg": "96px",
      "padding-y-xl": "144px",
      "title-align": "center",
      "heading-size": "clamp(1.5rem, 4vw, 2.5rem)",
      "heading-align": "center",
      "heading-max-width": "40rem",
      "heading-margin-bottom": "16px",
      "description-max-width": "32rem",
      "description-gap": "12px",
      "content-gap": "24px",
      "grid-columns": "3",
      "grid-gap": "24px",
      "alternate-bg": "var(--s-surface)",
      "alternate-bg-mode": "surface",
    },
    dividers: {
      style: "dashed",
      ornament: "cross",
      spacing: "0px",
      opacity: "0.8",
      "max-width": "100%",
      "margin-y": "0px",
      thickness: "1px",
      "gradient-start": "var(--s-primary)",
      "gradient-end": "var(--s-secondary)",
    },
    gridVisuals: {
      "line-color": "var(--s-border-muted)",
      "show-lines": true,
      "show-dots": true,
      "line-width": "1px",
      "rail-visible": true,
      "rail-columns": "12",
    },
    cursor: {
      variant: "ring",
      size: "24px",
      "dot-size": "4px",
      "stroke-width": "1.5px",
      "tick-size": "6px",
      gap: "3px",
      radius: "0px",
      color: "var(--s-text)",
      "ring-color": "var(--s-primary)",
      "dot-color": "var(--s-primary)",
      glow: "none",
      opacity: "1",
      "blend-mode": "normal",
      "z-index": "9999",
      "hide-native": false,
    },
    scrollbar: {
      width: "8px",
      height: "8px",
      padding: "2px",
      radius: "9999px",
      track: "transparent",
      thumb: "var(--s-border-muted)",
      "thumb-hover": "var(--s-border)",
      "thumb-active": "var(--s-border-strong)",
      corner: "transparent",
      border: "none",
      "firefox-width": "thin",
      gutter: "stable",
      visibility: "auto",
    },
    focus: {
      "ring-width": "2px",
      "ring-color": "var(--s-primary)",
      "ring-offset": "2px",
      "ring-shadow": "0 0 0 2px var(--s-primary)",
      "outline-color": "var(--s-primary)",
    },
    overlays: {
      bg: "rgb(0 0 0 / 0.5)",
      blur: "8px",
      surface: "var(--s-surface-elevated)",
      border: "1px solid var(--s-border-muted)",
      shadow: "var(--s-shadow-xl)",
      radius: "var(--s-radius-lg)",
      padding: "20px",
      "z-index": "50",
    },
    dataViz: {
      "series-1": "var(--s-primary)",
      "series-2": "var(--s-secondary)",
      "series-3": "var(--s-accent)",
      "series-4": "var(--s-info)",
      "series-5": "var(--s-success)",
      positive: "var(--s-success)",
      negative: "var(--s-error)",
      neutral: "var(--s-text-muted)",
      grid: "var(--s-border-muted)",
      axis: "var(--s-border)",
      label: "var(--s-text-secondary)",
      "tooltip-bg": "var(--s-surface-elevated)",
      "tooltip-border": "var(--s-border-muted)",
    },
    media: {
      radius: "var(--s-radius-md)",
      border: "none",
      outline: "1px solid rgb(0 0 0 / 0.08)",
      shadow: "none",
      bg: "var(--s-surface-sunken)",
      "object-fit": "cover",
    },
    controls: {
      height: "38px",
      "height-sm": "30px",
      "height-lg": "46px",
      "hit-area": "44px",
      "icon-size": "16px",
      "handle-size": "20px",
      "track-height": "4px",
      "track-bg": "var(--s-border-muted)",
      "track-fill": "var(--s-primary)",
      "thumb-bg": "var(--s-surface-elevated)",
      "thumb-border": "2px solid var(--s-primary)",
    },
    componentSurfaces: {
      bg: "var(--s-surface)",
      "bg-elevated": "var(--s-surface-elevated)",
      "bg-muted": "var(--s-surface-sunken)",
      border: "var(--s-border)",
      "border-muted": "var(--s-border-muted)",
      "border-strong": "var(--s-border-strong)",
      text: "var(--s-text)",
      "text-muted": "var(--s-text-muted)",
      contrast: "var(--s-primary-contrast)",
      "hover-bg": "var(--s-surface-elevated)",
      "active-bg": "var(--s-surface-sunken)",
      "selected-bg": "var(--s-primary-muted)",
    },
    hero: {
      "min-height": "auto",
      "padding-y": "96px",
      "padding-y-sm": "64px",
      "padding-x": "var(--s-page-margin, 24px)",
      "content-max": "640px",
      "content-align": "center",
      layout: "centered",
      "media-position": "below",
      "media-width": "50%",
      "media-radius": "var(--s-radius-xl)",
      "title-size": "clamp(2.25rem, 6vw, 4.5rem)",
      "title-max-width": "56rem",
      "description-size": "1.125rem",
      "description-max-width": "32rem",
      "description-gap": "24px",
      "actions-gap": "14px",
      "actions-margin-top": "32px",
      "action-padding-x": "28px",
      "action-padding-y": "12px",
      "badge-gap": "24px",
      "overlay-opacity": "0.4",
      "scroll-indicator": false,
      "gradient-overlay": "none",
    },
    cta: {
      "padding-y": "80px",
      "padding-x": "var(--s-page-margin, 24px)",
      "max-width": "var(--s-content-max, 1200px)",
      layout: "centered",
      border: true,
      "border-radius": "var(--s-radius-xl)",
      bg: "var(--s-surface)",
      "title-size": "clamp(1.5rem, 4vw, 2.5rem)",
      "description-max-width": "32rem",
      "description-gap": "12px",
      "actions-gap": "14px",
      "actions-margin-top": "32px",
      "action-padding-x": "28px",
      "action-padding-y": "12px",
      "split-gap": "48px",
    },
    footer: {
      "padding-y": "48px",
      "border-top": "1px solid var(--s-border)",
      columns: "4",
      "column-gap": "32px",
      "row-gap": "28px",
      "logo-height": "24px",
      "tagline-max-width": "20rem",
      "link-size": "0.875rem",
      "link-gap": "8px",
      "group-title-size": "0.875rem",
      "group-title-weight": "600",
      "social-icon-size": "20px",
      "social-gap": "12px",
      "bottom-bar-padding": "32px 0",
      "bottom-bar-border": "1px solid var(--s-border-muted)",
    },
    banner: {
      height: "auto",
      "padding-y": "8px",
      "padding-x": "16px",
      "font-size": "0.875rem",
      "font-weight": "500",
      "icon-size": "16px",
      "icon-gap": "12px",
      "border-width": "1px",
      "border-position": "bottom",
      position: "top",
      "dismiss-size": "16px",
      radius: "0px",
    },
    pageRhythm: {
      density: "normal",
      "section-gap": "0px",
      "section-gap-sm": "0px",
      "section-gap-lg": "0px",
      "first-section-offset": "0px",
      "last-section-margin": "0px",
      "alternate-bg": true,
      "alternate-bg-color": "var(--s-surface)",
      "divider-between": false,
      "max-content-width": "var(--s-content-max, 1200px)",
      "vertical-rhythm-unit": "8px",
      "scroll-snap": false,
      "responsive-scale": "0.9",
      "responsive-breakpoint": "768px",
    },

  },
};
