import type { SigilPreset } from "@sigil-ui/tokens";

export const dunePreset: SigilPreset = {
  name: "dune",
  metadata: {
    description: "Golden desert warmth with vast, open feeling. Sharp edges, deep amber tones, serif display type.",
    mood: "warm, golden, vast-feeling",
    tags: ["edgeless", "warm", "golden", "desert", "serif", "sharp"],
  },
  tokens: {
    colors: {
      background: { light: "oklch(0.94 0.05 85)", dark: "oklch(0.15 0.04 70)" },
      surface: { light: "oklch(0.92 0.055 85)", dark: "oklch(0.19 0.045 70)" },
      "surface-elevated": { light: "oklch(0.95 0.04 85)", dark: "oklch(0.23 0.05 70)" },
      "surface-sunken": { light: "oklch(0.89 0.06 85)", dark: "oklch(0.11 0.03 70)" },
      primary: { light: "oklch(0.55 0.16 70)", dark: "oklch(0.70 0.14 70)" },
      "primary-hover": { light: "oklch(0.48 0.18 70)", dark: "oklch(0.76 0.12 70)" },
      "primary-muted": { light: "oklch(0.55 0.06 70)", dark: "oklch(0.70 0.05 70)" },
      "primary-contrast": { light: "oklch(0.99 0.005 85)", dark: "oklch(0.15 0.04 70)" },
      secondary: "oklch(0.58 0.10 50)",
      "secondary-hover": "oklch(0.52 0.12 50)",
      "secondary-muted": "oklch(0.58 0.04 50)",
      accent: { light: "oklch(0.52 0.12 30)", dark: "oklch(0.65 0.10 30)" },
      "accent-hover": { light: "oklch(0.46 0.14 30)", dark: "oklch(0.71 0.08 30)" },
      "accent-muted": { light: "oklch(0.52 0.04 30)", dark: "oklch(0.65 0.04 30)" },
      text: { light: "oklch(0.22 0.03 55)", dark: "oklch(0.92 0.02 80)" },
      "text-secondary": { light: "oklch(0.38 0.025 55)", dark: "oklch(0.74 0.02 80)" },
      "text-muted": { light: "oklch(0.52 0.02 55)", dark: "oklch(0.56 0.02 80)" },
      "text-subtle": { light: "oklch(0.65 0.015 55)", dark: "oklch(0.42 0.02 80)" },
      "text-disabled": { light: "oklch(0.78 0.01 55)", dark: "oklch(0.30 0.015 80)" },
      "text-inverse": { light: "oklch(0.92 0.02 80)", dark: "oklch(0.22 0.03 55)" },
      border: { light: "oklch(0.82 0.03 85)", dark: "oklch(0.330 0.035 70)" },
      "border-muted": { light: "oklch(0.89 0.02 85)", dark: "oklch(0.270 0.025 70)" },
      "border-strong": { light: "oklch(0.72 0.04 85)", dark: "oklch(0.410 0.040 70)" },
      "border-interactive": { light: "oklch(0.55 0.16 70)", dark: "oklch(0.70 0.14 70)" },
      success: "oklch(0.62 0.16 155)",
      "success-muted": { light: "oklch(0.95 0.03 155)", dark: "oklch(0.15 0.04 155)" },
      warning: "oklch(0.68 0.16 65)",
      "warning-muted": { light: "oklch(0.95 0.04 65)", dark: "oklch(0.16 0.04 65)" },
      error: "oklch(0.55 0.18 20)",
      "error-muted": { light: "oklch(0.96 0.03 20)", dark: "oklch(0.16 0.04 20)" },
      info: "oklch(0.58 0.14 245)",
      "info-muted": { light: "oklch(0.96 0.02 245)", dark: "oklch(0.16 0.03 245)" },
      "gradient-start": { light: "oklch(0.55 0.16 70)", dark: "oklch(0.70 0.14 70)" },
      "gradient-end": { light: "oklch(0.52 0.12 30)", dark: "oklch(0.65 0.10 30)" },
      glow: { light: "oklch(0.55 0.16 70 / 0.15)", dark: "oklch(0.70 0.14 70 / 0.18)" },
      highlight: { light: "oklch(0.93 0.06 70)", dark: "oklch(0.28 0.05 70)" },
    },
    typography: {
      "font-display": "'Instrument Serif', Georgia, serif",
      "font-body": "'DM Sans', system-ui, sans-serif",
      "font-mono": "'IBM Plex Mono', ui-monospace, monospace",
      "size-xs": "0.75rem",
      "size-sm": "0.875rem",
      "size-base": "1rem",
      "size-lg": "1.125rem",
      "size-xl": "1.25rem",
      "size-2xl": "1.5rem",
      "size-3xl": "2rem",
      "size-4xl": "2.5rem",
      "size-5xl": "3.25rem",
      "size-6xl": "4.25rem",
      "weight-normal": "400",
      "weight-medium": "500",
      "weight-semibold": "600",
      "weight-bold": "700",
      "weight-extrabold": "800",
      "leading-tight": "1.15",
      "leading-normal": "1.6",
      "leading-relaxed": "1.75",
      "leading-loose": "2",
      "tracking-tighter": "-0.04em",
      "tracking-tight": "-0.02em",
      "tracking-normal": "0em",
      "tracking-wide": "0.025em",
      "tracking-wider": "0.05em",
      "heading-weight": "400",
      "heading-tracking": "-0.02em",
      "heading-transform": "none",
      "heading-family": "'Instrument Serif', Georgia, serif",
    },
    spacing: {
      scale: [4, 8, 12, 16, 24, 32, 48, 64, 96, 128],
      unit: "px",
      "button-px": "24px",
      "button-py": "12px",
      "button-px-sm": "16px",
      "button-py-sm": "8px",
      "button-px-lg": "32px",
      "button-py-lg": "14px",
      "card-padding": "32px",
      "card-padding-sm": "20px",
      "card-padding-lg": "48px",
      "input-px": "14px",
      "input-py": "10px",
      "badge-px": "10px",
      "badge-py": "3px",
      "section-py": "120px",
      "section-py-lg": "160px",
      "navbar-height": "64px",
      "navbar-px": "32px",
      "footer-py": "80px",
      "modal-padding": "32px",
      "popover-padding": "16px",
      "tooltip-padding": "8px 14px",
      "table-cell-px": "16px",
      "table-cell-py": "14px",
    },
    layout: {
      "content-max": "1100px",
      "content-max-narrow": "660px",
      "content-max-wide": "1340px",
      "page-margin": "32px",
      "page-margin-sm": "16px",
      "page-margin-lg": "64px",
      gutter: "0px",
      "gutter-sm": "0px",
      "gutter-lg": "0px",
      "grid-columns": "12",
      "grid-gap": "32px",
      "bento-gap": "24px",
      "bento-radius": "2px",
      "bento-min-height": "220px",
      "section-gap": "48px",
      "sidebar-width": "260px",
      "sidebar-collapsed": "56px",
      "footer-columns": "4",
      "stack-gap": "20px",
      "stack-gap-sm": "12px",
      "stack-gap-lg": "32px",
      "prose-max": "60ch",
    },
    sigil: {
      "grid-cell": "64px",
      "cross-arm": "0px",
      "cross-stroke": "0px",
      "rail-gap": "0px",
      "card-radius": "2px",
      "gutter-pattern": "none",
      "margin-pattern": "none",
      "gutter-border": "none",
      "gutter-visible": false,
    },
    radius: {
      none: "0px",
      sm: "2px",
      md: "3px",
      lg: "4px",
      xl: "6px",
      "2xl": "8px",
      full: "9999px",
      button: "3px",
      card: "2px",
      input: "3px",
      badge: "2px",
      modal: "6px",
      popover: "4px",
      tooltip: "3px",
      image: "2px",
      bento: "2px",
    },
    shadows: {
      sm: "0 1px 3px 0 oklch(0.30 0.05 70 / 0.06)",
      md: "0 2px 8px -1px oklch(0.30 0.05 70 / 0.08), 0 1px 3px 0 oklch(0.30 0.05 70 / 0.04)",
      lg: "0 4px 16px -3px oklch(0.30 0.05 70 / 0.10), 0 2px 4px 0 oklch(0.30 0.05 70 / 0.04)",
      xl: "0 10px 28px -6px oklch(0.30 0.05 70 / 0.14), 0 4px 8px -2px oklch(0.30 0.05 70 / 0.05)",
      "2xl": "0 20px 48px -10px oklch(0.30 0.05 70 / 0.18)",
      glow: "0 0 28px oklch(0.70 0.14 70 / 0.22)",
      "glow-sm": "0 0 14px oklch(0.70 0.14 70 / 0.14)",
      colored: "0 4px 20px -4px oklch(0.70 0.14 70 / 0.28)",
      inner: "inset 0 2px 4px 0 oklch(0.30 0.05 70 / 0.05)",
      card: "0 1px 4px 0 oklch(0.30 0.05 70 / 0.05)",
      button: "0 1px 2px 0 oklch(0.30 0.05 70 / 0.04)",
      "button-hover": "0 2px 8px -2px oklch(0.30 0.05 70 / 0.10)",
      dropdown: "0 6px 20px -4px oklch(0.30 0.05 70 / 0.12)",
      modal: "0 20px 44px -10px oklch(0.30 0.05 70 / 0.18)",
    },
    motion: {
      duration: { instant: "0ms", fast: "120ms", normal: "240ms", slow: "400ms", slower: "600ms", slowest: "900ms" },
      easing: {
        default: "cubic-bezier(0.22, 1, 0.36, 1)",
        in: "cubic-bezier(0.55, 0, 1, 0.45)",
        out: "cubic-bezier(0, 0.55, 0.45, 1)",
        "in-out": "cubic-bezier(0.45, 0, 0.55, 1)",
        spring: "cubic-bezier(0.34, 1.56, 0.64, 1)",
      },
      "hover-scale": "1.0",
      "press-scale": "0.98",
      "hover-lift": "-1px",
      "stagger-interval": "65ms",
      "stagger-interval-fast": "35ms",
    },
    borders: {
      width: { none: "0px", thin: "1px", medium: "1.5px", thick: "2px" },
      style: "solid",
      "card-border": "1px solid",
      "card-border-hover": "1px solid",
      "button-border": "1px solid",
      "input-border": "1px solid",
      "divider-style": "solid",
      "divider-width": "1px",
    },
    buttons: {
      "font-weight": "500",
      "text-transform": "none",
      "letter-spacing": "0.01em",
      "font-family": "'DM Sans', system-ui, sans-serif",
      "border-width": "1px",
      "hover-effect": "darken",
      "active-scale": "0.98",
      "icon-gap": "8px",
      "min-width": "0px",
    },
    cards: {
      "border-style": "solid",
      "border-width": "1px",
      "hover-effect": "lift",
      "hover-border-color": "var(--s-border-strong)",
      padding: "32px",
      "header-padding": "32px 32px 0",
      "footer-padding": "0 32px 32px",
      "title-size": "1.125rem",
      "title-weight": "600",
      "description-size": "0.9375rem",
      background: "surface",
      shadow: "sm",
      outline: true,
      "outline-on-hover-only": false,
      "gap-between": "20px",
      "content-padding-x": "32px",
      "content-padding-y": "24px",
    },
    headings: {
      "h1-size": "2.5rem",
      "h1-weight": "400",
      "h1-tracking": "-0.02em",
      "h1-leading": "1.12",
      "h2-size": "2rem",
      "h2-weight": "400",
      "h2-tracking": "-0.015em",
      "h2-leading": "1.15",
      "h3-size": "1.5rem",
      "h3-weight": "500",
      "h3-tracking": "0em",
      "h3-leading": "1.2",
      "h4-size": "1.25rem",
      "h4-weight": "500",
      "h4-tracking": "0em",
      "h4-leading": "1.3",
      "display-size": "4.25rem",
      "display-weight": "400",
      "display-tracking": "-0.03em",
      "display-leading": "1.06",
    },
    navigation: {
      "navbar-height": "64px",
      "navbar-backdrop-blur": "16px",
      "navbar-border": "none",
      "navbar-bg-opacity": "0.88",
      "navbar-padding-x": "28px",
      "navbar-position": "sticky",
      "navbar-logo-height": "26px",
      "navbar-logo-gap": "10px",
      "navbar-item-gap": "28px",
      "navbar-item-padding-x": "14px",
      "navbar-item-padding-y": "8px",
      "navbar-item-size": "0.875rem",
      "navbar-shadow": "none",
      "navbar-height-scrolled": "52px",
      "navbar-mobile-breakpoint": "768px",
      "nav-link-weight": "400",
      "nav-link-size": "0.9375rem",
      "nav-link-hover": "color",
      "breadcrumb-separator": "/",
      "pagination-radius": "3px",
      "sidebar-width": "260px",
      "sidebar-item-radius": "4px",
      "sidebar-item-padding": "10px 14px",
    },
    backgrounds: {
      pattern: "none",
      "pattern-opacity": "0",
      "pattern-scale": "1",
      noise: true,
      "noise-opacity": "0.02",
      "gradient-angle": "180deg",
      "gradient-type": "none",
      "hero-pattern": "noise",
      "section-divider": "none",
    },
    code: {
      "font-family": "'IBM Plex Mono', ui-monospace, monospace",
      "font-size": "0.875rem",
      "line-height": "1.7",
      bg: "var(--s-surface-sunken)",
      border: "1px solid var(--s-border-muted)",
      "border-radius": "3px",
      padding: "20px",
      "tab-size": "2",
      "selection-bg": "oklch(0.70 0.14 70 / 0.2)",
      "comment-color": "var(--s-text-muted)",
      "keyword-color": "oklch(0.55 0.16 70)",
      "string-color": "oklch(0.62 0.16 155)",
      "number-color": "oklch(0.58 0.14 245)",
      "function-color": "oklch(0.52 0.12 30)",
    },
    inputs: {
      height: "42px",
      "height-sm": "36px",
      "height-lg": "50px",
      "border-width": "1px",
      "focus-ring-width": "2px",
      "focus-ring-color": "var(--s-primary)",
      "focus-ring-offset": "2px",
      "placeholder-color": "var(--s-text-subtle)",
      "error-border-color": "var(--s-error)",
      "label-size": "0.875rem",
      "label-weight": "500",
      "label-spacing": "8px",
      "helper-size": "0.8125rem",
    },
    alignment: {
      "rail-width": "1100px",
      "rail-columns": "12",
      "rail-gutter": "32px",
      "rail-margin": "32px",
      "rail-visible": false,
      "rail-color": "var(--s-border-muted)",
      "content-align": "center",
      "hero-align": "center",
      "section-align": "center",
      "navbar-align": "full",
      "footer-align": "full",
    },
    sections: {
      "padding-y": "120px",
      "padding-y-hero": "160px",
      "padding-y-sm": "48px",
      "padding-x": "32px",
      "max-width": "1100px",
      gap: "48px",
      "padding-y-lg": "104px",
      "padding-y-xl": "152px",
      "title-align": "center",
      "heading-size": "clamp(1.5rem, 4vw, 2.5rem)",
      "heading-align": "center",
      "heading-max-width": "40rem",
      "heading-margin-bottom": "16px",
      "description-max-width": "32rem",
      "description-gap": "14px",
      "content-gap": "28px",
      "grid-columns": "3",
      "grid-gap": "28px",
      "alternate-bg": "var(--s-surface)",
      "alternate-bg-mode": "surface",
      "divider-above": false,
      "divider-below": false,
      "background-alt": false,
      indent: "0px",
    },
    dividers: {
      style: "none",
      width: "0px",
      color: "var(--s-border-muted)",
      spacing: "0px",
      opacity: "0.4",
      "max-width": "100%",
      "margin-y": "0px",
      thickness: "1px",
      "gradient-start": "transparent",
      "gradient-end": "transparent",
      "show-cross": false,
      "show-label": false,
      "full-bleed": false,
      ornament: "none",
    },
    gridVisuals: {
      "show-lines": false,
      "line-color": "var(--s-border-muted)",
      "line-width": "1px",
      "show-dots": false,
      "dot-size": "2px",
      "cell-background": "none",
      "cell-border": false,
      "cell-radius": "2px",
      "cell-padding": "24px",
      "hover-effect": "lift",
    },
    cursor: {
      variant: "dot",
      size: "24px",
      "dot-size": "4px",
      "stroke-width": "1.5px",
      "tick-size": "6px",
      gap: "3px",
      radius: "0px",
      color: "var(--s-text)",
      "ring-color": "var(--s-primary)",
      "dot-color": "var(--s-primary)",
      glow: "none",
      opacity: "1",
      "blend-mode": "normal",
      "z-index": "9999",
      "hide-native": false,
    },
    scrollbar: {
      width: "8px",
      height: "8px",
      padding: "2px",
      radius: "9999px",
      track: "transparent",
      thumb: "var(--s-border-muted)",
      "thumb-hover": "var(--s-border)",
      "thumb-active": "var(--s-border-strong)",
      corner: "transparent",
      border: "none",
      "firefox-width": "thin",
      gutter: "stable",
      visibility: "auto",
    },
    focus: {
      "ring-width": "2px",
      "ring-color": "var(--s-primary)",
      "ring-offset": "2px",
      "ring-shadow": "0 0 0 2px var(--s-primary)",
      "outline-color": "var(--s-primary)",
    },
    overlays: {
      bg: "rgb(0 0 0 / 0.5)",
      blur: "8px",
      surface: "var(--s-surface-elevated)",
      border: "1px solid var(--s-border-muted)",
      shadow: "var(--s-shadow-xl)",
      radius: "var(--s-radius-lg)",
      padding: "20px",
      "z-index": "50",
    },
    dataViz: {
      "series-1": "var(--s-primary)",
      "series-2": "var(--s-secondary)",
      "series-3": "var(--s-accent)",
      "series-4": "var(--s-info)",
      "series-5": "var(--s-success)",
      positive: "var(--s-success)",
      negative: "var(--s-error)",
      neutral: "var(--s-text-muted)",
      grid: "var(--s-border-muted)",
      axis: "var(--s-border)",
      label: "var(--s-text-secondary)",
      "tooltip-bg": "var(--s-surface-elevated)",
      "tooltip-border": "var(--s-border-muted)",
    },
    media: {
      radius: "var(--s-radius-md)",
      border: "none",
      outline: "1px solid rgb(0 0 0 / 0.08)",
      shadow: "none",
      bg: "var(--s-surface-sunken)",
      "object-fit": "cover",
    },
    controls: {
      height: "38px",
      "height-sm": "30px",
      "height-lg": "46px",
      "hit-area": "44px",
      "icon-size": "16px",
      "handle-size": "20px",
      "track-height": "4px",
      "track-bg": "var(--s-border-muted)",
      "track-fill": "var(--s-primary)",
      "thumb-bg": "var(--s-surface-elevated)",
      "thumb-border": "2px solid var(--s-primary)",
    },
    componentSurfaces: {
      bg: "var(--s-surface)",
      "bg-elevated": "var(--s-surface-elevated)",
      "bg-muted": "var(--s-surface-sunken)",
      border: "var(--s-border)",
      "border-muted": "var(--s-border-muted)",
      "border-strong": "var(--s-border-strong)",
      text: "var(--s-text)",
      "text-muted": "var(--s-text-muted)",
      contrast: "var(--s-primary-contrast)",
      "hover-bg": "var(--s-surface-elevated)",
      "active-bg": "var(--s-surface-sunken)",
      "selected-bg": "var(--s-primary-muted)",
    },
    hero: {
      "min-height": "auto",
      "padding-y": "128px",
      "padding-y-sm": "72px",
      "padding-x": "var(--s-page-margin, 28px)",
      "content-max": "640px",
      "content-align": "center",
      layout: "centered",
      "media-position": "below",
      "media-width": "50%",
      "media-radius": "var(--s-radius-2xl)",
      "title-size": "clamp(2.5rem, 6vw, 4.5rem)",
      "title-max-width": "56rem",
      "description-size": "1.1875rem",
      "description-max-width": "34rem",
      "description-gap": "28px",
      "actions-gap": "14px",
      "actions-margin-top": "36px",
      "action-padding-x": "28px",
      "action-padding-y": "14px",
      "badge-gap": "28px",
      "overlay-opacity": "0.3",
      "scroll-indicator": false,
      "gradient-overlay": "none",
    },
    cta: {
      "padding-y": "96px",
      "padding-x": "var(--s-page-margin, 28px)",
      "max-width": "var(--s-content-max, 1200px)",
      layout: "centered",
      border: false,
      "border-radius": "var(--s-radius-2xl)",
      bg: "var(--s-surface)",
      "title-size": "clamp(1.5rem, 4vw, 2.5rem)",
      "description-max-width": "34rem",
      "description-gap": "14px",
      "actions-gap": "14px",
      "actions-margin-top": "36px",
      "action-padding-x": "28px",
      "action-padding-y": "14px",
      "split-gap": "56px",
    },
    footer: {
      "padding-y": "56px",
      "border-top": "1px solid var(--s-border-muted)",
      columns: "4",
      "column-gap": "36px",
      "row-gap": "32px",
      "logo-height": "24px",
      "tagline-max-width": "22rem",
      "link-size": "0.875rem",
      "link-gap": "10px",
      "group-title-size": "0.8125rem",
      "group-title-weight": "500",
      "social-icon-size": "20px",
      "social-gap": "14px",
      "bottom-bar-padding": "28px 0",
      "bottom-bar-border": "1px solid var(--s-border-muted)",
    },
    banner: {
      height: "auto",
      "padding-y": "10px",
      "padding-x": "20px",
      "font-size": "0.875rem",
      "font-weight": "400",
      "icon-size": "16px",
      "icon-gap": "12px",
      "border-width": "1px",
      "border-position": "bottom",
      position: "top",
      "dismiss-size": "16px",
      radius: "0px",
    },
    pageRhythm: {
      density: "spacious",
      "section-gap": "0px",
      "section-gap-sm": "0px",
      "section-gap-lg": "0px",
      "first-section-offset": "0px",
      "last-section-margin": "0px",
      "alternate-bg": true,
      "alternate-bg-color": "var(--s-surface)",
      "divider-between": false,
      "max-content-width": "var(--s-content-max, 1200px)",
      "vertical-rhythm-unit": "8px",
      "scroll-snap": false,
      "responsive-scale": "0.85",
      "responsive-breakpoint": "768px",
    },
  },
};
