import type { SigilPreset } from "@sigil-ui/tokens";
import { completePreset } from "./_template";

export const duskPreset: SigilPreset = completePreset({
  name: "dusk",
  metadata: {
    description:
      "Twilight atmosphere. Purple haze gradients, atmospheric glow, and spring-eased motion.",
    mood: "twilight, atmospheric, haze",
    tags: ["dark", "twilight", "purple", "gradient", "atmospheric"],
  },
  tokens: {
    colors: {
      background: { light: "oklch(0.9691 0.0161 293.7557)", dark: "oklch(0.2125 0.0296 296.0338)" },
      surface: { light: "oklch(0.9433 0.0284 294.5878)", dark: "oklch(0.2458 0.0361 295.7188)" },
      "surface-elevated": { light: "oklch(1 0 0)", dark: "oklch(0.2827 0.0439 294.9211)" },
      "surface-sunken": { light: "oklch(0.9292 0.0325 293.4068)", dark: "oklch(0.1836 0.0265 294.232)" },
      primary: "oklch(0.6306 0.1991 289.7303)",
      "primary-hover": "oklch(0.6056 0.2189 292.7172)",
      "primary-muted": "oklch(0.709 0.1592 293.5412 / 0.1882)",
      "primary-contrast": "oklch(0.2125 0.0296 296.0338)",
      secondary: "oklch(0.6801 0.1583 276.9349)",
      "secondary-hover": "oklch(0.5854 0.2041 277.1173)",
      "secondary-muted": "oklch(0.6801 0.1583 276.9349 / 0.1451)",
      accent: "oklch(0.7253 0.1752 349.7607)",
      "accent-hover": "oklch(0.6559 0.2118 354.3084)",
      "accent-muted": "oklch(0.7253 0.1752 349.7607 / 0.1451)",
      text: { light: "oklch(0.2352 0.0362 290.5754)", dark: "oklch(0.9145 0.0219 297.398)" },
      "text-secondary": { light: "oklch(0.3681 0.0711 290.0994)", dark: "oklch(0.8056 0.0571 298.8341)" },
      "text-muted": { light: "oklch(0.5253 0.1008 290.9924)", dark: "oklch(0.6809 0.0561 295.7299)" },
      "text-subtle": { light: "oklch(0.6297 0.0794 293.5088)", dark: "oklch(0.604 0.0695 300.6338)" },
      "text-disabled": { light: "oklch(0.7596 0.0631 301.8992)", dark: "oklch(0.3889 0.0601 300.7163)" },
      "text-inverse": { light: "oklch(0.9145 0.0219 297.398)", dark: "oklch(0.2352 0.0362 290.5754)" },
      border: { light: "oklch(0.6414 0.0537 292.4592)", dark: "oklch(0.380 0.035 296)" },
      "border-muted": { light: "oklch(0.8113 0.0393 293.695)", dark: "oklch(0.320 0.025 296)" },
      "border-strong": { light: "oklch(0.6448 0.1025 293.9817)", dark: "oklch(0.472 0.045 293)" },
      "border-interactive": { light: "oklch(0.709 0.1592 293.5412)", dark: "oklch(0.709 0.1592 293.5412)" },
      success: "oklch(0.6201 0.1393 160.419)",
      "success-muted": "oklch(0.7729 0.1535 163.2231 / 0.1451)",
      warning: "oklch(0.6424 0.1344 76.9066)",
      "warning-muted": "oklch(0.8369 0.1644 84.4286 / 0.1451)",
      error: "oklch(0.6585 0.168 13.5147)",
      "error-muted": "oklch(0.7192 0.169 13.428 / 0.1451)",
      info: "oklch(0.6379 0.1431 254.7237)",
      "info-muted": "oklch(0.7137 0.1434 254.624 / 0.1451)",
      "gradient-start": "oklch(0.709 0.1592 293.5412)",
      "gradient-end": "oklch(0.7253 0.1752 349.7607)",
      glow: "oklch(0.709 0.1592 293.5412 / 0.3137)",
      highlight: { light: "oklch(0.9433 0.0284 294.5878)", dark: "oklch(0.6306 0.1991 289.7303 / 0.15)" },
    },
    typography: {
      "font-display": "'Vulf Sans', system-ui, sans-serif",
      "font-body": "'PP Pier Sans', system-ui, sans-serif",
      "font-mono": "'PP Fraktion Mono', ui-monospace, monospace",
      "size-xs": "0.75rem",
      "size-sm": "0.8125rem",
      "size-base": "0.9375rem",
      "size-lg": "1.0625rem",
      "size-xl": "1.1875rem",
      "size-2xl": "1.4375rem",
      "size-3xl": "1.75rem",
      "size-4xl": "2.25rem",
      "size-5xl": "3rem",
      "size-6xl": "3.75rem",
      "weight-normal": "400",
      "weight-medium": "500",
      "weight-semibold": "600",
      "weight-bold": "700",
      "weight-extrabold": "800",
      "leading-tight": "1.25",
      "leading-normal": "1.55",
      "leading-relaxed": "1.7",
      "leading-loose": "2",
      "tracking-tighter": "-0.04em",
      "tracking-tight": "-0.02em",
      "tracking-normal": "0em",
      "tracking-wide": "0.02em",
      "tracking-wider": "0.04em",
      "heading-weight": "400",
      "heading-tracking": "0em",
      "heading-transform": "none",
      "heading-family": "'Vulf Sans', system-ui, sans-serif",
    },
    spacing: {
      scale: [4, 8, 12, 16, 24, 32, 48, 64, 88, 112],
      unit: "px",
      "button-px": "24px",
      "button-py": "10px",
      "button-px-sm": "16px",
      "button-py-sm": "7px",
      "button-px-lg": "32px",
      "button-py-lg": "14px",
      "card-padding": "28px",
      "card-padding-sm": "16px",
      "card-padding-lg": "36px",
      "input-px": "12px",
      "input-py": "9px",
      "badge-px": "8px",
      "badge-py": "3px",
      "section-py": "6.5rem",
      "section-py-lg": "9.75rem",
      "navbar-height": "52px",
      "navbar-px": "32px",
      "footer-py": "52px",
      "modal-padding": "28px",
      "popover-padding": "16px",
      "tooltip-padding": "6px 12px",
      "table-cell-px": "16px",
      "table-cell-py": "10px",
    },
    layout: {
      "content-max": "1200px",
      "content-max-narrow": "720px",
      "content-max-wide": "1440px",
      "page-margin": "32px",
      "page-margin-sm": "16px",
      "page-margin-lg": "60px",
      gutter: "0px",
      "gutter-sm": "0px",
      "gutter-lg": "0px",
      "grid-columns": "12",
      "grid-gap": "28px",
      "bento-gap": "20px",
      "bento-radius": "16px",
      "bento-min-height": "208px",
      "section-gap": "26px",
      "sidebar-width": "272px",
      "sidebar-collapsed": "56px",
      "footer-columns": "4",
      "stack-gap": "16px",
      "stack-gap-sm": "8px",
      "stack-gap-lg": "24px",
      "prose-max": "65ch",
    },
    sigil: {
      "grid-cell": "52px",
      "cross-arm": "0px",
      "cross-stroke": "0px",
      "rail-gap": "0px",
      "card-radius": "16px",
      "gutter-pattern": "none",
      "margin-pattern": "none",
      "gutter-border": "none",
      "gutter-visible": false,
      "band-height": "52px",
      "divider-thickness-sm": "calc(var(--s-grid-cell) / 2)",
      "divider-thickness-md": "var(--s-grid-cell)",
      "divider-thickness-lg": "calc(2 * var(--s-grid-cell))",
      "divider-thickness-xl": "calc(3 * var(--s-grid-cell))",
    },
    radius: {
      none: "0px",
      sm: "4px",
      md: "8px",
      lg: "12px",
      xl: "16px",
      "2xl": "20px",
      full: "9999px",
      button: "12px",
      card: "16px",
      input: "8px",
      badge: "9999px",
      modal: "16px",
      popover: "12px",
      tooltip: "8px",
      image: "12px",
      bento: "16px",
    },
    shadows: {
      sm: "0 1px 3px rgb(0 0 0 / 0.2)",
      md: "0 2px 8px rgb(0 0 0 / 0.25)",
      lg: "0 4px 16px rgb(0 0 0 / 0.3)",
      xl: "0 8px 28px rgb(0 0 0 / 0.35)",
      "2xl": "0 20px 50px rgb(0 0 0 / 0.45)",
      glow: "0 0 28px #a78bfa44, 0 0 56px #a78bfa22",
      "glow-sm": "0 0 14px #a78bfa33",
      colored: "0 4px 20px -4px #a78bfa44",
      inner: "inset 0 2px 4px rgb(0 0 0 / 0.15)",
      card: "0 0 0 1px #2e264050, 0 0 20px #a78bfa12",
      button: "none",
      "button-hover": "0 0 20px #a78bfa44",
      dropdown: "0 8px 24px rgb(0 0 0 / 0.35)",
      modal: "0 24px 64px rgb(0 0 0 / 0.5), 0 0 40px #a78bfa15",
    },
    motion: {
      duration: { instant: "0ms", fast: "150ms", normal: "300ms", slow: "450ms", slower: "700ms", slowest: "1100ms" },
      easing: {
        default: "cubic-bezier(0.34, 1.56, 0.64, 1)",
        in: "cubic-bezier(0.55, 0, 1, 0.45)",
        out: "cubic-bezier(0, 0.55, 0.45, 1)",
        "in-out": "cubic-bezier(0.45, 0, 0.55, 1)",
        spring: "cubic-bezier(0.34, 1.56, 0.64, 1)",
        bounce: "cubic-bezier(0.68, -0.55, 0.27, 1.55)",
      },
      "enter-preset": "fadeUp",
      "exit-preset": "fadeOut",
      "hover-scale": "1.02",
      "press-scale": "0.97",
      "hover-lift": "-3px",
      "stagger-interval": "55ms",
      "stagger-interval-fast": "28ms",
    },
    borders: {
      width: { none: "0px", thin: "1px", medium: "1.5px", thick: "2px" },
      style: "solid",
      "card-border": "1px solid",
      "card-border-hover": "1px solid",
      "button-border": "1px solid",
      "input-border": "1px solid",
      "divider-style": "solid",
      "divider-width": "1px",
    },
    buttons: {
      "font-weight": "500",
      "text-transform": "none",
      "letter-spacing": "0.01em",
      "font-family": "'PP Pier Sans', system-ui, sans-serif",
      "border-width": "1px",
      "hover-effect": "glow",
      "active-scale": "0.97",
      "icon-gap": "8px",
      "min-width": "0px",
    },
    cards: {
      "border-style": "solid",
      "border-width": "1px",
      "hover-effect": "glow",
      "hover-border-color": "#a78bfa55",
      padding: "24px",
      "header-padding": "24px 24px 0",
      "footer-padding": "0 24px 24px",
      "title-size": "1.0625rem",
      "title-weight": "600",
      "description-size": "0.8125rem",
      outline: true,
      shadow: "md",
      background: "surface",
    },
    headings: {
      "h1-size": "2.25rem",
      "h1-weight": "700",
      "h1-tracking": "-0.025em",
      "h1-leading": "1.2",
      "h2-size": "1.75rem",
      "h2-weight": "600",
      "h2-tracking": "-0.02em",
      "h2-leading": "1.15",
      "h3-size": "1.4375rem",
      "h3-weight": "600",
      "h3-tracking": "0em",
      "h3-leading": "1.2",
      "h4-size": "1.1875rem",
      "h4-weight": "600",
      "h4-tracking": "0em",
      "h4-leading": "1.3",
      "display-size": "3.75rem",
      "display-weight": "800",
      "display-tracking": "-0.035em",
      "display-leading": "1.1",
    },
    navigation: {
      "navbar-height": "52px",
      "navbar-backdrop-blur": "24px",
      "navbar-border": "none",
      "navbar-bg-opacity": "0.7",
      "navbar-padding-x": "24px",
      "navbar-position": "sticky",
      "navbar-logo-height": "26px",
      "navbar-logo-gap": "10px",
      "navbar-item-gap": "24px",
      "navbar-item-padding-x": "14px",
      "navbar-item-padding-y": "6px",
      "navbar-item-size": "0.875rem",
      "navbar-shadow": "none",
      "navbar-height-scrolled": "48px",
      "navbar-mobile-breakpoint": "768px",
      "nav-link-weight": "500",
      "nav-link-size": "0.8125rem",
      "nav-link-hover": "background",
      "breadcrumb-separator": "/",
      "pagination-radius": "12px",
      "sidebar-width": "272px",
      "sidebar-item-radius": "12px",
      "sidebar-item-padding": "10px 14px",
    },
    backgrounds: {
      pattern: "none",
      "pattern-opacity": "0",
      "pattern-scale": "1",
      noise: true,
      "noise-opacity": "0.025",
      "gradient-angle": "180deg",
      "gradient-type": "radial",
      "hero-pattern": "radial-glow",
      "section-divider": "none",
    },
    code: {
      "font-family": "'PP Fraktion Mono', ui-monospace, monospace",
      "font-size": "0.8125rem",
      "line-height": "1.7",
      bg: "var(--s-surface-sunken)",
      border: "1px solid var(--s-border)",
      "border-radius": "12px",
      padding: "16px",
      "tab-size": "2",
      "selection-bg": "#a78bfa25",
      "comment-color": "var(--s-text-muted)",
      "keyword-color": "#a78bfa",
      "string-color": "#34d399",
      "number-color": "#fbbf24",
      "function-color": "#f472b6",
    },
    inputs: {
      height: "40px",
      "height-sm": "32px",
      "height-lg": "48px",
      "border-width": "1px",
      "focus-ring-width": "2px",
      "focus-ring-color": "#a78bfa",
      "focus-ring-offset": "2px",
      "placeholder-color": "var(--s-text-subtle)",
      "error-border-color": "var(--s-error)",
      "label-size": "0.8125rem",
      "label-weight": "500",
      "label-spacing": "6px",
      "helper-size": "0.75rem",
    },
    alignment: {
      "title-align": "center",
      "rail-margin": "36px",
    },
    sections: {
      "padding-y": "6.5rem",
      "padding-y-hero": "9.75rem",
      "padding-y-sm": "3.25rem",
      gap: "40px",
      "padding-y-lg": "9.75rem",
      "padding-y-xl": "13rem",
      "title-align": "center",
      "heading-size": "clamp(1.5rem, 4vw, 2.5rem)",
      "heading-align": "center",
      "heading-max-width": "40rem",
      "heading-margin-bottom": "16px",
      "description-max-width": "32rem",
      "description-gap": "12px",
      "content-gap": "24px",
      "grid-columns": "3",
      "grid-gap": "24px",
      "alternate-bg": "var(--s-surface)",
      "alternate-bg-mode": "surface",
    },
    dividers: {
      style: "none",
      spacing: "0px",
      opacity: "0.8",
      "max-width": "100%",
      "margin-y": "0px",
      thickness: "1px",
      "gradient-start": "var(--s-primary)",
      "gradient-end": "var(--s-secondary)",
    },
    gridVisuals: {
      "line-color": "var(--s-border-muted)",
      "line-width": "1px",
      "show-dots": true,
      "dot-size": "2px",
      "cell-radius": "12px",
    },
    cursor: {
      variant: "ring",
      size: "24px",
      "dot-size": "4px",
      "stroke-width": "1.5px",
      "tick-size": "6px",
      gap: "3px",
      radius: "0px",
      color: "var(--s-text)",
      "ring-color": "var(--s-primary)",
      "dot-color": "var(--s-primary)",
      glow: "none",
      opacity: "1",
      "blend-mode": "normal",
      "z-index": "9999",
      "hide-native": false,
    },
    scrollbar: {
      width: "8px",
      height: "8px",
      padding: "2px",
      radius: "9999px",
      track: "transparent",
      thumb: "var(--s-border-muted)",
      "thumb-hover": "var(--s-border)",
      "thumb-active": "var(--s-border-strong)",
      corner: "transparent",
      border: "none",
      "firefox-width": "thin",
      gutter: "stable",
      visibility: "auto",
    },
    focus: {
      "ring-width": "2px",
      "ring-color": "var(--s-primary)",
      "ring-offset": "2px",
      "ring-shadow": "0 0 0 2px var(--s-primary)",
      "outline-color": "var(--s-primary)",
    },
    overlays: {
      bg: "rgb(0 0 0 / 0.5)",
      blur: "8px",
      surface: "var(--s-surface-elevated)",
      border: "1px solid var(--s-border-muted)",
      shadow: "var(--s-shadow-xl)",
      radius: "var(--s-radius-lg)",
      padding: "20px",
      "z-index": "50",
    },
    dataViz: {
      "series-1": "var(--s-primary)",
      "series-2": "var(--s-secondary)",
      "series-3": "var(--s-accent)",
      "series-4": "var(--s-info)",
      "series-5": "var(--s-success)",
      positive: "var(--s-success)",
      negative: "var(--s-error)",
      neutral: "var(--s-text-muted)",
      grid: "var(--s-border-muted)",
      axis: "var(--s-border)",
      label: "var(--s-text-secondary)",
      "tooltip-bg": "var(--s-surface-elevated)",
      "tooltip-border": "var(--s-border-muted)",
    },
    media: {
      radius: "var(--s-radius-md)",
      border: "none",
      outline: "1px solid rgb(0 0 0 / 0.08)",
      shadow: "none",
      bg: "var(--s-surface-sunken)",
      "object-fit": "cover",
    },
    controls: {
      height: "38px",
      "height-sm": "30px",
      "height-lg": "46px",
      "hit-area": "44px",
      "icon-size": "16px",
      "handle-size": "20px",
      "track-height": "4px",
      "track-bg": "var(--s-border-muted)",
      "track-fill": "var(--s-primary)",
      "thumb-bg": "var(--s-surface-elevated)",
      "thumb-border": "2px solid var(--s-primary)",
    },
    componentSurfaces: {
      bg: "var(--s-surface)",
      "bg-elevated": "var(--s-surface-elevated)",
      "bg-muted": "var(--s-surface-sunken)",
      border: "var(--s-border)",
      "border-muted": "var(--s-border-muted)",
      "border-strong": "var(--s-border-strong)",
      text: "var(--s-text)",
      "text-muted": "var(--s-text-muted)",
      contrast: "var(--s-primary-contrast)",
      "hover-bg": "var(--s-surface-elevated)",
      "active-bg": "var(--s-surface-sunken)",
      "selected-bg": "var(--s-primary-muted)",
    },
    hero: {
      "min-height": "auto",
      "padding-y": "104px",
      "padding-y-sm": "52px",
      "padding-x": "var(--s-page-margin, 24px)",
      "content-max": "640px",
      "content-basis": "min(42%, var(--s-hero-content-max, 640px))",
      "content-align": "center",
      layout: "centered",
      "media-position": "below",
      "media-width": "50%",
      "media-radius": "var(--s-radius-xl)",
      "split-gap": "var(--s-section-subsection-gap, var(--s-grid-cell))",
      "title-size": "clamp(2.25rem, 6vw, 4.5rem)",
      "title-max-width": "56rem",
      "description-size": "1.125rem",
      "description-max-width": "32rem",
      "description-gap": "24px",
      "actions-gap": "14px",
      "actions-margin-top": "32px",
      "action-padding-x": "28px",
      "action-padding-y": "12px",
      "badge-gap": "24px",
      "overlay-opacity": "0.4",
      "scroll-indicator": false,
      "gradient-overlay": "none",
    },
    cta: {
      "padding-y": "78px",
      "padding-x": "var(--s-page-margin, 24px)",
      "max-width": "var(--s-content-max, 1200px)",
      layout: "centered",
      border: true,
      "border-radius": "var(--s-radius-xl)",
      bg: "var(--s-surface)",
      "title-size": "clamp(1.5rem, 4vw, 2.5rem)",
      "description-max-width": "32rem",
      "description-gap": "12px",
      "actions-gap": "14px",
      "actions-margin-top": "32px",
      "action-padding-x": "28px",
      "action-padding-y": "12px",
      "split-gap": "52px",
    },
    footer: {
      "padding-y": "52px",
      "border-top": "1px solid var(--s-border)",
      columns: "4",
      "column-gap": "32px",
      "row-gap": "28px",
      "logo-height": "24px",
      "tagline-max-width": "20rem",
      "link-size": "0.875rem",
      "link-gap": "8px",
      "group-title-size": "0.875rem",
      "group-title-weight": "600",
      "social-icon-size": "20px",
      "social-gap": "12px",
      "bottom-bar-padding": "26px 0",
      "bottom-bar-border": "1px solid var(--s-border-muted)",
    },
    banner: {
      height: "auto",
      "padding-y": "8px",
      "padding-x": "16px",
      "font-size": "0.875rem",
      "font-weight": "500",
      "icon-size": "16px",
      "icon-gap": "12px",
      "border-width": "1px",
      "border-position": "bottom",
      position: "top",
      "dismiss-size": "16px",
      radius: "0px",
    },
    pageRhythm: {
      mode: "locked",
      snap: true,
      "band-stroke": "visual",
      "hairline-width": "1px",
      "hairline-spacing": "var(--s-section-gap, 0px)",
      "hairline-style": "solid",
      density: "normal",
      "section-gap": "0px",
      "section-gap-sm": "0px",
      "section-gap-lg": "0px",
      "first-section-offset": "0px",
      "last-section-margin": "0px",
      "alternate-bg": true,
      "alternate-bg-color": "var(--s-surface)",
      "divider-between": false,
      "max-content-width": "var(--s-content-max, 1200px)",
      "vertical-rhythm-unit": "4px",
      "scroll-snap": false,
      "responsive-scale": "0.9",
      "responsive-breakpoint": "768px",
    },

  },
});
