import type { SigilPreset } from "@sigil-ui/tokens";

export const duskPreset: SigilPreset = {
  name: "dusk",
  metadata: {
    description:
      "Twilight atmosphere. Purple haze gradients, atmospheric glow, and spring-eased motion.",
    mood: "twilight, atmospheric, haze",
    tags: ["dark", "twilight", "purple", "gradient", "atmospheric"],
  },
  tokens: {
    colors: {
      background: { light: "#f5f3ff", dark: "#1a1625" },
      surface: { light: "#ede9fe", dark: "#221d30" },
      "surface-elevated": { light: "#ffffff", dark: "#2b253d" },
      "surface-sunken": { light: "#e8e4fc", dark: "#13101d" },
      primary: "#8b6cf7",
      "primary-hover": "#8b5cf6",
      "primary-muted": "#a78bfa30",
      "primary-contrast": "#1a1625",
      secondary: "#818cf8",
      "secondary-hover": "#6366f1",
      "secondary-muted": "#818cf825",
      accent: "#f472b6",
      "accent-hover": "#ec4899",
      "accent-muted": "#f472b625",
      text: { light: "#1e1b2e", dark: "#e4e0f0" },
      "text-secondary": { light: "#3f3862", dark: "#c4b8e0" },
      "text-muted": { light: "#6b5fa0", dark: "#9b92b8" },
      "text-subtle": { light: "#8b80b5", dark: "#8878a5" },
      "text-disabled": { light: "#b8a8d3", dark: "#4a3d60" },
      "text-inverse": { light: "#e4e0f0", dark: "#1e1b2e" },
      border: { light: "#8d87ab", dark: "#6b6188" },
      "border-muted": { light: "#ede9fe", dark: "#352d4a" },
      "border-strong": { light: "#9181c6", dark: "#6a608f" },
      "border-interactive": { light: "#a78bfa", dark: "#a78bfa" },
      success: "#009f69",
      "success-muted": "#34d39925",
      warning: "#ba8000",
      "warning-muted": "#fbbf2425",
      error: "#e55e73",
      "error-muted": "#fb718525",
      info: "#498de0",
      "info-muted": "#60a5fa25",
      "gradient-start": "#a78bfa",
      "gradient-end": "#f472b6",
      glow: "#a78bfa50",
    },
    typography: {
      "font-display": "'Vulf Sans', system-ui, sans-serif",
      "font-body": "'PP Pier Sans', system-ui, sans-serif",
      "font-mono": "'PP Fraktion Mono', ui-monospace, monospace",
      "size-xs": "0.75rem",
      "size-sm": "0.8125rem",
      "size-base": "0.9375rem",
      "size-lg": "1.0625rem",
      "size-xl": "1.1875rem",
      "size-2xl": "1.4375rem",
      "size-3xl": "1.75rem",
      "size-4xl": "2.25rem",
      "size-5xl": "3rem",
      "size-6xl": "3.75rem",
      "weight-normal": "400",
      "weight-medium": "500",
      "weight-semibold": "600",
      "weight-bold": "700",
      "weight-extrabold": "800",
      "leading-tight": "1.25",
      "leading-normal": "1.55",
      "leading-relaxed": "1.7",
      "leading-loose": "2",
      "tracking-tighter": "-0.04em",
      "tracking-tight": "-0.02em",
      "tracking-normal": "0em",
      "tracking-wide": "0.02em",
      "tracking-wider": "0.04em",
      "heading-weight": "400",
      "heading-tracking": "0em",
      "heading-transform": "none",
      "heading-family": "'Vulf Sans', system-ui, sans-serif",
    },
    spacing: {
      scale: [4, 8, 12, 16, 24, 32, 48, 64, 88, 112],
      unit: "px",
      "button-px": "24px",
      "button-py": "10px",
      "button-px-sm": "16px",
      "button-py-sm": "7px",
      "button-px-lg": "32px",
      "button-py-lg": "14px",
      "card-padding": "28px",
      "card-padding-sm": "16px",
      "card-padding-lg": "36px",
      "input-px": "12px",
      "input-py": "9px",
      "badge-px": "8px",
      "badge-py": "3px",
      "section-py": "84px",
      "section-py-lg": "128px",
      "navbar-height": "68px",
      "navbar-px": "32px",
      "footer-py": "60px",
      "modal-padding": "28px",
      "popover-padding": "16px",
      "tooltip-padding": "6px 12px",
      "table-cell-px": "16px",
      "table-cell-py": "10px",
    },
    layout: {
      "content-max": "1200px",
      "content-max-narrow": "720px",
      "content-max-wide": "1440px",
      "page-margin": "32px",
      "page-margin-sm": "16px",
      "page-margin-lg": "60px",
      gutter: "0px",
      "gutter-sm": "0px",
      "gutter-lg": "0px",
      "grid-columns": "12",
      "grid-gap": "28px",
      "bento-gap": "20px",
      "bento-radius": "16px",
      "bento-min-height": "200px",
      "section-gap": "36px",
      "sidebar-width": "272px",
      "sidebar-collapsed": "56px",
      "footer-columns": "4",
      "stack-gap": "16px",
      "stack-gap-sm": "8px",
      "stack-gap-lg": "24px",
      "prose-max": "65ch",
    },
    sigil: {
      "grid-cell": "52px",
      "cross-arm": "0px",
      "cross-stroke": "0px",
      "rail-gap": "0px",
      "card-radius": "16px",
      "gutter-pattern": "none",
      "margin-pattern": "none",
      "gutter-border": "none",
      "gutter-visible": false,
    },
    radius: {
      none: "0px",
      sm: "4px",
      md: "8px",
      lg: "12px",
      xl: "16px",
      "2xl": "20px",
      full: "9999px",
      button: "12px",
      card: "16px",
      input: "8px",
      badge: "9999px",
      modal: "16px",
      popover: "12px",
      tooltip: "8px",
      image: "12px",
      bento: "16px",
    },
    shadows: {
      sm: "0 1px 3px rgb(0 0 0 / 0.2)",
      md: "0 2px 8px rgb(0 0 0 / 0.25)",
      lg: "0 4px 16px rgb(0 0 0 / 0.3)",
      xl: "0 8px 28px rgb(0 0 0 / 0.35)",
      "2xl": "0 20px 50px rgb(0 0 0 / 0.45)",
      glow: "0 0 28px #a78bfa44, 0 0 56px #a78bfa22",
      "glow-sm": "0 0 14px #a78bfa33",
      colored: "0 4px 20px -4px #a78bfa44",
      inner: "inset 0 2px 4px rgb(0 0 0 / 0.15)",
      card: "0 0 0 1px #2e264050, 0 0 20px #a78bfa12",
      button: "none",
      "button-hover": "0 0 20px #a78bfa44",
      dropdown: "0 8px 24px rgb(0 0 0 / 0.35)",
      modal: "0 24px 64px rgb(0 0 0 / 0.5), 0 0 40px #a78bfa15",
    },
    motion: {
      duration: { instant: "0ms", fast: "150ms", normal: "300ms", slow: "450ms", slower: "700ms", slowest: "1100ms" },
      easing: {
        default: "cubic-bezier(0.34, 1.56, 0.64, 1)",
        in: "cubic-bezier(0.55, 0, 1, 0.45)",
        out: "cubic-bezier(0, 0.55, 0.45, 1)",
        "in-out": "cubic-bezier(0.45, 0, 0.55, 1)",
        spring: "cubic-bezier(0.34, 1.56, 0.64, 1)",
        bounce: "cubic-bezier(0.68, -0.55, 0.27, 1.55)",
      },
      "enter-preset": "fadeUp",
      "exit-preset": "fadeOut",
      "hover-scale": "1.02",
      "press-scale": "0.97",
      "hover-lift": "-3px",
      "stagger-interval": "55ms",
      "stagger-interval-fast": "28ms",
    },
    borders: {
      width: { none: "0px", thin: "1px", medium: "1.5px", thick: "2px" },
      style: "solid",
      "card-border": "1px solid",
      "card-border-hover": "1px solid",
      "button-border": "1px solid",
      "input-border": "1px solid",
      "divider-style": "solid",
      "divider-width": "1px",
    },
    buttons: {
      "font-weight": "500",
      "text-transform": "none",
      "letter-spacing": "0.01em",
      "font-family": "'PP Pier Sans', system-ui, sans-serif",
      "border-width": "1px",
      "hover-effect": "glow",
      "active-scale": "0.97",
      "icon-gap": "8px",
      "min-width": "0px",
    },
    cards: {
      "border-style": "solid",
      "border-width": "1px",
      "hover-effect": "glow",
      "hover-border-color": "#a78bfa55",
      padding: "24px",
      "header-padding": "24px 24px 0",
      "footer-padding": "0 24px 24px",
      "title-size": "1.0625rem",
      "title-weight": "600",
      "description-size": "0.8125rem",
      outline: true,
      shadow: "md",
      background: "surface",
    },
    headings: {
      "h1-size": "2.25rem",
      "h1-weight": "700",
      "h1-tracking": "-0.025em",
      "h1-leading": "1.2",
      "h2-size": "1.75rem",
      "h2-weight": "600",
      "h2-tracking": "-0.02em",
      "h3-size": "1.4375rem",
      "h3-weight": "600",
      "h4-size": "1.1875rem",
      "h4-weight": "600",
      "display-size": "3.75rem",
      "display-weight": "800",
      "display-tracking": "-0.035em",
      "display-leading": "1.1",
    },
    navigation: {
      "navbar-height": "68px",
      "navbar-backdrop-blur": "24px",
      "navbar-border": "none",
      "navbar-bg-opacity": "0.7",
      "nav-link-weight": "500",
      "nav-link-size": "0.8125rem",
      "nav-link-hover": "background",
      "breadcrumb-separator": "/",
      "pagination-radius": "12px",
      "sidebar-width": "272px",
      "sidebar-item-radius": "12px",
      "sidebar-item-padding": "10px 14px",
    },
    backgrounds: {
      pattern: "none",
      "pattern-opacity": "0",
      "pattern-scale": "1",
      noise: true,
      "noise-opacity": "0.025",
      "gradient-angle": "180deg",
      "gradient-type": "radial",
      "hero-pattern": "radial-glow",
      "section-divider": "none",
    },
    code: {
      "font-family": "'PP Fraktion Mono', ui-monospace, monospace",
      "font-size": "0.8125rem",
      "line-height": "1.7",
      bg: "var(--s-surface-sunken)",
      border: "1px solid var(--s-border)",
      "border-radius": "12px",
      padding: "16px",
      "tab-size": "2",
      "selection-bg": "#a78bfa25",
      "comment-color": "var(--s-text-muted)",
      "keyword-color": "#a78bfa",
      "string-color": "#34d399",
      "number-color": "#fbbf24",
      "function-color": "#f472b6",
    },
    inputs: {
      height: "40px",
      "height-sm": "32px",
      "height-lg": "48px",
      "border-width": "1px",
      "focus-ring-width": "2px",
      "focus-ring-color": "#a78bfa",
      "focus-ring-offset": "2px",
      "placeholder-color": "var(--s-text-subtle)",
      "error-border-color": "var(--s-error)",
      "label-size": "0.8125rem",
      "label-weight": "500",
      "label-spacing": "6px",
      "helper-size": "0.75rem",
    },
    alignment: {
      "title-align": "center",
      "rail-margin": "36px",
    },
    sections: {
      "padding-y": "80px",
      "padding-y-hero": "160px",
      gap: "40px",
    },
    dividers: {
      style: "none",
    },
    gridVisuals: {
      "show-dots": true,
      "dot-size": "2px",
      "cell-radius": "12px",
    },
  },
};
