import type { SigilPreset } from "@sigil-ui/tokens";

export const etchPreset: SigilPreset = {
  name: "etch",
  metadata: {
    description: "Engraved precision — fine etched lines, intaglio print aesthetic",
    author: "sigil-ui",
    version: "0.1.0",
    tags: ["light", "print", "editorial", "precise"],
    mood: "etched, precise, print-like",
    inspiration: "Copperplate engraving, letterpress, intaglio prints",
  },
  tokens: {
    colors: {
      background: { light: "#faf8f5", dark: "#1c1b19" },
      surface: { light: "#f5f2ee", dark: "#23221f" },
      "surface-elevated": { light: "#ffffff", dark: "#2a2926" },
      "surface-sunken": { light: "#efecea", dark: "#161513" },
      text: { light: "#2c2a27", dark: "#e8e5e0" },
      "text-secondary": { light: "#4a4740", dark: "#b5b0a8" },
      "text-muted": { light: "#6b6760", dark: "#8a857d" },
      "text-subtle": { light: "#908b83", dark: "#6b6760" },
      "text-disabled": { light: "#b5b0a8", dark: "#4a4740" },
      "text-inverse": { light: "#faf8f5", dark: "#2c2a27" },
      border: { light: "#ddd9d3", dark: "#3a3835" },
      "border-muted": { light: "#e8e5e0", dark: "#2e2d2a" },
      "border-strong": { light: "#b5b0a8", dark: "#5a5650" },
      "border-interactive": { light: "#15803d", dark: "#22c55e" },
      primary: "#15803d",
      "primary-hover": "#166534",
      "primary-muted": "#dcfce7",
      "primary-contrast": "#ffffff",
      secondary: "#78716c",
      "secondary-hover": "#57534e",
      "secondary-muted": "#e7e5e4",
      accent: "#a16207",
      "accent-hover": "#854d0e",
      "accent-muted": "#fef3c7",
      success: "#15803d",
      "success-muted": "#dcfce7",
      warning: "#a16207",
      "warning-muted": "#fef3c7",
      error: "#b91c1c",
      "error-muted": "#fee2e2",
      info: "#0369a1",
      "info-muted": "#e0f2fe",
      "gradient-start": "#15803d",
      "gradient-end": "#a16207",
      glow: "rgba(21, 128, 61, 0.15)",
    },
    typography: {
      "font-display": "'Apfel Grotezk', system-ui, sans-serif",
      "font-body": "'Apfel Grotezk', system-ui, sans-serif",
      "font-mono": "'PP Fraktion Mono', ui-monospace, monospace",
      "size-xs": "0.75rem",
      "size-sm": "0.8125rem",
      "size-base": "0.9375rem",
      "size-lg": "1.0625rem",
      "size-xl": "1.1875rem",
      "size-2xl": "1.375rem",
      "size-3xl": "1.625rem",
      "size-4xl": "2rem",
      "size-5xl": "2.5rem",
      "size-6xl": "3.25rem",
      "weight-normal": "400",
      "weight-medium": "500",
      "weight-semibold": "600",
      "weight-bold": "700",
      "weight-extrabold": "800",
      "leading-tight": "1.2",
      "leading-normal": "1.5",
      "leading-relaxed": "1.65",
      "leading-loose": "1.8",
      "tracking-tighter": "-0.03em",
      "tracking-tight": "-0.015em",
      "tracking-normal": "0em",
      "tracking-wide": "0.025em",
      "tracking-wider": "0.05em",
      "heading-weight": "400",
      "heading-tracking": "0.01em",
      "heading-transform": "none",
      "heading-family": "'Apfel Grotezk', system-ui, sans-serif",
    },
    spacing: {
      scale: [4, 8, 12, 16, 24, 32, 48, 64, 80, 96],
      unit: "px",
      "button-px": "20px",
      "button-py": "10px",
      "button-px-sm": "14px",
      "button-py-sm": "6px",
      "button-px-lg": "28px",
      "button-py-lg": "14px",
      "card-padding": "28px",
      "card-padding-sm": "20px",
      "card-padding-lg": "36px",
      "input-px": "14px",
      "input-py": "10px",
      "badge-px": "10px",
      "badge-py": "3px",
      "section-py": "64px",
      "section-py-lg": "96px",
      "navbar-height": "56px",
      "navbar-px": "24px",
      "footer-py": "48px",
      "modal-padding": "28px",
      "popover-padding": "16px",
      "tooltip-padding": "8px 12px",
      "table-cell-px": "16px",
      "table-cell-py": "10px",
    },
    layout: {
      "content-max": "1120px",
      "content-max-narrow": "680px",
      "content-max-wide": "1400px",
      "page-margin": "24px",
      "page-margin-sm": "16px",
      "page-margin-lg": "48px",
      gutter: "24px",
      "gutter-sm": "16px",
      "gutter-lg": "32px",
      "grid-columns": "12",
      "grid-gap": "24px",
      "bento-gap": "16px",
      "bento-radius": "6px",
      "bento-min-height": "200px",
      "section-gap": "48px",
      "sidebar-width": "260px",
      "sidebar-collapsed": "64px",
      "footer-columns": "4",
      "stack-gap": "16px",
      "stack-gap-sm": "8px",
      "stack-gap-lg": "24px",
      "prose-max": "65ch",
    },
    sigil: {
      "grid-cell": "40px",
      "cross-arm": "8px",
      "cross-stroke": "0.5px",
      "rail-gap": "20px",
      "card-radius": "4px",
    },
    radius: {
      none: "0px",
      sm: "2px",
      md: "4px",
      lg: "6px",
      xl: "8px",
      "2xl": "10px",
      full: "9999px",
      button: "4px",
      card: "4px",
      input: "4px",
      badge: "2px",
      modal: "6px",
      popover: "4px",
      tooltip: "2px",
      image: "4px",
      bento: "6px",
    },
    shadows: {
      sm: "0 1px 1px rgba(44, 42, 39, 0.03)",
      md: "0 1px 2px rgba(44, 42, 39, 0.04)",
      lg: "0 2px 4px rgba(44, 42, 39, 0.05)",
      xl: "0 4px 8px rgba(44, 42, 39, 0.06)",
      "2xl": "0 8px 16px rgba(44, 42, 39, 0.07)",
      glow: "0 0 16px rgba(21, 128, 61, 0.12)",
      "glow-sm": "0 0 8px rgba(21, 128, 61, 0.08)",
      colored: "0 2px 8px rgba(21, 128, 61, 0.1)",
      inner: "inset 0 1px 2px rgba(44, 42, 39, 0.05)",
      card: "none",
      button: "none",
      "button-hover": "0 1px 2px rgba(44, 42, 39, 0.06)",
      dropdown: "0 2px 6px rgba(44, 42, 39, 0.08)",
      modal: "0 4px 16px rgba(44, 42, 39, 0.1)",
    },
    motion: {
      duration: {
        instant: "0ms",
        fast: "120ms",
        normal: "200ms",
        slow: "350ms",
        slower: "500ms",
        slowest: "700ms",
      },
      easing: {
        default: "cubic-bezier(0.25, 0.1, 0.25, 1)",
        in: "cubic-bezier(0.42, 0, 1, 1)",
        out: "cubic-bezier(0, 0, 0.58, 1)",
        "in-out": "cubic-bezier(0.42, 0, 0.58, 1)",
        spring: "cubic-bezier(0.34, 1.56, 0.64, 1)",
        bounce: "cubic-bezier(0.34, 1.4, 0.64, 1)",
      },
      "enter-preset": "200ms cubic-bezier(0.25, 0.1, 0.25, 1)",
      "exit-preset": "150ms cubic-bezier(0.42, 0, 1, 1)",
      "hover-scale": "1",
      "press-scale": "0.98",
      "hover-lift": "-1px",
      "stagger-interval": "50ms",
      "stagger-interval-fast": "30ms",
    },
    borders: {
      width: { none: "0px", thin: "0.5px", medium: "1px", thick: "1.5px" },
      style: "solid",
      "card-border": "0.5px dashed var(--s-border)",
      "card-border-hover": "0.5px dashed var(--s-border-strong)",
      "button-border": "0.5px solid var(--s-border)",
      "input-border": "0.5px solid var(--s-border)",
      "divider-style": "dashed",
      "divider-width": "0.5px",
    },
    buttons: {
      "font-weight": "500",
      "text-transform": "none",
      "letter-spacing": "0em",
      "font-family": "'Apfel Grotezk', system-ui, sans-serif",
      "border-width": "0.5px",
      "hover-effect": "outline",
      "active-scale": "0.98",
      "icon-gap": "8px",
      "min-width": "0px",
    },
    cards: {
      "border-style": "dashed",
      "border-width": "0.5px",
      "hover-effect": "none",
      "hover-border-color": "var(--s-border-strong)",
      padding: "28px",
      "header-padding": "28px 28px 0",
      "footer-padding": "0 28px 28px",
      "title-size": "var(--s-size-lg)",
      "title-weight": "500",
      "description-size": "var(--s-size-sm)",
      background: "transparent",
      shadow: "none",
      outline: true,
      "outline-on-hover-only": false,
      "gap-between": "16px",
      "content-padding-x": "28px",
      "content-padding-y": "20px",
    },
    headings: {
      "h1-size": "2.5rem",
      "h1-weight": "500",
      "h1-tracking": "-0.025em",
      "h1-leading": "1.15",
      "h2-size": "1.875rem",
      "h2-weight": "500",
      "h2-tracking": "-0.02em",
      "h3-size": "1.375rem",
      "h3-weight": "500",
      "h4-size": "1.125rem",
      "h4-weight": "500",
      "display-size": "3.25rem",
      "display-weight": "500",
      "display-tracking": "-0.03em",
      "display-leading": "1.08",
    },
    navigation: {
      "navbar-height": "56px",
      "navbar-backdrop-blur": "12px",
      "navbar-border": "0.5px solid var(--s-border-muted)",
      "navbar-bg-opacity": "0.85",
      "nav-link-weight": "450",
      "nav-link-size": "var(--s-size-sm)",
      "nav-link-hover": "color",
      "breadcrumb-separator": "/",
      "pagination-radius": "4px",
      "sidebar-width": "260px",
      "sidebar-item-radius": "4px",
      "sidebar-item-padding": "8px 12px",
    },
    backgrounds: {
      pattern: "grid",
      "pattern-opacity": "0.03",
      "pattern-scale": "40px",
      noise: false,
      "noise-opacity": "0",
      "gradient-angle": "180deg",
      "gradient-type": "none",
      "hero-pattern": "grid",
      "section-divider": "line",
    },
    code: {
      "font-family": "'PP Fraktion Mono', ui-monospace, monospace",
      "font-size": "0.8125rem",
      "line-height": "1.6",
      bg: "#f5f2ee",
      border: "0.5px solid #ddd9d3",
      "border-radius": "4px",
      padding: "20px 24px",
      "tab-size": "2",
      "selection-bg": "rgba(21, 128, 61, 0.12)",
      "comment-color": "#908b83",
      "keyword-color": "#15803d",
      "string-color": "#a16207",
      "number-color": "#b91c1c",
      "function-color": "#0369a1",
    },
    inputs: {
      height: "40px",
      "height-sm": "32px",
      "height-lg": "48px",
      "border-width": "0.5px",
      "focus-ring-width": "1.5px",
      "focus-ring-color": "var(--s-primary)",
      "focus-ring-offset": "1px",
      "placeholder-color": "var(--s-text-muted)",
      "error-border-color": "var(--s-error)",
      "label-size": "var(--s-size-sm)",
      "label-weight": "500",
      "label-spacing": "6px",
      "helper-size": "var(--s-size-xs)",
    },
    alignment: {
      "rail-width": "1120px",
      "rail-columns": "12",
      "rail-gutter": "24px",
      "rail-margin": "24px",
      "rail-visible": true,
      "rail-color": "var(--s-border-muted)",
      "content-align": "center",
      "hero-align": "center",
      "section-align": "center",
      "navbar-align": "full",
      "footer-align": "content",
    },
    sections: {
      "padding-y": "56px",
      "padding-y-hero": "96px",
      "padding-x": "24px",
      "max-width": "1120px",
      gap: "28px",
      "title-align": "left",
      "divider-above": false,
      "divider-below": true,
      "background-alt": false,
      indent: "0px",
    },
    dividers: {
      style: "dashed",
      width: "0.5px",
      color: "var(--s-border)",
      spacing: "0px",
      "show-cross": true,
      "show-label": false,
      "full-bleed": false,
      ornament: "cross",
    },
    gridVisuals: {
      "show-lines": true,
      "line-color": "var(--s-border-muted)",
      "line-width": "0.5px",
      "show-dots": true,
      "dot-size": "2px",
      "cell-background": "none",
      "cell-border": false,
      "cell-radius": "0px",
      "cell-padding": "16px",
      "hover-effect": "none",
    },
  },
};
