import type { SigilPreset } from "@sigil-ui/tokens";

export const fangPreset: SigilPreset = {
  name: "fang",
  metadata: {
    description: "Predatory sharp — aggressive, fast, dark with acid accents",
    author: "sigil-ui",
    version: "0.1.0",
    tags: ["dark", "aggressive", "fast", "sharp", "neon"],
    mood: "predatory, fast, razor-sharp",
    inspiration: "Stealth fighters, acid house, cyberpunk terminals",
  },
  tokens: {
    colors: {
      background: { light: "#f8f8f8", dark: "#000000" },
      surface: { light: "#f0f0f0", dark: "#0a0a0a" },
      "surface-elevated": { light: "#ffffff", dark: "#141414" },
      "surface-sunken": { light: "#e8e8e8", dark: "#000000" },
      text: { light: "#0a0a0a", dark: "#ffffff" },
      "text-secondary": { light: "#333333", dark: "#d4d4d4" },
      "text-muted": { light: "#666666", dark: "#737373" },
      "text-subtle": { light: "#999999", dark: "#525252" },
      "text-disabled": { light: "#bbbbbb", dark: "#404040" },
      "text-inverse": { light: "#ffffff", dark: "#000000" },
      border: { light: "#e0e0e0", dark: "#1a1a1a" },
      "border-muted": { light: "#f0f0f0", dark: "#111111" },
      "border-strong": { light: "#333333", dark: "#333333" },
      "border-interactive": { light: "#84cc16", dark: "#84cc16" },
      primary: "#84cc16",
      "primary-hover": "#a3e635",
      "primary-muted": "#1a2e05",
      "primary-contrast": "#000000",
      secondary: "#ef4444",
      "secondary-hover": "#f87171",
      "secondary-muted": "#2a0a0a",
      accent: "#84cc16",
      "accent-hover": "#a3e635",
      "accent-muted": "#1a2e05",
      success: "#22c55e",
      "success-muted": "#052e16",
      warning: "#eab308",
      "warning-muted": "#2e2204",
      error: "#ef4444",
      "error-muted": "#2a0a0a",
      info: "#3b82f6",
      "info-muted": "#0a1a2e",
      "gradient-start": "#84cc16",
      "gradient-end": "#ef4444",
      glow: "rgba(132, 204, 22, 0.35)",
    },
    typography: {
      "font-display": "'PP Mondwest', system-ui, sans-serif",
      "font-body": "'PP Radio Grotesk', system-ui, sans-serif",
      "font-mono": "'PP Supply Mono', ui-monospace, monospace",
      "size-xs": "0.6875rem",
      "size-sm": "0.75rem",
      "size-base": "0.875rem",
      "size-lg": "1rem",
      "size-xl": "1.125rem",
      "size-2xl": "1.375rem",
      "size-3xl": "1.75rem",
      "size-4xl": "2.25rem",
      "size-5xl": "3rem",
      "size-6xl": "4rem",
      "weight-normal": "400",
      "weight-medium": "500",
      "weight-semibold": "600",
      "weight-bold": "700",
      "weight-extrabold": "800",
      "leading-tight": "1.1",
      "leading-normal": "1.4",
      "leading-relaxed": "1.55",
      "leading-loose": "1.7",
      "tracking-tighter": "-0.04em",
      "tracking-tight": "-0.02em",
      "tracking-normal": "0em",
      "tracking-wide": "0.06em",
      "tracking-wider": "0.12em",
      "heading-weight": "700",
      "heading-tracking": "-0.03em",
      "heading-transform": "none",
      "heading-family": "'PP Mondwest', system-ui, sans-serif",
    },
    spacing: {
      scale: [2, 4, 6, 8, 12, 16, 20, 28, 40, 56],
      unit: "px",
      "button-px": "16px",
      "button-py": "8px",
      "button-px-sm": "10px",
      "button-py-sm": "5px",
      "button-px-lg": "24px",
      "button-py-lg": "12px",
      "card-padding": "16px",
      "card-padding-sm": "10px",
      "card-padding-lg": "24px",
      "input-px": "10px",
      "input-py": "6px",
      "badge-px": "8px",
      "badge-py": "2px",
      "section-py": "48px",
      "section-py-lg": "72px",
      "navbar-height": "48px",
      "navbar-px": "16px",
      "footer-py": "32px",
      "modal-padding": "20px",
      "popover-padding": "10px",
      "tooltip-padding": "4px 8px",
      "table-cell-px": "10px",
      "table-cell-py": "6px",
    },
    layout: {
      "content-max": "1200px",
      "content-max-narrow": "640px",
      "content-max-wide": "1440px",
      "page-margin": "16px",
      "page-margin-sm": "10px",
      "page-margin-lg": "32px",
      gutter: "12px",
      "gutter-sm": "6px",
      "gutter-lg": "20px",
      "grid-columns": "12",
      "grid-gap": "12px",
      "bento-gap": "6px",
      "bento-radius": "0px",
      "bento-min-height": "160px",
      "section-gap": "32px",
      "sidebar-width": "220px",
      "sidebar-collapsed": "48px",
      "footer-columns": "4",
      "stack-gap": "10px",
      "stack-gap-sm": "4px",
      "stack-gap-lg": "16px",
      "prose-max": "60ch",
    },
    sigil: {
      "grid-cell": "40px",
      "cross-arm": "8px",
      "cross-stroke": "1px",
      "rail-gap": "12px",
      "card-radius": "0px",
    },
    radius: {
      none: "0px",
      sm: "0px",
      md: "0px",
      lg: "0px",
      xl: "0px",
      "2xl": "0px",
      full: "0px",
      button: "0px",
      card: "0px",
      input: "0px",
      badge: "0px",
      modal: "0px",
      popover: "0px",
      tooltip: "0px",
      image: "0px",
      bento: "0px",
    },
    shadows: {
      sm: "none",
      md: "none",
      lg: "none",
      xl: "none",
      "2xl": "none",
      glow: "0 0 24px rgba(132, 204, 22, 0.3)",
      "glow-sm": "0 0 12px rgba(132, 204, 22, 0.2)",
      colored: "0 0 16px rgba(132, 204, 22, 0.2)",
      inner: "inset 0 0 8px rgba(132, 204, 22, 0.05)",
      card: "0 0 8px rgba(132, 204, 22, 0.06)",
      button: "none",
      "button-hover": "0 0 16px rgba(132, 204, 22, 0.25)",
      dropdown: "0 0 12px rgba(0, 0, 0, 0.6)",
      modal: "0 0 40px rgba(0, 0, 0, 0.8)",
    },
    motion: {
      duration: {
        instant: "0ms",
        fast: "60ms",
        normal: "100ms",
        slow: "180ms",
        slower: "280ms",
        slowest: "400ms",
      },
      easing: {
        default: "cubic-bezier(0.16, 1, 0.3, 1)",
        in: "cubic-bezier(0.7, 0, 1, 0.5)",
        out: "cubic-bezier(0, 0.5, 0.3, 1)",
        "in-out": "cubic-bezier(0.7, 0, 0.3, 1)",
        spring: "cubic-bezier(0.22, 1.8, 0.36, 1)",
        bounce: "cubic-bezier(0.22, 2, 0.36, 1)",
      },
      "enter-preset": "100ms cubic-bezier(0.16, 1, 0.3, 1)",
      "exit-preset": "60ms cubic-bezier(0.7, 0, 1, 0.5)",
      "hover-scale": "1.03",
      "press-scale": "0.95",
      "hover-lift": "0px",
      "stagger-interval": "25ms",
      "stagger-interval-fast": "10ms",
    },
    borders: {
      width: { none: "0px", thin: "1px", medium: "1.5px", thick: "2px" },
      style: "solid",
      "card-border": "0px solid transparent",
      "card-border-hover": "0px solid transparent",
      "button-border": "0px solid transparent",
      "input-border": "1px solid var(--s-border)",
      "divider-style": "solid",
      "divider-width": "1px",
    },
    buttons: {
      "font-weight": "700",
      "text-transform": "uppercase",
      "letter-spacing": "0.1em",
      "font-family": "'PP Radio Grotesk', system-ui, sans-serif",
      "border-width": "0px",
      "hover-effect": "glow",
      "active-scale": "0.95",
      "icon-gap": "6px",
      "min-width": "0px",
    },
    cards: {
      "border-style": "solid",
      "border-width": "1px",
      "hover-effect": "border",
      "hover-border-color": "var(--s-primary)",
      padding: "16px",
      "header-padding": "16px 16px 0",
      "footer-padding": "0 16px 16px",
      "title-size": "var(--s-size-lg)",
      "title-weight": "700",
      "description-size": "var(--s-size-sm)",
      background: "surface",
      shadow: "none",
      outline: true,
      "outline-on-hover-only": false,
      "gap-between": "10px",
      "content-padding-x": "16px",
      "content-padding-y": "12px",
    },
    headings: {
      "h1-size": "3rem",
      "h1-weight": "700",
      "h1-tracking": "-0.04em",
      "h1-leading": "1.05",
      "h2-size": "2.25rem",
      "h2-weight": "700",
      "h2-tracking": "-0.03em",
      "h3-size": "1.5rem",
      "h3-weight": "600",
      "h4-size": "1.125rem",
      "h4-weight": "600",
      "display-size": "4.5rem",
      "display-weight": "800",
      "display-tracking": "-0.05em",
      "display-leading": "0.9",
    },
    navigation: {
      "navbar-height": "48px",
      "navbar-backdrop-blur": "0px",
      "navbar-border": "1px solid var(--s-border-muted)",
      "navbar-bg-opacity": "0.95",
      "nav-link-weight": "500",
      "nav-link-size": "var(--s-size-sm)",
      "nav-link-hover": "color",
      "breadcrumb-separator": "/",
      "pagination-radius": "0px",
      "sidebar-width": "220px",
      "sidebar-item-radius": "0px",
      "sidebar-item-padding": "6px 10px",
    },
    backgrounds: {
      pattern: "none",
      "pattern-opacity": "0",
      "pattern-scale": "0px",
      noise: false,
      "noise-opacity": "0",
      "gradient-angle": "180deg",
      "gradient-type": "none",
      "hero-pattern": "none",
      "section-divider": "none",
    },
    code: {
      "font-family": "'PP Supply Mono', ui-monospace, monospace",
      "font-size": "0.8125rem",
      "line-height": "1.5",
      bg: "#0a0a0a",
      border: "1px solid #262626",
      "border-radius": "0px",
      padding: "16px 20px",
      "tab-size": "2",
      "selection-bg": "rgba(132, 204, 22, 0.2)",
      "comment-color": "#555555",
      "keyword-color": "#84cc16",
      "string-color": "#a3e635",
      "number-color": "#ef4444",
      "function-color": "#3b82f6",
    },
    inputs: {
      height: "36px",
      "height-sm": "28px",
      "height-lg": "44px",
      "border-width": "1px",
      "focus-ring-width": "1px",
      "focus-ring-color": "var(--s-primary)",
      "focus-ring-offset": "0px",
      "placeholder-color": "var(--s-text-subtle)",
      "error-border-color": "var(--s-error)",
      "label-size": "var(--s-size-xs)",
      "label-weight": "600",
      "label-spacing": "4px",
      "helper-size": "var(--s-size-xs)",
    },
    alignment: {
      "title-align": "left",
    },
    sections: {
      "rail-margin": "8px",
      "padding-y": "36px",
      gap: "16px",
    },
    dividers: {
      style: "solid",
      width: "1px",
      "full-bleed": true,
    },
    gridVisuals: {
      "cell-border": true,
      "line-width": "1px",
    },
  },
};
