import type { SigilPreset } from "@sigil-ui/tokens";

export const fangPreset: SigilPreset = {
  name: "fang",
  metadata: {
    description: "Predatory sharp — aggressive, fast, dark with acid accents",
    author: "sigil-ui",
    version: "0.1.0",
    tags: ["dark", "aggressive", "fast", "sharp", "neon"],
    mood: "predatory, fast, razor-sharp",
    inspiration: "Stealth fighters, acid house, cyberpunk terminals",
  },
  tokens: {
    colors: {
      background: { light: "#f8f8f8", dark: "#000000" },
      surface: { light: "#f0f0f0", dark: "#0a0a0a" },
      "surface-elevated": { light: "#ffffff", dark: "#141414" },
      "surface-sunken": { light: "#e8e8e8", dark: "#000000" },
      text: { light: "#0a0a0a", dark: "#ffffff" },
      "text-secondary": { light: "#333333", dark: "#d4d4d4" },
      "text-muted": { light: "#666666", dark: "#858585" },
      "text-subtle": { light: "#8e8e8e", dark: "#666666" },
      "text-disabled": { light: "#bbbbbb", dark: "#404040" },
      "text-inverse": { light: "#ffffff", dark: "#000000" },
      border: { light: "#8e8e8e", dark: "oklch(0.220 0.006 0)" },
      "border-muted": { light: "#c4c4c4", dark: "oklch(0.160 0.006 0)" },
      "border-strong": { light: "#333333", dark: "oklch(0.300 0.006 0)" },
      "border-interactive": { light: "#84cc16", dark: "#84cc16" },
      primary: "#5a9f00",
      "primary-hover": "#a3e635",
      "primary-muted": "#1a2e05",
      "primary-contrast": "#000000",
      secondary: "#ef4444",
      "secondary-hover": "#f87171",
      "secondary-muted": "#2a0a0a",
      accent: "#84cc16",
      "accent-hover": "#a3e635",
      "accent-muted": "#1a2e05",
      success: "#00a43e",
      "success-muted": "#052e16",
      warning: "#b98400",
      "warning-muted": "#2e2204",
      error: "#ef4444",
      "error-muted": "#2a0a0a",
      info: "#3b82f6",
      "info-muted": "#0a1a2e",
      "gradient-start": "#84cc16",
      "gradient-end": "#ef4444",
      glow: "rgba(132, 204, 22, 0.35)",
      highlight: { light: "#ecfccb", dark: "rgba(132, 204, 22, 0.15)" },
    },
    typography: {
      "font-display": "'PP Mondwest', system-ui, sans-serif",
      "font-body": "'PP Radio Grotesk', system-ui, sans-serif",
      "font-mono": "'PP Supply Mono', ui-monospace, monospace",
      "size-xs": "0.6875rem",
      "size-sm": "0.75rem",
      "size-base": "0.875rem",
      "size-lg": "1rem",
      "size-xl": "1.125rem",
      "size-2xl": "1.375rem",
      "size-3xl": "1.75rem",
      "size-4xl": "2.25rem",
      "size-5xl": "3rem",
      "size-6xl": "4rem",
      "weight-normal": "400",
      "weight-medium": "500",
      "weight-semibold": "600",
      "weight-bold": "700",
      "weight-extrabold": "800",
      "leading-tight": "1.1",
      "leading-normal": "1.4",
      "leading-relaxed": "1.55",
      "leading-loose": "1.7",
      "tracking-tighter": "-0.04em",
      "tracking-tight": "-0.02em",
      "tracking-normal": "0em",
      "tracking-wide": "0.06em",
      "tracking-wider": "0.12em",
      "heading-weight": "700",
      "heading-tracking": "-0.03em",
      "heading-transform": "none",
      "heading-family": "'PP Mondwest', system-ui, sans-serif",
    },
    spacing: {
      scale: [2, 4, 6, 8, 12, 16, 20, 28, 40, 56],
      unit: "px",
      "button-px": "16px",
      "button-py": "8px",
      "button-px-sm": "10px",
      "button-py-sm": "5px",
      "button-px-lg": "24px",
      "button-py-lg": "12px",
      "card-padding": "12px",
      "card-padding-sm": "8px",
      "card-padding-lg": "20px",
      "input-px": "10px",
      "input-py": "6px",
      "badge-px": "8px",
      "badge-py": "2px",
      "section-py": "40px",
      "section-py-lg": "64px",
      "navbar-height": "40px",
      "navbar-px": "12px",
      "footer-py": "24px",
      "modal-padding": "20px",
      "popover-padding": "10px",
      "tooltip-padding": "4px 8px",
      "table-cell-px": "10px",
      "table-cell-py": "6px",
    },
    layout: {
      "content-max": "1200px",
      "content-max-narrow": "720px",
      "content-max-wide": "1440px",
      "page-margin": "12px",
      "page-margin-sm": "10px",
      "page-margin-lg": "24px",
      gutter: "8px",
      "gutter-sm": "4px",
      "gutter-lg": "16px",
      "grid-columns": "12",
      "grid-gap": "8px",
      "bento-gap": "4px",
      "bento-radius": "0px",
      "bento-min-height": "160px",
      "section-gap": "32px",
      "sidebar-width": "200px",
      "sidebar-collapsed": "48px",
      "footer-columns": "4",
      "stack-gap": "10px",
      "stack-gap-sm": "4px",
      "stack-gap-lg": "16px",
      "prose-max": "60ch",
    },
    sigil: {
      "grid-cell": "32px",
      "cross-arm": "10px",
      "cross-stroke": "2px",
      "rail-gap": "8px",
      "card-radius": "0px",
      "gutter-pattern": "zigzag",
      "margin-pattern": "crosshatch",
      "margin-border": "1px solid var(--s-border-muted)",
    },
    radius: {
      none: "0px",
      sm: "0px",
      md: "0px",
      lg: "0px",
      xl: "0px",
      "2xl": "0px",
      full: "0px",
      button: "0px",
      card: "0px",
      input: "0px",
      badge: "0px",
      modal: "0px",
      popover: "0px",
      tooltip: "0px",
      image: "0px",
      bento: "0px",
    },
    shadows: {
      sm: "0 1px 2px rgb(0 0 0 / 0.3)",
      md: "0 2px 6px rgb(0 0 0 / 0.4)",
      lg: "0 4px 12px rgb(0 0 0 / 0.5)",
      xl: "0 8px 24px rgb(0 0 0 / 0.6)",
      "2xl": "none",
      glow: "0 0 24px rgba(132, 204, 22, 0.3)",
      "glow-sm": "0 0 12px rgba(132, 204, 22, 0.2)",
      colored: "0 0 16px rgba(132, 204, 22, 0.2)",
      inner: "inset 0 0 8px rgba(132, 204, 22, 0.05)",
      card: "0 0 8px rgba(132, 204, 22, 0.06)",
      button: "none",
      "button-hover": "0 0 16px rgba(132, 204, 22, 0.25)",
      dropdown: "0 0 12px rgba(0, 0, 0, 0.6)",
      modal: "0 0 40px rgba(0, 0, 0, 0.8)",
    },
    motion: {
      duration: {
        instant: "0ms",
        fast: "60ms",
        normal: "100ms",
        slow: "180ms",
        slower: "280ms",
        slowest: "400ms",
      },
      easing: {
        default: "cubic-bezier(0.16, 1, 0.3, 1)",
        in: "cubic-bezier(0.7, 0, 1, 0.5)",
        out: "cubic-bezier(0, 0.5, 0.3, 1)",
        "in-out": "cubic-bezier(0.7, 0, 0.3, 1)",
        spring: "cubic-bezier(0.22, 1.8, 0.36, 1)",
        bounce: "cubic-bezier(0.22, 2, 0.36, 1)",
      },
      "enter-preset": "100ms cubic-bezier(0.16, 1, 0.3, 1)",
      "exit-preset": "60ms cubic-bezier(0.7, 0, 1, 0.5)",
      "hover-scale": "1.03",
      "press-scale": "0.95",
      "hover-lift": "0px",
      "stagger-interval": "25ms",
      "stagger-interval-fast": "10ms",
    },
    borders: {
      width: { none: "0px", thin: "1px", medium: "1.5px", thick: "2px" },
      style: "solid",
      "card-border": "0px solid transparent",
      "card-border-hover": "0px solid transparent",
      "button-border": "0px solid transparent",
      "input-border": "1px solid var(--s-border)",
      "divider-style": "solid",
      "divider-width": "1px",
    },
    buttons: {
      "font-weight": "700",
      "text-transform": "uppercase",
      "letter-spacing": "0.1em",
      "font-family": "'PP Radio Grotesk', system-ui, sans-serif",
      "border-width": "0px",
      "hover-effect": "glow",
      "active-scale": "0.95",
      "icon-gap": "6px",
      "min-width": "0px",
    },
    cards: {
      "border-style": "solid",
      "border-width": "1px",
      "hover-effect": "border",
      "hover-border-color": "var(--s-primary)",
      padding: "16px",
      "header-padding": "16px 16px 0",
      "footer-padding": "0 16px 16px",
      "title-size": "var(--s-size-lg)",
      "title-weight": "700",
      "description-size": "var(--s-size-sm)",
      background: "surface",
      shadow: "none",
      outline: true,
      "outline-on-hover-only": false,
      "gap-between": "10px",
      "content-padding-x": "16px",
      "content-padding-y": "12px",
    },
    headings: {
      "h1-size": "3rem",
      "h1-weight": "700",
      "h1-tracking": "-0.04em",
      "h1-leading": "1.05",
      "h2-size": "2.25rem",
      "h2-weight": "700",
      "h2-tracking": "-0.03em",
      "h3-size": "1.5rem",
      "h3-weight": "600",
      "h4-size": "1.125rem",
      "h4-weight": "600",
      "display-size": "4.5rem",
      "display-weight": "800",
      "display-tracking": "-0.05em",
      "display-leading": "0.9",
    },
    navigation: {
      "navbar-height": "40px",
      "navbar-backdrop-blur": "0px",
      "navbar-border": "2px solid",
      "navbar-bg-opacity": "1",
      "navbar-padding-x": "24px",
      "navbar-position": "sticky",
      "navbar-logo-height": "24px",
      "navbar-logo-gap": "10px",
      "navbar-item-gap": "24px",
      "navbar-item-padding-x": "12px",
      "navbar-item-padding-y": "6px",
      "navbar-item-size": "0.875rem",
      "navbar-shadow": "0 1px 3px rgb(0 0 0 / 0.3)",
      "navbar-height-scrolled": "48px",
      "navbar-mobile-breakpoint": "768px",
      "nav-link-weight": "700",
      "nav-link-size": "var(--s-size-sm)",
      "nav-link-hover": "none",
      "breadcrumb-separator": "/",
      "pagination-radius": "0px",
      "sidebar-width": "200px",
      "sidebar-item-radius": "0px",
      "sidebar-item-padding": "4px 8px",
    },
    backgrounds: {
      pattern: "crosshatch",
      "pattern-opacity": "0.06",
      "pattern-scale": "0px",
      noise: false,
      "noise-opacity": "0",
      "gradient-angle": "180deg",
      "gradient-type": "none",
      "hero-pattern": "crosshatch",
      "section-divider": "none",
    },
    code: {
      "font-family": "'PP Supply Mono', ui-monospace, monospace",
      "font-size": "0.8125rem",
      "line-height": "1.5",
      bg: "#0a0a0a",
      border: "1px solid #262626",
      "border-radius": "0px",
      padding: "16px 20px",
      "tab-size": "2",
      "selection-bg": "rgba(132, 204, 22, 0.2)",
      "comment-color": "#555555",
      "keyword-color": "#84cc16",
      "string-color": "#a3e635",
      "number-color": "#ef4444",
      "function-color": "#3b82f6",
    },
    inputs: {
      height: "36px",
      "height-sm": "28px",
      "height-lg": "44px",
      "border-width": "1px",
      "focus-ring-width": "1px",
      "focus-ring-color": "var(--s-primary)",
      "focus-ring-offset": "0px",
      "placeholder-color": "var(--s-text-subtle)",
      "error-border-color": "var(--s-error)",
      "label-size": "var(--s-size-xs)",
      "label-weight": "600",
      "label-spacing": "4px",
      "helper-size": "var(--s-size-xs)",
    },
    alignment: {
      "title-align": "left",
    },
    sections: {
      "rail-margin": "8px",
      "padding-y": "36px",
      "padding-y-sm": "48px",
      gap: "16px",
      "padding-y-lg": "96px",
      "padding-y-xl": "144px",
      "heading-size": "clamp(1.5rem, 4vw, 2.5rem)",
      "heading-align": "center",
      "heading-max-width": "40rem",
      "heading-margin-bottom": "16px",
      "description-max-width": "32rem",
      "description-gap": "14px",
      "content-gap": "24px",
      "grid-columns": "3",
      "grid-gap": "24px",
      "alternate-bg": "var(--s-surface-sunken)",
      "alternate-bg-mode": "sunken",
    },
    dividers: {
      style: "solid",
      width: "1px",
      "full-bleed": true,
      spacing: "0px",
      opacity: "0.5",
      "max-width": "100%",
      "margin-y": "0px",
      thickness: "1px",
      "gradient-start": "transparent",
      "gradient-end": "transparent",
    },
    gridVisuals: {
      "line-color": "var(--s-border-muted)",
      "cell-border": true,
      "line-width": "1px",
    },
    cursor: {
      variant: "ring",
      size: "24px",
      "dot-size": "4px",
      "stroke-width": "1.5px",
      "tick-size": "6px",
      gap: "3px",
      radius: "0px",
      color: "var(--s-text)",
      "ring-color": "var(--s-primary)",
      "dot-color": "var(--s-primary)",
      glow: "0 0 8px var(--s-primary)",
      opacity: "1",
      "blend-mode": "normal",
      "z-index": "9999",
      "hide-native": false,
    },
    scrollbar: {
      width: "8px",
      height: "8px",
      padding: "2px",
      radius: "9999px",
      track: "transparent",
      thumb: "var(--s-border-muted)",
      "thumb-hover": "var(--s-border)",
      "thumb-active": "var(--s-border-strong)",
      corner: "transparent",
      border: "none",
      "firefox-width": "thin",
      gutter: "stable",
      visibility: "auto",
    },
    focus: {
      "ring-width": "2px",
      "ring-color": "var(--s-primary)",
      "ring-offset": "0px",
      "ring-shadow": "0 0 0 2px var(--s-primary)",
      "outline-color": "var(--s-primary)",
    },
    overlays: {
      bg: "rgb(0 0 0 / 0.7)",
      blur: "12px",
      surface: "var(--s-surface-elevated)",
      border: "1px solid var(--s-border-muted)",
      shadow: "var(--s-shadow-xl)",
      radius: "var(--s-radius-lg)",
      padding: "20px",
      "z-index": "50",
    },
    dataViz: {
      "series-1": "var(--s-primary)",
      "series-2": "var(--s-secondary)",
      "series-3": "var(--s-accent)",
      "series-4": "var(--s-info)",
      "series-5": "var(--s-success)",
      positive: "var(--s-success)",
      negative: "var(--s-error)",
      neutral: "var(--s-text-muted)",
      grid: "var(--s-border-muted)",
      axis: "var(--s-border)",
      label: "var(--s-text-secondary)",
      "tooltip-bg": "var(--s-surface-elevated)",
      "tooltip-border": "var(--s-border-muted)",
    },
    media: {
      radius: "var(--s-radius-md)",
      border: "none",
      outline: "1px solid rgb(0 0 0 / 0.08)",
      shadow: "none",
      bg: "var(--s-surface-sunken)",
      "object-fit": "cover",
    },
    controls: {
      height: "38px",
      "height-sm": "30px",
      "height-lg": "46px",
      "hit-area": "44px",
      "icon-size": "16px",
      "handle-size": "20px",
      "track-height": "4px",
      "track-bg": "var(--s-border-muted)",
      "track-fill": "var(--s-primary)",
      "thumb-bg": "var(--s-surface-elevated)",
      "thumb-border": "2px solid var(--s-primary)",
    },
    componentSurfaces: {
      bg: "var(--s-surface)",
      "bg-elevated": "var(--s-surface-elevated)",
      "bg-muted": "var(--s-surface-sunken)",
      border: "var(--s-border)",
      "border-muted": "var(--s-border-muted)",
      "border-strong": "var(--s-border-strong)",
      text: "var(--s-text)",
      "text-muted": "var(--s-text-muted)",
      contrast: "var(--s-primary-contrast)",
      "hover-bg": "var(--s-surface-elevated)",
      "active-bg": "var(--s-surface-sunken)",
      "selected-bg": "var(--s-primary-muted)",
    },
    hero: {
      "min-height": "auto",
      "padding-y": "120px",
      "padding-y-sm": "72px",
      "padding-x": "var(--s-page-margin, 24px)",
      "content-max": "640px",
      "content-align": "center",
      layout: "centered",
      "media-position": "below",
      "media-width": "50%",
      "media-radius": "var(--s-radius-lg)",
      "title-size": "clamp(2.5rem, 6vw, 4.5rem)",
      "title-max-width": "56rem",
      "description-size": "1.125rem",
      "description-max-width": "32rem",
      "description-gap": "24px",
      "actions-gap": "12px",
      "actions-margin-top": "36px",
      "action-padding-x": "24px",
      "action-padding-y": "12px",
      "badge-gap": "24px",
      "overlay-opacity": "0.7",
      "scroll-indicator": false,
      "gradient-overlay": "linear-gradient(to bottom, transparent, var(--s-background))",
    },
    cta: {
      "padding-y": "96px",
      "padding-x": "var(--s-page-margin, 24px)",
      "max-width": "var(--s-content-max, 1200px)",
      layout: "centered",
      border: false,
      "border-radius": "var(--s-radius-lg)",
      bg: "var(--s-surface-elevated)",
      "title-size": "clamp(1.5rem, 4vw, 2.5rem)",
      "description-max-width": "32rem",
      "description-gap": "14px",
      "actions-gap": "12px",
      "actions-margin-top": "36px",
      "action-padding-x": "24px",
      "action-padding-y": "12px",
      "split-gap": "48px",
    },
    footer: {
      "padding-y": "56px",
      "border-top": "1px solid var(--s-border)",
      columns: "4",
      "column-gap": "32px",
      "row-gap": "32px",
      "logo-height": "24px",
      "tagline-max-width": "20rem",
      "link-size": "0.875rem",
      "link-gap": "8px",
      "group-title-size": "0.8125rem",
      "group-title-weight": "600",
      "social-icon-size": "20px",
      "social-gap": "12px",
      "bottom-bar-padding": "24px 0",
      "bottom-bar-border": "1px solid var(--s-border-muted)",
    },
    banner: {
      height: "auto",
      "padding-y": "8px",
      "padding-x": "16px",
      "font-size": "0.875rem",
      "font-weight": "500",
      "icon-size": "16px",
      "icon-gap": "12px",
      "border-width": "1px",
      "border-position": "bottom",
      position: "top",
      "dismiss-size": "16px",
      radius: "0px",
    },
    pageRhythm: {
      density: "spacious",
      "section-gap": "0px",
      "section-gap-sm": "0px",
      "section-gap-lg": "0px",
      "first-section-offset": "0px",
      "last-section-margin": "0px",
      "alternate-bg": true,
      "alternate-bg-color": "var(--s-surface-sunken)",
      "divider-between": false,
      "max-content-width": "var(--s-content-max, 1200px)",
      "vertical-rhythm-unit": "8px",
      "scroll-snap": false,
      "responsive-scale": "0.9",
      "responsive-breakpoint": "768px",
    },

  },
};
