import type { SigilPreset } from "@sigil-ui/tokens";

export const fieldPreset: SigilPreset = {
  name: "field",
  metadata: {
    description: "Clean utilitarian open space. Forest green accent, monospace-forward, functional precision.",
    mood: "open, functional, utilitarian",
    tags: ["edgeless", "minimal", "green", "monospace", "functional"],
  },
  tokens: {
    colors: {
      background: { light: "oklch(0.995 0 0)", dark: "oklch(0.08 0.005 160)" },
      surface: { light: "oklch(0.975 0.003 160)", dark: "oklch(0.12 0.008 160)" },
      "surface-elevated": { light: "oklch(1 0 0)", dark: "oklch(0.16 0.01 160)" },
      "surface-sunken": { light: "oklch(0.96 0.005 160)", dark: "oklch(0.05 0.004 160)" },
      primary: { light: "oklch(0.45 0.12 160)", dark: "oklch(0.65 0.14 160)" },
      "primary-hover": { light: "oklch(0.40 0.14 160)", dark: "oklch(0.70 0.12 160)" },
      "primary-muted": { light: "oklch(0.45 0.04 160)", dark: "oklch(0.65 0.04 160)" },
      "primary-contrast": { light: "oklch(1 0 0)", dark: "oklch(0.08 0.005 160)" },
      secondary: "oklch(0.50 0.06 210)",
      "secondary-hover": "oklch(0.44 0.08 210)",
      "secondary-muted": "oklch(0.50 0.02 210)",
      accent: "oklch(0.55 0.10 140)",
      "accent-hover": "oklch(0.48 0.12 140)",
      "accent-muted": "oklch(0.55 0.03 140)",
      text: { light: "oklch(0.12 0.005 160)", dark: "oklch(0.90 0.005 160)" },
      "text-secondary": { light: "oklch(0.32 0.005 160)", dark: "oklch(0.68 0.008 160)" },
      "text-muted": { light: "oklch(0.50 0.005 160)", dark: "oklch(0.50 0.008 160)" },
      "text-subtle": { light: "oklch(0.65 0.003 160)", dark: "oklch(0.38 0.005 160)" },
      "text-disabled": { light: "oklch(0.78 0.002 160)", dark: "oklch(0.28 0.003 160)" },
      "text-inverse": { light: "oklch(0.90 0.005 160)", dark: "oklch(0.12 0.005 160)" },
      border: { light: "oklch(0.82 0.008 160)", dark: "oklch(0.260 0.010 160)" },
      "border-muted": { light: "oklch(0.92 0.004 160)", dark: "oklch(0.200 0.008 160)" },
      "border-strong": { light: "oklch(0.70 0.012 160)", dark: "oklch(0.340 0.015 160)" },
      "border-interactive": { light: "oklch(0.45 0.12 160)", dark: "oklch(0.65 0.14 160)" },
      success: "oklch(0.60 0.16 155)",
      "success-muted": { light: "oklch(0.95 0.03 155)", dark: "oklch(0.14 0.04 155)" },
      warning: "oklch(0.70 0.14 80)",
      "warning-muted": { light: "oklch(0.96 0.03 80)", dark: "oklch(0.16 0.04 80)" },
      error: "oklch(0.55 0.18 25)",
      "error-muted": { light: "oklch(0.96 0.03 25)", dark: "oklch(0.16 0.04 25)" },
      info: "oklch(0.58 0.13 240)",
      "info-muted": { light: "oklch(0.96 0.02 240)", dark: "oklch(0.16 0.03 240)" },
      "gradient-start": { light: "oklch(0.45 0.12 160)", dark: "oklch(0.65 0.14 160)" },
      "gradient-end": { light: "oklch(0.50 0.06 210)", dark: "oklch(0.50 0.06 210)" },
      glow: { light: "oklch(0.45 0.12 160 / 0.12)", dark: "oklch(0.65 0.14 160 / 0.10)" },
      highlight: { light: "oklch(0.92 0.06 160)", dark: "oklch(0.28 0.05 160)" },
    },
    typography: {
      "font-display": "'Space Grotesk', 'Space Mono', system-ui, sans-serif",
      "font-body": "'Inter', system-ui, sans-serif",
      "font-mono": "'Space Mono', 'Fira Code', ui-monospace, monospace",
      "size-xs": "0.6875rem",
      "size-sm": "0.8125rem",
      "size-base": "0.875rem",
      "size-lg": "0.9375rem",
      "size-xl": "1.0625rem",
      "size-2xl": "1.25rem",
      "size-3xl": "1.5rem",
      "size-4xl": "1.875rem",
      "size-5xl": "2.375rem",
      "size-6xl": "3rem",
      "weight-normal": "400",
      "weight-medium": "500",
      "weight-semibold": "600",
      "weight-bold": "700",
      "weight-extrabold": "800",
      "leading-tight": "1.2",
      "leading-normal": "1.5",
      "leading-relaxed": "1.625",
      "leading-loose": "2",
      "tracking-tighter": "-0.04em",
      "tracking-tight": "-0.02em",
      "tracking-normal": "0em",
      "tracking-wide": "0.03em",
      "tracking-wider": "0.06em",
      "heading-weight": "700",
      "heading-tracking": "-0.02em",
      "heading-transform": "none",
      "heading-family": "'Space Grotesk', system-ui, sans-serif",
    },
    spacing: {
      scale: [4, 8, 12, 16, 20, 24, 32, 48, 64, 80],
      unit: "px",
      "button-px": "16px",
      "button-py": "8px",
      "button-px-sm": "12px",
      "button-py-sm": "6px",
      "button-px-lg": "24px",
      "button-py-lg": "10px",
      "card-padding": "20px",
      "card-padding-sm": "14px",
      "card-padding-lg": "28px",
      "input-px": "12px",
      "input-py": "8px",
      "badge-px": "8px",
      "badge-py": "2px",
      "section-py": "80px",
      "section-py-lg": "112px",
      "navbar-height": "52px",
      "navbar-px": "20px",
      "footer-py": "48px",
      "modal-padding": "24px",
      "popover-padding": "12px",
      "tooltip-padding": "6px 10px",
      "table-cell-px": "14px",
      "table-cell-py": "10px",
    },
    layout: {
      "content-max": "1120px",
      "content-max-narrow": "640px",
      "content-max-wide": "1360px",
      "page-margin": "20px",
      "page-margin-sm": "12px",
      "page-margin-lg": "40px",
      gutter: "0px",
      "gutter-sm": "0px",
      "gutter-lg": "0px",
      "grid-columns": "12",
      "grid-gap": "20px",
      "bento-gap": "12px",
      "bento-radius": "4px",
      "bento-min-height": "180px",
      "section-gap": "24px",
      "sidebar-width": "240px",
      "sidebar-collapsed": "48px",
      "footer-columns": "3",
      "stack-gap": "12px",
      "stack-gap-sm": "6px",
      "stack-gap-lg": "20px",
      "prose-max": "60ch",
    },
    sigil: {
      "grid-cell": "40px",
      "cross-arm": "0px",
      "cross-stroke": "0px",
      "rail-gap": "0px",
      "card-radius": "4px",
      "gutter-pattern": "none",
      "margin-pattern": "none",
      "gutter-border": "none",
      "gutter-visible": false,
    },
    radius: {
      none: "0px",
      sm: "3px",
      md: "5px",
      lg: "8px",
      xl: "12px",
      "2xl": "16px",
      full: "9999px",
      button: "4px",
      card: "6px",
      input: "4px",
      badge: "3px",
      modal: "8px",
      popover: "6px",
      tooltip: "4px",
      image: "4px",
      bento: "4px",
    },
    shadows: {
      sm: "0 1px 2px 0 rgb(0 0 0 / 0.04)",
      md: "0 1px 4px -1px rgb(0 0 0 / 0.06), 0 1px 2px 0 rgb(0 0 0 / 0.03)",
      lg: "0 3px 10px -2px rgb(0 0 0 / 0.08), 0 1px 3px 0 rgb(0 0 0 / 0.03)",
      xl: "0 6px 20px -4px rgb(0 0 0 / 0.1), 0 2px 6px -2px rgb(0 0 0 / 0.04)",
      "2xl": "0 12px 32px -6px rgb(0 0 0 / 0.14)",
      glow: "none",
      "glow-sm": "none",
      colored: "none",
      inner: "inset 0 1px 3px 0 rgb(0 0 0 / 0.04)",
      card: "0 1px 3px 0 rgb(0 0 0 / 0.04)",
      button: "none",
      "button-hover": "0 1px 4px -1px rgb(0 0 0 / 0.08)",
      dropdown: "0 4px 12px -2px rgb(0 0 0 / 0.1)",
      modal: "0 16px 36px -8px rgb(0 0 0 / 0.18)",
    },
    motion: {
      duration: { instant: "0ms", fast: "100ms", normal: "180ms", slow: "300ms", slower: "450ms", slowest: "700ms" },
      easing: {
        default: "cubic-bezier(0.16, 1, 0.3, 1)",
        in: "cubic-bezier(0.55, 0, 1, 0.45)",
        out: "cubic-bezier(0, 0.55, 0.45, 1)",
        "in-out": "cubic-bezier(0.45, 0, 0.55, 1)",
        spring: "cubic-bezier(0.22, 1, 0.36, 1)",
      },
      "hover-scale": "1.0",
      "press-scale": "0.98",
      "hover-lift": "-1px",
      "stagger-interval": "40ms",
      "stagger-interval-fast": "25ms",
    },
    borders: {
      width: { none: "0px", thin: "1px", medium: "1.5px", thick: "2px" },
      style: "solid",
      "card-border": "1px solid",
      "card-border-hover": "1px solid",
      "button-border": "1px solid",
      "input-border": "1px solid",
      "divider-style": "solid",
      "divider-width": "1px",
    },
    buttons: {
      "font-weight": "600",
      "text-transform": "none",
      "letter-spacing": "0.02em",
      "font-family": "'Space Grotesk', system-ui, sans-serif",
      "border-width": "1px",
      "hover-effect": "darken",
      "active-scale": "0.98",
      "icon-gap": "6px",
      "min-width": "0px",
    },
    cards: {
      "border-style": "solid",
      "border-width": "1px",
      "hover-effect": "border",
      "hover-border-color": "var(--s-primary)",
      padding: "20px",
      "header-padding": "20px 20px 0",
      "footer-padding": "0 20px 20px",
      "title-size": "0.9375rem",
      "title-weight": "600",
      "description-size": "0.8125rem",
      background: "surface",
      shadow: "none",
      outline: true,
      "outline-on-hover-only": false,
      "gap-between": "12px",
      "content-padding-x": "20px",
      "content-padding-y": "16px",
    },
    headings: {
      "h1-size": "1.875rem",
      "h1-weight": "700",
      "h1-tracking": "-0.025em",
      "h1-leading": "1.15",
      "h2-size": "1.5rem",
      "h2-weight": "700",
      "h2-tracking": "-0.02em",
      "h3-size": "1.25rem",
      "h3-weight": "600",
      "h4-size": "1.0625rem",
      "h4-weight": "600",
      "display-size": "2.75rem",
      "display-weight": "800",
      "display-tracking": "-0.035em",
      "display-leading": "1.08",
    },
    navigation: {
      "navbar-height": "52px",
      "navbar-backdrop-blur": "12px",
      "navbar-border": "1px solid",
      "navbar-bg-opacity": "0.92",
      "nav-link-weight": "500",
      "nav-link-size": "0.8125rem",
      "nav-link-hover": "color",
      "breadcrumb-separator": "/",
      "pagination-radius": "4px",
      "sidebar-width": "240px",
      "sidebar-item-radius": "4px",
      "sidebar-item-padding": "8px 12px",
    },
    backgrounds: {
      pattern: "none",
      "pattern-opacity": "0",
      "pattern-scale": "1",
      noise: false,
      "noise-opacity": "0",
      "gradient-angle": "0deg",
      "gradient-type": "none",
      "hero-pattern": "none",
      "section-divider": "line",
    },
    code: {
      "font-family": "'Space Mono', 'Fira Code', ui-monospace, monospace",
      "font-size": "0.8125rem",
      "line-height": "1.6",
      bg: "var(--s-surface)",
      border: "1px solid var(--s-border)",
      "border-radius": "4px",
      padding: "16px",
      "tab-size": "2",
      "selection-bg": "var(--s-primary-muted)",
      "comment-color": "var(--s-text-muted)",
      "keyword-color": "oklch(0.45 0.12 160)",
      "string-color": "oklch(0.55 0.10 140)",
      "number-color": "oklch(0.70 0.14 80)",
      "function-color": "oklch(0.58 0.13 240)",
    },
    inputs: {
      height: "36px",
      "height-sm": "30px",
      "height-lg": "44px",
      "border-width": "1px",
      "focus-ring-width": "2px",
      "focus-ring-color": "var(--s-primary)",
      "focus-ring-offset": "1px",
      "placeholder-color": "var(--s-text-subtle)",
      "error-border-color": "var(--s-error)",
      "label-size": "0.75rem",
      "label-weight": "600",
      "label-spacing": "6px",
      "helper-size": "0.6875rem",
    },
    alignment: {
      "rail-width": "1120px",
      "rail-columns": "12",
      "rail-gutter": "20px",
      "rail-margin": "20px",
      "rail-visible": false,
      "rail-color": "var(--s-border-muted)",
      "content-align": "center",
      "hero-align": "left",
      "section-align": "center",
      "navbar-align": "full",
      "footer-align": "full",
    },
    sections: {
      "padding-y": "80px",
      "padding-y-hero": "112px",
      "padding-x": "20px",
      "max-width": "1120px",
      gap: "24px",
      "title-align": "left",
      "divider-above": true,
      "divider-below": false,
      "background-alt": false,
      indent: "0px",
    },
    dividers: {
      style: "solid",
      width: "1px",
      color: "var(--s-border-muted)",
      spacing: "0px",
      "show-cross": false,
      "show-label": false,
      "full-bleed": true,
      ornament: "none",
    },
    gridVisuals: {
      "show-lines": false,
      "line-color": "var(--s-border-muted)",
      "line-width": "1px",
      "show-dots": false,
      "dot-size": "1.5px",
      "cell-background": "none",
      "cell-border": true,
      "cell-radius": "4px",
      "cell-padding": "16px",
      "hover-effect": "border",
    },
    cursor: {
      variant: "dot",
      size: "24px",
      "dot-size": "4px",
      "stroke-width": "1.5px",
      "tick-size": "6px",
      gap: "3px",
      radius: "0px",
      color: "var(--s-text)",
      "ring-color": "var(--s-primary)",
      "dot-color": "var(--s-primary)",
      glow: "none",
      opacity: "1",
      "blend-mode": "normal",
      "z-index": "9999",
      "hide-native": false,
    },
    scrollbar: {
      width: "8px",
      height: "8px",
      padding: "2px",
      radius: "9999px",
      track: "transparent",
      thumb: "var(--s-border-muted)",
      "thumb-hover": "var(--s-border)",
      "thumb-active": "var(--s-border-strong)",
      corner: "transparent",
      border: "none",
      "firefox-width": "thin",
      gutter: "stable",
      visibility: "auto",
    },
    focus: {
      "ring-width": "2px",
      "ring-color": "var(--s-primary)",
      "ring-offset": "2px",
      "ring-shadow": "0 0 0 2px var(--s-primary)",
      "outline-color": "var(--s-primary)",
    },
    overlays: {
      bg: "rgb(0 0 0 / 0.5)",
      blur: "8px",
      surface: "var(--s-surface-elevated)",
      border: "1px solid var(--s-border-muted)",
      shadow: "var(--s-shadow-xl)",
      radius: "var(--s-radius-lg)",
      padding: "20px",
      "z-index": "50",
    },
    dataViz: {
      "series-1": "var(--s-primary)",
      "series-2": "var(--s-secondary)",
      "series-3": "var(--s-accent)",
      "series-4": "var(--s-info)",
      "series-5": "var(--s-success)",
      positive: "var(--s-success)",
      negative: "var(--s-error)",
      neutral: "var(--s-text-muted)",
      grid: "var(--s-border-muted)",
      axis: "var(--s-border)",
      label: "var(--s-text-secondary)",
      "tooltip-bg": "var(--s-surface-elevated)",
      "tooltip-border": "var(--s-border-muted)",
    },
    media: {
      radius: "var(--s-radius-md)",
      border: "none",
      outline: "1px solid rgb(0 0 0 / 0.08)",
      shadow: "none",
      bg: "var(--s-surface-sunken)",
      "object-fit": "cover",
    },
    controls: {
      height: "38px",
      "height-sm": "30px",
      "height-lg": "46px",
      "hit-area": "44px",
      "icon-size": "16px",
      "handle-size": "20px",
      "track-height": "4px",
      "track-bg": "var(--s-border-muted)",
      "track-fill": "var(--s-primary)",
      "thumb-bg": "var(--s-surface-elevated)",
      "thumb-border": "2px solid var(--s-primary)",
    },
    componentSurfaces: {
      bg: "var(--s-surface)",
      "bg-elevated": "var(--s-surface-elevated)",
      "bg-muted": "var(--s-surface-sunken)",
      border: "var(--s-border)",
      "border-muted": "var(--s-border-muted)",
      "border-strong": "var(--s-border-strong)",
      text: "var(--s-text)",
      "text-muted": "var(--s-text-muted)",
      contrast: "var(--s-primary-contrast)",
      "hover-bg": "var(--s-surface-elevated)",
      "active-bg": "var(--s-surface-sunken)",
      "selected-bg": "var(--s-primary-muted)",
    },

  },
};
