import type { SigilPreset } from "@sigil-ui/tokens";

export const fluxPreset: SigilPreset = {
  name: "flux",
  metadata: {
    description: "Dynamic change. Gradient-heavy, movement-focused, energetic flow state.",
    mood: "dynamic, energetic, flowing",
    tags: ["gradient", "dynamic", "energetic", "colorful", "motion", "electric"],
  },
  tokens: {
    colors: {
      background: { light: "oklch(0.985 0.003 240)", dark: "oklch(0.08 0.015 260)" },
      surface: { light: "oklch(0.97 0.004 240)", dark: "oklch(0.12 0.014 260)" },
      "surface-elevated": { light: "oklch(1 0 0)", dark: "oklch(0.16 0.013 260)" },
      "surface-sunken": { light: "oklch(0.955 0.005 240)", dark: "oklch(0.06 0.016 260)" },
      primary: "oklch(0.61 0.18 210)",
      "primary-hover": "oklch(0.55 0.22 210)",
      "primary-muted": "oklch(0.75 0.07 210)",
      "primary-contrast": "oklch(0.08 0.01 260)",
      secondary: "oklch(0.65 0.22 285)",
      "secondary-hover": "oklch(0.58 0.24 285)",
      "secondary-muted": "oklch(0.65 0.08 285)",
      accent: "oklch(0.7 0.2 330)",
      "accent-hover": "oklch(0.64 0.22 330)",
      "accent-muted": "oklch(0.7 0.07 330)",
      text: { light: "oklch(0.12 0.012 260)", dark: "oklch(0.95 0.004 240)" },
      "text-secondary": { light: "oklch(0.32 0.01 260)", dark: "oklch(0.78 0.005 240)" },
      "text-muted": { light: "oklch(0.48 0.008 260)", dark: "oklch(0.65 0.004 240)" },
      "text-subtle": { light: "oklch(0.62 0.006 260)", dark: "oklch(0.52 0.004 240)" },
      "text-disabled": { light: "oklch(0.74 0.004 260)", dark: "oklch(0.34 0.003 240)" },
      "text-inverse": { light: "oklch(0.95 0.004 240)", dark: "oklch(0.12 0.012 260)" },
      border: { light: "oklch(0.65 0.006 240)", dark: "oklch(0.260 0.012 260)" },
      "border-muted": { light: "oklch(0.82 0.006 240)", dark: "oklch(0.200 0.010 260)" },
      "border-strong": { light: "oklch(0.55 0.012 240)", dark: "oklch(0.340 0.018 260)" },
      "border-interactive": { light: "oklch(0.75 0.18 210)", dark: "oklch(0.75 0.18 210)" },
      success: "oklch(0.62 0.18 155)",
      "success-muted": "oklch(0.74 0.06 155)",
      warning: "oklch(0.65 0.15 80)",
      "warning-muted": "oklch(0.82 0.05 80)",
      error: "oklch(0.62 0.22 20)",
      "error-muted": "oklch(0.62 0.08 20)",
      info: "oklch(0.64 0.16 240)",
      "info-muted": "oklch(0.72 0.06 240)",
      "gradient-start": "oklch(0.75 0.18 210)",
      "gradient-end": "oklch(0.65 0.22 285)",
      glow: "oklch(0.75 0.18 210 / 0.4)",
      highlight: { light: "oklch(0.92 0.08 210)", dark: "oklch(0.28 0.06 210)" },
    },
    typography: {
      "font-display": "'PP Gosha Sans', system-ui, sans-serif",
      "font-body": "'PP Pangram Sans', system-ui, sans-serif",
      "font-mono": "'PP Supply Mono', ui-monospace, monospace",
      "size-xs": "0.75rem",
      "size-sm": "0.875rem",
      "size-base": "1rem",
      "size-lg": "1.125rem",
      "size-xl": "1.25rem",
      "size-2xl": "1.5rem",
      "size-3xl": "1.875rem",
      "size-4xl": "2.25rem",
      "size-5xl": "3rem",
      "size-6xl": "3.75rem",
      "weight-normal": "400",
      "weight-medium": "500",
      "weight-semibold": "600",
      "weight-bold": "700",
      "weight-extrabold": "800",
      "leading-tight": "1.2",
      "leading-normal": "1.5",
      "leading-relaxed": "1.625",
      "leading-loose": "2",
      "tracking-tighter": "-0.04em",
      "tracking-tight": "-0.02em",
      "tracking-normal": "0em",
      "tracking-wide": "0.02em",
      "tracking-wider": "0.04em",
      "heading-weight": "700",
      "heading-tracking": "-0.02em",
      "heading-transform": "none",
      "heading-family": "'PP Gosha Sans', system-ui, sans-serif",
    },
    spacing: {
      scale: [4, 8, 12, 16, 24, 32, 48, 64, 80, 96],
      unit: "px",
      "button-px": "24px",
      "button-py": "12px",
      "button-px-sm": "16px",
      "button-py-sm": "8px",
      "button-px-lg": "32px",
      "button-py-lg": "14px",
      "card-padding": "24px",
      "card-padding-sm": "16px",
      "card-padding-lg": "36px",
      "input-px": "14px",
      "input-py": "10px",
      "badge-px": "10px",
      "badge-py": "3px",
      "section-py": "6.5rem",
      "section-py-lg": "9.75rem",
      "navbar-height": "52px",
      "navbar-px": "24px",
      "footer-py": "52px",
      "modal-padding": "28px",
      "popover-padding": "16px",
      "tooltip-padding": "8px 12px",
      "table-cell-px": "16px",
      "table-cell-py": "12px",
    },
    layout: {
      "content-max": "1200px",
      "content-max-narrow": "720px",
      "content-max-wide": "1440px",
      "page-margin": "24px",
      "page-margin-sm": "16px",
      "page-margin-lg": "48px",
      gutter: "0px",
      "gutter-sm": "0px",
      "gutter-lg": "0px",
      "grid-columns": "12",
      "grid-gap": "24px",
      "bento-gap": "16px",
      "bento-radius": "16px",
      "bento-min-height": "208px",
      "section-gap": "26px",
      "sidebar-width": "288px",
      "sidebar-collapsed": "64px",
      "footer-columns": "4",
      "stack-gap": "16px",
      "stack-gap-sm": "8px",
      "stack-gap-lg": "24px",
      "prose-max": "65ch",
    },
    sigil: {
      "grid-cell": "52px",
      "cross-arm": "0px",
      "cross-stroke": "0px",
      "rail-gap": "0px",
      "card-radius": "16px",
      "gutter-pattern": "none",
      "margin-pattern": "none",
      "gutter-border": "none",
      "gutter-visible": false,
      "band-height": "52px",
      "divider-thickness-sm": "27px",
      "divider-thickness-md": "53px",
      "divider-thickness-lg": "105px",
      "divider-thickness-xl": "157px",
    },
    radius: {
      none: "0px",
      sm: "6px",
      md: "10px",
      lg: "14px",
      xl: "18px",
      "2xl": "24px",
      full: "9999px",
      button: "10px",
      card: "16px",
      input: "10px",
      badge: "9999px",
      modal: "20px",
      popover: "14px",
      tooltip: "8px",
      image: "12px",
      bento: "16px",
    },
    shadows: {
      sm: "0 1px 2px 0 rgb(0 0 0 / 0.05)",
      md: "0 2px 6px -1px rgb(0 0 0 / 0.08), 0 0 0 1px rgb(0 0 0 / 0.03)",
      lg: "0 6px 16px -3px rgb(0 0 0 / 0.12), 0 3px 6px -3px rgb(0 0 0 / 0.05)",
      xl: "0 12px 28px -6px rgb(0 0 0 / 0.15), 0 6px 12px -4px rgb(0 0 0 / 0.06)",
      "2xl": "0 24px 50px -12px rgb(0 0 0 / 0.22)",
      glow: "0 0 24px var(--s-primary), 0 0 48px var(--s-secondary)",
      "glow-sm": "0 0 12px var(--s-primary)",
      colored: "0 6px 20px -4px var(--s-primary)",
      inner: "inset 0 2px 4px 0 rgb(0 0 0 / 0.05)",
      card: "0 0 0 1px var(--s-border-muted), 0 2px 8px -2px rgb(0 0 0 / 0.06)",
      button: "none",
      "button-hover": "0 4px 16px -2px var(--s-primary)",
      dropdown: "0 8px 24px -4px rgb(0 0 0 / 0.14), 0 0 0 1px rgb(0 0 0 / 0.04)",
      modal: "0 24px 64px -16px rgb(0 0 0 / 0.28)",
    },
    motion: {
      duration: { instant: "0ms", fast: "100ms", normal: "180ms", slow: "300ms", slower: "450ms", slowest: "750ms" },
      easing: {
        default: "cubic-bezier(0.34, 1.56, 0.64, 1)",
        in: "cubic-bezier(0.55, 0, 1, 0.45)",
        out: "cubic-bezier(0, 0.55, 0.45, 1)",
        "in-out": "cubic-bezier(0.45, 0, 0.55, 1)",
        spring: "cubic-bezier(0.34, 1.56, 0.64, 1)",
        bounce: "cubic-bezier(0.68, -0.6, 0.32, 1.6)",
      },
      "enter-preset": "scaleUp",
      "exit-preset": "fadeOut",
      "hover-scale": "1.04",
      "press-scale": "0.96",
      "hover-lift": "-3px",
      "stagger-interval": "35ms",
      "stagger-interval-fast": "15ms",
    },
    borders: {
      width: { none: "0px", thin: "1px", medium: "1.5px", thick: "2px" },
      style: "solid",
      "card-border": "1px solid",
      "card-border-hover": "1px solid",
      "button-border": "0px solid",
      "input-border": "1px solid",
      "divider-style": "solid",
      "divider-width": "1px",
    },
    buttons: {
      "font-weight": "700",
      "text-transform": "none",
      "letter-spacing": "0em",
      "font-family": "'PP Pangram Sans', system-ui, sans-serif",
      "border-width": "0px",
      "hover-effect": "fill",
      "active-scale": "0.96",
      "icon-gap": "8px",
      "min-width": "0px",
    },
    cards: {
      "border-style": "solid",
      "border-width": "1px",
      "hover-effect": "glow",
      "hover-border-color": "var(--s-primary)",
      padding: "24px",
      "header-padding": "24px 24px 0",
      "footer-padding": "0 24px 24px",
      "title-size": "1.125rem",
      "title-weight": "700",
      "description-size": "0.875rem",
      background: "surface",
      shadow: "md",
      outline: true,
      "outline-on-hover-only": true,
      "gap-between": "20px",
      "content-padding-x": "24px",
      "content-padding-y": "20px",
    },
    headings: {
      "h1-size": "2.25rem",
      "h1-weight": "700",
      "h1-tracking": "-0.025em",
      "h1-leading": "1.2",
      "h2-size": "1.875rem",
      "h2-weight": "700",
      "h2-tracking": "-0.02em",
      "h2-leading": "1.15",
      "h3-size": "1.5rem",
      "h3-weight": "600",
      "h3-tracking": "0em",
      "h3-leading": "1.2",
      "h4-size": "1.25rem",
      "h4-weight": "600",
      "h4-tracking": "0em",
      "h4-leading": "1.3",
      "display-size": "3.75rem",
      "display-weight": "800",
      "display-tracking": "-0.04em",
      "display-leading": "1.1",
    },
    navigation: {
      "navbar-height": "52px",
      "navbar-backdrop-blur": "20px",
      "navbar-border": "none",
      "navbar-bg-opacity": "0.75",
      "navbar-padding-x": "24px",
      "navbar-position": "sticky",
      "navbar-logo-height": "26px",
      "navbar-logo-gap": "10px",
      "navbar-item-gap": "24px",
      "navbar-item-padding-x": "14px",
      "navbar-item-padding-y": "6px",
      "navbar-item-size": "0.875rem",
      "navbar-shadow": "none",
      "navbar-height-scrolled": "48px",
      "navbar-mobile-breakpoint": "768px",
      "nav-link-weight": "500",
      "nav-link-size": "0.875rem",
      "nav-link-hover": "background",
      "breadcrumb-separator": "/",
      "pagination-radius": "10px",
      "sidebar-width": "288px",
      "sidebar-item-radius": "12px",
      "sidebar-item-padding": "9px 14px",
    },
    backgrounds: {
      pattern: "none",
      "pattern-opacity": "0",
      "pattern-scale": "1",
      noise: true,
      "noise-opacity": "0.02",
      "gradient-angle": "45deg",
      "gradient-type": "conic",
      "hero-pattern": "gradient",
      "section-divider": "wave",
    },
    code: {
      "font-family": "'PP Supply Mono', ui-monospace, monospace",
      "font-size": "0.875rem",
      "line-height": "1.7",
      bg: "var(--s-surface-sunken)",
      border: "1px solid var(--s-border-muted)",
      "border-radius": "12px",
      padding: "16px",
      "tab-size": "2",
      "selection-bg": "var(--s-primary-muted)",
      "comment-color": "var(--s-text-muted)",
      "keyword-color": "var(--s-secondary)",
      "string-color": "var(--s-success)",
      "number-color": "var(--s-accent)",
      "function-color": "var(--s-primary)",
    },
    inputs: {
      height: "42px",
      "height-sm": "34px",
      "height-lg": "50px",
      "border-width": "1px",
      "focus-ring-width": "2px",
      "focus-ring-color": "var(--s-primary)",
      "focus-ring-offset": "2px",
      "placeholder-color": "var(--s-text-subtle)",
      "error-border-color": "var(--s-error)",
      "label-size": "0.875rem",
      "label-weight": "500",
      "label-spacing": "8px",
      "helper-size": "0.8125rem",
    },
    alignment: {
      "rail-width": "1280px",
      "rail-columns": "12",
      "rail-gutter": "24px",
      "rail-margin": "32px",
      "rail-visible": false,
      "rail-color": "var(--s-border-muted)",
      "content-align": "center",
      "hero-align": "center",
      "section-align": "center",
      "navbar-align": "full",
      "footer-align": "content",
    },
    sections: {
      "padding-y": "6.5rem",
      "padding-y-hero": "9.75rem",
      "padding-y-sm": "3.25rem",
      "padding-x": "32px",
      "max-width": "1280px",
      gap: "32px",
      "padding-y-lg": "9.75rem",
      "padding-y-xl": "13rem",
      "title-align": "center",
      "heading-size": "clamp(1.5rem, 4vw, 2.5rem)",
      "heading-align": "center",
      "heading-max-width": "40rem",
      "heading-margin-bottom": "16px",
      "description-max-width": "32rem",
      "description-gap": "12px",
      "content-gap": "24px",
      "grid-columns": "3",
      "grid-gap": "24px",
      "alternate-bg": "var(--s-surface)",
      "alternate-bg-mode": "surface",
      "divider-above": false,
      "divider-below": false,
      "background-alt": false,
      indent: "0px",
    },
    dividers: {
      style: "none",
      width: "0px",
      color: "var(--s-border-muted)",
      spacing: "0px",
      opacity: "0.8",
      "max-width": "100%",
      "margin-y": "0px",
      thickness: "1px",
      "gradient-start": "var(--s-primary)",
      "gradient-end": "var(--s-secondary)",
      "show-cross": false,
      "show-label": false,
      "full-bleed": false,
      ornament: "none",
    },
    gridVisuals: {
      "show-lines": false,
      "line-color": "var(--s-border-muted)",
      "line-width": "1px",
      "show-dots": true,
      "dot-size": "2px",
      "cell-background": "surface",
      "cell-border": false,
      "cell-radius": "12px",
      "cell-padding": "16px",
      "hover-effect": "glow",
    },
    cursor: {
      variant: "ring",
      size: "24px",
      "dot-size": "4px",
      "stroke-width": "1.5px",
      "tick-size": "6px",
      gap: "3px",
      radius: "0px",
      color: "var(--s-text)",
      "ring-color": "var(--s-primary)",
      "dot-color": "var(--s-primary)",
      glow: "none",
      opacity: "1",
      "blend-mode": "normal",
      "z-index": "9999",
      "hide-native": false,
    },
    scrollbar: {
      width: "8px",
      height: "8px",
      padding: "2px",
      radius: "9999px",
      track: "transparent",
      thumb: "var(--s-border-muted)",
      "thumb-hover": "var(--s-border)",
      "thumb-active": "var(--s-border-strong)",
      corner: "transparent",
      border: "none",
      "firefox-width": "thin",
      gutter: "stable",
      visibility: "auto",
    },
    focus: {
      "ring-width": "2px",
      "ring-color": "var(--s-primary)",
      "ring-offset": "2px",
      "ring-shadow": "0 0 0 2px var(--s-primary)",
      "outline-color": "var(--s-primary)",
    },
    overlays: {
      bg: "rgb(0 0 0 / 0.5)",
      blur: "8px",
      surface: "var(--s-surface-elevated)",
      border: "1px solid var(--s-border-muted)",
      shadow: "var(--s-shadow-xl)",
      radius: "var(--s-radius-lg)",
      padding: "20px",
      "z-index": "50",
    },
    dataViz: {
      "series-1": "var(--s-primary)",
      "series-2": "var(--s-secondary)",
      "series-3": "var(--s-accent)",
      "series-4": "var(--s-info)",
      "series-5": "var(--s-success)",
      positive: "var(--s-success)",
      negative: "var(--s-error)",
      neutral: "var(--s-text-muted)",
      grid: "var(--s-border-muted)",
      axis: "var(--s-border)",
      label: "var(--s-text-secondary)",
      "tooltip-bg": "var(--s-surface-elevated)",
      "tooltip-border": "var(--s-border-muted)",
    },
    media: {
      radius: "var(--s-radius-md)",
      border: "none",
      outline: "1px solid rgb(0 0 0 / 0.08)",
      shadow: "none",
      bg: "var(--s-surface-sunken)",
      "object-fit": "cover",
    },
    controls: {
      height: "38px",
      "height-sm": "30px",
      "height-lg": "46px",
      "hit-area": "44px",
      "icon-size": "16px",
      "handle-size": "20px",
      "track-height": "4px",
      "track-bg": "var(--s-border-muted)",
      "track-fill": "var(--s-primary)",
      "thumb-bg": "var(--s-surface-elevated)",
      "thumb-border": "2px solid var(--s-primary)",
    },
    componentSurfaces: {
      bg: "var(--s-surface)",
      "bg-elevated": "var(--s-surface-elevated)",
      "bg-muted": "var(--s-surface-sunken)",
      border: "var(--s-border)",
      "border-muted": "var(--s-border-muted)",
      "border-strong": "var(--s-border-strong)",
      text: "var(--s-text)",
      "text-muted": "var(--s-text-muted)",
      contrast: "var(--s-primary-contrast)",
      "hover-bg": "var(--s-surface-elevated)",
      "active-bg": "var(--s-surface-sunken)",
      "selected-bg": "var(--s-primary-muted)",
    },
    hero: {
      "min-height": "auto",
      "padding-y": "104px",
      "padding-y-sm": "52px",
      "padding-x": "var(--s-page-margin, 24px)",
      "content-max": "640px",
      "content-align": "center",
      layout: "centered",
      "media-position": "below",
      "media-width": "50%",
      "media-radius": "var(--s-radius-xl)",
      "title-size": "clamp(2.25rem, 6vw, 4.5rem)",
      "title-max-width": "56rem",
      "description-size": "1.125rem",
      "description-max-width": "32rem",
      "description-gap": "24px",
      "actions-gap": "14px",
      "actions-margin-top": "32px",
      "action-padding-x": "28px",
      "action-padding-y": "12px",
      "badge-gap": "24px",
      "overlay-opacity": "0.4",
      "scroll-indicator": false,
      "gradient-overlay": "none",
    },
    cta: {
      "padding-y": "78px",
      "padding-x": "var(--s-page-margin, 24px)",
      "max-width": "var(--s-content-max, 1200px)",
      layout: "centered",
      border: true,
      "border-radius": "var(--s-radius-xl)",
      bg: "var(--s-surface)",
      "title-size": "clamp(1.5rem, 4vw, 2.5rem)",
      "description-max-width": "32rem",
      "description-gap": "12px",
      "actions-gap": "14px",
      "actions-margin-top": "32px",
      "action-padding-x": "28px",
      "action-padding-y": "12px",
      "split-gap": "52px",
    },
    footer: {
      "padding-y": "52px",
      "border-top": "1px solid var(--s-border)",
      columns: "4",
      "column-gap": "32px",
      "row-gap": "28px",
      "logo-height": "24px",
      "tagline-max-width": "20rem",
      "link-size": "0.875rem",
      "link-gap": "8px",
      "group-title-size": "0.875rem",
      "group-title-weight": "600",
      "social-icon-size": "20px",
      "social-gap": "12px",
      "bottom-bar-padding": "26px 0",
      "bottom-bar-border": "1px solid var(--s-border-muted)",
    },
    banner: {
      height: "auto",
      "padding-y": "8px",
      "padding-x": "16px",
      "font-size": "0.875rem",
      "font-weight": "500",
      "icon-size": "16px",
      "icon-gap": "12px",
      "border-width": "1px",
      "border-position": "bottom",
      position: "top",
      "dismiss-size": "16px",
      radius: "0px",
    },
    pageRhythm: {
      density: "normal",
      "section-gap": "0px",
      "section-gap-sm": "0px",
      "section-gap-lg": "0px",
      "first-section-offset": "0px",
      "last-section-margin": "0px",
      "alternate-bg": true,
      "alternate-bg-color": "var(--s-surface)",
      "divider-between": false,
      "max-content-width": "var(--s-content-max, 1200px)",
      "vertical-rhythm-unit": "4px",
      "scroll-snap": false,
      "responsive-scale": "0.9",
      "responsive-breakpoint": "768px",
    },

  },
};
