import type { SigilPreset } from "@sigil-ui/tokens";

export const forgePreset: SigilPreset = {
  name: "forge",
  metadata: {
    description: "Hot metal. Orange fire, heavy weight, blacksmith intensity. Built to endure.",
    mood: "hot, heavy, forged",
    tags: ["dark", "fire", "orange", "heavy", "industrial", "blacksmith"],
  },
  tokens: {
    colors: {
      background: { light: "oklch(0.97 0.004 50)", dark: "oklch(0.1 0.008 40)" },
      surface: { light: "oklch(0.955 0.005 50)", dark: "oklch(0.14 0.008 40)" },
      "surface-elevated": { light: "oklch(0.985 0.003 50)", dark: "oklch(0.18 0.008 40)" },
      "surface-sunken": { light: "oklch(0.935 0.006 50)", dark: "oklch(0.07 0.008 40)" },
      primary: "oklch(0.66 0.2 45)",
      "primary-hover": "oklch(0.62 0.22 45)",
      "primary-muted": "oklch(0.68 0.08 45)",
      "primary-contrast": "oklch(0.08 0 0)",
      secondary: "oklch(0.55 0.2 25)",
      "secondary-hover": "oklch(0.48 0.22 25)",
      "secondary-muted": "oklch(0.55 0.07 25)",
      accent: "oklch(0.8 0.15 65)",
      "accent-hover": "oklch(0.74 0.17 65)",
      "accent-muted": "oklch(0.8 0.06 65)",
      text: { light: "oklch(0.12 0.008 40)", dark: "oklch(0.92 0.006 50)" },
      "text-secondary": { light: "oklch(0.32 0.006 40)", dark: "oklch(0.74 0.006 50)" },
      "text-muted": { light: "oklch(0.48 0.005 40)", dark: "oklch(0.63 0.005 50)" },
      "text-subtle": { light: "oklch(0.6 0.004 40)", dark: "oklch(0.51 0.004 50)" },
      "text-disabled": { light: "oklch(0.72 0.003 40)", dark: "oklch(0.34 0.003 50)" },
      "text-inverse": { light: "oklch(0.92 0.006 50)", dark: "oklch(0.12 0.008 40)" },
      border: { light: "oklch(0.64 0.008 45)", dark: "oklch(0.280 0.010 40)" },
      "border-muted": { light: "oklch(0.81 0.006 45)", dark: "oklch(0.220 0.008 40)" },
      "border-strong": { light: "oklch(0.64 0.012 45)", dark: "oklch(0.360 0.014 40)" },
      "border-interactive": { light: "oklch(0.68 0.2 45)", dark: "oklch(0.68 0.2 45)" },
      success: "oklch(0.62 0.17 150)",
      "success-muted": "oklch(0.7 0.06 150)",
      warning: "oklch(0.65 0.17 65)",
      "warning-muted": "oklch(0.8 0.06 65)",
      error: "oklch(0.55 0.23 25)",
      "error-muted": "oklch(0.55 0.08 25)",
      info: "oklch(0.64 0.13 245)",
      "info-muted": "oklch(0.65 0.05 245)",
      "gradient-start": "oklch(0.68 0.2 45)",
      "gradient-end": "oklch(0.55 0.2 25)",
      glow: "oklch(0.68 0.2 45 / 0.45)",
      highlight: { light: "oklch(0.93 0.08 45)", dark: "oklch(0.28 0.06 45)" },
    },
    typography: {
      "font-display": "'Tex Gyre Heros', system-ui, sans-serif",
      "font-body": "'PP Supply Sans', system-ui, sans-serif",
      "font-mono": "'PP Supply Mono', ui-monospace, monospace",
      "size-xs": "0.75rem",
      "size-sm": "0.875rem",
      "size-base": "1rem",
      "size-lg": "1.1875rem",
      "size-xl": "1.375rem",
      "size-2xl": "1.75rem",
      "size-3xl": "2.125rem",
      "size-4xl": "2.75rem",
      "size-5xl": "3.5rem",
      "size-6xl": "4.5rem",
      "weight-normal": "400",
      "weight-medium": "500",
      "weight-semibold": "600",
      "weight-bold": "700",
      "weight-extrabold": "800",
      "leading-tight": "1.15",
      "leading-normal": "1.5",
      "leading-relaxed": "1.625",
      "leading-loose": "1.875",
      "tracking-tighter": "-0.05em",
      "tracking-tight": "-0.025em",
      "tracking-normal": "0em",
      "tracking-wide": "0.03em",
      "tracking-wider": "0.06em",
      "heading-weight": "700",
      "heading-tracking": "0.06em",
      "heading-transform": "uppercase",
      "heading-family": "'Tex Gyre Heros', system-ui, sans-serif",
    },
    spacing: {
      scale: [4, 8, 16, 20, 28, 40, 56, 72, 96, 120],
      unit: "px",
      "button-px": "28px",
      "button-py": "14px",
      "button-px-sm": "20px",
      "button-py-sm": "10px",
      "button-px-lg": "40px",
      "button-py-lg": "18px",
      "card-padding": "28px",
      "card-padding-sm": "20px",
      "card-padding-lg": "40px",
      "input-px": "14px",
      "input-py": "10px",
      "badge-px": "10px",
      "badge-py": "3px",
      "section-py": "96px",
      "section-py-lg": "144px",
      "navbar-height": "48px",
      "navbar-px": "36px",
      "footer-py": "72px",
      "modal-padding": "28px",
      "popover-padding": "18px",
      "tooltip-padding": "8px 14px",
      "table-cell-px": "18px",
      "table-cell-py": "14px",
    },
    layout: {
      "content-max": "1200px",
      "content-max-narrow": "720px",
      "content-max-wide": "1440px",
      "page-margin": "32px",
      "page-margin-sm": "16px",
      "page-margin-lg": "64px",
      gutter: "36px",
      "gutter-sm": "16px",
      "gutter-lg": "48px",
      "grid-columns": "12",
      "grid-gap": "32px",
      "bento-gap": "18px",
      "bento-radius": "6px",
      "bento-min-height": "240px",
      "section-gap": "48px",
      "sidebar-width": "320px",
      "sidebar-collapsed": "64px",
      "footer-columns": "4",
      "stack-gap": "16px",
      "stack-gap-sm": "8px",
      "stack-gap-lg": "28px",
      "prose-max": "66ch",
    },
    sigil: {
      "grid-cell": "48px",
      "cross-arm": "16px",
      "cross-stroke": "2.5px",
      "rail-gap": "24px",
      "card-radius": "6px",
      "gutter-pattern": "crosshatch",
      "margin-pattern": "brick",
      "margin-border": "2px solid var(--s-border-muted)",
    },
    radius: {
      none: "0px",
      sm: "2px",
      md: "4px",
      lg: "6px",
      xl: "8px",
      "2xl": "12px",
      full: "9999px",
      button: "4px",
      card: "6px",
      input: "4px",
      badge: "9999px",
      modal: "8px",
      popover: "6px",
      tooltip: "4px",
      image: "4px",
      bento: "6px",
    },
    shadows: {
      sm: "0 1px 3px 0 rgb(0 0 0 / 0.1)",
      md: "0 2px 8px -1px rgb(0 0 0 / 0.15), 0 0 0 1px rgb(0 0 0 / 0.05)",
      lg: "0 8px 20px -4px rgb(0 0 0 / 0.2), 0 4px 8px -2px rgb(0 0 0 / 0.08)",
      xl: "0 16px 36px -6px rgb(0 0 0 / 0.22), 0 6px 12px -3px rgb(0 0 0 / 0.08)",
      "2xl": "0 32px 64px -16px rgb(0 0 0 / 0.3)",
      glow: "0 0 32px var(--s-primary)",
      "glow-sm": "0 0 16px var(--s-primary)",
      colored: "0 8px 24px -6px var(--s-primary)",
      inner: "inset 0 3px 6px 0 rgb(0 0 0 / 0.1)",
      card: "0 4px 12px -2px rgb(0 0 0 / 0.12), 0 0 0 1px rgb(0 0 0 / 0.05)",
      button: "0 1px 3px 0 rgb(0 0 0 / 0.1)",
      "button-hover": "0 0 24px var(--s-primary)",
      dropdown: "0 10px 30px -6px rgb(0 0 0 / 0.2), 0 0 0 1px rgb(0 0 0 / 0.05)",
      modal: "0 28px 72px -16px rgb(0 0 0 / 0.35)",
    },
    motion: {
      duration: { instant: "0ms", fast: "120ms", normal: "240ms", slow: "400ms", slower: "600ms", slowest: "1000ms" },
      easing: {
        default: "cubic-bezier(0.16, 1, 0.3, 1)",
        in: "cubic-bezier(0.6, 0, 1, 0.4)",
        out: "cubic-bezier(0, 0.6, 0.4, 1)",
        "in-out": "cubic-bezier(0.5, 0, 0.5, 1)",
        spring: "cubic-bezier(0.34, 1.56, 0.64, 1)",
        bounce: "cubic-bezier(0.68, -0.55, 0.27, 1.55)",
      },
      "enter-preset": "scaleUp",
      "exit-preset": "fadeOut",
      "hover-scale": "1.03",
      "press-scale": "0.95",
      "hover-lift": "-3px",
      "stagger-interval": "40ms",
      "stagger-interval-fast": "20ms",
    },
    borders: {
      width: { none: "0px", thin: "1px", medium: "2px", thick: "3px" },
      style: "solid",
      "card-border": "2px solid",
      "card-border-hover": "2px solid",
      "button-border": "2px solid",
      "input-border": "2px solid",
      "divider-style": "solid",
      "divider-width": "2px",
    },
    buttons: {
      "font-weight": "800",
      "text-transform": "uppercase",
      "letter-spacing": "0.06em",
      "font-family": "'PP Supply Sans', system-ui, sans-serif",
      "border-width": "2px",
      "hover-effect": "glow",
      "active-scale": "0.95",
      "icon-gap": "10px",
      "min-width": "0px",
    },
    cards: {
      "border-style": "solid",
      "border-width": "2px",
      "hover-effect": "lift",
      "hover-border-color": "var(--s-primary)",
      padding: "28px",
      "header-padding": "28px 28px 0",
      "footer-padding": "0 28px 28px",
      "title-size": "1.1875rem",
      "title-weight": "800",
      "description-size": "0.875rem",
      background: "surface",
      shadow: "none",
      outline: true,
      "outline-on-hover-only": false,
      "gap-between": "16px",
      "content-padding-x": "28px",
      "content-padding-y": "20px",
    },
    headings: {
      "h1-size": "2.75rem",
      "h1-weight": "800",
      "h1-tracking": "-0.035em",
      "h1-leading": "1.1",
      "h2-size": "2.125rem",
      "h2-weight": "800",
      "h2-tracking": "-0.03em",
      "h2-leading": "1.1",
      "h3-size": "1.75rem",
      "h3-weight": "700",
      "h3-tracking": "0em",
      "h3-leading": "1.15",
      "h4-size": "1.375rem",
      "h4-weight": "700",
      "h4-tracking": "0em",
      "h4-leading": "1.2",
      "display-size": "4.5rem",
      "display-weight": "800",
      "display-tracking": "-0.05em",
      "display-leading": "1.0",
    },
    navigation: {
      "navbar-height": "48px",
      "navbar-backdrop-blur": "8px",
      "navbar-border": "3px solid",
      "navbar-bg-opacity": "0.95",
      "navbar-padding-x": "20px",
      "navbar-position": "sticky",
      "navbar-logo-height": "22px",
      "navbar-logo-gap": "8px",
      "navbar-item-gap": "16px",
      "navbar-item-padding-x": "10px",
      "navbar-item-padding-y": "4px",
      "navbar-item-size": "0.8125rem",
      "navbar-shadow": "none",
      "navbar-height-scrolled": "44px",
      "navbar-mobile-breakpoint": "768px",
      "nav-link-weight": "700",
      "nav-link-size": "0.875rem",
      "nav-link-hover": "color",
      "breadcrumb-separator": "//",
      "pagination-radius": "4px",
      "sidebar-width": "320px",
      "sidebar-item-radius": "4px",
      "sidebar-item-padding": "12px 16px",
    },
    backgrounds: {
      pattern: "crosshatch",
      "pattern-opacity": "0.06",
      "pattern-scale": "0.8",
      noise: true,
      "noise-opacity": "0.03",
      "gradient-angle": "150deg",
      "gradient-type": "none",
      "hero-pattern": "crosshatch",
      "section-divider": "zigzag",
    },
    code: {
      "font-family": "'PP Supply Mono', ui-monospace, monospace",
      "font-size": "0.875rem",
      "line-height": "1.65",
      bg: "var(--s-surface-sunken)",
      border: "2px solid var(--s-border)",
      "border-radius": "4px",
      padding: "18px",
      "tab-size": "4",
      "selection-bg": "var(--s-primary-muted)",
      "comment-color": "var(--s-text-muted)",
      "keyword-color": "var(--s-primary)",
      "string-color": "var(--s-accent)",
      "number-color": "var(--s-secondary)",
      "function-color": "var(--s-info)",
    },
    inputs: {
      height: "44px",
      "height-sm": "36px",
      "height-lg": "52px",
      "border-width": "2px",
      "focus-ring-width": "3px",
      "focus-ring-color": "var(--s-primary)",
      "focus-ring-offset": "0px",
      "placeholder-color": "var(--s-text-subtle)",
      "error-border-color": "var(--s-error)",
      "label-size": "0.75rem",
      "label-weight": "700",
      "label-spacing": "6px",
      "helper-size": "0.75rem",
    },
    alignment: {
      "rail-width": "1360px",
      "rail-columns": "12",
      "rail-gutter": "28px",
      "rail-margin": "16px",
      "rail-visible": false,
      "rail-color": "var(--s-border-muted)",
      "content-align": "center",
      "hero-align": "center",
      "section-align": "center",
      "navbar-align": "full",
      "footer-align": "content",
    },
    sections: {
      "padding-y": "48px",
      "padding-y-hero": "96px",
      "padding-y-sm": "36px",
      "padding-x": "16px",
      "max-width": "1360px",
      gap: "24px",
      "padding-y-lg": "72px",
      "padding-y-xl": "96px",
      "title-align": "left",
      "heading-size": "clamp(1.25rem, 3vw, 2rem)",
      "heading-align": "left",
      "heading-max-width": "36rem",
      "heading-margin-bottom": "12px",
      "description-max-width": "28rem",
      "description-gap": "8px",
      "content-gap": "16px",
      "grid-columns": "3",
      "grid-gap": "16px",
      "alternate-bg": "var(--s-surface)",
      "alternate-bg-mode": "none",
      "divider-above": false,
      "divider-below": true,
      "background-alt": false,
      indent: "0px",
    },
    dividers: {
      style: "solid",
      width: "3px",
      color: "var(--s-border-muted)",
      spacing: "0px",
      opacity: "1",
      "max-width": "100%",
      "margin-y": "0px",
      thickness: "2px",
      "gradient-start": "transparent",
      "gradient-end": "transparent",
      "show-cross": false,
      "show-label": false,
      "full-bleed": true,
      ornament: "none",
    },
    gridVisuals: {
      "show-lines": true,
      "line-color": "var(--s-border-muted)",
      "line-width": "2px",
      "show-dots": false,
      "dot-size": "2px",
      "cell-background": "none",
      "cell-border": true,
      "cell-radius": "0px",
      "cell-padding": "16px",
      "hover-effect": "border",
    },
    cursor: {
      variant: "crosshair",
      size: "24px",
      "dot-size": "4px",
      "stroke-width": "2px",
      "tick-size": "6px",
      gap: "3px",
      radius: "0px",
      color: "var(--s-text)",
      "ring-color": "var(--s-primary)",
      "dot-color": "var(--s-primary)",
      glow: "none",
      opacity: "1",
      "blend-mode": "normal",
      "z-index": "9999",
      "hide-native": false,
    },
    scrollbar: {
      width: "10px",
      height: "10px",
      padding: "2px",
      radius: "2px",
      track: "transparent",
      thumb: "var(--s-border-muted)",
      "thumb-hover": "var(--s-border)",
      "thumb-active": "var(--s-border-strong)",
      corner: "transparent",
      border: "none",
      "firefox-width": "auto",
      gutter: "stable",
      visibility: "auto",
    },
    focus: {
      "ring-width": "3px",
      "ring-color": "var(--s-primary)",
      "ring-offset": "0px",
      "ring-shadow": "0 0 0 3px var(--s-primary)",
      "outline-color": "var(--s-primary)",
    },
    overlays: {
      bg: "rgb(0 0 0 / 0.6)",
      blur: "4px",
      surface: "var(--s-surface-elevated)",
      border: "1px solid var(--s-border-muted)",
      shadow: "var(--s-shadow-xl)",
      radius: "var(--s-radius-lg)",
      padding: "20px",
      "z-index": "50",
    },
    dataViz: {
      "series-1": "var(--s-primary)",
      "series-2": "var(--s-secondary)",
      "series-3": "var(--s-accent)",
      "series-4": "var(--s-info)",
      "series-5": "var(--s-success)",
      positive: "var(--s-success)",
      negative: "var(--s-error)",
      neutral: "var(--s-text-muted)",
      grid: "var(--s-border-muted)",
      axis: "var(--s-border)",
      label: "var(--s-text-secondary)",
      "tooltip-bg": "var(--s-surface-elevated)",
      "tooltip-border": "var(--s-border-muted)",
    },
    media: {
      radius: "var(--s-radius-md)",
      border: "none",
      outline: "1px solid rgb(0 0 0 / 0.08)",
      shadow: "none",
      bg: "var(--s-surface-sunken)",
      "object-fit": "cover",
    },
    controls: {
      height: "38px",
      "height-sm": "30px",
      "height-lg": "46px",
      "hit-area": "44px",
      "icon-size": "16px",
      "handle-size": "20px",
      "track-height": "4px",
      "track-bg": "var(--s-border-muted)",
      "track-fill": "var(--s-primary)",
      "thumb-bg": "var(--s-surface-elevated)",
      "thumb-border": "2px solid var(--s-primary)",
    },
    componentSurfaces: {
      bg: "var(--s-surface)",
      "bg-elevated": "var(--s-surface-elevated)",
      "bg-muted": "var(--s-surface-sunken)",
      border: "var(--s-border)",
      "border-muted": "var(--s-border-muted)",
      "border-strong": "var(--s-border-strong)",
      text: "var(--s-text)",
      "text-muted": "var(--s-text-muted)",
      contrast: "var(--s-primary-contrast)",
      "hover-bg": "var(--s-surface-elevated)",
      "active-bg": "var(--s-surface-sunken)",
      "selected-bg": "var(--s-primary-muted)",
    },
    hero: {
      "min-height": "auto",
      "padding-y": "72px",
      "padding-y-sm": "48px",
      "padding-x": "var(--s-page-margin, 20px)",
      "content-max": "560px",
      "content-align": "left",
      layout: "split",
      "media-position": "right",
      "media-width": "45%",
      "media-radius": "var(--s-radius-sm)",
      "title-size": "clamp(1.75rem, 5vw, 3rem)",
      "title-max-width": "40rem",
      "description-size": "1rem",
      "description-max-width": "28rem",
      "description-gap": "16px",
      "actions-gap": "10px",
      "actions-margin-top": "24px",
      "action-padding-x": "20px",
      "action-padding-y": "10px",
      "badge-gap": "16px",
      "overlay-opacity": "0.6",
      "scroll-indicator": false,
      "gradient-overlay": "none",
    },
    cta: {
      "padding-y": "48px",
      "padding-x": "var(--s-page-margin, 20px)",
      "max-width": "var(--s-content-max, 1200px)",
      layout: "split",
      border: true,
      "border-radius": "var(--s-radius-sm)",
      bg: "var(--s-surface)",
      "title-size": "clamp(1.25rem, 3vw, 2rem)",
      "description-max-width": "28rem",
      "description-gap": "8px",
      "actions-gap": "10px",
      "actions-margin-top": "20px",
      "action-padding-x": "20px",
      "action-padding-y": "10px",
      "split-gap": "24px",
    },
    footer: {
      "padding-y": "48px",
      "border-top": "2px solid var(--s-border-strong)",
      columns: "4",
      "column-gap": "24px",
      "row-gap": "24px",
      "logo-height": "20px",
      "tagline-max-width": "18rem",
      "link-size": "0.8125rem",
      "link-gap": "6px",
      "group-title-size": "0.75rem",
      "group-title-weight": "700",
      "social-icon-size": "16px",
      "social-gap": "10px",
      "bottom-bar-padding": "24px 0",
      "bottom-bar-border": "2px solid var(--s-border)",
    },
    banner: {
      height: "auto",
      "padding-y": "6px",
      "padding-x": "16px",
      "font-size": "0.8125rem",
      "font-weight": "600",
      "icon-size": "14px",
      "icon-gap": "8px",
      "border-width": "2px",
      "border-position": "bottom",
      position: "top",
      "dismiss-size": "14px",
      radius: "0px",
    },
    pageRhythm: {
      density: "compact",
      "section-gap": "0px",
      "section-gap-sm": "0px",
      "section-gap-lg": "0px",
      "first-section-offset": "0px",
      "last-section-margin": "0px",
      "alternate-bg": false,
      "alternate-bg-color": "var(--s-surface)",
      "divider-between": true,
      "max-content-width": "var(--s-content-max, 1200px)",
      "vertical-rhythm-unit": "4px",
      "scroll-snap": false,
      "responsive-scale": "1",
      "responsive-breakpoint": "768px",
    },

  },
};
