import type { SigilPreset } from "@sigil-ui/tokens";

export const forgePreset: SigilPreset = {
  name: "forge",
  metadata: {
    description: "Hot metal. Orange fire, heavy weight, blacksmith intensity. Built to endure.",
    mood: "hot, heavy, forged",
    tags: ["dark", "fire", "orange", "heavy", "industrial", "blacksmith"],
  },
  tokens: {
    colors: {
      background: { light: "oklch(0.97 0.004 50)", dark: "oklch(0.1 0.008 40)" },
      surface: { light: "oklch(0.955 0.005 50)", dark: "oklch(0.14 0.008 40)" },
      "surface-elevated": { light: "oklch(0.985 0.003 50)", dark: "oklch(0.18 0.008 40)" },
      "surface-sunken": { light: "oklch(0.935 0.006 50)", dark: "oklch(0.07 0.008 40)" },
      primary: "oklch(0.66 0.2 45)",
      "primary-hover": "oklch(0.62 0.22 45)",
      "primary-muted": "oklch(0.68 0.08 45)",
      "primary-contrast": "oklch(0.08 0 0)",
      secondary: "oklch(0.55 0.2 25)",
      "secondary-hover": "oklch(0.48 0.22 25)",
      "secondary-muted": "oklch(0.55 0.07 25)",
      accent: "oklch(0.8 0.15 65)",
      "accent-hover": "oklch(0.74 0.17 65)",
      "accent-muted": "oklch(0.8 0.06 65)",
      text: { light: "oklch(0.12 0.008 40)", dark: "oklch(0.92 0.006 50)" },
      "text-secondary": { light: "oklch(0.32 0.006 40)", dark: "oklch(0.74 0.006 50)" },
      "text-muted": { light: "oklch(0.48 0.005 40)", dark: "oklch(0.63 0.005 50)" },
      "text-subtle": { light: "oklch(0.6 0.004 40)", dark: "oklch(0.51 0.004 50)" },
      "text-disabled": { light: "oklch(0.72 0.003 40)", dark: "oklch(0.34 0.003 50)" },
      "text-inverse": { light: "oklch(0.92 0.006 50)", dark: "oklch(0.12 0.008 40)" },
      border: { light: "oklch(0.64 0.008 45)", dark: "oklch(0.48 0.01 40)" },
      "border-muted": { light: "oklch(0.9 0.006 45)", dark: "oklch(0.25 0.008 40)" },
      "border-strong": { light: "oklch(0.64 0.012 45)", dark: "oklch(0.48 0.014 40)" },
      "border-interactive": { light: "oklch(0.68 0.2 45)", dark: "oklch(0.68 0.2 45)" },
      success: "oklch(0.62 0.17 150)",
      "success-muted": "oklch(0.7 0.06 150)",
      warning: "oklch(0.65 0.17 65)",
      "warning-muted": "oklch(0.8 0.06 65)",
      error: "oklch(0.55 0.23 25)",
      "error-muted": "oklch(0.55 0.08 25)",
      info: "oklch(0.64 0.13 245)",
      "info-muted": "oklch(0.65 0.05 245)",
      "gradient-start": "oklch(0.68 0.2 45)",
      "gradient-end": "oklch(0.55 0.2 25)",
      glow: "oklch(0.68 0.2 45 / 0.45)",
    },
    typography: {
      "font-display": "'Tex Gyre Heros', system-ui, sans-serif",
      "font-body": "'PP Supply Sans', system-ui, sans-serif",
      "font-mono": "'PP Supply Mono', ui-monospace, monospace",
      "size-xs": "0.75rem",
      "size-sm": "0.875rem",
      "size-base": "1rem",
      "size-lg": "1.1875rem",
      "size-xl": "1.375rem",
      "size-2xl": "1.75rem",
      "size-3xl": "2.125rem",
      "size-4xl": "2.75rem",
      "size-5xl": "3.5rem",
      "size-6xl": "4.5rem",
      "weight-normal": "400",
      "weight-medium": "500",
      "weight-semibold": "600",
      "weight-bold": "700",
      "weight-extrabold": "800",
      "leading-tight": "1.15",
      "leading-normal": "1.5",
      "leading-relaxed": "1.625",
      "leading-loose": "1.875",
      "tracking-tighter": "-0.05em",
      "tracking-tight": "-0.025em",
      "tracking-normal": "0em",
      "tracking-wide": "0.03em",
      "tracking-wider": "0.06em",
      "heading-weight": "700",
      "heading-tracking": "0.06em",
      "heading-transform": "uppercase",
      "heading-family": "'Tex Gyre Heros', system-ui, sans-serif",
    },
    spacing: {
      scale: [4, 8, 16, 20, 28, 40, 56, 72, 96, 120],
      unit: "px",
      "button-px": "28px",
      "button-py": "14px",
      "button-px-sm": "20px",
      "button-py-sm": "10px",
      "button-px-lg": "40px",
      "button-py-lg": "18px",
      "card-padding": "28px",
      "card-padding-sm": "20px",
      "card-padding-lg": "40px",
      "input-px": "14px",
      "input-py": "10px",
      "badge-px": "10px",
      "badge-py": "3px",
      "section-py": "96px",
      "section-py-lg": "144px",
      "navbar-height": "80px",
      "navbar-px": "36px",
      "footer-py": "64px",
      "modal-padding": "28px",
      "popover-padding": "18px",
      "tooltip-padding": "8px 14px",
      "table-cell-px": "18px",
      "table-cell-py": "14px",
    },
    layout: {
      "content-max": "1200px",
      "content-max-narrow": "720px",
      "content-max-wide": "1440px",
      "page-margin": "32px",
      "page-margin-sm": "16px",
      "page-margin-lg": "64px",
      gutter: "36px",
      "gutter-sm": "16px",
      "gutter-lg": "48px",
      "grid-columns": "12",
      "grid-gap": "32px",
      "bento-gap": "18px",
      "bento-radius": "6px",
      "bento-min-height": "240px",
      "section-gap": "40px",
      "sidebar-width": "320px",
      "sidebar-collapsed": "64px",
      "footer-columns": "4",
      "stack-gap": "16px",
      "stack-gap-sm": "8px",
      "stack-gap-lg": "28px",
      "prose-max": "66ch",
    },
    sigil: {
      "grid-cell": "48px",
      "cross-arm": "16px",
      "cross-stroke": "2.5px",
      "rail-gap": "24px",
      "card-radius": "6px",
      "gutter-pattern": "crosshatch",
      "margin-pattern": "brick",
    },
    radius: {
      none: "0px",
      sm: "2px",
      md: "4px",
      lg: "6px",
      xl: "8px",
      "2xl": "12px",
      full: "9999px",
      button: "4px",
      card: "6px",
      input: "4px",
      badge: "9999px",
      modal: "8px",
      popover: "6px",
      tooltip: "4px",
      image: "4px",
      bento: "6px",
    },
    shadows: {
      sm: "0 1px 3px 0 rgb(0 0 0 / 0.1)",
      md: "0 2px 8px -1px rgb(0 0 0 / 0.15), 0 0 0 1px rgb(0 0 0 / 0.05)",
      lg: "0 8px 20px -4px rgb(0 0 0 / 0.2), 0 4px 8px -2px rgb(0 0 0 / 0.08)",
      xl: "0 16px 36px -6px rgb(0 0 0 / 0.22), 0 6px 12px -3px rgb(0 0 0 / 0.08)",
      "2xl": "0 32px 64px -16px rgb(0 0 0 / 0.3)",
      glow: "0 0 32px var(--s-primary)",
      "glow-sm": "0 0 16px var(--s-primary)",
      colored: "0 8px 24px -6px var(--s-primary)",
      inner: "inset 0 3px 6px 0 rgb(0 0 0 / 0.1)",
      card: "0 4px 12px -2px rgb(0 0 0 / 0.12), 0 0 0 1px rgb(0 0 0 / 0.05)",
      button: "0 1px 3px 0 rgb(0 0 0 / 0.1)",
      "button-hover": "0 0 24px var(--s-primary)",
      dropdown: "0 10px 30px -6px rgb(0 0 0 / 0.2), 0 0 0 1px rgb(0 0 0 / 0.05)",
      modal: "0 28px 72px -16px rgb(0 0 0 / 0.35)",
    },
    motion: {
      duration: { instant: "0ms", fast: "120ms", normal: "240ms", slow: "400ms", slower: "600ms", slowest: "1000ms" },
      easing: {
        default: "cubic-bezier(0.16, 1, 0.3, 1)",
        in: "cubic-bezier(0.6, 0, 1, 0.4)",
        out: "cubic-bezier(0, 0.6, 0.4, 1)",
        "in-out": "cubic-bezier(0.5, 0, 0.5, 1)",
        spring: "cubic-bezier(0.34, 1.56, 0.64, 1)",
        bounce: "cubic-bezier(0.68, -0.55, 0.27, 1.55)",
      },
      "enter-preset": "scaleUp",
      "exit-preset": "fadeOut",
      "hover-scale": "1.03",
      "press-scale": "0.95",
      "hover-lift": "-3px",
      "stagger-interval": "40ms",
      "stagger-interval-fast": "20ms",
    },
    borders: {
      width: { none: "0px", thin: "1px", medium: "2px", thick: "3px" },
      style: "solid",
      "card-border": "2px solid",
      "card-border-hover": "2px solid",
      "button-border": "2px solid",
      "input-border": "2px solid",
      "divider-style": "solid",
      "divider-width": "2px",
    },
    buttons: {
      "font-weight": "800",
      "text-transform": "uppercase",
      "letter-spacing": "0.06em",
      "font-family": "'PP Supply Sans', system-ui, sans-serif",
      "border-width": "2px",
      "hover-effect": "glow",
      "active-scale": "0.95",
      "icon-gap": "10px",
      "min-width": "0px",
    },
    cards: {
      "border-style": "solid",
      "border-width": "2px",
      "hover-effect": "lift",
      "hover-border-color": "var(--s-primary)",
      padding: "28px",
      "header-padding": "28px 28px 0",
      "footer-padding": "0 28px 28px",
      "title-size": "1.1875rem",
      "title-weight": "800",
      "description-size": "0.875rem",
      background: "surface",
      shadow: "none",
      outline: true,
      "outline-on-hover-only": false,
      "gap-between": "16px",
      "content-padding-x": "28px",
      "content-padding-y": "20px",
    },
    headings: {
      "h1-size": "2.75rem",
      "h1-weight": "800",
      "h1-tracking": "-0.035em",
      "h1-leading": "1.1",
      "h2-size": "2.125rem",
      "h2-weight": "800",
      "h2-tracking": "-0.03em",
      "h3-size": "1.75rem",
      "h3-weight": "700",
      "h4-size": "1.375rem",
      "h4-weight": "700",
      "display-size": "4.5rem",
      "display-weight": "800",
      "display-tracking": "-0.05em",
      "display-leading": "1.0",
    },
    navigation: {
      "navbar-height": "80px",
      "navbar-backdrop-blur": "8px",
      "navbar-border": "3px solid",
      "navbar-bg-opacity": "0.95",
      "nav-link-weight": "700",
      "nav-link-size": "0.875rem",
      "nav-link-hover": "color",
      "breadcrumb-separator": "//",
      "pagination-radius": "4px",
      "sidebar-width": "320px",
      "sidebar-item-radius": "4px",
      "sidebar-item-padding": "12px 16px",
    },
    backgrounds: {
      pattern: "crosshatch",
      "pattern-opacity": "0.06",
      "pattern-scale": "0.8",
      noise: true,
      "noise-opacity": "0.03",
      "gradient-angle": "150deg",
      "gradient-type": "none",
      "hero-pattern": "crosshatch",
      "section-divider": "zigzag",
    },
    code: {
      "font-family": "'PP Supply Mono', ui-monospace, monospace",
      "font-size": "0.875rem",
      "line-height": "1.65",
      bg: "var(--s-surface-sunken)",
      border: "2px solid var(--s-border)",
      "border-radius": "4px",
      padding: "18px",
      "tab-size": "4",
      "selection-bg": "var(--s-primary-muted)",
      "comment-color": "var(--s-text-muted)",
      "keyword-color": "var(--s-primary)",
      "string-color": "var(--s-accent)",
      "number-color": "var(--s-secondary)",
      "function-color": "var(--s-info)",
    },
    inputs: {
      height: "44px",
      "height-sm": "36px",
      "height-lg": "52px",
      "border-width": "2px",
      "focus-ring-width": "3px",
      "focus-ring-color": "var(--s-primary)",
      "focus-ring-offset": "0px",
      "placeholder-color": "var(--s-text-subtle)",
      "error-border-color": "var(--s-error)",
      "label-size": "0.75rem",
      "label-weight": "700",
      "label-spacing": "6px",
      "helper-size": "0.75rem",
    },
    alignment: {
      "rail-width": "1360px",
      "rail-columns": "12",
      "rail-gutter": "28px",
      "rail-margin": "16px",
      "rail-visible": false,
      "rail-color": "var(--s-border-muted)",
      "content-align": "center",
      "hero-align": "center",
      "section-align": "center",
      "navbar-align": "full",
      "footer-align": "content",
    },
    sections: {
      "padding-y": "48px",
      "padding-y-hero": "96px",
      "padding-x": "16px",
      "max-width": "1360px",
      gap: "24px",
      "title-align": "left",
      "divider-above": false,
      "divider-below": true,
      "background-alt": false,
      indent: "0px",
    },
    dividers: {
      style: "solid",
      width: "3px",
      color: "var(--s-border)",
      spacing: "0px",
      "show-cross": false,
      "show-label": false,
      "full-bleed": true,
      ornament: "none",
    },
    gridVisuals: {
      "show-lines": true,
      "line-color": "var(--s-border-muted)",
      "line-width": "2px",
      "show-dots": false,
      "dot-size": "2px",
      "cell-background": "none",
      "cell-border": true,
      "cell-radius": "0px",
      "cell-padding": "16px",
      "hover-effect": "border",
    },
  },
};
