import type { SigilPreset } from "@sigil-ui/tokens";

export const glyphPreset: SigilPreset = {
  name: "glyph",
  metadata: {
    description: "Typographic character — type-as-design, letter-focused, the typeface IS the decoration.",
    mood: "typographic, character-focused, type-is-design",
    tags: ["typographic", "editorial", "type", "letterform", "display"],
    author: "sigil-ui",
    version: "0.1.0",
  },
  tokens: {
    colors: {
      background: { light: "oklch(0.985 0 0)", dark: "oklch(0.07 0 0)" },
      surface: { light: "oklch(0.97 0 0)", dark: "oklch(0.11 0 0)" },
      "surface-elevated": { light: "oklch(1 0 0)", dark: "oklch(0.15 0 0)" },
      "surface-sunken": { light: "oklch(0.955 0 0)", dark: "oklch(0.05 0 0)" },
      primary: "oklch(0.55 0.22 25)",
      "primary-hover": "oklch(0.48 0.24 25)",
      "primary-muted": "oklch(0.88 0.06 25)",
      "primary-contrast": "oklch(1 0 0)",
      secondary: "oklch(0.35 0.04 0)",
      "secondary-hover": "oklch(0.28 0.05 0)",
      "secondary-muted": "oklch(0.75 0.02 0)",
      accent: "oklch(0.55 0.18 25)",
      "accent-hover": "oklch(0.48 0.2 25)",
      "accent-muted": "oklch(0.85 0.06 25)",
      text: { light: "oklch(0.08 0 0)", dark: "oklch(0.94 0 0)" },
      "text-secondary": { light: "oklch(0.3 0 0)", dark: "oklch(0.72 0 0)" },
      "text-muted": { light: "oklch(0.48 0 0)", dark: "oklch(0.63 0 0)" },
      "text-subtle": { light: "oklch(0.62 0 0)", dark: "oklch(0.50 0 0)" },
      "text-disabled": { light: "oklch(0.75 0 0)", dark: "oklch(0.32 0 0)" },
      "text-inverse": { light: "oklch(0.96 0 0)", dark: "oklch(0.1 0 0)" },
      border: { light: "oklch(0.65 0 0)", dark: "oklch(0.47 0 0)" },
      "border-muted": { light: "oklch(0.91 0 0)", dark: "oklch(0.23 0 0)" },
      "border-strong": { light: "oklch(0.65 0 0)", dark: "oklch(0.47 0 0)" },
      "border-interactive": { light: "oklch(0.55 0.22 25)", dark: "oklch(0.6 0.22 25)" },
      success: "oklch(0.63 0.17 155)",
      "success-muted": "oklch(0.65 0.05 155)",
      warning: "oklch(0.65 0.14 80)",
      "warning-muted": "oklch(0.78 0.05 80)",
      error: "oklch(0.55 0.22 25)",
      "error-muted": "oklch(0.55 0.07 25)",
      info: "oklch(0.6 0.14 250)",
      "info-muted": "oklch(0.6 0.05 250)",
      "gradient-start": "oklch(0.55 0.22 25)",
      "gradient-end": "oklch(0.35 0.04 0)",
      glow: "oklch(0.55 0.22 25 / 0.2)",
    },
    typography: {
      "font-display": "'Migra', Georgia, serif",
      "font-body": "'PP Editorial New', Georgia, serif",
      "font-mono": "'PP Supply Mono', ui-monospace, monospace",
      "size-xs": "0.75rem",
      "size-sm": "0.875rem",
      "size-base": "1.0625rem",
      "size-lg": "1.1875rem",
      "size-xl": "1.375rem",
      "size-2xl": "1.75rem",
      "size-3xl": "2.125rem",
      "size-4xl": "2.75rem",
      "size-5xl": "3.5rem",
      "size-6xl": "4.5rem",
      "weight-normal": "400",
      "weight-medium": "500",
      "weight-semibold": "600",
      "weight-bold": "700",
      "weight-extrabold": "800",
      "leading-tight": "1.15",
      "leading-normal": "1.6",
      "leading-relaxed": "1.75",
      "leading-loose": "2.1",
      "tracking-tighter": "-0.06em",
      "tracking-tight": "-0.03em",
      "tracking-normal": "0em",
      "tracking-wide": "0.04em",
      "tracking-wider": "0.08em",
      "heading-weight": "200",
      "heading-tracking": "0em",
      "heading-transform": "none",
      "heading-family": "'Migra', Georgia, serif",
    },
    spacing: {
      scale: [4, 8, 16, 24, 36, 48, 72, 96, 128, 160],
      unit: "px",
      "button-px": "24px",
      "button-py": "10px",
      "button-px-sm": "16px",
      "button-py-sm": "7px",
      "button-px-lg": "32px",
      "button-py-lg": "14px",
      "card-padding": "40px",
      "card-padding-sm": "28px",
      "card-padding-lg": "56px",
      "input-px": "14px",
      "input-py": "10px",
      "badge-px": "10px",
      "badge-py": "3px",
      "section-py": "120px",
      "section-py-lg": "176px",
      "navbar-height": "80px",
      "navbar-px": "40px",
      "footer-py": "80px",
      "modal-padding": "32px",
      "popover-padding": "16px",
      "tooltip-padding": "6px 12px",
      "table-cell-px": "16px",
      "table-cell-py": "12px",
    },
    layout: {
      "content-max": "1200px",
      "content-max-narrow": "720px",
      "content-max-wide": "1440px",
      "page-margin": "44px",
      "page-margin-sm": "20px",
      "page-margin-lg": "80px",
      gutter: "44px",
      "gutter-sm": "16px",
      "gutter-lg": "60px",
      "grid-columns": "12",
      "grid-gap": "40px",
      "bento-gap": "28px",
      "bento-radius": "0px",
      "bento-min-height": "200px",
      "section-gap": "36px",
      "sidebar-width": "240px",
      "sidebar-collapsed": "56px",
      "footer-columns": "3",
      "stack-gap": "18px",
      "stack-gap-sm": "10px",
      "stack-gap-lg": "28px",
      "prose-max": "58ch",
    },
    sigil: {
      "grid-cell": "68px",
      "cross-arm": "16px",
      "cross-stroke": "1.5px",
      "rail-gap": "36px",
      "card-radius": "0px",
      "gutter-pattern": "wave",
      "margin-pattern": "dots",
    },
    radius: {
      none: "0px",
      sm: "0px",
      md: "0px",
      lg: "0px",
      xl: "0px",
      "2xl": "0px",
      full: "9999px",
      button: "0px",
      card: "0px",
      input: "0px",
      badge: "0px",
      modal: "0px",
      popover: "0px",
      tooltip: "0px",
      image: "0px",
      bento: "0px",
    },
    shadows: {
      sm: "0 1px 2px rgb(0 0 0 / 0.03)",
      md: "0 2px 4px rgb(0 0 0 / 0.04)",
      lg: "0 4px 8px rgb(0 0 0 / 0.05)",
      xl: "0 8px 16px rgb(0 0 0 / 0.06)",
      "2xl": "0 20px 40px -12px rgb(0 0 0 / 0.12)",
      glow: "0 0 20px var(--s-primary)",
      "glow-sm": "0 0 10px var(--s-primary)",
      colored: "0 4px 14px -3px var(--s-primary)",
      inner: "inset 0 1px 2px 0 rgb(0 0 0 / 0.04)",
      card: "none",
      button: "none",
      "button-hover": "none",
      dropdown: "0 4px 12px rgb(0 0 0 / 0.08), 0 0 0 1px rgb(0 0 0 / 0.04)",
      modal: "0 16px 48px -8px rgb(0 0 0 / 0.15)",
    },
    motion: {
      duration: { instant: "0ms", fast: "150ms", normal: "280ms", slow: "450ms", slower: "650ms", slowest: "1000ms" },
      easing: {
        default: "cubic-bezier(0.22, 1, 0.36, 1)",
        in: "cubic-bezier(0.55, 0, 1, 0.45)",
        out: "cubic-bezier(0, 0.55, 0.45, 1)",
        "in-out": "cubic-bezier(0.45, 0, 0.55, 1)",
        spring: "cubic-bezier(0.34, 1.56, 0.64, 1)",
        bounce: "cubic-bezier(0.68, -0.55, 0.27, 1.55)",
      },
      "enter-preset": "fadeUp",
      "exit-preset": "fadeOut",
      "hover-scale": "1.0",
      "press-scale": "0.98",
      "hover-lift": "0px",
      "stagger-interval": "55ms",
      "stagger-interval-fast": "28ms",
    },
    borders: {
      width: { none: "0px", thin: "1px", medium: "1.5px", thick: "2px" },
      style: "dashed",
      "card-border": "1px dashed",
      "card-border-hover": "1px dashed",
      "button-border": "none",
      "input-border": "1px solid",
      "divider-style": "solid",
      "divider-width": "1px",
    },
    buttons: {
      "font-weight": "700",
      "text-transform": "lowercase",
      "letter-spacing": "0.06em",
      "font-family": "'PP Editorial New', Georgia, serif",
      "border-width": "0px",
      "hover-effect": "darken",
      "active-scale": "0.97",
      "icon-gap": "10px",
      "min-width": "0px",
    },
    cards: {
      "border-style": "none",
      "border-width": "0px",
      "hover-effect": "lift",
      "hover-border-color": "var(--s-border)",
      padding: "36px",
      "header-padding": "36px 36px 0",
      "footer-padding": "0 36px 36px",
      "title-size": "1.375rem",
      "title-weight": "700",
      "description-size": "0.9375rem",
      background: "transparent",
      shadow: "none",
      outline: false,
      "outline-on-hover-only": false,
      "gap-between": "20px",
      "content-padding-x": "36px",
      "content-padding-y": "28px",
    },
    headings: {
      "h1-size": "2.75rem",
      "h1-weight": "800",
      "h1-tracking": "-0.05em",
      "h1-leading": "1.1",
      "h2-size": "2.125rem",
      "h2-weight": "700",
      "h2-tracking": "-0.04em",
      "h3-size": "1.75rem",
      "h3-weight": "700",
      "h4-size": "1.375rem",
      "h4-weight": "600",
      "display-size": "5rem",
      "display-weight": "800",
      "display-tracking": "-0.06em",
      "display-leading": "1.0",
    },
    navigation: {
      "navbar-height": "80px",
      "navbar-backdrop-blur": "8px",
      "navbar-border": "1px solid",
      "navbar-bg-opacity": "0.92",
      "nav-link-weight": "400",
      "nav-link-size": "0.9375rem",
      "nav-link-hover": "underline",
      "breadcrumb-separator": "—",
      "pagination-radius": "0px",
      "sidebar-width": "240px",
      "sidebar-item-radius": "0px",
      "sidebar-item-padding": "12px 18px",
    },
    backgrounds: {
      pattern: "none",
      "pattern-opacity": "0",
      "pattern-scale": "1",
      noise: true,
      "noise-opacity": "0.02",
      "gradient-angle": "180deg",
      "gradient-type": "none",
      "hero-pattern": "noise",
      "section-divider": "line",
    },
    code: {
      "font-family": "'PP Supply Mono', ui-monospace, monospace",
      "font-size": "0.875rem",
      "line-height": "1.7",
      bg: "var(--s-surface-sunken)",
      border: "1px dashed var(--s-border)",
      "border-radius": "0px",
      padding: "18px",
      "tab-size": "2",
      "selection-bg": "var(--s-primary-muted)",
      "comment-color": "var(--s-text-muted)",
      "keyword-color": "var(--s-primary)",
      "string-color": "var(--s-success)",
      "number-color": "var(--s-warning)",
      "function-color": "var(--s-info)",
    },
    inputs: {
      height: "42px",
      "height-sm": "34px",
      "height-lg": "50px",
      "border-width": "1px",
      "focus-ring-width": "2px",
      "focus-ring-color": "var(--s-primary)",
      "focus-ring-offset": "2px",
      "placeholder-color": "var(--s-text-subtle)",
      "error-border-color": "var(--s-error)",
      "label-size": "0.875rem",
      "label-weight": "600",
      "label-spacing": "8px",
      "helper-size": "0.75rem",
    },
    alignment: {
      "title-align": "left",
    },
    sections: {
      "rail-margin": "48px",
      "padding-y": "80px",
      "padding-y-hero": "160px",
      gap: "40px",
      "max-width": "800px",
      indent: "0px",
    },
    dividers: {
      style: "solid",
      width: "3px",
    },
    gridVisuals: {
      "show-lines": false,
      "show-dots": false,
    },
  },
};
