import type { SigilPreset } from "@sigil-ui/tokens";

export const glyphPreset: SigilPreset = {
  name: "glyph",
  metadata: {
    description: "Typographic character — type-as-design, letter-focused, the typeface IS the decoration.",
    mood: "typographic, character-focused, type-is-design",
    tags: ["typographic", "editorial", "type", "letterform", "display"],
    author: "sigil-ui",
    version: "0.1.0",
  },
  tokens: {
    colors: {
      background: { light: "oklch(0.985 0 0)", dark: "oklch(0.07 0 0)" },
      surface: { light: "oklch(0.97 0 0)", dark: "oklch(0.11 0 0)" },
      "surface-elevated": { light: "oklch(1 0 0)", dark: "oklch(0.15 0 0)" },
      "surface-sunken": { light: "oklch(0.955 0 0)", dark: "oklch(0.05 0 0)" },
      primary: "oklch(0.55 0.22 25)",
      "primary-hover": "oklch(0.48 0.24 25)",
      "primary-muted": "oklch(0.88 0.06 25)",
      "primary-contrast": "oklch(1 0 0)",
      secondary: "oklch(0.35 0.04 0)",
      "secondary-hover": "oklch(0.28 0.05 0)",
      "secondary-muted": "oklch(0.75 0.02 0)",
      accent: "oklch(0.55 0.18 25)",
      "accent-hover": "oklch(0.48 0.2 25)",
      "accent-muted": "oklch(0.85 0.06 25)",
      text: { light: "oklch(0.08 0 0)", dark: "oklch(0.94 0 0)" },
      "text-secondary": { light: "oklch(0.3 0 0)", dark: "oklch(0.72 0 0)" },
      "text-muted": { light: "oklch(0.48 0 0)", dark: "oklch(0.63 0 0)" },
      "text-subtle": { light: "oklch(0.62 0 0)", dark: "oklch(0.50 0 0)" },
      "text-disabled": { light: "oklch(0.75 0 0)", dark: "oklch(0.32 0 0)" },
      "text-inverse": { light: "oklch(0.96 0 0)", dark: "oklch(0.1 0 0)" },
      border: { light: "oklch(0.65 0 0)", dark: "oklch(0.250 0.006 0)" },
      "border-muted": { light: "oklch(0.82 0.006 0)", dark: "oklch(0.190 0.006 0)" },
      "border-strong": { light: "oklch(0.50 0.005 0)", dark: "oklch(0.330 0.005 0)" },
      "border-interactive": { light: "oklch(0.55 0.22 25)", dark: "oklch(0.6 0.22 25)" },
      success: "oklch(0.63 0.17 155)",
      "success-muted": "oklch(0.65 0.05 155)",
      warning: "oklch(0.65 0.14 80)",
      "warning-muted": "oklch(0.78 0.05 80)",
      error: "oklch(0.60 0.23 18)",
      "error-muted": "oklch(0.55 0.07 25)",
      info: "oklch(0.6 0.14 250)",
      "info-muted": "oklch(0.6 0.05 250)",
      "gradient-start": "oklch(0.55 0.22 25)",
      "gradient-end": "oklch(0.35 0.04 0)",
      glow: "oklch(0.55 0.22 25 / 0.2)",
      highlight: { light: "oklch(0.93 0.08 25)", dark: "oklch(0.28 0.06 25)" },
    },
    typography: {
      "font-display": "'Migra', Georgia, serif",
      "font-body": "'PP Editorial New', Georgia, serif",
      "font-mono": "'PP Supply Mono', ui-monospace, monospace",
      "size-xs": "0.75rem",
      "size-sm": "0.875rem",
      "size-base": "1.0625rem",
      "size-lg": "1.1875rem",
      "size-xl": "1.375rem",
      "size-2xl": "1.75rem",
      "size-3xl": "2.125rem",
      "size-4xl": "2.75rem",
      "size-5xl": "3.5rem",
      "size-6xl": "4.5rem",
      "weight-normal": "400",
      "weight-medium": "500",
      "weight-semibold": "600",
      "weight-bold": "700",
      "weight-extrabold": "800",
      "leading-tight": "1.15",
      "leading-normal": "1.6",
      "leading-relaxed": "1.75",
      "leading-loose": "2.1",
      "tracking-tighter": "-0.06em",
      "tracking-tight": "-0.03em",
      "tracking-normal": "0em",
      "tracking-wide": "0.04em",
      "tracking-wider": "0.08em",
      "heading-weight": "200",
      "heading-tracking": "0em",
      "heading-transform": "none",
      "heading-family": "'Migra', Georgia, serif",
    },
    spacing: {
      scale: [4, 8, 16, 24, 36, 48, 72, 96, 128, 160],
      unit: "px",
      "button-px": "24px",
      "button-py": "10px",
      "button-px-sm": "16px",
      "button-py-sm": "7px",
      "button-px-lg": "32px",
      "button-py-lg": "14px",
      "card-padding": "40px",
      "card-padding-sm": "28px",
      "card-padding-lg": "56px",
      "input-px": "14px",
      "input-py": "10px",
      "badge-px": "10px",
      "badge-py": "3px",
      "section-py": "8.5rem",
      "section-py-lg": "12.75rem",
      "navbar-height": "68px",
      "navbar-px": "40px",
      "footer-py": "68px",
      "modal-padding": "32px",
      "popover-padding": "16px",
      "tooltip-padding": "6px 12px",
      "table-cell-px": "16px",
      "table-cell-py": "12px",
    },
    layout: {
      "content-max": "1200px",
      "content-max-narrow": "720px",
      "content-max-wide": "1440px",
      "page-margin": "44px",
      "page-margin-sm": "20px",
      "page-margin-lg": "80px",
      gutter: "44px",
      "gutter-sm": "16px",
      "gutter-lg": "60px",
      "grid-columns": "12",
      "grid-gap": "40px",
      "bento-gap": "28px",
      "bento-radius": "0px",
      "bento-min-height": "204px",
      "section-gap": "34px",
      "sidebar-width": "240px",
      "sidebar-collapsed": "56px",
      "footer-columns": "3",
      "stack-gap": "18px",
      "stack-gap-sm": "10px",
      "stack-gap-lg": "28px",
      "prose-max": "58ch",
    },
    sigil: {
      "grid-cell": "68px",
      "cross-arm": "16px",
      "cross-stroke": "1.5px",
      "rail-gap": "36px",
      "card-radius": "0px",
      "gutter-pattern": "wave",
      "margin-pattern": "dots",
      "band-height": "68px",
      "divider-thickness-sm": "35px",
      "divider-thickness-md": "69px",
      "divider-thickness-lg": "137px",
      "divider-thickness-xl": "205px",
    },
    radius: {
      none: "0px",
      sm: "0px",
      md: "0px",
      lg: "0px",
      xl: "0px",
      "2xl": "0px",
      full: "9999px",
      button: "0px",
      card: "0px",
      input: "0px",
      badge: "0px",
      modal: "0px",
      popover: "0px",
      tooltip: "0px",
      image: "0px",
      bento: "0px",
    },
    shadows: {
      sm: "0 1px 2px rgb(0 0 0 / 0.03)",
      md: "0 2px 4px rgb(0 0 0 / 0.04)",
      lg: "0 4px 8px rgb(0 0 0 / 0.05)",
      xl: "0 8px 16px rgb(0 0 0 / 0.06)",
      "2xl": "0 20px 40px -12px rgb(0 0 0 / 0.12)",
      glow: "0 0 20px var(--s-primary)",
      "glow-sm": "0 0 10px var(--s-primary)",
      colored: "0 4px 14px -3px var(--s-primary)",
      inner: "inset 0 1px 2px 0 rgb(0 0 0 / 0.04)",
      card: "none",
      button: "none",
      "button-hover": "none",
      dropdown: "0 4px 12px rgb(0 0 0 / 0.08), 0 0 0 1px rgb(0 0 0 / 0.04)",
      modal: "0 16px 48px -8px rgb(0 0 0 / 0.15)",
    },
    motion: {
      duration: { instant: "0ms", fast: "150ms", normal: "280ms", slow: "450ms", slower: "650ms", slowest: "1000ms" },
      easing: {
        default: "cubic-bezier(0.22, 1, 0.36, 1)",
        in: "cubic-bezier(0.55, 0, 1, 0.45)",
        out: "cubic-bezier(0, 0.55, 0.45, 1)",
        "in-out": "cubic-bezier(0.45, 0, 0.55, 1)",
        spring: "cubic-bezier(0.34, 1.56, 0.64, 1)",
        bounce: "cubic-bezier(0.68, -0.55, 0.27, 1.55)",
      },
      "enter-preset": "fadeUp",
      "exit-preset": "fadeOut",
      "hover-scale": "1.0",
      "press-scale": "0.98",
      "hover-lift": "0px",
      "stagger-interval": "55ms",
      "stagger-interval-fast": "28ms",
    },
    borders: {
      width: { none: "0px", thin: "1px", medium: "1.5px", thick: "2px" },
      style: "dashed",
      "card-border": "1px dashed",
      "card-border-hover": "1px dashed",
      "button-border": "none",
      "input-border": "1px solid",
      "divider-style": "solid",
      "divider-width": "1px",
    },
    buttons: {
      "font-weight": "700",
      "text-transform": "lowercase",
      "letter-spacing": "0.06em",
      "font-family": "'PP Editorial New', Georgia, serif",
      "border-width": "0px",
      "hover-effect": "darken",
      "active-scale": "0.97",
      "icon-gap": "10px",
      "min-width": "0px",
    },
    cards: {
      "border-style": "none",
      "border-width": "0px",
      "hover-effect": "lift",
      "hover-border-color": "var(--s-border)",
      padding: "36px",
      "header-padding": "36px 36px 0",
      "footer-padding": "0 36px 36px",
      "title-size": "1.375rem",
      "title-weight": "700",
      "description-size": "0.9375rem",
      background: "transparent",
      shadow: "none",
      outline: false,
      "outline-on-hover-only": false,
      "gap-between": "20px",
      "content-padding-x": "36px",
      "content-padding-y": "28px",
    },
    headings: {
      "h1-size": "2.75rem",
      "h1-weight": "800",
      "h1-tracking": "-0.05em",
      "h1-leading": "1.1",
      "h2-size": "2.125rem",
      "h2-weight": "700",
      "h2-tracking": "-0.04em",
      "h2-leading": "1.2",
      "h3-size": "1.75rem",
      "h3-weight": "700",
      "h3-tracking": "0em",
      "h3-leading": "1.25",
      "h4-size": "1.375rem",
      "h4-weight": "600",
      "h4-tracking": "0em",
      "h4-leading": "1.3",
      "display-size": "5rem",
      "display-weight": "800",
      "display-tracking": "-0.06em",
      "display-leading": "1.0",
    },
    navigation: {
      "navbar-height": "68px",
      "navbar-backdrop-blur": "8px",
      "navbar-border": "1px solid",
      "navbar-bg-opacity": "0.92",
      "navbar-padding-x": "32px",
      "navbar-position": "sticky",
      "navbar-logo-height": "28px",
      "navbar-logo-gap": "12px",
      "navbar-item-gap": "32px",
      "navbar-item-padding-x": "14px",
      "navbar-item-padding-y": "8px",
      "navbar-item-size": "0.875rem",
      "navbar-shadow": "none",
      "navbar-height-scrolled": "52px",
      "navbar-mobile-breakpoint": "768px",
      "nav-link-weight": "400",
      "nav-link-size": "0.9375rem",
      "nav-link-hover": "underline",
      "breadcrumb-separator": "—",
      "pagination-radius": "0px",
      "sidebar-width": "240px",
      "sidebar-item-radius": "0px",
      "sidebar-item-padding": "12px 18px",
    },
    backgrounds: {
      pattern: "none",
      "pattern-opacity": "0",
      "pattern-scale": "1",
      noise: true,
      "noise-opacity": "0.02",
      "gradient-angle": "180deg",
      "gradient-type": "none",
      "hero-pattern": "noise",
      "section-divider": "line",
    },
    code: {
      "font-family": "'PP Supply Mono', ui-monospace, monospace",
      "font-size": "0.875rem",
      "line-height": "1.7",
      bg: "var(--s-surface-sunken)",
      border: "1px dashed var(--s-border)",
      "border-radius": "0px",
      padding: "18px",
      "tab-size": "2",
      "selection-bg": "var(--s-primary-muted)",
      "comment-color": "var(--s-text-muted)",
      "keyword-color": "var(--s-primary)",
      "string-color": "var(--s-success)",
      "number-color": "var(--s-warning)",
      "function-color": "var(--s-info)",
    },
    inputs: {
      height: "42px",
      "height-sm": "34px",
      "height-lg": "50px",
      "border-width": "1px",
      "focus-ring-width": "2px",
      "focus-ring-color": "var(--s-primary)",
      "focus-ring-offset": "2px",
      "placeholder-color": "var(--s-text-subtle)",
      "error-border-color": "var(--s-error)",
      "label-size": "0.875rem",
      "label-weight": "600",
      "label-spacing": "8px",
      "helper-size": "0.75rem",
    },
    alignment: {
      "title-align": "left",
    },
    sections: {
      "rail-margin": "48px",
      "padding-y": "8.5rem",
      "padding-y-hero": "12.75rem",
      "padding-y-sm": "4.25rem",
      gap: "40px",
      "padding-y-lg": "12.75rem",
      "padding-y-xl": "17rem",
      "max-width": "800px",
      indent: "0px",
      "heading-size": "clamp(1.75rem, 5vw, 3rem)",
      "heading-align": "left",
      "heading-max-width": "48rem",
      "heading-margin-bottom": "20px",
      "description-max-width": "36rem",
      "description-gap": "16px",
      "content-gap": "32px",
      "grid-columns": "2",
      "grid-gap": "32px",
      "alternate-bg": "var(--s-surface)",
      "alternate-bg-mode": "none",
    },
    dividers: {
      style: "solid",
      width: "3px",
      opacity: "0.4",
      "max-width": "100%",
      "margin-y": "0px",
      thickness: "1px",
      "gradient-start": "transparent",
      "gradient-end": "transparent",
    },
    gridVisuals: {
      "line-color": "var(--s-border-muted)",
      "line-width": "1px",
      "show-lines": false,
      "show-dots": false,
    },
    cursor: {
      variant: "dot",
      size: "24px",
      "dot-size": "4px",
      "stroke-width": "1.5px",
      "tick-size": "6px",
      gap: "3px",
      radius: "0px",
      color: "var(--s-text)",
      "ring-color": "var(--s-primary)",
      "dot-color": "var(--s-primary)",
      glow: "none",
      opacity: "1",
      "blend-mode": "normal",
      "z-index": "9999",
      "hide-native": false,
    },
    scrollbar: {
      width: "6px",
      height: "6px",
      padding: "2px",
      radius: "9999px",
      track: "transparent",
      thumb: "var(--s-border-muted)",
      "thumb-hover": "var(--s-border)",
      "thumb-active": "var(--s-border-strong)",
      corner: "transparent",
      border: "none",
      "firefox-width": "thin",
      gutter: "stable",
      visibility: "auto",
    },
    focus: {
      "ring-width": "1.5px",
      "ring-color": "var(--s-primary)",
      "ring-offset": "2px",
      "ring-shadow": "0 0 0 1.5px var(--s-primary)",
      "outline-color": "var(--s-primary)",
    },
    overlays: {
      bg: "rgb(0 0 0 / 0.4)",
      blur: "4px",
      surface: "var(--s-surface-elevated)",
      border: "1px solid var(--s-border-muted)",
      shadow: "var(--s-shadow-xl)",
      radius: "var(--s-radius-lg)",
      padding: "20px",
      "z-index": "50",
    },
    dataViz: {
      "series-1": "var(--s-primary)",
      "series-2": "var(--s-secondary)",
      "series-3": "var(--s-accent)",
      "series-4": "var(--s-info)",
      "series-5": "var(--s-success)",
      positive: "var(--s-success)",
      negative: "var(--s-error)",
      neutral: "var(--s-text-muted)",
      grid: "var(--s-border-muted)",
      axis: "var(--s-border)",
      label: "var(--s-text-secondary)",
      "tooltip-bg": "var(--s-surface-elevated)",
      "tooltip-border": "var(--s-border-muted)",
    },
    media: {
      radius: "var(--s-radius-md)",
      border: "none",
      outline: "1px solid rgb(0 0 0 / 0.08)",
      shadow: "none",
      bg: "var(--s-surface-sunken)",
      "object-fit": "cover",
    },
    controls: {
      height: "38px",
      "height-sm": "30px",
      "height-lg": "46px",
      "hit-area": "44px",
      "icon-size": "16px",
      "handle-size": "20px",
      "track-height": "4px",
      "track-bg": "var(--s-border-muted)",
      "track-fill": "var(--s-primary)",
      "thumb-bg": "var(--s-surface-elevated)",
      "thumb-border": "2px solid var(--s-primary)",
    },
    componentSurfaces: {
      bg: "var(--s-surface)",
      "bg-elevated": "var(--s-surface-elevated)",
      "bg-muted": "var(--s-surface-sunken)",
      border: "var(--s-border)",
      "border-muted": "var(--s-border-muted)",
      "border-strong": "var(--s-border-strong)",
      text: "var(--s-text)",
      "text-muted": "var(--s-text-muted)",
      contrast: "var(--s-primary-contrast)",
      "hover-bg": "var(--s-surface-elevated)",
      "active-bg": "var(--s-surface-sunken)",
      "selected-bg": "var(--s-primary-muted)",
    },
    hero: {
      "min-height": "auto",
      "padding-y": "136px",
      "padding-y-sm": "68px",
      "padding-x": "var(--s-page-margin, 32px)",
      "content-max": "680px",
      "content-align": "center",
      layout: "centered",
      "media-position": "below",
      "media-width": "50%",
      "media-radius": "var(--s-radius-lg)",
      "title-size": "clamp(2.5rem, 7vw, 5rem)",
      "title-max-width": "64rem",
      "description-size": "1.1875rem",
      "description-max-width": "36rem",
      "description-gap": "32px",
      "actions-gap": "14px",
      "actions-margin-top": "40px",
      "action-padding-x": "28px",
      "action-padding-y": "14px",
      "badge-gap": "32px",
      "overlay-opacity": "0.3",
      "scroll-indicator": false,
      "gradient-overlay": "none",
    },
    cta: {
      "padding-y": "102px",
      "padding-x": "var(--s-page-margin, 32px)",
      "max-width": "var(--s-content-max, 1200px)",
      layout: "centered",
      border: false,
      "border-radius": "var(--s-radius-lg)",
      bg: "var(--s-surface)",
      "title-size": "clamp(1.75rem, 5vw, 3rem)",
      "description-max-width": "36rem",
      "description-gap": "16px",
      "actions-gap": "14px",
      "actions-margin-top": "40px",
      "action-padding-x": "28px",
      "action-padding-y": "14px",
      "split-gap": "68px",
    },
    footer: {
      "padding-y": "68px",
      "border-top": "1px solid var(--s-border)",
      columns: "4",
      "column-gap": "40px",
      "row-gap": "36px",
      "logo-height": "28px",
      "tagline-max-width": "24rem",
      "link-size": "0.875rem",
      "link-gap": "10px",
      "group-title-size": "0.75rem",
      "group-title-weight": "600",
      "social-icon-size": "18px",
      "social-gap": "14px",
      "bottom-bar-padding": "34px 0",
      "bottom-bar-border": "1px solid var(--s-border-muted)",
    },
    banner: {
      height: "auto",
      "padding-y": "10px",
      "padding-x": "20px",
      "font-size": "0.875rem",
      "font-weight": "400",
      "icon-size": "14px",
      "icon-gap": "12px",
      "border-width": "1px",
      "border-position": "bottom",
      position: "top",
      "dismiss-size": "14px",
      radius: "0px",
    },
    pageRhythm: {
      density: "editorial",
      "section-gap": "0px",
      "section-gap-sm": "0px",
      "section-gap-lg": "0px",
      "first-section-offset": "0px",
      "last-section-margin": "0px",
      "alternate-bg": false,
      "alternate-bg-color": "var(--s-surface)",
      "divider-between": true,
      "max-content-width": "var(--s-content-max, 1200px)",
      "vertical-rhythm-unit": "4px",
      "scroll-snap": false,
      "responsive-scale": "0.8",
      "responsive-breakpoint": "768px",
    },

  },
};
