import type { SigilPreset } from "@sigil-ui/tokens";

export const helixPreset: SigilPreset = {
  name: "helix",
  metadata: {
    description: "DNA spiral — biotech precision, organic curves, clean scientific aesthetic.",
    mood: "biotech, scientific, organic-curve",
    tags: ["biotech", "scientific", "dna", "organic", "emerald"],
    author: "sigil-ui",
    version: "0.1.0",
  },
  tokens: {
    colors: {
      background: { light: "oklch(0.995 0.002 170)", dark: "oklch(0.08 0.012 170)" },
      surface: { light: "oklch(0.975 0.004 170)", dark: "oklch(0.12 0.01 170)" },
      "surface-elevated": { light: "oklch(1 0 0)", dark: "oklch(0.16 0.012 170)" },
      "surface-sunken": { light: "oklch(0.96 0.005 170)", dark: "oklch(0.06 0.01 170)" },
      primary: "oklch(0.62 0.18 165)",
      "primary-hover": "oklch(0.56 0.2 165)",
      "primary-muted": "oklch(0.88 0.05 165)",
      "primary-contrast": "oklch(0 0 0)",
      secondary: "oklch(0.6 0.14 240)",
      "secondary-hover": "oklch(0.54 0.16 240)",
      "secondary-muted": "oklch(0.86 0.05 240)",
      accent: "oklch(0.7 0.12 190)",
      "accent-hover": "oklch(0.64 0.14 190)",
      "accent-muted": "oklch(0.88 0.04 190)",
      text: { light: "oklch(0.14 0.01 170)", dark: "oklch(0.93 0.005 170)" },
      "text-secondary": { light: "oklch(0.35 0.008 170)", dark: "oklch(0.76 0.005 170)" },
      "text-muted": { light: "oklch(0.5 0.006 170)", dark: "oklch(0.64 0.004 170)" },
      "text-subtle": { light: "oklch(0.63 0.005 170)", dark: "oklch(0.52 0.004 170)" },
      "text-disabled": { light: "oklch(0.74 0.003 170)", dark: "oklch(0.34 0.003 170)" },
      "text-inverse": { light: "oklch(0.96 0.003 170)", dark: "oklch(0.12 0.008 170)" },
      border: { light: "oklch(0.66 0.008 170)", dark: "oklch(0.47 0.01 170)" },
      "border-muted": { light: "oklch(0.93 0.005 170)", dark: "oklch(0.24 0.008 170)" },
      "border-strong": { light: "oklch(0.66 0.012 170)", dark: "oklch(0.47 0.014 170)" },
      "border-interactive": { light: "oklch(0.62 0.18 165)", dark: "oklch(0.65 0.18 165)" },
      success: "oklch(0.63 0.19 155)",
      "success-muted": "oklch(0.72 0.06 155)",
      warning: "oklch(0.66 0.15 80)",
      "warning-muted": "oklch(0.8 0.05 80)",
      error: "oklch(0.6 0.2 25)",
      "error-muted": "oklch(0.6 0.06 25)",
      info: "oklch(0.62 0.16 240)",
      "info-muted": "oklch(0.62 0.05 240)",
      "gradient-start": "oklch(0.62 0.18 165)",
      "gradient-end": "oklch(0.6 0.14 240)",
      glow: "oklch(0.62 0.18 165 / 0.35)",
      highlight: { light: "oklch(0.92 0.08 165)", dark: "oklch(0.28 0.06 165)" },
    },
    typography: {
      "font-display": "'PP Gatwick', system-ui, sans-serif",
      "font-body": "'PP Charlevoix', system-ui, sans-serif",
      "font-mono": "'PP Supply Mono', ui-monospace, monospace",
      "size-xs": "0.75rem",
      "size-sm": "0.8125rem",
      "size-base": "0.9375rem",
      "size-lg": "1.0625rem",
      "size-xl": "1.1875rem",
      "size-2xl": "1.4375rem",
      "size-3xl": "1.75rem",
      "size-4xl": "2.125rem",
      "size-5xl": "2.75rem",
      "size-6xl": "3.5rem",
      "weight-normal": "400",
      "weight-medium": "500",
      "weight-semibold": "600",
      "weight-bold": "700",
      "weight-extrabold": "800",
      "leading-tight": "1.25",
      "leading-normal": "1.55",
      "leading-relaxed": "1.7",
      "leading-loose": "2",
      "tracking-tighter": "-0.03em",
      "tracking-tight": "-0.015em",
      "tracking-normal": "0em",
      "tracking-wide": "0.015em",
      "tracking-wider": "0.03em",
      "heading-weight": "400",
      "heading-tracking": "0.04em",
      "heading-transform": "uppercase",
      "heading-family": "'PP Gatwick', system-ui, sans-serif",
    },
    spacing: {
      scale: [4, 8, 12, 16, 24, 32, 44, 60, 80, 96],
      unit: "px",
      "button-px": "20px",
      "button-py": "9px",
      "button-px-sm": "14px",
      "button-py-sm": "6px",
      "button-px-lg": "28px",
      "button-py-lg": "12px",
      "card-padding": "20px",
      "card-padding-sm": "14px",
      "card-padding-lg": "30px",
      "input-px": "11px",
      "input-py": "7px",
      "badge-px": "8px",
      "badge-py": "2px",
      "section-py": "96px",
      "section-py-lg": "144px",
      "navbar-height": "52px",
      "navbar-px": "20px",
      "footer-py": "40px",
      "modal-padding": "22px",
      "popover-padding": "14px",
      "tooltip-padding": "6px 10px",
      "table-cell-px": "14px",
      "table-cell-py": "10px",
    },
    layout: {
      "content-max": "1200px",
      "content-max-narrow": "720px",
      "content-max-wide": "1440px",
      "page-margin": "20px",
      "page-margin-sm": "16px",
      "page-margin-lg": "40px",
      gutter: "16px",
      "gutter-sm": "8px",
      "gutter-lg": "24px",
      "grid-columns": "12",
      "grid-gap": "16px",
      "bento-gap": "10px",
      "bento-radius": "12px",
      "bento-min-height": "180px",
      "section-gap": "28px",
      "sidebar-width": "248px",
      "sidebar-collapsed": "52px",
      "footer-columns": "4",
      "stack-gap": "14px",
      "stack-gap-sm": "8px",
      "stack-gap-lg": "22px",
      "prose-max": "64ch",
    },
    sigil: {
      "grid-cell": "44px",
      "cross-arm": "8px",
      "cross-stroke": "1px",
      "rail-gap": "0px",
      "card-radius": "12px",
      "gutter-pattern": "none",
      "margin-pattern": "hexagon",
      "margin-border": "1px solid",
    },
    radius: {
      none: "0px",
      sm: "4px",
      md: "8px",
      lg: "10px",
      xl: "12px",
      "2xl": "16px",
      full: "9999px",
      button: "8px",
      card: "12px",
      input: "8px",
      badge: "9999px",
      modal: "12px",
      popover: "10px",
      tooltip: "6px",
      image: "8px",
      bento: "12px",
    },
    shadows: {
      sm: "0 1px 2px 0 rgb(5 150 105 / 0.06)",
      md: "0 2px 4px -1px rgb(5 150 105 / 0.08), 0 1px 2px rgb(0 0 0 / 0.04)",
      lg: "0 4px 10px -2px rgb(5 150 105 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.05)",
      xl: "0 10px 20px -4px rgb(5 150 105 / 0.12), 0 4px 8px -4px rgb(0 0 0 / 0.05)",
      "2xl": "0 24px 48px -12px rgb(5 150 105 / 0.18)",
      glow: "0 0 24px var(--s-primary)",
      "glow-sm": "0 0 12px var(--s-primary)",
      colored: "0 4px 14px -3px var(--s-primary)",
      inner: "inset 0 2px 4px 0 rgb(0 0 0 / 0.05)",
      card: "0 1px 3px rgb(0 0 0 / 0.06)",
      button: "none",
      "button-hover": "0 1px 4px rgb(5 150 105 / 0.12)",
      dropdown: "0 4px 14px rgb(0 0 0 / 0.1), 0 0 0 1px rgb(0 0 0 / 0.04)",
      modal: "0 16px 48px -8px rgb(0 0 0 / 0.18)",
    },
    motion: {
      duration: { instant: "0ms", fast: "140ms", normal: "240ms", slow: "380ms", slower: "550ms", slowest: "900ms" },
      easing: {
        default: "cubic-bezier(0.16, 1, 0.3, 1)",
        in: "cubic-bezier(0.55, 0, 1, 0.45)",
        out: "cubic-bezier(0, 0.55, 0.45, 1)",
        "in-out": "cubic-bezier(0.45, 0, 0.55, 1)",
        spring: "cubic-bezier(0.34, 1.56, 0.64, 1)",
        bounce: "cubic-bezier(0.68, -0.55, 0.27, 1.55)",
      },
      "enter-preset": "fadeUp",
      "exit-preset": "fadeOut",
      "hover-scale": "1.02",
      "press-scale": "0.97",
      "hover-lift": "-2px",
      "stagger-interval": "50ms",
      "stagger-interval-fast": "25ms",
    },
    borders: {
      width: { none: "0px", thin: "1px", medium: "1.5px", thick: "2px" },
      style: "dotted",
      "card-border": "1px solid",
      "card-border-hover": "1px solid",
      "button-border": "1px solid",
      "input-border": "1px solid",
      "divider-style": "solid",
      "divider-width": "1px",
    },
    buttons: {
      "font-weight": "500",
      "text-transform": "none",
      "letter-spacing": "0em",
      "font-family": "'PP Charlevoix', system-ui, sans-serif",
      "border-width": "1px",
      "hover-effect": "darken",
      "active-scale": "0.97",
      "icon-gap": "8px",
      "min-width": "0px",
    },
    cards: {
      "border-style": "solid",
      "border-width": "1px",
      "hover-effect": "lift",
      "hover-border-color": "var(--s-primary-muted)",
      padding: "22px",
      "header-padding": "22px 22px 0",
      "footer-padding": "0 22px 22px",
      "title-size": "1.0625rem",
      "title-weight": "600",
      "description-size": "0.8125rem",
      outline: true,
      shadow: "sm",
      background: "surface",
    },
    headings: {
      "h1-size": "2.125rem",
      "h1-weight": "700",
      "h1-tracking": "-0.02em",
      "h1-leading": "1.2",
      "h2-size": "1.75rem",
      "h2-weight": "600",
      "h2-tracking": "-0.015em",
      "h3-size": "1.4375rem",
      "h3-weight": "600",
      "h4-size": "1.1875rem",
      "h4-weight": "600",
      "display-size": "3.5rem",
      "display-weight": "700",
      "display-tracking": "-0.03em",
      "display-leading": "1.1",
    },
    navigation: {
      "navbar-height": "52px",
      "navbar-backdrop-blur": "16px",
      "navbar-border": "1px solid",
      "navbar-bg-opacity": "0.82",
      "nav-link-weight": "500",
      "nav-link-size": "0.8125rem",
      "nav-link-hover": "underline",
      "breadcrumb-separator": "/",
      "pagination-radius": "8px",
      "sidebar-width": "248px",
      "sidebar-item-radius": "6px",
      "sidebar-item-padding": "8px 12px",
    },
    backgrounds: {
      pattern: "diagonal",
      "pattern-opacity": "0.03",
      "pattern-scale": "1",
      noise: false,
      "noise-opacity": "0",
      "gradient-angle": "135deg",
      "gradient-type": "none",
      "hero-pattern": "crosshatch",
      "section-divider": "wave",
    },
    code: {
      "font-family": "'PP Supply Mono', ui-monospace, monospace",
      "font-size": "0.8125rem",
      "line-height": "1.65",
      bg: "var(--s-surface-sunken)",
      border: "1px solid var(--s-border)",
      "border-radius": "8px",
      padding: "14px",
      "tab-size": "2",
      "selection-bg": "var(--s-primary-muted)",
      "comment-color": "var(--s-text-muted)",
      "keyword-color": "var(--s-primary)",
      "string-color": "var(--s-secondary)",
      "number-color": "var(--s-warning)",
      "function-color": "var(--s-accent)",
    },
    inputs: {
      height: "38px",
      "height-sm": "30px",
      "height-lg": "46px",
      "border-width": "1px",
      "focus-ring-width": "2px",
      "focus-ring-color": "var(--s-primary)",
      "focus-ring-offset": "2px",
      "placeholder-color": "var(--s-text-subtle)",
      "error-border-color": "var(--s-error)",
      "label-size": "0.8125rem",
      "label-weight": "500",
      "label-spacing": "6px",
      "helper-size": "0.75rem",
    },
    alignment: {
      "title-align": "left",
      "rail-margin": "32px",
    },
    sections: {
      "padding-y": "64px",
      gap: "28px",
    },
    dividers: {
      style: "solid",
      width: "1px",
    },
    gridVisuals: {
      "show-dots": true,
      "dot-size": "2px",
    },
    cursor: {
      variant: "sigil",
      size: "24px",
      "dot-size": "4px",
      "stroke-width": "1.5px",
      "tick-size": "6px",
      gap: "3px",
      radius: "0px",
      color: "var(--s-text)",
      "ring-color": "var(--s-primary)",
      "dot-color": "var(--s-primary)",
      glow: "none",
      opacity: "1",
      "blend-mode": "normal",
      "z-index": "9999",
      "hide-native": false,
    },
    scrollbar: {
      width: "6px",
      height: "6px",
      padding: "2px",
      radius: "9999px",
      track: "transparent",
      thumb: "var(--s-border-muted)",
      "thumb-hover": "var(--s-border)",
      "thumb-active": "var(--s-border-strong)",
      corner: "transparent",
      border: "none",
      "firefox-width": "thin",
      gutter: "stable",
      visibility: "auto",
    },
    focus: {
      "ring-width": "2px",
      "ring-color": "var(--s-primary)",
      "ring-offset": "2px",
      "ring-shadow": "0 0 0 2px var(--s-primary)",
      "outline-color": "var(--s-primary)",
    },
    overlays: {
      bg: "rgb(0 0 0 / 0.5)",
      blur: "8px",
      surface: "var(--s-surface-elevated)",
      border: "1px solid var(--s-border-muted)",
      shadow: "var(--s-shadow-xl)",
      radius: "var(--s-radius-lg)",
      padding: "20px",
      "z-index": "50",
    },
    dataViz: {
      "series-1": "var(--s-primary)",
      "series-2": "var(--s-secondary)",
      "series-3": "var(--s-accent)",
      "series-4": "var(--s-info)",
      "series-5": "var(--s-success)",
      positive: "var(--s-success)",
      negative: "var(--s-error)",
      neutral: "var(--s-text-muted)",
      grid: "var(--s-border-muted)",
      axis: "var(--s-border)",
      label: "var(--s-text-secondary)",
      "tooltip-bg": "var(--s-surface-elevated)",
      "tooltip-border": "var(--s-border-muted)",
    },
    media: {
      radius: "var(--s-radius-md)",
      border: "none",
      outline: "1px solid rgb(0 0 0 / 0.08)",
      shadow: "none",
      bg: "var(--s-surface-sunken)",
      "object-fit": "cover",
    },
    controls: {
      height: "38px",
      "height-sm": "30px",
      "height-lg": "46px",
      "hit-area": "44px",
      "icon-size": "16px",
      "handle-size": "20px",
      "track-height": "4px",
      "track-bg": "var(--s-border-muted)",
      "track-fill": "var(--s-primary)",
      "thumb-bg": "var(--s-surface-elevated)",
      "thumb-border": "2px solid var(--s-primary)",
    },
    componentSurfaces: {
      bg: "var(--s-surface)",
      "bg-elevated": "var(--s-surface-elevated)",
      "bg-muted": "var(--s-surface-sunken)",
      border: "var(--s-border)",
      "border-muted": "var(--s-border-muted)",
      "border-strong": "var(--s-border-strong)",
      text: "var(--s-text)",
      "text-muted": "var(--s-text-muted)",
      contrast: "var(--s-primary-contrast)",
      "hover-bg": "var(--s-surface-elevated)",
      "active-bg": "var(--s-surface-sunken)",
      "selected-bg": "var(--s-primary-muted)",
    },

  },
};
