import type { SigilPreset } from "@sigil-ui/tokens";

export const hexPreset: SigilPreset = {
  name: "hex",
  metadata: {
    description:
      "Hexagonal geometry. Six-sided lattices, magenta spell-glow, indigo void.",
    mood: "hexagonal, geometric, spell-like",
    tags: ["dark", "geometric", "hexagon", "glow", "spell"],
  },
  tokens: {
    colors: {
      background: { light: "#f5f0ff", dark: "#0f0720" },
      surface: { light: "#ede8ff", dark: "#170b30" },
      "surface-elevated": { light: "#ffffff", dark: "#1f1240" },
      "surface-sunken": { light: "#e8e0ff", dark: "#0a0418" },
      primary: "#d946ef",
      "primary-hover": "#c026d3",
      "primary-muted": "#d946ef40",
      "primary-contrast": "#000000",
      secondary: "#8b5cf6",
      "secondary-hover": "#7c3aed",
      "secondary-muted": "#8b5cf640",
      accent: "#22d3ee",
      "accent-hover": "#06b6d4",
      "accent-muted": "#22d3ee30",
      text: { light: "#1a0533", dark: "#ede8ff" },
      "text-secondary": { light: "#3b1764", dark: "#c4b5fd" },
      "text-muted": { light: "#6b3fa0", dark: "#9b8ec8" },
      "text-subtle": { light: "#8b6db5", dark: "#8878a8" },
      "text-disabled": { light: "#b8a5d3", dark: "#4a3d66" },
      "text-inverse": { light: "#ede8ff", dark: "#1a0533" },
      border: { light: "#9085a6", dark: "oklch(0.338 0.035 297)" },
      "border-muted": { light: "#c0b7d7", dark: "oklch(0.278 0.025 297)" },
      "border-strong": { light: "#9482ae", dark: "oklch(0.418 0.045 295)" },
      "border-interactive": { light: "#d946ef", dark: "#d946ef" },
      success: "#009e67",
      "success-muted": "#34d39930",
      warning: "#b87f00",
      "warning-muted": "#fbbf2430",
      error: "#e35e60",
      "error-muted": "#f8717130",
      info: "#478cdf",
      "info-muted": "#60a5fa30",
      "gradient-start": "#d946ef",
      "gradient-end": "#22d3ee",
      glow: "#d946ef66",
      highlight: { light: "#fae8ff", dark: "rgba(217, 70, 239, 0.15)" },
    },
    typography: {
      "font-display": "'PP Fuji', system-ui, sans-serif",
      "font-body": "'PP Fuji', system-ui, sans-serif",
      "font-mono": "'PP Fraktion Mono', ui-monospace, monospace",
      "size-xs": "0.75rem",
      "size-sm": "0.8125rem",
      "size-base": "0.9375rem",
      "size-lg": "1.0625rem",
      "size-xl": "1.1875rem",
      "size-2xl": "1.4375rem",
      "size-3xl": "1.75rem",
      "size-4xl": "2.125rem",
      "size-5xl": "2.75rem",
      "size-6xl": "3.5rem",
      "weight-normal": "400",
      "weight-medium": "500",
      "weight-semibold": "600",
      "weight-bold": "700",
      "weight-extrabold": "800",
      "leading-tight": "1.25",
      "leading-normal": "1.5",
      "leading-relaxed": "1.625",
      "leading-loose": "2",
      "tracking-tighter": "-0.04em",
      "tracking-tight": "-0.02em",
      "tracking-normal": "0em",
      "tracking-wide": "0.025em",
      "tracking-wider": "0.05em",
      "heading-weight": "700",
      "heading-tracking": "-0.03em",
      "heading-transform": "none",
      "heading-family": "'PP Fuji', system-ui, sans-serif",
    },
    spacing: {
      scale: [4, 8, 12, 16, 24, 32, 48, 64, 80, 96],
      unit: "px",
      "button-px": "24px",
      "button-py": "10px",
      "button-px-sm": "16px",
      "button-py-sm": "6px",
      "button-px-lg": "32px",
      "button-py-lg": "14px",
      "card-padding": "24px",
      "card-padding-sm": "16px",
      "card-padding-lg": "32px",
      "input-px": "12px",
      "input-py": "8px",
      "badge-px": "8px",
      "badge-py": "3px",
      "section-py": "8rem",
      "section-py-lg": "12rem",
      "navbar-height": "64px",
      "navbar-px": "28px",
      "footer-py": "64px",
      "modal-padding": "24px",
      "popover-padding": "16px",
      "tooltip-padding": "6px 12px",
      "table-cell-px": "16px",
      "table-cell-py": "10px",
    },
    layout: {
      "content-max": "1200px",
      "content-max-narrow": "720px",
      "content-max-wide": "1440px",
      "page-margin": "28px",
      "page-margin-sm": "16px",
      "page-margin-lg": "52px",
      gutter: "28px",
      "gutter-sm": "14px",
      "gutter-lg": "40px",
      "grid-columns": "12",
      "grid-gap": "28px",
      "bento-gap": "18px",
      "bento-radius": "0px",
      "bento-min-height": "192px",
      "section-gap": "32px",
      "sidebar-width": "272px",
      "sidebar-collapsed": "56px",
      "footer-columns": "3",
      "stack-gap": "16px",
      "stack-gap-sm": "8px",
      "stack-gap-lg": "24px",
      "prose-max": "65ch",
    },
    sigil: {
      "grid-cell": "64px",
      "cross-arm": "14px",
      "cross-stroke": "2px",
      "rail-gap": "32px",
      "card-radius": "0px",
      "gutter-pattern": "hexagon",
      "margin-pattern": "crosshatch",
    },
    radius: {
      none: "0px",
      sm: "0px",
      md: "0px",
      lg: "12px",
      xl: "16px",
      "2xl": "20px",
      full: "9999px",
      button: "0px",
      card: "0px",
      input: "0px",
      badge: "0px",
      modal: "12px",
      popover: "12px",
      tooltip: "6px",
      image: "0px",
      bento: "0px",
    },
    shadows: {
      sm: "0 1px 3px rgb(0 0 0 / 0.2)",
      md: "0 2px 6px rgb(0 0 0 / 0.25)",
      lg: "0 4px 12px rgb(0 0 0 / 0.3)",
      xl: "0 8px 24px rgb(0 0 0 / 0.35)",
      "2xl": "0 20px 50px rgb(0 0 0 / 0.5)",
      glow: "0 0 24px #d946ef66, 0 0 48px #d946ef33",
      "glow-sm": "0 0 12px #d946ef44",
      colored: "0 4px 20px -4px #d946ef55",
      inner: "inset 0 2px 4px rgb(0 0 0 / 0.15)",
      card: "0 0 0 1px #2e1a50, 0 0 16px #d946ef15",
      button: "none",
      "button-hover": "0 0 20px #d946ef44",
      dropdown: "0 8px 24px rgb(0 0 0 / 0.4)",
      modal: "0 24px 64px rgb(0 0 0 / 0.5), 0 0 32px #d946ef22",
    },
    motion: {
      duration: { instant: "0ms", fast: "150ms", normal: "250ms", slow: "400ms", slower: "600ms", slowest: "1000ms" },
      easing: {
        default: "cubic-bezier(0.16, 1, 0.3, 1)",
        in: "cubic-bezier(0.55, 0, 1, 0.45)",
        out: "cubic-bezier(0, 0.55, 0.45, 1)",
        "in-out": "cubic-bezier(0.45, 0, 0.55, 1)",
        spring: "cubic-bezier(0.34, 1.56, 0.64, 1)",
        bounce: "cubic-bezier(0.68, -0.55, 0.27, 1.55)",
      },
      "enter-preset": "fadeUp",
      "exit-preset": "fadeOut",
      "hover-scale": "1.03",
      "press-scale": "0.97",
      "hover-lift": "-3px",
      "stagger-interval": "60ms",
      "stagger-interval-fast": "30ms",
    },
    borders: {
      width: { none: "0px", thin: "1px", medium: "1.5px", thick: "2px" },
      style: "solid",
      "card-border": "1px solid",
      "card-border-hover": "1px solid",
      "button-border": "0px solid",
      "input-border": "1px solid",
      "divider-style": "solid",
      "divider-width": "1px",
    },
    buttons: {
      "font-weight": "600",
      "text-transform": "none",
      "letter-spacing": "0.01em",
      "font-family": "'PP Fuji', system-ui, sans-serif",
      "border-width": "0px",
      "hover-effect": "glow",
      "active-scale": "0.96",
      "icon-gap": "8px",
      "min-width": "0px",
    },
    cards: {
      "border-style": "solid",
      "border-width": "1px",
      "hover-effect": "glow",
      "hover-border-color": "#d946ef88",
      padding: "24px",
      "header-padding": "24px 24px 0",
      "footer-padding": "0 24px 24px",
      "title-size": "1.0625rem",
      "title-weight": "600",
      "description-size": "0.8125rem",
      outline: true,
      shadow: "sm",
      background: "surface",
    },
    headings: {
      "h1-size": "2.25rem",
      "h1-weight": "700",
      "h1-tracking": "-0.02em",
      "h1-leading": "1.2",
      "h2-size": "1.75rem",
      "h2-weight": "600",
      "h2-tracking": "-0.015em",
      "h2-leading": "1.15",
      "h3-size": "1.375rem",
      "h3-weight": "600",
      "h3-tracking": "0em",
      "h3-leading": "1.2",
      "h4-size": "1.125rem",
      "h4-weight": "600",
      "h4-tracking": "0em",
      "h4-leading": "1.3",
      "display-size": "3.75rem",
      "display-weight": "800",
      "display-tracking": "-0.035em",
      "display-leading": "1.05",
    },
    navigation: {
      "navbar-height": "64px",
      "navbar-backdrop-blur": "12px",
      "navbar-border": "1px solid",
      "navbar-bg-opacity": "0.85",
      "navbar-padding-x": "20px",
      "navbar-position": "sticky",
      "navbar-logo-height": "22px",
      "navbar-logo-gap": "8px",
      "navbar-item-gap": "20px",
      "navbar-item-padding-x": "10px",
      "navbar-item-padding-y": "4px",
      "navbar-item-size": "0.8125rem",
      "navbar-shadow": "none",
      "navbar-height-scrolled": "44px",
      "navbar-mobile-breakpoint": "768px",
      "nav-link-weight": "500",
      "nav-link-size": "0.875rem",
      "nav-link-hover": "background",
      "breadcrumb-separator": "⬡",
      "pagination-radius": "0px",
      "sidebar-width": "272px",
      "sidebar-item-radius": "0px",
      "sidebar-item-padding": "10px 14px",
    },
    backgrounds: {
      pattern: "hexagon",
      "pattern-opacity": "0.05",
      "pattern-scale": "1.2",
      noise: false,
      "noise-opacity": "0.02",
      "gradient-angle": "135deg",
      "gradient-type": "radial",
      "hero-pattern": "grid",
      "section-divider": "none",
    },
    code: {
      "font-family": "'PP Fraktion Mono', ui-monospace, monospace",
      "font-size": "0.8125rem",
      "line-height": "1.7",
      bg: "var(--s-surface-sunken)",
      border: "1px solid var(--s-border)",
      "border-radius": "0px",
      padding: "16px",
      "tab-size": "2",
      "selection-bg": "#d946ef33",
      "comment-color": "var(--s-text-muted)",
      "keyword-color": "#d946ef",
      "string-color": "#22d3ee",
      "number-color": "#fbbf24",
      "function-color": "#8b5cf6",
    },
    inputs: {
      height: "40px",
      "height-sm": "32px",
      "height-lg": "48px",
      "border-width": "1px",
      "focus-ring-width": "2px",
      "focus-ring-color": "#d946ef",
      "focus-ring-offset": "2px",
      "placeholder-color": "var(--s-text-subtle)",
      "error-border-color": "var(--s-error)",
      "label-size": "0.8125rem",
      "label-weight": "500",
      "label-spacing": "6px",
      "helper-size": "0.75rem",
    },
    alignment: {
      "title-align": "center",
      "rail-margin": "24px",
    },
    sections: {
      "padding-y": "8rem",
      "padding-y-sm": "4rem",
      gap: "28px",
      "padding-y-lg": "12rem",
      "padding-y-xl": "16rem",
      "title-align": "center",
      "heading-size": "clamp(1.5rem, 4vw, 2rem)",
      "heading-align": "left",
      "heading-max-width": "36rem",
      "heading-margin-bottom": "12px",
      "description-max-width": "28rem",
      "description-gap": "10px",
      "content-gap": "20px",
      "grid-columns": "3",
      "grid-gap": "20px",
      "alternate-bg": "var(--s-surface)",
      "alternate-bg-mode": "none",
    },
    dividers: {
      style: "none",
      opacity: "1",
      "max-width": "100%",
      "margin-y": "0px",
      thickness: "1px",
      "gradient-start": "transparent",
      "gradient-end": "transparent",
    },
    gridVisuals: {
      "line-color": "var(--s-border-muted)",
      "line-width": "1px",
      "show-dots": true,
      "cell-radius": "8px",
    },
    cursor: {
      variant: "sigil",
      size: "24px",
      "dot-size": "4px",
      "stroke-width": "1.5px",
      "tick-size": "6px",
      gap: "3px",
      radius: "0px",
      color: "var(--s-text)",
      "ring-color": "var(--s-primary)",
      "dot-color": "var(--s-primary)",
      glow: "none",
      opacity: "1",
      "blend-mode": "normal",
      "z-index": "9999",
      "hide-native": false,
    },
    scrollbar: {
      width: "6px",
      height: "6px",
      padding: "2px",
      radius: "9999px",
      track: "transparent",
      thumb: "var(--s-border-muted)",
      "thumb-hover": "var(--s-border)",
      "thumb-active": "var(--s-border-strong)",
      corner: "transparent",
      border: "none",
      "firefox-width": "thin",
      gutter: "stable",
      visibility: "auto",
    },
    focus: {
      "ring-width": "2px",
      "ring-color": "var(--s-primary)",
      "ring-offset": "2px",
      "ring-shadow": "0 0 0 2px var(--s-primary)",
      "outline-color": "var(--s-primary)",
    },
    overlays: {
      bg: "rgb(0 0 0 / 0.5)",
      blur: "8px",
      surface: "var(--s-surface-elevated)",
      border: "1px solid var(--s-border-muted)",
      shadow: "var(--s-shadow-xl)",
      radius: "var(--s-radius-lg)",
      padding: "20px",
      "z-index": "50",
    },
    dataViz: {
      "series-1": "var(--s-primary)",
      "series-2": "var(--s-secondary)",
      "series-3": "var(--s-accent)",
      "series-4": "var(--s-info)",
      "series-5": "var(--s-success)",
      positive: "var(--s-success)",
      negative: "var(--s-error)",
      neutral: "var(--s-text-muted)",
      grid: "var(--s-border-muted)",
      axis: "var(--s-border)",
      label: "var(--s-text-secondary)",
      "tooltip-bg": "var(--s-surface-elevated)",
      "tooltip-border": "var(--s-border-muted)",
    },
    media: {
      radius: "var(--s-radius-md)",
      border: "none",
      outline: "1px solid rgb(0 0 0 / 0.08)",
      shadow: "none",
      bg: "var(--s-surface-sunken)",
      "object-fit": "cover",
    },
    controls: {
      height: "38px",
      "height-sm": "30px",
      "height-lg": "46px",
      "hit-area": "44px",
      "icon-size": "16px",
      "handle-size": "20px",
      "track-height": "4px",
      "track-bg": "var(--s-border-muted)",
      "track-fill": "var(--s-primary)",
      "thumb-bg": "var(--s-surface-elevated)",
      "thumb-border": "2px solid var(--s-primary)",
    },
    componentSurfaces: {
      bg: "var(--s-surface)",
      "bg-elevated": "var(--s-surface-elevated)",
      "bg-muted": "var(--s-surface-sunken)",
      border: "var(--s-border)",
      "border-muted": "var(--s-border-muted)",
      "border-strong": "var(--s-border-strong)",
      text: "var(--s-text)",
      "text-muted": "var(--s-text-muted)",
      contrast: "var(--s-primary-contrast)",
      "hover-bg": "var(--s-surface-elevated)",
      "active-bg": "var(--s-surface-sunken)",
      "selected-bg": "var(--s-primary-muted)",
    },
    hero: {
      "min-height": "auto",
      "padding-y": "96px",
      "padding-y-sm": "64px",
      "padding-x": "var(--s-page-margin, 20px)",
      "content-max": "600px",
      "content-align": "center",
      layout: "centered",
      "media-position": "below",
      "media-width": "50%",
      "media-radius": "var(--s-radius-md)",
      "title-size": "clamp(2rem, 5vw, 3.5rem)",
      "title-max-width": "48rem",
      "description-size": "1rem",
      "description-max-width": "28rem",
      "description-gap": "20px",
      "actions-gap": "10px",
      "actions-margin-top": "24px",
      "action-padding-x": "20px",
      "action-padding-y": "10px",
      "badge-gap": "20px",
      "overlay-opacity": "0.5",
      "scroll-indicator": false,
      "gradient-overlay": "none",
    },
    cta: {
      "padding-y": "64px",
      "padding-x": "var(--s-page-margin, 20px)",
      "max-width": "var(--s-content-max, 1200px)",
      layout: "centered",
      border: true,
      "border-radius": "var(--s-card-radius, 0px)",
      bg: "var(--s-surface)",
      "title-size": "clamp(1.25rem, 3vw, 2rem)",
      "description-max-width": "28rem",
      "description-gap": "10px",
      "actions-gap": "10px",
      "actions-margin-top": "24px",
      "action-padding-x": "20px",
      "action-padding-y": "10px",
      "split-gap": "32px",
    },
    footer: {
      "padding-y": "32px",
      "border-top": "1px solid var(--s-border)",
      columns: "4",
      "column-gap": "24px",
      "row-gap": "24px",
      "logo-height": "20px",
      "tagline-max-width": "18rem",
      "link-size": "0.8125rem",
      "link-gap": "6px",
      "group-title-size": "0.8125rem",
      "group-title-weight": "600",
      "social-icon-size": "18px",
      "social-gap": "10px",
      "bottom-bar-padding": "32px 0",
      "bottom-bar-border": "1px solid var(--s-border-muted)",
    },
    banner: {
      height: "auto",
      "padding-y": "6px",
      "padding-x": "16px",
      "font-size": "0.8125rem",
      "font-weight": "500",
      "icon-size": "14px",
      "icon-gap": "10px",
      "border-width": "1px",
      "border-position": "bottom",
      position: "top",
      "dismiss-size": "14px",
      radius: "0px",
    },
    pageRhythm: {
      density: "compact",
      "section-gap": "0px",
      "section-gap-sm": "0px",
      "section-gap-lg": "0px",
      "first-section-offset": "0px",
      "last-section-margin": "0px",
      "alternate-bg": false,
      "alternate-bg-color": "var(--s-surface)",
      "divider-between": true,
      "max-content-width": "var(--s-content-max, 1200px)",
      "vertical-rhythm-unit": "8px",
      "scroll-snap": false,
      "responsive-scale": "1",
      "responsive-breakpoint": "768px",
    },

  },
};
