import type { SigilPreset } from "@sigil-ui/tokens";

export const hexPreset: SigilPreset = {
  name: "hex",
  metadata: {
    description:
      "Hexagonal geometry. Six-sided lattices, magenta spell-glow, indigo void.",
    mood: "hexagonal, geometric, spell-like",
    tags: ["dark", "geometric", "hexagon", "glow", "spell"],
  },
  tokens: {
    colors: {
      background: { light: "#f5f0ff", dark: "#0f0720" },
      surface: { light: "#ede8ff", dark: "#170b30" },
      "surface-elevated": { light: "#ffffff", dark: "#1f1240" },
      "surface-sunken": { light: "#e8e0ff", dark: "#0a0418" },
      primary: "#d946ef",
      "primary-hover": "#c026d3",
      "primary-muted": "#d946ef40",
      "primary-contrast": "#ffffff",
      secondary: "#8b5cf6",
      "secondary-hover": "#7c3aed",
      "secondary-muted": "#8b5cf640",
      accent: "#22d3ee",
      "accent-hover": "#06b6d4",
      "accent-muted": "#22d3ee30",
      text: { light: "#1a0533", dark: "#ede8ff" },
      "text-secondary": { light: "#3b1764", dark: "#c4b5fd" },
      "text-muted": { light: "#6b3fa0", dark: "#8b7ab8" },
      "text-subtle": { light: "#8b6db5", dark: "#6b5a8e" },
      "text-disabled": { light: "#b8a5d3", dark: "#4a3d66" },
      "text-inverse": { light: "#ede8ff", dark: "#1a0533" },
      border: { light: "#d8ccf0", dark: "#2e1a50" },
      "border-muted": { light: "#e8e0ff", dark: "#231040" },
      "border-strong": { light: "#b8a5d3", dark: "#3f2570" },
      "border-interactive": { light: "#d946ef", dark: "#d946ef" },
      success: "#34d399",
      "success-muted": "#34d39930",
      warning: "#fbbf24",
      "warning-muted": "#fbbf2430",
      error: "#f87171",
      "error-muted": "#f8717130",
      info: "#60a5fa",
      "info-muted": "#60a5fa30",
      "gradient-start": "#d946ef",
      "gradient-end": "#22d3ee",
      glow: "#d946ef66",
    },
    typography: {
      "font-display": "'Lexend', system-ui, sans-serif",
      "font-body": "'Lexend', system-ui, sans-serif",
      "font-mono": "'Fira Code', ui-monospace, monospace",
      "size-xs": "0.75rem",
      "size-sm": "0.8125rem",
      "size-base": "0.9375rem",
      "size-lg": "1.0625rem",
      "size-xl": "1.1875rem",
      "size-2xl": "1.4375rem",
      "size-3xl": "1.75rem",
      "size-4xl": "2.125rem",
      "size-5xl": "2.75rem",
      "size-6xl": "3.5rem",
      "weight-normal": "400",
      "weight-medium": "500",
      "weight-semibold": "600",
      "weight-bold": "700",
      "weight-extrabold": "800",
      "leading-tight": "1.25",
      "leading-normal": "1.5",
      "leading-relaxed": "1.625",
      "leading-loose": "2",
      "tracking-tighter": "-0.04em",
      "tracking-tight": "-0.02em",
      "tracking-normal": "0em",
      "tracking-wide": "0.025em",
      "tracking-wider": "0.05em",
      "heading-weight": "700",
      "heading-tracking": "-0.02em",
      "heading-transform": "none",
      "heading-family": "'Lexend', system-ui, sans-serif",
    },
    spacing: {
      scale: [4, 8, 12, 16, 24, 32, 48, 64, 80, 96],
      unit: "px",
      "button-px": "24px",
      "button-py": "10px",
      "button-px-sm": "16px",
      "button-py-sm": "6px",
      "button-px-lg": "32px",
      "button-py-lg": "14px",
      "card-padding": "24px",
      "card-padding-sm": "16px",
      "card-padding-lg": "32px",
      "input-px": "12px",
      "input-py": "8px",
      "badge-px": "8px",
      "badge-py": "3px",
      "section-py": "64px",
      "section-py-lg": "96px",
      "navbar-height": "56px",
      "navbar-px": "24px",
      "footer-py": "48px",
      "modal-padding": "24px",
      "popover-padding": "16px",
      "tooltip-padding": "6px 12px",
      "table-cell-px": "16px",
      "table-cell-py": "10px",
    },
    layout: {
      "content-max": "1200px",
      "content-max-narrow": "720px",
      "content-max-wide": "1440px",
      "page-margin": "24px",
      "page-margin-sm": "16px",
      "page-margin-lg": "48px",
      gutter: "24px",
      "gutter-sm": "16px",
      "gutter-lg": "32px",
      "grid-columns": "12",
      "grid-gap": "24px",
      "bento-gap": "16px",
      "bento-radius": "0px",
      "bento-min-height": "200px",
      "section-gap": "32px",
      "sidebar-width": "260px",
      "sidebar-collapsed": "56px",
      "footer-columns": "3",
      "stack-gap": "16px",
      "stack-gap-sm": "8px",
      "stack-gap-lg": "24px",
      "prose-max": "65ch",
    },
    sigil: {
      "grid-cell": "60px",
      "cross-arm": "12px",
      "cross-stroke": "1.5px",
      "rail-gap": "30px",
      "card-radius": "0px",
    },
    radius: {
      none: "0px",
      sm: "0px",
      md: "0px",
      lg: "12px",
      xl: "16px",
      "2xl": "20px",
      full: "9999px",
      button: "0px",
      card: "0px",
      input: "0px",
      badge: "0px",
      modal: "12px",
      popover: "12px",
      tooltip: "6px",
      image: "0px",
      bento: "0px",
    },
    shadows: {
      sm: "0 1px 3px rgb(0 0 0 / 0.2)",
      md: "0 2px 6px rgb(0 0 0 / 0.25)",
      lg: "0 4px 12px rgb(0 0 0 / 0.3)",
      xl: "0 8px 24px rgb(0 0 0 / 0.35)",
      "2xl": "0 20px 50px rgb(0 0 0 / 0.5)",
      glow: "0 0 24px #d946ef66, 0 0 48px #d946ef33",
      "glow-sm": "0 0 12px #d946ef44",
      colored: "0 4px 20px -4px #d946ef55",
      inner: "inset 0 2px 4px rgb(0 0 0 / 0.15)",
      card: "0 0 0 1px #2e1a50, 0 0 16px #d946ef15",
      button: "none",
      "button-hover": "0 0 20px #d946ef44",
      dropdown: "0 8px 24px rgb(0 0 0 / 0.4)",
      modal: "0 24px 64px rgb(0 0 0 / 0.5), 0 0 32px #d946ef22",
    },
    motion: {
      duration: { instant: "0ms", fast: "150ms", normal: "250ms", slow: "400ms", slower: "600ms", slowest: "1000ms" },
      easing: {
        default: "cubic-bezier(0.16, 1, 0.3, 1)",
        in: "cubic-bezier(0.55, 0, 1, 0.45)",
        out: "cubic-bezier(0, 0.55, 0.45, 1)",
        "in-out": "cubic-bezier(0.45, 0, 0.55, 1)",
        spring: "cubic-bezier(0.34, 1.56, 0.64, 1)",
        bounce: "cubic-bezier(0.68, -0.55, 0.27, 1.55)",
      },
      "enter-preset": "fadeUp",
      "exit-preset": "fadeOut",
      "hover-scale": "1.03",
      "press-scale": "0.97",
      "hover-lift": "-3px",
      "stagger-interval": "60ms",
      "stagger-interval-fast": "30ms",
    },
    borders: {
      width: { none: "0px", thin: "1px", medium: "1.5px", thick: "2px" },
      style: "solid",
      "card-border": "1px solid",
      "card-border-hover": "1px solid",
      "button-border": "0px solid",
      "input-border": "1px solid",
      "divider-style": "solid",
      "divider-width": "1px",
    },
    buttons: {
      "font-weight": "600",
      "text-transform": "none",
      "letter-spacing": "0.01em",
      "font-family": "'Lexend', system-ui, sans-serif",
      "border-width": "0px",
      "hover-effect": "glow",
      "active-scale": "0.96",
      "icon-gap": "8px",
      "min-width": "0px",
    },
    cards: {
      "border-style": "solid",
      "border-width": "1px",
      "hover-effect": "glow",
      "hover-border-color": "#d946ef88",
      padding: "24px",
      "header-padding": "24px 24px 0",
      "footer-padding": "0 24px 24px",
      "title-size": "1.0625rem",
      "title-weight": "600",
      "description-size": "0.8125rem",
      outline: true,
      shadow: "sm",
      background: "surface",
    },
    headings: {
      "h1-size": "2.25rem",
      "h1-weight": "700",
      "h1-tracking": "-0.02em",
      "h1-leading": "1.2",
      "h2-size": "1.75rem",
      "h2-weight": "600",
      "h2-tracking": "-0.015em",
      "h3-size": "1.375rem",
      "h3-weight": "600",
      "h4-size": "1.125rem",
      "h4-weight": "600",
      "display-size": "3.75rem",
      "display-weight": "800",
      "display-tracking": "-0.035em",
      "display-leading": "1.05",
    },
    navigation: {
      "navbar-height": "56px",
      "navbar-backdrop-blur": "16px",
      "navbar-border": "1px solid",
      "navbar-bg-opacity": "0.8",
      "nav-link-weight": "500",
      "nav-link-size": "0.875rem",
      "nav-link-hover": "color",
      "breadcrumb-separator": "⬡",
      "pagination-radius": "0px",
      "sidebar-width": "260px",
      "sidebar-item-radius": "0px",
      "sidebar-item-padding": "8px 12px",
    },
    backgrounds: {
      pattern: "hexagon",
      "pattern-opacity": "0.06",
      "pattern-scale": "1.2",
      noise: false,
      "noise-opacity": "0.02",
      "gradient-angle": "135deg",
      "gradient-type": "linear",
      "hero-pattern": "radial-glow",
      "section-divider": "none",
    },
    code: {
      "font-family": "'Fira Code', ui-monospace, monospace",
      "font-size": "0.8125rem",
      "line-height": "1.7",
      bg: "var(--s-surface-sunken)",
      border: "1px solid var(--s-border)",
      "border-radius": "0px",
      padding: "16px",
      "tab-size": "2",
      "selection-bg": "#d946ef33",
      "comment-color": "var(--s-text-muted)",
      "keyword-color": "#d946ef",
      "string-color": "#22d3ee",
      "number-color": "#fbbf24",
      "function-color": "#8b5cf6",
    },
    inputs: {
      height: "40px",
      "height-sm": "32px",
      "height-lg": "48px",
      "border-width": "1px",
      "focus-ring-width": "2px",
      "focus-ring-color": "#d946ef",
      "focus-ring-offset": "2px",
      "placeholder-color": "var(--s-text-subtle)",
      "error-border-color": "var(--s-error)",
      "label-size": "0.8125rem",
      "label-weight": "500",
      "label-spacing": "6px",
      "helper-size": "0.75rem",
    },
    alignment: {
      "title-align": "center",
      "rail-margin": "24px",
    },
    sections: {
      "padding-y": "64px",
      gap: "28px",
    },
    dividers: {
      style: "none",
    },
    gridVisuals: {
      "show-dots": true,
      "cell-radius": "8px",
    },
  },
};
