import type { SigilPreset } from "@sigil-ui/tokens";

export const inkPreset: SigilPreset = {
  name: "ink",
  metadata: {
    description: "Deep indigo surfaces with violet-tinted depth. Dark-first preset with lavender light mode, modern sans typography, indigo-tinted glows.",
    mood: "creative, deep, immersive",
    tags: ["edgeless", "indigo", "dark-first", "modern", "colorful-bg"],
  },
  tokens: {
    colors: {
      background: { light: "oklch(0.95 0.02 265)", dark: "oklch(0.13 0.05 265)" },
      surface: { light: "oklch(0.93 0.025 265)", dark: "oklch(0.17 0.055 265)" },
      "surface-elevated": { light: "oklch(0.97 0.015 265)", dark: "oklch(0.21 0.05 265)" },
      "surface-sunken": { light: "oklch(0.90 0.03 265)", dark: "oklch(0.10 0.045 265)" },
      primary: { light: "oklch(0.55 0.22 265)", dark: "oklch(0.72 0.18 265)" },
      "primary-hover": { light: "oklch(0.48 0.24 265)", dark: "oklch(0.78 0.15 265)" },
      "primary-muted": { light: "oklch(0.55 0.06 265)", dark: "oklch(0.72 0.05 265)" },
      "primary-contrast": { light: "oklch(0.99 0.005 265)", dark: "oklch(0.13 0.05 265)" },
      secondary: "oklch(0.58 0.12 295)",
      "secondary-hover": "oklch(0.52 0.14 295)",
      "secondary-muted": "oklch(0.58 0.04 295)",
      accent: "oklch(0.65 0.15 235)",
      "accent-hover": "oklch(0.58 0.17 235)",
      "accent-muted": "oklch(0.65 0.05 235)",
      text: { light: "oklch(0.20 0.04 265)", dark: "oklch(0.90 0.025 270)" },
      "text-secondary": { light: "oklch(0.35 0.03 265)", dark: "oklch(0.74 0.025 270)" },
      "text-muted": { light: "oklch(0.50 0.025 265)", dark: "oklch(0.56 0.025 270)" },
      "text-subtle": { light: "oklch(0.62 0.02 265)", dark: "oklch(0.42 0.02 270)" },
      "text-disabled": { light: "oklch(0.75 0.015 265)", dark: "oklch(0.30 0.02 270)" },
      "text-inverse": { light: "oklch(0.90 0.025 270)", dark: "oklch(0.20 0.04 265)" },
      border: { light: "oklch(0.85 0.022 265)", dark: "oklch(0.310 0.035 265)" },
      "border-muted": { light: "oklch(0.91 0.015 265)", dark: "oklch(0.250 0.025 265)" },
      "border-strong": { light: "oklch(0.74 0.035 265)", dark: "oklch(0.390 0.045 265)" },
      "border-interactive": { light: "oklch(0.55 0.22 265)", dark: "oklch(0.72 0.18 265)" },
      success: "oklch(0.62 0.16 155)",
      "success-muted": { light: "oklch(0.93 0.04 155)", dark: "oklch(0.16 0.04 155)" },
      warning: "oklch(0.72 0.14 80)",
      "warning-muted": { light: "oklch(0.94 0.04 80)", dark: "oklch(0.18 0.04 80)" },
      error: "oklch(0.55 0.18 25)",
      "error-muted": { light: "oklch(0.94 0.04 25)", dark: "oklch(0.18 0.04 25)" },
      info: "oklch(0.60 0.13 245)",
      "info-muted": { light: "oklch(0.94 0.03 245)", dark: "oklch(0.18 0.03 245)" },
      "gradient-start": { light: "oklch(0.55 0.22 265)", dark: "oklch(0.72 0.18 265)" },
      "gradient-end": { light: "oklch(0.58 0.12 295)", dark: "oklch(0.60 0.14 295)" },
      glow: { light: "oklch(0.55 0.22 265 / 0.15)", dark: "oklch(0.72 0.18 265 / 0.18)" },
      highlight: { light: "oklch(0.92 0.08 265)", dark: "oklch(0.28 0.06 265)" },
    },
    typography: {
      "font-display": "'Plus Jakarta Sans', system-ui, sans-serif",
      "font-body": "'Inter', system-ui, sans-serif",
      "font-mono": "'JetBrains Mono', ui-monospace, monospace",
      "size-xs": "0.75rem",
      "size-sm": "0.875rem",
      "size-base": "1rem",
      "size-lg": "1.125rem",
      "size-xl": "1.25rem",
      "size-2xl": "1.5rem",
      "size-3xl": "1.875rem",
      "size-4xl": "2.25rem",
      "size-5xl": "3rem",
      "size-6xl": "3.75rem",
      "weight-normal": "400",
      "weight-medium": "500",
      "weight-semibold": "600",
      "weight-bold": "700",
      "weight-extrabold": "800",
      "leading-tight": "1.2",
      "leading-normal": "1.55",
      "leading-relaxed": "1.7",
      "leading-loose": "1.9",
      "tracking-tighter": "-0.04em",
      "tracking-tight": "-0.02em",
      "tracking-normal": "0em",
      "tracking-wide": "0.02em",
      "tracking-wider": "0.04em",
      "heading-weight": "700",
      "heading-tracking": "-0.025em",
      "heading-transform": "none",
      "heading-family": "'Plus Jakarta Sans', system-ui, sans-serif",
    },
    spacing: {
      scale: [4, 8, 12, 16, 24, 32, 48, 64, 96, 128],
      unit: "px",
      "button-px": "24px",
      "button-py": "11px",
      "button-px-sm": "16px",
      "button-py-sm": "7px",
      "button-px-lg": "32px",
      "button-py-lg": "14px",
      "card-padding": "28px",
      "card-padding-sm": "18px",
      "card-padding-lg": "40px",
      "input-px": "14px",
      "input-py": "10px",
      "badge-px": "12px",
      "badge-py": "3px",
      "section-py": "108px",
      "section-py-lg": "148px",
      "navbar-height": "60px",
      "navbar-px": "28px",
      "footer-py": "72px",
      "modal-padding": "28px",
      "popover-padding": "14px",
      "tooltip-padding": "6px 12px",
      "table-cell-px": "14px",
      "table-cell-py": "12px",
    },
    layout: {
      "content-max": "1080px",
      "content-max-narrow": "680px",
      "content-max-wide": "1320px",
      "page-margin": "32px",
      "page-margin-sm": "16px",
      "page-margin-lg": "64px",
      gutter: "0px",
      "gutter-sm": "0px",
      "gutter-lg": "0px",
      "grid-columns": "12",
      "grid-gap": "28px",
      "bento-gap": "20px",
      "bento-radius": "14px",
      "bento-min-height": "200px",
      "section-gap": "44px",
      "sidebar-width": "260px",
      "sidebar-collapsed": "56px",
      "footer-columns": "4",
      "stack-gap": "18px",
      "stack-gap-sm": "10px",
      "stack-gap-lg": "28px",
      "prose-max": "64ch",
    },
    sigil: {
      "grid-cell": "64px",
      "cross-arm": "0px",
      "cross-stroke": "0px",
      "rail-gap": "0px",
      "card-radius": "14px",
      "gutter-pattern": "none",
      "margin-pattern": "none",
      "gutter-border": "none",
      "gutter-visible": false,
    },
    radius: {
      none: "0px",
      sm: "6px",
      md: "10px",
      lg: "14px",
      xl: "20px",
      "2xl": "28px",
      full: "9999px",
      button: "10px",
      card: "14px",
      input: "10px",
      badge: "9999px",
      modal: "16px",
      popover: "12px",
      tooltip: "8px",
      image: "12px",
      bento: "14px",
    },
    shadows: {
      sm: "0 1px 3px 0 oklch(0.18 0.05 265 / 0.08)",
      md: "0 2px 8px -1px oklch(0.18 0.05 265 / 0.10), 0 1px 3px 0 oklch(0.18 0.05 265 / 0.06)",
      lg: "0 4px 14px -2px oklch(0.18 0.05 265 / 0.14), 0 2px 4px 0 oklch(0.18 0.05 265 / 0.06)",
      xl: "0 8px 28px -4px oklch(0.18 0.05 265 / 0.16), 0 4px 8px -2px oklch(0.18 0.05 265 / 0.06)",
      "2xl": "0 16px 48px -8px oklch(0.18 0.05 265 / 0.20)",
      glow: "0 0 28px oklch(0.55 0.22 265 / 0.20)",
      "glow-sm": "0 0 14px oklch(0.55 0.22 265 / 0.14)",
      colored: "0 4px 18px -4px oklch(0.55 0.22 265 / 0.25)",
      inner: "inset 0 2px 4px 0 oklch(0.18 0.05 265 / 0.06)",
      card: "0 1px 4px 0 oklch(0.18 0.05 265 / 0.06)",
      button: "0 1px 2px 0 oklch(0.18 0.05 265 / 0.06)",
      "button-hover": "0 2px 8px -1px oklch(0.55 0.22 265 / 0.14)",
      dropdown: "0 4px 14px -2px oklch(0.18 0.05 265 / 0.14)",
      modal: "0 20px 44px -8px oklch(0.18 0.05 265 / 0.22)",
    },
    motion: {
      duration: { instant: "0ms", fast: "110ms", normal: "200ms", slow: "340ms", slower: "500ms", slowest: "750ms" },
      easing: {
        default: "cubic-bezier(0.22, 1, 0.36, 1)",
        in: "cubic-bezier(0.55, 0, 1, 0.45)",
        out: "cubic-bezier(0, 0.55, 0.45, 1)",
        "in-out": "cubic-bezier(0.45, 0, 0.55, 1)",
        spring: "cubic-bezier(0.34, 1.56, 0.64, 1)",
      },
      "hover-scale": "1.02",
      "press-scale": "0.97",
      "hover-lift": "-3px",
      "stagger-interval": "55ms",
      "stagger-interval-fast": "30ms",
    },
    borders: {
      width: { none: "0px", thin: "1px", medium: "1.5px", thick: "2px" },
      style: "solid",
      "card-border": "1px solid",
      "card-border-hover": "1px solid",
      "button-border": "1px solid",
      "input-border": "1px solid",
      "divider-style": "solid",
      "divider-width": "1px",
    },
    buttons: {
      "font-weight": "600",
      "text-transform": "none",
      "letter-spacing": "-0.005em",
      "font-family": "'Plus Jakarta Sans', system-ui, sans-serif",
      "border-width": "1px",
      "hover-effect": "glow",
      "active-scale": "0.97",
      "icon-gap": "8px",
      "min-width": "0px",
    },
    cards: {
      "border-style": "solid",
      "border-width": "1px",
      "hover-effect": "glow",
      "hover-border-color": "var(--s-border-strong)",
      padding: "28px",
      "header-padding": "28px 28px 0",
      "footer-padding": "0 28px 28px",
      "title-size": "1.125rem",
      "title-weight": "600",
      "description-size": "0.9375rem",
      background: "surface",
      shadow: "md",
      outline: true,
      "outline-on-hover-only": false,
      "gap-between": "18px",
      "content-padding-x": "28px",
      "content-padding-y": "22px",
    },
    headings: {
      "h1-size": "2.5rem",
      "h1-weight": "700",
      "h1-tracking": "-0.025em",
      "h1-leading": "1.15",
      "h2-size": "2rem",
      "h2-weight": "700",
      "h2-tracking": "-0.02em",
      "h3-size": "1.5rem",
      "h3-weight": "600",
      "h4-size": "1.25rem",
      "h4-weight": "600",
      "display-size": "4rem",
      "display-weight": "800",
      "display-tracking": "-0.035em",
      "display-leading": "1.05",
    },
    navigation: {
      "navbar-height": "60px",
      "navbar-backdrop-blur": "18px",
      "navbar-border": "none",
      "navbar-bg-opacity": "0.88",
      "nav-link-weight": "500",
      "nav-link-size": "0.9375rem",
      "nav-link-hover": "color",
      "breadcrumb-separator": "/",
      "pagination-radius": "10px",
      "sidebar-width": "260px",
      "sidebar-item-radius": "10px",
      "sidebar-item-padding": "10px 14px",
    },
    backgrounds: {
      pattern: "none",
      "pattern-opacity": "0",
      "pattern-scale": "1",
      noise: true,
      "noise-opacity": "0.02",
      "gradient-angle": "135deg",
      "gradient-type": "none",
      "hero-pattern": "noise",
      "section-divider": "none",
    },
    code: {
      "font-family": "'JetBrains Mono', ui-monospace, monospace",
      "font-size": "0.875rem",
      "line-height": "1.7",
      bg: "var(--s-surface-sunken)",
      border: "1px solid var(--s-border-muted)",
      "border-radius": "10px",
      padding: "20px",
      "tab-size": "2",
      "selection-bg": "var(--s-primary-muted)",
      "comment-color": "var(--s-text-muted)",
      "keyword-color": "oklch(0.60 0.20 265)",
      "string-color": "oklch(0.65 0.15 155)",
      "number-color": "oklch(0.72 0.14 80)",
      "function-color": "oklch(0.58 0.12 295)",
    },
    inputs: {
      height: "42px",
      "height-sm": "36px",
      "height-lg": "50px",
      "border-width": "1px",
      "focus-ring-width": "2px",
      "focus-ring-color": "var(--s-primary)",
      "focus-ring-offset": "2px",
      "placeholder-color": "var(--s-text-subtle)",
      "error-border-color": "var(--s-error)",
      "label-size": "0.875rem",
      "label-weight": "500",
      "label-spacing": "8px",
      "helper-size": "0.8125rem",
    },
    alignment: {
      "rail-width": "1080px",
      "rail-columns": "12",
      "rail-gutter": "28px",
      "rail-margin": "32px",
      "rail-visible": false,
      "rail-color": "var(--s-border-muted)",
      "content-align": "center",
      "hero-align": "center",
      "section-align": "center",
      "navbar-align": "full",
      "footer-align": "full",
    },
    sections: {
      "padding-y": "108px",
      "padding-y-hero": "148px",
      "padding-x": "32px",
      "max-width": "1080px",
      gap: "44px",
      "title-align": "center",
      "divider-above": false,
      "divider-below": false,
      "background-alt": false,
      indent: "0px",
    },
    dividers: {
      style: "none",
      width: "0px",
      color: "var(--s-border-muted)",
      spacing: "0px",
      "show-cross": false,
      "show-label": false,
      "full-bleed": false,
      ornament: "none",
    },
    gridVisuals: {
      "show-lines": false,
      "line-color": "var(--s-border-muted)",
      "line-width": "1px",
      "show-dots": false,
      "dot-size": "2px",
      "cell-background": "none",
      "cell-border": false,
      "cell-radius": "14px",
      "cell-padding": "22px",
      "hover-effect": "glow",
    },
    cursor: {
      variant: "dot",
      size: "24px",
      "dot-size": "4px",
      "stroke-width": "1.5px",
      "tick-size": "6px",
      gap: "3px",
      radius: "0px",
      color: "var(--s-text)",
      "ring-color": "var(--s-primary)",
      "dot-color": "var(--s-primary)",
      glow: "none",
      opacity: "1",
      "blend-mode": "normal",
      "z-index": "9999",
      "hide-native": false,
    },
    scrollbar: {
      width: "8px",
      height: "8px",
      padding: "2px",
      radius: "9999px",
      track: "transparent",
      thumb: "var(--s-border-muted)",
      "thumb-hover": "var(--s-border)",
      "thumb-active": "var(--s-border-strong)",
      corner: "transparent",
      border: "none",
      "firefox-width": "thin",
      gutter: "stable",
      visibility: "auto",
    },
    focus: {
      "ring-width": "2px",
      "ring-color": "var(--s-primary)",
      "ring-offset": "2px",
      "ring-shadow": "0 0 0 2px var(--s-primary)",
      "outline-color": "var(--s-primary)",
    },
    overlays: {
      bg: "rgb(0 0 0 / 0.5)",
      blur: "8px",
      surface: "var(--s-surface-elevated)",
      border: "1px solid var(--s-border-muted)",
      shadow: "var(--s-shadow-xl)",
      radius: "var(--s-radius-lg)",
      padding: "20px",
      "z-index": "50",
    },
    dataViz: {
      "series-1": "var(--s-primary)",
      "series-2": "var(--s-secondary)",
      "series-3": "var(--s-accent)",
      "series-4": "var(--s-info)",
      "series-5": "var(--s-success)",
      positive: "var(--s-success)",
      negative: "var(--s-error)",
      neutral: "var(--s-text-muted)",
      grid: "var(--s-border-muted)",
      axis: "var(--s-border)",
      label: "var(--s-text-secondary)",
      "tooltip-bg": "var(--s-surface-elevated)",
      "tooltip-border": "var(--s-border-muted)",
    },
    media: {
      radius: "var(--s-radius-md)",
      border: "none",
      outline: "1px solid rgb(0 0 0 / 0.08)",
      shadow: "none",
      bg: "var(--s-surface-sunken)",
      "object-fit": "cover",
    },
    controls: {
      height: "38px",
      "height-sm": "30px",
      "height-lg": "46px",
      "hit-area": "44px",
      "icon-size": "16px",
      "handle-size": "20px",
      "track-height": "4px",
      "track-bg": "var(--s-border-muted)",
      "track-fill": "var(--s-primary)",
      "thumb-bg": "var(--s-surface-elevated)",
      "thumb-border": "2px solid var(--s-primary)",
    },
    componentSurfaces: {
      bg: "var(--s-surface)",
      "bg-elevated": "var(--s-surface-elevated)",
      "bg-muted": "var(--s-surface-sunken)",
      border: "var(--s-border)",
      "border-muted": "var(--s-border-muted)",
      "border-strong": "var(--s-border-strong)",
      text: "var(--s-text)",
      "text-muted": "var(--s-text-muted)",
      contrast: "var(--s-primary-contrast)",
      "hover-bg": "var(--s-surface-elevated)",
      "active-bg": "var(--s-surface-sunken)",
      "selected-bg": "var(--s-primary-muted)",
    },

  },
};
