import type { SigilPreset } from "@sigil-ui/tokens";

export const kovaPreset: SigilPreset = {
  name: "kova",
  metadata: {
    description: "Finnish hard. Cold precision, Nordic minimalism, ice and steel.",
    mood: "cold, precise, Nordic",
    tags: ["cold", "nordic", "minimal", "ice", "steel", "precise"],
  },
  tokens: {
    colors: {
      background: { light: "oklch(0.98 0.003 230)", dark: "oklch(0.09 0.008 240)" },
      surface: { light: "oklch(0.965 0.004 230)", dark: "oklch(0.13 0.008 240)" },
      "surface-elevated": { light: "oklch(1 0 0)", dark: "oklch(0.17 0.007 240)" },
      "surface-sunken": { light: "oklch(0.95 0.005 230)", dark: "oklch(0.06 0.008 240)" },
      primary: "oklch(0.64 0.12 230)",
      "primary-hover": "oklch(0.64 0.14 230)",
      "primary-muted": "oklch(0.7 0.05 230)",
      "primary-contrast": "oklch(0 0 0)",
      secondary: "oklch(0.5 0.03 250)",
      "secondary-hover": "oklch(0.44 0.04 250)",
      "secondary-muted": "oklch(0.5 0.015 250)",
      accent: "oklch(0.68 0.1 200)",
      "accent-hover": "oklch(0.62 0.12 200)",
      "accent-muted": "oklch(0.68 0.04 200)",
      text: { light: "oklch(0.14 0.006 240)", dark: "oklch(0.92 0.004 230)" },
      "text-secondary": { light: "oklch(0.34 0.005 240)", dark: "oklch(0.72 0.004 230)" },
      "text-muted": { light: "oklch(0.52 0.004 240)", dark: "oklch(0.62 0.004 230)" },
      "text-subtle": { light: "oklch(0.65 0.003 240)", dark: "oklch(0.50 0.003 230)" },
      "text-disabled": { light: "oklch(0.76 0.002 240)", dark: "oklch(0.32 0.002 230)" },
      "text-inverse": { light: "oklch(0.92 0.004 230)", dark: "oklch(0.14 0.006 240)" },
      border: { light: "oklch(0.65 0.004 235)", dark: "oklch(0.47 0.006 240)" },
      "border-muted": { light: "oklch(0.93 0.003 235)", dark: "oklch(0.22 0.005 240)" },
      "border-strong": { light: "oklch(0.65 0.006 235)", dark: "oklch(0.47 0.008 240)" },
      "border-interactive": { light: "oklch(0.7 0.12 230)", dark: "oklch(0.7 0.12 230)" },
      success: "oklch(0.63 0.16 155)",
      "success-muted": "oklch(0.7 0.06 155)",
      warning: "oklch(0.65 0.13 80)",
      "warning-muted": "oklch(0.78 0.05 80)",
      error: "oklch(0.6 0.18 20)",
      "error-muted": "oklch(0.6 0.07 20)",
      info: "oklch(0.64 0.12 230)",
      "info-muted": "oklch(0.7 0.05 230)",
      "gradient-start": "oklch(0.7 0.12 230)",
      "gradient-end": "oklch(0.5 0.03 250)",
      glow: "oklch(0.7 0.12 230 / 0.25)",
      highlight: { light: "oklch(0.92 0.06 230)", dark: "oklch(0.28 0.05 230)" },
    },
    typography: {
      "font-display": "'PP Acma', system-ui, sans-serif",
      "font-body": "'PP Mori', system-ui, sans-serif",
      "font-mono": "'PP Supply Mono', ui-monospace, monospace",
      "size-xs": "0.6875rem",
      "size-sm": "0.8125rem",
      "size-base": "0.9375rem",
      "size-lg": "1.0625rem",
      "size-xl": "1.1875rem",
      "size-2xl": "1.375rem",
      "size-3xl": "1.6875rem",
      "size-4xl": "2rem",
      "size-5xl": "2.625rem",
      "size-6xl": "3.25rem",
      "weight-normal": "400",
      "weight-medium": "500",
      "weight-semibold": "600",
      "weight-bold": "700",
      "weight-extrabold": "800",
      "leading-tight": "1.2",
      "leading-normal": "1.5",
      "leading-relaxed": "1.625",
      "leading-loose": "1.875",
      "tracking-tighter": "-0.04em",
      "tracking-tight": "-0.02em",
      "tracking-normal": "0em",
      "tracking-wide": "0.025em",
      "tracking-wider": "0.05em",
      "heading-weight": "300",
      "heading-tracking": "-0.01em",
      "heading-transform": "uppercase",
      "heading-family": "'PP Acma', system-ui, sans-serif",
    },
    spacing: {
      scale: [4, 8, 12, 16, 20, 28, 40, 56, 72, 88],
      unit: "px",
      "button-px": "20px",
      "button-py": "10px",
      "button-px-sm": "14px",
      "button-py-sm": "6px",
      "button-px-lg": "28px",
      "button-py-lg": "12px",
      "card-padding": "16px",
      "card-padding-sm": "10px",
      "card-padding-lg": "24px",
      "input-px": "12px",
      "input-py": "8px",
      "badge-px": "8px",
      "badge-py": "2px",
      "section-py": "56px",
      "section-py-lg": "80px",
      "navbar-height": "52px",
      "navbar-px": "16px",
      "footer-py": "36px",
      "modal-padding": "24px",
      "popover-padding": "14px",
      "tooltip-padding": "6px 10px",
      "table-cell-px": "14px",
      "table-cell-py": "10px",
    },
    layout: {
      "content-max": "1200px",
      "content-max-narrow": "720px",
      "content-max-wide": "1440px",
      "page-margin": "16px",
      "page-margin-sm": "16px",
      "page-margin-lg": "36px",
      gutter: "16px",
      "gutter-sm": "8px",
      "gutter-lg": "24px",
      "grid-columns": "12",
      "grid-gap": "16px",
      "bento-gap": "8px",
      "bento-radius": "6px",
      "bento-min-height": "180px",
      "section-gap": "28px",
      "sidebar-width": "232px",
      "sidebar-collapsed": "52px",
      "footer-columns": "4",
      "stack-gap": "12px",
      "stack-gap-sm": "6px",
      "stack-gap-lg": "20px",
      "prose-max": "60ch",
    },
    sigil: {
      "grid-cell": "36px",
      "cross-arm": "6px",
      "cross-stroke": "0.75px",
      "rail-gap": "16px",
      "card-radius": "6px",
      "gutter-pattern": "dots",
      "margin-pattern": "wave",
    },
    radius: {
      none: "0px",
      sm: "2px",
      md: "4px",
      lg: "6px",
      xl: "8px",
      "2xl": "12px",
      full: "9999px",
      button: "4px",
      card: "6px",
      input: "4px",
      badge: "9999px",
      modal: "8px",
      popover: "6px",
      tooltip: "4px",
      image: "4px",
      bento: "6px",
    },
    shadows: {
      sm: "0 1px 2px 0 rgb(0 0 0 / 0.04)",
      md: "0 1px 4px -1px rgb(0 0 0 / 0.06), 0 0 0 1px rgb(0 0 0 / 0.03)",
      lg: "0 3px 8px -2px rgb(0 0 0 / 0.08), 0 1px 2px -1px rgb(0 0 0 / 0.04)",
      xl: "0 6px 16px -4px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.04)",
      "2xl": "0 16px 36px -8px rgb(0 0 0 / 0.15)",
      glow: "0 0 16px var(--s-primary)",
      "glow-sm": "0 0 8px var(--s-primary)",
      colored: "0 4px 12px -3px var(--s-primary)",
      inner: "inset 0 1px 3px 0 rgb(0 0 0 / 0.04)",
      card: "0 1px 4px -1px rgb(0 0 0 / 0.05), 0 0 0 1px var(--s-border-muted)",
      button: "none",
      "button-hover": "0 1px 3px -1px rgb(0 0 0 / 0.08)",
      dropdown: "0 4px 12px -2px rgb(0 0 0 / 0.1), 0 0 0 1px rgb(0 0 0 / 0.03)",
      modal: "0 16px 48px -12px rgb(0 0 0 / 0.2)",
    },
    motion: {
      duration: { instant: "0ms", fast: "120ms", normal: "220ms", slow: "350ms", slower: "500ms", slowest: "800ms" },
      easing: {
        default: "cubic-bezier(0.22, 1, 0.36, 1)",
        in: "cubic-bezier(0.55, 0, 1, 0.45)",
        out: "cubic-bezier(0, 0.55, 0.45, 1)",
        "in-out": "cubic-bezier(0.45, 0, 0.55, 1)",
        spring: "cubic-bezier(0.22, 1, 0.36, 1)",
        bounce: "cubic-bezier(0.68, -0.55, 0.27, 1.55)",
      },
      "enter-preset": "fadeIn",
      "exit-preset": "fadeOut",
      "hover-scale": "1.01",
      "press-scale": "0.98",
      "hover-lift": "-1px",
      "stagger-interval": "50ms",
      "stagger-interval-fast": "25ms",
    },
    borders: {
      width: { none: "0px", thin: "1px", medium: "1.5px", thick: "2px" },
      style: "solid",
      "card-border": "1px solid",
      "card-border-hover": "1px solid",
      "button-border": "1px solid",
      "input-border": "1px solid",
      "divider-style": "dashed",
      "divider-width": "1px",
    },
    buttons: {
      "font-weight": "500",
      "text-transform": "none",
      "letter-spacing": "0.025em",
      "font-family": "'PP Mori', system-ui, sans-serif",
      "border-width": "1px",
      "hover-effect": "darken",
      "active-scale": "0.98",
      "icon-gap": "8px",
      "min-width": "0px",
    },
    cards: {
      "border-style": "solid",
      "border-width": "1px",
      "hover-effect": "lift",
      "hover-border-color": "var(--s-border-strong)",
      padding: "22px",
      "header-padding": "22px 22px 0",
      "footer-padding": "0 22px 22px",
      "title-size": "1.0625rem",
      "title-weight": "600",
      "description-size": "0.8125rem",
      background: "surface",
      shadow: "none",
      outline: true,
      "outline-on-hover-only": false,
      "gap-between": "14px",
      "content-padding-x": "22px",
      "content-padding-y": "18px",
    },
    headings: {
      "h1-size": "2rem",
      "h1-weight": "700",
      "h1-tracking": "-0.025em",
      "h1-leading": "1.2",
      "h2-size": "1.6875rem",
      "h2-weight": "700",
      "h2-tracking": "-0.02em",
      "h3-size": "1.375rem",
      "h3-weight": "600",
      "h4-size": "1.1875rem",
      "h4-weight": "600",
      "display-size": "3.25rem",
      "display-weight": "800",
      "display-tracking": "-0.04em",
      "display-leading": "1.1",
    },
    navigation: {
      "navbar-height": "52px",
      "navbar-backdrop-blur": "8px",
      "navbar-border": "1px solid",
      "navbar-bg-opacity": "0.95",
      "nav-link-weight": "500",
      "nav-link-size": "0.75rem",
      "nav-link-hover": "underline",
      "breadcrumb-separator": "/",
      "pagination-radius": "4px",
      "sidebar-width": "232px",
      "sidebar-item-radius": "2px",
      "sidebar-item-padding": "6px 10px",
    },
    backgrounds: {
      pattern: "dots",
      "pattern-opacity": "0.04",
      "pattern-scale": "0.8",
      noise: true,
      "noise-opacity": "0.015",
      "gradient-angle": "180deg",
      "gradient-type": "none",
      "hero-pattern": "noise",
      "section-divider": "line",
    },
    code: {
      "font-family": "'PP Supply Mono', ui-monospace, monospace",
      "font-size": "0.8125rem",
      "line-height": "1.65",
      bg: "var(--s-surface-sunken)",
      border: "1px solid var(--s-border)",
      "border-radius": "4px",
      padding: "14px",
      "tab-size": "2",
      "selection-bg": "var(--s-primary-muted)",
      "comment-color": "var(--s-text-muted)",
      "keyword-color": "var(--s-primary)",
      "string-color": "var(--s-success)",
      "number-color": "var(--s-warning)",
      "function-color": "var(--s-accent)",
    },
    inputs: {
      height: "38px",
      "height-sm": "30px",
      "height-lg": "46px",
      "border-width": "1px",
      "focus-ring-width": "2px",
      "focus-ring-color": "var(--s-primary)",
      "focus-ring-offset": "1px",
      "placeholder-color": "var(--s-text-subtle)",
      "error-border-color": "var(--s-error)",
      "label-size": "0.8125rem",
      "label-weight": "500",
      "label-spacing": "6px",
      "helper-size": "0.75rem",
    },
    alignment: {
      "rail-width": "1120px",
      "rail-columns": "12",
      "rail-gutter": "24px",
      "rail-margin": "32px",
      "rail-visible": false,
      "rail-color": "var(--s-border-muted)",
      "content-align": "center",
      "hero-align": "center",
      "section-align": "center",
      "navbar-align": "full",
      "footer-align": "content",
    },
    sections: {
      "padding-y": "80px",
      "padding-y-hero": "128px",
      "padding-x": "32px",
      "max-width": "1120px",
      gap: "40px",
      "title-align": "left",
      "divider-above": false,
      "divider-below": true,
      "background-alt": false,
      indent: "0px",
    },
    dividers: {
      style: "solid",
      width: "0.5px",
      color: "var(--s-border)",
      spacing: "0px",
      "show-cross": false,
      "show-label": false,
      "full-bleed": false,
      ornament: "none",
    },
    gridVisuals: {
      "show-lines": false,
      "line-color": "var(--s-border-muted)",
      "line-width": "1px",
      "show-dots": true,
      "dot-size": "1px",
      "cell-background": "none",
      "cell-border": false,
      "cell-radius": "0px",
      "cell-padding": "16px",
      "hover-effect": "none",
    },
    cursor: {
      variant: "sigil",
      size: "24px",
      "dot-size": "4px",
      "stroke-width": "1.5px",
      "tick-size": "6px",
      gap: "3px",
      radius: "0px",
      color: "var(--s-text)",
      "ring-color": "var(--s-primary)",
      "dot-color": "var(--s-primary)",
      glow: "none",
      opacity: "1",
      "blend-mode": "normal",
      "z-index": "9999",
      "hide-native": false,
    },
    scrollbar: {
      width: "6px",
      height: "6px",
      padding: "2px",
      radius: "9999px",
      track: "transparent",
      thumb: "var(--s-border-muted)",
      "thumb-hover": "var(--s-border)",
      "thumb-active": "var(--s-border-strong)",
      corner: "transparent",
      border: "none",
      "firefox-width": "thin",
      gutter: "stable",
      visibility: "auto",
    },
    focus: {
      "ring-width": "2px",
      "ring-color": "var(--s-primary)",
      "ring-offset": "2px",
      "ring-shadow": "0 0 0 2px var(--s-primary)",
      "outline-color": "var(--s-primary)",
    },
    overlays: {
      bg: "rgb(0 0 0 / 0.5)",
      blur: "8px",
      surface: "var(--s-surface-elevated)",
      border: "1px solid var(--s-border-muted)",
      shadow: "var(--s-shadow-xl)",
      radius: "var(--s-radius-lg)",
      padding: "20px",
      "z-index": "50",
    },
    dataViz: {
      "series-1": "var(--s-primary)",
      "series-2": "var(--s-secondary)",
      "series-3": "var(--s-accent)",
      "series-4": "var(--s-info)",
      "series-5": "var(--s-success)",
      positive: "var(--s-success)",
      negative: "var(--s-error)",
      neutral: "var(--s-text-muted)",
      grid: "var(--s-border-muted)",
      axis: "var(--s-border)",
      label: "var(--s-text-secondary)",
      "tooltip-bg": "var(--s-surface-elevated)",
      "tooltip-border": "var(--s-border-muted)",
    },
    media: {
      radius: "var(--s-radius-md)",
      border: "none",
      outline: "1px solid rgb(0 0 0 / 0.08)",
      shadow: "none",
      bg: "var(--s-surface-sunken)",
      "object-fit": "cover",
    },
    controls: {
      height: "38px",
      "height-sm": "30px",
      "height-lg": "46px",
      "hit-area": "44px",
      "icon-size": "16px",
      "handle-size": "20px",
      "track-height": "4px",
      "track-bg": "var(--s-border-muted)",
      "track-fill": "var(--s-primary)",
      "thumb-bg": "var(--s-surface-elevated)",
      "thumb-border": "2px solid var(--s-primary)",
    },
    componentSurfaces: {
      bg: "var(--s-surface)",
      "bg-elevated": "var(--s-surface-elevated)",
      "bg-muted": "var(--s-surface-sunken)",
      border: "var(--s-border)",
      "border-muted": "var(--s-border-muted)",
      "border-strong": "var(--s-border-strong)",
      text: "var(--s-text)",
      "text-muted": "var(--s-text-muted)",
      contrast: "var(--s-primary-contrast)",
      "hover-bg": "var(--s-surface-elevated)",
      "active-bg": "var(--s-surface-sunken)",
      "selected-bg": "var(--s-primary-muted)",
    },

  },
};
