import type { SigilPreset } from "@sigil-ui/tokens";

export const monoPreset: SigilPreset = {
  name: "mono",
  metadata: {
    description:
      "Monochrome monospace. Terminal aesthetic with all-mono typography, dense grid alignment, and zero decoration.",
    mood: "monochrome, monospace, single-focus",
    tags: ["light", "monochrome", "monospace", "terminal", "minimal"],
  },
  tokens: {
    colors: {
      background: { light: "#ffffff", dark: "#0a0a0a" },
      surface: { light: "#f5f5f5", dark: "#141414" },
      "surface-elevated": { light: "#ffffff", dark: "#1a1a1a" },
      "surface-sunken": { light: "#e5e5e5", dark: "#050505" },
      primary: "#525252",
      "primary-hover": "#404040",
      "primary-muted": "#52525220",
      "primary-contrast": "#ffffff",
      secondary: "#737373",
      "secondary-hover": "#525252",
      "secondary-muted": "#73737320",
      accent: "#525252",
      "accent-hover": "#404040",
      "accent-muted": "#52525215",
      text: { light: "#000000", dark: "#e5e5e5" },
      "text-secondary": { light: "#262626", dark: "#a3a3a3" },
      "text-muted": { light: "#525252", dark: "#858585" },
      "text-subtle": { light: "#737373", dark: "#666666" },
      "text-disabled": { light: "#a3a3a3", dark: "#404040" },
      "text-inverse": { light: "#ffffff", dark: "#000000" },
      border: { light: "#d4d4d4", dark: "#333333" },
      "border-muted": { light: "#e5e5e5", dark: "#282828" },
      "border-strong": { light: "#a3a3a3", dark: "#404040" },
      "border-interactive": { light: "#525252", dark: "#737373" },
      success: "#22c55e",
      "success-muted": "#22c55e15",
      warning: "#eab308",
      "warning-muted": "#eab30815",
      error: "#ef4444",
      "error-muted": "#ef444415",
      info: "#525252",
      "info-muted": "#52525215",
      "gradient-start": "#525252",
      "gradient-end": "#a3a3a3",
      glow: "#52525225",
    },
    typography: {
      "font-display": "'PP Supply Mono', ui-monospace, monospace",
      "font-body": "'PP Supply Mono', ui-monospace, monospace",
      "font-mono": "'PP Supply Mono', ui-monospace, monospace",
      "size-xs": "0.6875rem",
      "size-sm": "0.75rem",
      "size-base": "0.8125rem",
      "size-lg": "0.875rem",
      "size-xl": "1rem",
      "size-2xl": "1.1875rem",
      "size-3xl": "1.4375rem",
      "size-4xl": "1.75rem",
      "size-5xl": "2.25rem",
      "size-6xl": "3rem",
      "weight-normal": "400",
      "weight-medium": "500",
      "weight-semibold": "600",
      "weight-bold": "700",
      "weight-extrabold": "800",
      "leading-tight": "1.3",
      "leading-normal": "1.5",
      "leading-relaxed": "1.625",
      "leading-loose": "1.85",
      "tracking-tighter": "-0.02em",
      "tracking-tight": "-0.01em",
      "tracking-normal": "0em",
      "tracking-wide": "0.04em",
      "tracking-wider": "0.08em",
      "heading-weight": "400",
      "heading-tracking": "0.15em",
      "heading-transform": "uppercase",
      "heading-family": "'PP Supply Mono', ui-monospace, monospace",
    },
    spacing: {
      scale: [2, 4, 8, 12, 16, 20, 24, 32, 48, 64],
      unit: "px",
      "button-px": "16px",
      "button-py": "8px",
      "button-px-sm": "10px",
      "button-py-sm": "4px",
      "button-px-lg": "24px",
      "button-py-lg": "10px",
      "card-padding": "12px",
      "card-padding-sm": "8px",
      "card-padding-lg": "20px",
      "input-px": "8px",
      "input-py": "6px",
      "badge-px": "6px",
      "badge-py": "2px",
      "section-py": "40px",
      "section-py-lg": "60px",
      "navbar-height": "40px",
      "navbar-px": "12px",
      "footer-py": "24px",
      "modal-padding": "20px",
      "popover-padding": "12px",
      "tooltip-padding": "4px 8px",
      "table-cell-px": "12px",
      "table-cell-py": "8px",
    },
    layout: {
      "content-max": "1040px",
      "content-max-narrow": "640px",
      "content-max-wide": "1320px",
      "page-margin": "12px",
      "page-margin-sm": "8px",
      "page-margin-lg": "24px",
      gutter: "8px",
      "gutter-sm": "4px",
      "gutter-lg": "16px",
      "grid-columns": "12",
      "grid-gap": "8px",
      "bento-gap": "4px",
      "bento-radius": "0px",
      "bento-min-height": "160px",
      "section-gap": "24px",
      "sidebar-width": "200px",
      "sidebar-collapsed": "48px",
      "footer-columns": "4",
      "stack-gap": "8px",
      "stack-gap-sm": "4px",
      "stack-gap-lg": "16px",
      "prose-max": "72ch",
    },
    sigil: {
      "grid-cell": "32px",
      "cross-arm": "6px",
      "cross-stroke": "0.5px",
      "rail-gap": "12px",
      "card-radius": "0px",
      "gutter-pattern": "grid",
      "margin-pattern": "checker",
    },
    radius: {
      none: "0px",
      sm: "0px",
      md: "0px",
      lg: "0px",
      xl: "0px",
      "2xl": "0px",
      full: "0px",
      button: "0px",
      card: "0px",
      input: "0px",
      badge: "0px",
      modal: "0px",
      popover: "0px",
      tooltip: "0px",
      image: "0px",
      bento: "0px",
    },
    shadows: {
      sm: "0 1px 2px rgb(0 0 0 / 0.04)",
      md: "0 1px 3px rgb(0 0 0 / 0.06)",
      lg: "0 2px 6px rgb(0 0 0 / 0.08)",
      xl: "0 4px 12px rgb(0 0 0 / 0.1)",
      "2xl": "none",
      glow: "none",
      "glow-sm": "none",
      colored: "none",
      inner: "none",
      card: "none",
      button: "none",
      "button-hover": "none",
      dropdown: "0 2px 8px rgb(0 0 0 / 0.1)",
      modal: "0 8px 32px rgb(0 0 0 / 0.15)",
    },
    motion: {
      duration: { instant: "0ms", fast: "80ms", normal: "150ms", slow: "250ms", slower: "400ms", slowest: "600ms" },
      easing: {
        default: "cubic-bezier(0, 0, 1, 1)",
        in: "cubic-bezier(0.55, 0, 1, 0.45)",
        out: "cubic-bezier(0, 0.55, 0.45, 1)",
        "in-out": "cubic-bezier(0.45, 0, 0.55, 1)",
        spring: "cubic-bezier(0.22, 1, 0.36, 1)",
        bounce: "cubic-bezier(0.68, -0.55, 0.27, 1.55)",
      },
      "enter-preset": "fadeIn",
      "exit-preset": "fadeOut",
      "hover-scale": "1",
      "press-scale": "0.98",
      "hover-lift": "0px",
      "stagger-interval": "30ms",
      "stagger-interval-fast": "15ms",
    },
    borders: {
      width: { none: "0px", thin: "1px", medium: "1.5px", thick: "2px" },
      style: "dashed",
      "card-border": "1px solid",
      "card-border-hover": "1px solid",
      "button-border": "1px solid",
      "input-border": "1px solid",
      "divider-style": "dashed",
      "divider-width": "1px",
    },
    buttons: {
      "font-weight": "500",
      "text-transform": "uppercase",
      "letter-spacing": "0.04em",
      "font-family": "'PP Supply Mono', ui-monospace, monospace",
      "border-width": "1px",
      "hover-effect": "outline",
      "active-scale": "0.98",
      "icon-gap": "6px",
      "min-width": "0px",
    },
    cards: {
      "border-style": "solid",
      "border-width": "1px",
      "hover-effect": "border",
      "hover-border-color": "var(--s-border-strong)",
      padding: "16px",
      "header-padding": "16px 16px 0",
      "footer-padding": "0 16px 16px",
      "title-size": "0.875rem",
      "title-weight": "700",
      "description-size": "0.75rem",
      outline: true,
      shadow: "none",
    },
    headings: {
      "h1-size": "1.75rem",
      "h1-weight": "700",
      "h1-tracking": "0.02em",
      "h1-leading": "1.3",
      "h2-size": "1.4375rem",
      "h2-weight": "700",
      "h2-tracking": "0.02em",
      "h3-size": "1.1875rem",
      "h3-weight": "600",
      "h4-size": "1rem",
      "h4-weight": "600",
      "display-size": "3rem",
      "display-weight": "800",
      "display-tracking": "0.04em",
      "display-leading": "1.15",
    },
    navigation: {
      "navbar-height": "40px",
      "navbar-backdrop-blur": "0px",
      "navbar-border": "1px solid",
      "navbar-bg-opacity": "1",
      "nav-link-weight": "400",
      "nav-link-size": "0.6875rem",
      "nav-link-hover": "underline",
      "breadcrumb-separator": " > ",
      "pagination-radius": "0px",
      "sidebar-width": "200px",
      "sidebar-item-radius": "0px",
      "sidebar-item-padding": "4px 6px",
    },
    backgrounds: {
      pattern: "grid",
      "pattern-opacity": "0.04",
      "pattern-scale": "1",
      noise: false,
      "noise-opacity": "0",
      "gradient-angle": "0deg",
      "gradient-type": "none",
      "hero-pattern": "grid",
      "section-divider": "line",
    },
    code: {
      "font-family": "'PP Supply Mono', ui-monospace, monospace",
      "font-size": "0.8125rem",
      "line-height": "1.6",
      bg: "var(--s-surface-sunken)",
      border: "1px solid var(--s-border)",
      "border-radius": "0px",
      padding: "12px",
      "tab-size": "4",
      "selection-bg": "#52525225",
      "comment-color": "var(--s-text-muted)",
      "keyword-color": "#000000",
      "string-color": "#525252",
      "number-color": "#737373",
      "function-color": "#262626",
    },
    inputs: {
      height: "36px",
      "height-sm": "28px",
      "height-lg": "44px",
      "border-width": "1px",
      "focus-ring-width": "2px",
      "focus-ring-color": "#525252",
      "focus-ring-offset": "1px",
      "placeholder-color": "var(--s-text-subtle)",
      "error-border-color": "#ef4444",
      "label-size": "0.75rem",
      "label-weight": "500",
      "label-spacing": "4px",
      "helper-size": "0.6875rem",
    },
    alignment: {
      "title-align": "left",
      "rail-visible": true,
      "rail-columns": "8",
      "rail-margin": "24px",
    },
    sections: {
      "padding-y": "48px",
      gap: "24px",
    },
    dividers: {
      style: "solid",
      width: "1px",
    },
    gridVisuals: {
      "show-lines": true,
      "line-width": "1px",
      "cell-border": true,
      "cell-background": "surface",
    },
  },
};
