import type { SigilPreset } from "@sigil-ui/tokens";

export const mossPreset: SigilPreset = {
  name: "moss",
  metadata: {
    description: "Dark forest green with organic-tech energy. Deep mossy backgrounds, bright green primaries, warm gold accent.",
    mood: "forest, deep, organic-tech",
    tags: ["edgeless", "dark", "green", "forest", "organic"],
  },
  tokens: {
    colors: {
      background: { light: "oklch(0.94 0.03 145)", dark: "oklch(0.12 0.04 145)" },
      surface: { light: "oklch(0.91 0.035 145)", dark: "oklch(0.16 0.045 145)" },
      "surface-elevated": { light: "oklch(0.95 0.025 145)", dark: "oklch(0.20 0.05 145)" },
      "surface-sunken": { light: "oklch(0.88 0.04 145)", dark: "oklch(0.08 0.03 145)" },
      primary: { light: "oklch(0.55 0.15 145)", dark: "oklch(0.70 0.14 145)" },
      "primary-hover": { light: "oklch(0.48 0.17 145)", dark: "oklch(0.76 0.12 145)" },
      "primary-muted": { light: "oklch(0.55 0.05 145)", dark: "oklch(0.70 0.05 145)" },
      "primary-contrast": { light: "oklch(0.08 0.02 145)", dark: "oklch(0.12 0.04 145)" },
      secondary: "oklch(0.58 0.10 170)",
      "secondary-hover": "oklch(0.52 0.12 170)",
      "secondary-muted": "oklch(0.58 0.04 170)",
      accent: { light: "oklch(0.68 0.12 85)", dark: "oklch(0.74 0.11 85)" },
      "accent-hover": { light: "oklch(0.62 0.14 85)", dark: "oklch(0.80 0.09 85)" },
      "accent-muted": { light: "oklch(0.68 0.04 85)", dark: "oklch(0.74 0.04 85)" },
      text: { light: "oklch(0.16 0.02 145)", dark: "oklch(0.92 0.015 145)" },
      "text-secondary": { light: "oklch(0.34 0.015 145)", dark: "oklch(0.74 0.015 145)" },
      "text-muted": { light: "oklch(0.50 0.015 145)", dark: "oklch(0.55 0.02 145)" },
      "text-subtle": { light: "oklch(0.64 0.01 145)", dark: "oklch(0.42 0.02 145)" },
      "text-disabled": { light: "oklch(0.78 0.008 145)", dark: "oklch(0.28 0.015 145)" },
      "text-inverse": { light: "oklch(0.92 0.015 145)", dark: "oklch(0.16 0.02 145)" },
      border: { light: "oklch(0.82 0.02 145)", dark: "oklch(0.300 0.035 145)" },
      "border-muted": { light: "oklch(0.89 0.015 145)", dark: "oklch(0.240 0.025 145)" },
      "border-strong": { light: "oklch(0.72 0.025 145)", dark: "oklch(0.380 0.040 145)" },
      "border-interactive": { light: "oklch(0.55 0.15 145)", dark: "oklch(0.70 0.14 145)" },
      success: "oklch(0.65 0.17 155)",
      "success-muted": { light: "oklch(0.95 0.03 155)", dark: "oklch(0.15 0.04 155)" },
      warning: "oklch(0.72 0.14 80)",
      "warning-muted": { light: "oklch(0.96 0.03 80)", dark: "oklch(0.16 0.04 80)" },
      error: "oklch(0.55 0.18 25)",
      "error-muted": { light: "oklch(0.96 0.03 25)", dark: "oklch(0.16 0.04 25)" },
      info: "oklch(0.60 0.14 240)",
      "info-muted": { light: "oklch(0.96 0.02 240)", dark: "oklch(0.16 0.03 240)" },
      "gradient-start": { light: "oklch(0.55 0.15 145)", dark: "oklch(0.70 0.14 145)" },
      "gradient-end": { light: "oklch(0.68 0.12 85)", dark: "oklch(0.74 0.11 85)" },
      glow: { light: "oklch(0.55 0.15 145 / 0.15)", dark: "oklch(0.70 0.14 145 / 0.2)" },
      highlight: { light: "oklch(0.92 0.06 145)", dark: "oklch(0.28 0.05 145)" },
    },
    typography: {
      "font-display": "'Space Grotesk', system-ui, sans-serif",
      "font-body": "'Inter', system-ui, sans-serif",
      "font-mono": "'JetBrains Mono', ui-monospace, monospace",
      "size-xs": "0.75rem",
      "size-sm": "0.8125rem",
      "size-base": "0.875rem",
      "size-lg": "1rem",
      "size-xl": "1.125rem",
      "size-2xl": "1.375rem",
      "size-3xl": "1.75rem",
      "size-4xl": "2.25rem",
      "size-5xl": "3rem",
      "size-6xl": "3.75rem",
      "weight-normal": "400",
      "weight-medium": "500",
      "weight-semibold": "600",
      "weight-bold": "700",
      "weight-extrabold": "800",
      "leading-tight": "1.2",
      "leading-normal": "1.5",
      "leading-relaxed": "1.625",
      "leading-loose": "2",
      "tracking-tighter": "-0.04em",
      "tracking-tight": "-0.025em",
      "tracking-normal": "0em",
      "tracking-wide": "0.025em",
      "tracking-wider": "0.05em",
      "heading-weight": "600",
      "heading-tracking": "-0.025em",
      "heading-transform": "none",
      "heading-family": "'Space Grotesk', system-ui, sans-serif",
    },
    spacing: {
      scale: [4, 8, 12, 16, 24, 32, 48, 64, 80, 96],
      unit: "px",
      "button-px": "18px",
      "button-py": "9px",
      "button-px-sm": "12px",
      "button-py-sm": "6px",
      "button-px-lg": "24px",
      "button-py-lg": "12px",
      "card-padding": "24px",
      "card-padding-sm": "16px",
      "card-padding-lg": "36px",
      "input-px": "12px",
      "input-py": "9px",
      "badge-px": "10px",
      "badge-py": "3px",
      "section-py": "80px",
      "section-py-lg": "120px",
      "navbar-height": "56px",
      "navbar-px": "24px",
      "footer-py": "56px",
      "modal-padding": "24px",
      "popover-padding": "14px",
      "tooltip-padding": "6px 12px",
      "table-cell-px": "14px",
      "table-cell-py": "10px",
    },
    layout: {
      "content-max": "1200px",
      "content-max-narrow": "700px",
      "content-max-wide": "1400px",
      "page-margin": "24px",
      "page-margin-sm": "16px",
      "page-margin-lg": "48px",
      gutter: "0px",
      "gutter-sm": "0px",
      "gutter-lg": "0px",
      "grid-columns": "12",
      "grid-gap": "24px",
      "bento-gap": "16px",
      "bento-radius": "6px",
      "bento-min-height": "200px",
      "section-gap": "32px",
      "sidebar-width": "256px",
      "sidebar-collapsed": "48px",
      "footer-columns": "4",
      "stack-gap": "16px",
      "stack-gap-sm": "8px",
      "stack-gap-lg": "24px",
      "prose-max": "65ch",
    },
    sigil: {
      "grid-cell": "48px",
      "cross-arm": "0px",
      "cross-stroke": "0px",
      "rail-gap": "0px",
      "card-radius": "6px",
      "gutter-pattern": "none",
      "margin-pattern": "none",
      "gutter-border": "none",
      "gutter-visible": false,
    },
    radius: {
      none: "0px",
      sm: "3px",
      md: "5px",
      lg: "8px",
      xl: "12px",
      "2xl": "16px",
      full: "9999px",
      button: "5px",
      card: "6px",
      input: "5px",
      badge: "3px",
      modal: "10px",
      popover: "8px",
      tooltip: "4px",
      image: "6px",
      bento: "6px",
    },
    shadows: {
      sm: "0 1px 2px 0 oklch(0.20 0.04 145 / 0.08)",
      md: "0 2px 6px -1px oklch(0.20 0.04 145 / 0.10), 0 1px 3px 0 oklch(0.20 0.04 145 / 0.06)",
      lg: "0 4px 14px -3px oklch(0.20 0.04 145 / 0.12), 0 2px 4px 0 oklch(0.20 0.04 145 / 0.05)",
      xl: "0 10px 24px -6px oklch(0.20 0.04 145 / 0.16), 0 4px 8px -2px oklch(0.20 0.04 145 / 0.06)",
      "2xl": "0 20px 48px -10px oklch(0.20 0.04 145 / 0.20)",
      glow: "0 0 28px oklch(0.70 0.14 145 / 0.25)",
      "glow-sm": "0 0 14px oklch(0.70 0.14 145 / 0.15)",
      colored: "0 4px 18px -4px oklch(0.70 0.14 145 / 0.3)",
      inner: "inset 0 2px 4px 0 oklch(0.20 0.04 145 / 0.06)",
      card: "0 1px 4px 0 oklch(0.20 0.04 145 / 0.06)",
      button: "0 1px 2px 0 oklch(0.20 0.04 145 / 0.05)",
      "button-hover": "0 2px 8px -2px oklch(0.20 0.04 145 / 0.10), 0 0 12px oklch(0.70 0.14 145 / 0.08)",
      dropdown: "0 6px 18px -4px oklch(0.20 0.04 145 / 0.14)",
      modal: "0 20px 40px -8px oklch(0.20 0.04 145 / 0.20), 0 0 24px oklch(0.70 0.14 145 / 0.06)",
    },
    motion: {
      duration: { instant: "0ms", fast: "120ms", normal: "200ms", slow: "320ms", slower: "500ms", slowest: "750ms" },
      easing: {
        default: "cubic-bezier(0.16, 1, 0.3, 1)",
        in: "cubic-bezier(0.55, 0, 1, 0.45)",
        out: "cubic-bezier(0, 0.55, 0.45, 1)",
        "in-out": "cubic-bezier(0.45, 0, 0.55, 1)",
        spring: "cubic-bezier(0.34, 1.56, 0.64, 1)",
      },
      "hover-scale": "1.02",
      "press-scale": "0.97",
      "hover-lift": "-2px",
      "stagger-interval": "50ms",
      "stagger-interval-fast": "30ms",
    },
    borders: {
      width: { none: "0px", thin: "1px", medium: "1.5px", thick: "2px" },
      style: "solid",
      "card-border": "1px solid",
      "card-border-hover": "1px solid",
      "button-border": "1px solid",
      "input-border": "1px solid",
      "divider-style": "solid",
      "divider-width": "1px",
    },
    buttons: {
      "font-weight": "500",
      "text-transform": "none",
      "letter-spacing": "0em",
      "font-family": "inherit",
      "border-width": "1px",
      "hover-effect": "glow",
      "active-scale": "0.97",
      "icon-gap": "8px",
      "min-width": "0px",
    },
    cards: {
      "border-style": "solid",
      "border-width": "1px",
      "hover-effect": "glow",
      "hover-border-color": "var(--s-primary)",
      padding: "24px",
      "header-padding": "24px 24px 0",
      "footer-padding": "0 24px 24px",
      "title-size": "1rem",
      "title-weight": "600",
      "description-size": "0.875rem",
      background: "surface",
      shadow: "sm",
      outline: true,
      "outline-on-hover-only": false,
      "gap-between": "16px",
      "content-padding-x": "24px",
      "content-padding-y": "20px",
    },
    headings: {
      "h1-size": "2.25rem",
      "h1-weight": "700",
      "h1-tracking": "-0.025em",
      "h1-leading": "1.12",
      "h2-size": "1.75rem",
      "h2-weight": "600",
      "h2-tracking": "-0.02em",
      "h3-size": "1.375rem",
      "h3-weight": "600",
      "h4-size": "1.125rem",
      "h4-weight": "600",
      "display-size": "3.5rem",
      "display-weight": "800",
      "display-tracking": "-0.035em",
      "display-leading": "1.06",
    },
    navigation: {
      "navbar-height": "56px",
      "navbar-backdrop-blur": "16px",
      "navbar-border": "none",
      "navbar-bg-opacity": "0.80",
      "nav-link-weight": "500",
      "nav-link-size": "0.875rem",
      "nav-link-hover": "color",
      "breadcrumb-separator": "/",
      "pagination-radius": "5px",
      "sidebar-width": "256px",
      "sidebar-item-radius": "5px",
      "sidebar-item-padding": "8px 12px",
    },
    backgrounds: {
      pattern: "none",
      "pattern-opacity": "0",
      "pattern-scale": "1",
      noise: true,
      "noise-opacity": "0.02",
      "gradient-angle": "180deg",
      "gradient-type": "none",
      "hero-pattern": "noise",
      "section-divider": "none",
    },
    code: {
      "font-family": "'JetBrains Mono', ui-monospace, monospace",
      "font-size": "0.8125rem",
      "line-height": "1.6",
      bg: "var(--s-surface-sunken)",
      border: "1px solid var(--s-border-muted)",
      "border-radius": "5px",
      padding: "16px",
      "tab-size": "2",
      "selection-bg": "oklch(0.70 0.14 145 / 0.2)",
      "comment-color": "var(--s-text-muted)",
      "keyword-color": "oklch(0.70 0.14 145)",
      "string-color": "oklch(0.74 0.11 85)",
      "number-color": "oklch(0.68 0.16 50)",
      "function-color": "oklch(0.62 0.14 240)",
    },
    inputs: {
      height: "38px",
      "height-sm": "32px",
      "height-lg": "46px",
      "border-width": "1px",
      "focus-ring-width": "2px",
      "focus-ring-color": "var(--s-primary)",
      "focus-ring-offset": "1px",
      "placeholder-color": "var(--s-text-subtle)",
      "error-border-color": "var(--s-error)",
      "label-size": "0.8125rem",
      "label-weight": "500",
      "label-spacing": "6px",
      "helper-size": "0.75rem",
    },
    alignment: {
      "rail-width": "1200px",
      "rail-columns": "12",
      "rail-gutter": "24px",
      "rail-margin": "24px",
      "rail-visible": false,
      "rail-color": "var(--s-border-muted)",
      "content-align": "center",
      "hero-align": "center",
      "section-align": "center",
      "navbar-align": "full",
      "footer-align": "full",
    },
    sections: {
      "padding-y": "80px",
      "padding-y-hero": "120px",
      "padding-x": "24px",
      "max-width": "1200px",
      gap: "32px",
      "title-align": "left",
      "divider-above": false,
      "divider-below": false,
      "background-alt": false,
      indent: "0px",
    },
    dividers: {
      style: "none",
      width: "0px",
      color: "var(--s-border-muted)",
      spacing: "0px",
      "show-cross": false,
      "show-label": false,
      "full-bleed": false,
      ornament: "none",
    },
    gridVisuals: {
      "show-lines": false,
      "line-color": "var(--s-border-muted)",
      "line-width": "1px",
      "show-dots": false,
      "dot-size": "2px",
      "cell-background": "none",
      "cell-border": false,
      "cell-radius": "6px",
      "cell-padding": "20px",
      "hover-effect": "glow",
    },
    cursor: {
      variant: "dot",
      size: "24px",
      "dot-size": "4px",
      "stroke-width": "1.5px",
      "tick-size": "6px",
      gap: "3px",
      radius: "0px",
      color: "var(--s-text)",
      "ring-color": "var(--s-primary)",
      "dot-color": "var(--s-primary)",
      glow: "none",
      opacity: "1",
      "blend-mode": "normal",
      "z-index": "9999",
      "hide-native": false,
    },
    scrollbar: {
      width: "8px",
      height: "8px",
      padding: "2px",
      radius: "9999px",
      track: "transparent",
      thumb: "var(--s-border-muted)",
      "thumb-hover": "var(--s-border)",
      "thumb-active": "var(--s-border-strong)",
      corner: "transparent",
      border: "none",
      "firefox-width": "thin",
      gutter: "stable",
      visibility: "auto",
    },
    focus: {
      "ring-width": "2px",
      "ring-color": "var(--s-primary)",
      "ring-offset": "2px",
      "ring-shadow": "0 0 0 2px var(--s-primary)",
      "outline-color": "var(--s-primary)",
    },
    overlays: {
      bg: "rgb(0 0 0 / 0.5)",
      blur: "8px",
      surface: "var(--s-surface-elevated)",
      border: "1px solid var(--s-border-muted)",
      shadow: "var(--s-shadow-xl)",
      radius: "var(--s-radius-lg)",
      padding: "20px",
      "z-index": "50",
    },
    dataViz: {
      "series-1": "var(--s-primary)",
      "series-2": "var(--s-secondary)",
      "series-3": "var(--s-accent)",
      "series-4": "var(--s-info)",
      "series-5": "var(--s-success)",
      positive: "var(--s-success)",
      negative: "var(--s-error)",
      neutral: "var(--s-text-muted)",
      grid: "var(--s-border-muted)",
      axis: "var(--s-border)",
      label: "var(--s-text-secondary)",
      "tooltip-bg": "var(--s-surface-elevated)",
      "tooltip-border": "var(--s-border-muted)",
    },
    media: {
      radius: "var(--s-radius-md)",
      border: "none",
      outline: "1px solid rgb(0 0 0 / 0.08)",
      shadow: "none",
      bg: "var(--s-surface-sunken)",
      "object-fit": "cover",
    },
    controls: {
      height: "38px",
      "height-sm": "30px",
      "height-lg": "46px",
      "hit-area": "44px",
      "icon-size": "16px",
      "handle-size": "20px",
      "track-height": "4px",
      "track-bg": "var(--s-border-muted)",
      "track-fill": "var(--s-primary)",
      "thumb-bg": "var(--s-surface-elevated)",
      "thumb-border": "2px solid var(--s-primary)",
    },
    componentSurfaces: {
      bg: "var(--s-surface)",
      "bg-elevated": "var(--s-surface-elevated)",
      "bg-muted": "var(--s-surface-sunken)",
      border: "var(--s-border)",
      "border-muted": "var(--s-border-muted)",
      "border-strong": "var(--s-border-strong)",
      text: "var(--s-text)",
      "text-muted": "var(--s-text-muted)",
      contrast: "var(--s-primary-contrast)",
      "hover-bg": "var(--s-surface-elevated)",
      "active-bg": "var(--s-surface-sunken)",
      "selected-bg": "var(--s-primary-muted)",
    },

  },
};
