import type { SigilPreset } from "@sigil-ui/tokens";

export const mrkrPreset: SigilPreset = {
  name: "mrkr",
  metadata: {
    description:
      "Highlighted annotation. Editorial markup with yellow marker highlights, serif typography, and wide prose measure.",
    mood: "annotated, highlighted, editorial-markup",
    tags: ["light", "editorial", "serif", "annotation", "highlight"],
  },
  tokens: {
    colors: {
      background: { light: "#fefce8", dark: "#1a1800" },
      surface: { light: "#fef9c3", dark: "#252300" },
      "surface-elevated": { light: "#ffffff", dark: "#302d00" },
      "surface-sunken": { light: "#fef08a", dark: "#121100" },
      primary: "#b18b00",
      "primary-hover": "#9a7508",
      "primary-muted": "#eab30835",
      "primary-contrast": "#1a1400",
      secondary: "#dc2626",
      "secondary-hover": "#b91c1c",
      "secondary-muted": "#dc262625",
      accent: "#ea580c",
      "accent-hover": "#c2410c",
      "accent-muted": "#ea580c20",
      text: { light: "#1c1917", dark: "#fefce8" },
      "text-secondary": { light: "#44403c", dark: "#d6d3d1" },
      "text-muted": { light: "#78716c", dark: "#a8a29e" },
      "text-subtle": { light: "#958f8b", dark: "#8a847e" },
      "text-disabled": { light: "#d6d3d1", dark: "#57534e" },
      "text-inverse": { light: "#fefce8", dark: "#1c1917" },
      border: { light: "#928f8d", dark: "oklch(0.380 0.008 68)" },
      "border-muted": { light: "#c1bebd", dark: "oklch(0.320 0.011 78)" },
      "border-strong": { light: "#958f8b", dark: "oklch(0.465 0.009 74)" },
      "border-interactive": { light: "#eab308", dark: "#eab308" },
      success: "#16a34a",
      "success-muted": "#16a34a20",
      warning: "#ea580c",
      "warning-muted": "#ea580c20",
      error: "#dc2626",
      "error-muted": "#dc262620",
      info: "#2563eb",
      "info-muted": "#2563eb20",
      "gradient-start": "#eab308",
      "gradient-end": "#ea580c",
      glow: "#eab30840",
      highlight: { light: "#fef3c7", dark: "rgba(177, 139, 0, 0.15)" },
    },
    typography: {
      "font-display": "'PP Writer', Georgia, serif",
      "font-body": "'PP Writer', Georgia, serif",
      "font-mono": "'PP Fraktion Mono', ui-monospace, monospace",
      "size-xs": "0.8125rem",
      "size-sm": "0.875rem",
      "size-base": "1.0625rem",
      "size-lg": "1.1875rem",
      "size-xl": "1.3125rem",
      "size-2xl": "1.5rem",
      "size-3xl": "1.875rem",
      "size-4xl": "2.25rem",
      "size-5xl": "3rem",
      "size-6xl": "3.75rem",
      "weight-normal": "400",
      "weight-medium": "500",
      "weight-semibold": "600",
      "weight-bold": "700",
      "weight-extrabold": "800",
      "leading-tight": "1.3",
      "leading-normal": "1.65",
      "leading-relaxed": "1.8",
      "leading-loose": "2.1",
      "tracking-tighter": "-0.02em",
      "tracking-tight": "-0.01em",
      "tracking-normal": "0em",
      "tracking-wide": "0.02em",
      "tracking-wider": "0.04em",
      "heading-weight": "400",
      "heading-tracking": "0em",
      "heading-transform": "none",
      "heading-family": "'PP Writer', Georgia, serif",
    },
    spacing: {
      scale: [4, 8, 16, 24, 32, 40, 56, 72, 96, 120],
      unit: "px",
      "button-px": "24px",
      "button-py": "10px",
      "button-px-sm": "16px",
      "button-py-sm": "6px",
      "button-px-lg": "32px",
      "button-py-lg": "14px",
      "card-padding": "20px",
      "card-padding-sm": "18px",
      "card-padding-lg": "40px",
      "input-px": "12px",
      "input-py": "10px",
      "badge-px": "8px",
      "badge-py": "3px",
      "section-py": "56px",
      "section-py-lg": "88px",
      "navbar-height": "48px",
      "navbar-px": "20px",
      "footer-py": "40px",
      "modal-padding": "28px",
      "popover-padding": "16px",
      "tooltip-padding": "6px 12px",
      "table-cell-px": "16px",
      "table-cell-py": "12px",
    },
    layout: {
      "content-max": "1200px",
      "content-max-narrow": "720px",
      "content-max-wide": "1440px",
      "page-margin": "24px",
      "page-margin-sm": "18px",
      "page-margin-lg": "44px",
      gutter: "24px",
      "gutter-sm": "16px",
      "gutter-lg": "32px",
      "grid-columns": "12",
      "grid-gap": "20px",
      "bento-gap": "12px",
      "bento-radius": "0px",
      "bento-min-height": "180px",
      "section-gap": "40px",
      "sidebar-width": "240px",
      "sidebar-collapsed": "56px",
      "footer-columns": "3",
      "stack-gap": "18px",
      "stack-gap-sm": "10px",
      "stack-gap-lg": "28px",
      "prose-max": "75ch",
    },
    sigil: {
      "grid-cell": "44px",
      "cross-arm": "8px",
      "cross-stroke": "0.75px",
      "rail-gap": "20px",
      "card-radius": "0px",
      "gutter-pattern": "checker",
      "margin-pattern": "dots",
    },
    radius: {
      none: "0px",
      sm: "0px",
      md: "0px",
      lg: "0px",
      xl: "0px",
      "2xl": "0px",
      full: "9999px",
      button: "0px",
      card: "0px",
      input: "0px",
      badge: "0px",
      modal: "0px",
      popover: "0px",
      tooltip: "0px",
      image: "0px",
      bento: "0px",
    },
    shadows: {
      sm: "0 1px 2px rgb(44 37 23 / 0.04)",
      md: "0 1px 3px rgb(44 37 23 / 0.06)",
      lg: "0 2px 6px rgb(44 37 23 / 0.08)",
      xl: "0 4px 12px rgb(44 37 23 / 0.1)",
      "2xl": "none",
      glow: "none",
      "glow-sm": "none",
      colored: "none",
      inner: "none",
      card: "none",
      button: "none",
      "button-hover": "none",
      dropdown: "0 4px 12px rgb(0 0 0 / 0.08)",
      modal: "0 16px 40px rgb(0 0 0 / 0.12)",
    },
    motion: {
      duration: { instant: "0ms", fast: "150ms", normal: "250ms", slow: "400ms", slower: "600ms", slowest: "1000ms" },
      easing: {
        default: "cubic-bezier(0.16, 1, 0.3, 1)",
        in: "cubic-bezier(0.55, 0, 1, 0.45)",
        out: "cubic-bezier(0, 0.55, 0.45, 1)",
        "in-out": "cubic-bezier(0.45, 0, 0.55, 1)",
        spring: "cubic-bezier(0.22, 1, 0.36, 1)",
        bounce: "cubic-bezier(0.68, -0.55, 0.27, 1.55)",
      },
      "enter-preset": "fadeIn",
      "exit-preset": "fadeOut",
      "hover-scale": "1",
      "press-scale": "0.99",
      "hover-lift": "0px",
      "stagger-interval": "50ms",
      "stagger-interval-fast": "25ms",
    },
    borders: {
      width: { none: "0px", thin: "1px", medium: "2px", thick: "3px" },
      style: "dashed",
      "card-border": "0px solid",
      "card-border-hover": "0px solid",
      "button-border": "0px solid",
      "input-border": "1px solid",
      "divider-style": "solid",
      "divider-width": "1px",
    },
    buttons: {
      "font-weight": "500",
      "text-transform": "none",
      "letter-spacing": "0em",
      "font-family": "'PP Writer', Georgia, serif",
      "border-width": "0px",
      "hover-effect": "fill",
      "active-scale": "0.99",
      "icon-gap": "8px",
      "min-width": "0px",
    },
    cards: {
      "border-style": "none",
      "border-width": "0px",
      "hover-effect": "border",
      "hover-border-color": "transparent",
      padding: "28px",
      "header-padding": "28px 28px 0",
      "footer-padding": "0 28px 28px",
      "title-size": "1.1875rem",
      "title-weight": "700",
      "description-size": "0.875rem",
      outline: false,
      shadow: "none",
      background: "transparent",
    },
    headings: {
      "h1-size": "2.5rem",
      "h1-weight": "700",
      "h1-tracking": "-0.01em",
      "h1-leading": "1.2",
      "h2-size": "2rem",
      "h2-weight": "700",
      "h2-tracking": "-0.005em",
      "h2-leading": "1.2",
      "h3-size": "1.5rem",
      "h3-weight": "600",
      "h3-tracking": "0em",
      "h3-leading": "1.25",
      "h4-size": "1.25rem",
      "h4-weight": "600",
      "h4-tracking": "0em",
      "h4-leading": "1.3",
      "display-size": "3.75rem",
      "display-weight": "800",
      "display-tracking": "-0.02em",
      "display-leading": "1.1",
    },
    navigation: {
      "navbar-height": "48px",
      "navbar-backdrop-blur": "0px",
      "navbar-border": "1px solid",
      "navbar-bg-opacity": "1",
      "navbar-padding-x": "32px",
      "navbar-position": "sticky",
      "navbar-logo-height": "28px",
      "navbar-logo-gap": "12px",
      "navbar-item-gap": "32px",
      "navbar-item-padding-x": "14px",
      "navbar-item-padding-y": "8px",
      "navbar-item-size": "0.875rem",
      "navbar-shadow": "none",
      "navbar-height-scrolled": "52px",
      "navbar-mobile-breakpoint": "768px",
      "nav-link-weight": "500",
      "nav-link-size": "0.875rem",
      "nav-link-hover": "underline",
      "breadcrumb-separator": " / ",
      "pagination-radius": "0px",
      "sidebar-width": "240px",
      "sidebar-item-radius": "0px",
      "sidebar-item-padding": "7px 12px",
    },
    backgrounds: {
      pattern: "dots",
      "pattern-opacity": "0.04",
      "pattern-scale": "1",
      noise: true,
      "noise-opacity": "0.02",
      "gradient-angle": "0deg",
      "gradient-type": "none",
      "hero-pattern": "noise",
      "section-divider": "line",
    },
    code: {
      "font-family": "'PP Fraktion Mono', ui-monospace, monospace",
      "font-size": "0.875rem",
      "line-height": "1.7",
      bg: "#fef9c3",
      border: "0px solid transparent",
      "border-radius": "0px",
      padding: "16px",
      "tab-size": "4",
      "selection-bg": "#eab30840",
      "comment-color": "var(--s-text-muted)",
      "keyword-color": "#dc2626",
      "string-color": "#16a34a",
      "number-color": "#ea580c",
      "function-color": "#2563eb",
    },
    inputs: {
      height: "42px",
      "height-sm": "34px",
      "height-lg": "50px",
      "border-width": "1px",
      "focus-ring-width": "2px",
      "focus-ring-color": "#eab308",
      "focus-ring-offset": "2px",
      "placeholder-color": "var(--s-text-subtle)",
      "error-border-color": "#dc2626",
      "label-size": "0.875rem",
      "label-weight": "600",
      "label-spacing": "6px",
      "helper-size": "0.8125rem",
    },
    alignment: {
      "title-align": "left",
      "rail-margin": "48px",
    },
    sections: {
      "padding-y": "72px",
      "padding-y-sm": "56px",
      gap: "36px",
      "padding-y-lg": "112px",
      "padding-y-xl": "160px",
      "max-width": "900px",
      indent: "24px",
      "heading-size": "clamp(1.75rem, 5vw, 3rem)",
      "heading-align": "left",
      "heading-max-width": "48rem",
      "heading-margin-bottom": "20px",
      "description-max-width": "36rem",
      "description-gap": "16px",
      "content-gap": "32px",
      "grid-columns": "2",
      "grid-gap": "32px",
      "alternate-bg": "var(--s-surface)",
      "alternate-bg-mode": "none",
    },
    dividers: {
      style: "solid",
      width: "2px",
      opacity: "0.4",
      "max-width": "100%",
      "margin-y": "0px",
      thickness: "1px",
      "gradient-start": "transparent",
      "gradient-end": "transparent",
      color: "var(--s-primary)",
      "show-label": true,
    },
    gridVisuals: {
      "line-color": "var(--s-border-muted)",
      "line-width": "1px",
      "show-lines": false,
    },
    cursor: {
      variant: "dot",
      size: "24px",
      "dot-size": "4px",
      "stroke-width": "1.5px",
      "tick-size": "6px",
      gap: "3px",
      radius: "0px",
      color: "var(--s-text)",
      "ring-color": "var(--s-primary)",
      "dot-color": "var(--s-primary)",
      glow: "none",
      opacity: "1",
      "blend-mode": "normal",
      "z-index": "9999",
      "hide-native": false,
    },
    scrollbar: {
      width: "6px",
      height: "6px",
      padding: "2px",
      radius: "9999px",
      track: "transparent",
      thumb: "var(--s-border-muted)",
      "thumb-hover": "var(--s-border)",
      "thumb-active": "var(--s-border-strong)",
      corner: "transparent",
      border: "none",
      "firefox-width": "thin",
      gutter: "stable",
      visibility: "auto",
    },
    focus: {
      "ring-width": "1.5px",
      "ring-color": "var(--s-primary)",
      "ring-offset": "2px",
      "ring-shadow": "0 0 0 1.5px var(--s-primary)",
      "outline-color": "var(--s-primary)",
    },
    overlays: {
      bg: "rgb(0 0 0 / 0.4)",
      blur: "4px",
      surface: "var(--s-surface-elevated)",
      border: "1px solid var(--s-border-muted)",
      shadow: "var(--s-shadow-xl)",
      radius: "var(--s-radius-lg)",
      padding: "20px",
      "z-index": "50",
    },
    dataViz: {
      "series-1": "var(--s-primary)",
      "series-2": "var(--s-secondary)",
      "series-3": "var(--s-accent)",
      "series-4": "var(--s-info)",
      "series-5": "var(--s-success)",
      positive: "var(--s-success)",
      negative: "var(--s-error)",
      neutral: "var(--s-text-muted)",
      grid: "var(--s-border-muted)",
      axis: "var(--s-border)",
      label: "var(--s-text-secondary)",
      "tooltip-bg": "var(--s-surface-elevated)",
      "tooltip-border": "var(--s-border-muted)",
    },
    media: {
      radius: "var(--s-radius-md)",
      border: "none",
      outline: "1px solid rgb(0 0 0 / 0.08)",
      shadow: "none",
      bg: "var(--s-surface-sunken)",
      "object-fit": "cover",
    },
    controls: {
      height: "38px",
      "height-sm": "30px",
      "height-lg": "46px",
      "hit-area": "44px",
      "icon-size": "16px",
      "handle-size": "20px",
      "track-height": "4px",
      "track-bg": "var(--s-border-muted)",
      "track-fill": "var(--s-primary)",
      "thumb-bg": "var(--s-surface-elevated)",
      "thumb-border": "2px solid var(--s-primary)",
    },
    componentSurfaces: {
      bg: "var(--s-surface)",
      "bg-elevated": "var(--s-surface-elevated)",
      "bg-muted": "var(--s-surface-sunken)",
      border: "var(--s-border)",
      "border-muted": "var(--s-border-muted)",
      "border-strong": "var(--s-border-strong)",
      text: "var(--s-text)",
      "text-muted": "var(--s-text-muted)",
      contrast: "var(--s-primary-contrast)",
      "hover-bg": "var(--s-surface-elevated)",
      "active-bg": "var(--s-surface-sunken)",
      "selected-bg": "var(--s-primary-muted)",
    },
    hero: {
      "min-height": "auto",
      "padding-y": "144px",
      "padding-y-sm": "80px",
      "padding-x": "var(--s-page-margin, 32px)",
      "content-max": "680px",
      "content-align": "center",
      layout: "centered",
      "media-position": "below",
      "media-width": "50%",
      "media-radius": "var(--s-radius-lg)",
      "title-size": "clamp(2.5rem, 7vw, 5rem)",
      "title-max-width": "64rem",
      "description-size": "1.1875rem",
      "description-max-width": "36rem",
      "description-gap": "32px",
      "actions-gap": "14px",
      "actions-margin-top": "40px",
      "action-padding-x": "28px",
      "action-padding-y": "14px",
      "badge-gap": "32px",
      "overlay-opacity": "0.3",
      "scroll-indicator": false,
      "gradient-overlay": "none",
    },
    cta: {
      "padding-y": "96px",
      "padding-x": "var(--s-page-margin, 32px)",
      "max-width": "var(--s-content-max, 1200px)",
      layout: "centered",
      border: false,
      "border-radius": "var(--s-radius-lg)",
      bg: "var(--s-surface)",
      "title-size": "clamp(1.75rem, 5vw, 3rem)",
      "description-max-width": "36rem",
      "description-gap": "16px",
      "actions-gap": "14px",
      "actions-margin-top": "40px",
      "action-padding-x": "28px",
      "action-padding-y": "14px",
      "split-gap": "56px",
    },
    footer: {
      "padding-y": "64px",
      "border-top": "1px solid var(--s-border)",
      columns: "4",
      "column-gap": "40px",
      "row-gap": "36px",
      "logo-height": "28px",
      "tagline-max-width": "24rem",
      "link-size": "0.875rem",
      "link-gap": "10px",
      "group-title-size": "0.75rem",
      "group-title-weight": "600",
      "social-icon-size": "18px",
      "social-gap": "14px",
      "bottom-bar-padding": "28px 0",
      "bottom-bar-border": "1px solid var(--s-border-muted)",
    },
    banner: {
      height: "auto",
      "padding-y": "10px",
      "padding-x": "20px",
      "font-size": "0.875rem",
      "font-weight": "400",
      "icon-size": "14px",
      "icon-gap": "12px",
      "border-width": "1px",
      "border-position": "bottom",
      position: "top",
      "dismiss-size": "14px",
      radius: "0px",
    },
    pageRhythm: {
      density: "editorial",
      "section-gap": "0px",
      "section-gap-sm": "0px",
      "section-gap-lg": "0px",
      "first-section-offset": "0px",
      "last-section-margin": "0px",
      "alternate-bg": false,
      "alternate-bg-color": "var(--s-surface)",
      "divider-between": true,
      "max-content-width": "var(--s-content-max, 1200px)",
      "vertical-rhythm-unit": "8px",
      "scroll-snap": false,
      "responsive-scale": "0.8",
      "responsive-breakpoint": "768px",
    },

  },
};
