import type { SigilPreset } from "@sigil-ui/tokens";

export const mrkrPreset: SigilPreset = {
  name: "mrkr",
  metadata: {
    description:
      "Highlighted annotation. Editorial markup with yellow marker highlights, serif typography, and wide prose measure.",
    mood: "annotated, highlighted, editorial-markup",
    tags: ["light", "editorial", "serif", "annotation", "highlight"],
  },
  tokens: {
    colors: {
      background: { light: "#fefce8", dark: "#1a1800" },
      surface: { light: "#fef9c3", dark: "#252300" },
      "surface-elevated": { light: "#ffffff", dark: "#302d00" },
      "surface-sunken": { light: "#fef08a", dark: "#121100" },
      primary: "#eab308",
      "primary-hover": "#ca8a04",
      "primary-muted": "#eab30835",
      "primary-contrast": "#1a1400",
      secondary: "#dc2626",
      "secondary-hover": "#b91c1c",
      "secondary-muted": "#dc262625",
      accent: "#ea580c",
      "accent-hover": "#c2410c",
      "accent-muted": "#ea580c20",
      text: { light: "#1c1917", dark: "#fefce8" },
      "text-secondary": { light: "#44403c", dark: "#d6d3d1" },
      "text-muted": { light: "#78716c", dark: "#a8a29e" },
      "text-subtle": { light: "#a8a29e", dark: "#78716c" },
      "text-disabled": { light: "#d6d3d1", dark: "#57534e" },
      "text-inverse": { light: "#fefce8", dark: "#1c1917" },
      border: { light: "#d6d3d1", dark: "#44403c" },
      "border-muted": { light: "#e7e5e4", dark: "#292524" },
      "border-strong": { light: "#a8a29e", dark: "#57534e" },
      "border-interactive": { light: "#eab308", dark: "#eab308" },
      success: "#16a34a",
      "success-muted": "#16a34a20",
      warning: "#ea580c",
      "warning-muted": "#ea580c20",
      error: "#dc2626",
      "error-muted": "#dc262620",
      info: "#2563eb",
      "info-muted": "#2563eb20",
      "gradient-start": "#eab308",
      "gradient-end": "#ea580c",
      glow: "#eab30840",
    },
    typography: {
      "font-display": "'PP Writer', Georgia, serif",
      "font-body": "'PP Writer', Georgia, serif",
      "font-mono": "'PP Fraktion Mono', ui-monospace, monospace",
      "size-xs": "0.8125rem",
      "size-sm": "0.875rem",
      "size-base": "1.0625rem",
      "size-lg": "1.1875rem",
      "size-xl": "1.3125rem",
      "size-2xl": "1.5rem",
      "size-3xl": "1.875rem",
      "size-4xl": "2.25rem",
      "size-5xl": "3rem",
      "size-6xl": "3.75rem",
      "weight-normal": "400",
      "weight-medium": "500",
      "weight-semibold": "600",
      "weight-bold": "700",
      "weight-extrabold": "800",
      "leading-tight": "1.3",
      "leading-normal": "1.65",
      "leading-relaxed": "1.8",
      "leading-loose": "2.1",
      "tracking-tighter": "-0.02em",
      "tracking-tight": "-0.01em",
      "tracking-normal": "0em",
      "tracking-wide": "0.02em",
      "tracking-wider": "0.04em",
      "heading-weight": "400",
      "heading-tracking": "0em",
      "heading-transform": "none",
      "heading-family": "'PP Writer', Georgia, serif",
    },
    spacing: {
      scale: [4, 8, 16, 24, 32, 40, 56, 72, 96, 120],
      unit: "px",
      "button-px": "24px",
      "button-py": "10px",
      "button-px-sm": "16px",
      "button-py-sm": "6px",
      "button-px-lg": "32px",
      "button-py-lg": "14px",
      "card-padding": "28px",
      "card-padding-sm": "18px",
      "card-padding-lg": "40px",
      "input-px": "12px",
      "input-py": "10px",
      "badge-px": "8px",
      "badge-py": "3px",
      "section-py": "72px",
      "section-py-lg": "120px",
      "navbar-height": "56px",
      "navbar-px": "28px",
      "footer-py": "56px",
      "modal-padding": "28px",
      "popover-padding": "16px",
      "tooltip-padding": "6px 12px",
      "table-cell-px": "16px",
      "table-cell-py": "12px",
    },
    layout: {
      "content-max": "1200px",
      "content-max-narrow": "720px",
      "content-max-wide": "1440px",
      "page-margin": "28px",
      "page-margin-sm": "18px",
      "page-margin-lg": "56px",
      gutter: "28px",
      "gutter-sm": "16px",
      "gutter-lg": "40px",
      "grid-columns": "12",
      "grid-gap": "24px",
      "bento-gap": "16px",
      "bento-radius": "0px",
      "bento-min-height": "180px",
      "section-gap": "40px",
      "sidebar-width": "280px",
      "sidebar-collapsed": "56px",
      "footer-columns": "3",
      "stack-gap": "18px",
      "stack-gap-sm": "10px",
      "stack-gap-lg": "28px",
      "prose-max": "75ch",
    },
    sigil: {
      "grid-cell": "48px",
      "cross-arm": "10px",
      "cross-stroke": "1px",
      "rail-gap": "24px",
      "card-radius": "0px",
    },
    radius: {
      none: "0px",
      sm: "0px",
      md: "0px",
      lg: "0px",
      xl: "0px",
      "2xl": "0px",
      full: "9999px",
      button: "0px",
      card: "0px",
      input: "0px",
      badge: "0px",
      modal: "0px",
      popover: "0px",
      tooltip: "0px",
      image: "0px",
      bento: "0px",
    },
    shadows: {
      sm: "none",
      md: "none",
      lg: "none",
      xl: "none",
      "2xl": "none",
      glow: "none",
      "glow-sm": "none",
      colored: "none",
      inner: "none",
      card: "none",
      button: "none",
      "button-hover": "none",
      dropdown: "0 4px 12px rgb(0 0 0 / 0.08)",
      modal: "0 16px 40px rgb(0 0 0 / 0.12)",
    },
    motion: {
      duration: { instant: "0ms", fast: "150ms", normal: "250ms", slow: "400ms", slower: "600ms", slowest: "1000ms" },
      easing: {
        default: "cubic-bezier(0.16, 1, 0.3, 1)",
        in: "cubic-bezier(0.55, 0, 1, 0.45)",
        out: "cubic-bezier(0, 0.55, 0.45, 1)",
        "in-out": "cubic-bezier(0.45, 0, 0.55, 1)",
        spring: "cubic-bezier(0.22, 1, 0.36, 1)",
        bounce: "cubic-bezier(0.68, -0.55, 0.27, 1.55)",
      },
      "enter-preset": "fadeIn",
      "exit-preset": "fadeOut",
      "hover-scale": "1",
      "press-scale": "0.99",
      "hover-lift": "0px",
      "stagger-interval": "50ms",
      "stagger-interval-fast": "25ms",
    },
    borders: {
      width: { none: "0px", thin: "1px", medium: "2px", thick: "3px" },
      style: "solid",
      "card-border": "0px solid",
      "card-border-hover": "0px solid",
      "button-border": "0px solid",
      "input-border": "1px solid",
      "divider-style": "solid",
      "divider-width": "1px",
    },
    buttons: {
      "font-weight": "500",
      "text-transform": "none",
      "letter-spacing": "0em",
      "font-family": "'PP Writer', Georgia, serif",
      "border-width": "0px",
      "hover-effect": "fill",
      "active-scale": "0.99",
      "icon-gap": "8px",
      "min-width": "0px",
    },
    cards: {
      "border-style": "none",
      "border-width": "0px",
      "hover-effect": "none",
      "hover-border-color": "transparent",
      padding: "28px",
      "header-padding": "28px 28px 0",
      "footer-padding": "0 28px 28px",
      "title-size": "1.1875rem",
      "title-weight": "700",
      "description-size": "0.875rem",
      outline: false,
      shadow: "none",
      background: "transparent",
    },
    headings: {
      "h1-size": "2.5rem",
      "h1-weight": "700",
      "h1-tracking": "-0.01em",
      "h1-leading": "1.2",
      "h2-size": "2rem",
      "h2-weight": "700",
      "h2-tracking": "-0.005em",
      "h3-size": "1.5rem",
      "h3-weight": "600",
      "h4-size": "1.25rem",
      "h4-weight": "600",
      "display-size": "3.75rem",
      "display-weight": "800",
      "display-tracking": "-0.02em",
      "display-leading": "1.1",
    },
    navigation: {
      "navbar-height": "56px",
      "navbar-backdrop-blur": "0px",
      "navbar-border": "1px solid",
      "navbar-bg-opacity": "0.95",
      "nav-link-weight": "500",
      "nav-link-size": "0.875rem",
      "nav-link-hover": "underline",
      "breadcrumb-separator": " / ",
      "pagination-radius": "0px",
      "sidebar-width": "280px",
      "sidebar-item-radius": "0px",
      "sidebar-item-padding": "8px 14px",
    },
    backgrounds: {
      pattern: "none",
      "pattern-opacity": "0",
      "pattern-scale": "1",
      noise: false,
      "noise-opacity": "0",
      "gradient-angle": "0deg",
      "gradient-type": "none",
      "hero-pattern": "none",
      "section-divider": "line",
    },
    code: {
      "font-family": "'PP Fraktion Mono', ui-monospace, monospace",
      "font-size": "0.875rem",
      "line-height": "1.7",
      bg: "#fef9c3",
      border: "0px solid transparent",
      "border-radius": "0px",
      padding: "16px",
      "tab-size": "4",
      "selection-bg": "#eab30840",
      "comment-color": "var(--s-text-muted)",
      "keyword-color": "#dc2626",
      "string-color": "#16a34a",
      "number-color": "#ea580c",
      "function-color": "#2563eb",
    },
    inputs: {
      height: "42px",
      "height-sm": "34px",
      "height-lg": "50px",
      "border-width": "1px",
      "focus-ring-width": "2px",
      "focus-ring-color": "#eab308",
      "focus-ring-offset": "2px",
      "placeholder-color": "var(--s-text-subtle)",
      "error-border-color": "#dc2626",
      "label-size": "0.875rem",
      "label-weight": "600",
      "label-spacing": "6px",
      "helper-size": "0.8125rem",
    },
    alignment: {
      "title-align": "left",
      "rail-margin": "48px",
    },
    sections: {
      "padding-y": "72px",
      gap: "36px",
      "max-width": "900px",
      indent: "24px",
    },
    dividers: {
      style: "solid",
      width: "2px",
      color: "var(--s-primary)",
      "show-label": true,
    },
    gridVisuals: {
      "show-lines": false,
    },
  },
};
