import type { SigilPreset } from "@sigil-ui/tokens";

export const noirPreset: SigilPreset = {
  name: "noir",
  metadata: {
    description:
      "Cinematic dark. Film noir atmosphere with dramatic shadows, warm amber highlights, and slow dramatic motion.",
    mood: "cinematic, noir, dramatic",
    tags: ["dark", "cinematic", "noir", "dramatic", "amber"],
  },
  tokens: {
    colors: {
      background: { light: "#fafaf9", dark: "#000000" },
      surface: { light: "#f5f5f4", dark: "#0a0a0a" },
      "surface-elevated": { light: "#ffffff", dark: "#141414" },
      "surface-sunken": { light: "#e7e5e4", dark: "#000000" },
      primary: "#d97706",
      "primary-hover": "#b45309",
      "primary-muted": "#d9770630",
      "primary-contrast": "#000000",
      secondary: "#78716c",
      "secondary-hover": "#57534e",
      "secondary-muted": "#78716c25",
      accent: "#ef4444",
      "accent-hover": "#dc2626",
      "accent-muted": "#ef444420",
      text: { light: "#1c1917", dark: "#e8e8e8" },
      "text-secondary": { light: "#44403c", dark: "#b8b8b8" },
      "text-muted": { light: "#78716c", dark: "#888888" },
      "text-subtle": { light: "#a8a29e", dark: "#606060" },
      "text-disabled": { light: "#d6d3d1", dark: "#404040" },
      "text-inverse": { light: "#e8e8e8", dark: "#1c1917" },
      border: { light: "#d6d3d1", dark: "#1a1a1a" },
      "border-muted": { light: "#e7e5e4", dark: "#111111" },
      "border-strong": { light: "#a8a29e", dark: "#2a2a2a" },
      "border-interactive": { light: "#d97706", dark: "#d97706" },
      success: "#34d399",
      "success-muted": "#34d39920",
      warning: "#fbbf24",
      "warning-muted": "#fbbf2420",
      error: "#f87171",
      "error-muted": "#f8717120",
      info: "#60a5fa",
      "info-muted": "#60a5fa20",
      "gradient-start": "#d97706",
      "gradient-end": "#78716c",
      glow: "#d9770650",
    },
    typography: {
      "font-display": "'PP Hatton', Georgia, serif",
      "font-body": "'PP Mori', system-ui, sans-serif",
      "font-mono": "'PP Fraktion Mono', ui-monospace, monospace",
      "size-xs": "0.75rem",
      "size-sm": "0.8125rem",
      "size-base": "0.9375rem",
      "size-lg": "1.0625rem",
      "size-xl": "1.1875rem",
      "size-2xl": "1.4375rem",
      "size-3xl": "1.75rem",
      "size-4xl": "2.25rem",
      "size-5xl": "3rem",
      "size-6xl": "4rem",
      "weight-normal": "400",
      "weight-medium": "500",
      "weight-semibold": "600",
      "weight-bold": "700",
      "weight-extrabold": "800",
      "leading-tight": "1.2",
      "leading-normal": "1.55",
      "leading-relaxed": "1.7",
      "leading-loose": "2",
      "tracking-tighter": "-0.04em",
      "tracking-tight": "-0.02em",
      "tracking-normal": "0em",
      "tracking-wide": "0.02em",
      "tracking-wider": "0.04em",
      "heading-weight": "200",
      "heading-tracking": "0.01em",
      "heading-transform": "none",
      "heading-family": "'PP Hatton', Georgia, serif",
    },
    spacing: {
      scale: [4, 8, 16, 24, 32, 48, 64, 80, 112, 144],
      unit: "px",
      "button-px": "28px",
      "button-py": "12px",
      "button-px-sm": "18px",
      "button-py-sm": "8px",
      "button-px-lg": "36px",
      "button-py-lg": "16px",
      "card-padding": "28px",
      "card-padding-sm": "18px",
      "card-padding-lg": "40px",
      "input-px": "14px",
      "input-py": "10px",
      "badge-px": "10px",
      "badge-py": "4px",
      "section-py": "80px",
      "section-py-lg": "144px",
      "navbar-height": "64px",
      "navbar-px": "32px",
      "footer-py": "64px",
      "modal-padding": "32px",
      "popover-padding": "18px",
      "tooltip-padding": "8px 14px",
      "table-cell-px": "18px",
      "table-cell-py": "12px",
    },
    layout: {
      "content-max": "1200px",
      "content-max-narrow": "720px",
      "content-max-wide": "1440px",
      "page-margin": "32px",
      "page-margin-sm": "18px",
      "page-margin-lg": "64px",
      gutter: "32px",
      "gutter-sm": "18px",
      "gutter-lg": "48px",
      "grid-columns": "12",
      "grid-gap": "32px",
      "bento-gap": "18px",
      "bento-radius": "16px",
      "bento-min-height": "220px",
      "section-gap": "48px",
      "sidebar-width": "280px",
      "sidebar-collapsed": "64px",
      "footer-columns": "4",
      "stack-gap": "18px",
      "stack-gap-sm": "10px",
      "stack-gap-lg": "32px",
      "prose-max": "65ch",
    },
    sigil: {
      "grid-cell": "56px",
      "cross-arm": "12px",
      "cross-stroke": "1px",
      "rail-gap": "28px",
      "card-radius": "16px",
    },
    radius: {
      none: "0px",
      sm: "4px",
      md: "8px",
      lg: "12px",
      xl: "16px",
      "2xl": "20px",
      full: "9999px",
      button: "12px",
      card: "16px",
      input: "8px",
      badge: "9999px",
      modal: "16px",
      popover: "12px",
      tooltip: "8px",
      image: "12px",
      bento: "16px",
    },
    shadows: {
      sm: "0 1px 4px rgb(0 0 0 / 0.4)",
      md: "0 2px 8px rgb(0 0 0 / 0.5)",
      lg: "0 4px 16px rgb(0 0 0 / 0.6)",
      xl: "0 8px 32px rgb(0 0 0 / 0.7)",
      "2xl": "0 24px 64px rgb(0 0 0 / 0.8)",
      glow: "0 0 40px #d9770644, 0 0 80px #d9770622",
      "glow-sm": "0 0 20px #d9770633",
      colored: "0 8px 32px -8px #d9770655",
      inner: "inset 0 2px 6px rgb(0 0 0 / 0.3)",
      card: "0 4px 24px rgb(0 0 0 / 0.5)",
      button: "none",
      "button-hover": "0 0 24px #d9770644",
      dropdown: "0 8px 32px rgb(0 0 0 / 0.6)",
      modal: "0 32px 80px rgb(0 0 0 / 0.7)",
    },
    motion: {
      duration: { instant: "0ms", fast: "200ms", normal: "400ms", slow: "600ms", slower: "900ms", slowest: "1500ms" },
      easing: {
        default: "cubic-bezier(0.16, 1, 0.3, 1)",
        in: "cubic-bezier(0.55, 0, 1, 0.45)",
        out: "cubic-bezier(0, 0.55, 0.45, 1)",
        "in-out": "cubic-bezier(0.45, 0, 0.55, 1)",
        spring: "cubic-bezier(0.34, 1.56, 0.64, 1)",
        bounce: "cubic-bezier(0.68, -0.55, 0.27, 1.55)",
      },
      "enter-preset": "fadeUp",
      "exit-preset": "fadeOut",
      "hover-scale": "1.02",
      "press-scale": "0.97",
      "hover-lift": "-4px",
      "stagger-interval": "80ms",
      "stagger-interval-fast": "40ms",
    },
    borders: {
      width: { none: "0px", thin: "1px", medium: "1.5px", thick: "2px" },
      style: "solid",
      "card-border": "0px solid",
      "card-border-hover": "0px solid",
      "button-border": "0px solid",
      "input-border": "1px solid",
      "divider-style": "solid",
      "divider-width": "1px",
    },
    buttons: {
      "font-weight": "600",
      "text-transform": "none",
      "letter-spacing": "0.01em",
      "font-family": "'PP Mori', system-ui, sans-serif",
      "border-width": "0px",
      "hover-effect": "glow",
      "active-scale": "0.97",
      "icon-gap": "10px",
      "min-width": "0px",
    },
    cards: {
      "border-style": "none",
      "border-width": "0px",
      "hover-effect": "lift",
      "hover-border-color": "transparent",
      padding: "28px",
      "header-padding": "28px 28px 0",
      "footer-padding": "0 28px 28px",
      "title-size": "1.125rem",
      "title-weight": "600",
      "description-size": "0.8125rem",
      outline: false,
      shadow: "2xl",
      background: "surface",
    },
    headings: {
      "h1-size": "2.5rem",
      "h1-weight": "700",
      "h1-tracking": "-0.03em",
      "h1-leading": "1.15",
      "h2-size": "1.875rem",
      "h2-weight": "600",
      "h2-tracking": "-0.02em",
      "h3-size": "1.5rem",
      "h3-weight": "600",
      "h4-size": "1.1875rem",
      "h4-weight": "600",
      "display-size": "4.5rem",
      "display-weight": "800",
      "display-tracking": "-0.04em",
      "display-leading": "1.05",
    },
    navigation: {
      "navbar-height": "64px",
      "navbar-backdrop-blur": "20px",
      "navbar-border": "0px solid",
      "navbar-bg-opacity": "0.7",
      "nav-link-weight": "500",
      "nav-link-size": "0.8125rem",
      "nav-link-hover": "color",
      "breadcrumb-separator": " / ",
      "pagination-radius": "12px",
      "sidebar-width": "280px",
      "sidebar-item-radius": "10px",
      "sidebar-item-padding": "10px 14px",
    },
    backgrounds: {
      pattern: "none",
      "pattern-opacity": "0",
      "pattern-scale": "1",
      noise: true,
      "noise-opacity": "0.03",
      "gradient-angle": "180deg",
      "gradient-type": "radial",
      "hero-pattern": "radial-glow",
      "section-divider": "none",
    },
    code: {
      "font-family": "'PP Fraktion Mono', ui-monospace, monospace",
      "font-size": "0.8125rem",
      "line-height": "1.7",
      bg: "var(--s-surface-sunken)",
      border: "0px solid transparent",
      "border-radius": "12px",
      padding: "18px",
      "tab-size": "2",
      "selection-bg": "#d9770630",
      "comment-color": "var(--s-text-muted)",
      "keyword-color": "#d97706",
      "string-color": "#34d399",
      "number-color": "#fbbf24",
      "function-color": "#60a5fa",
    },
    inputs: {
      height: "42px",
      "height-sm": "34px",
      "height-lg": "50px",
      "border-width": "1px",
      "focus-ring-width": "2px",
      "focus-ring-color": "#d97706",
      "focus-ring-offset": "2px",
      "placeholder-color": "var(--s-text-subtle)",
      "error-border-color": "var(--s-error)",
      "label-size": "0.8125rem",
      "label-weight": "500",
      "label-spacing": "8px",
      "helper-size": "0.75rem",
    },
    alignment: {
      "title-align": "center",
      "rail-margin": "56px",
    },
    sections: {
      "padding-y": "96px",
      "padding-y-hero": "200px",
      gap: "56px",
      "max-width": "1080px",
    },
    dividers: {
      style: "none",
    },
    gridVisuals: {
      "show-lines": false,
      "show-dots": false,
    },
  },
};
