import type { SigilPreset } from "@sigil-ui/tokens";

export const noirPreset: SigilPreset = {
  name: "noir",
  metadata: {
    description:
      "Cinematic dark. Film noir atmosphere with dramatic shadows, warm amber highlights, and slow dramatic motion.",
    mood: "cinematic, noir, dramatic",
    tags: ["dark", "cinematic", "noir", "dramatic", "amber"],
  },
  tokens: {
    colors: {
      background: { light: "#fafaf9", dark: "#000000" },
      surface: { light: "#f5f5f4", dark: "#0a0a0a" },
      "surface-elevated": { light: "#ffffff", dark: "#141414" },
      "surface-sunken": { light: "#e7e5e4", dark: "#000000" },
      primary: "#d97706",
      "primary-hover": "#b45309",
      "primary-muted": "#d9770630",
      "primary-contrast": "#000000",
      secondary: "#78716c",
      "secondary-hover": "#57534e",
      "secondary-muted": "#78716c25",
      accent: "#ef4444",
      "accent-hover": "#dc2626",
      "accent-muted": "#ef444420",
      text: { light: "#1c1917", dark: "#e8e8e8" },
      "text-secondary": { light: "#44403c", dark: "#b8b8b8" },
      "text-muted": { light: "#78716c", dark: "#959595" },
      "text-subtle": { light: "#948e8a", dark: "#707070" },
      "text-disabled": { light: "#d6d3d1", dark: "#404040" },
      "text-inverse": { light: "#e8e8e8", dark: "#1c1917" },
      border: { light: "#918e8d", dark: "oklch(0.220 0.006 0)" },
      "border-muted": { light: "#c0bebd", dark: "oklch(0.160 0.006 0)" },
      "border-strong": { light: "#948e8a", dark: "oklch(0.300 0.006 0)" },
      "border-interactive": { light: "#d97706", dark: "#d97706" },
      success: "#00a36d",
      "success-muted": "#34d39920",
      warning: "#be8400",
      "warning-muted": "#fbbf2420",
      error: "#e96465",
      "error-muted": "#f8717120",
      info: "#4c91e4",
      "info-muted": "#60a5fa20",
      "gradient-start": "#d97706",
      "gradient-end": "#78716c",
      glow: "#d9770650",
      highlight: { light: "#fef3c7", dark: "rgba(217, 119, 6, 0.15)" },
    },
    typography: {
      "font-display": "'PP Hatton', Georgia, serif",
      "font-body": "'PP Mori', system-ui, sans-serif",
      "font-mono": "'PP Fraktion Mono', ui-monospace, monospace",
      "size-xs": "0.75rem",
      "size-sm": "0.8125rem",
      "size-base": "0.9375rem",
      "size-lg": "1.0625rem",
      "size-xl": "1.1875rem",
      "size-2xl": "1.4375rem",
      "size-3xl": "1.75rem",
      "size-4xl": "2.25rem",
      "size-5xl": "3rem",
      "size-6xl": "4rem",
      "weight-normal": "400",
      "weight-medium": "500",
      "weight-semibold": "600",
      "weight-bold": "700",
      "weight-extrabold": "800",
      "leading-tight": "1.2",
      "leading-normal": "1.55",
      "leading-relaxed": "1.7",
      "leading-loose": "2",
      "tracking-tighter": "-0.04em",
      "tracking-tight": "-0.02em",
      "tracking-normal": "0em",
      "tracking-wide": "0.02em",
      "tracking-wider": "0.04em",
      "heading-weight": "200",
      "heading-tracking": "0.01em",
      "heading-transform": "none",
      "heading-family": "'PP Hatton', Georgia, serif",
    },
    spacing: {
      scale: [4, 8, 16, 24, 32, 48, 64, 80, 112, 144],
      unit: "px",
      "button-px": "28px",
      "button-py": "12px",
      "button-px-sm": "18px",
      "button-py-sm": "8px",
      "button-px-lg": "36px",
      "button-py-lg": "16px",
      "card-padding": "36px",
      "card-padding-sm": "24px",
      "card-padding-lg": "48px",
      "input-px": "14px",
      "input-py": "10px",
      "badge-px": "10px",
      "badge-py": "4px",
      "section-py": "8rem",
      "section-py-lg": "12rem",
      "navbar-height": "64px",
      "navbar-px": "40px",
      "footer-py": "64px",
      "modal-padding": "32px",
      "popover-padding": "18px",
      "tooltip-padding": "8px 14px",
      "table-cell-px": "18px",
      "table-cell-py": "12px",
    },
    layout: {
      "content-max": "1200px",
      "content-max-narrow": "720px",
      "content-max-wide": "1440px",
      "page-margin": "40px",
      "page-margin-sm": "18px",
      "page-margin-lg": "80px",
      gutter: "44px",
      "gutter-sm": "18px",
      "gutter-lg": "60px",
      "grid-columns": "12",
      "grid-gap": "40px",
      "bento-gap": "24px",
      "bento-radius": "16px",
      "bento-min-height": "256px",
      "section-gap": "64px",
      "sidebar-width": "300px",
      "sidebar-collapsed": "64px",
      "footer-columns": "4",
      "stack-gap": "18px",
      "stack-gap-sm": "10px",
      "stack-gap-lg": "32px",
      "prose-max": "65ch",
    },
    sigil: {
      "grid-cell": "64px",
      "cross-arm": "14px",
      "cross-stroke": "0.75px",
      "rail-gap": "36px",
      "card-radius": "20px",
      "gutter-pattern": "horizontal",
      "margin-pattern": "wave",
      "band-height": "64px",
      "divider-thickness-sm": "33px",
      "divider-thickness-md": "65px",
      "divider-thickness-lg": "129px",
      "divider-thickness-xl": "193px",
    },
    radius: {
      none: "0px",
      sm: "4px",
      md: "8px",
      lg: "12px",
      xl: "16px",
      "2xl": "20px",
      full: "9999px",
      button: "12px",
      card: "16px",
      input: "8px",
      badge: "9999px",
      modal: "16px",
      popover: "12px",
      tooltip: "8px",
      image: "12px",
      bento: "16px",
    },
    shadows: {
      sm: "0 1px 4px rgb(0 0 0 / 0.4)",
      md: "0 2px 8px rgb(0 0 0 / 0.5)",
      lg: "0 4px 16px rgb(0 0 0 / 0.6)",
      xl: "0 8px 32px rgb(0 0 0 / 0.7)",
      "2xl": "0 24px 64px rgb(0 0 0 / 0.8)",
      glow: "0 0 40px #d9770644, 0 0 80px #d9770622",
      "glow-sm": "0 0 20px #d9770633",
      colored: "0 8px 32px -8px #d9770655",
      inner: "inset 0 2px 6px rgb(0 0 0 / 0.3)",
      card: "0 4px 24px rgb(0 0 0 / 0.5)",
      button: "none",
      "button-hover": "0 0 24px #d9770644",
      dropdown: "0 8px 32px rgb(0 0 0 / 0.6)",
      modal: "0 32px 80px rgb(0 0 0 / 0.7)",
    },
    motion: {
      duration: { instant: "0ms", fast: "200ms", normal: "400ms", slow: "600ms", slower: "900ms", slowest: "1500ms" },
      easing: {
        default: "cubic-bezier(0.16, 1, 0.3, 1)",
        in: "cubic-bezier(0.55, 0, 1, 0.45)",
        out: "cubic-bezier(0, 0.55, 0.45, 1)",
        "in-out": "cubic-bezier(0.45, 0, 0.55, 1)",
        spring: "cubic-bezier(0.34, 1.56, 0.64, 1)",
        bounce: "cubic-bezier(0.68, -0.55, 0.27, 1.55)",
      },
      "enter-preset": "fadeUp",
      "exit-preset": "fadeOut",
      "hover-scale": "1.02",
      "press-scale": "0.97",
      "hover-lift": "-4px",
      "stagger-interval": "80ms",
      "stagger-interval-fast": "40ms",
    },
    borders: {
      width: { none: "0px", thin: "1px", medium: "1.5px", thick: "2px" },
      style: "solid",
      "card-border": "0px solid",
      "card-border-hover": "0px solid",
      "button-border": "0px solid",
      "input-border": "1px solid",
      "divider-style": "solid",
      "divider-width": "1px",
    },
    buttons: {
      "font-weight": "600",
      "text-transform": "none",
      "letter-spacing": "0.01em",
      "font-family": "'PP Mori', system-ui, sans-serif",
      "border-width": "0px",
      "hover-effect": "glow",
      "active-scale": "0.97",
      "icon-gap": "10px",
      "min-width": "0px",
    },
    cards: {
      "border-style": "none",
      "border-width": "0px",
      "hover-effect": "lift",
      "hover-border-color": "transparent",
      padding: "28px",
      "header-padding": "28px 28px 0",
      "footer-padding": "0 28px 28px",
      "title-size": "1.125rem",
      "title-weight": "600",
      "description-size": "0.8125rem",
      outline: false,
      shadow: "2xl",
      background: "surface",
    },
    headings: {
      "h1-size": "2.5rem",
      "h1-weight": "700",
      "h1-tracking": "-0.03em",
      "h1-leading": "1.15",
      "h2-size": "1.875rem",
      "h2-weight": "600",
      "h2-tracking": "-0.02em",
      "h2-leading": "1.15",
      "h3-size": "1.5rem",
      "h3-weight": "600",
      "h3-tracking": "0em",
      "h3-leading": "1.2",
      "h4-size": "1.1875rem",
      "h4-weight": "600",
      "h4-tracking": "0em",
      "h4-leading": "1.3",
      "display-size": "4.5rem",
      "display-weight": "800",
      "display-tracking": "-0.04em",
      "display-leading": "1.05",
    },
    navigation: {
      "navbar-height": "64px",
      "navbar-backdrop-blur": "24px",
      "navbar-border": "none",
      "navbar-bg-opacity": "0.6",
      "navbar-padding-x": "24px",
      "navbar-position": "sticky",
      "navbar-logo-height": "24px",
      "navbar-logo-gap": "10px",
      "navbar-item-gap": "24px",
      "navbar-item-padding-x": "12px",
      "navbar-item-padding-y": "6px",
      "navbar-item-size": "0.875rem",
      "navbar-shadow": "0 1px 3px rgb(0 0 0 / 0.3)",
      "navbar-height-scrolled": "48px",
      "navbar-mobile-breakpoint": "768px",
      "nav-link-weight": "400",
      "nav-link-size": "0.8125rem",
      "nav-link-hover": "color",
      "breadcrumb-separator": " / ",
      "pagination-radius": "12px",
      "sidebar-width": "300px",
      "sidebar-item-radius": "12px",
      "sidebar-item-padding": "12px 18px",
    },
    backgrounds: {
      pattern: "none",
      "pattern-opacity": "0",
      "pattern-scale": "1",
      noise: true,
      "noise-opacity": "0.03",
      "gradient-angle": "180deg",
      "gradient-type": "radial",
      "hero-pattern": "radial-glow",
      "section-divider": "none",
    },
    code: {
      "font-family": "'PP Fraktion Mono', ui-monospace, monospace",
      "font-size": "0.8125rem",
      "line-height": "1.7",
      bg: "var(--s-surface-sunken)",
      border: "0px solid transparent",
      "border-radius": "12px",
      padding: "18px",
      "tab-size": "2",
      "selection-bg": "#d9770630",
      "comment-color": "var(--s-text-muted)",
      "keyword-color": "#d97706",
      "string-color": "#34d399",
      "number-color": "#fbbf24",
      "function-color": "#60a5fa",
    },
    inputs: {
      height: "42px",
      "height-sm": "34px",
      "height-lg": "50px",
      "border-width": "1px",
      "focus-ring-width": "2px",
      "focus-ring-color": "#d97706",
      "focus-ring-offset": "2px",
      "placeholder-color": "var(--s-text-subtle)",
      "error-border-color": "var(--s-error)",
      "label-size": "0.8125rem",
      "label-weight": "500",
      "label-spacing": "8px",
      "helper-size": "0.75rem",
    },
    alignment: {
      "title-align": "center",
      "rail-margin": "56px",
    },
    sections: {
      "padding-y": "8rem",
      "padding-y-hero": "12rem",
      "padding-y-sm": "4rem",
      gap: "56px",
      "padding-y-lg": "12rem",
      "padding-y-xl": "16rem",
      "max-width": "1080px",
      "heading-size": "clamp(1.5rem, 4vw, 2.5rem)",
      "heading-align": "center",
      "heading-max-width": "40rem",
      "heading-margin-bottom": "16px",
      "description-max-width": "32rem",
      "description-gap": "14px",
      "content-gap": "24px",
      "grid-columns": "3",
      "grid-gap": "24px",
      "alternate-bg": "var(--s-surface-sunken)",
      "alternate-bg-mode": "sunken",
    },
    dividers: {
      style: "none",
      spacing: "0px",
      opacity: "0.5",
      "max-width": "100%",
      "margin-y": "0px",
      thickness: "1px",
      "gradient-start": "transparent",
      "gradient-end": "transparent",
    },
    gridVisuals: {
      "line-color": "var(--s-border-muted)",
      "line-width": "1px",
      "show-lines": false,
      "show-dots": false,
    },
    cursor: {
      variant: "ring",
      size: "24px",
      "dot-size": "4px",
      "stroke-width": "1.5px",
      "tick-size": "6px",
      gap: "3px",
      radius: "0px",
      color: "var(--s-text)",
      "ring-color": "var(--s-primary)",
      "dot-color": "var(--s-primary)",
      glow: "0 0 8px var(--s-primary)",
      opacity: "1",
      "blend-mode": "normal",
      "z-index": "9999",
      "hide-native": false,
    },
    scrollbar: {
      width: "8px",
      height: "8px",
      padding: "2px",
      radius: "9999px",
      track: "transparent",
      thumb: "var(--s-border-muted)",
      "thumb-hover": "var(--s-border)",
      "thumb-active": "var(--s-border-strong)",
      corner: "transparent",
      border: "none",
      "firefox-width": "thin",
      gutter: "stable",
      visibility: "auto",
    },
    focus: {
      "ring-width": "2px",
      "ring-color": "var(--s-primary)",
      "ring-offset": "0px",
      "ring-shadow": "0 0 0 2px var(--s-primary)",
      "outline-color": "var(--s-primary)",
    },
    overlays: {
      bg: "rgb(0 0 0 / 0.7)",
      blur: "12px",
      surface: "var(--s-surface-elevated)",
      border: "1px solid var(--s-border-muted)",
      shadow: "var(--s-shadow-xl)",
      radius: "var(--s-radius-lg)",
      padding: "20px",
      "z-index": "50",
    },
    dataViz: {
      "series-1": "var(--s-primary)",
      "series-2": "var(--s-secondary)",
      "series-3": "var(--s-accent)",
      "series-4": "var(--s-info)",
      "series-5": "var(--s-success)",
      positive: "var(--s-success)",
      negative: "var(--s-error)",
      neutral: "var(--s-text-muted)",
      grid: "var(--s-border-muted)",
      axis: "var(--s-border)",
      label: "var(--s-text-secondary)",
      "tooltip-bg": "var(--s-surface-elevated)",
      "tooltip-border": "var(--s-border-muted)",
    },
    media: {
      radius: "var(--s-radius-md)",
      border: "none",
      outline: "1px solid rgb(0 0 0 / 0.08)",
      shadow: "none",
      bg: "var(--s-surface-sunken)",
      "object-fit": "cover",
    },
    controls: {
      height: "38px",
      "height-sm": "30px",
      "height-lg": "46px",
      "hit-area": "44px",
      "icon-size": "16px",
      "handle-size": "20px",
      "track-height": "4px",
      "track-bg": "var(--s-border-muted)",
      "track-fill": "var(--s-primary)",
      "thumb-bg": "var(--s-surface-elevated)",
      "thumb-border": "2px solid var(--s-primary)",
    },
    componentSurfaces: {
      bg: "var(--s-surface)",
      "bg-elevated": "var(--s-surface-elevated)",
      "bg-muted": "var(--s-surface-sunken)",
      border: "var(--s-border)",
      "border-muted": "var(--s-border-muted)",
      "border-strong": "var(--s-border-strong)",
      text: "var(--s-text)",
      "text-muted": "var(--s-text-muted)",
      contrast: "var(--s-primary-contrast)",
      "hover-bg": "var(--s-surface-elevated)",
      "active-bg": "var(--s-surface-sunken)",
      "selected-bg": "var(--s-primary-muted)",
    },
    hero: {
      "min-height": "auto",
      "padding-y": "128px",
      "padding-y-sm": "128px",
      "padding-x": "var(--s-page-margin, 24px)",
      "content-max": "640px",
      "content-align": "center",
      layout: "centered",
      "media-position": "below",
      "media-width": "50%",
      "media-radius": "var(--s-radius-lg)",
      "title-size": "clamp(2.5rem, 6vw, 4.5rem)",
      "title-max-width": "56rem",
      "description-size": "1.125rem",
      "description-max-width": "32rem",
      "description-gap": "24px",
      "actions-gap": "12px",
      "actions-margin-top": "36px",
      "action-padding-x": "24px",
      "action-padding-y": "12px",
      "badge-gap": "24px",
      "overlay-opacity": "0.7",
      "scroll-indicator": false,
      "gradient-overlay": "linear-gradient(to bottom, transparent, var(--s-background))",
    },
    cta: {
      "padding-y": "128px",
      "padding-x": "var(--s-page-margin, 24px)",
      "max-width": "var(--s-content-max, 1200px)",
      layout: "centered",
      border: false,
      "border-radius": "var(--s-radius-lg)",
      bg: "var(--s-surface-elevated)",
      "title-size": "clamp(1.5rem, 4vw, 2.5rem)",
      "description-max-width": "32rem",
      "description-gap": "14px",
      "actions-gap": "12px",
      "actions-margin-top": "36px",
      "action-padding-x": "24px",
      "action-padding-y": "12px",
      "split-gap": "64px",
    },
    footer: {
      "padding-y": "64px",
      "border-top": "1px solid var(--s-border)",
      columns: "4",
      "column-gap": "32px",
      "row-gap": "32px",
      "logo-height": "24px",
      "tagline-max-width": "20rem",
      "link-size": "0.875rem",
      "link-gap": "8px",
      "group-title-size": "0.8125rem",
      "group-title-weight": "600",
      "social-icon-size": "20px",
      "social-gap": "12px",
      "bottom-bar-padding": "0px 0",
      "bottom-bar-border": "1px solid var(--s-border-muted)",
    },
    banner: {
      height: "auto",
      "padding-y": "8px",
      "padding-x": "16px",
      "font-size": "0.875rem",
      "font-weight": "500",
      "icon-size": "16px",
      "icon-gap": "12px",
      "border-width": "1px",
      "border-position": "bottom",
      position: "top",
      "dismiss-size": "16px",
      radius: "0px",
    },
    pageRhythm: {
      density: "spacious",
      "section-gap": "0px",
      "section-gap-sm": "0px",
      "section-gap-lg": "0px",
      "first-section-offset": "0px",
      "last-section-margin": "0px",
      "alternate-bg": true,
      "alternate-bg-color": "var(--s-surface-sunken)",
      "divider-between": false,
      "max-content-width": "var(--s-content-max, 1200px)",
      "vertical-rhythm-unit": "8px",
      "scroll-snap": false,
      "responsive-scale": "0.9",
      "responsive-breakpoint": "768px",
    },

  },
};
