import type { SigilPreset } from "@sigil-ui/tokens";

export const obsidPreset: SigilPreset = {
  name: "obsid",
  metadata: {
    description: "Obsidian mirror — volcanic glass, reflective dark surfaces, razor-sharp edges.",
    mood: "obsidian, reflective, volcanic glass",
    tags: ["dark", "obsidian", "reflective", "razor", "glass"],
    author: "sigil-ui",
    version: "0.1.0",
  },
  tokens: {
    colors: {
      background: { light: "oklch(0.96 0.005 300)", dark: "oklch(0.05 0.005 300)" },
      surface: { light: "oklch(0.94 0.008 300)", dark: "oklch(0.1 0.008 300)" },
      "surface-elevated": { light: "oklch(0.97 0.004 300)", dark: "oklch(0.14 0.01 300)" },
      "surface-sunken": { light: "oklch(0.92 0.01 300)", dark: "oklch(0.03 0.005 300)" },
      primary: "oklch(0.55 0.2 350)",
      "primary-hover": "oklch(0.5 0.22 350)",
      "primary-muted": "oklch(0.55 0.08 350)",
      "primary-contrast": "oklch(0.98 0 0)",
      secondary: "oklch(0.6 0.14 280)",
      "secondary-hover": "oklch(0.55 0.16 280)",
      "secondary-muted": "oklch(0.6 0.06 280)",
      accent: "oklch(0.7 0.12 310)",
      "accent-hover": "oklch(0.65 0.14 310)",
      "accent-muted": "oklch(0.7 0.05 310)",
      text: { light: "oklch(0.15 0.005 300)", dark: "oklch(0.85 0.008 280)" },
      "text-secondary": { light: "oklch(0.35 0.005 300)", dark: "oklch(0.7 0.006 280)" },
      "text-muted": { light: "oklch(0.5 0.004 300)", dark: "oklch(0.63 0.005 280)" },
      "text-subtle": { light: "oklch(0.62 0.003 300)", dark: "oklch(0.50 0.004 280)" },
      "text-disabled": { light: "oklch(0.72 0.003 300)", dark: "oklch(0.3 0.003 280)" },
      "text-inverse": { light: "oklch(0.95 0.004 280)", dark: "oklch(0.1 0.005 300)" },
      border: { light: "oklch(0.63 0.006 300)", dark: "oklch(0.230 0.010 300)" },
      "border-muted": { light: "oklch(0.80 0.006 300)", dark: "oklch(0.170 0.008 300)" },
      "border-strong": { light: "oklch(0.63 0.008 300)", dark: "oklch(0.310 0.012 300)" },
      "border-interactive": { light: "oklch(0.55 0.2 350)", dark: "oklch(0.55 0.2 350)" },
      success: "oklch(0.6 0.18 155)",
      "success-muted": "oklch(0.7 0.06 155)",
      warning: "oklch(0.63 0.15 80)",
      "warning-muted": "oklch(0.78 0.05 80)",
      error: "oklch(0.6 0.22 25)",
      "error-muted": "oklch(0.6 0.08 25)",
      info: "oklch(0.63 0.15 250)",
      "info-muted": "oklch(0.65 0.06 250)",
      "gradient-start": "oklch(0.55 0.2 350)",
      "gradient-end": "oklch(0.6 0.14 280)",
      glow: "oklch(0.55 0.2 350 / 0.5)",
      highlight: { light: "oklch(0.92 0.08 350)", dark: "oklch(0.28 0.06 350)" },
    },
    typography: {
      "font-display": "'PP Stellar', system-ui, sans-serif",
      "font-body": "'PP Stellar', system-ui, sans-serif",
      "font-mono": "'PP Fraktion Mono', ui-monospace, monospace",
      "size-xs": "0.75rem",
      "size-sm": "0.8125rem",
      "size-base": "0.875rem",
      "size-lg": "1rem",
      "size-xl": "1.125rem",
      "size-2xl": "1.375rem",
      "size-3xl": "1.625rem",
      "size-4xl": "2rem",
      "size-5xl": "2.625rem",
      "size-6xl": "3.25rem",
      "weight-normal": "400",
      "weight-medium": "500",
      "weight-semibold": "600",
      "weight-bold": "700",
      "weight-extrabold": "800",
      "leading-tight": "1.2",
      "leading-normal": "1.5",
      "leading-relaxed": "1.625",
      "leading-loose": "1.9",
      "tracking-tighter": "-0.04em",
      "tracking-tight": "-0.02em",
      "tracking-normal": "0em",
      "tracking-wide": "0.02em",
      "tracking-wider": "0.04em",
      "heading-weight": "400",
      "heading-tracking": "0.02em",
      "heading-transform": "none",
      "heading-family": "'PP Stellar', system-ui, sans-serif",
    },
    spacing: {
      scale: [2, 4, 8, 12, 16, 20, 28, 40, 56, 72],
      unit: "px",
      "button-px": "18px",
      "button-py": "9px",
      "button-px-sm": "12px",
      "button-py-sm": "6px",
      "button-px-lg": "24px",
      "button-py-lg": "12px",
      "card-padding": "20px",
      "card-padding-sm": "14px",
      "card-padding-lg": "28px",
      "input-px": "10px",
      "input-py": "7px",
      "badge-px": "7px",
      "badge-py": "2px",
      "section-py": "5rem",
      "section-py-lg": "7.5rem",
      "navbar-height": "40px",
      "navbar-px": "20px",
      "footer-py": "40px",
      "modal-padding": "20px",
      "popover-padding": "12px",
      "tooltip-padding": "5px 10px",
      "table-cell-px": "12px",
      "table-cell-py": "9px",
    },
    layout: {
      "content-max": "1200px",
      "content-max-narrow": "720px",
      "content-max-wide": "1440px",
      "page-margin": "24px",
      "page-margin-sm": "12px",
      "page-margin-lg": "48px",
      gutter: "20px",
      "gutter-sm": "10px",
      "gutter-lg": "28px",
      "grid-columns": "12",
      "grid-gap": "20px",
      "bento-gap": "14px",
      "bento-radius": "4px",
      "bento-min-height": "160px",
      "section-gap": "20px",
      "sidebar-width": "248px",
      "sidebar-collapsed": "48px",
      "footer-columns": "4",
      "stack-gap": "12px",
      "stack-gap-sm": "6px",
      "stack-gap-lg": "20px",
      "prose-max": "62ch",
    },
    sigil: {
      "grid-cell": "40px",
      "cross-arm": "8px",
      "cross-stroke": "0.75px",
      "rail-gap": "20px",
      "card-radius": "4px",
      "gutter-pattern": "hexagon",
      "margin-pattern": "diagonal",
    },
    radius: {
      none: "0px",
      sm: "2px",
      md: "3px",
      lg: "4px",
      xl: "6px",
      "2xl": "8px",
      full: "9999px",
      button: "3px",
      card: "4px",
      input: "3px",
      badge: "2px",
      modal: "6px",
      popover: "4px",
      tooltip: "3px",
      image: "3px",
      bento: "4px",
    },
    shadows: {
      sm: "0 1px 3px 0 rgb(100 0 40 / 0.08)",
      md: "0 2px 8px -2px rgb(100 0 40 / 0.12), 0 0 0 1px rgb(0 0 0 / 0.06)",
      lg: "0 4px 16px -4px rgb(100 0 40 / 0.16), 0 0 0 1px rgb(0 0 0 / 0.05)",
      xl: "0 8px 30px -6px rgb(100 0 40 / 0.2), 0 0 0 1px rgb(0 0 0 / 0.04)",
      "2xl": "0 20px 50px -12px rgb(100 0 40 / 0.3)",
      glow: "0 0 30px var(--s-primary)",
      "glow-sm": "0 0 14px var(--s-primary)",
      colored: "0 4px 20px -4px var(--s-primary)",
      inner: "inset 0 2px 4px 0 rgb(0 0 0 / 0.15)",
      card: "0 4px 20px -4px var(--s-primary)",
      button: "0 2px 10px -2px var(--s-primary)",
      "button-hover": "0 4px 18px -3px var(--s-primary)",
      dropdown: "0 8px 24px rgb(0 0 0 / 0.3), 0 0 0 1px rgb(255 255 255 / 0.05)",
      modal: "0 20px 60px -12px rgb(0 0 0 / 0.5), 0 0 40px -8px var(--s-primary)",
    },
    motion: {
      duration: { instant: "0ms", fast: "120ms", normal: "200ms", slow: "350ms", slower: "500ms", slowest: "800ms" },
      easing: {
        default: "cubic-bezier(0.16, 1, 0.3, 1)",
        in: "cubic-bezier(0.55, 0, 1, 0.45)",
        out: "cubic-bezier(0, 0.55, 0.45, 1)",
        "in-out": "cubic-bezier(0.45, 0, 0.55, 1)",
        spring: "cubic-bezier(0.34, 1.56, 0.64, 1)",
        bounce: "cubic-bezier(0.68, -0.55, 0.27, 1.55)",
      },
      "enter-preset": "fadeUp",
      "exit-preset": "fadeOut",
      "hover-scale": "1.03",
      "press-scale": "0.96",
      "hover-lift": "-4px",
      "stagger-interval": "40ms",
      "stagger-interval-fast": "20ms",
    },
    borders: {
      width: { none: "0px", thin: "1px", medium: "1.5px", thick: "2px" },
      style: "solid",
      "card-border": "none",
      "card-border-hover": "none",
      "button-border": "none",
      "input-border": "1px solid",
      "divider-style": "solid",
      "divider-width": "1px",
    },
    buttons: {
      "font-weight": "600",
      "text-transform": "none",
      "letter-spacing": "0.01em",
      "font-family": "'PP Stellar', system-ui, sans-serif",
      "border-width": "0px",
      "hover-effect": "fill",
      "active-scale": "0.96",
      "icon-gap": "8px",
      "min-width": "0px",
    },
    cards: {
      "border-style": "none",
      "border-width": "0px",
      "hover-effect": "glow",
      "hover-border-color": "transparent",
      padding: "20px",
      "header-padding": "20px 20px 0",
      "footer-padding": "0 20px 20px",
      "title-size": "1rem",
      "title-weight": "600",
      "description-size": "0.8125rem",
      background: "elevated",
      shadow: "lg",
      outline: false,
      "outline-on-hover-only": true,
      "gap-between": "16px",
      "content-padding-x": "20px",
      "content-padding-y": "18px",
    },
    headings: {
      "h1-size": "2rem",
      "h1-weight": "600",
      "h1-tracking": "-0.03em",
      "h1-leading": "1.15",
      "h2-size": "1.625rem",
      "h2-weight": "600",
      "h2-tracking": "-0.025em",
      "h2-leading": "1.15",
      "h3-size": "1.375rem",
      "h3-weight": "600",
      "h3-tracking": "0em",
      "h3-leading": "1.2",
      "h4-size": "1.125rem",
      "h4-weight": "600",
      "h4-tracking": "0em",
      "h4-leading": "1.3",
      "display-size": "3.25rem",
      "display-weight": "700",
      "display-tracking": "-0.04em",
      "display-leading": "1.05",
    },
    navigation: {
      "navbar-height": "40px",
      "navbar-backdrop-blur": "24px",
      "navbar-border": "none",
      "navbar-bg-opacity": "0.5",
      "navbar-padding-x": "24px",
      "navbar-position": "sticky",
      "navbar-logo-height": "24px",
      "navbar-logo-gap": "10px",
      "navbar-item-gap": "24px",
      "navbar-item-padding-x": "12px",
      "navbar-item-padding-y": "6px",
      "navbar-item-size": "0.875rem",
      "navbar-shadow": "0 1px 3px rgb(0 0 0 / 0.3)",
      "navbar-height-scrolled": "48px",
      "navbar-mobile-breakpoint": "768px",
      "nav-link-weight": "500",
      "nav-link-size": "0.8125rem",
      "nav-link-hover": "color",
      "breadcrumb-separator": "›",
      "pagination-radius": "3px",
      "sidebar-width": "248px",
      "sidebar-item-radius": "4px",
      "sidebar-item-padding": "7px 12px",
    },
    backgrounds: {
      pattern: "none",
      "pattern-opacity": "0",
      "pattern-scale": "1",
      noise: true,
      "noise-opacity": "0.025",
      "gradient-angle": "135deg",
      "gradient-type": "radial",
      "hero-pattern": "radial-glow",
      "section-divider": "none",
    },
    code: {
      "font-family": "'PP Fraktion Mono', ui-monospace, monospace",
      "font-size": "0.8125rem",
      "line-height": "1.6",
      bg: "var(--s-surface-sunken)",
      border: "1px solid var(--s-border-muted)",
      "border-radius": "3px",
      padding: "14px",
      "tab-size": "2",
      "selection-bg": "var(--s-primary-muted)",
      "comment-color": "var(--s-text-muted)",
      "keyword-color": "var(--s-primary)",
      "string-color": "var(--s-success)",
      "number-color": "var(--s-warning)",
      "function-color": "var(--s-accent)",
    },
    inputs: {
      height: "36px",
      "height-sm": "28px",
      "height-lg": "44px",
      "border-width": "1px",
      "focus-ring-width": "2px",
      "focus-ring-color": "var(--s-primary)",
      "focus-ring-offset": "0px",
      "placeholder-color": "var(--s-text-subtle)",
      "error-border-color": "var(--s-error)",
      "label-size": "0.8125rem",
      "label-weight": "500",
      "label-spacing": "6px",
      "helper-size": "0.75rem",
    },
    alignment: {
      "title-align": "center",
    },
    sections: {
      "rail-margin": "40px",
      "padding-y": "5rem",
      "padding-y-hero": "7.5rem",
      "padding-y-sm": "2.5rem",
      gap: "44px",
      "padding-y-lg": "7.5rem",
      "padding-y-xl": "10rem",
      "max-width": "1080px",
      "heading-size": "clamp(1.5rem, 4vw, 2.5rem)",
      "heading-align": "center",
      "heading-max-width": "40rem",
      "heading-margin-bottom": "16px",
      "description-max-width": "32rem",
      "description-gap": "14px",
      "content-gap": "24px",
      "grid-columns": "3",
      "grid-gap": "24px",
      "alternate-bg": "var(--s-surface-sunken)",
      "alternate-bg-mode": "sunken",
    },
    dividers: {
      style: "none",
      spacing: "0px",
      opacity: "0.5",
      "max-width": "100%",
      "margin-y": "0px",
      thickness: "1px",
      "gradient-start": "transparent",
      "gradient-end": "transparent",
    },
    gridVisuals: {
      "line-color": "var(--s-border-muted)",
      "line-width": "1px",
      "show-lines": false,
      "show-dots": false,
      "cell-border": false,
    },
    cursor: {
      variant: "ring",
      size: "24px",
      "dot-size": "4px",
      "stroke-width": "1.5px",
      "tick-size": "6px",
      gap: "3px",
      radius: "0px",
      color: "var(--s-text)",
      "ring-color": "var(--s-primary)",
      "dot-color": "var(--s-primary)",
      glow: "0 0 8px var(--s-primary)",
      opacity: "1",
      "blend-mode": "normal",
      "z-index": "9999",
      "hide-native": false,
    },
    scrollbar: {
      width: "8px",
      height: "8px",
      padding: "2px",
      radius: "9999px",
      track: "transparent",
      thumb: "var(--s-border-muted)",
      "thumb-hover": "var(--s-border)",
      "thumb-active": "var(--s-border-strong)",
      corner: "transparent",
      border: "none",
      "firefox-width": "thin",
      gutter: "stable",
      visibility: "auto",
    },
    focus: {
      "ring-width": "2px",
      "ring-color": "var(--s-primary)",
      "ring-offset": "0px",
      "ring-shadow": "0 0 0 2px var(--s-primary)",
      "outline-color": "var(--s-primary)",
    },
    overlays: {
      bg: "rgb(0 0 0 / 0.7)",
      blur: "12px",
      surface: "var(--s-surface-elevated)",
      border: "1px solid var(--s-border-muted)",
      shadow: "var(--s-shadow-xl)",
      radius: "var(--s-radius-lg)",
      padding: "20px",
      "z-index": "50",
    },
    dataViz: {
      "series-1": "var(--s-primary)",
      "series-2": "var(--s-secondary)",
      "series-3": "var(--s-accent)",
      "series-4": "var(--s-info)",
      "series-5": "var(--s-success)",
      positive: "var(--s-success)",
      negative: "var(--s-error)",
      neutral: "var(--s-text-muted)",
      grid: "var(--s-border-muted)",
      axis: "var(--s-border)",
      label: "var(--s-text-secondary)",
      "tooltip-bg": "var(--s-surface-elevated)",
      "tooltip-border": "var(--s-border-muted)",
    },
    media: {
      radius: "var(--s-radius-md)",
      border: "none",
      outline: "1px solid rgb(0 0 0 / 0.08)",
      shadow: "none",
      bg: "var(--s-surface-sunken)",
      "object-fit": "cover",
    },
    controls: {
      height: "38px",
      "height-sm": "30px",
      "height-lg": "46px",
      "hit-area": "44px",
      "icon-size": "16px",
      "handle-size": "20px",
      "track-height": "4px",
      "track-bg": "var(--s-border-muted)",
      "track-fill": "var(--s-primary)",
      "thumb-bg": "var(--s-surface-elevated)",
      "thumb-border": "2px solid var(--s-primary)",
    },
    componentSurfaces: {
      bg: "var(--s-surface)",
      "bg-elevated": "var(--s-surface-elevated)",
      "bg-muted": "var(--s-surface-sunken)",
      border: "var(--s-border)",
      "border-muted": "var(--s-border-muted)",
      "border-strong": "var(--s-border-strong)",
      text: "var(--s-text)",
      "text-muted": "var(--s-text-muted)",
      contrast: "var(--s-primary-contrast)",
      "hover-bg": "var(--s-surface-elevated)",
      "active-bg": "var(--s-surface-sunken)",
      "selected-bg": "var(--s-primary-muted)",
    },
    hero: {
      "min-height": "auto",
      "padding-y": "120px",
      "padding-y-sm": "80px",
      "padding-x": "var(--s-page-margin, 24px)",
      "content-max": "640px",
      "content-align": "center",
      layout: "centered",
      "media-position": "below",
      "media-width": "50%",
      "media-radius": "var(--s-radius-lg)",
      "title-size": "clamp(2.5rem, 6vw, 4.5rem)",
      "title-max-width": "56rem",
      "description-size": "1.125rem",
      "description-max-width": "32rem",
      "description-gap": "24px",
      "actions-gap": "12px",
      "actions-margin-top": "36px",
      "action-padding-x": "24px",
      "action-padding-y": "12px",
      "badge-gap": "24px",
      "overlay-opacity": "0.7",
      "scroll-indicator": false,
      "gradient-overlay": "linear-gradient(to bottom, transparent, var(--s-background))",
    },
    cta: {
      "padding-y": "100px",
      "padding-x": "var(--s-page-margin, 24px)",
      "max-width": "var(--s-content-max, 1200px)",
      layout: "centered",
      border: false,
      "border-radius": "var(--s-radius-lg)",
      bg: "var(--s-surface-elevated)",
      "title-size": "clamp(1.5rem, 4vw, 2.5rem)",
      "description-max-width": "32rem",
      "description-gap": "14px",
      "actions-gap": "12px",
      "actions-margin-top": "36px",
      "action-padding-x": "24px",
      "action-padding-y": "12px",
      "split-gap": "40px",
    },
    footer: {
      "padding-y": "60px",
      "border-top": "1px solid var(--s-border)",
      columns: "4",
      "column-gap": "32px",
      "row-gap": "32px",
      "logo-height": "24px",
      "tagline-max-width": "20rem",
      "link-size": "0.875rem",
      "link-gap": "8px",
      "group-title-size": "0.8125rem",
      "group-title-weight": "600",
      "social-icon-size": "20px",
      "social-gap": "12px",
      "bottom-bar-padding": "20px 0",
      "bottom-bar-border": "1px solid var(--s-border-muted)",
    },
    banner: {
      height: "auto",
      "padding-y": "8px",
      "padding-x": "16px",
      "font-size": "0.875rem",
      "font-weight": "500",
      "icon-size": "16px",
      "icon-gap": "12px",
      "border-width": "1px",
      "border-position": "bottom",
      position: "top",
      "dismiss-size": "16px",
      radius: "0px",
    },
    pageRhythm: {
      density: "spacious",
      "section-gap": "0px",
      "section-gap-sm": "0px",
      "section-gap-lg": "0px",
      "first-section-offset": "0px",
      "last-section-margin": "0px",
      "alternate-bg": true,
      "alternate-bg-color": "var(--s-surface-sunken)",
      "divider-between": false,
      "max-content-width": "var(--s-content-max, 1200px)",
      "vertical-rhythm-unit": "8px",
      "scroll-snap": false,
      "responsive-scale": "0.9",
      "responsive-breakpoint": "768px",
    },

  },
};
