import type { SigilPreset } from "@sigil-ui/tokens";

export const onyxPreset: SigilPreset = {
  name: "onyx",
  metadata: {
    description: "Luxury dark. Gem-like depth, premium refinement, amethyst and gold.",
    mood: "luxury, dark, gem-like",
    tags: ["luxury", "dark", "premium", "amethyst", "gold", "refined"],
  },
  tokens: {
    colors: {
      background: { light: "oklch(0.98 0.004 310)", dark: "oklch(0.06 0.01 300)" },
      surface: { light: "oklch(0.965 0.005 310)", dark: "oklch(0.1 0.012 300)" },
      "surface-elevated": { light: "oklch(0.99 0.003 310)", dark: "oklch(0.14 0.012 300)" },
      "surface-sunken": { light: "oklch(0.945 0.006 310)", dark: "oklch(0.04 0.01 300)" },
      primary: "oklch(0.6 0.2 300)",
      "primary-hover": "oklch(0.54 0.22 300)",
      "primary-muted": "oklch(0.6 0.08 300)",
      "primary-contrast": "oklch(1 0 0)",
      secondary: "oklch(0.78 0.1 85)",
      "secondary-hover": "oklch(0.72 0.12 85)",
      "secondary-muted": "oklch(0.78 0.04 85)",
      accent: "oklch(0.68 0.14 340)",
      "accent-hover": "oklch(0.62 0.16 340)",
      "accent-muted": "oklch(0.68 0.06 340)",
      text: { light: "oklch(0.1 0.008 300)", dark: "oklch(0.94 0.004 310)" },
      "text-secondary": { light: "oklch(0.32 0.006 300)", dark: "oklch(0.76 0.005 310)" },
      "text-muted": { light: "oklch(0.48 0.005 300)", dark: "oklch(0.64 0.004 310)" },
      "text-subtle": { light: "oklch(0.6 0.004 300)", dark: "oklch(0.52 0.004 310)" },
      "text-disabled": { light: "oklch(0.72 0.003 300)", dark: "oklch(0.32 0.003 310)" },
      "text-inverse": { light: "oklch(0.94 0.004 310)", dark: "oklch(0.1 0.008 300)" },
      border: { light: "oklch(0.9 0.006 310)", dark: "oklch(0.26 0.01 300)" },
      "border-muted": { light: "oklch(0.93 0.004 310)", dark: "oklch(0.22 0.008 300)" },
      "border-strong": { light: "oklch(0.8 0.01 310)", dark: "oklch(0.28 0.014 300)" },
      "border-interactive": { light: "oklch(0.6 0.2 300)", dark: "oklch(0.6 0.2 300)" },
      success: "oklch(0.72 0.17 155)",
      "success-muted": "oklch(0.72 0.06 155)",
      warning: "oklch(0.78 0.14 80)",
      "warning-muted": "oklch(0.78 0.05 80)",
      error: "oklch(0.6 0.2 15)",
      "error-muted": "oklch(0.6 0.07 15)",
      info: "oklch(0.68 0.14 250)",
      "info-muted": "oklch(0.68 0.05 250)",
      "gradient-start": "oklch(0.6 0.2 300)",
      "gradient-end": "oklch(0.78 0.1 85)",
      glow: "oklch(0.6 0.2 300 / 0.4)",
    },
    typography: {
      "font-display": "'PP Neue Machina', system-ui, sans-serif",
      "font-body": "'PP Pier Sans', system-ui, sans-serif",
      "font-mono": "'PP Fraktion Mono', ui-monospace, monospace",
      "size-xs": "0.75rem",
      "size-sm": "0.875rem",
      "size-base": "1rem",
      "size-lg": "1.125rem",
      "size-xl": "1.3125rem",
      "size-2xl": "1.625rem",
      "size-3xl": "2rem",
      "size-4xl": "2.5rem",
      "size-5xl": "3.25rem",
      "size-6xl": "4.25rem",
      "weight-normal": "400",
      "weight-medium": "500",
      "weight-semibold": "600",
      "weight-bold": "700",
      "weight-extrabold": "800",
      "leading-tight": "1.2",
      "leading-normal": "1.55",
      "leading-relaxed": "1.7",
      "leading-loose": "2",
      "tracking-tighter": "-0.04em",
      "tracking-tight": "-0.02em",
      "tracking-normal": "0em",
      "tracking-wide": "0.03em",
      "tracking-wider": "0.06em",
      "heading-weight": "800",
      "heading-tracking": "0.08em",
      "heading-transform": "uppercase",
      "heading-family": "'PP Neue Machina', system-ui, sans-serif",
    },
    spacing: {
      scale: [4, 8, 12, 16, 24, 36, 52, 72, 96, 128],
      unit: "px",
      "button-px": "28px",
      "button-py": "14px",
      "button-px-sm": "20px",
      "button-py-sm": "10px",
      "button-px-lg": "40px",
      "button-py-lg": "16px",
      "card-padding": "36px",
      "card-padding-sm": "24px",
      "card-padding-lg": "48px",
      "input-px": "16px",
      "input-py": "12px",
      "badge-px": "12px",
      "badge-py": "3px",
      "section-py": "112px",
      "section-py-lg": "160px",
      "navbar-height": "76px",
      "navbar-px": "36px",
      "footer-py": "72px",
      "modal-padding": "32px",
      "popover-padding": "20px",
      "tooltip-padding": "8px 16px",
      "table-cell-px": "20px",
      "table-cell-py": "14px",
    },
    layout: {
      "content-max": "1200px",
      "content-max-narrow": "760px",
      "content-max-wide": "1536px",
      "page-margin": "40px",
      "page-margin-sm": "20px",
      "page-margin-lg": "72px",
      gutter: "40px",
      "gutter-sm": "20px",
      "gutter-lg": "56px",
      "grid-columns": "12",
      "grid-gap": "36px",
      "bento-gap": "24px",
      "bento-radius": "20px",
      "bento-min-height": "240px",
      "section-gap": "48px",
      "sidebar-width": "300px",
      "sidebar-collapsed": "64px",
      "footer-columns": "4",
      "stack-gap": "20px",
      "stack-gap-sm": "12px",
      "stack-gap-lg": "32px",
      "prose-max": "65ch",
    },
    sigil: {
      "grid-cell": "56px",
      "cross-arm": "6px",
      "cross-stroke": "0.75px",
      "rail-gap": "36px",
      "card-radius": "24px",
      "gutter-pattern": "wave",
      "margin-pattern": "dots",
    },
    radius: {
      none: "0px",
      sm: "6px",
      md: "12px",
      lg: "16px",
      xl: "20px",
      "2xl": "28px",
      full: "9999px",
      button: "12px",
      card: "20px",
      input: "12px",
      badge: "9999px",
      modal: "24px",
      popover: "16px",
      tooltip: "10px",
      image: "16px",
      bento: "20px",
    },
    shadows: {
      sm: "0 1px 3px 0 rgb(0 0 0 / 0.06), 0 1px 2px -1px rgb(0 0 0 / 0.06)",
      md: "0 4px 8px -2px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.06)",
      lg: "0 8px 20px -4px rgb(0 0 0 / 0.14), 0 4px 8px -4px rgb(0 0 0 / 0.06)",
      xl: "0 16px 36px -6px rgb(0 0 0 / 0.18), 0 8px 16px -8px rgb(0 0 0 / 0.08)",
      "2xl": "0 32px 64px -12px rgb(0 0 0 / 0.3)",
      glow: "0 0 36px var(--s-primary)",
      "glow-sm": "0 0 18px var(--s-primary)",
      colored: "0 8px 28px -6px var(--s-primary)",
      inner: "inset 0 2px 4px 0 rgb(0 0 0 / 0.06)",
      card: "0 8px 24px -6px rgb(0 0 0 / 0.12)",
      button: "none",
      "button-hover": "0 0 20px var(--s-primary)",
      dropdown: "0 12px 36px -6px rgb(0 0 0 / 0.18), 0 0 0 1px rgb(0 0 0 / 0.04)",
      modal: "0 32px 80px -20px rgb(0 0 0 / 0.35)",
    },
    motion: {
      duration: { instant: "0ms", fast: "180ms", normal: "300ms", slow: "480ms", slower: "720ms", slowest: "1200ms" },
      easing: {
        default: "cubic-bezier(0.22, 1, 0.36, 1)",
        in: "cubic-bezier(0.55, 0, 1, 0.45)",
        out: "cubic-bezier(0, 0.55, 0.45, 1)",
        "in-out": "cubic-bezier(0.45, 0, 0.55, 1)",
        spring: "cubic-bezier(0.34, 1.56, 0.64, 1)",
        bounce: "cubic-bezier(0.68, -0.55, 0.27, 1.55)",
      },
      "enter-preset": "fadeUp",
      "exit-preset": "fadeOut",
      "hover-scale": "1.015",
      "press-scale": "0.98",
      "hover-lift": "-4px",
      "stagger-interval": "65ms",
      "stagger-interval-fast": "35ms",
    },
    borders: {
      width: { none: "0px", thin: "1px", medium: "1.5px", thick: "2px" },
      style: "none",
      "card-border": "0px solid",
      "card-border-hover": "0px solid",
      "button-border": "0px solid",
      "input-border": "1px solid",
      "divider-style": "solid",
      "divider-width": "1px",
    },
    buttons: {
      "font-weight": "500",
      "text-transform": "none",
      "letter-spacing": "0.03em",
      "font-family": "'PP Pier Sans', system-ui, sans-serif",
      "border-width": "0px",
      "hover-effect": "fill",
      "active-scale": "0.98",
      "icon-gap": "10px",
      "min-width": "0px",
    },
    cards: {
      "border-style": "none",
      "border-width": "0px",
      "hover-effect": "glow",
      "hover-border-color": "transparent",
      padding: "32px",
      "header-padding": "32px 32px 0",
      "footer-padding": "0 32px 32px",
      "title-size": "1.125rem",
      "title-weight": "600",
      "description-size": "0.875rem",
      background: "elevated",
      shadow: "xl",
      outline: false,
      "outline-on-hover-only": true,
      "gap-between": "24px",
      "content-padding-x": "32px",
      "content-padding-y": "24px",
    },
    headings: {
      "h1-size": "2.5rem",
      "h1-weight": "600",
      "h1-tracking": "-0.025em",
      "h1-leading": "1.2",
      "h2-size": "2rem",
      "h2-weight": "600",
      "h2-tracking": "-0.02em",
      "h3-size": "1.625rem",
      "h3-weight": "600",
      "h4-size": "1.3125rem",
      "h4-weight": "500",
      "display-size": "4.25rem",
      "display-weight": "700",
      "display-tracking": "-0.04em",
      "display-leading": "1.08",
    },
    navigation: {
      "navbar-height": "76px",
      "navbar-backdrop-blur": "28px",
      "navbar-border": "none",
      "navbar-bg-opacity": "0.65",
      "nav-link-weight": "400",
      "nav-link-size": "0.875rem",
      "nav-link-hover": "background",
      "breadcrumb-separator": "/",
      "pagination-radius": "12px",
      "sidebar-width": "300px",
      "sidebar-item-radius": "14px",
      "sidebar-item-padding": "12px 18px",
    },
    backgrounds: {
      pattern: "none",
      "pattern-opacity": "0",
      "pattern-scale": "1",
      noise: true,
      "noise-opacity": "0.02",
      "gradient-angle": "180deg",
      "gradient-type": "radial",
      "hero-pattern": "radial-glow",
      "section-divider": "none",
    },
    code: {
      "font-family": "'PP Fraktion Mono', ui-monospace, monospace",
      "font-size": "0.875rem",
      "line-height": "1.75",
      bg: "var(--s-surface-sunken)",
      border: "1px solid var(--s-border-muted)",
      "border-radius": "16px",
      padding: "20px",
      "tab-size": "2",
      "selection-bg": "var(--s-primary-muted)",
      "comment-color": "var(--s-text-muted)",
      "keyword-color": "var(--s-primary)",
      "string-color": "var(--s-secondary)",
      "number-color": "var(--s-accent)",
      "function-color": "var(--s-info)",
    },
    inputs: {
      height: "46px",
      "height-sm": "38px",
      "height-lg": "54px",
      "border-width": "1px",
      "focus-ring-width": "2px",
      "focus-ring-color": "var(--s-primary)",
      "focus-ring-offset": "2px",
      "placeholder-color": "var(--s-text-subtle)",
      "error-border-color": "var(--s-error)",
      "label-size": "0.875rem",
      "label-weight": "500",
      "label-spacing": "8px",
      "helper-size": "0.8125rem",
    },
    alignment: {
      "rail-width": "1080px",
      "rail-columns": "12",
      "rail-gutter": "32px",
      "rail-margin": "48px",
      "rail-visible": false,
      "rail-color": "var(--s-border-muted)",
      "content-align": "center",
      "hero-align": "center",
      "section-align": "center",
      "navbar-align": "full",
      "footer-align": "content",
    },
    sections: {
      "padding-y": "96px",
      "padding-y-hero": "180px",
      "padding-x": "48px",
      "max-width": "1080px",
      gap: "48px",
      "title-align": "center",
      "divider-above": false,
      "divider-below": false,
      "background-alt": false,
      indent: "0px",
    },
    dividers: {
      style: "none",
      width: "0px",
      color: "var(--s-border)",
      spacing: "0px",
      "show-cross": false,
      "show-label": false,
      "full-bleed": false,
      ornament: "none",
    },
    gridVisuals: {
      "show-lines": false,
      "line-color": "var(--s-border-muted)",
      "line-width": "1px",
      "show-dots": false,
      "dot-size": "2px",
      "cell-background": "none",
      "cell-border": false,
      "cell-radius": "0px",
      "cell-padding": "24px",
      "hover-effect": "lift",
    },
  },
};
