import type { SigilPreset } from "@sigil-ui/tokens";

export const plumPreset: SigilPreset = {
  name: "plum",
  metadata: {
    description: "Luxurious plum surfaces with magenta depth. Dark-first preset with mauve light mode, elegant serif display, dramatic plum-tinted glows.",
    mood: "luxurious, rich, dramatic",
    tags: ["edgeless", "plum", "dark-first", "luxury", "colorful-bg"],
  },
  tokens: {
    colors: {
      background: { light: "oklch(0.94 0.025 320)", dark: "oklch(0.12 0.05 310)" },
      surface: { light: "oklch(0.92 0.03 320)", dark: "oklch(0.16 0.06 310)" },
      "surface-elevated": { light: "oklch(0.96 0.02 320)", dark: "oklch(0.20 0.055 310)" },
      "surface-sunken": { light: "oklch(0.89 0.035 320)", dark: "oklch(0.09 0.04 310)" },
      primary: { light: "oklch(0.55 0.20 330)", dark: "oklch(0.70 0.18 330)" },
      "primary-hover": { light: "oklch(0.48 0.22 330)", dark: "oklch(0.76 0.15 330)" },
      "primary-muted": { light: "oklch(0.55 0.06 330)", dark: "oklch(0.70 0.05 330)" },
      "primary-contrast": { light: "oklch(0.99 0.005 320)", dark: "oklch(0.12 0.05 310)" },
      secondary: "oklch(0.56 0.14 290)",
      "secondary-hover": "oklch(0.50 0.16 290)",
      "secondary-muted": "oklch(0.56 0.04 290)",
      accent: "oklch(0.62 0.12 350)",
      "accent-hover": "oklch(0.56 0.14 350)",
      "accent-muted": "oklch(0.62 0.04 350)",
      text: { light: "oklch(0.20 0.035 310)", dark: "oklch(0.92 0.02 330)" },
      "text-secondary": { light: "oklch(0.36 0.028 310)", dark: "oklch(0.76 0.02 325)" },
      "text-muted": { light: "oklch(0.50 0.022 315)", dark: "oklch(0.55 0.022 320)" },
      "text-subtle": { light: "oklch(0.63 0.018 315)", dark: "oklch(0.42 0.02 315)" },
      "text-disabled": { light: "oklch(0.75 0.015 315)", dark: "oklch(0.30 0.018 310)" },
      "text-inverse": { light: "oklch(0.92 0.02 330)", dark: "oklch(0.20 0.035 310)" },
      border: { light: "oklch(0.84 0.025 320)", dark: "oklch(0.300 0.035 310)" },
      "border-muted": { light: "oklch(0.90 0.018 320)", dark: "oklch(0.240 0.025 310)" },
      "border-strong": { light: "oklch(0.74 0.035 315)", dark: "oklch(0.380 0.045 310)" },
      "border-interactive": { light: "oklch(0.55 0.20 330)", dark: "oklch(0.70 0.18 330)" },
      success: "oklch(0.62 0.16 155)",
      "success-muted": { light: "oklch(0.93 0.04 155)", dark: "oklch(0.15 0.04 155)" },
      warning: "oklch(0.72 0.14 80)",
      "warning-muted": { light: "oklch(0.94 0.04 80)", dark: "oklch(0.18 0.04 80)" },
      error: "oklch(0.55 0.18 25)",
      "error-muted": { light: "oklch(0.94 0.04 25)", dark: "oklch(0.18 0.04 25)" },
      info: "oklch(0.60 0.13 245)",
      "info-muted": { light: "oklch(0.94 0.03 245)", dark: "oklch(0.18 0.03 245)" },
      "gradient-start": { light: "oklch(0.55 0.20 330)", dark: "oklch(0.70 0.18 330)" },
      "gradient-end": { light: "oklch(0.56 0.14 290)", dark: "oklch(0.58 0.14 290)" },
      glow: { light: "oklch(0.55 0.20 330 / 0.15)", dark: "oklch(0.70 0.18 330 / 0.20)" },
      highlight: { light: "oklch(0.92 0.08 330)", dark: "oklch(0.28 0.06 330)" },
    },
    typography: {
      "font-display": "'Playfair Display', Georgia, serif",
      "font-body": "'Inter', system-ui, sans-serif",
      "font-mono": "'Fira Code', ui-monospace, monospace",
      "size-xs": "0.75rem",
      "size-sm": "0.875rem",
      "size-base": "1rem",
      "size-lg": "1.125rem",
      "size-xl": "1.25rem",
      "size-2xl": "1.5rem",
      "size-3xl": "1.875rem",
      "size-4xl": "2.25rem",
      "size-5xl": "3rem",
      "size-6xl": "3.75rem",
      "weight-normal": "400",
      "weight-medium": "500",
      "weight-semibold": "600",
      "weight-bold": "700",
      "weight-extrabold": "800",
      "leading-tight": "1.2",
      "leading-normal": "1.6",
      "leading-relaxed": "1.75",
      "leading-loose": "2",
      "tracking-tighter": "-0.04em",
      "tracking-tight": "-0.02em",
      "tracking-normal": "0em",
      "tracking-wide": "0.02em",
      "tracking-wider": "0.04em",
      "heading-weight": "700",
      "heading-tracking": "-0.02em",
      "heading-transform": "none",
      "heading-family": "'Playfair Display', Georgia, serif",
    },
    spacing: {
      scale: [4, 8, 12, 16, 24, 32, 48, 64, 96, 128],
      unit: "px",
      "button-px": "26px",
      "button-py": "12px",
      "button-px-sm": "16px",
      "button-py-sm": "8px",
      "button-px-lg": "34px",
      "button-py-lg": "15px",
      "card-padding": "30px",
      "card-padding-sm": "20px",
      "card-padding-lg": "44px",
      "input-px": "14px",
      "input-py": "11px",
      "badge-px": "12px",
      "badge-py": "4px",
      "section-py": "112px",
      "section-py-lg": "156px",
      "navbar-height": "64px",
      "navbar-px": "32px",
      "footer-py": "80px",
      "modal-padding": "32px",
      "popover-padding": "16px",
      "tooltip-padding": "8px 14px",
      "table-cell-px": "16px",
      "table-cell-py": "14px",
    },
    layout: {
      "content-max": "1080px",
      "content-max-narrow": "680px",
      "content-max-wide": "1320px",
      "page-margin": "32px",
      "page-margin-sm": "16px",
      "page-margin-lg": "64px",
      gutter: "0px",
      "gutter-sm": "0px",
      "gutter-lg": "0px",
      "grid-columns": "12",
      "grid-gap": "28px",
      "bento-gap": "22px",
      "bento-radius": "16px",
      "bento-min-height": "220px",
      "section-gap": "48px",
      "sidebar-width": "260px",
      "sidebar-collapsed": "56px",
      "footer-columns": "4",
      "stack-gap": "20px",
      "stack-gap-sm": "12px",
      "stack-gap-lg": "32px",
      "prose-max": "64ch",
    },
    sigil: {
      "grid-cell": "64px",
      "cross-arm": "0px",
      "cross-stroke": "0px",
      "rail-gap": "0px",
      "card-radius": "16px",
      "gutter-pattern": "none",
      "margin-pattern": "none",
      "gutter-border": "none",
      "gutter-visible": false,
    },
    radius: {
      none: "0px",
      sm: "6px",
      md: "12px",
      lg: "16px",
      xl: "24px",
      "2xl": "32px",
      full: "9999px",
      button: "12px",
      card: "16px",
      input: "12px",
      badge: "9999px",
      modal: "20px",
      popover: "14px",
      tooltip: "8px",
      image: "14px",
      bento: "16px",
    },
    shadows: {
      sm: "0 1px 3px 0 oklch(0.15 0.05 310 / 0.08)",
      md: "0 2px 8px -1px oklch(0.15 0.05 310 / 0.12), 0 1px 3px 0 oklch(0.15 0.05 310 / 0.06)",
      lg: "0 4px 16px -2px oklch(0.15 0.05 310 / 0.16), 0 2px 4px 0 oklch(0.15 0.05 310 / 0.06)",
      xl: "0 8px 32px -4px oklch(0.15 0.05 310 / 0.18), 0 4px 8px -2px oklch(0.15 0.05 310 / 0.07)",
      "2xl": "0 16px 52px -8px oklch(0.15 0.05 310 / 0.22)",
      glow: "0 0 32px oklch(0.55 0.20 330 / 0.22)",
      "glow-sm": "0 0 16px oklch(0.55 0.20 330 / 0.15)",
      colored: "0 4px 20px -4px oklch(0.55 0.20 330 / 0.28)",
      inner: "inset 0 2px 4px 0 oklch(0.15 0.05 310 / 0.07)",
      card: "0 1px 6px 0 oklch(0.15 0.05 310 / 0.08)",
      button: "0 1px 3px 0 oklch(0.15 0.05 310 / 0.07)",
      "button-hover": "0 2px 10px -1px oklch(0.55 0.20 330 / 0.16)",
      dropdown: "0 4px 16px -2px oklch(0.15 0.05 310 / 0.16)",
      modal: "0 24px 48px -8px oklch(0.15 0.05 310 / 0.24)",
    },
    motion: {
      duration: { instant: "0ms", fast: "120ms", normal: "220ms", slow: "380ms", slower: "560ms", slowest: "820ms" },
      easing: {
        default: "cubic-bezier(0.22, 1, 0.36, 1)",
        in: "cubic-bezier(0.55, 0, 1, 0.45)",
        out: "cubic-bezier(0, 0.55, 0.45, 1)",
        "in-out": "cubic-bezier(0.45, 0, 0.55, 1)",
        spring: "cubic-bezier(0.34, 1.56, 0.64, 1)",
      },
      "hover-scale": "1.02",
      "press-scale": "0.97",
      "hover-lift": "-3px",
      "stagger-interval": "60ms",
      "stagger-interval-fast": "32ms",
    },
    borders: {
      width: { none: "0px", thin: "1px", medium: "1.5px", thick: "2px" },
      style: "solid",
      "card-border": "1px solid",
      "card-border-hover": "1px solid",
      "button-border": "1px solid",
      "input-border": "1px solid",
      "divider-style": "solid",
      "divider-width": "1px",
    },
    buttons: {
      "font-weight": "600",
      "text-transform": "none",
      "letter-spacing": "0em",
      "font-family": "'Inter', system-ui, sans-serif",
      "border-width": "1px",
      "hover-effect": "glow",
      "active-scale": "0.97",
      "icon-gap": "8px",
      "min-width": "0px",
    },
    cards: {
      "border-style": "solid",
      "border-width": "1px",
      "hover-effect": "glow",
      "hover-border-color": "var(--s-border-strong)",
      padding: "30px",
      "header-padding": "30px 30px 0",
      "footer-padding": "0 30px 30px",
      "title-size": "1.125rem",
      "title-weight": "600",
      "description-size": "0.9375rem",
      background: "surface",
      shadow: "md",
      outline: true,
      "outline-on-hover-only": false,
      "gap-between": "20px",
      "content-padding-x": "30px",
      "content-padding-y": "24px",
    },
    headings: {
      "h1-size": "2.75rem",
      "h1-weight": "700",
      "h1-tracking": "-0.025em",
      "h1-leading": "1.12",
      "h2-size": "2.125rem",
      "h2-weight": "700",
      "h2-tracking": "-0.02em",
      "h2-leading": "1.15",
      "h3-size": "1.5rem",
      "h3-weight": "600",
      "h3-tracking": "0em",
      "h3-leading": "1.2",
      "h4-size": "1.25rem",
      "h4-weight": "600",
      "h4-tracking": "0em",
      "h4-leading": "1.3",
      "display-size": "4.5rem",
      "display-weight": "700",
      "display-tracking": "-0.035em",
      "display-leading": "1.05",
    },
    navigation: {
      "navbar-height": "64px",
      "navbar-backdrop-blur": "18px",
      "navbar-border": "none",
      "navbar-bg-opacity": "0.88",
      "nav-link-weight": "500",
      "nav-link-size": "0.9375rem",
      "nav-link-hover": "color",
      "breadcrumb-separator": "/",
      "pagination-radius": "12px",
      "sidebar-width": "260px",
      "sidebar-item-radius": "12px",
      "sidebar-item-padding": "10px 16px",
    },
    backgrounds: {
      pattern: "none",
      "pattern-opacity": "0",
      "pattern-scale": "1",
      noise: true,
      "noise-opacity": "0.022",
      "gradient-angle": "135deg",
      "gradient-type": "none",
      "hero-pattern": "noise",
      "section-divider": "none",
    },
    code: {
      "font-family": "'Fira Code', ui-monospace, monospace",
      "font-size": "0.875rem",
      "line-height": "1.7",
      bg: "var(--s-surface-sunken)",
      border: "1px solid var(--s-border-muted)",
      "border-radius": "12px",
      padding: "20px",
      "tab-size": "2",
      "selection-bg": "var(--s-primary-muted)",
      "comment-color": "var(--s-text-muted)",
      "keyword-color": "oklch(0.58 0.18 330)",
      "string-color": "oklch(0.65 0.14 155)",
      "number-color": "oklch(0.72 0.14 80)",
      "function-color": "oklch(0.60 0.16 265)",
    },
    inputs: {
      height: "44px",
      "height-sm": "36px",
      "height-lg": "52px",
      "border-width": "1px",
      "focus-ring-width": "2px",
      "focus-ring-color": "var(--s-primary)",
      "focus-ring-offset": "2px",
      "placeholder-color": "var(--s-text-subtle)",
      "error-border-color": "var(--s-error)",
      "label-size": "0.875rem",
      "label-weight": "500",
      "label-spacing": "8px",
      "helper-size": "0.8125rem",
    },
    alignment: {
      "rail-width": "1080px",
      "rail-columns": "12",
      "rail-gutter": "28px",
      "rail-margin": "32px",
      "rail-visible": false,
      "rail-color": "var(--s-border-muted)",
      "content-align": "center",
      "hero-align": "center",
      "section-align": "center",
      "navbar-align": "full",
      "footer-align": "full",
    },
    sections: {
      "padding-y": "112px",
      "padding-y-hero": "156px",
      "padding-x": "32px",
      "max-width": "1080px",
      gap: "48px",
      "title-align": "center",
      "divider-above": false,
      "divider-below": false,
      "background-alt": false,
      indent: "0px",
    },
    dividers: {
      style: "none",
      width: "0px",
      color: "var(--s-border-muted)",
      spacing: "0px",
      "show-cross": false,
      "show-label": false,
      "full-bleed": false,
      ornament: "none",
    },
    gridVisuals: {
      "show-lines": false,
      "line-color": "var(--s-border-muted)",
      "line-width": "1px",
      "show-dots": false,
      "dot-size": "2px",
      "cell-background": "none",
      "cell-border": false,
      "cell-radius": "16px",
      "cell-padding": "24px",
      "hover-effect": "glow",
    },
    cursor: {
      variant: "dot",
      size: "24px",
      "dot-size": "4px",
      "stroke-width": "1.5px",
      "tick-size": "6px",
      gap: "3px",
      radius: "0px",
      color: "var(--s-text)",
      "ring-color": "var(--s-primary)",
      "dot-color": "var(--s-primary)",
      glow: "none",
      opacity: "1",
      "blend-mode": "normal",
      "z-index": "9999",
      "hide-native": false,
    },
    scrollbar: {
      width: "8px",
      height: "8px",
      padding: "2px",
      radius: "9999px",
      track: "transparent",
      thumb: "var(--s-border-muted)",
      "thumb-hover": "var(--s-border)",
      "thumb-active": "var(--s-border-strong)",
      corner: "transparent",
      border: "none",
      "firefox-width": "thin",
      gutter: "stable",
      visibility: "auto",
    },
    focus: {
      "ring-width": "2px",
      "ring-color": "var(--s-primary)",
      "ring-offset": "2px",
      "ring-shadow": "0 0 0 2px var(--s-primary)",
      "outline-color": "var(--s-primary)",
    },
    overlays: {
      bg: "rgb(0 0 0 / 0.5)",
      blur: "8px",
      surface: "var(--s-surface-elevated)",
      border: "1px solid var(--s-border-muted)",
      shadow: "var(--s-shadow-xl)",
      radius: "var(--s-radius-lg)",
      padding: "20px",
      "z-index": "50",
    },
    dataViz: {
      "series-1": "var(--s-primary)",
      "series-2": "var(--s-secondary)",
      "series-3": "var(--s-accent)",
      "series-4": "var(--s-info)",
      "series-5": "var(--s-success)",
      positive: "var(--s-success)",
      negative: "var(--s-error)",
      neutral: "var(--s-text-muted)",
      grid: "var(--s-border-muted)",
      axis: "var(--s-border)",
      label: "var(--s-text-secondary)",
      "tooltip-bg": "var(--s-surface-elevated)",
      "tooltip-border": "var(--s-border-muted)",
    },
    media: {
      radius: "var(--s-radius-md)",
      border: "none",
      outline: "1px solid rgb(0 0 0 / 0.08)",
      shadow: "none",
      bg: "var(--s-surface-sunken)",
      "object-fit": "cover",
    },
    controls: {
      height: "38px",
      "height-sm": "30px",
      "height-lg": "46px",
      "hit-area": "44px",
      "icon-size": "16px",
      "handle-size": "20px",
      "track-height": "4px",
      "track-bg": "var(--s-border-muted)",
      "track-fill": "var(--s-primary)",
      "thumb-bg": "var(--s-surface-elevated)",
      "thumb-border": "2px solid var(--s-primary)",
    },
    componentSurfaces: {
      bg: "var(--s-surface)",
      "bg-elevated": "var(--s-surface-elevated)",
      "bg-muted": "var(--s-surface-sunken)",
      border: "var(--s-border)",
      "border-muted": "var(--s-border-muted)",
      "border-strong": "var(--s-border-strong)",
      text: "var(--s-text)",
      "text-muted": "var(--s-text-muted)",
      contrast: "var(--s-primary-contrast)",
      "hover-bg": "var(--s-surface-elevated)",
      "active-bg": "var(--s-surface-sunken)",
      "selected-bg": "var(--s-primary-muted)",
    },

  },
};
