import type { SigilPreset } from "@sigil-ui/tokens";

export const rivetPreset: SigilPreset = {
  name: "rivet",
  metadata: {
    description: "Structural connections — exposed joints, industrial web aesthetic",
    author: "sigil-ui",
    version: "0.1.0",
    tags: ["industrial", "structural", "connected", "exposed"],
    mood: "structural, exposed, connected",
    inspiration: "Steel bridges, exposed rivets, construction blueprints",
  },
  tokens: {
    colors: {
      background: { light: "#f8f7f4", dark: "#141414" },
      surface: { light: "#f0efec", dark: "#1c1c1c" },
      "surface-elevated": { light: "#fafaf8", dark: "#242424" },
      "surface-sunken": { light: "#e8e7e4", dark: "#0c0c0c" },
      text: { light: "#27272a", dark: "#e4e4e7" },
      "text-secondary": { light: "#52525b", dark: "#a1a1aa" },
      "text-muted": { light: "#71717a", dark: "#71717a" },
      "text-subtle": { light: "#a1a1aa", dark: "#52525b" },
      "text-disabled": { light: "#d4d4d8", dark: "#3f3f46" },
      "text-inverse": { light: "#fafafa", dark: "#18181b" },
      border: { light: "#d4d4d8", dark: "#3f3f46" },
      "border-muted": { light: "#e4e4e7", dark: "#27272a" },
      "border-strong": { light: "#a1a1aa", dark: "#52525b" },
      "border-interactive": { light: "#c2410c", dark: "#ea580c" },
      primary: "#c2410c",
      "primary-hover": "#9a3412",
      "primary-muted": "#fff7ed",
      "primary-contrast": "#ffffff",
      secondary: "#3f3f46",
      "secondary-hover": "#27272a",
      "secondary-muted": "#e4e4e7",
      accent: "#0369a1",
      "accent-hover": "#075985",
      "accent-muted": "#e0f2fe",
      success: "#15803d",
      "success-muted": "#dcfce7",
      warning: "#a16207",
      "warning-muted": "#fef3c7",
      error: "#dc2626",
      "error-muted": "#fee2e2",
      info: "#0369a1",
      "info-muted": "#e0f2fe",
      "gradient-start": "#c2410c",
      "gradient-end": "#0369a1",
      glow: "rgba(194, 65, 12, 0.15)",
    },
    typography: {
      "font-display": "'Nacelle', system-ui, sans-serif",
      "font-body": "'Nacelle', system-ui, sans-serif",
      "font-mono": "'PP Supply Mono', ui-monospace, monospace",
      "size-xs": "0.75rem",
      "size-sm": "0.8125rem",
      "size-base": "0.9375rem",
      "size-lg": "1.0625rem",
      "size-xl": "1.25rem",
      "size-2xl": "1.5rem",
      "size-3xl": "1.875rem",
      "size-4xl": "2.25rem",
      "size-5xl": "3rem",
      "size-6xl": "3.75rem",
      "weight-normal": "400",
      "weight-medium": "500",
      "weight-semibold": "600",
      "weight-bold": "700",
      "weight-extrabold": "800",
      "leading-tight": "1.2",
      "leading-normal": "1.5",
      "leading-relaxed": "1.65",
      "leading-loose": "1.8",
      "tracking-tighter": "-0.03em",
      "tracking-tight": "-0.015em",
      "tracking-normal": "0em",
      "tracking-wide": "0.03em",
      "tracking-wider": "0.06em",
      "heading-weight": "600",
      "heading-tracking": "0.05em",
      "heading-transform": "uppercase",
      "heading-family": "'Nacelle', system-ui, sans-serif",
    },
    spacing: {
      scale: [4, 8, 12, 16, 24, 32, 48, 64, 80, 96],
      unit: "px",
      "button-px": "20px",
      "button-py": "10px",
      "button-px-sm": "14px",
      "button-py-sm": "7px",
      "button-px-lg": "28px",
      "button-py-lg": "14px",
      "card-padding": "24px",
      "card-padding-sm": "16px",
      "card-padding-lg": "32px",
      "input-px": "12px",
      "input-py": "10px",
      "badge-px": "10px",
      "badge-py": "3px",
      "section-py": "64px",
      "section-py-lg": "96px",
      "navbar-height": "56px",
      "navbar-px": "24px",
      "footer-py": "48px",
      "modal-padding": "24px",
      "popover-padding": "14px",
      "tooltip-padding": "6px 10px",
      "table-cell-px": "14px",
      "table-cell-py": "10px",
    },
    layout: {
      "content-max": "1200px",
      "content-max-narrow": "700px",
      "content-max-wide": "1440px",
      "page-margin": "24px",
      "page-margin-sm": "16px",
      "page-margin-lg": "48px",
      gutter: "24px",
      "gutter-sm": "16px",
      "gutter-lg": "32px",
      "grid-columns": "12",
      "grid-gap": "24px",
      "bento-gap": "16px",
      "bento-radius": "0px",
      "bento-min-height": "200px",
      "section-gap": "48px",
      "sidebar-width": "260px",
      "sidebar-collapsed": "56px",
      "footer-columns": "4",
      "stack-gap": "16px",
      "stack-gap-sm": "8px",
      "stack-gap-lg": "24px",
      "prose-max": "65ch",
    },
    sigil: {
      "grid-cell": "48px",
      "cross-arm": "6px",
      "cross-stroke": "1.5px",
      "rail-gap": "24px",
      "card-radius": "0px",
    },
    radius: {
      none: "0px",
      sm: "0px",
      md: "0px",
      lg: "0px",
      xl: "0px",
      "2xl": "0px",
      full: "9999px",
      button: "0px",
      card: "0px",
      input: "0px",
      badge: "9999px",
      modal: "0px",
      popover: "0px",
      tooltip: "9999px",
      image: "0px",
      bento: "0px",
    },
    shadows: {
      sm: "0 1px 2px rgba(0, 0, 0, 0.04)",
      md: "0 2px 4px rgba(0, 0, 0, 0.06)",
      lg: "0 4px 8px rgba(0, 0, 0, 0.08)",
      xl: "0 8px 16px rgba(0, 0, 0, 0.1)",
      "2xl": "0 12px 24px rgba(0, 0, 0, 0.12)",
      glow: "0 0 16px rgba(194, 65, 12, 0.15)",
      "glow-sm": "0 0 8px rgba(194, 65, 12, 0.1)",
      colored: "0 2px 8px rgba(194, 65, 12, 0.12)",
      inner: "inset 0 1px 2px rgba(0, 0, 0, 0.06)",
      card: "none",
      button: "none",
      "button-hover": "0 1px 3px rgba(0, 0, 0, 0.08)",
      dropdown: "0 4px 12px rgba(0, 0, 0, 0.1)",
      modal: "0 8px 24px rgba(0, 0, 0, 0.15)",
    },
    motion: {
      duration: {
        instant: "0ms",
        fast: "120ms",
        normal: "220ms",
        slow: "350ms",
        slower: "500ms",
        slowest: "700ms",
      },
      easing: {
        default: "cubic-bezier(0.16, 1, 0.3, 1)",
        in: "cubic-bezier(0.55, 0, 1, 0.45)",
        out: "cubic-bezier(0, 0.55, 0.45, 1)",
        "in-out": "cubic-bezier(0.45, 0, 0.55, 1)",
        spring: "cubic-bezier(0.34, 1.56, 0.64, 1)",
        bounce: "cubic-bezier(0.34, 1.4, 0.64, 1)",
      },
      "enter-preset": "220ms cubic-bezier(0.16, 1, 0.3, 1)",
      "exit-preset": "160ms cubic-bezier(0.55, 0, 1, 0.45)",
      "hover-scale": "1",
      "press-scale": "0.97",
      "hover-lift": "-1px",
      "stagger-interval": "50ms",
      "stagger-interval-fast": "25ms",
    },
    borders: {
      width: { none: "0px", thin: "1px", medium: "1.5px", thick: "2px" },
      style: "solid",
      "card-border": "1px solid var(--s-border)",
      "card-border-hover": "1px solid var(--s-border-interactive)",
      "button-border": "1.5px solid var(--s-border)",
      "input-border": "1px solid var(--s-border)",
      "divider-style": "dotted",
      "divider-width": "1.5px",
    },
    buttons: {
      "font-weight": "600",
      "text-transform": "none",
      "letter-spacing": "0em",
      "font-family": "'Nacelle', system-ui, sans-serif",
      "border-width": "1.5px",
      "hover-effect": "outline",
      "active-scale": "0.97",
      "icon-gap": "8px",
      "min-width": "0px",
    },
    cards: {
      "border-style": "solid",
      "border-width": "1px",
      "hover-effect": "border",
      "hover-border-color": "var(--s-primary)",
      padding: "24px",
      "header-padding": "24px 24px 0",
      "footer-padding": "0 24px 24px",
      "title-size": "var(--s-size-lg)",
      "title-weight": "600",
      "description-size": "var(--s-size-sm)",
      background: "surface",
      shadow: "none",
      outline: true,
      "outline-on-hover-only": false,
      "gap-between": "16px",
      "content-padding-x": "24px",
      "content-padding-y": "20px",
    },
    headings: {
      "h1-size": "3rem",
      "h1-weight": "700",
      "h1-tracking": "-0.025em",
      "h1-leading": "1.1",
      "h2-size": "2.25rem",
      "h2-weight": "600",
      "h2-tracking": "-0.02em",
      "h3-size": "1.5rem",
      "h3-weight": "600",
      "h4-size": "1.1875rem",
      "h4-weight": "600",
      "display-size": "3.75rem",
      "display-weight": "700",
      "display-tracking": "-0.035em",
      "display-leading": "1.05",
    },
    navigation: {
      "navbar-height": "56px",
      "navbar-backdrop-blur": "10px",
      "navbar-border": "1px solid var(--s-border-muted)",
      "navbar-bg-opacity": "0.9",
      "nav-link-weight": "500",
      "nav-link-size": "var(--s-size-sm)",
      "nav-link-hover": "color",
      "breadcrumb-separator": "·",
      "pagination-radius": "0px",
      "sidebar-width": "260px",
      "sidebar-item-radius": "0px",
      "sidebar-item-padding": "8px 12px",
    },
    backgrounds: {
      pattern: "dots",
      "pattern-opacity": "0.06",
      "pattern-scale": "24px",
      noise: false,
      "noise-opacity": "0",
      "gradient-angle": "135deg",
      "gradient-type": "none",
      "hero-pattern": "grid",
      "section-divider": "line",
    },
    code: {
      "font-family": "'PP Supply Mono', ui-monospace, monospace",
      "font-size": "0.8125rem",
      "line-height": "1.6",
      bg: "#f0efec",
      border: "1px solid #d4d4d8",
      "border-radius": "0px",
      padding: "20px 24px",
      "tab-size": "2",
      "selection-bg": "rgba(194, 65, 12, 0.12)",
      "comment-color": "#71717a",
      "keyword-color": "#c2410c",
      "string-color": "#15803d",
      "number-color": "#0369a1",
      "function-color": "#7c3aed",
    },
    inputs: {
      height: "40px",
      "height-sm": "32px",
      "height-lg": "48px",
      "border-width": "1px",
      "focus-ring-width": "2px",
      "focus-ring-color": "var(--s-primary)",
      "focus-ring-offset": "1px",
      "placeholder-color": "var(--s-text-muted)",
      "error-border-color": "var(--s-error)",
      "label-size": "var(--s-size-sm)",
      "label-weight": "500",
      "label-spacing": "6px",
      "helper-size": "var(--s-size-xs)",
    },
    alignment: {
      "title-align": "left",
    },
    sections: {
      "rail-margin": "20px",
      "padding-y": "52px",
      gap: "24px",
    },
    dividers: {
      style: "dotted",
      ornament: "dot",
    },
    gridVisuals: {
      "rail-visible": true,
      "show-lines": true,
      "show-dots": true,
      "cell-border": true,
    },
  },
};
