import type { SigilPreset } from "@sigil-ui/tokens";
import { completePreset } from "./_template";

export const rivetPreset: SigilPreset = completePreset({
  name: "rivet",
  metadata: {
    description: "Structural connections — exposed joints, industrial web aesthetic",
    author: "sigil-ui",
    version: "0.1.0",
    tags: ["industrial", "structural", "connected", "exposed"],
    mood: "structural, exposed, connected",
    inspiration: "Steel bridges, exposed rivets, construction blueprints",
  },
  tokens: {
    colors: {
      background: { light: "oklch(0.9761 0.0041 91.4461)", dark: "oklch(0.1913 0 0)" },
      surface: { light: "oklch(0.9521 0.0041 91.4473)", dark: "oklch(0.2264 0 0)" },
      "surface-elevated": { light: "oklch(0.9845 0.0026 106.4479)", dark: "oklch(0.2603 0 0)" },
      "surface-sunken": { light: "oklch(0.9279 0.0042 91.4485)", dark: "oklch(0.1543 0 0)" },
      text: { light: "oklch(0.2739 0.0055 286.0326)", dark: "oklch(0.9197 0.004 286.3201)" },
      "text-secondary": { light: "oklch(0.4419 0.0146 285.7864)", dark: "oklch(0.7118 0.0129 286.0665)" },
      "text-muted": { light: "oklch(0.5517 0.0138 285.9384)", dark: "oklch(0.6493 0.0118 286.0674)" },
      "text-subtle": { light: "oklch(0.643 0.0133 286.0204)", dark: "oklch(0.5017 0.0094 286.0555)" },
      "text-disabled": { light: "oklch(0.8711 0.0055 286.2859)", dark: "oklch(0.3703 0.0119 285.8054)" },
      "text-inverse": { light: "oklch(0.9851 0 0)", dark: "oklch(0.2103 0.0059 285.8851)" },
      border: { light: "oklch(0.6444 0.0044 286.2752)", dark: "oklch(0.371 0.013 286)" },
      "border-muted": { light: "oklch(0.7993 0.0042 286.3048)", dark: "oklch(0.311 0.010 286)" },
      "border-strong": { light: "oklch(0.643 0.0133 286.0204)", dark: "oklch(0.451 0.014 286)" },
      "border-interactive": { light: "oklch(0.5534 0.1739 38.4022)", dark: "oklch(0.6461 0.1943 41.1158)" },
      primary: "oklch(0.5534 0.1739 38.4022)",
      "primary-hover": "oklch(0.4698 0.143 37.3035)",
      "primary-muted": "oklch(0.9796 0.0158 73.684)",
      "primary-contrast": "oklch(1 0 0)",
      secondary: "oklch(0.3703 0.0119 285.8054)",
      "secondary-hover": "oklch(0.2739 0.0055 286.0326)",
      "secondary-muted": "oklch(0.9197 0.004 286.3201)",
      accent: "oklch(0.5 0.1193 242.749)",
      "accent-hover": "oklch(0.4434 0.1 240.7897)",
      "accent-muted": "oklch(0.9514 0.025 236.8242)",
      success: "oklch(0.5273 0.1371 150.0693)",
      "success-muted": "oklch(0.9624 0.0434 156.7426)",
      warning: "oklch(0.5538 0.1207 66.4416)",
      "warning-muted": "oklch(0.9619 0.058 95.6174)",
      error: "oklch(0.5771 0.2152 27.325)",
      "error-muted": "oklch(0.9356 0.0309 17.7171)",
      info: "oklch(0.5461 0.2152 262.8809)",
      "info-muted": "oklch(0.9514 0.025 236.8242)",
      "gradient-start": "oklch(0.5534 0.1739 38.4022)",
      "gradient-end": "oklch(0.5 0.1193 242.749)",
      glow: "oklch(0.5534 0.1739 38.4022 / 0.15)",
      highlight: { light: "oklch(0.9015 0.0729 70.6972)", dark: "oklch(0.6461 0.1943 41.1158 / 0.15)" },
    },
    typography: {
      "font-display": "'Nacelle', system-ui, sans-serif",
      "font-body": "'Nacelle', system-ui, sans-serif",
      "font-mono": "'PP Supply Mono', ui-monospace, monospace",
      "size-xs": "0.75rem",
      "size-sm": "0.8125rem",
      "size-base": "0.9375rem",
      "size-lg": "1.0625rem",
      "size-xl": "1.25rem",
      "size-2xl": "1.5rem",
      "size-3xl": "1.875rem",
      "size-4xl": "2.25rem",
      "size-5xl": "3rem",
      "size-6xl": "3.75rem",
      "weight-normal": "400",
      "weight-medium": "500",
      "weight-semibold": "600",
      "weight-bold": "700",
      "weight-extrabold": "800",
      "leading-tight": "1.2",
      "leading-normal": "1.5",
      "leading-relaxed": "1.65",
      "leading-loose": "1.8",
      "tracking-tighter": "-0.03em",
      "tracking-tight": "-0.015em",
      "tracking-normal": "0em",
      "tracking-wide": "0.03em",
      "tracking-wider": "0.06em",
      "heading-weight": "600",
      "heading-tracking": "0.05em",
      "heading-transform": "uppercase",
      "heading-family": "'Nacelle', system-ui, sans-serif",
    },
    spacing: {
      scale: [4, 8, 12, 16, 24, 32, 48, 64, 80, 96],
      unit: "px",
      "button-px": "20px",
      "button-py": "10px",
      "button-px-sm": "14px",
      "button-py-sm": "7px",
      "button-px-lg": "28px",
      "button-py-lg": "14px",
      "card-padding": "20px",
      "card-padding-sm": "16px",
      "card-padding-lg": "32px",
      "input-px": "12px",
      "input-py": "10px",
      "badge-px": "10px",
      "badge-py": "3px",
      "section-py": "5.5rem",
      "section-py-lg": "8.25rem",
      "navbar-height": "44px",
      "navbar-px": "20px",
      "footer-py": "44px",
      "modal-padding": "24px",
      "popover-padding": "14px",
      "tooltip-padding": "6px 10px",
      "table-cell-px": "14px",
      "table-cell-py": "10px",
    },
    layout: {
      "content-max": "1200px",
      "content-max-narrow": "720px",
      "content-max-wide": "1440px",
      "page-margin": "20px",
      "page-margin-sm": "16px",
      "page-margin-lg": "40px",
      gutter: "20px",
      "gutter-sm": "16px",
      "gutter-lg": "28px",
      "grid-columns": "12",
      "grid-gap": "20px",
      "bento-gap": "12px",
      "bento-radius": "0px",
      "bento-min-height": "198px",
      "section-gap": "44px",
      "sidebar-width": "256px",
      "sidebar-collapsed": "56px",
      "footer-columns": "4",
      "stack-gap": "16px",
      "stack-gap-sm": "8px",
      "stack-gap-lg": "24px",
      "prose-max": "65ch",
    },
    sigil: {
      "grid-cell": "44px",
      "cross-arm": "8px",
      "cross-stroke": "1.5px",
      "rail-gap": "20px",
      "card-radius": "0px",
      "gutter-pattern": "triangle",
      "margin-pattern": "grid",
      "margin-border": "1px solid var(--s-border-muted)",
      "band-height": "44px",
      "divider-thickness-sm": "calc(var(--s-grid-cell) / 2)",
      "divider-thickness-md": "var(--s-grid-cell)",
      "divider-thickness-lg": "calc(2 * var(--s-grid-cell))",
      "divider-thickness-xl": "calc(3 * var(--s-grid-cell))",
    },
    radius: {
      none: "0px",
      sm: "0px",
      md: "0px",
      lg: "0px",
      xl: "0px",
      "2xl": "0px",
      full: "9999px",
      button: "0px",
      card: "0px",
      input: "0px",
      badge: "9999px",
      modal: "0px",
      popover: "0px",
      tooltip: "9999px",
      image: "0px",
      bento: "0px",
    },
    shadows: {
      sm: "0 1px 2px rgba(0, 0, 0, 0.04)",
      md: "0 2px 4px rgba(0, 0, 0, 0.06)",
      lg: "0 4px 8px rgba(0, 0, 0, 0.08)",
      xl: "0 8px 16px rgba(0, 0, 0, 0.1)",
      "2xl": "0 12px 24px rgba(0, 0, 0, 0.12)",
      glow: "0 0 16px rgba(194, 65, 12, 0.15)",
      "glow-sm": "0 0 8px rgba(194, 65, 12, 0.1)",
      colored: "0 2px 8px rgba(194, 65, 12, 0.12)",
      inner: "inset 0 1px 2px rgba(0, 0, 0, 0.06)",
      card: "none",
      button: "none",
      "button-hover": "0 1px 3px rgba(0, 0, 0, 0.08)",
      dropdown: "0 4px 12px rgba(0, 0, 0, 0.1)",
      modal: "0 8px 24px rgba(0, 0, 0, 0.15)",
    },
    motion: {
      duration: {
        instant: "0ms",
        fast: "120ms",
        normal: "220ms",
        slow: "350ms",
        slower: "500ms",
        slowest: "700ms",
      },
      easing: {
        default: "cubic-bezier(0.16, 1, 0.3, 1)",
        in: "cubic-bezier(0.55, 0, 1, 0.45)",
        out: "cubic-bezier(0, 0.55, 0.45, 1)",
        "in-out": "cubic-bezier(0.45, 0, 0.55, 1)",
        spring: "cubic-bezier(0.34, 1.56, 0.64, 1)",
        bounce: "cubic-bezier(0.34, 1.4, 0.64, 1)",
      },
      "enter-preset": "220ms cubic-bezier(0.16, 1, 0.3, 1)",
      "exit-preset": "160ms cubic-bezier(0.55, 0, 1, 0.45)",
      "hover-scale": "1",
      "press-scale": "0.97",
      "hover-lift": "-1px",
      "stagger-interval": "50ms",
      "stagger-interval-fast": "25ms",
    },
    borders: {
      width: { none: "0px", thin: "1px", medium: "1.5px", thick: "2px" },
      style: "dotted",
      "card-border": "1px solid var(--s-border)",
      "card-border-hover": "1px solid var(--s-border-interactive)",
      "button-border": "1.5px solid var(--s-border)",
      "input-border": "1px solid var(--s-border)",
      "divider-style": "dotted",
      "divider-width": "1.5px",
    },
    buttons: {
      "font-weight": "600",
      "text-transform": "none",
      "letter-spacing": "0em",
      "font-family": "'Nacelle', system-ui, sans-serif",
      "border-width": "1.5px",
      "hover-effect": "outline",
      "active-scale": "0.97",
      "icon-gap": "8px",
      "min-width": "0px",
    },
    cards: {
      "border-style": "solid",
      "border-width": "1px",
      "hover-effect": "lift",
      "hover-border-color": "var(--s-primary)",
      padding: "24px",
      "header-padding": "24px 24px 0",
      "footer-padding": "0 24px 24px",
      "title-size": "var(--s-size-lg)",
      "title-weight": "600",
      "description-size": "var(--s-size-sm)",
      background: "surface",
      shadow: "none",
      outline: true,
      "outline-on-hover-only": false,
      "gap-between": "16px",
      "content-padding-x": "24px",
      "content-padding-y": "20px",
    },
    headings: {
      "h1-size": "3rem",
      "h1-weight": "700",
      "h1-tracking": "-0.025em",
      "h1-leading": "1.1",
      "h2-size": "2.25rem",
      "h2-weight": "600",
      "h2-tracking": "-0.02em",
      "h2-leading": "1.1",
      "h3-size": "1.5rem",
      "h3-weight": "600",
      "h3-tracking": "0em",
      "h3-leading": "1.15",
      "h4-size": "1.1875rem",
      "h4-weight": "600",
      "h4-tracking": "0em",
      "h4-leading": "1.2",
      "display-size": "3.75rem",
      "display-weight": "700",
      "display-tracking": "-0.035em",
      "display-leading": "1.05",
    },
    navigation: {
      "navbar-height": "44px",
      "navbar-backdrop-blur": "10px",
      "navbar-border": "1px solid",
      "navbar-bg-opacity": "0.9",
      "navbar-padding-x": "20px",
      "navbar-position": "sticky",
      "navbar-logo-height": "22px",
      "navbar-logo-gap": "8px",
      "navbar-item-gap": "16px",
      "navbar-item-padding-x": "10px",
      "navbar-item-padding-y": "4px",
      "navbar-item-size": "0.8125rem",
      "navbar-shadow": "none",
      "navbar-height-scrolled": "44px",
      "navbar-mobile-breakpoint": "768px",
      "nav-link-weight": "500",
      "nav-link-size": "var(--s-size-sm)",
      "nav-link-hover": "color",
      "breadcrumb-separator": "·",
      "pagination-radius": "0px",
      "sidebar-width": "256px",
      "sidebar-item-radius": "0px",
      "sidebar-item-padding": "7px 12px",
    },
    backgrounds: {
      pattern: "dots",
      "pattern-opacity": "0.04",
      "pattern-scale": "24px",
      noise: true,
      "noise-opacity": "0.015",
      "gradient-angle": "135deg",
      "gradient-type": "none",
      "hero-pattern": "grid",
      "section-divider": "line",
    },
    code: {
      "font-family": "'PP Supply Mono', ui-monospace, monospace",
      "font-size": "0.8125rem",
      "line-height": "1.6",
      bg: "#f0efec",
      border: "1px solid #d4d4d8",
      "border-radius": "0px",
      padding: "20px 24px",
      "tab-size": "2",
      "selection-bg": "rgba(194, 65, 12, 0.12)",
      "comment-color": "#71717a",
      "keyword-color": "#c2410c",
      "string-color": "#15803d",
      "number-color": "#0369a1",
      "function-color": "#7c3aed",
    },
    inputs: {
      height: "40px",
      "height-sm": "32px",
      "height-lg": "48px",
      "border-width": "1px",
      "focus-ring-width": "2px",
      "focus-ring-color": "var(--s-primary)",
      "focus-ring-offset": "1px",
      "placeholder-color": "var(--s-text-muted)",
      "error-border-color": "var(--s-error)",
      "label-size": "var(--s-size-sm)",
      "label-weight": "500",
      "label-spacing": "6px",
      "helper-size": "var(--s-size-xs)",
    },
    alignment: {
      "title-align": "left",
    },
    sections: {
      "rail-margin": "20px",
      "padding-y": "5.5rem",
      "padding-y-sm": "2.75rem",
      gap: "24px",
      "padding-y-lg": "8.25rem",
      "padding-y-xl": "11rem",
      "heading-size": "clamp(1.25rem, 3vw, 2rem)",
      "heading-align": "left",
      "heading-max-width": "36rem",
      "heading-margin-bottom": "12px",
      "description-max-width": "28rem",
      "description-gap": "8px",
      "content-gap": "16px",
      "grid-columns": "3",
      "grid-gap": "16px",
      "alternate-bg": "var(--s-surface)",
      "alternate-bg-mode": "none",
    },
    dividers: {
      style: "dotted",
      opacity: "1",
      "max-width": "100%",
      "margin-y": "0px",
      thickness: "2px",
      "gradient-start": "transparent",
      "gradient-end": "transparent",
      ornament: "dot",
    },
    gridVisuals: {
      "line-color": "var(--s-border-muted)",
      "line-width": "1px",
      "rail-visible": true,
      "show-lines": true,
      "show-dots": true,
      "cell-border": true,
    },
    cursor: {
      variant: "crosshair",
      size: "24px",
      "dot-size": "4px",
      "stroke-width": "2px",
      "tick-size": "6px",
      gap: "3px",
      radius: "0px",
      color: "var(--s-text)",
      "ring-color": "var(--s-primary)",
      "dot-color": "var(--s-primary)",
      glow: "none",
      opacity: "1",
      "blend-mode": "normal",
      "z-index": "9999",
      "hide-native": false,
    },
    scrollbar: {
      width: "10px",
      height: "10px",
      padding: "2px",
      radius: "2px",
      track: "transparent",
      thumb: "var(--s-border-muted)",
      "thumb-hover": "var(--s-border)",
      "thumb-active": "var(--s-border-strong)",
      corner: "transparent",
      border: "none",
      "firefox-width": "auto",
      gutter: "stable",
      visibility: "auto",
    },
    focus: {
      "ring-width": "3px",
      "ring-color": "var(--s-primary)",
      "ring-offset": "0px",
      "ring-shadow": "0 0 0 3px var(--s-primary)",
      "outline-color": "var(--s-primary)",
    },
    overlays: {
      bg: "rgb(0 0 0 / 0.6)",
      blur: "4px",
      surface: "var(--s-surface-elevated)",
      border: "1px solid var(--s-border-muted)",
      shadow: "var(--s-shadow-xl)",
      radius: "var(--s-radius-lg)",
      padding: "20px",
      "z-index": "50",
    },
    dataViz: {
      "series-1": "var(--s-primary)",
      "series-2": "var(--s-secondary)",
      "series-3": "var(--s-accent)",
      "series-4": "var(--s-info)",
      "series-5": "var(--s-success)",
      positive: "var(--s-success)",
      negative: "var(--s-error)",
      neutral: "var(--s-text-muted)",
      grid: "var(--s-border-muted)",
      axis: "var(--s-border)",
      label: "var(--s-text-secondary)",
      "tooltip-bg": "var(--s-surface-elevated)",
      "tooltip-border": "var(--s-border-muted)",
    },
    media: {
      radius: "var(--s-radius-md)",
      border: "none",
      outline: "1px solid rgb(0 0 0 / 0.08)",
      shadow: "none",
      bg: "var(--s-surface-sunken)",
      "object-fit": "cover",
    },
    controls: {
      height: "38px",
      "height-sm": "30px",
      "height-lg": "46px",
      "hit-area": "44px",
      "icon-size": "16px",
      "handle-size": "20px",
      "track-height": "4px",
      "track-bg": "var(--s-border-muted)",
      "track-fill": "var(--s-primary)",
      "thumb-bg": "var(--s-surface-elevated)",
      "thumb-border": "2px solid var(--s-primary)",
    },
    componentSurfaces: {
      bg: "var(--s-surface)",
      "bg-elevated": "var(--s-surface-elevated)",
      "bg-muted": "var(--s-surface-sunken)",
      border: "var(--s-border)",
      "border-muted": "var(--s-border-muted)",
      "border-strong": "var(--s-border-strong)",
      text: "var(--s-text)",
      "text-muted": "var(--s-text-muted)",
      contrast: "var(--s-primary-contrast)",
      "hover-bg": "var(--s-surface-elevated)",
      "active-bg": "var(--s-surface-sunken)",
      "selected-bg": "var(--s-primary-muted)",
    },
    hero: {
      "min-height": "auto",
      "padding-y": "66px",
      "padding-y-sm": "44px",
      "padding-x": "var(--s-page-margin, 20px)",
      "content-max": "560px",
      "content-basis": "min(42%, var(--s-hero-content-max, 640px))",
      "content-align": "left",
      layout: "split",
      "media-position": "right",
      "media-width": "45%",
      "media-radius": "var(--s-radius-sm)",
      "split-gap": "var(--s-section-subsection-gap, var(--s-grid-cell))",
      "title-size": "clamp(1.75rem, 5vw, 3rem)",
      "title-max-width": "40rem",
      "description-size": "1rem",
      "description-max-width": "28rem",
      "description-gap": "16px",
      "actions-gap": "10px",
      "actions-margin-top": "24px",
      "action-padding-x": "20px",
      "action-padding-y": "10px",
      "badge-gap": "16px",
      "overlay-opacity": "0.6",
      "scroll-indicator": false,
      "gradient-overlay": "none",
    },
    cta: {
      "padding-y": "66px",
      "padding-x": "var(--s-page-margin, 20px)",
      "max-width": "var(--s-content-max, 1200px)",
      layout: "split",
      border: true,
      "border-radius": "var(--s-radius-sm)",
      bg: "var(--s-surface)",
      "title-size": "clamp(1.25rem, 3vw, 2rem)",
      "description-max-width": "28rem",
      "description-gap": "8px",
      "actions-gap": "10px",
      "actions-margin-top": "20px",
      "action-padding-x": "20px",
      "action-padding-y": "10px",
      "split-gap": "22px",
    },
    footer: {
      "padding-y": "44px",
      "border-top": "2px solid var(--s-border-strong)",
      columns: "4",
      "column-gap": "24px",
      "row-gap": "24px",
      "logo-height": "20px",
      "tagline-max-width": "18rem",
      "link-size": "0.8125rem",
      "link-gap": "6px",
      "group-title-size": "0.75rem",
      "group-title-weight": "700",
      "social-icon-size": "16px",
      "social-gap": "10px",
      "bottom-bar-padding": "22px 0",
      "bottom-bar-border": "2px solid var(--s-border)",
    },
    banner: {
      height: "auto",
      "padding-y": "6px",
      "padding-x": "16px",
      "font-size": "0.8125rem",
      "font-weight": "600",
      "icon-size": "14px",
      "icon-gap": "8px",
      "border-width": "2px",
      "border-position": "bottom",
      position: "top",
      "dismiss-size": "14px",
      radius: "0px",
    },
    pageRhythm: {
      mode: "locked",
      snap: true,
      "band-stroke": "visual",
      "hairline-width": "1px",
      "hairline-spacing": "var(--s-section-gap, 0px)",
      "hairline-style": "solid",
      density: "compact",
      "section-gap": "0px",
      "section-gap-sm": "0px",
      "section-gap-lg": "0px",
      "first-section-offset": "0px",
      "last-section-margin": "0px",
      "alternate-bg": false,
      "alternate-bg-color": "var(--s-surface)",
      "divider-between": true,
      "max-content-width": "var(--s-content-max, 1200px)",
      "vertical-rhythm-unit": "4px",
      "scroll-snap": false,
      "responsive-scale": "1",
      "responsive-breakpoint": "768px",
    },

  },
});
