import type { SigilPreset } from "@sigil-ui/tokens";

export const runePreset: SigilPreset = {
  name: "rune",
  metadata: {
    description: "Ancient symbols — mystical, carved, timeless serif aesthetic",
    author: "sigil-ui",
    version: "0.1.0",
    tags: ["serif", "mystical", "warm", "timeless"],
    mood: "ancient, carved, mystical",
    inspiration: "Illuminated manuscripts, carved stone, parchment scrolls",
  },
  tokens: {
    colors: {
      background: { light: "#f5f0e8", dark: "#1a1814" },
      surface: { light: "#ede8df", dark: "#22201b" },
      "surface-elevated": { light: "#faf7f2", dark: "#2a2722" },
      "surface-sunken": { light: "#e5dfd5", dark: "#12110e" },
      text: { light: "#2c2517", dark: "#e5dfd5" },
      "text-secondary": { light: "#4a4233", dark: "#b5ad9e" },
      "text-muted": { light: "#6b6354", dark: "#9a9284" },
      "text-subtle": { light: "#8a8274", dark: "#7d7566" },
      "text-disabled": { light: "#b5ad9e", dark: "#4a4233" },
      "text-inverse": { light: "#f5f0e8", dark: "#2c2517" },
      border: { light: "#8f887c", dark: "oklch(0.380 0.012 82)" },
      "border-muted": { light: "#beb8ad", dark: "oklch(0.320 0.011 78)" },
      "border-strong": { light: "#908879", dark: "oklch(0.470 0.021 89)" },
      "border-interactive": { light: "#b45309", dark: "#f59e0b" },
      primary: "#b45309",
      "primary-hover": "#92400e",
      "primary-muted": "#fef3c7",
      "primary-contrast": "#ffffff",
      secondary: "#6b6354",
      "secondary-hover": "#4a4233",
      "secondary-muted": "#e5dfd5",
      accent: "#7c2d12",
      "accent-hover": "#6c2710",
      "accent-muted": "#fee2e2",
      success: "#4c7024",
      "success-muted": "#ecfccb",
      warning: "#b45309",
      "warning-muted": "#fef3c7",
      error: "#b73b34",
      "error-muted": "#fee2e2",
      info: "#3867a8",
      "info-muted": "#dbeafe",
      "gradient-start": "#b45309",
      "gradient-end": "#7c2d12",
      glow: "rgba(180, 83, 9, 0.15)",
      highlight: { light: "#fef3c7", dark: "rgba(217, 119, 6, 0.15)" },
    },
    typography: {
      "font-display": "'PP Rader', Georgia, serif",
      "font-body": "'PP Writer', Georgia, serif",
      "font-mono": "'PP Supply Mono', ui-monospace, monospace",
      "size-xs": "0.8125rem",
      "size-sm": "0.875rem",
      "size-base": "1rem",
      "size-lg": "1.125rem",
      "size-xl": "1.3125rem",
      "size-2xl": "1.5625rem",
      "size-3xl": "1.9375rem",
      "size-4xl": "2.375rem",
      "size-5xl": "3rem",
      "size-6xl": "3.75rem",
      "weight-normal": "400",
      "weight-medium": "500",
      "weight-semibold": "600",
      "weight-bold": "700",
      "weight-extrabold": "800",
      "leading-tight": "1.25",
      "leading-normal": "1.6",
      "leading-relaxed": "1.75",
      "leading-loose": "1.9",
      "tracking-tighter": "-0.02em",
      "tracking-tight": "-0.01em",
      "tracking-normal": "0em",
      "tracking-wide": "0.02em",
      "tracking-wider": "0.04em",
      "heading-weight": "400",
      "heading-tracking": "0em",
      "heading-transform": "none",
      "heading-family": "'PP Rader', Georgia, serif",
    },
    spacing: {
      scale: [4, 8, 16, 24, 32, 40, 56, 72, 96, 120],
      unit: "px",
      "button-px": "24px",
      "button-py": "12px",
      "button-px-sm": "16px",
      "button-py-sm": "8px",
      "button-px-lg": "32px",
      "button-py-lg": "16px",
      "card-padding": "36px",
      "card-padding-sm": "24px",
      "card-padding-lg": "48px",
      "input-px": "16px",
      "input-py": "12px",
      "badge-px": "12px",
      "badge-py": "4px",
      "section-py": "104px",
      "section-py-lg": "160px",
      "navbar-height": "72px",
      "navbar-px": "36px",
      "footer-py": "72px",
      "modal-padding": "32px",
      "popover-padding": "18px",
      "tooltip-padding": "8px 14px",
      "table-cell-px": "18px",
      "table-cell-py": "12px",
    },
    layout: {
      "content-max": "1200px",
      "content-max-narrow": "720px",
      "content-max-wide": "1440px",
      "page-margin": "40px",
      "page-margin-sm": "20px",
      "page-margin-lg": "72px",
      gutter: "40px",
      "gutter-sm": "16px",
      "gutter-lg": "56px",
      "grid-columns": "12",
      "grid-gap": "36px",
      "bento-gap": "24px",
      "bento-radius": "10px",
      "bento-min-height": "220px",
      "section-gap": "64px",
      "sidebar-width": "280px",
      "sidebar-collapsed": "64px",
      "footer-columns": "3",
      "stack-gap": "20px",
      "stack-gap-sm": "12px",
      "stack-gap-lg": "32px",
      "prose-max": "60ch",
    },
    sigil: {
      "grid-cell": "60px",
      "cross-arm": "12px",
      "cross-stroke": "1px",
      "rail-gap": "36px",
      "card-radius": "8px",
      "gutter-pattern": "brick",
      "margin-pattern": "horizontal",
    },
    radius: {
      none: "0px",
      sm: "4px",
      md: "6px",
      lg: "8px",
      xl: "10px",
      "2xl": "14px",
      full: "9999px",
      button: "6px",
      card: "8px",
      input: "6px",
      badge: "4px",
      modal: "10px",
      popover: "8px",
      tooltip: "6px",
      image: "6px",
      bento: "10px",
    },
    shadows: {
      sm: "0 1px 2px rgba(44, 37, 23, 0.04)",
      md: "0 1px 3px rgba(44, 37, 23, 0.06)",
      lg: "0 2px 6px rgba(44, 37, 23, 0.08)",
      xl: "0 4px 12px rgba(44, 37, 23, 0.1)",
      "2xl": "0 8px 20px rgba(44, 37, 23, 0.12)",
      glow: "0 0 20px rgba(180, 83, 9, 0.12)",
      "glow-sm": "0 0 10px rgba(180, 83, 9, 0.08)",
      colored: "0 2px 10px rgba(180, 83, 9, 0.1)",
      inner: "inset 0 1px 3px rgba(44, 37, 23, 0.06)",
      card: "0 1px 3px rgba(44, 37, 23, 0.05)",
      button: "none",
      "button-hover": "0 1px 4px rgba(44, 37, 23, 0.08)",
      dropdown: "0 4px 12px rgba(44, 37, 23, 0.1)",
      modal: "0 8px 30px rgba(44, 37, 23, 0.14)",
    },
    motion: {
      duration: {
        instant: "0ms",
        fast: "180ms",
        normal: "320ms",
        slow: "500ms",
        slower: "700ms",
        slowest: "1000ms",
      },
      easing: {
        default: "cubic-bezier(0.25, 0.1, 0.25, 1)",
        in: "cubic-bezier(0.42, 0, 1, 1)",
        out: "cubic-bezier(0, 0, 0.58, 1)",
        "in-out": "cubic-bezier(0.42, 0, 0.58, 1)",
        spring: "cubic-bezier(0.34, 1.3, 0.64, 1)",
        bounce: "cubic-bezier(0.34, 1.2, 0.64, 1)",
      },
      "enter-preset": "320ms cubic-bezier(0.25, 0.1, 0.25, 1)",
      "exit-preset": "240ms cubic-bezier(0.42, 0, 1, 1)",
      "hover-scale": "1",
      "press-scale": "0.98",
      "hover-lift": "-1px",
      "stagger-interval": "70ms",
      "stagger-interval-fast": "40ms",
    },
    borders: {
      width: { none: "0px", thin: "1px", medium: "1.5px", thick: "2px" },
      style: "solid",
      "card-border": "1px solid var(--s-border)",
      "card-border-hover": "1px solid var(--s-border)",
      "button-border": "1px solid var(--s-border)",
      "input-border": "1px solid var(--s-border)",
      "divider-style": "solid",
      "divider-width": "1px",
    },
    buttons: {
      "font-weight": "500",
      "text-transform": "none",
      "letter-spacing": "0.01em",
      "font-family": "'PP Writer', Georgia, serif",
      "border-width": "1px",
      "hover-effect": "darken",
      "active-scale": "0.98",
      "icon-gap": "10px",
      "min-width": "0px",
    },
    cards: {
      "border-style": "dashed",
      "border-width": "1px",
      "hover-effect": "border",
      "hover-border-color": "var(--s-border)",
      padding: "32px",
      "header-padding": "32px 32px 0",
      "footer-padding": "0 32px 32px",
      "title-size": "var(--s-size-xl)",
      "title-weight": "600",
      "description-size": "var(--s-size-base)",
      background: "surface",
      shadow: "none",
      outline: true,
      "outline-on-hover-only": false,
      "gap-between": "20px",
      "content-padding-x": "32px",
      "content-padding-y": "28px",
    },
    headings: {
      "h1-size": "3rem",
      "h1-weight": "600",
      "h1-tracking": "-0.015em",
      "h1-leading": "1.2",
      "h2-size": "2.25rem",
      "h2-weight": "600",
      "h2-tracking": "-0.01em",
      "h3-size": "1.625rem",
      "h3-weight": "600",
      "h4-size": "1.25rem",
      "h4-weight": "600",
      "display-size": "3.75rem",
      "display-weight": "600",
      "display-tracking": "-0.02em",
      "display-leading": "1.12",
    },
    navigation: {
      "navbar-height": "72px",
      "navbar-backdrop-blur": "12px",
      "navbar-border": "1px solid var(--s-border-muted)",
      "navbar-bg-opacity": "0.88",
      "nav-link-weight": "400",
      "nav-link-size": "var(--s-size-sm)",
      "nav-link-hover": "color",
      "breadcrumb-separator": "›",
      "pagination-radius": "6px",
      "sidebar-width": "280px",
      "sidebar-item-radius": "6px",
      "sidebar-item-padding": "12px 18px",
    },
    backgrounds: {
      pattern: "none",
      "pattern-opacity": "0",
      "pattern-scale": "0px",
      noise: true,
      "noise-opacity": "0.025",
      "gradient-angle": "180deg",
      "gradient-type": "none",
      "hero-pattern": "noise",
      "section-divider": "diagonal",
    },
    code: {
      "font-family": "'PP Supply Mono', ui-monospace, monospace",
      "font-size": "0.875rem",
      "line-height": "1.7",
      bg: "#ede8df",
      border: "1px solid #d5cdc0",
      "border-radius": "6px",
      padding: "24px 28px",
      "tab-size": "2",
      "selection-bg": "rgba(180, 83, 9, 0.12)",
      "comment-color": "#8a8274",
      "keyword-color": "#b45309",
      "string-color": "#3f6212",
      "number-color": "#991b1b",
      "function-color": "#1e4d8c",
    },
    inputs: {
      height: "44px",
      "height-sm": "36px",
      "height-lg": "52px",
      "border-width": "1px",
      "focus-ring-width": "2px",
      "focus-ring-color": "var(--s-primary)",
      "focus-ring-offset": "2px",
      "placeholder-color": "var(--s-text-muted)",
      "error-border-color": "var(--s-error)",
      "label-size": "var(--s-size-sm)",
      "label-weight": "500",
      "label-spacing": "8px",
      "helper-size": "var(--s-size-xs)",
    },
    alignment: {
      "title-align": "center",
    },
    sections: {
      "rail-margin": "48px",
      "padding-y": "80px",
      "padding-y-hero": "140px",
      gap: "40px",
      "max-width": "900px",
      indent: "24px",
    },
    dividers: {
      style: "dashed",
      width: "1px",
      ornament: "diamond",
    },
    gridVisuals: {
      "line-color": "var(--s-border-muted)",
      "line-width": "1px",
      "show-lines": false,
      "show-dots": false,
    },
    cursor: {
      variant: "dot",
      size: "24px",
      "dot-size": "4px",
      "stroke-width": "1.5px",
      "tick-size": "6px",
      gap: "3px",
      radius: "0px",
      color: "var(--s-text)",
      "ring-color": "var(--s-primary)",
      "dot-color": "var(--s-primary)",
      glow: "none",
      opacity: "1",
      "blend-mode": "normal",
      "z-index": "9999",
      "hide-native": false,
    },
    scrollbar: {
      width: "6px",
      height: "6px",
      padding: "2px",
      radius: "9999px",
      track: "transparent",
      thumb: "var(--s-border-muted)",
      "thumb-hover": "var(--s-border)",
      "thumb-active": "var(--s-border-strong)",
      corner: "transparent",
      border: "none",
      "firefox-width": "thin",
      gutter: "stable",
      visibility: "auto",
    },
    focus: {
      "ring-width": "1.5px",
      "ring-color": "var(--s-primary)",
      "ring-offset": "2px",
      "ring-shadow": "0 0 0 1.5px var(--s-primary)",
      "outline-color": "var(--s-primary)",
    },
    overlays: {
      bg: "rgb(0 0 0 / 0.4)",
      blur: "4px",
      surface: "var(--s-surface-elevated)",
      border: "1px solid var(--s-border-muted)",
      shadow: "var(--s-shadow-xl)",
      radius: "var(--s-radius-lg)",
      padding: "20px",
      "z-index": "50",
    },
    dataViz: {
      "series-1": "var(--s-primary)",
      "series-2": "var(--s-secondary)",
      "series-3": "var(--s-accent)",
      "series-4": "var(--s-info)",
      "series-5": "var(--s-success)",
      positive: "var(--s-success)",
      negative: "var(--s-error)",
      neutral: "var(--s-text-muted)",
      grid: "var(--s-border-muted)",
      axis: "var(--s-border)",
      label: "var(--s-text-secondary)",
      "tooltip-bg": "var(--s-surface-elevated)",
      "tooltip-border": "var(--s-border-muted)",
    },
    media: {
      radius: "var(--s-radius-md)",
      border: "none",
      outline: "1px solid rgb(0 0 0 / 0.08)",
      shadow: "none",
      bg: "var(--s-surface-sunken)",
      "object-fit": "cover",
    },
    controls: {
      height: "38px",
      "height-sm": "30px",
      "height-lg": "46px",
      "hit-area": "44px",
      "icon-size": "16px",
      "handle-size": "20px",
      "track-height": "4px",
      "track-bg": "var(--s-border-muted)",
      "track-fill": "var(--s-primary)",
      "thumb-bg": "var(--s-surface-elevated)",
      "thumb-border": "2px solid var(--s-primary)",
    },
    componentSurfaces: {
      bg: "var(--s-surface)",
      "bg-elevated": "var(--s-surface-elevated)",
      "bg-muted": "var(--s-surface-sunken)",
      border: "var(--s-border)",
      "border-muted": "var(--s-border-muted)",
      "border-strong": "var(--s-border-strong)",
      text: "var(--s-text)",
      "text-muted": "var(--s-text-muted)",
      contrast: "var(--s-primary-contrast)",
      "hover-bg": "var(--s-surface-elevated)",
      "active-bg": "var(--s-surface-sunken)",
      "selected-bg": "var(--s-primary-muted)",
    },

  },
};
