import type { SigilPreset } from "@sigil-ui/tokens";

export const sagePreset: SigilPreset = {
  name: "sage",
  metadata: {
    description: "Botanical sage-green surfaces with forest depth. Tinted backgrounds in both modes, classic serif headings, calm natural palette.",
    mood: "botanical, calm, natural",
    tags: ["edgeless", "green", "botanical", "serif", "colorful-bg"],
  },
  tokens: {
    colors: {
      background: { light: "oklch(0.94 0.025 155)", dark: "oklch(0.14 0.03 155)" },
      surface: { light: "oklch(0.92 0.03 155)", dark: "oklch(0.18 0.035 155)" },
      "surface-elevated": { light: "oklch(0.96 0.02 155)", dark: "oklch(0.22 0.03 155)" },
      "surface-sunken": { light: "oklch(0.89 0.035 155)", dark: "oklch(0.11 0.025 155)" },
      primary: { light: "oklch(0.48 0.12 155)", dark: "oklch(0.65 0.12 155)" },
      "primary-hover": { light: "oklch(0.42 0.14 155)", dark: "oklch(0.72 0.10 155)" },
      "primary-muted": { light: "oklch(0.48 0.04 155)", dark: "oklch(0.65 0.04 155)" },
      "primary-contrast": { light: "oklch(0.98 0.01 155)", dark: "oklch(0.14 0.03 155)" },
      secondary: "oklch(0.52 0.08 120)",
      "secondary-hover": "oklch(0.46 0.10 120)",
      "secondary-muted": "oklch(0.52 0.03 120)",
      accent: "oklch(0.58 0.10 90)",
      "accent-hover": "oklch(0.52 0.12 90)",
      "accent-muted": "oklch(0.58 0.04 90)",
      text: { light: "oklch(0.20 0.025 155)", dark: "oklch(0.90 0.02 155)" },
      "text-secondary": { light: "oklch(0.36 0.02 155)", dark: "oklch(0.72 0.018 155)" },
      "text-muted": { light: "oklch(0.50 0.018 155)", dark: "oklch(0.54 0.018 155)" },
      "text-subtle": { light: "oklch(0.62 0.015 155)", dark: "oklch(0.42 0.015 155)" },
      "text-disabled": { light: "oklch(0.74 0.012 155)", dark: "oklch(0.30 0.012 155)" },
      "text-inverse": { light: "oklch(0.90 0.02 155)", dark: "oklch(0.20 0.025 155)" },
      border: { light: "oklch(0.84 0.025 155)", dark: "oklch(0.320 0.028 155)" },
      "border-muted": { light: "oklch(0.90 0.018 155)", dark: "oklch(0.260 0.022 155)" },
      "border-strong": { light: "oklch(0.74 0.035 155)", dark: "oklch(0.400 0.035 155)" },
      "border-interactive": { light: "oklch(0.48 0.12 155)", dark: "oklch(0.65 0.12 155)" },
      success: "oklch(0.62 0.16 155)",
      "success-muted": { light: "oklch(0.92 0.04 155)", dark: "oklch(0.18 0.04 155)" },
      warning: "oklch(0.72 0.14 80)",
      "warning-muted": { light: "oklch(0.93 0.04 80)", dark: "oklch(0.20 0.04 80)" },
      error: "oklch(0.55 0.18 25)",
      "error-muted": { light: "oklch(0.93 0.04 25)", dark: "oklch(0.20 0.04 25)" },
      info: "oklch(0.60 0.13 245)",
      "info-muted": { light: "oklch(0.93 0.03 245)", dark: "oklch(0.20 0.03 245)" },
      "gradient-start": { light: "oklch(0.48 0.12 155)", dark: "oklch(0.65 0.12 155)" },
      "gradient-end": { light: "oklch(0.52 0.08 120)", dark: "oklch(0.55 0.08 120)" },
      glow: { light: "oklch(0.48 0.12 155 / 0.12)", dark: "oklch(0.65 0.12 155 / 0.10)" },
      highlight: { light: "oklch(0.92 0.06 155)", dark: "oklch(0.28 0.05 155)" },
    },
    typography: {
      "font-display": "'Libre Baskerville', Georgia, serif",
      "font-body": "'Source Sans 3', system-ui, sans-serif",
      "font-mono": "'Fira Code', ui-monospace, monospace",
      "size-xs": "0.75rem",
      "size-sm": "0.875rem",
      "size-base": "1rem",
      "size-lg": "1.125rem",
      "size-xl": "1.25rem",
      "size-2xl": "1.5rem",
      "size-3xl": "1.875rem",
      "size-4xl": "2.25rem",
      "size-5xl": "3rem",
      "size-6xl": "3.75rem",
      "weight-normal": "400",
      "weight-medium": "500",
      "weight-semibold": "600",
      "weight-bold": "700",
      "weight-extrabold": "800",
      "leading-tight": "1.25",
      "leading-normal": "1.6",
      "leading-relaxed": "1.75",
      "leading-loose": "2",
      "tracking-tighter": "-0.03em",
      "tracking-tight": "-0.015em",
      "tracking-normal": "0em",
      "tracking-wide": "0.02em",
      "tracking-wider": "0.04em",
      "heading-weight": "700",
      "heading-tracking": "-0.01em",
      "heading-transform": "none",
      "heading-family": "'Libre Baskerville', Georgia, serif",
    },
    spacing: {
      scale: [4, 8, 12, 16, 24, 32, 48, 64, 96, 128],
      unit: "px",
      "button-px": "22px",
      "button-py": "10px",
      "button-px-sm": "14px",
      "button-py-sm": "7px",
      "button-px-lg": "28px",
      "button-py-lg": "13px",
      "card-padding": "24px",
      "card-padding-sm": "16px",
      "card-padding-lg": "36px",
      "input-px": "12px",
      "input-py": "9px",
      "badge-px": "10px",
      "badge-py": "3px",
      "section-py": "90px",
      "section-py-lg": "120px",
      "navbar-height": "60px",
      "navbar-px": "28px",
      "footer-py": "60px",
      "modal-padding": "28px",
      "popover-padding": "14px",
      "tooltip-padding": "6px 12px",
      "table-cell-px": "14px",
      "table-cell-py": "12px",
    },
    layout: {
      "content-max": "1020px",
      "content-max-narrow": "640px",
      "content-max-wide": "1260px",
      "page-margin": "28px",
      "page-margin-sm": "16px",
      "page-margin-lg": "56px",
      gutter: "0px",
      "gutter-sm": "0px",
      "gutter-lg": "0px",
      "grid-columns": "12",
      "grid-gap": "24px",
      "bento-gap": "18px",
      "bento-radius": "6px",
      "bento-min-height": "210px",
      "section-gap": "30px",
      "sidebar-width": "240px",
      "sidebar-collapsed": "52px",
      "footer-columns": "4",
      "stack-gap": "16px",
      "stack-gap-sm": "10px",
      "stack-gap-lg": "24px",
      "prose-max": "60ch",
    },
    sigil: {
      "grid-cell": "60px",
      "cross-arm": "0px",
      "cross-stroke": "0px",
      "rail-gap": "0px",
      "card-radius": "6px",
      "gutter-pattern": "none",
      "margin-pattern": "none",
      "gutter-border": "none",
      "gutter-visible": false,
    },
    radius: {
      none: "0px",
      sm: "3px",
      md: "6px",
      lg: "8px",
      xl: "12px",
      "2xl": "18px",
      full: "9999px",
      button: "6px",
      card: "6px",
      input: "6px",
      badge: "9999px",
      modal: "10px",
      popover: "8px",
      tooltip: "4px",
      image: "6px",
      bento: "6px",
    },
    shadows: {
      sm: "0 1px 3px 0 oklch(0.25 0.03 155 / 0.06)",
      md: "0 2px 6px -1px oklch(0.25 0.03 155 / 0.08), 0 1px 3px 0 oklch(0.25 0.03 155 / 0.04)",
      lg: "0 4px 12px -2px oklch(0.25 0.03 155 / 0.10), 0 2px 4px 0 oklch(0.25 0.03 155 / 0.04)",
      xl: "0 8px 24px -4px oklch(0.25 0.03 155 / 0.12), 0 4px 8px -2px oklch(0.25 0.03 155 / 0.05)",
      "2xl": "0 16px 48px -8px oklch(0.25 0.03 155 / 0.14)",
      glow: "0 0 20px oklch(0.48 0.12 155 / 0.12)",
      "glow-sm": "0 0 10px oklch(0.48 0.12 155 / 0.08)",
      colored: "0 4px 14px -4px oklch(0.48 0.12 155 / 0.18)",
      inner: "inset 0 2px 4px 0 oklch(0.25 0.03 155 / 0.05)",
      card: "0 1px 4px 0 oklch(0.25 0.03 155 / 0.05)",
      button: "0 1px 2px 0 oklch(0.25 0.03 155 / 0.05)",
      "button-hover": "0 2px 6px -1px oklch(0.25 0.03 155 / 0.08)",
      dropdown: "0 4px 12px -2px oklch(0.25 0.03 155 / 0.10)",
      modal: "0 20px 40px -8px oklch(0.25 0.03 155 / 0.16)",
    },
    motion: {
      duration: { instant: "0ms", fast: "120ms", normal: "220ms", slow: "360ms", slower: "520ms", slowest: "780ms" },
      easing: {
        default: "cubic-bezier(0.22, 1, 0.36, 1)",
        in: "cubic-bezier(0.55, 0, 1, 0.45)",
        out: "cubic-bezier(0, 0.55, 0.45, 1)",
        "in-out": "cubic-bezier(0.45, 0, 0.55, 1)",
        spring: "cubic-bezier(0.34, 1.56, 0.64, 1)",
      },
      "hover-scale": "1.0",
      "press-scale": "0.98",
      "hover-lift": "-1px",
      "stagger-interval": "50ms",
      "stagger-interval-fast": "28ms",
    },
    borders: {
      width: { none: "0px", thin: "1px", medium: "1.5px", thick: "2px" },
      style: "solid",
      "card-border": "1px solid",
      "card-border-hover": "1px solid",
      "button-border": "1px solid",
      "input-border": "1px solid",
      "divider-style": "solid",
      "divider-width": "1px",
    },
    buttons: {
      "font-weight": "500",
      "text-transform": "none",
      "letter-spacing": "0.01em",
      "font-family": "'Source Sans 3', system-ui, sans-serif",
      "border-width": "1px",
      "hover-effect": "darken",
      "active-scale": "0.98",
      "icon-gap": "8px",
      "min-width": "0px",
    },
    cards: {
      "border-style": "solid",
      "border-width": "1px",
      "hover-effect": "border",
      "hover-border-color": "var(--s-border-strong)",
      padding: "24px",
      "header-padding": "24px 24px 0",
      "footer-padding": "0 24px 24px",
      "title-size": "1.0625rem",
      "title-weight": "600",
      "description-size": "0.9375rem",
      background: "surface",
      shadow: "sm",
      outline: true,
      "outline-on-hover-only": false,
      "gap-between": "16px",
      "content-padding-x": "24px",
      "content-padding-y": "20px",
    },
    headings: {
      "h1-size": "2.25rem",
      "h1-weight": "700",
      "h1-tracking": "-0.015em",
      "h1-leading": "1.2",
      "h2-size": "1.875rem",
      "h2-weight": "700",
      "h2-tracking": "-0.01em",
      "h2-leading": "1.15",
      "h3-size": "1.375rem",
      "h3-weight": "600",
      "h3-tracking": "0em",
      "h3-leading": "1.2",
      "h4-size": "1.125rem",
      "h4-weight": "600",
      "h4-tracking": "0em",
      "h4-leading": "1.3",
      "display-size": "3.5rem",
      "display-weight": "700",
      "display-tracking": "-0.025em",
      "display-leading": "1.1",
    },
    navigation: {
      "navbar-height": "60px",
      "navbar-backdrop-blur": "12px",
      "navbar-border": "none",
      "navbar-bg-opacity": "0.90",
      "navbar-padding-x": "28px",
      "navbar-position": "sticky",
      "navbar-logo-height": "26px",
      "navbar-logo-gap": "10px",
      "navbar-item-gap": "28px",
      "navbar-item-padding-x": "14px",
      "navbar-item-padding-y": "8px",
      "navbar-item-size": "0.875rem",
      "navbar-shadow": "none",
      "navbar-height-scrolled": "52px",
      "navbar-mobile-breakpoint": "768px",
      "nav-link-weight": "400",
      "nav-link-size": "0.9375rem",
      "nav-link-hover": "color",
      "breadcrumb-separator": "/",
      "pagination-radius": "6px",
      "sidebar-width": "240px",
      "sidebar-item-radius": "6px",
      "sidebar-item-padding": "8px 12px",
    },
    backgrounds: {
      pattern: "none",
      "pattern-opacity": "0",
      "pattern-scale": "1",
      noise: true,
      "noise-opacity": "0.018",
      "gradient-angle": "180deg",
      "gradient-type": "none",
      "hero-pattern": "noise",
      "section-divider": "none",
    },
    code: {
      "font-family": "'Fira Code', ui-monospace, monospace",
      "font-size": "0.875rem",
      "line-height": "1.7",
      bg: "var(--s-surface-sunken)",
      border: "1px solid var(--s-border-muted)",
      "border-radius": "6px",
      padding: "18px",
      "tab-size": "2",
      "selection-bg": "var(--s-primary-muted)",
      "comment-color": "var(--s-text-muted)",
      "keyword-color": "oklch(0.48 0.12 155)",
      "string-color": "oklch(0.58 0.10 90)",
      "number-color": "oklch(0.72 0.14 80)",
      "function-color": "oklch(0.55 0.14 265)",
    },
    inputs: {
      height: "40px",
      "height-sm": "34px",
      "height-lg": "48px",
      "border-width": "1px",
      "focus-ring-width": "2px",
      "focus-ring-color": "var(--s-primary)",
      "focus-ring-offset": "2px",
      "placeholder-color": "var(--s-text-subtle)",
      "error-border-color": "var(--s-error)",
      "label-size": "0.875rem",
      "label-weight": "500",
      "label-spacing": "6px",
      "helper-size": "0.8125rem",
    },
    alignment: {
      "rail-width": "1020px",
      "rail-columns": "12",
      "rail-gutter": "0px",
      "rail-margin": "28px",
      "rail-visible": false,
      "rail-color": "var(--s-border-muted)",
      "content-align": "center",
      "hero-align": "center",
      "section-align": "center",
      "navbar-align": "full",
      "footer-align": "full",
    },
    sections: {
      "padding-y": "90px",
      "padding-y-hero": "120px",
      "padding-y-sm": "48px",
      "padding-x": "28px",
      "max-width": "1020px",
      gap: "40px",
      "padding-y-lg": "104px",
      "padding-y-xl": "152px",
      "title-align": "center",
      "heading-size": "clamp(1.5rem, 4vw, 2.5rem)",
      "heading-align": "center",
      "heading-max-width": "40rem",
      "heading-margin-bottom": "16px",
      "description-max-width": "32rem",
      "description-gap": "14px",
      "content-gap": "28px",
      "grid-columns": "3",
      "grid-gap": "28px",
      "alternate-bg": "var(--s-surface)",
      "alternate-bg-mode": "surface",
      "divider-above": false,
      "divider-below": false,
      "background-alt": false,
      indent: "0px",
    },
    dividers: {
      style: "none",
      width: "0px",
      color: "var(--s-border-muted)",
      spacing: "0px",
      opacity: "0.4",
      "max-width": "100%",
      "margin-y": "0px",
      thickness: "1px",
      "gradient-start": "transparent",
      "gradient-end": "transparent",
      "show-cross": false,
      "show-label": false,
      "full-bleed": false,
      ornament: "none",
    },
    gridVisuals: {
      "show-lines": false,
      "line-color": "var(--s-border-muted)",
      "line-width": "1px",
      "show-dots": false,
      "dot-size": "2px",
      "cell-background": "none",
      "cell-border": false,
      "cell-radius": "6px",
      "cell-padding": "18px",
      "hover-effect": "border",
    },
    cursor: {
      variant: "dot",
      size: "24px",
      "dot-size": "4px",
      "stroke-width": "1.5px",
      "tick-size": "6px",
      gap: "3px",
      radius: "0px",
      color: "var(--s-text)",
      "ring-color": "var(--s-primary)",
      "dot-color": "var(--s-primary)",
      glow: "none",
      opacity: "1",
      "blend-mode": "normal",
      "z-index": "9999",
      "hide-native": false,
    },
    scrollbar: {
      width: "8px",
      height: "8px",
      padding: "2px",
      radius: "9999px",
      track: "transparent",
      thumb: "var(--s-border-muted)",
      "thumb-hover": "var(--s-border)",
      "thumb-active": "var(--s-border-strong)",
      corner: "transparent",
      border: "none",
      "firefox-width": "thin",
      gutter: "stable",
      visibility: "auto",
    },
    focus: {
      "ring-width": "2px",
      "ring-color": "var(--s-primary)",
      "ring-offset": "2px",
      "ring-shadow": "0 0 0 2px var(--s-primary)",
      "outline-color": "var(--s-primary)",
    },
    overlays: {
      bg: "rgb(0 0 0 / 0.5)",
      blur: "8px",
      surface: "var(--s-surface-elevated)",
      border: "1px solid var(--s-border-muted)",
      shadow: "var(--s-shadow-xl)",
      radius: "var(--s-radius-lg)",
      padding: "20px",
      "z-index": "50",
    },
    dataViz: {
      "series-1": "var(--s-primary)",
      "series-2": "var(--s-secondary)",
      "series-3": "var(--s-accent)",
      "series-4": "var(--s-info)",
      "series-5": "var(--s-success)",
      positive: "var(--s-success)",
      negative: "var(--s-error)",
      neutral: "var(--s-text-muted)",
      grid: "var(--s-border-muted)",
      axis: "var(--s-border)",
      label: "var(--s-text-secondary)",
      "tooltip-bg": "var(--s-surface-elevated)",
      "tooltip-border": "var(--s-border-muted)",
    },
    media: {
      radius: "var(--s-radius-md)",
      border: "none",
      outline: "1px solid rgb(0 0 0 / 0.08)",
      shadow: "none",
      bg: "var(--s-surface-sunken)",
      "object-fit": "cover",
    },
    controls: {
      height: "38px",
      "height-sm": "30px",
      "height-lg": "46px",
      "hit-area": "44px",
      "icon-size": "16px",
      "handle-size": "20px",
      "track-height": "4px",
      "track-bg": "var(--s-border-muted)",
      "track-fill": "var(--s-primary)",
      "thumb-bg": "var(--s-surface-elevated)",
      "thumb-border": "2px solid var(--s-primary)",
    },
    componentSurfaces: {
      bg: "var(--s-surface)",
      "bg-elevated": "var(--s-surface-elevated)",
      "bg-muted": "var(--s-surface-sunken)",
      border: "var(--s-border)",
      "border-muted": "var(--s-border-muted)",
      "border-strong": "var(--s-border-strong)",
      text: "var(--s-text)",
      "text-muted": "var(--s-text-muted)",
      contrast: "var(--s-primary-contrast)",
      "hover-bg": "var(--s-surface-elevated)",
      "active-bg": "var(--s-surface-sunken)",
      "selected-bg": "var(--s-primary-muted)",
    },
    hero: {
      "min-height": "auto",
      "padding-y": "120px",
      "padding-y-sm": "60px",
      "padding-x": "var(--s-page-margin, 28px)",
      "content-max": "640px",
      "content-align": "center",
      layout: "centered",
      "media-position": "below",
      "media-width": "50%",
      "media-radius": "var(--s-radius-2xl)",
      "title-size": "clamp(2.5rem, 6vw, 4.5rem)",
      "title-max-width": "56rem",
      "description-size": "1.1875rem",
      "description-max-width": "34rem",
      "description-gap": "28px",
      "actions-gap": "14px",
      "actions-margin-top": "36px",
      "action-padding-x": "28px",
      "action-padding-y": "14px",
      "badge-gap": "28px",
      "overlay-opacity": "0.3",
      "scroll-indicator": false,
      "gradient-overlay": "none",
    },
    cta: {
      "padding-y": "90px",
      "padding-x": "var(--s-page-margin, 28px)",
      "max-width": "var(--s-content-max, 1200px)",
      layout: "centered",
      border: false,
      "border-radius": "var(--s-radius-2xl)",
      bg: "var(--s-surface)",
      "title-size": "clamp(1.5rem, 4vw, 2.5rem)",
      "description-max-width": "34rem",
      "description-gap": "14px",
      "actions-gap": "14px",
      "actions-margin-top": "36px",
      "action-padding-x": "28px",
      "action-padding-y": "14px",
      "split-gap": "60px",
    },
    footer: {
      "padding-y": "60px",
      "border-top": "1px solid var(--s-border-muted)",
      columns: "4",
      "column-gap": "36px",
      "row-gap": "32px",
      "logo-height": "24px",
      "tagline-max-width": "22rem",
      "link-size": "0.875rem",
      "link-gap": "10px",
      "group-title-size": "0.8125rem",
      "group-title-weight": "500",
      "social-icon-size": "20px",
      "social-gap": "14px",
      "bottom-bar-padding": "30px 0",
      "bottom-bar-border": "1px solid var(--s-border-muted)",
    },
    banner: {
      height: "auto",
      "padding-y": "10px",
      "padding-x": "20px",
      "font-size": "0.875rem",
      "font-weight": "400",
      "icon-size": "16px",
      "icon-gap": "12px",
      "border-width": "1px",
      "border-position": "bottom",
      position: "top",
      "dismiss-size": "16px",
      radius: "0px",
    },
    pageRhythm: {
      density: "spacious",
      "section-gap": "0px",
      "section-gap-sm": "0px",
      "section-gap-lg": "0px",
      "first-section-offset": "0px",
      "last-section-margin": "0px",
      "alternate-bg": true,
      "alternate-bg-color": "var(--s-surface)",
      "divider-between": false,
      "max-content-width": "var(--s-content-max, 1200px)",
      "vertical-rhythm-unit": "10px",
      "scroll-snap": false,
      "responsive-scale": "0.85",
      "responsive-breakpoint": "768px",
    },
  },
};
