import type { SigilPreset } from "@sigil-ui/tokens";

export const shardPreset: SigilPreset = {
  name: "shard",
  metadata: {
    description: "Broken glass — angular, fragmented, aggressive geometry",
    author: "sigil-ui",
    version: "0.1.0",
    tags: ["aggressive", "angular", "fragmented", "sharp"],
    mood: "angular, aggressive, fragmented",
    inspiration: "Shattered glass, deconstructivism, glitch art",
  },
  tokens: {
    colors: {
      background: { light: "#fafafa", dark: "#0a0a0a" },
      surface: { light: "#f4f4f5", dark: "#141414" },
      "surface-elevated": { light: "#ffffff", dark: "#1c1c1c" },
      "surface-sunken": { light: "#e4e4e7", dark: "#050505" },
      text: { light: "#09090b", dark: "#fafafa" },
      "text-secondary": { light: "#27272a", dark: "#d4d4d8" },
      "text-muted": { light: "#52525b", dark: "#a1a1aa" },
      "text-subtle": { light: "#71717a", dark: "#71717a" },
      "text-disabled": { light: "#a1a1aa", dark: "#3f3f46" },
      "text-inverse": { light: "#fafafa", dark: "#09090b" },
      border: { light: "#d4d4d8", dark: "#27272a" },
      "border-muted": { light: "#e4e4e7", dark: "#1c1c1c" },
      "border-strong": { light: "#71717a", dark: "#52525b" },
      "border-interactive": { light: "#7c3aed", dark: "#a78bfa" },
      primary: "#7c3aed",
      "primary-hover": "#6d28d9",
      "primary-muted": "#ede9fe",
      "primary-contrast": "#ffffff",
      secondary: "#18181b",
      "secondary-hover": "#09090b",
      "secondary-muted": "#f4f4f5",
      accent: "#ec4899",
      "accent-hover": "#db2777",
      "accent-muted": "#fce7f3",
      success: "#16a34a",
      "success-muted": "#dcfce7",
      warning: "#d97706",
      "warning-muted": "#fef3c7",
      error: "#dc2626",
      "error-muted": "#fee2e2",
      info: "#2563eb",
      "info-muted": "#dbeafe",
      "gradient-start": "#7c3aed",
      "gradient-end": "#ec4899",
      glow: "rgba(124, 58, 237, 0.25)",
    },
    typography: {
      "font-display": '"Archivo", system-ui, sans-serif',
      "font-body": '"Archivo", system-ui, sans-serif',
      "font-mono": '"Fira Code", ui-monospace, monospace',
      "size-xs": "0.75rem",
      "size-sm": "0.8125rem",
      "size-base": "0.9375rem",
      "size-lg": "1.0625rem",
      "size-xl": "1.25rem",
      "size-2xl": "1.5rem",
      "size-3xl": "1.875rem",
      "size-4xl": "2.25rem",
      "size-5xl": "3rem",
      "size-6xl": "3.75rem",
      "weight-normal": "400",
      "weight-medium": "500",
      "weight-semibold": "600",
      "weight-bold": "700",
      "weight-extrabold": "800",
      "leading-tight": "1.1",
      "leading-normal": "1.45",
      "leading-relaxed": "1.6",
      "leading-loose": "1.75",
      "tracking-tighter": "-0.04em",
      "tracking-tight": "-0.02em",
      "tracking-normal": "0em",
      "tracking-wide": "0.05em",
      "tracking-wider": "0.1em",
      "heading-weight": "800",
      "heading-tracking": "-0.03em",
      "heading-transform": "uppercase",
      "heading-family": '"Archivo", system-ui, sans-serif',
    },
    spacing: {
      scale: [2, 4, 8, 12, 16, 20, 28, 40, 56, 72],
      unit: "px",
      "button-px": "20px",
      "button-py": "10px",
      "button-px-sm": "14px",
      "button-py-sm": "6px",
      "button-px-lg": "28px",
      "button-py-lg": "14px",
      "card-padding": "16px",
      "card-padding-sm": "12px",
      "card-padding-lg": "24px",
      "input-px": "12px",
      "input-py": "8px",
      "badge-px": "8px",
      "badge-py": "2px",
      "section-py": "56px",
      "section-py-lg": "88px",
      "navbar-height": "52px",
      "navbar-px": "20px",
      "footer-py": "40px",
      "modal-padding": "20px",
      "popover-padding": "12px",
      "tooltip-padding": "6px 10px",
      "table-cell-px": "12px",
      "table-cell-py": "8px",
    },
    layout: {
      "content-max": "1200px",
      "content-max-narrow": "680px",
      "content-max-wide": "1440px",
      "page-margin": "20px",
      "page-margin-sm": "12px",
      "page-margin-lg": "40px",
      gutter: "16px",
      "gutter-sm": "8px",
      "gutter-lg": "24px",
      "grid-columns": "12",
      "grid-gap": "16px",
      "bento-gap": "8px",
      "bento-radius": "0px",
      "bento-min-height": "180px",
      "section-gap": "40px",
      "sidebar-width": "240px",
      "sidebar-collapsed": "52px",
      "footer-columns": "4",
      "stack-gap": "12px",
      "stack-gap-sm": "6px",
      "stack-gap-lg": "20px",
      "prose-max": "62ch",
    },
    sigil: {
      "grid-cell": "44px",
      "cross-arm": "10px",
      "cross-stroke": "1.5px",
      "rail-gap": "16px",
      "card-radius": "0px",
    },
    radius: {
      none: "0px",
      sm: "0px",
      md: "0px",
      lg: "0px",
      xl: "0px",
      "2xl": "0px",
      full: "0px",
      button: "0px",
      card: "0px",
      input: "0px",
      badge: "0px",
      modal: "0px",
      popover: "0px",
      tooltip: "0px",
      image: "0px",
      bento: "0px",
    },
    shadows: {
      sm: "0 1px 2px rgba(0, 0, 0, 0.05)",
      md: "0 2px 4px rgba(0, 0, 0, 0.08)",
      lg: "0 4px 8px rgba(0, 0, 0, 0.1)",
      xl: "0 8px 16px rgba(0, 0, 0, 0.12)",
      "2xl": "0 16px 32px rgba(0, 0, 0, 0.15)",
      glow: "0 0 20px rgba(124, 58, 237, 0.3)",
      "glow-sm": "0 0 10px rgba(124, 58, 237, 0.2)",
      colored: "0 4px 12px rgba(124, 58, 237, 0.15)",
      inner: "inset 0 2px 4px rgba(0, 0, 0, 0.08)",
      card: "none",
      button: "none",
      "button-hover": "0 0 12px rgba(124, 58, 237, 0.2)",
      dropdown: "0 4px 12px rgba(0, 0, 0, 0.12)",
      modal: "0 16px 48px rgba(0, 0, 0, 0.2)",
    },
    motion: {
      duration: {
        instant: "0ms",
        fast: "80ms",
        normal: "150ms",
        slow: "250ms",
        slower: "380ms",
        slowest: "500ms",
      },
      easing: {
        default: "cubic-bezier(0.22, 0.68, 0, 1)",
        in: "cubic-bezier(0.6, 0, 1, 0.6)",
        out: "cubic-bezier(0, 0.4, 0.4, 1)",
        "in-out": "cubic-bezier(0.6, 0, 0.4, 1)",
        spring: "cubic-bezier(0.22, 1.4, 0.36, 1)",
        bounce: "cubic-bezier(0.22, 1.6, 0.36, 1)",
      },
      "enter-preset": "150ms cubic-bezier(0.22, 0.68, 0, 1)",
      "exit-preset": "100ms cubic-bezier(0.6, 0, 1, 0.6)",
      "hover-scale": "1.02",
      "press-scale": "0.96",
      "hover-lift": "-2px",
      "stagger-interval": "35ms",
      "stagger-interval-fast": "15ms",
    },
    borders: {
      width: { none: "0px", thin: "1px", medium: "1.5px", thick: "2px" },
      style: "solid",
      "card-border": "1px solid var(--s-border)",
      "card-border-hover": "1px solid var(--s-primary)",
      "button-border": "0px solid transparent",
      "input-border": "1px solid var(--s-border)",
      "divider-style": "solid",
      "divider-width": "1px",
    },
    buttons: {
      "font-weight": "800",
      "text-transform": "uppercase",
      "letter-spacing": "0.08em",
      "font-family": "var(--s-font-body)",
      "border-width": "0px",
      "hover-effect": "fill",
      "active-scale": "0.96",
      "icon-gap": "8px",
      "min-width": "0px",
    },
    cards: {
      "border-style": "solid",
      "border-width": "1.5px",
      "hover-effect": "border",
      "hover-border-color": "var(--s-primary)",
      padding: "16px",
      "header-padding": "16px 16px 0",
      "footer-padding": "0 16px 16px",
      "title-size": "var(--s-size-lg)",
      "title-weight": "700",
      "description-size": "var(--s-size-sm)",
      background: "surface",
      shadow: "none",
      outline: true,
      "outline-on-hover-only": false,
      "gap-between": "12px",
      "content-padding-x": "16px",
      "content-padding-y": "14px",
    },
    headings: {
      "h1-size": "3rem",
      "h1-weight": "800",
      "h1-tracking": "-0.04em",
      "h1-leading": "1.05",
      "h2-size": "2.25rem",
      "h2-weight": "800",
      "h2-tracking": "-0.03em",
      "h3-size": "1.5rem",
      "h3-weight": "700",
      "h4-size": "1.125rem",
      "h4-weight": "700",
      "display-size": "4rem",
      "display-weight": "800",
      "display-tracking": "-0.05em",
      "display-leading": "0.95",
    },
    navigation: {
      "navbar-height": "52px",
      "navbar-backdrop-blur": "8px",
      "navbar-border": "1px solid var(--s-border-muted)",
      "navbar-bg-opacity": "0.92",
      "nav-link-weight": "600",
      "nav-link-size": "var(--s-size-sm)",
      "nav-link-hover": "color",
      "breadcrumb-separator": "//",
      "pagination-radius": "0px",
      "sidebar-width": "240px",
      "sidebar-item-radius": "0px",
      "sidebar-item-padding": "8px 12px",
    },
    backgrounds: {
      pattern: "diagonal",
      "pattern-opacity": "0.03",
      "pattern-scale": "8px",
      noise: false,
      "noise-opacity": "0",
      "gradient-angle": "135deg",
      "gradient-type": "linear",
      "hero-pattern": "crosshatch",
      "section-divider": "diagonal",
    },
    code: {
      "font-family": '"Fira Code", ui-monospace, monospace',
      "font-size": "0.8125rem",
      "line-height": "1.55",
      bg: "#f4f4f5",
      border: "1px solid #d4d4d8",
      "border-radius": "0px",
      padding: "16px 20px",
      "tab-size": "2",
      "selection-bg": "rgba(124, 58, 237, 0.15)",
      "comment-color": "#71717a",
      "keyword-color": "#7c3aed",
      "string-color": "#16a34a",
      "number-color": "#ec4899",
      "function-color": "#2563eb",
    },
    inputs: {
      height: "38px",
      "height-sm": "30px",
      "height-lg": "46px",
      "border-width": "1px",
      "focus-ring-width": "2px",
      "focus-ring-color": "var(--s-primary)",
      "focus-ring-offset": "0px",
      "placeholder-color": "var(--s-text-muted)",
      "error-border-color": "var(--s-error)",
      "label-size": "var(--s-size-xs)",
      "label-weight": "700",
      "label-spacing": "4px",
      "helper-size": "var(--s-size-xs)",
    },
    alignment: {
      "title-align": "left",
    },
    sections: {
      "rail-margin": "16px",
      "padding-y": "44px",
      gap: "20px",
    },
    dividers: {
      style: "solid",
      width: "2px",
      "full-bleed": true,
    },
    gridVisuals: {
      "cell-border": true,
      "show-lines": true,
      "line-width": "1.5px",
    },
  },
};
