import type { SigilPreset } from "@sigil-ui/tokens";

export const strataPreset: SigilPreset = {
  name: "strata",
  metadata: {
    description: "Geological layers — earth tones, stratified typography, sedimentary depth.",
    mood: "geological, layered, earth-toned",
    tags: ["earth", "warm", "geological", "organic", "layered"],
    author: "sigil-ui",
    version: "0.1.0",
  },
  tokens: {
    colors: {
      background: { light: "oklch(0.96 0.01 70)", dark: "oklch(0.12 0.02 55)" },
      surface: { light: "oklch(0.94 0.012 65)", dark: "oklch(0.16 0.018 55)" },
      "surface-elevated": { light: "oklch(0.97 0.008 75)", dark: "oklch(0.2 0.016 55)" },
      "surface-sunken": { light: "oklch(0.92 0.015 60)", dark: "oklch(0.09 0.02 55)" },
      primary: "oklch(0.5 0.12 65)",
      "primary-hover": "oklch(0.44 0.14 65)",
      "primary-muted": "oklch(0.82 0.04 65)",
      "primary-contrast": "oklch(0.99 0.005 70)",
      secondary: "oklch(0.58 0.1 35)",
      "secondary-hover": "oklch(0.52 0.12 35)",
      "secondary-muted": "oklch(0.82 0.04 35)",
      accent: "oklch(0.65 0.09 155)",
      "accent-hover": "oklch(0.58 0.11 155)",
      "accent-muted": "oklch(0.85 0.04 155)",
      text: { light: "oklch(0.22 0.02 55)", dark: "oklch(0.9 0.01 70)" },
      "text-secondary": { light: "oklch(0.38 0.018 55)", dark: "oklch(0.75 0.01 70)" },
      "text-muted": { light: "oklch(0.52 0.015 55)", dark: "oklch(0.64 0.01 70)" },
      "text-subtle": { light: "oklch(0.63 0.01 55)", dark: "oklch(0.52 0.008 70)" },
      "text-disabled": { light: "oklch(0.75 0.008 55)", dark: "oklch(0.35 0.006 70)" },
      "text-inverse": { light: "oklch(0.95 0.005 70)", dark: "oklch(0.15 0.015 55)" },
      border: { light: "oklch(0.63 0.015 60)", dark: "oklch(0.300 0.015 55)" },
      "border-muted": { light: "oklch(0.80 0.010 60)", dark: "oklch(0.240 0.012 55)" },
      "border-strong": { light: "oklch(0.63 0.02 60)", dark: "oklch(0.380 0.018 55)" },
      "border-interactive": { light: "oklch(0.5 0.12 65)", dark: "oklch(0.55 0.12 65)" },
      success: "oklch(0.61 0.16 155)",
      "success-muted": "oklch(0.65 0.05 155)",
      warning: "oklch(0.63 0.14 80)",
      "warning-muted": "oklch(0.75 0.05 80)",
      error: "oklch(0.58 0.18 25)",
      "error-muted": "oklch(0.58 0.06 25)",
      info: "oklch(0.62 0.13 240)",
      "info-muted": "oklch(0.62 0.05 240)",
      "gradient-start": "oklch(0.5 0.12 65)",
      "gradient-end": "oklch(0.58 0.1 35)",
      glow: "oklch(0.5 0.12 65 / 0.3)",
      highlight: { light: "oklch(0.93 0.06 65)", dark: "oklch(0.28 0.05 65)" },
    },
    typography: {
      "font-display": "'PP Cirka', Georgia, serif",
      "font-body": "'PP Mori', system-ui, sans-serif",
      "font-mono": "'PP Fraktion Mono', ui-monospace, monospace",
      "size-xs": "0.75rem",
      "size-sm": "0.8125rem",
      "size-base": "1rem",
      "size-lg": "1.125rem",
      "size-xl": "1.25rem",
      "size-2xl": "1.5rem",
      "size-3xl": "1.875rem",
      "size-4xl": "2.25rem",
      "size-5xl": "3rem",
      "size-6xl": "3.75rem",
      "weight-normal": "400",
      "weight-medium": "500",
      "weight-semibold": "600",
      "weight-bold": "700",
      "weight-extrabold": "800",
      "leading-tight": "1.25",
      "leading-normal": "1.6",
      "leading-relaxed": "1.75",
      "leading-loose": "2",
      "tracking-tighter": "-0.03em",
      "tracking-tight": "-0.015em",
      "tracking-normal": "0em",
      "tracking-wide": "0.02em",
      "tracking-wider": "0.04em",
      "heading-weight": "500",
      "heading-tracking": "-0.01em",
      "heading-transform": "none",
      "heading-family": "'PP Cirka', Georgia, serif",
    },
    spacing: {
      scale: [4, 8, 16, 24, 32, 48, 64, 80, 104, 128],
      unit: "px",
      "button-px": "22px",
      "button-py": "10px",
      "button-px-sm": "16px",
      "button-py-sm": "7px",
      "button-px-lg": "30px",
      "button-py-lg": "14px",
      "card-padding": "28px",
      "card-padding-sm": "20px",
      "card-padding-lg": "36px",
      "input-px": "12px",
      "input-py": "8px",
      "badge-px": "8px",
      "badge-py": "3px",
      "section-py": "80px",
      "section-py-lg": "120px",
      "navbar-height": "60px",
      "navbar-px": "28px",
      "footer-py": "56px",
      "modal-padding": "28px",
      "popover-padding": "16px",
      "tooltip-padding": "6px 12px",
      "table-cell-px": "16px",
      "table-cell-py": "12px",
    },
    layout: {
      "content-max": "1200px",
      "content-max-narrow": "720px",
      "content-max-wide": "1440px",
      "page-margin": "28px",
      "page-margin-sm": "16px",
      "page-margin-lg": "52px",
      gutter: "28px",
      "gutter-sm": "16px",
      "gutter-lg": "40px",
      "grid-columns": "12",
      "grid-gap": "28px",
      "bento-gap": "18px",
      "bento-radius": "14px",
      "bento-min-height": "200px",
      "section-gap": "32px",
      "sidebar-width": "260px",
      "sidebar-collapsed": "56px",
      "footer-columns": "4",
      "stack-gap": "16px",
      "stack-gap-sm": "8px",
      "stack-gap-lg": "24px",
      "prose-max": "65ch",
    },
    sigil: {
      "grid-cell": "52px",
      "cross-arm": "12px",
      "cross-stroke": "1px",
      "rail-gap": "28px",
      "card-radius": "14px",
      "gutter-pattern": "diagonal",
      "margin-pattern": "triangle",
      "margin-border": "1px solid var(--s-border-muted)",
    },
    radius: {
      none: "0px",
      sm: "6px",
      md: "10px",
      lg: "14px",
      xl: "16px",
      "2xl": "20px",
      full: "9999px",
      button: "10px",
      card: "14px",
      input: "10px",
      badge: "9999px",
      modal: "16px",
      popover: "12px",
      tooltip: "8px",
      image: "12px",
      bento: "14px",
    },
    shadows: {
      sm: "0 1px 3px 0 rgb(60 40 20 / 0.06)",
      md: "0 2px 6px -1px rgb(60 40 20 / 0.08), 0 1px 3px rgb(60 40 20 / 0.05)",
      lg: "0 4px 12px -2px rgb(60 40 20 / 0.1), 0 2px 6px -2px rgb(60 40 20 / 0.06)",
      xl: "0 10px 24px -4px rgb(60 40 20 / 0.12), 0 4px 8px -4px rgb(60 40 20 / 0.06)",
      "2xl": "0 24px 50px -12px rgb(60 40 20 / 0.2)",
      glow: "0 0 24px var(--s-primary)",
      "glow-sm": "0 0 12px var(--s-primary)",
      colored: "0 4px 16px -4px var(--s-primary)",
      inner: "inset 0 2px 4px 0 rgb(60 40 20 / 0.06)",
      card: "none",
      button: "none",
      "button-hover": "0 1px 3px rgb(60 40 20 / 0.1)",
      dropdown: "0 4px 14px rgb(60 40 20 / 0.1), 0 0 0 1px rgb(60 40 20 / 0.04)",
      modal: "0 16px 48px -8px rgb(60 40 20 / 0.18)",
    },
    motion: {
      duration: { instant: "0ms", fast: "150ms", normal: "280ms", slow: "450ms", slower: "650ms", slowest: "1000ms" },
      easing: {
        default: "cubic-bezier(0.22, 1, 0.36, 1)",
        in: "cubic-bezier(0.55, 0, 1, 0.45)",
        out: "cubic-bezier(0, 0.55, 0.45, 1)",
        "in-out": "cubic-bezier(0.45, 0, 0.55, 1)",
        spring: "cubic-bezier(0.34, 1.56, 0.64, 1)",
        bounce: "cubic-bezier(0.68, -0.55, 0.27, 1.55)",
      },
      "enter-preset": "fadeUp",
      "exit-preset": "fadeOut",
      "hover-scale": "1.0",
      "press-scale": "0.98",
      "hover-lift": "0px",
      "stagger-interval": "60ms",
      "stagger-interval-fast": "30ms",
    },
    borders: {
      width: { none: "0px", thin: "1px", medium: "1.5px", thick: "2px" },
      style: "solid",
      "card-border": "1px solid",
      "card-border-hover": "1px solid",
      "button-border": "1px solid",
      "input-border": "1px solid",
      "divider-style": "solid",
      "divider-width": "1px",
    },
    buttons: {
      "font-weight": "500",
      "text-transform": "none",
      "letter-spacing": "0em",
      "font-family": "'PP Mori', system-ui, sans-serif",
      "border-width": "1px",
      "hover-effect": "darken",
      "active-scale": "0.98",
      "icon-gap": "8px",
      "min-width": "0px",
    },
    cards: {
      "border-style": "solid",
      "border-width": "1px",
      "hover-effect": "lift",
      "hover-border-color": "var(--s-border)",
      padding: "28px",
      "header-padding": "28px 28px 0",
      "footer-padding": "0 28px 28px",
      "title-size": "1.125rem",
      "title-weight": "600",
      "description-size": "0.875rem",
      background: "surface",
      shadow: "none",
      outline: true,
      "outline-on-hover-only": false,
      "gap-between": "0px",
      "content-padding-x": "28px",
      "content-padding-y": "24px",
    },
    headings: {
      "h1-size": "2.25rem",
      "h1-weight": "700",
      "h1-tracking": "-0.02em",
      "h1-leading": "1.2",
      "h2-size": "1.875rem",
      "h2-weight": "600",
      "h2-tracking": "-0.015em",
      "h3-size": "1.5rem",
      "h3-weight": "600",
      "h4-size": "1.25rem",
      "h4-weight": "600",
      "display-size": "3.75rem",
      "display-weight": "700",
      "display-tracking": "-0.03em",
      "display-leading": "1.1",
    },
    navigation: {
      "navbar-height": "60px",
      "navbar-backdrop-blur": "12px",
      "navbar-border": "1px solid",
      "navbar-bg-opacity": "0.85",
      "nav-link-weight": "500",
      "nav-link-size": "0.875rem",
      "nav-link-hover": "color",
      "breadcrumb-separator": "›",
      "pagination-radius": "10px",
      "sidebar-width": "260px",
      "sidebar-item-radius": "10px",
      "sidebar-item-padding": "9px 14px",
    },
    backgrounds: {
      pattern: "diagonal",
      "pattern-opacity": "0.04",
      "pattern-scale": "1.2",
      noise: false,
      "noise-opacity": "0.02",
      "gradient-angle": "180deg",
      "gradient-type": "none",
      "hero-pattern": "crosshatch",
      "section-divider": "diagonal",
    },
    code: {
      "font-family": "'PP Fraktion Mono', ui-monospace, monospace",
      "font-size": "0.8125rem",
      "line-height": "1.7",
      bg: "var(--s-surface-sunken)",
      border: "1px solid var(--s-border)",
      "border-radius": "10px",
      padding: "16px",
      "tab-size": "2",
      "selection-bg": "var(--s-primary-muted)",
      "comment-color": "var(--s-text-muted)",
      "keyword-color": "var(--s-primary)",
      "string-color": "var(--s-success)",
      "number-color": "var(--s-warning)",
      "function-color": "var(--s-accent)",
    },
    inputs: {
      height: "40px",
      "height-sm": "32px",
      "height-lg": "48px",
      "border-width": "1px",
      "focus-ring-width": "2px",
      "focus-ring-color": "var(--s-primary)",
      "focus-ring-offset": "2px",
      "placeholder-color": "var(--s-text-subtle)",
      "error-border-color": "var(--s-error)",
      "label-size": "0.8125rem",
      "label-weight": "500",
      "label-spacing": "6px",
      "helper-size": "0.75rem",
    },
    alignment: {
      "title-align": "left",
    },
    sections: {
      "rail-margin": "40px",
      "padding-y": "72px",
      gap: "36px",
      "max-width": "1000px",
    },
    dividers: {
      style: "solid",
      width: "1px",
      "background-alt": true,
    },
    gridVisuals: {
      "line-color": "var(--s-border-muted)",
      "line-width": "1px",
      "show-lines": false,
    },
    cursor: {
      variant: "dot",
      size: "24px",
      "dot-size": "4px",
      "stroke-width": "1.5px",
      "tick-size": "6px",
      gap: "3px",
      radius: "0px",
      color: "var(--s-text)",
      "ring-color": "var(--s-primary)",
      "dot-color": "var(--s-primary)",
      glow: "none",
      opacity: "1",
      "blend-mode": "normal",
      "z-index": "9999",
      "hide-native": false,
    },
    scrollbar: {
      width: "6px",
      height: "6px",
      padding: "2px",
      radius: "9999px",
      track: "transparent",
      thumb: "var(--s-border-muted)",
      "thumb-hover": "var(--s-border)",
      "thumb-active": "var(--s-border-strong)",
      corner: "transparent",
      border: "none",
      "firefox-width": "thin",
      gutter: "stable",
      visibility: "auto",
    },
    focus: {
      "ring-width": "1.5px",
      "ring-color": "var(--s-primary)",
      "ring-offset": "2px",
      "ring-shadow": "0 0 0 1.5px var(--s-primary)",
      "outline-color": "var(--s-primary)",
    },
    overlays: {
      bg: "rgb(0 0 0 / 0.4)",
      blur: "4px",
      surface: "var(--s-surface-elevated)",
      border: "1px solid var(--s-border-muted)",
      shadow: "var(--s-shadow-xl)",
      radius: "var(--s-radius-lg)",
      padding: "20px",
      "z-index": "50",
    },
    dataViz: {
      "series-1": "var(--s-primary)",
      "series-2": "var(--s-secondary)",
      "series-3": "var(--s-accent)",
      "series-4": "var(--s-info)",
      "series-5": "var(--s-success)",
      positive: "var(--s-success)",
      negative: "var(--s-error)",
      neutral: "var(--s-text-muted)",
      grid: "var(--s-border-muted)",
      axis: "var(--s-border)",
      label: "var(--s-text-secondary)",
      "tooltip-bg": "var(--s-surface-elevated)",
      "tooltip-border": "var(--s-border-muted)",
    },
    media: {
      radius: "var(--s-radius-md)",
      border: "none",
      outline: "1px solid rgb(0 0 0 / 0.08)",
      shadow: "none",
      bg: "var(--s-surface-sunken)",
      "object-fit": "cover",
    },
    controls: {
      height: "38px",
      "height-sm": "30px",
      "height-lg": "46px",
      "hit-area": "44px",
      "icon-size": "16px",
      "handle-size": "20px",
      "track-height": "4px",
      "track-bg": "var(--s-border-muted)",
      "track-fill": "var(--s-primary)",
      "thumb-bg": "var(--s-surface-elevated)",
      "thumb-border": "2px solid var(--s-primary)",
    },
    componentSurfaces: {
      bg: "var(--s-surface)",
      "bg-elevated": "var(--s-surface-elevated)",
      "bg-muted": "var(--s-surface-sunken)",
      border: "var(--s-border)",
      "border-muted": "var(--s-border-muted)",
      "border-strong": "var(--s-border-strong)",
      text: "var(--s-text)",
      "text-muted": "var(--s-text-muted)",
      contrast: "var(--s-primary-contrast)",
      "hover-bg": "var(--s-surface-elevated)",
      "active-bg": "var(--s-surface-sunken)",
      "selected-bg": "var(--s-primary-muted)",
    },

  },
};
