import type { SigilPreset } from "@sigil-ui/tokens";

export const vastPreset: SigilPreset = {
  name: "vast",
  metadata: {
    description: "Expansive open space. Warm editorial tones, generous whitespace, no gutter decoration.",
    mood: "expansive, warm, editorial",
    tags: ["edgeless", "warm", "editorial", "serif", "open"],
  },
  tokens: {
    colors: {
      background: { light: "oklch(0.985 0.005 75)", dark: "oklch(0.10 0.01 45)" },
      surface: { light: "oklch(0.97 0.008 75)", dark: "oklch(0.14 0.012 45)" },
      "surface-elevated": { light: "oklch(0.99 0.003 75)", dark: "oklch(0.18 0.015 45)" },
      "surface-sunken": { light: "oklch(0.95 0.01 75)", dark: "oklch(0.07 0.008 45)" },
      primary: { light: "oklch(0.52 0.14 35)", dark: "oklch(0.68 0.14 35)" },
      "primary-hover": { light: "oklch(0.46 0.16 35)", dark: "oklch(0.74 0.12 35)" },
      "primary-muted": { light: "oklch(0.52 0.05 35)", dark: "oklch(0.68 0.04 35)" },
      "primary-contrast": { light: "oklch(1 0 0)", dark: "oklch(0.10 0.01 45)" },
      secondary: "oklch(0.55 0.08 60)",
      "secondary-hover": "oklch(0.48 0.10 60)",
      "secondary-muted": "oklch(0.55 0.03 60)",
      accent: "oklch(0.60 0.12 25)",
      "accent-hover": "oklch(0.54 0.14 25)",
      "accent-muted": "oklch(0.60 0.04 25)",
      text: { light: "oklch(0.18 0.01 45)", dark: "oklch(0.92 0.01 75)" },
      "text-secondary": { light: "oklch(0.35 0.01 45)", dark: "oklch(0.72 0.01 75)" },
      "text-muted": { light: "oklch(0.52 0.01 45)", dark: "oklch(0.55 0.01 75)" },
      "text-subtle": { light: "oklch(0.65 0.01 45)", dark: "oklch(0.42 0.01 75)" },
      "text-disabled": { light: "oklch(0.78 0.005 45)", dark: "oklch(0.30 0.005 75)" },
      "text-inverse": { light: "oklch(0.92 0.01 75)", dark: "oklch(0.18 0.01 45)" },
      border: { light: "oklch(0.85 0.01 75)", dark: "oklch(0.280 0.010 45)" },
      "border-muted": { light: "oklch(0.92 0.005 75)", dark: "oklch(0.220 0.008 45)" },
      "border-strong": { light: "oklch(0.75 0.015 75)", dark: "oklch(0.360 0.015 45)" },
      "border-interactive": { light: "oklch(0.52 0.14 35)", dark: "oklch(0.68 0.14 35)" },
      success: "oklch(0.62 0.16 155)",
      "success-muted": { light: "oklch(0.95 0.03 155)", dark: "oklch(0.15 0.04 155)" },
      warning: "oklch(0.72 0.14 80)",
      "warning-muted": { light: "oklch(0.96 0.03 80)", dark: "oklch(0.18 0.04 80)" },
      error: "oklch(0.55 0.18 25)",
      "error-muted": { light: "oklch(0.96 0.03 25)", dark: "oklch(0.18 0.04 25)" },
      info: "oklch(0.60 0.13 245)",
      "info-muted": { light: "oklch(0.96 0.02 245)", dark: "oklch(0.18 0.03 245)" },
      "gradient-start": { light: "oklch(0.52 0.14 35)", dark: "oklch(0.68 0.14 35)" },
      "gradient-end": { light: "oklch(0.55 0.08 60)", dark: "oklch(0.55 0.08 60)" },
      glow: { light: "oklch(0.52 0.14 35 / 0.15)", dark: "oklch(0.68 0.14 35 / 0.12)" },
      highlight: { light: "oklch(0.93 0.06 35)", dark: "oklch(0.28 0.05 35)" },
    },
    typography: {
      "font-display": "Fraunces, 'Playfair Display', Georgia, serif",
      "font-body": "'Source Sans 3', 'Source Sans Pro', system-ui, sans-serif",
      "font-mono": "'IBM Plex Mono', ui-monospace, monospace",
      "size-xs": "0.75rem",
      "size-sm": "0.875rem",
      "size-base": "1rem",
      "size-lg": "1.125rem",
      "size-xl": "1.25rem",
      "size-2xl": "1.5rem",
      "size-3xl": "1.875rem",
      "size-4xl": "2.25rem",
      "size-5xl": "3rem",
      "size-6xl": "3.75rem",
      "weight-normal": "400",
      "weight-medium": "500",
      "weight-semibold": "600",
      "weight-bold": "700",
      "weight-extrabold": "800",
      "leading-tight": "1.2",
      "leading-normal": "1.6",
      "leading-relaxed": "1.75",
      "leading-loose": "2",
      "tracking-tighter": "-0.04em",
      "tracking-tight": "-0.02em",
      "tracking-normal": "0em",
      "tracking-wide": "0.02em",
      "tracking-wider": "0.04em",
      "heading-weight": "400",
      "heading-tracking": "-0.02em",
      "heading-transform": "none",
      "heading-family": "Fraunces, 'Playfair Display', Georgia, serif",
    },
    spacing: {
      scale: [4, 8, 12, 16, 24, 32, 48, 64, 96, 128],
      unit: "px",
      "button-px": "24px",
      "button-py": "12px",
      "button-px-sm": "16px",
      "button-py-sm": "8px",
      "button-px-lg": "32px",
      "button-py-lg": "14px",
      "card-padding": "32px",
      "card-padding-sm": "20px",
      "card-padding-lg": "48px",
      "input-px": "14px",
      "input-py": "10px",
      "badge-px": "12px",
      "badge-py": "3px",
      "section-py": "120px",
      "section-py-lg": "160px",
      "navbar-height": "64px",
      "navbar-px": "32px",
      "footer-py": "80px",
      "modal-padding": "32px",
      "popover-padding": "16px",
      "tooltip-padding": "8px 14px",
      "table-cell-px": "16px",
      "table-cell-py": "14px",
    },
    layout: {
      "content-max": "1080px",
      "content-max-narrow": "680px",
      "content-max-wide": "1320px",
      "page-margin": "32px",
      "page-margin-sm": "16px",
      "page-margin-lg": "64px",
      gutter: "0px",
      "gutter-sm": "0px",
      "gutter-lg": "0px",
      "grid-columns": "12",
      "grid-gap": "32px",
      "bento-gap": "24px",
      "bento-radius": "12px",
      "bento-min-height": "220px",
      "section-gap": "48px",
      "sidebar-width": "260px",
      "sidebar-collapsed": "56px",
      "footer-columns": "4",
      "stack-gap": "20px",
      "stack-gap-sm": "12px",
      "stack-gap-lg": "32px",
      "prose-max": "62ch",
    },
    sigil: {
      "grid-cell": "64px",
      "cross-arm": "0px",
      "cross-stroke": "0px",
      "rail-gap": "0px",
      "card-radius": "12px",
      "gutter-pattern": "none",
      "margin-pattern": "none",
      "gutter-border": "none",
      "gutter-visible": false,
    },
    radius: {
      none: "0px",
      sm: "6px",
      md: "10px",
      lg: "14px",
      xl: "20px",
      "2xl": "28px",
      full: "9999px",
      button: "8px",
      card: "12px",
      input: "8px",
      badge: "9999px",
      modal: "16px",
      popover: "12px",
      tooltip: "8px",
      image: "10px",
      bento: "12px",
    },
    shadows: {
      sm: "0 1px 3px 0 rgb(0 0 0 / 0.04)",
      md: "0 2px 6px -1px rgb(0 0 0 / 0.06), 0 1px 3px 0 rgb(0 0 0 / 0.04)",
      lg: "0 4px 12px -2px rgb(0 0 0 / 0.08), 0 2px 4px 0 rgb(0 0 0 / 0.03)",
      xl: "0 8px 24px -4px rgb(0 0 0 / 0.1), 0 4px 8px -2px rgb(0 0 0 / 0.04)",
      "2xl": "0 16px 48px -8px rgb(0 0 0 / 0.12)",
      glow: "0 0 24px oklch(0.52 0.14 35 / 0.15)",
      "glow-sm": "0 0 12px oklch(0.52 0.14 35 / 0.1)",
      colored: "0 4px 16px -4px oklch(0.52 0.14 35 / 0.2)",
      inner: "inset 0 2px 4px 0 rgb(0 0 0 / 0.04)",
      card: "0 1px 4px 0 rgb(0 0 0 / 0.04)",
      button: "0 1px 2px 0 rgb(0 0 0 / 0.04)",
      "button-hover": "0 2px 6px -1px rgb(0 0 0 / 0.08)",
      dropdown: "0 4px 12px -2px rgb(0 0 0 / 0.1)",
      modal: "0 20px 40px -8px rgb(0 0 0 / 0.15)",
    },
    motion: {
      duration: { instant: "0ms", fast: "120ms", normal: "220ms", slow: "380ms", slower: "550ms", slowest: "800ms" },
      easing: {
        default: "cubic-bezier(0.22, 1, 0.36, 1)",
        in: "cubic-bezier(0.55, 0, 1, 0.45)",
        out: "cubic-bezier(0, 0.55, 0.45, 1)",
        "in-out": "cubic-bezier(0.45, 0, 0.55, 1)",
        spring: "cubic-bezier(0.34, 1.56, 0.64, 1)",
      },
      "hover-scale": "1.0",
      "press-scale": "0.98",
      "hover-lift": "-2px",
      "stagger-interval": "60ms",
      "stagger-interval-fast": "35ms",
    },
    borders: {
      width: { none: "0px", thin: "1px", medium: "1.5px", thick: "2px" },
      style: "solid",
      "card-border": "1px solid",
      "card-border-hover": "1px solid",
      "button-border": "1px solid",
      "input-border": "1px solid",
      "divider-style": "solid",
      "divider-width": "1px",
    },
    buttons: {
      "font-weight": "500",
      "text-transform": "none",
      "letter-spacing": "0.01em",
      "font-family": "'Source Sans 3', system-ui, sans-serif",
      "border-width": "1px",
      "hover-effect": "darken",
      "active-scale": "0.98",
      "icon-gap": "8px",
      "min-width": "0px",
    },
    cards: {
      "border-style": "solid",
      "border-width": "1px",
      "hover-effect": "lift",
      "hover-border-color": "var(--s-border-strong)",
      padding: "32px",
      "header-padding": "32px 32px 0",
      "footer-padding": "0 32px 32px",
      "title-size": "1.125rem",
      "title-weight": "600",
      "description-size": "0.9375rem",
      background: "surface",
      shadow: "sm",
      outline: true,
      "outline-on-hover-only": false,
      "gap-between": "20px",
      "content-padding-x": "32px",
      "content-padding-y": "24px",
    },
    headings: {
      "h1-size": "2.5rem",
      "h1-weight": "400",
      "h1-tracking": "-0.02em",
      "h1-leading": "1.15",
      "h2-size": "2rem",
      "h2-weight": "400",
      "h2-tracking": "-0.015em",
      "h3-size": "1.5rem",
      "h3-weight": "500",
      "h4-size": "1.25rem",
      "h4-weight": "500",
      "display-size": "4rem",
      "display-weight": "400",
      "display-tracking": "-0.03em",
      "display-leading": "1.08",
    },
    navigation: {
      "navbar-height": "64px",
      "navbar-backdrop-blur": "16px",
      "navbar-border": "none",
      "navbar-bg-opacity": "0.92",
      "nav-link-weight": "400",
      "nav-link-size": "0.9375rem",
      "nav-link-hover": "color",
      "breadcrumb-separator": "/",
      "pagination-radius": "8px",
      "sidebar-width": "260px",
      "sidebar-item-radius": "8px",
      "sidebar-item-padding": "10px 14px",
    },
    backgrounds: {
      pattern: "none",
      "pattern-opacity": "0",
      "pattern-scale": "1",
      noise: true,
      "noise-opacity": "0.015",
      "gradient-angle": "180deg",
      "gradient-type": "none",
      "hero-pattern": "noise",
      "section-divider": "none",
    },
    code: {
      "font-family": "'IBM Plex Mono', ui-monospace, monospace",
      "font-size": "0.875rem",
      "line-height": "1.7",
      bg: "var(--s-surface-sunken)",
      border: "1px solid var(--s-border-muted)",
      "border-radius": "8px",
      padding: "20px",
      "tab-size": "2",
      "selection-bg": "var(--s-primary-muted)",
      "comment-color": "var(--s-text-muted)",
      "keyword-color": "oklch(0.52 0.14 35)",
      "string-color": "oklch(0.62 0.16 155)",
      "number-color": "oklch(0.72 0.14 80)",
      "function-color": "oklch(0.60 0.13 245)",
    },
    inputs: {
      height: "42px",
      "height-sm": "36px",
      "height-lg": "50px",
      "border-width": "1px",
      "focus-ring-width": "2px",
      "focus-ring-color": "var(--s-primary)",
      "focus-ring-offset": "2px",
      "placeholder-color": "var(--s-text-subtle)",
      "error-border-color": "var(--s-error)",
      "label-size": "0.875rem",
      "label-weight": "500",
      "label-spacing": "8px",
      "helper-size": "0.8125rem",
    },
    alignment: {
      "rail-width": "1080px",
      "rail-columns": "12",
      "rail-gutter": "32px",
      "rail-margin": "32px",
      "rail-visible": false,
      "rail-color": "var(--s-border-muted)",
      "content-align": "center",
      "hero-align": "center",
      "section-align": "center",
      "navbar-align": "full",
      "footer-align": "full",
    },
    sections: {
      "padding-y": "120px",
      "padding-y-hero": "160px",
      "padding-x": "32px",
      "max-width": "1080px",
      gap: "48px",
      "title-align": "center",
      "divider-above": false,
      "divider-below": false,
      "background-alt": false,
      indent: "0px",
    },
    dividers: {
      style: "none",
      width: "0px",
      color: "var(--s-border-muted)",
      spacing: "0px",
      "show-cross": false,
      "show-label": false,
      "full-bleed": false,
      ornament: "none",
    },
    gridVisuals: {
      "show-lines": false,
      "line-color": "var(--s-border-muted)",
      "line-width": "1px",
      "show-dots": false,
      "dot-size": "2px",
      "cell-background": "none",
      "cell-border": false,
      "cell-radius": "12px",
      "cell-padding": "24px",
      "hover-effect": "lift",
    },
    cursor: {
      variant: "dot",
      size: "24px",
      "dot-size": "4px",
      "stroke-width": "1.5px",
      "tick-size": "6px",
      gap: "3px",
      radius: "0px",
      color: "var(--s-text)",
      "ring-color": "var(--s-primary)",
      "dot-color": "var(--s-primary)",
      glow: "none",
      opacity: "1",
      "blend-mode": "normal",
      "z-index": "9999",
      "hide-native": false,
    },
    scrollbar: {
      width: "8px",
      height: "8px",
      padding: "2px",
      radius: "9999px",
      track: "transparent",
      thumb: "var(--s-border-muted)",
      "thumb-hover": "var(--s-border)",
      "thumb-active": "var(--s-border-strong)",
      corner: "transparent",
      border: "none",
      "firefox-width": "thin",
      gutter: "stable",
      visibility: "auto",
    },
    focus: {
      "ring-width": "2px",
      "ring-color": "var(--s-primary)",
      "ring-offset": "2px",
      "ring-shadow": "0 0 0 2px var(--s-primary)",
      "outline-color": "var(--s-primary)",
    },
    overlays: {
      bg: "rgb(0 0 0 / 0.5)",
      blur: "8px",
      surface: "var(--s-surface-elevated)",
      border: "1px solid var(--s-border-muted)",
      shadow: "var(--s-shadow-xl)",
      radius: "var(--s-radius-lg)",
      padding: "20px",
      "z-index": "50",
    },
    dataViz: {
      "series-1": "var(--s-primary)",
      "series-2": "var(--s-secondary)",
      "series-3": "var(--s-accent)",
      "series-4": "var(--s-info)",
      "series-5": "var(--s-success)",
      positive: "var(--s-success)",
      negative: "var(--s-error)",
      neutral: "var(--s-text-muted)",
      grid: "var(--s-border-muted)",
      axis: "var(--s-border)",
      label: "var(--s-text-secondary)",
      "tooltip-bg": "var(--s-surface-elevated)",
      "tooltip-border": "var(--s-border-muted)",
    },
    media: {
      radius: "var(--s-radius-md)",
      border: "none",
      outline: "1px solid rgb(0 0 0 / 0.08)",
      shadow: "none",
      bg: "var(--s-surface-sunken)",
      "object-fit": "cover",
    },
    controls: {
      height: "38px",
      "height-sm": "30px",
      "height-lg": "46px",
      "hit-area": "44px",
      "icon-size": "16px",
      "handle-size": "20px",
      "track-height": "4px",
      "track-bg": "var(--s-border-muted)",
      "track-fill": "var(--s-primary)",
      "thumb-bg": "var(--s-surface-elevated)",
      "thumb-border": "2px solid var(--s-primary)",
    },
    componentSurfaces: {
      bg: "var(--s-surface)",
      "bg-elevated": "var(--s-surface-elevated)",
      "bg-muted": "var(--s-surface-sunken)",
      border: "var(--s-border)",
      "border-muted": "var(--s-border-muted)",
      "border-strong": "var(--s-border-strong)",
      text: "var(--s-text)",
      "text-muted": "var(--s-text-muted)",
      contrast: "var(--s-primary-contrast)",
      "hover-bg": "var(--s-surface-elevated)",
      "active-bg": "var(--s-surface-sunken)",
      "selected-bg": "var(--s-primary-muted)",
    },

  },
};
