import type { SigilPreset } from "@sigil-ui/tokens";

export const vexPreset: SigilPreset = {
  name: "vex",
  metadata: {
    description:
      "Provocative challenge. Anti-establishment punk with maximum contrast and aggressive typography.",
    mood: "provocative, punk, anti-establishment",
    tags: ["light", "punk", "bold", "aggressive", "high-contrast"],
  },
  tokens: {
    colors: {
      background: { light: "#fef08a", dark: "#1a1a00" },
      surface: { light: "#fef9c3", dark: "#262600" },
      "surface-elevated": { light: "#ffffff", dark: "#333300" },
      "surface-sunken": { light: "#fde047", dark: "#111100" },
      primary: "#ec4899",
      "primary-hover": "#db2777",
      "primary-muted": "#ec489940",
      "primary-contrast": "#000000",
      secondary: "#000000",
      "secondary-hover": "#1a1a1a",
      "secondary-muted": "#00000020",
      accent: "#ef4444",
      "accent-hover": "#dc2626",
      "accent-muted": "#ef444430",
      text: { light: "#000000", dark: "#fef08a" },
      "text-secondary": { light: "#1a1a1a", dark: "#fde047" },
      "text-muted": { light: "#333333", dark: "#d4c800" },
      "text-subtle": { light: "#555555", dark: "#a39e00" },
      "text-disabled": { light: "#888888", dark: "#6b6700" },
      "text-inverse": { light: "#fef08a", dark: "#000000" },
      border: { light: "#000000", dark: "#fef08a" },
      "border-muted": { light: "#333333", dark: "#c8c200" },
      "border-strong": { light: "#000000", dark: "#fef9c3" },
      "border-interactive": { light: "#ec4899", dark: "#ec4899" },
      success: "#22c55e",
      "success-muted": "#22c55e30",
      warning: "#f97316",
      "warning-muted": "#f9731630",
      error: "#ef4444",
      "error-muted": "#ef444430",
      info: "#3b82f6",
      "info-muted": "#3b82f630",
      "gradient-start": "#ec4899",
      "gradient-end": "#000000",
      glow: "#ec489960",
    },
    typography: {
      "font-display": "'PP Formula Condensed', Impact, sans-serif",
      "font-body": "'PP Supply Sans', system-ui, sans-serif",
      "font-mono": "'PP Supply Mono', ui-monospace, monospace",
      "size-xs": "0.75rem",
      "size-sm": "0.875rem",
      "size-base": "1rem",
      "size-lg": "1.125rem",
      "size-xl": "1.25rem",
      "size-2xl": "1.5rem",
      "size-3xl": "2rem",
      "size-4xl": "2.5rem",
      "size-5xl": "3.5rem",
      "size-6xl": "5rem",
      "weight-normal": "400",
      "weight-medium": "500",
      "weight-semibold": "600",
      "weight-bold": "700",
      "weight-extrabold": "800",
      "leading-tight": "1.1",
      "leading-normal": "1.45",
      "leading-relaxed": "1.6",
      "leading-loose": "1.8",
      "tracking-tighter": "-0.04em",
      "tracking-tight": "-0.02em",
      "tracking-normal": "0em",
      "tracking-wide": "0.05em",
      "tracking-wider": "0.1em",
      "heading-weight": "400",
      "heading-tracking": "0.05em",
      "heading-transform": "uppercase",
      "heading-family": "'PP Formula Condensed', Impact, sans-serif",
    },
    spacing: {
      scale: [2, 4, 8, 12, 16, 20, 28, 40, 56, 72],
      unit: "px",
      "button-px": "20px",
      "button-py": "10px",
      "button-px-sm": "12px",
      "button-py-sm": "6px",
      "button-px-lg": "28px",
      "button-py-lg": "14px",
      "card-padding": "14px",
      "card-padding-sm": "12px",
      "card-padding-lg": "24px",
      "input-px": "10px",
      "input-py": "8px",
      "badge-px": "8px",
      "badge-py": "2px",
      "section-py": "44px",
      "section-py-lg": "68px",
      "navbar-height": "48px",
      "navbar-px": "12px",
      "footer-py": "28px",
      "modal-padding": "20px",
      "popover-padding": "12px",
      "tooltip-padding": "4px 8px",
      "table-cell-px": "12px",
      "table-cell-py": "8px",
    },
    layout: {
      "content-max": "1080px",
      "content-max-narrow": "680px",
      "content-max-wide": "1400px",
      "page-margin": "12px",
      "page-margin-sm": "12px",
      "page-margin-lg": "24px",
      gutter: "10px",
      "gutter-sm": "6px",
      "gutter-lg": "18px",
      "grid-columns": "12",
      "grid-gap": "10px",
      "bento-gap": "6px",
      "bento-radius": "0px",
      "bento-min-height": "160px",
      "section-gap": "24px",
      "sidebar-width": "220px",
      "sidebar-collapsed": "48px",
      "footer-columns": "4",
      "stack-gap": "12px",
      "stack-gap-sm": "6px",
      "stack-gap-lg": "20px",
      "prose-max": "60ch",
    },
    sigil: {
      "grid-cell": "36px",
      "cross-arm": "8px",
      "cross-stroke": "3px",
      "rail-gap": "12px",
      "card-radius": "0px",
      "gutter-pattern": "crosshatch",
      "margin-pattern": "checker",
    },
    radius: {
      none: "0px",
      sm: "0px",
      md: "0px",
      lg: "0px",
      xl: "0px",
      "2xl": "0px",
      full: "0px",
      button: "0px",
      card: "0px",
      input: "0px",
      badge: "0px",
      modal: "0px",
      popover: "0px",
      tooltip: "0px",
      image: "0px",
      bento: "0px",
    },
    shadows: {
      sm: "2px 2px 0 var(--s-border)",
      md: "3px 3px 0 var(--s-border)",
      lg: "4px 4px 0 var(--s-border)",
      xl: "6px 6px 0 var(--s-border)",
      "2xl": "none",
      glow: "none",
      "glow-sm": "none",
      colored: "none",
      inner: "none",
      card: "3px 3px 0 var(--s-border)",
      button: "2px 2px 0 var(--s-border)",
      "button-hover": "4px 4px 0 var(--s-border)",
      dropdown: "4px 4px 0 #000000",
      modal: "8px 8px 0 #000000",
    },
    motion: {
      duration: { instant: "0ms", fast: "80ms", normal: "150ms", slow: "250ms", slower: "400ms", slowest: "600ms" },
      easing: {
        default: "cubic-bezier(0, 0, 1, 1)",
        in: "cubic-bezier(0.55, 0, 1, 0.45)",
        out: "cubic-bezier(0, 0.55, 0.45, 1)",
        "in-out": "cubic-bezier(0.45, 0, 0.55, 1)",
        spring: "cubic-bezier(0.22, 1, 0.36, 1)",
        bounce: "cubic-bezier(0.68, -0.55, 0.27, 1.55)",
      },
      "enter-preset": "fadeIn",
      "exit-preset": "fadeOut",
      "hover-scale": "1",
      "press-scale": "0.95",
      "hover-lift": "0px",
      "stagger-interval": "30ms",
      "stagger-interval-fast": "15ms",
    },
    borders: {
      width: { none: "0px", thin: "1px", medium: "2px", thick: "3px" },
      style: "solid",
      "card-border": "2px solid",
      "card-border-hover": "2px solid",
      "button-border": "3px solid",
      "input-border": "2px solid",
      "divider-style": "solid",
      "divider-width": "2px",
    },
    buttons: {
      "font-weight": "800",
      "text-transform": "uppercase",
      "letter-spacing": "0.1em",
      "font-family": "'PP Supply Sans', system-ui, sans-serif",
      "border-width": "3px",
      "hover-effect": "none",
      "active-scale": "0.95",
      "icon-gap": "8px",
      "min-width": "0px",
    },
    cards: {
      "border-style": "solid",
      "border-width": "3px",
      "hover-effect": "border",
      "hover-border-color": "#000000",
      padding: "16px",
      "header-padding": "16px 16px 0",
      "footer-padding": "0 16px 16px",
      "title-size": "1.25rem",
      "title-weight": "700",
      "description-size": "0.875rem",
      outline: true,
      shadow: "none",
    },
    headings: {
      "h1-size": "3.5rem",
      "h1-weight": "400",
      "h1-tracking": "0.05em",
      "h1-leading": "1",
      "h2-size": "2.5rem",
      "h2-weight": "400",
      "h2-tracking": "0.04em",
      "h3-size": "2rem",
      "h3-weight": "400",
      "h4-size": "1.5rem",
      "h4-weight": "400",
      "display-size": "6rem",
      "display-weight": "900",
      "display-tracking": "0.06em",
      "display-leading": "0.9",
    },
    navigation: {
      "navbar-height": "48px",
      "navbar-backdrop-blur": "0px",
      "navbar-border": "3px solid",
      "navbar-bg-opacity": "1",
      "nav-link-weight": "800",
      "nav-link-size": "0.875rem",
      "nav-link-hover": "none",
      "breadcrumb-separator": " > ",
      "pagination-radius": "0px",
      "sidebar-width": "220px",
      "sidebar-item-radius": "0px",
      "sidebar-item-padding": "6px 10px",
    },
    backgrounds: {
      pattern: "crosshatch",
      "pattern-opacity": "0.08",
      "pattern-scale": "1",
      noise: false,
      "noise-opacity": "0",
      "gradient-angle": "0deg",
      "gradient-type": "none",
      "hero-pattern": "crosshatch",
      "section-divider": "zigzag",
    },
    code: {
      "font-family": "'PP Supply Mono', ui-monospace, monospace",
      "font-size": "0.875rem",
      "line-height": "1.6",
      bg: "var(--s-surface-sunken)",
      border: "2px solid var(--s-border)",
      "border-radius": "0px",
      padding: "12px",
      "tab-size": "4",
      "selection-bg": "#ec489940",
      "comment-color": "var(--s-text-muted)",
      "keyword-color": "#ec4899",
      "string-color": "#22c55e",
      "number-color": "#f97316",
      "function-color": "#3b82f6",
    },
    inputs: {
      height: "40px",
      "height-sm": "32px",
      "height-lg": "48px",
      "border-width": "2px",
      "focus-ring-width": "3px",
      "focus-ring-color": "#ec4899",
      "focus-ring-offset": "0px",
      "placeholder-color": "var(--s-text-muted)",
      "error-border-color": "#ef4444",
      "label-size": "0.875rem",
      "label-weight": "700",
      "label-spacing": "4px",
      "helper-size": "0.75rem",
    },
    alignment: {
      "title-align": "left",
      "rail-margin": "8px",
    },
    sections: {
      "padding-y": "32px",
      gap: "16px",
    },
    dividers: {
      style: "solid",
      width: "3px",
      "full-bleed": true,
    },
    gridVisuals: {
      "show-lines": true,
      "line-width": "3px",
      "cell-border": true,
    },
  },
};
