import type { SigilTokens } from "../types";

/**
 * Generates a TypeScript source file exporting a `tokens` constant
 * that mirrors the design token values as a plain object.
 */
export function compileToTs(tokens: SigilTokens): string {
  const json = JSON.stringify(tokens, null, 2);
  const lines = [
    "// Auto-generated by @sigil-ui/tokens — do not edit manually",
    `import type { SigilTokens } from "@sigil-ui/tokens";`,
    "",
    `export const tokens: SigilTokens = ${json} as const;`,
    "",
  ];
  return lines.join("\n");
}

/**
 * Serializes tokens to a JSON string for tooling and validation.
 */
export function compileToJson(tokens: SigilTokens): string {
  return JSON.stringify(tokens, null, 2) + "\n";
}
