import type { SigilConfig } from "./config.js";
import type { PresetInfo } from "./presets.js";
import type { ProjectDetection } from "./detect.js";
import { generateRequiredSkillsSection } from "./skills.js";

export function generateAgentInstructions(
  config: SigilConfig,
  preset: PresetInfo | undefined,
  detection: ProjectDetection,
  features: string[],
  generator = "sigil init",
): string {
  const featuresList = features.length > 0 ? features.join(", ") : "none selected";

  return `# Sigil UI — Agent Instructions

> Auto-generated by \`${generator}\`. Read this before writing any UI code in this project.

## The #1 Rule

**Edit the token spec. Not the components.**

To change how things look, edit the token CSS file (\`${config.tokensPath}\`) or switch presets. Components read from CSS variables — they update automatically when tokens change. Do not manually edit Tailwind classes or hardcode colors/spacing/fonts in component files.

## Project Setup

| Key | Value |
|-----|-------|
| Preset | \`${config.preset}\`${preset ? ` — ${preset.description}` : ""} |
${preset ? `| Mood | ${preset.mood} |\n` : ""}| Components | \`${config.componentsDir}\` |
| Tokens CSS | \`${config.tokensPath}\` |
| TypeScript | ${config.typescript ? "Yes" : "No"} |
| Framework | ${detection.framework} |
| Features | ${featuresList} |

## How to Make Visual Changes

| Want to change... | Do this | Do NOT do this |
|-------------------|---------|----------------|
| Primary color | Edit \`${config.tokensPath}\`: \`--sigil-primary: oklch(...);\` | Edit component files |
| Fonts | Edit \`${config.tokensPath}\`: \`--sigil-font-display: "Font", ...;\` | Add font classes to components |
| Border radius | Edit \`${config.tokensPath}\`: \`--sigil-radius-md: 12px;\` | Add \`rounded-*\` to components |
| Animation speed | Edit \`${config.tokensPath}\`: \`--sigil-duration-fast: 200ms;\` | Add inline transition values |
| Everything at once | Run \`npx @sigil-ui/cli preset <name>\` | Edit dozens of component files |
| Create custom aesthetic | Run \`npx @sigil-ui/cli preset create\` | Manually override each component |

## Token Conventions

- All colors use OKLCH: \`oklch(L C H)\` — no hex, no rgb, no hsl
- CSS variables use \`--s-\` prefix: \`var(--s-primary)\`, \`var(--s-radius-md)\`, \`var(--s-duration-fast)\`
- Themed tokens (backgrounds, text, borders) have automatic light/dark support
- Spacing follows the token scale — do not use arbitrary pixel values

## Component Conventions

- Components live in \`${config.componentsDir}\`
- Every component uses \`forwardRef\` and accepts \`className\`
- Styling uses CSS classes prefixed with \`sigil-\` that reference \`var(--s-*)\`
- Use \`clsx\` + \`tailwind-merge\` for class merging
- Add new components with \`npx @sigil-ui/cli add <name>\`

${generateRequiredSkillsSection()}

## Available Commands

\`\`\`bash
npx @sigil-ui/cli convert     # adopt Sigil end-to-end
npx @sigil-ui/cli add <components>    # copy components into project
npx @sigil-ui/cli add --all           # add all registered components
npx @sigil-ui/cli preset              # show current preset
npx @sigil-ui/cli preset list         # browse all 31 presets by category
npx @sigil-ui/cli preset <name>       # switch presets
npx @sigil-ui/cli preset create       # scaffold a custom preset
npx @sigil-ui/cli diff                # show token changes
npx @sigil-ui/cli doctor              # validate project health
\`\`\`

## File Map

| File | Purpose | When to edit |
|------|---------|-------------|
| \`${config.tokensPath}\` | Token CSS (imports base + preset + overrides) | To change any visual property |
| \`sigil.config.ts\` | Project configuration | To change preset, paths, settings |
| \`${config.componentsDir}/*.tsx\` | Component source files | To change component behavior (not appearance) |
| \`.sigil/tokens.snapshot.css\` | Token snapshot for diffing | Never (managed by \`sigil diff\`) |

## Agent Workflow

1. Read this file first to understand the setup
2. Read the relevant skill from \`.sigil/skills/\` before editing
3. Check the active preset (\`${config.preset}\`)${preset ? ` — mood is "${preset.mood}"` : ""}
4. Use existing components from \`${config.componentsDir}\` before creating new ones
5. For visual changes, edit \`${config.tokensPath}\` — never hardcode values in components
6. For wholesale changes, switch presets: \`npx @sigil-ui/cli preset <name>\`
7. Run \`npx @sigil-ui/cli doctor\` after changes to validate
${features.includes("gsap") ? `8. Scroll animations use GSAP + ScrollTrigger — import from \`gsap\` and \`gsap/ScrollTrigger\`\n` : ""}${features.includes("motion") ? `${features.includes("gsap") ? "9" : "8"}. Component animations use Motion — use \`motion\` components with spring physics\n` : ""}${features.includes("grid") ? `${features.includes("gsap") && features.includes("motion") ? "10" : features.includes("gsap") || features.includes("motion") ? "9" : "8"}. Layout uses the Sigil structural-visibility grid — \`--sigil-grid-cell\` (48px) and \`--sigil-rail-gap\` (24px)\n` : ""}`;
}
