import fs from "fs-extra";
import path from "node:path";
import { fileURLToPath } from "node:url";

export type SigilSkill = {
  id: string;
  label: string;
  task: string;
  trigger: string;
  files: string[];
};

export const SIGIL_SKILLS: SigilSkill[] = [
  {
    id: "sigil-tokens",
    label: "Sigil Tokens",
    task: "Edit or debug design tokens",
    trigger: "colors, fonts, spacing, radius, shadows, motion, token CSS",
    files: ["SKILL.md"],
  },
  {
    id: "sigil-preset",
    label: "Sigil Preset",
    task: "Create, modify, or choose presets",
    trigger: "new theme, preset creation, visual identity changes",
    files: ["SKILL.md"],
  },
  {
    id: "sigil-component",
    label: "Sigil Component",
    task: "Create, modify, or review components",
    trigger: "component source, variants, registry entries, exports",
    files: ["SKILL.md"],
  },
  {
    id: "sigil-layout",
    label: "Sigil Layout",
    task: "Compose layouts and grid structures",
    trigger: "page layout, sections, grids, rails, app shells",
    files: ["SKILL.md"],
  },
  {
    id: "sigil-playbook",
    label: "Sigil Playbook",
    task: "Build full pages in the Sigil aesthetic",
    trigger: "landing pages, dashboards, docs pages, page composition",
    files: ["SKILL.md"],
  },
  {
    id: "sigil-migration",
    label: "Sigil Migration",
    task: "Migrate from shadcn/ui or another design system",
    trigger: "migration, compatibility layer, replacing shadcn components",
    files: ["SKILL.md"],
  },
  {
    id: "sigil-polish",
    label: "Sigil Polish",
    task: "Polish visual details and interactions",
    trigger: "typography, surfaces, animations, performance, micro-interactions",
    files: ["SKILL.md", "typography.md", "surfaces.md", "animations.md", "performance.md"],
  },
];

export type SigilAgentAssetsResult = {
  skillsDir: string;
  cursorRulePath: string;
  installedSkillCount: number;
};

export function installSigilAgentAssets(cwd: string): SigilAgentAssetsResult {
  const sourceDir = resolveSkillsSourceDir();
  const skillsDir = path.join(cwd, ".sigil", "skills");
  const cursorRulePath = path.join(cwd, ".cursor", "rules", "sigil-skills.mdc");

  fs.ensureDirSync(path.dirname(skillsDir));
  fs.emptyDirSync(skillsDir);
  fs.copySync(sourceDir, skillsDir, { overwrite: true });

  fs.ensureDirSync(path.dirname(cursorRulePath));
  fs.writeFileSync(cursorRulePath, generateCursorSkillsRule(), "utf-8");

  return {
    skillsDir,
    cursorRulePath,
    installedSkillCount: SIGIL_SKILLS.length,
  };
}

export function getMissingSigilSkillFiles(cwd: string): string[] {
  const missing: string[] = [];

  for (const skill of SIGIL_SKILLS) {
    for (const file of skill.files) {
      const relativePath = path.join(".sigil", "skills", skill.id, file);
      if (!fs.existsSync(path.join(cwd, relativePath))) {
        missing.push(relativePath.replaceAll(path.sep, "/"));
      }
    }
  }

  return missing;
}

export function hasSigilCursorRule(cwd: string): boolean {
  return fs.existsSync(path.join(cwd, ".cursor", "rules", "sigil-skills.mdc"));
}

export function generateRequiredSkillsSection(): string {
  const rows = SIGIL_SKILLS
    .map((skill) => `| ${skill.task} | \`.sigil/skills/${skill.id}/SKILL.md\` | ${skill.trigger} |`)
    .join("\n");

  return `## Required Skills

Before changing a Sigil project, pick the relevant skill and read it first:

| Task | Skill File | Use When |
|------|------------|----------|
${rows}

If a task spans multiple areas, read every matching skill before editing. The token-first rule still wins: visual changes go through tokens or presets before component files.`;
}

function generateCursorSkillsRule(): string {
  const skillList = SIGIL_SKILLS
    .map((skill) => `- ${skill.task}: read \`.sigil/skills/${skill.id}/SKILL.md\`.`)
    .join("\n");

  return `# Sigil Skills Enforcement

This project uses Sigil UI. These rules are generated by Sigil and should be followed before writing code.

## Required Workflow

1. Read \`.sigil/AGENTS.md\` at the start of any Sigil UI task.
2. Select and read the relevant installed skill before editing:
${skillList}
3. For visual changes, edit the token CSS file or preset. Do not hardcode colors, spacing, fonts, radii, shadows, or durations in components.
4. Run \`npx @sigil-ui/cli doctor\` after Sigil changes when practical.

## Enforcement

- Components must consume \`var(--s-*)\` token variables and Sigil classes.
- Presets and token edits must use OKLCH colors.
- Layout and page work should use the Sigil playbook and layout skills.
- Polish work should use the typography, surfaces, animations, and performance references under \`.sigil/skills/sigil-polish/\`.
`;
}

function resolveSkillsSourceDir(): string {
  const moduleDir = path.dirname(fileURLToPath(import.meta.url));
  const candidates = [
    path.join(moduleDir, "assets", "skills"),
    path.join(moduleDir, "..", "assets", "skills"),
    path.join(moduleDir, "..", "..", "assets", "skills"),
    path.join(moduleDir, "..", "..", "..", "..", "skills"),
  ];

  for (const candidate of candidates) {
    if (fs.existsSync(path.join(candidate, "sigil-tokens", "SKILL.md"))) {
      return candidate;
    }
  }

  throw new Error("Could not find bundled Sigil skills. Rebuild @sigil-ui/cli and try again.");
}
