"use client";

import { forwardRef } from "react";
import type { Icon, IconProps } from "@phosphor-icons/react";
import { AppWindowIcon as AppWindowGlyph } from "@phosphor-icons/react/dist/ssr/AppWindow";
import { ArchiveIcon as ArchiveGlyph } from "@phosphor-icons/react/dist/ssr/Archive";
import { ArrowCounterClockwiseIcon as ArrowCounterClockwiseGlyph } from "@phosphor-icons/react/dist/ssr/ArrowCounterClockwise";
import { ArrowDownIcon as ArrowDownGlyph } from "@phosphor-icons/react/dist/ssr/ArrowDown";
import { ArrowLeftIcon as ArrowLeftGlyph } from "@phosphor-icons/react/dist/ssr/ArrowLeft";
import { ArrowRightIcon as ArrowRightGlyph } from "@phosphor-icons/react/dist/ssr/ArrowRight";
import { ArrowSquareOutIcon as ArrowSquareOutGlyph } from "@phosphor-icons/react/dist/ssr/ArrowSquareOut";
import { ArrowUpIcon as ArrowUpGlyph } from "@phosphor-icons/react/dist/ssr/ArrowUp";
import { ArrowUpRightIcon as ArrowUpRightGlyph } from "@phosphor-icons/react/dist/ssr/ArrowUpRight";
import { ArrowsClockwiseIcon as ArrowsClockwiseGlyph } from "@phosphor-icons/react/dist/ssr/ArrowsClockwise";
import { ArrowsOutLineHorizontalIcon as ArrowsOutLineHorizontalGlyph } from "@phosphor-icons/react/dist/ssr/ArrowsOutLineHorizontal";
import { AtIcon as AtGlyph } from "@phosphor-icons/react/dist/ssr/At";
import { BellIcon as BellGlyph } from "@phosphor-icons/react/dist/ssr/Bell";
import { BookOpenIcon as BookOpenGlyph } from "@phosphor-icons/react/dist/ssr/BookOpen";
import { BroadcastIcon as BroadcastGlyph } from "@phosphor-icons/react/dist/ssr/Broadcast";
import { BrowserIcon as BrowserGlyph } from "@phosphor-icons/react/dist/ssr/Browser";
import { BuildingsIcon as BuildingsGlyph } from "@phosphor-icons/react/dist/ssr/Buildings";
import { CalendarBlankIcon as CalendarBlankGlyph } from "@phosphor-icons/react/dist/ssr/CalendarBlank";
import { CalendarDotsIcon as CalendarDotsGlyph } from "@phosphor-icons/react/dist/ssr/CalendarDots";
import { CaretDownIcon as CaretDownGlyph } from "@phosphor-icons/react/dist/ssr/CaretDown";
import { CaretLeftIcon as CaretLeftGlyph } from "@phosphor-icons/react/dist/ssr/CaretLeft";
import { CaretRightIcon as CaretRightGlyph } from "@phosphor-icons/react/dist/ssr/CaretRight";
import { CaretUpIcon as CaretUpGlyph } from "@phosphor-icons/react/dist/ssr/CaretUp";
import { ChartBarIcon as ChartBarGlyph } from "@phosphor-icons/react/dist/ssr/ChartBar";
import { ChatCircleTextIcon as ChatCircleTextGlyph } from "@phosphor-icons/react/dist/ssr/ChatCircleText";
import { CheckIcon as CheckGlyph } from "@phosphor-icons/react/dist/ssr/Check";
import { CheckCircleIcon as CheckCircleGlyph } from "@phosphor-icons/react/dist/ssr/CheckCircle";
import { CircleIcon as CircleGlyph } from "@phosphor-icons/react/dist/ssr/Circle";
import { ClockIcon as ClockGlyph } from "@phosphor-icons/react/dist/ssr/Clock";
import { CloudArrowUpIcon as CloudArrowUpGlyph } from "@phosphor-icons/react/dist/ssr/CloudArrowUp";
import { CodeIcon as CodeGlyph } from "@phosphor-icons/react/dist/ssr/Code";
import { CodeBlockIcon as CodeBlockGlyph } from "@phosphor-icons/react/dist/ssr/CodeBlock";
import { CompassIcon as CompassGlyph } from "@phosphor-icons/react/dist/ssr/Compass";
import { CopyIcon as CopyGlyph } from "@phosphor-icons/react/dist/ssr/Copy";
import { CpuIcon as CpuGlyph } from "@phosphor-icons/react/dist/ssr/Cpu";
import { CreditCardIcon as CreditCardGlyph } from "@phosphor-icons/react/dist/ssr/CreditCard";
import { CrosshairIcon as CrosshairGlyph } from "@phosphor-icons/react/dist/ssr/Crosshair";
import { CrownIcon as CrownGlyph } from "@phosphor-icons/react/dist/ssr/Crown";
import { CubeIcon as CubeGlyph } from "@phosphor-icons/react/dist/ssr/Cube";
import { CursorIcon as CursorGlyph } from "@phosphor-icons/react/dist/ssr/Cursor";
import { CursorClickIcon as CursorClickGlyph } from "@phosphor-icons/react/dist/ssr/CursorClick";
import { DotsSixVerticalIcon as DotsSixVerticalGlyph } from "@phosphor-icons/react/dist/ssr/DotsSixVertical";
import { DotsThreeIcon as DotsThreeGlyph } from "@phosphor-icons/react/dist/ssr/DotsThree";
import { DownloadSimpleIcon as DownloadSimpleGlyph } from "@phosphor-icons/react/dist/ssr/DownloadSimple";
import { EnvelopeSimpleIcon as EnvelopeSimpleGlyph } from "@phosphor-icons/react/dist/ssr/EnvelopeSimple";
import { EyeIcon as EyeGlyph } from "@phosphor-icons/react/dist/ssr/Eye";
import { FileIcon as FileGlyph } from "@phosphor-icons/react/dist/ssr/File";
import { FileArrowUpIcon as FileArrowUpGlyph } from "@phosphor-icons/react/dist/ssr/FileArrowUp";
import { FileTextIcon as FileTextGlyph } from "@phosphor-icons/react/dist/ssr/FileText";
import { FloppyDiskIcon as FloppyDiskGlyph } from "@phosphor-icons/react/dist/ssr/FloppyDisk";
import { FolderIcon as FolderGlyph } from "@phosphor-icons/react/dist/ssr/Folder";
import { GitBranchIcon as GitBranchGlyph } from "@phosphor-icons/react/dist/ssr/GitBranch";
import { GitCommitIcon as GitCommitGlyph } from "@phosphor-icons/react/dist/ssr/GitCommit";
import { GitPullRequestIcon as GitPullRequestGlyph } from "@phosphor-icons/react/dist/ssr/GitPullRequest";
import { GlobeHemisphereWestIcon as GlobeHemisphereWestGlyph } from "@phosphor-icons/react/dist/ssr/GlobeHemisphereWest";
import { GridNineIcon as GridNineGlyph } from "@phosphor-icons/react/dist/ssr/GridNine";
import { HardDriveIcon as HardDriveGlyph } from "@phosphor-icons/react/dist/ssr/HardDrive";
import { HardDrivesIcon as HardDrivesGlyph } from "@phosphor-icons/react/dist/ssr/HardDrives";
import { HeartIcon as HeartGlyph } from "@phosphor-icons/react/dist/ssr/Heart";
import { ImageIcon as ImageGlyph } from "@phosphor-icons/react/dist/ssr/Image";
import { InfoIcon as InfoGlyph } from "@phosphor-icons/react/dist/ssr/Info";
import { IntersectIcon as IntersectGlyph } from "@phosphor-icons/react/dist/ssr/Intersect";
import { LightningIcon as LightningGlyph } from "@phosphor-icons/react/dist/ssr/Lightning";
import { LinkIcon as LinkGlyph } from "@phosphor-icons/react/dist/ssr/Link";
import { ListIcon as ListGlyph } from "@phosphor-icons/react/dist/ssr/List";
import { MagnifyingGlassIcon as MagnifyingGlassGlyph } from "@phosphor-icons/react/dist/ssr/MagnifyingGlass";
import { MinusIcon as MinusGlyph } from "@phosphor-icons/react/dist/ssr/Minus";
import { MonitorIcon as MonitorGlyph } from "@phosphor-icons/react/dist/ssr/Monitor";
import { MoonIcon as MoonGlyph } from "@phosphor-icons/react/dist/ssr/Moon";
import { PackageIcon as PackageGlyph } from "@phosphor-icons/react/dist/ssr/Package";
import { PaintBrushIcon as PaintBrushGlyph } from "@phosphor-icons/react/dist/ssr/PaintBrush";
import { PaletteIcon as PaletteGlyph } from "@phosphor-icons/react/dist/ssr/Palette";
import { PaperPlaneTiltIcon as PaperPlaneTiltGlyph } from "@phosphor-icons/react/dist/ssr/PaperPlaneTilt";
import { PlusIcon as PlusGlyph } from "@phosphor-icons/react/dist/ssr/Plus";
import { RectangleIcon as RectangleGlyph } from "@phosphor-icons/react/dist/ssr/Rectangle";
import { RocketLaunchIcon as RocketLaunchGlyph } from "@phosphor-icons/react/dist/ssr/RocketLaunch";
import { RowsIcon as RowsGlyph } from "@phosphor-icons/react/dist/ssr/Rows";
import { RulerIcon as RulerGlyph } from "@phosphor-icons/react/dist/ssr/Ruler";
import { ScanIcon as ScanGlyph } from "@phosphor-icons/react/dist/ssr/Scan";
import { SelectionSlashIcon as SelectionSlashGlyph } from "@phosphor-icons/react/dist/ssr/SelectionSlash";
import { ShieldIcon as ShieldGlyph } from "@phosphor-icons/react/dist/ssr/Shield";
import { ShieldCheckIcon as ShieldCheckGlyph } from "@phosphor-icons/react/dist/ssr/ShieldCheck";
import { ShuffleIcon as ShuffleGlyph } from "@phosphor-icons/react/dist/ssr/Shuffle";
import { SidebarIcon as SidebarGlyph } from "@phosphor-icons/react/dist/ssr/Sidebar";
import { SidebarSimpleIcon as SidebarSimpleGlyph } from "@phosphor-icons/react/dist/ssr/SidebarSimple";
import { SlidersHorizontalIcon as SlidersHorizontalGlyph } from "@phosphor-icons/react/dist/ssr/SlidersHorizontal";
import { SparkleIcon as SparkleGlyph } from "@phosphor-icons/react/dist/ssr/Sparkle";
import { SpeakerHighIcon as SpeakerHighGlyph } from "@phosphor-icons/react/dist/ssr/SpeakerHigh";
import { SpeakerSlashIcon as SpeakerSlashGlyph } from "@phosphor-icons/react/dist/ssr/SpeakerSlash";
import { SpinnerGapIcon as SpinnerGapGlyph } from "@phosphor-icons/react/dist/ssr/SpinnerGap";
import { SquareIcon as SquareGlyph } from "@phosphor-icons/react/dist/ssr/Square";
import { SquareSplitVerticalIcon as SquareSplitVerticalGlyph } from "@phosphor-icons/react/dist/ssr/SquareSplitVertical";
import { SquaresFourIcon as SquaresFourGlyph } from "@phosphor-icons/react/dist/ssr/SquaresFour";
import { StackIcon as StackGlyph } from "@phosphor-icons/react/dist/ssr/Stack";
import { StarIcon as StarGlyph } from "@phosphor-icons/react/dist/ssr/Star";
import { SunIcon as SunGlyph } from "@phosphor-icons/react/dist/ssr/Sun";
import { TerminalWindowIcon as TerminalWindowGlyph } from "@phosphor-icons/react/dist/ssr/TerminalWindow";
import { TextAlignCenterIcon as TextAlignCenterGlyph } from "@phosphor-icons/react/dist/ssr/TextAlignCenter";
import { TextAlignLeftIcon as TextAlignLeftGlyph } from "@phosphor-icons/react/dist/ssr/TextAlignLeft";
import { TextAlignRightIcon as TextAlignRightGlyph } from "@phosphor-icons/react/dist/ssr/TextAlignRight";
import { TextBIcon as TextBGlyph } from "@phosphor-icons/react/dist/ssr/TextB";
import { TextHIcon as TextHGlyph } from "@phosphor-icons/react/dist/ssr/TextH";
import { TextItalicIcon as TextItalicGlyph } from "@phosphor-icons/react/dist/ssr/TextItalic";
import { TextStrikethroughIcon as TextStrikethroughGlyph } from "@phosphor-icons/react/dist/ssr/TextStrikethrough";
import { TextTIcon as TextTGlyph } from "@phosphor-icons/react/dist/ssr/TextT";
import { TextUnderlineIcon as TextUnderlineGlyph } from "@phosphor-icons/react/dist/ssr/TextUnderline";
import { TextboxIcon as TextboxGlyph } from "@phosphor-icons/react/dist/ssr/Textbox";
import { TrashIcon as TrashGlyph } from "@phosphor-icons/react/dist/ssr/Trash";
import { UploadSimpleIcon as UploadSimpleGlyph } from "@phosphor-icons/react/dist/ssr/UploadSimple";
import { WaveformIcon as WaveformGlyph } from "@phosphor-icons/react/dist/ssr/Waveform";
import { WifiHighIcon as WifiHighGlyph } from "@phosphor-icons/react/dist/ssr/WifiHigh";
import { XIcon as XGlyph } from "@phosphor-icons/react/dist/ssr/X";

/** Product icon language: filled Phosphor glyphs, inherited color, token sizing. */
function solidIcon(Glyph: Icon, name: string) {
  const Component = forwardRef<SVGSVGElement, IconProps>(function SolidIcon({ size = "var(--s-control-icon-size)", weight = "fill", className, ...props }, ref) {
    return <Glyph ref={ref} size={size} weight={weight} focusable="false"
      aria-hidden={props["aria-label"] || props.alt ? undefined : true}
      data-sigil-icon={name} className={className ? `sigil-icon ${className}` : "sigil-icon"} {...props} />;
  });
  Component.displayName = `${name}Icon`;
  return Component;
}

export const AlignCenter = /* @__PURE__ */ solidIcon(TextAlignCenterGlyph, "AlignCenter");
export const AlignLeft = /* @__PURE__ */ solidIcon(TextAlignLeftGlyph, "AlignLeft");
export const AlignRight = /* @__PURE__ */ solidIcon(TextAlignRightGlyph, "AlignRight");
export const Archive = /* @__PURE__ */ solidIcon(ArchiveGlyph, "Archive");
export const ArrowDown = /* @__PURE__ */ solidIcon(ArrowDownGlyph, "ArrowDown");
export const ArrowLeft = /* @__PURE__ */ solidIcon(ArrowLeftGlyph, "ArrowLeft");
export const ArrowRight = /* @__PURE__ */ solidIcon(ArrowRightGlyph, "ArrowRight");
export const ArrowUp = /* @__PURE__ */ solidIcon(ArrowUpGlyph, "ArrowUp");
export const ArrowUpRight = /* @__PURE__ */ solidIcon(ArrowUpRightGlyph, "ArrowUpRight");
export const AtSign = /* @__PURE__ */ solidIcon(AtGlyph, "AtSign");
export const AudioLines = /* @__PURE__ */ solidIcon(WaveformGlyph, "AudioLines");
export const BarChart3 = /* @__PURE__ */ solidIcon(ChartBarGlyph, "BarChart3");
export const Bell = /* @__PURE__ */ solidIcon(BellGlyph, "Bell");
export const Blend = /* @__PURE__ */ solidIcon(IntersectGlyph, "Blend");
export const Bold = /* @__PURE__ */ solidIcon(TextBGlyph, "Bold");
export const BookOpen = /* @__PURE__ */ solidIcon(BookOpenGlyph, "BookOpen");
export const Box = /* @__PURE__ */ solidIcon(CubeGlyph, "Box");
export const Building2 = /* @__PURE__ */ solidIcon(BuildingsGlyph, "Building2");
export const Calendar = /* @__PURE__ */ solidIcon(CalendarBlankGlyph, "Calendar");
export const CalendarDays = /* @__PURE__ */ solidIcon(CalendarDotsGlyph, "CalendarDays");
export const Check = /* @__PURE__ */ solidIcon(CheckGlyph, "Check");
export const CheckCircle2 = /* @__PURE__ */ solidIcon(CheckCircleGlyph, "CheckCircle2");
export const ChevronDown = /* @__PURE__ */ solidIcon(CaretDownGlyph, "ChevronDown");
export const ChevronLeft = /* @__PURE__ */ solidIcon(CaretLeftGlyph, "ChevronLeft");
export const ChevronRight = /* @__PURE__ */ solidIcon(CaretRightGlyph, "ChevronRight");
export const ChevronUp = /* @__PURE__ */ solidIcon(CaretUpGlyph, "ChevronUp");
export const Circle = /* @__PURE__ */ solidIcon(CircleGlyph, "Circle");
export const CircleCheck = /* @__PURE__ */ solidIcon(CheckCircleGlyph, "CircleCheck");
export const CircleCheckBig = /* @__PURE__ */ solidIcon(CheckCircleGlyph, "CircleCheckBig");
export const Clock = /* @__PURE__ */ solidIcon(ClockGlyph, "Clock");
export const CloudUpload = /* @__PURE__ */ solidIcon(CloudArrowUpGlyph, "CloudUpload");
export const Code = /* @__PURE__ */ solidIcon(CodeGlyph, "Code");
export const Code2 = /* @__PURE__ */ solidIcon(CodeBlockGlyph, "Code2");
export const Compass = /* @__PURE__ */ solidIcon(CompassGlyph, "Compass");
export const Copy = /* @__PURE__ */ solidIcon(CopyGlyph, "Copy");
export const Cpu = /* @__PURE__ */ solidIcon(CpuGlyph, "Cpu");
export const CreditCard = /* @__PURE__ */ solidIcon(CreditCardGlyph, "CreditCard");
export const Crosshair = /* @__PURE__ */ solidIcon(CrosshairGlyph, "Crosshair");
export const Crown = /* @__PURE__ */ solidIcon(CrownGlyph, "Crown");
export const Download = /* @__PURE__ */ solidIcon(DownloadSimpleGlyph, "Download");
export const ExternalLink = /* @__PURE__ */ solidIcon(ArrowSquareOutGlyph, "ExternalLink");
export const Eye = /* @__PURE__ */ solidIcon(EyeGlyph, "Eye");
export const File = /* @__PURE__ */ solidIcon(FileGlyph, "File");
export const FileText = /* @__PURE__ */ solidIcon(FileTextGlyph, "FileText");
export const FileUp = /* @__PURE__ */ solidIcon(FileArrowUpGlyph, "FileUp");
export const Focus = /* @__PURE__ */ solidIcon(ScanGlyph, "Focus");
export const Folder = /* @__PURE__ */ solidIcon(FolderGlyph, "Folder");
export const GitBranch = /* @__PURE__ */ solidIcon(GitBranchGlyph, "GitBranch");
export const GitCommitHorizontal = /* @__PURE__ */ solidIcon(GitCommitGlyph, "GitCommitHorizontal");
export const GitPullRequest = /* @__PURE__ */ solidIcon(GitPullRequestGlyph, "GitPullRequest");
export const Globe = /* @__PURE__ */ solidIcon(GlobeHemisphereWestGlyph, "Globe");
export const Grid3X3 = /* @__PURE__ */ solidIcon(GridNineGlyph, "Grid3X3");
export const GripVertical = /* @__PURE__ */ solidIcon(DotsSixVerticalGlyph, "GripVertical");
export const HardDrive = /* @__PURE__ */ solidIcon(HardDriveGlyph, "HardDrive");
export const Heading = /* @__PURE__ */ solidIcon(TextHGlyph, "Heading");
export const Heart = /* @__PURE__ */ solidIcon(HeartGlyph, "Heart");
export const Image = /* @__PURE__ */ solidIcon(ImageGlyph, "Image");
export const ImageIcon = /* @__PURE__ */ solidIcon(ImageGlyph, "ImageIcon");
export const Info = /* @__PURE__ */ solidIcon(InfoGlyph, "Info");
export const Italic = /* @__PURE__ */ solidIcon(TextItalicGlyph, "Italic");
export const Layers = /* @__PURE__ */ solidIcon(StackGlyph, "Layers");
export const LayoutGrid = /* @__PURE__ */ solidIcon(SquaresFourGlyph, "LayoutGrid");
export const Link = /* @__PURE__ */ solidIcon(LinkGlyph, "Link");
export const Loader2 = /* @__PURE__ */ solidIcon(SpinnerGapGlyph, "Loader2");
export const Mail = /* @__PURE__ */ solidIcon(EnvelopeSimpleGlyph, "Mail");
export const Menu = /* @__PURE__ */ solidIcon(ListGlyph, "Menu");
export const MessageSquare = /* @__PURE__ */ solidIcon(ChatCircleTextGlyph, "MessageSquare");
export const Minus = /* @__PURE__ */ solidIcon(MinusGlyph, "Minus");
export const Monitor = /* @__PURE__ */ solidIcon(MonitorGlyph, "Monitor");
export const Moon = /* @__PURE__ */ solidIcon(MoonGlyph, "Moon");
export const MoreHorizontal = /* @__PURE__ */ solidIcon(DotsThreeGlyph, "MoreHorizontal");
export const MousePointer = /* @__PURE__ */ solidIcon(CursorGlyph, "MousePointer");
export const MousePointerClick = /* @__PURE__ */ solidIcon(CursorClickGlyph, "MousePointerClick");
export const Package = /* @__PURE__ */ solidIcon(PackageGlyph, "Package");
export const Paintbrush = /* @__PURE__ */ solidIcon(PaintBrushGlyph, "Paintbrush");
export const Palette = /* @__PURE__ */ solidIcon(PaletteGlyph, "Palette");
export const PanelBottom = /* @__PURE__ */ solidIcon(SquareSplitVerticalGlyph, "PanelBottom");
export const PanelLeft = /* @__PURE__ */ solidIcon(SidebarSimpleGlyph, "PanelLeft");
export const PanelRight = /* @__PURE__ */ solidIcon(SidebarGlyph, "PanelRight");
export const PanelTop = /* @__PURE__ */ solidIcon(BrowserGlyph, "PanelTop");
export const PanelsTopLeft = /* @__PURE__ */ solidIcon(AppWindowGlyph, "PanelsTopLeft");
export const Plus = /* @__PURE__ */ solidIcon(PlusGlyph, "Plus");
export const Radio = /* @__PURE__ */ solidIcon(BroadcastGlyph, "Radio");
export const RectangleHorizontal = /* @__PURE__ */ solidIcon(RectangleGlyph, "RectangleHorizontal");
export const RefreshCw = /* @__PURE__ */ solidIcon(ArrowsClockwiseGlyph, "RefreshCw");
export const Rocket = /* @__PURE__ */ solidIcon(RocketLaunchGlyph, "Rocket");
export const RotateCcw = /* @__PURE__ */ solidIcon(ArrowCounterClockwiseGlyph, "RotateCcw");
export const Rows3 = /* @__PURE__ */ solidIcon(RowsGlyph, "Rows3");
export const Ruler = /* @__PURE__ */ solidIcon(RulerGlyph, "Ruler");
export const Save = /* @__PURE__ */ solidIcon(FloppyDiskGlyph, "Save");
export const Search = /* @__PURE__ */ solidIcon(MagnifyingGlassGlyph, "Search");
export const Send = /* @__PURE__ */ solidIcon(PaperPlaneTiltGlyph, "Send");
export const Server = /* @__PURE__ */ solidIcon(HardDrivesGlyph, "Server");
export const Shield = /* @__PURE__ */ solidIcon(ShieldGlyph, "Shield");
export const ShieldCheck = /* @__PURE__ */ solidIcon(ShieldCheckGlyph, "ShieldCheck");
export const Shuffle = /* @__PURE__ */ solidIcon(ShuffleGlyph, "Shuffle");
export const SlidersHorizontal = /* @__PURE__ */ solidIcon(SlidersHorizontalGlyph, "SlidersHorizontal");
export const Space = /* @__PURE__ */ solidIcon(ArrowsOutLineHorizontalGlyph, "Space");
export const Sparkles = /* @__PURE__ */ solidIcon(SparkleGlyph, "Sparkles");
export const Square = /* @__PURE__ */ solidIcon(SquareGlyph, "Square");
export const SquareSlash = /* @__PURE__ */ solidIcon(SelectionSlashGlyph, "SquareSlash");
export const Star = /* @__PURE__ */ solidIcon(StarGlyph, "Star");
export const Strikethrough = /* @__PURE__ */ solidIcon(TextStrikethroughGlyph, "Strikethrough");
export const Sun = /* @__PURE__ */ solidIcon(SunGlyph, "Sun");
export const Terminal = /* @__PURE__ */ solidIcon(TerminalWindowGlyph, "Terminal");
export const TextCursorInput = /* @__PURE__ */ solidIcon(TextboxGlyph, "TextCursorInput");
export const Trash2 = /* @__PURE__ */ solidIcon(TrashGlyph, "Trash2");
export const Type = /* @__PURE__ */ solidIcon(TextTGlyph, "Type");
export const Underline = /* @__PURE__ */ solidIcon(TextUnderlineGlyph, "Underline");
export const Upload = /* @__PURE__ */ solidIcon(UploadSimpleGlyph, "Upload");
export const Volume2 = /* @__PURE__ */ solidIcon(SpeakerHighGlyph, "Volume2");
export const VolumeX = /* @__PURE__ */ solidIcon(SpeakerSlashGlyph, "VolumeX");
export const Wifi = /* @__PURE__ */ solidIcon(WifiHighGlyph, "Wifi");
export const X = /* @__PURE__ */ solidIcon(XGlyph, "X");
export const Zap = /* @__PURE__ */ solidIcon(LightningGlyph, "Zap");
