import { defineConfig } from "tsup";

export default defineConfig({
  entry: [
    "src/index.ts",
    "src/catalog.ts",
    "src/sigil.ts",
    "src/crux.ts",
    "src/alloy.ts",
    "src/basalt.ts",
    "src/forge.ts",
    "src/onyx.ts",
    "src/flux.ts",
    "src/kova.ts",
    "src/etch.ts",
    "src/anvil.ts",
    "src/rivet.ts",
    "src/shard.ts",
    "src/rune.ts",
    "src/fang.ts",
    "src/cobalt.ts",
    "src/strata.ts",
    "src/brass.ts",
    "src/obsid.ts",
    "src/axiom.ts",
    "src/glyph.ts",
    "src/cipher.ts",
    "src/prism.ts",
    "src/helix.ts",
    "src/hex.ts",
    "src/vex.ts",
    "src/arc.ts",
    "src/dsgn.ts",
    "src/mrkr.ts",
    "src/noir.ts",
    "src/dusk.ts",
    "src/mono.ts",
    "src/vast.ts",
    "src/aura.ts",
    "src/field.ts",
    "src/clay.ts",
    "src/sage.ts",
    "src/ink.ts",
    "src/sand.ts",
    "src/plum.ts",
    "src/moss.ts",
    "src/coral.ts",
    "src/dune.ts",
    "src/ocean.ts",
    "src/rose.ts",
  ],
  format: ["esm", "cjs"],
  dts: true,
  splitting: false,
  sourcemap: true,
  clean: true,
  treeshake: true,
  outDir: "dist",
});
