import fs from "fs-extra";
import path from "node:path";
import { fileURLToPath } from "node:url";

export type SigilSkill = {
  id: string;
  task: string;
  trigger: string;
  files: string[];
};

export const SIGIL_SKILLS: SigilSkill[] = [
  {
    id: "sigil-tokens",
    task: "Edit or debug design tokens",
    trigger: "colors, fonts, spacing, radius, shadows, motion, token CSS",
    files: ["SKILL.md"],
  },
  {
    id: "sigil-preset",
    task: "Create, modify, or choose presets",
    trigger: "new theme, preset creation, visual identity changes",
    files: ["SKILL.md"],
  },
  {
    id: "sigil-design",
    task: "Generate, compile, or audit a DESIGN.md spec",
    trigger: "DESIGN.md, design extraction, compile to CSS/Tailwind/W3C JSON",
    files: ["SKILL.md"],
  },
  {
    id: "sigil-messaging",
    task: "Write or update copy, READMEs, marketing, and stats",
    trigger: "README, docs copy, llms.txt, marketing pages, positioning",
    files: ["SKILL.md"],
  },
  {
    id: "sigil-component",
    task: "Create, modify, or review components",
    trigger: "component source, variants, registry entries, exports",
    files: ["SKILL.md"],
  },
  {
    id: "sigil-layout",
    task: "Compose layouts and grid structures",
    trigger: "page layout, sections, grids, rails, app shells",
    files: ["SKILL.md"],
  },
  {
    id: "sigil-playbook",
    task: "Build full pages in the Sigil aesthetic",
    trigger: "landing pages, dashboards, docs pages, page composition",
    files: ["SKILL.md"],
  },
  {
    id: "sigil-migration",
    task: "Migrate from shadcn/ui or another design system",
    trigger: "migration, compatibility layer, replacing shadcn components",
    files: ["SKILL.md"],
  },
  {
    id: "sigil-polish",
    task: "Polish visual details and interactions",
    trigger: "typography, surfaces, animations, performance, micro-interactions",
    files: ["SKILL.md", "typography.md", "surfaces.md", "animations.md", "performance.md"],
  },
  {
    id: "sigil-audit",
    task: "Run browser + static audits over the component library",
    trigger: "audit components, visual regression, doc-vs-showcase reconciliation",
    files: ["SKILL.md"],
  },
];

export function installSigilAgentAssets(cwd: string): number {
  const skillsDir = path.join(cwd, ".sigil", "skills");
  fs.ensureDirSync(path.dirname(skillsDir));
  fs.emptyDirSync(skillsDir);
  fs.copySync(resolveSkillsSourceDir(), skillsDir, { overwrite: true });
  fs.ensureDirSync(path.join(cwd, ".cursor", "rules"));
  fs.writeFileSync(
    path.join(cwd, ".cursor", "rules", "sigil-skills.mdc"),
    generateCursorSkillsRule(),
    "utf-8",
  );
  return SIGIL_SKILLS.length;
}

export function generateRequiredSkillsSection(): string {
  const rows = SIGIL_SKILLS
    .map((skill) => `| ${skill.task} | \`.sigil/skills/${skill.id}/SKILL.md\` | ${skill.trigger} |`)
    .join("\n");

  return `## Required Skills

Before changing a Sigil project, pick the relevant skill and read it first:

| Task | Skill File | Use When |
|------|------------|----------|
${rows}

If a task spans multiple areas, read every matching skill before editing. The token-first rule still wins: visual changes go through tokens or presets before component files.`;
}

function generateCursorSkillsRule(): string {
  const skillList = SIGIL_SKILLS
    .map((skill) => `- ${skill.task}: read \`.sigil/skills/${skill.id}/SKILL.md\`.`)
    .join("\n");

  return `# Sigil Skills Enforcement

This project uses Sigil UI. These rules are generated by Sigil and should be followed before writing code.

## Required Workflow

1. Read \`.sigil/AGENTS.md\` at the start of any Sigil UI task.
2. Select and read the relevant installed skill before editing:
${skillList}
3. For visual changes, edit the token CSS file or preset. Do not hardcode colors, spacing, fonts, radii, shadows, or durations in components.
4. Run \`npx @sigil-ui/cli doctor\` after Sigil changes when practical.

## Enforcement

- Components must consume \`var(--s-*)\` token variables and Sigil classes.
- Presets and token edits must use OKLCH colors.
- Layout and page work should use the Sigil playbook and layout skills.
- Polish work should use the typography, surfaces, animations, and performance references under \`.sigil/skills/sigil-polish/\`.
`;
}

function resolveSkillsSourceDir(): string {
  const moduleDir = path.dirname(fileURLToPath(import.meta.url));
  const candidates = [
    path.join(moduleDir, "assets", "skills"),
    path.join(moduleDir, "..", "assets", "skills"),
    path.join(moduleDir, "..", "..", "..", "skills"),
  ];

  for (const candidate of candidates) {
    if (fs.existsSync(path.join(candidate, "sigil-tokens", "SKILL.md"))) {
      return candidate;
    }
  }

  throw new Error("Could not find bundled Sigil skills. Rebuild create-sigil-app and try again.");
}
